### ISSUE TITLE
ICY metadata charset

### ISSUE THREAD

**Issue by Phaet** [MusicPlayerDaemon/MPD#1002]
I am listening to internet radio stations using Moode and are currently collaborating in their version 7.0.0.

I noticed that for some radio stations the meta data for the current title is not send as UTF-8, but ISO-8859-1. Characters like German umlauts are displayed as question marks. Appending the URL with #charset=ISO-8859-1 does indeed help as described in the mpd user manual, section ICY-MetaData.

The default charset for mp3 stream metadata from Icecast is ISO-8859-1 since a while and UTF-8 only for ogg streams.

In Icecast 2.3.2 was introduced a charset parameter to be used with the http meta data request. As far as I understood the docs the meta data are then converted to the requested charset.
So setting this parameter to UTF-8 should do the job regardless how the source clients have been configured.

Unfortunately I do not have the means to test it myself.
So could you please look into this issue?

Danke und Grüße aus dem Schwarzwald :-)

**Comment by MaxKellermann** [comment]
Where is documentation on this new protocol?

**Comment by Phaet** [comment]
I found the info in the 2.3.2 release notes:

https://icecast.org/news/icecast-release-2_3_2/

Changes

Character set support. Most non-Ogg streams (eg MP3) send metadata as Latin1 but it could be in other character sets.
As icecast uses UTF-8, we need to convert to UTF-8 so that web pages and stream directories render correctly.

Allow a per-mount <charset> setting. For when source clients do not indicate which character set is in use.

A charset= parameter to the metadata request.

Default for non-Ogg content is now Latin-1 (aka ISO-8859-1). Ogg content still uses UTF-8.



But I can't find any documentation at all which deals with the HTTP/ICY protocol

**Comment by MaxKellermann** [comment]
And... what exactly do you request MPD to do? Your initial text is very unspecific.

**Comment by Phaet** [comment]
As said, I cannot find any protocol spec bar some second hand info.

I think that the charset parameter introduced in  2.3.2 works like:

PUT/SOURCE request
.
.
Icy-MetaData:1
**Icy-Charset: UTF-8** 
.
.


The syntax is a wild guess.
This should solve the charset ambiguities so that Icecast always sends the meta-info in UTF-8 regardless of the source client settings.

This is what I'd like to ask you whether yoh could make a quick test to prove this assumption and then possibly implement it in mpd.

If I knew an Icecast server with telnet access, I would try it myself.

**Comment by MaxKellermann** [comment]
I repeat: what exactly do you request MPD to do?

**Comment by Phaet** [comment]
I just talkex to somebody from Icecast via IRC. He told me that this charset= is only on source client side at not with the ICY request.
What is true that for mp3 the metadata are sent as 8859-1 by default. Nothing could be done on streaming client side to change what Icecast sends.
He recommends to use "some charset guessing library".

So do you think you could improve something to translate the charset in case.

Otherwise we need to get along with the URL parameter.

**Comment by MaxKellermann** [comment]
Too bad Icecast doesn't allow clients to choose a charset.
No, MPD will not attempt to guess the charset, because that's error prone.
