### ISSUE TITLE
Playback Speed MacOS

### ISSUE THREAD

**Issue by JohWl** [MusicPlayerDaemon/MPD#1005]
### Describe the bug
Playback speed constantly changes, could be CPU speed related.
Config:
audio_output {
    type                  "osx"
    name                  "CoreAudio"
}

bind_to_address         "localhost"
port                    "6600"

## Expected Behavior
Constant playback speed.

## Actual Behavior
See above.

## Version

Music Player Daemon 0.22.2 (0.22.2)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local nfs curl

Neighbor plugins:
 upnp

Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe ao openal osx httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg nfs

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// nfs:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// smb:// srtp://

Other features:
 icu ipv6 tcp un

## Log

No log entries made when speed changes.

**Comment by MaxKellermann** [comment]
What is the latest MPD version which worked as expected?
MPD doesn't control the playback speed; it's the macOS audio driver who does, and who requests more data from MPD. (@Wang-Yue do you have an idea what could cause this?)
What is your output configuration? A verbose log of the start of playback could be useful.

**Comment by JohWl** [comment]
I think something like 0.20, but I really do not have the time to compile and test this, I installed via Brew.
Verbose log of startup and playback start:

Nov 11 13:33 : libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
Nov 11 13:33 : vorbis: Xiph.Org libVorbis 1.3.7
Nov 11 13:33 : opus: libopus 1.3.1
Nov 11 13:33 : sndfile: libsndfile-1.0.30
Nov 11 13:33 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Nov 11 13:33 : simple_db: reading DB
Nov 11 13:33 : curl: version 7.64.1
Nov 11 13:33 : curl: with (SecureTransport) LibreSSL/2.8.3
Nov 11 13:33 : state_file: Loading state file /var/lib/mpd/mpdstate
Nov 11 13:33 : playlist: queue song 1:"...mp3"
Nov 11 13:33 : decoder_thread: probing plugin ffmpeg
Nov 11 13:33 : ffmpeg/mp3: Format mp3 probed with size=8192 and score=51
Nov 11 13:33 : ffmpeg/mp3: pad 576 843
Nov 11 13:33 : ffmpeg/mp3: Skipping 0 bytes of junk at 2432.
Nov 11 13:33 : ffmpeg: detected input format 'mp3' (MP2/3 (MPEG audio layer 2/3))
Nov 11 13:33 : ffmpeg/mp3: Before avformat_find_stream_info() pos: 2432 bytes read:8192 seeks:0 nb_streams:1
Nov 11 13:33 : ffmpeg/mp3: demuxer injecting skip 1105 / discard 0
Nov 11 13:33 : ffmpeg/mp3float: skip 1105 / discard 0 samples due to side data
Nov 11 13:33 : ffmpeg/mp3float: skip 1105/1152 samples
Nov 11 13:33 : ffmpeg/mp3: All info found
Nov 11 13:33 : ffmpeg/mp3: stream 0: start_time: 0.0230208 duration: 309.024
Nov 11 13:33 : ffmpeg/mp3: format: start_time: 0.023021 duration: 309.024 (estimate from stream) bitrate=160 kb/s
Nov 11 13:33 : ffmpeg/mp3: After avformat_find_stream_info() pos: 27008 bytes read:32768 seeks:0 frames:50
Nov 11 13:33 : ffmpeg: codec 'mp3'
Nov 11 13:33 : decoder: audio_format=48000:f:2, seekable=true
Nov 11 13:33 : ffmpeg/mp3: demuxer injecting skip 1105 / discard 0
Nov 11 13:33 : client: [0] opened from [::1]:55979
Nov 11 13:33 : client: [0] process command "play"
Nov 11 13:33 : osx_output: Format: 2 channel mixable interleaved 16-bit SInt LE (48000Hz) rated 2512.000000
Nov 11 13:33 : osx_output: Format: 2 channel mixable interleaved 16-bit SInt LE (44100Hz) rated 512.000000
Nov 11 13:33 : output: opened "CoreAudio" (osx) audio_format=48000:f:2
Nov 11 13:33 : client: [0] command returned 0
Nov 11 13:33 : client: [0] process command list
Nov 11 13:33 : client: process command "status"
Nov 11 13:33 : client: command returned 0
Nov 11 13:33 : client: process command "currentsong"
Nov 11 13:33 : client: command returned 0
Nov 11 13:33 : client: [0] process command list returned 0
Nov 11 13:33 : client: [0] closed

**Comment by MaxKellermann** [comment]
I really do not have the time for your issue if you don't have time to do research for your own issue.
Remember, you don't pay me to spend time on your issue. And you have the guts to tell me you don't have time.

**Comment by jasonm23** [comment]
Gee whiz, the nerve.  I have this problem also.  However I have time to report / check as needed.  

May I request the issue be reopened.

**Comment by jasonm23** [comment]
My notes/status so far.

mpd: stable 0.23.8

This seems to happen at random, I haven't been able to trap it yet.

For now I'm restarting the mpd service to fix playback speed.

Installed via Homebrew, 0.23.8  (bottled), HEAD

Running via `brew service start mpd`
