### ISSUE TITLE
Undesired Virtual folders from CUE file

### ISSUE THREAD

**Issue by h-2** [MusicPlayerDaemon/MPD#1006]
## Question

MPD that I usually use through ncmpcpp (and sometimes cantata) has recently started displaying my CUE files as "virtual folders" (not just playlists). While this is a nice feature if one has single-file FLACs, I always split mine. But now I get all songs in the list twice -- once through the actual filename and once through the additional folder created by the cue.

How can I prevent that? Or is this possibly a "feature" of newer ncmpcpp?

**Comment by MaxKellermann** [comment]
See https://www.musicpd.org/doc/html/user.html#configuring-playlist-plugins setting `as_directory`.

**Comment by h-2** [comment]
Thank you for the quick reply!

I have added:
```
playlist_plugin {
    name "cue"
    enabled "true"
    as_directory "false"
}
```
to the config, restarted the server and updated the collection, but the cue still appear as directories. This is in ncmpcpp and cantata, so I think it's a server issue.

musicpd-0.22.1_1 on FreeBSD-12.1

Thanks for your help on this.

**Comment by MaxKellermann** [comment]
Before you request support, you should make sure you have the latest MPD version. 0.22.1 is too old.

**Comment by h-2** [comment]
I am on `musicpd-0.22.3` now (which is only two patch levels higher btw). The behaviour is the same.
