### ISSUE TITLE
Mpd, Home Assistant och ID3Tag.

### ISSUE THREAD

**Issue by AcidSleeper** [MusicPlayerDaemon/MPD#1008]
## Question
Hello
In running a Mpd server and integration to HA. Play, pause, volume and so on. 
But Im missing coverarts.

I would be great if it is possible to show coverarts from songfiles (mp3...).
Is it possible and how do I do it?

Or is this a request to HA-integration?

**Comment by MaxKellermann** [comment]
Yes, it's possible. MPD can read cover art from MP3 files, and send it to the client on request.

**Comment by AcidSleeper** [comment]
But how? 
I cant find it anywhere om how to do it!

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/html/protocol.html#the-music-database
