### ISSUE TITLE
"Art" tag in Icecast/Shoutcast streams

### ISSUE THREAD

**Issue by Phaet** [MusicPlayerDaemon/MPD#1011]
I was wondering how streaming clients display station logos, cover art, artist pictures, etc. synchroniously with each new title.
I found out that the links to the image files are sent as part of the metadata as art tag.
This depends probably from the station and how the source client is configured. But many stations do so.

[icecast-shoutcast-metadata-grabber](https://github.com/cryptiksouls/icecast-shoutcast-metadata-grabber) has a nice demo on the bottom of the readme where one can watch the tags comming in from a radio stream, including the art tag.

Would be good if the currentsong cmd would pass over this tags in its response (and others which may be missing too).

Thanks

**Comment by MaxKellermann** [comment]
I wrote:
> If you want MPD to support it, submit a feature request with a link to the formal specification for each codec.

But your feature request does not contain a link to the formal specification of each codec.

**Comment by Phaet** [comment]
It seems that I have been taken in by outdated information. But I still do not know how artwork is passed in Icecast/Shoutcast streams. Is it up to the audio clients to filter them out? I desparately searched ths internet, but can't find aby substantial info. Am I looking in the wrong places?
