### ISSUE TITLE
Implement PipeWire Output Plugin

### ISSUE THREAD

**Issue by Scrumplex** [MusicPlayerDaemon/MPD#1012]
## Feature request
As some distributions (as of 2020/11/21 Arch Linux testing) started shipping PipeWire as a drop in replacement for PulseAudio it might be relevant to implement an output plugin for PipeWire directly. Currently I use the PulseAudio output plugin, which works for now as PipeWire also accepts PulseAudio clients.

Generally though I think mpd should also have a direct way to appear as a PipeWire client.

[Arch Linux pipewire-pulse package change](https://github.com/archlinux/svntogit-packages/commit/19680fdad08f5f93090e2797750f466eb4914c0a#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422R104)

**Comment by zarkone** [comment]
looks like it is already here..? https://github.com/MusicPlayerDaemon/MPD/blob/master/src/output/plugins/PipeWireOutputPlugin.cxx

https://mpd.readthedocs.io/en/latest/plugins.html#pipewire

**Comment by MaxKellermann** [comment]
Thanks @zarkone, yes this was implemented already, but I forgot to close this issue.

**Comment by aereaux** [comment]
Thanks for implementing this.  I compiled the master branch to try it out, but it seems like there is no hardware volume mixer.  Is that possible/planned to add before the 0.23 release?

**Comment by zarkone** [comment]
@aereaux does it look like this? https://github.com/MusicPlayerDaemon/MPD/issues/1207

**Comment by aereaux** [comment]
I do get some issues sort of like that, but pausing and resuming a couple times usually fixes it.  But I was getting more segfaults before, although I'm having trouble reproducing them now

**Comment by lnicola** [comment]
@aereaux maybe you can file an issue if you haven't already?
