### ISSUE TITLE
Docker container / Balena

### ISSUE THREAD

**Issue by scls19fr** [MusicPlayerDaemon/MPD#1015]
Hello,

following discussion on https://github.com/balenalabs/balena-sound/issues/215
I think it will be great to have a Docker container which could run a MPD server.
Ideally having it, easily intallable on single board computer such as Raspberry Pi using [Balena Clould](https://www.balena.io/) will be a great feature to have!
Some docker-compose skills are probably required to achieve that.
What is you opinion about that?

Kind regards

**Comment by MaxKellermann** [comment]
I have no interest in developing or supporting something with Docker.
If somebody else wants to do that, that is perfectly fine for me (as long as it's in conformance with MPD's license).
