### ISSUE TITLE
mpd fails to start using mpd.socket in systemd user instance

### ISSUE THREAD

**Issue by jmechnich** [MusicPlayerDaemon/MPD#1016]
### Describe the bug
On my machine I run Debian Bullseye / BunsenLabs Lithium with sddm as login manager and an openbox session. mpd is configured to be started through `mpd.socket` by the systemd user instance.

## Expected Behavior
After logging in, mpd starts as soon as a client accesses port 6600.

## Actual Behavior
Socket initialization fails as the port is already in use. Checking via `lsof` does not show any other application using this port. After restarting the socket, everything works as expected.

## Explanation
It took me probably over a year to figure this one out...
sddm is run by the user `sddm`. This user gets a complete session including a systemd user instance which sets up `mpd.socket`. After logging in, this session is destroyed but not soon enough to release the port in time for my personal systemd user instance. As soon as I can open a terminal and restart the socket, everything works fine.

## Possible Solution / Workaround
Restrict the socket to certain users or groups. A nice solution could be a group `mpd` containing all users for whom the socket should be set up. In my particular case, adding `ConditionGroup=audio` to a new `[Unit]` section of `mpd.socket` worked flawlessly.

## Version

```
Music Player Daemon 0.22.3 (0.22.3)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log

From `journalctl --user -u mpd.socket`:
```
-- Reboot --
Nov 27 20:08:09 darkstar systemd[4049]: mpd.socket: Failed to create listening socket ([::]:6600): Address already in use
Nov 27 20:08:09 darkstar systemd[4028]: mpd.socket: Failed to receive listening socket ([::]:6600): Input/output error
Nov 27 20:08:09 darkstar systemd[4028]: mpd.socket: Failed to listen on sockets: Input/output error
Nov 27 20:08:09 darkstar systemd[4028]: mpd.socket: Failed with result 'resources'.
Nov 27 20:08:09 darkstar systemd[4028]: Failed to listen on mpd.socket.
Nov 27 20:10:53 darkstar systemd[4028]: Listening on mpd.socket.
```

**Comment by MaxKellermann** [comment]
This is not a MPD problem. Your log doesn't show that systemd even attempts to start MPD. systemd fails to create the listener socket, because the "Address already in use". I assume some other process is already listening on that address.

**Comment by MaxKellermann** [comment]
> In my particular case, adding ConditionGroup=audio to a new [Unit] section of mpd.socket worked flawlessly.

About this part: yes sure, you can do that. You can write a drop-in for the user socket unit. But it's a configuration that is very specific to your setup, and is not a general solution, and may cause problems for others.

**Comment by jmechnich** [comment]
> This is not a MPD problem. Your log doesn't show that systemd even attempts to start MPD. systemd fails to create the listener socket, because the "Address already in use". I assume some other process is already listening on that address.

Thanks for your reply. I have described why this is happening above: the mpd.socket opened by the login manager session is the culprit here. I consider this to be a mpd problem as those unit files for systemd are part of this project (and are not modified in Debian). During researching this issue over the last couple of months I found quite a few similar reports, so possibly it affects other setups as well.

> > In my particular case, adding ConditionGroup=audio to a new [Unit] section of mpd.socket worked flawlessly.
> 
> About this part: yes sure, you can do that. You can write a drop-in for the user socket unit. But it's a configuration that is very specific to your setup, and is not a general solution, and may cause problems for others.

That is kind of why I opened this bug report: to find a more general solution. I proposed one option (add `mpd` group), another one could be just deleting `/usr/lib/systemd/user/mpd.socket`.

**Comment by jmechnich** [comment]
Maybe one more piece of information: this problem does not exist on a more or less identical setup using Debian Buster and mpd 0.21.5 as this version of mpd does not have the user mpd.socket file yet.
