### ISSUE TITLE
MPD 0.20.10 win32 saved unusable playlist

### ISSUE THREAD

**Issue by guizhenwei** [MusicPlayerDaemon/MPD#102]
By the latest released **win32** version: MPD 0.20.10. 

I saved a playlist file(named **360.m3u** which contains 360 items) by invoking ***save*** method introduced in the MPD protocol: https://www.musicpd.org/doc/protocol/playlist_files.html 

It is OK so far.

But when i **load** the playlist file(**360.m3u**) i just saved, MPD only load items with file path in English. (In my case, just 2 file, the other 358 files contained Chinese characters can not be load)

I open the playlist file with text editor, i found all the 360 files were contained in it, without missing any. 
But all the **non-english items** with human unreadable encoding. (Even text edit shows its UTF-8)

Here i upload the playlist file for reference. (Renamed from *.m3u to *.txt, Github don't allow m3u file)

[360.txt](https://github.com/MusicPlayerDaemon/MPD/files/1254243/360.txt)

**Comment by guizhenwei** [comment]
New found. 

If i save the above uploaded "360.txt" file as **UTF-8 with BOM**(I saved by notepad.exe, choice UTF-8 encoding, then open it with **visual code** editor to see the encoding, it shows the encoding is **UTF-8 with BOM**),  then i renamed it as **360.m3u**, problem solved! It can be load into queue by MPD.

So i guess the problem might be: 

On Windows platform, MPD save playlist file as **UTF-8** encoding, not **UTF-8 with BOM**.
(It is OK for items with english file path, not ok for items with non-english  file path.)

**Comment by MaxKellermann** [comment]
@torumyax unrelated and caused by you; please don't spam this bug report.
