### ISSUE TITLE
Protocol idle/noidle question.

### ISSUE THREAD

**Issue by RomanBurunkov** [MusicPlayerDaemon/MPD#1027]
## Question

Hi there,

My mpd version is 0.22.3.
I'm trying to use mpd protocol and faced with some strange behavior of noidle command.
I use idling to get updates about any changes and before sending any other requests to the mpd I use noidle to leave idling.

May be I do that in a wrong way, but double checking the mpd proto docs didn't help.

According to the docs:

* `A command returns OK on completion or ACK some error on failure. These denote the end of command execution.`
* `The idle command can be canceled by sending the command noidle (no other commands are allowed)`

In the most cases I've got back 'OK\n' from mpd after sending 'noidle', so to handle that my code waits the response from mpd before continue sending further requests. But sometimes(usually after 7-8 requests) mpd doesn't send any responses on 'noidle' requests at all so my code stuck waiting for a OK/ACK. E.g. I can sent noidle ten times and will not get any response at all.

The workaround which works for me is to wait about 300-500 ms and send idle and then try to send noidle again, and after that mpd starts answering on 'noilde'. But that doesn't looks good.

Is there any conditions when mpd shouldn't answer on 'noidle' requests?
Or do I use idle/noidle in a wrong way?

**Comment by MaxKellermann** [comment]
The "noidle" command technically doesn't have a response. All it does is cancel the pending "idle" command. The "noidle" response you're seeing is really the "idle" response (which may be empty because it was canceled).
Sending "noidle" while no "idle" is pending doesn't produce anything because this behavior solves a race condition: what if you're sending "noidle", and at the very same time MPD sends the "idle" response because something happened meanwhile - then you'd be seeing two responses, but how can your client know that there are now two distinct responses for "idle" and "noidle"? That's why there's the rule that "noidle" never has a response.

**Comment by RomanBurunkov** [comment]
Thank you Max for so fast response.

So I should to stop waiting any data after sending 'noidle' and just start sending commands, since waiting for that is wrong Am I right?

I will check the docs also if that mentioned there, may be I missed it.

**Comment by MaxKellermann** [comment]
> Am I right?

No. After sending "noidle", you *must* read a response first. Not the response of "noidle", but the response of the preceding "idle".

If there weren't an "idle" pending, you just wouldn't be sending "noidle". So assuming there won't be a response is a wrong assumption. Sure, "noidle" doesn't have a response, but the whole point of "noidle" is to get the "idle" response *now*.

**Comment by RomanBurunkov** [comment]
Sorry, looks I'm a bit lost.

So it looks that I'm trying to send 'noidle' while connection is not really in idle mode and I should have some better idle state tracking in my code to not send 'noidle' if connection is not in idle state.

**Comment by MaxKellermann** [comment]
Yes, your code should remember whether you're waiting for "idle" or not. And only send "noidle" to pull the connection out of "idle" mode.
Why else would you want to send "noidle"? Serious question.
Sending "noidle" without having the intention to cancel a preceding "idle" doesn't make any sense, so I really wonder why you send "noidle" unconditionally.

**Comment by RomanBurunkov** [comment]
Indeed I'm trying to connect to mpd instance from a node js and forked a module called node-mpd for that purpose.
It uses some sort of queue to handle concurrent requests and after getting this clarification about how idle works I believe it could be some sort of race condition or bad idle state tracking in it. E.g. it doesn't check at all idle state before sending 'noidle'.

```
MPD.prototype._leaveIdle = function(callback) {
	this.idling = false;
	this.client.once("data", function(message) {
		//this._checkReturn(message.trim());
		this.commanding = true;
		callback();
	}.bind(this));
	this._write("noidle");
};
```

 Will try to debug and fix it.

Thank you.

**Comment by RomanBurunkov** [comment]
Solved,

Again thanks for clarification.
