### ISSUE TITLE
Failed to compile mpd.exe binary for Windows 32bit

### ISSUE THREAD

**Issue by handsomegui** [MusicPlayerDaemon/MPD#103]
it is OK without any problem by issuing:

```
./win32/build.py --64
```
to generated 64bit mpd.exe for Windows 64bit.

 

But if i compile to 32bit of Windows by issueing:
```
./win32/build.py --32
``` 

then it will failed. The related part is lame: 
```
Makefile:319: recipe for target 'xmm_quantize_sub.lo' failed
make[3]: *** [xmm_quantize_sub.lo] Error 1
```
But i'm sorry that i have no knowledge to debug that in detail.

**Comment by MaxKellermann** [comment]
The error message is incomplete. You pasted only the boring uninformative part.
