### ISSUE TITLE
Build failure with clang 10.0.1 and any mpd release >= 0.21.25: error: no member named 'forward' in namespace 'std'

### ISSUE THREAD

**Issue by GvMariani** [MusicPlayerDaemon/MPD#1030]
### Describe the bug
Trying to build mpd >= 0.21.5 on the distro Rosa 2016.1 x86_64, a LTS distribution derived from Mandriva. Being a LTS release it has a rather old gcc (5.5.0), so since a few releases we are using clang 10.0.1 to build mpd and this worked OK until 0.21.24.
Starting with 0.21.5 the build now fails with the error: "no member named 'forward' in namespace 'std'" in src/Log.hxx.
Something weird is happening between clang and stdc++...
If needed I can provide the full log of the failed build.

By comparing 0.21.4 (last release building OK) and 0.21.5 (first failing) I guess that commits (on 0.21.x branch)
36e6079c57787a3599de8be80e508eb497d0de1e and e7c5a42821ebe7767f76aabebf1247fddd3c6376 are the culprits.
Reverting them indeed seems to fix the build, but I would like to know how to fix it without having to carrying around revert patches against upstream.

## Expected Behavior
Successful build.

## Actual Behavior
Build failure while processing /src/system/FatalError.cxx.

## Version

0.21.25 and 0.21.26; any 0.22.x release.

## Log

Log from a 0.21.26 failed build:
-Isrc/system/33029a6@@system@sta -Isrc/system -I../src/system -Isrc -I../src -I. -I../ -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -funwind-tables -ffunction-sections -fdata-sections -D_GNU_SOURCE -O2 -Wa,--compress-debug-sections -gdwarf-4 -Wstrict-aliasing=2 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -fPIC -MD -MQ src/system/33029a6@@system@sta/FatalError.cxx.o -MF src/system/33029a6@@system@sta/FatalError.cxx.o.d -o src/system/33029a6@@system@sta/FatalError.cxx.o -c ../src/system/FatalError.cxx
In file included from ../src/system/FatalError.cxx:22:
In file included from ../src/LogV.hxx:23:
../src/Log.hxx:121:42: error: no member named 'forward' in namespace 'std'
        LogFormat(LogLevel::ERROR, e, fmt, std::forward<Args>(args)...);
                                           ~~~~~^
../src/Log.hxx:121:50: error: 'Args' does not refer to a value
        LogFormat(LogLevel::ERROR, e, fmt, std::forward<Args>(args)...);
                                                        ^
../src/Log.hxx:117:22: note: declared here
template<typename... Args>
                     ^
../src/Log.hxx:141:43: error: no member named 'forward' in namespace 'std'
        LogFormat(LogLevel::ERROR, ep, fmt, std::forward<Args>(args)...);
                                            ~~~~~^
../src/Log.hxx:141:51: error: 'Args' does not refer to a value
        LogFormat(LogLevel::ERROR, ep, fmt, std::forward<Args>(args)...);
                                                         ^
../src/Log.hxx:136:22: note: declared here
template<typename... Args>
                     ^
4 errors generated.

**Comment by MaxKellermann** [comment]
MPD 0.21.x is not supported, but your only log is from this unsupported version.

**Comment by GvMariani** [comment]
> MPD 0.21.x is not supported, but your only log is from this unsupported version.
Yes, that was from the last build I did while trying to find what change broke the build on my system: but I can assure you that the error is exactly the same from 0.22.3 (ie the first release that I tried) and below...
If you prefer I can produce a log from 0.22.3, but let me point out that the change happened well before, since 0.21.24 works and 0.21.25 don't, so the supported/unsupported thing is rather moot IMHO...

**Comment by MaxKellermann** [comment]
I can't reproduce the problem, so it would be helpful to see the build errors of the current version.

**Comment by neheb** [comment]
You should try compiling with libcxx.

**Comment by GvMariani** [comment]
> You should try compiling with libcxx.


Yes, I found that this is the origin of all the story...
My build is using clang with a too old libstdc++ (from gcc 5.5.0): while the first supports c++17, the latter does not... and mpd started to use something absent in it with the two commits I listed above (ie with 0.21.25). Note that, in general, mixing clang and stdc++ should be OK, since it worked in the past (until 0.21.24) and can be made work with mpd >= 0.21.25 (I have already a workaround for the originating issue).

So this is not really a mpd bug...
However I would dare to suggest that you try to check at build time not only for the system compiler, but also for the system c++ std library, to avoid bug reports as this one...

**Comment by MaxKellermann** [comment]
Mixing clang with GCC's libstdc++ is fine, but as you said, libstdc++ version 5.5 is not C++17 compliant, and MPD requires a C++17 toolchain.

**Comment by GvMariani** [comment]
> Mixing clang with GCC's libstdc++ is fine, but as you said, libstdc++ version 5.5 is not C++17 compliant, and MPD requires a C++17 toolchain.


Exactly... but then, at the configure time, you should test not only for the right compiler, but also for the presence of the right standard library: otherwise some other user could get bitten by the same issue as I did, because in my case the compiler was OK (and tested), while libstdc++ was not (and this passed unnoticed, causing the build error).
