### ISSUE TITLE
usage of the ID3tags artist and albumartists for sampler

### ISSUE THREAD

**Issue by seniorgod** [MusicPlayerDaemon/MPD#1032]
I struggle (since years) to organize my music library quit well with mpd for sampler (albums with various artists). 
If search for sampler in the album view, all MPD clients i use show every song as dedicated album. 
I see my sampler albums only as exactly one album in the album list if i write the same "name" to the interpret tag of every song in a sampler. For example i write "Various Artists" into the interpret tag of every song in a sampler. In that case i see the sampler as only one album in the album view. 
In my opinion this is wrong. An album should be exactly one album based on the name of the album, not relying on the name of the artists. If MPD would sort the album list based on the names of artists, you should use album artists as first choice. If the album artists is not present in ID3tags, you can use artist as second choice for sorting. 

Or? Do i anything wrong?

**Comment by MaxKellermann** [comment]
MPD doesn't sort anything. That depends on the client you're using.
ncmpc, for example, has a library view which you can configure to use "AlbumArtist" (but falls back to "Artist" if there's no "AlbumArtist").

**Comment by seniorgod** [comment]
Do i have to configure "something" in order that MPD reads and store Album artist or is that standard?

**Comment by seniorgod** [comment]
Ok, ok,
i found the error. My configuration (which is very old) included that: 
metadata_to_use "artist,album,title,track,name,genre,date"

I guess i have to "comment" that line in order to use all ID3tags which are found.
