### ISSUE TITLE
MPD over HTTP?

### ISSUE THREAD

**Issue by diracs-delta** [MusicPlayerDaemon/MPD#1033]
## Question

I've spent the past 3 days building a javascript library for a web client to communicate over TCP with MPD, with TCP packet handling and all the works. But then I found out that if I just type my MPD's IP and port into my browser, my browser returns

```
OK MPD 0.21.11
```

Which obviously begs the question, can I send commands over HTTP? That would make my life so much easier. I've tried the following:

```
192.168.86.19:6600/status
192.168.86.19:6600?q=status
```

but neither worked. I've also scoured the documentation and can't find any mention of how to send commands over HTTP. Is it even possible? Or is the `OK MPD` I received over HTTP just some side effect of the TCP socket being bound to the same MPD port?

**Comment by MaxKellermann** [comment]
No, the MPD protocol is not HTTP.
The "OK MPD" is not a response, but the server greeting. Your browser just misunderstands it.

**Comment by diracs-delta** [comment]
@MaxKellermann thanks for the quick response. that's what i had assumed (and secretly hoped for because otherwise it would have meant i wasted 3 days)
