### ISSUE TITLE
Webdav not working with Nextcloud

### ISSUE THREAD

**Issue by PVince81** [MusicPlayerDaemon/MPD#1039]
### Describe the bug
1. Set music_directory to a Webdav URL connecting to a Nextcloud instance: "https://mpd:password@nextcloud.hostname.com/remote.php/dav/files/mpd/Music/"
2. Restart mpd service
3. Run `mpc rescan`
4. Observe Nextcloud's Apache access log

## Expected Behavior
Scanning process goes through all directories.

## Actual Behavior
Only one PROPFIND is made and then the scanning stops.

## Version
mpd 0.22.3 (from Arch ARM packages on Rpi1 model B)

### mpd
TODO

### Apache access log
```
xx.xx.xx.xx - - [03/Jan/2021:17:52:00 +0100] "PROPFIND /remote.php/dav/files/mpd/Music/ HTTP/1.1" 401 5509 "-" "Music Player Daemon 0.22.3"
xx.xx.xx.xx - mpd [03/Jan/2021:17:52:00 +0100] "PROPFIND /remote.php/dav/files/mpd/Music/ HTTP/1.1" 207 1883 "-" "Music Player Daemon 0.22.3"
```
First request is from auth, the second one is the authenticated one.

## Notes
I looked at the source code and I believe that the Webdav response processing is incomplete: https://github.com/MusicPlayerDaemon/MPD/blob/abbd980671944bc2d7a043a8481f4168ce878ae7/src/storage/plugins/CurlStorage.cxx#L436

A successful PROPFIND response returns the HTTP status code 207, not 200. So probably the related code paths should check for more 2xx status codes.

**Comment by PVince81** [comment]
Next up:
- [ ] test with master and provide logs
- [ ] check Nextcloud logs / find out if the request is constructed properly
- [ ] try replacing 200 with 207 and see if it works

**Comment by PVince81** [comment]
wow, compiling mpd on the Rpi 1 Model B took more than 3 hours... and it seems that rerunning `ninja -C output/release` starts from scratch, which means that for every code change attempt I'll need a few hours

**Comment by PVince81** [comment]
okay, got the verbose mode output from mpd after compiling from master: when trying to scan Webdav, it says something like:
```
update: Not a directory: https://mpd:password@nextcloud.hostname.com/remote.php/dav/files/mpd/Music/
```

so need to check the exact request and how the response is processed

**Comment by PVince81** [comment]
Note: could also be a namespace parsing issue when parsing the collection tag

**Comment by PVince81** [comment]
adding 207 as a valid status did not work, it still says "Not a directory".

more intense debugging needed

**Comment by PVince81** [comment]
okay, I got a glimpse of the response received in the Curl handler's OnData:
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/mpd/Music/</d:href>
    <d:propstat>
      <d:prop>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

but if I do a curl manually on the CLI on the same URL with Depth 0 I get this:
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/mpd/Music/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Sun, 20 Dec 2020 08:17:04 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>15948001844</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5fdf08804a35f"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

in my PROPFIND I didn't send a body.

In the code I see a TODO about sending the actual body, maybe that's missing: https://github.com/MusicPlayerDaemon/MPD/blob/abbd980671944bc2d7a043a8481f4168ce878ae7/src/storage/plugins/CurlStorage.cxx#L276

The fact that getcontentlength is missing on collections is intentional, but somehow the other properties are not returned.

The problem is likely with the request body sent by mpd.

Note: other Webdav servers ignore the request and would return all properties anyway, this would explain why this code might have been seen working before with other servers.

**Comment by PVince81** [comment]
I managed to capture the request from MPD with Apache's mod_security:
```
PROPFIND /remote.php/dav/files/mpd/Music/ HTTP/1.1
Host: cloud.vincentpetry.net
Authorization: Basic bXBkOm5XMzRLLXlFajU0LXdCSnFSLVdLTUNqLTJOR0ZR
User-Agent: Music Player Daemon 0.23~git
Accept: */*
depth: 0
Content-Length: 170
Content-Type: application/x-www-form-urlencoded

<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:"><a:prop><a:resourcetype/></a:prop><a:prop><a:getcontenttype/></a:prop><a:prop><a:getcontentlength/></a:prop></a:propfind>
```

So the correct properties are being sent, but the content-type is wrong.

**Comment by PVince81** [comment]
I managed to capture the request from MPD with Apache's mod_security:
```
PROPFIND /remote.php/dav/files/mpd/Music/ HTTP/1.1
Host: xxxxx
Authorization: Basic xxxxxxxxxx
User-Agent: Music Player Daemon 0.23~git
Accept: */*
depth: 0
Content-Length: 170
Content-Type: application/x-www-form-urlencoded

<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:"><a:prop><a:resourcetype/></a:prop><a:prop><a:getcontenttype/></a:prop><a:prop><a:getcontentlength/></a:prop></a:propfind>
```

So the correct properties are being sent, but the content-type is wrong.

**Comment by PVince81** [comment]
I was able to reproduce the issue with curl by putting the body into a file "propfind.xml" and doing a curl:
```
curl -X PROPFIND -H "Content-Type:text/xml" -H Depth:0 --data-binary "@propfind.xml" https://mpd:password@hostname/remote.php/dav/files/mpd/Music/
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/files/mpd/Music/</d:href><d:propstat><d:prop><d:getcontentlength/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
```

so despite passing in the correct content-type, the properties are still not returned... strange.

will double check the propfind request format

**Comment by PVince81** [comment]
okay, got it.
it's a classic that also bit me in the past:

not working (current, reformatted):
```
<a:propfind xmlns:a="DAV:">
    <a:prop><a:resourcetype/></a:prop>
     <a:prop><a:getcontenttype/></a:prop>
     <a:prop><a:getcontentlength/></a:prop>
</a:propfind>
```

working:
```xml
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:">
   <a:prop>
        <a:resourcetype/>
        <a:getcontenttype/>
        <a:getcontentlength/>
   </a:prop>
</a:propfind>
```

There's an example here that uses the same format: https://docs.nextcloud.com/server/12.0/developer_manual/client_apis/WebDAV/index.html#testing-requests-with-curl

and here from the RFC: https://tools.ietf.org/html/rfc4918#section-9.1.3

okay, so it should be an easy fix:
- [ ] adjust content-type to send "text/xml" (just in case)
- [ ] fix the format of the request in the PROPFIND

I'll prepare a PR after testing

**Comment by MaxKellermann** [comment]
Yay, now that's an excellent bug report! Please do the PR for the stable branch (v0.22.x).

**Comment by PVince81** [comment]
after fixing, the response looks fine (reformatted):
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/mpd/Music/</d:href>
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:getcontenttype/>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

but for some reason mpd still thinks it's not a collection/directory :thinking: 

seems like this will need even more debugging

**Comment by PVince81** [comment]
draft PR here https://github.com/PVince81/MPD/pull/1

next I'll add more "FormatDebug" locally to find out why it's not detected as directory

**Comment by PVince81** [comment]
okay, I think I found another misunderstanding in the code about Webdav: the code seems to parse the "d:status" element and interprets this as a global status code.

this is wrong: there are two propstat blocks in the response, one with "found properties" that have status 200 and another one with the "not found properties" with status 404. But the global status is still 207 and means we did find the resource.

I'll try to rewire this to use the actual http status code.

**Comment by PVince81** [comment]
Phew, I managed to make it go a bit further by making it process the propstat blocks separately (pushed to the PR e8e5c6399827bb23773d9a52b8a92ab0a23eda53)

Now the next problem is that it stops at the first level: the dir entries seem to be parsed but for some reason it doesn't go further.

Also I see this request in the apache log:
```
192.168.1.2 - - [04/Jan/2021:15:21:24 +0100] "GET /remote.php/dav/files/mpd/Music/.mpdignore HTTP/1.1" 401 1823 "-" "Music Player Daemon 0.22.4"
192.168.1.2 - mpd [04/Jan/2021:15:21:24 +0100] "GET /remote.php/dav/files/mpd/Music/.mpdignore HTTP/1.1" 404 1628 "-" "Music Player Daemon 0.22.4"
```

which triggers an error in the mpd stdout:
```
exception: CURL failed: The requested URL returned error: 404 Not Found
```

not sure if that 404 is making the scanner trip or whether it's unrelated.

needs further research

**Comment by PVince81** [comment]
after commenting out the "throw" for the 404, I just get a "update: finished". so probably not related.

I need to find out where the path walking logic is to debug there.

**Comment by PVince81** [comment]
After a long detour doing printf debugging, I found out that the base_path and href don't match in HrefToEscapedName.

The base_path used also contains the host name with user id, like `/mpd:password@hostname/remote.php/dav/files/mpd/Music/`
so it is not able to extract the relative path from the href, the latter contains `/remote.php/dav/files/mpd/Music/Vincent/`.

I suspect that this code was designed and tested against servers that return an URI instead of relative path. The RFC allows both: https://tools.ietf.org/html/rfc4918#section-14.7

**Comment by PVince81** [comment]
After a lot of struggles with strings (c_str vs StringView vs std::string) I managed to adjust base path extraction when the href is relative, see https://github.com/PVince81/MPD/pull/1/commits/216f62ea1468933f4a78f17885b27e37e1393d8c

Now the scan is working recursively!

It seems scanning faster than with davfs, which is the reason I was exploring this.

I'll do some more testing

**Comment by PVince81** [comment]
Seems the scanning worked, even for file names containing chinese characters. And they can be added to playlist and played :tada: 

I've switched the PR https://github.com/PVince81/MPD/pull/1 to ready for review.

**Comment by PVince81** [comment]
I just discovered that I made had a mistake in my test config: I had "https:///mpd:password@..." in the config.
Basically three slashes... After testing with two slashes the scanning doesn't work.

I've raised https://github.com/MusicPlayerDaemon/MPD/issues/1043 to track it and will have a look.
