### ISSUE TITLE
volume control is broken with alsa and hardware mixer

### ISSUE THREAD

**Issue by edio** [MusicPlayerDaemon/MPD#104]
### Testcases

Case 1: mpc volume -2
Expected: volume is decreased by 2
Actual: volume remains unchanged

Case 2: mpc volume +1
Expected: volume is increased by 1
Actual: volume is increased by more than 1

### Details
*Platform* ARMv7
*OS* Archlinux-ARM
*MPD version* 0.20.10

#### mpd config
```
gapless_mp3_playback "yes"
replaygain "album"
replaygain_missing_preamp "-6"

filesystem_charset "UTF-8"
id3v1_encoding "UTF-8"

input { 
        plugin "curl"
}

audio_output {
       type            "alsa"
       name            "My ALSA Device"
       device          "hw:0,0"        # optional
       mixer_device    "default"       # optional
       mixer_control   "PCM"           # optional
       mixer_index     "0"             # optional
}

pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
```

P.S. I tried to report bug to mantis, but the tracker is effectively down, it doesn't allow to send any bug report

**Comment by MaxKellermann** [comment]
Upload a verbose log.

**Comment by edio** [comment]
Tbh, I don't see how log can help (it just logs request from client, which is correct, but doesn't reflect how mpd reacted).

On the other hand, I've noticed, that the issue is reproducible only with alsa output and *hardware* mixer. Probably it's somehow related to how values are translated by the mixer. Maybe the issue is not even in mpd, but only developers of mpd can confirm.

With software mixer and pulseaudio it works just fine.

https://pastebin.com/EaMNkBk6

**Comment by MaxKellermann** [comment]
When using relative volume, it is not guaranteed that the volume really changes. It all depends on the granularity of your hardware mixer. If it only allows, say, 10 steps from "silent" to "loudest", then "+1" will be a no-op.
So, what is the granularity of your hardware mixer?

**Comment by edio** [comment]
Thanks for explanation.
Now I finally paid attention. Indeed, alsamixer level ranges from -45 dB to 0 dB with 1dB step. But this translates into 1..4 step on a scale of 0..100 (it's highly non-uniform).

I don't know what interface alsa hw mixer provides, but if it's possible, it would be more intuitive if mpd decreased volume even when the requested change is smaller than mixer granularity.

**Comment by quantenschaum** [comment]
What kind of % does MPD set on the hardware mixer? With "kind" I mean linear or natural %, as the -M option of amixer does. (Not all soundcards support this option, though.)

About linear and logarithmic volume control: https://github.com/larsimmisch/pyalsaaudio/issues/8

**Comment by miccoli** [comment]
Just to clarify the problem, if I run repeatedly `mpc volume +1` starting from volume 0, I get
```
$ mpc volume 0; for i in {1..78}; do mpc volume +1; done
volume:  0%   repeat: off   random: off   single: off   consume: on 
volume:  2%   repeat: off   random: off   single: off   consume: on 
volume:  3%   repeat: off   random: off   single: off   consume: on 
volume:  4%   repeat: off   random: off   single: off   consume: on 
volume:  5%   repeat: off   random: off   single: off   consume: on 
volume:  6%   repeat: off   random: off   single: off   consume: on 
volume:  7%   repeat: off   random: off   single: off   consume: on 
volume:  8%   repeat: off   random: off   single: off   consume: on 
volume:  9%   repeat: off   random: off   single: off   consume: on 
volume: 10%   repeat: off   random: off   single: off   consume: on 
volume: 11%   repeat: off   random: off   single: off   consume: on 
volume: 12%   repeat: off   random: off   single: off   consume: on 
volume: 13%   repeat: off   random: off   single: off   consume: on 
volume: 14%   repeat: off   random: off   single: off   consume: on 
volume: 15%   repeat: off   random: off   single: off   consume: on 
volume: 16%   repeat: off   random: off   single: off   consume: on 
volume: 17%   repeat: off   random: off   single: off   consume: on 
volume: 18%   repeat: off   random: off   single: off   consume: on 
volume: 19%   repeat: off   random: off   single: off   consume: on 
volume: 20%   repeat: off   random: off   single: off   consume: on 
volume: 21%   repeat: off   random: off   single: off   consume: on 
volume: 22%   repeat: off   random: off   single: off   consume: on 
volume: 23%   repeat: off   random: off   single: off   consume: on 
volume: 24%   repeat: off   random: off   single: off   consume: on 
volume: 25%   repeat: off   random: off   single: off   consume: on 
volume: 26%   repeat: off   random: off   single: off   consume: on 
volume: 27%   repeat: off   random: off   single: off   consume: on 
volume: 28%   repeat: off   random: off   single: off   consume: on 
volume: 29%   repeat: off   random: off   single: off   consume: on 
volume: 30%   repeat: off   random: off   single: off   consume: on 
volume: 31%   repeat: off   random: off   single: off   consume: on 
volume: 32%   repeat: off   random: off   single: off   consume: on 
volume: 33%   repeat: off   random: off   single: off   consume: on 
volume: 34%   repeat: off   random: off   single: off   consume: on 
volume: 35%   repeat: off   random: off   single: off   consume: on 
volume: 36%   repeat: off   random: off   single: off   consume: on 
volume: 38%   repeat: off   random: off   single: off   consume: on 
volume: 39%   repeat: off   random: off   single: off   consume: on 
volume: 41%   repeat: off   random: off   single: off   consume: on 
volume: 42%   repeat: off   random: off   single: off   consume: on 
volume: 44%   repeat: off   random: off   single: off   consume: on 
volume: 46%   repeat: off   random: off   single: off   consume: on 
volume: 47%   repeat: off   random: off   single: off   consume: on 
volume: 48%   repeat: off   random: off   single: off   consume: on 
volume: 49%   repeat: off   random: off   single: off   consume: on 
volume: 50%   repeat: off   random: off   single: off   consume: on 
volume: 51%   repeat: off   random: off   single: off   consume: on 
volume: 52%   repeat: off   random: off   single: off   consume: on 
volume: 53%   repeat: off   random: off   single: off   consume: on 
volume: 54%   repeat: off   random: off   single: off   consume: on 
volume: 55%   repeat: off   random: off   single: off   consume: on 
volume: 56%   repeat: off   random: off   single: off   consume: on 
volume: 57%   repeat: off   random: off   single: off   consume: on 
volume: 58%   repeat: off   random: off   single: off   consume: on 
volume: 60%   repeat: off   random: off   single: off   consume: on 
volume: 62%   repeat: off   random: off   single: off   consume: on 
volume: 63%   repeat: off   random: off   single: off   consume: on 
volume: 64%   repeat: off   random: off   single: off   consume: on 
volume: 66%   repeat: off   random: off   single: off   consume: on 
volume: 68%   repeat: off   random: off   single: off   consume: on 
volume: 69%   repeat: off   random: off   single: off   consume: on 
volume: 71%   repeat: off   random: off   single: off   consume: on 
volume: 72%   repeat: off   random: off   single: off   consume: on 
volume: 74%   repeat: off   random: off   single: off   consume: on 
volume: 76%   repeat: off   random: off   single: off   consume: on 
volume: 78%   repeat: off   random: off   single: off   consume: on 
volume: 79%   repeat: off   random: off   single: off   consume: on 
volume: 81%   repeat: off   random: off   single: off   consume: on 
volume: 83%   repeat: off   random: off   single: off   consume: on 
volume: 84%   repeat: off   random: off   single: off   consume: on 
volume: 86%   repeat: off   random: off   single: off   consume: on 
volume: 87%   repeat: off   random: off   single: off   consume: on 
volume: 89%   repeat: off   random: off   single: off   consume: on 
volume: 91%   repeat: off   random: off   single: off   consume: on 
volume: 93%   repeat: off   random: off   single: off   consume: on 
volume: 94%   repeat: off   random: off   single: off   consume: on 
volume: 96%   repeat: off   random: off   single: off   consume: on 
volume: 98%   repeat: off   random: off   single: off   consume: on 
volume:100%   repeat: off   random: off   single: off   consume: on 
```
So there are forbidden values, `{1%, 40%, ..., 92%, 95%, 97%, 99%}`. 

The problem is that `mpc volume +1` skips the invalid values, while `mpc volume -1` simply gets stuck at the ceiling valid value:
```
$ mpc volume 100; for i in {1..77}; do mpc volume -1; done
volume:100%   repeat: off   random: off   single: off   consume: on 
volume:100%   repeat: off   random: off   single: off   consume: on 
volume:100%   repeat: off   random: off   single: off   consume: on 
```
and so on.

Apparently somewhere in the guts of mpd/alsa/xxx the invalid value is approximated with the ceiling value:
```
$ mpc volume 40                                           
volume: 41%   repeat: off   random: off   single: off   consume: on 
```

But there also other weird situations:
```
$ mpc volume 92
volume: 93%   repeat: off   random: off   single: off   consume: on 
$ mpc volume 93
volume: 94%   repeat: off   random: off   single: off   consume: on 
```
which are responsible for the impossibility to reliably decrease the volume with alsa+hardware mixer.

**Comment by miccoli** [comment]
In all probability the bug is in line <https://github.com/MusicPlayerDaemon/MPD/blob/fbc4bb29dcc471a08e47f10ffaa24ad8da6d40a2/src/mixer/plugins/AlsaMixerPlugin.cxx#L285> where the last argument of `set_normalized_playback_volume` is hardcoded to `1`.

The call signature is <https://github.com/MusicPlayerDaemon/MPD/blob/fbc4bb29dcc471a08e47f10ffaa24ad8da6d40a2/src/mixer/plugins/volume_mapping.h#L10-L12> where `dir > 0` means *round up* (take the ceiling) and `dir < 0` means *round down* (take the floor): see <https://github.com/MusicPlayerDaemon/MPD/blob/fbc4bb29dcc471a08e47f10ffaa24ad8da6d40a2/src/mixer/plugins/volume_mapping.c#L49-L57>

This means that the current implementation hardcodes to round volume values towards plus infinity which is coherent with the findings of my previous comment.

A possible solution should be to call `set_normalized_playback_volume(elem, 0.01*volume, 1)` for *increasing* volume, but `set_normalized_playback_volume(elem, 0.01*volume, -1)` for decreasing volume.

**Comment by MaxKellermann** [comment]
Thanks @miccoli that's a helpful analysis for the root cause.
Your suggestion sounds reasonable, but the problem is that the method doesn't know whether the volume is increased or decreased. That is just not part of the plugin API. A different approach is needed to get sane rounding.

**Comment by miccoli** [comment]
Then simply read the current volume and compare it with the new one. I will test this approach and provide a PR, if this solves the problem.

**Comment by MaxKellermann** [comment]
On 2017/12/12 20:44, Stefano Miccoli <notifications@github.com> wrote:
> Then simply read the current volume and compare it with the new one. I will test this approach and provide a PR, if this solves the problem.

It won't solve the problem.  I dug some code today and did some
debugging.

Your idea of adjusting the rounding direction is certainly a good one,
and it sometimes makes the symptoms of this bug disappear (and fixes
some weird inconsistent behavior like the one you cited), but it is
not a general solution for this bug report.  If the gap between two
"supported" discrete volume levels is too large, rounding properly
still doesn't help jump over that gap.

**Comment by miccoli** [comment]
Yes, but from my preliminary testing at least I have symmetry: `mpc volume -1` undoes `mpc volume +1`. (Tested on a RPi with snd-rpi-hifiberry-dacplus, but I do not have large gaps).

**Comment by miccoli** [comment]
Finally I'm quite satisfied with
<https://github.com/miccoli/MPD/blob/3b0a289a833a909b6e9deb061d24b0fb24b011c5/src/mixer/plugins/AlsaMixerPlugin.cxx#L280-L291>
The idea is to simulate a relative volume control and to overshoot by design. 

In fact I'm controlling the volume via a bluetooth remote by the KEY_VOLUMEUP and KEY_VOLUMEDOWN keys. At least with my setup the 'user experience' is satisfactory, and I have a smooth and responsive volume control.
