### ISSUE TITLE
Webdav scan only works with three slashes after scheme

### ISSUE THREAD

**Issue by PVince81** [MusicPlayerDaemon/MPD#1043]
Follow up of https://github.com/MusicPlayerDaemon/MPD/issues/1039.

Today I looked at my mpd.conf and noticed that when I tested the above, I had three slashes after "https:" :facepalm: 

So the fix only works if one uses three slashes instead of two... Doesn't work with two slashes.

I'll look into it... Sorry for the mess.

**Comment by PVince81** [comment]
In hindsight, it might explain why the path appeared as "/mpd:password@hostname/remote.php/..." in some tests. So maybe the base path logic is not needed or needs tweaking.

**Comment by PVince81** [comment]
Okay, it was just about removing the base_path_relative stuff.

PR here: https://github.com/MusicPlayerDaemon/MPD/pull/1044

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/MPD/commit/ec1e04a65ddae1f65b6fb84101acc827646585fb
