### ISSUE TITLE
no final track endtime returned via Range for cue sheets

### ISSUE THREAD

**Issue by twojstaryzdomu** [MusicPlayerDaemon/MPD#1048]
### Describe the bug
When returning a cuesheet derived playlist, mpd is returning an open ended range for the final track. 
A side effect of this is clients of mpd will not receive the length for the final track unless by resorting to what mpd should have done in the first place.
A cuesheet by definition defines the starting point (INDEX 01) for a track but not the end point. Cuesheet supporting software naturally assume the final track runs on from the starting point until the end of the audio file.
The tail end value for the final cue sheet track could be derived from the duration of the file defined earlier (which need not be the only FILE definition in a cuesheet).
It would be appropriate to assume the file defined prior to parsing INDEX tags as valid for duration check.
An end of cuesheet file ([Single file cue sheet](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#A_single-file_cue_sheet_with_a_TRACK_01_INDEX_00_hidden_track)) or a new FILE instance in the cuesheet ([Multiple files](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Multiple_files_with_corrected_gap)) needs to trigger closing the range. The duration check could happen as soon as a file is available, only to be updated at the end of cuesheet file or when a new FILE is encountered.

## Expected Behavior
In addition to the track starting time, return the duration of the file defined earlier header as the tail end value in Range.

## Actual Behavior
mpd returns only the audio starting point in the value defined by Range. Nothing is returned following the hyphen for any cuesheet based final track.

## Version
0.22.3

## Log
For any cuesheet based final album track, lsinfo is returning an open ended range, e.g.:
file: artist/album/file.cue/track0010
Range: 2828.173-

**Comment by MPconta** [comment]
If MPD would store not only a value for "Range", but also for "duration" and "Time", there would be no problem with clients in this context.

**Comment by twojstaryzdomu** [comment]
All those values are related to each other. Duration & time are derived from start time / end time (range) values.

CueParser.cxx uses two interchanging objects previous & current. previous stores the end time of the previous track that is used to populate the start time of the current track. Beyond the final track, the parser has no object from a cuesheet to look up the final end time information but the referenced file.

**Comment by MPconta** [comment]
Yes, "Duration" and "Time" are derived from start / end of the "Range"-values. But these values are not stored in the database. When you look into it with "lsinfo", you don't find "Duration" or "Time"-entries.

So to my understanding it depends how the "Range"-value is defined. If this value should give MPD the information which part of the whole file to play, it works perfectly. It gives MPD a value where to start and where to stop. For the last track it is not necessary to have a stop-value, beacause there is nothing to go on.

Hope, you understand what i mean. Sorry, i'm no programmer and cannot dig into the code. I can only look at this from a logical point of view.

**Comment by twojstaryzdomu** [comment]
If the server is already performing 90% of the task (providing the virtual directory from a cuesheet), it doesn't make much sense for the clients to perform the other 10% (have the final tracks inherit endtime value from the files referenced in a cuesheet).

**Comment by MaxKellermann** [comment]
The song duration is (usually) stored in the database, and is thus part of the `lsinfo` response.
The displayed `Range` is correct - if it's open-ended, it's open-ended, but MPD should better scan the underlying file and show the derived song duration.

**Comment by twojstaryzdomu** [comment]
My limited understanding of a case for an open-ended range is a live stream. Still, a cuesheet is a different case, its contents only make sense in the context of the audio file that will invariably have some length.
I've been trying to solve it myself and look up duration from within CueParser.cxx, however to little effect. Either a DB lookup (the big question being does the filename object entry exist in the DB at the time CueParser.cxx runs?) or getting it from an inherited object, both of which are beyond my C++ skills. Could the Song object gather the duration information early, so that the info could be used to fill in end track duration?

**Comment by MaxKellermann** [comment]
The CueParser has no access to the underlying file. And during database scan, MPD may not have scanned the underlying file already.
Note that `listplaylistinfo` on a CUE file will show the durations, because in that case, MPD scans the underlying file. But not for virtual directories of CUE files. I have an idea how to implement this properly.

**Comment by twojstaryzdomu** [comment]
Thank you. Right, been probably looking at the wrong place to update the code. The local DB may well keep the open ended range (which is convenient). When a client requests the virtual directory, that could be a good time for the server to resolve the missing duration info from a related Song object.

**Comment by MaxKellermann** [comment]
Note: don't use the Range to determine the song duration. Only use the "duration" value. It was missing previously, which was a bug fixed by fee282f49c6a998cf37ee4050971c20239f98056

**Comment by twojstaryzdomu** [comment]
I couldn't get past the db_thread_lock when looking up the parent audio file from within SongPrint.cxx.

Great stuff, you beat me to it. I believe your work concludes it, no more final track times missing.
