### ISSUE TITLE
Unable to play to ALSA PCM using the copy plugin

### ISSUE THREAD

**Issue by timothyjward** [MusicPlayerDaemon/MPD#1056]
### Describe the bug
When attempting to use MPD with an ALSA output on my Raspberry Pi B I find that I am unable to play audio through some of the PCMs configured in `/etc/asound.conf`. Specifically if I use a PCM that uses the `copy` plugin MPD gets "stuck" playing at 1 second into the file:

    > mpc status
    The Lumineers - Ho Hey
    [playing] #1/1   0:01/2:43 (0%)
    volume: 35%   repeat: off   random: off   single: off   consume: off

I simplified my `asound.conf` to the following:
```
pcm.mpdTest {
    type copy
    slave.pcm "hwOutput"
}

# There is always a plug before the hardware to be safe
pcm.output {
    type plug
    slave.pcm "hwOutput"
}

pcm.hwOutput {
    type hw
    card "Headphones"
}
```

and was able to reproduce the following behaviour through changing `mpd.conf`:

- If I write to the hardware directly by using `hw:1` everything works
- If I write to the hardware through a plug using `plughw:1`, everything works
- If I write to the hardware through the pcm `hw` everything works
- If I write to the hardware through the pcm `output` everything works
- If I write to the hardware through the pcm `mpdTest` then audio hangs

## Expected Behavior
I expect the `mpdTest` PCM to work just like any other PCM. I am able to play audio through it using `aplay -D mpdTest`

## Actual Behavior
When using the `mpdTest` PCM there is no playback from mpd, and mpd becomes slow to respond. Sometimes calls to `mpc` time out

## Version

```
Music Player Daemon 0.22.3 (0.22.3)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log

Jan 19 11:04 : alsa_output: opened mpdTest type=COPY
Jan 19 11:04 : alsa_output: buffer: size=444..32768 time=10068..743039
Jan 19 11:04 : alsa_output: period: size=444..32768 time=10068..743039
Jan 19 11:04 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Jan 19 11:04 : alsa_output: format=S16_LE (Signed 16 bit Little Endian)
Jan 19 11:04 : alsa_output: buffer_size=22050 period_size=5512
Jan 19 11:04 : output: opened "alsa" (alsa) audio_format=44100:16:2

**Comment by timothyjward** [comment]
For additional proof that something is wrong, I've tried using the `ao` output as an alternative and it *is* able to play to the `mpdTest` PCM.

I've also tried using some whacky alternatives to the copy plugin, such as the `route` plugin. I still see the same issue when trying to use ALSA directly. with something that isn't hw, or a plug into the hw.

**Comment by MaxKellermann** [comment]
I can't reproduce this problem. Which libasound2 version are you using?

**Comment by timothyjward** [comment]
Hopefully this contains all the version information that you need!

```
$ cat /proc/asound/version
Advanced Linux Sound Architecture Driver Version k5.10.3+.

$ uname -a
Linux pi-test 5.10.3+ #1386 Sun Dec 27 13:58:20 GMT 2020 armv6l GNU/Linux

$ apt show -a libasound2
Package: libasound2
Version: 1.1.8-1+rpt1
Priority: optional
Section: libs
Source: alsa-lib
Maintainer: Debian ALSA Maintainers <pkg-alsa-devel@lists.alioth.debian.org>
Installed-Size: 969 kB
Depends: libasound2-data (>= 1.1.8-1+rpt1), libc6 (>= 2.28)
Suggests: libasound2-plugins (>= 1.0.24)
Breaks: bluez-alsa (<= 4.94-2), libasound2-plugin-equal (<= 0.6-1), libasound2-plugins (<< 1.0.24)
Homepage: https://www.alsa-project.org/
Download-Size: 303 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.raspberrypi.org/debian buster/main armhf Packages
Description: shared library for ALSA applications
 This package contains the ALSA library and its standard plugins, as well
 as the required configuration files.
 .
 ALSA is the Advanced Linux Sound Architecture.
```

**Comment by MaxKellermann** [comment]
I think for further debugging, I need an strace of MPD. Start MPD like this:
`strace -tttTfo /tmp/trace mpd --no-daemon --stdout --verbose`
Then start playback, wait for a few seconds, stop playback and stop MPD with Ctrl-C.
... and then send the trace file (compressed) to me: max at musicpd dot org.

**Comment by timothyjward** [comment]
> I think for further debugging, I need an strace of MPD. Start MPD like this:
> `strace -tttTfo /tmp/trace mpd --no-daemon --stdout --verbose`
> Then start playback, wait for a few seconds, stop playback and stop MPD with Ctrl-C.
> ... and then send the trace file (compressed) to me: max at musicpd dot org.

I've collected the trace and sent it. Thank you for looking into this.

**Comment by MaxKellermann** [comment]
OK, so it looks like the "copy" plugin correctly registers the PCM device in MPD's I/O event loop, and MPD receives 4 of those events and acts accordingly. After the 4th event, MPD actually starts the PCM (because the PCM ring buffer was filled), and after that, MPD receives no more events from the PCM device. Therefore, no playback progress.
This doesn't look like a MPD bug. If I had to guess, I'd say this is a libasound bug (a bug in the "copy" plugin?), somehow maybe it misconfigures the PCM.
(Unlike most programs, MPD uses ALSA's non-blocking mode. This is a very efficient mode, but it's harder to use, and harder to get right. And it reveals more bugs in plugins. For example, bluez-alsa's non-blocking mode is still buggy and thus incompatible with MPD, so this may be a similar story.)
What you could do is record another strace, this time with a "hw" device, and then I'll compare the two traces, to look for hints. (One or two seconds or successful playback is enough.)

**Comment by MaxKellermann** [comment]
Say, what is this "Headphones" card? I re-read your bug report, and found that you never tried to use that directly.
Does that just happen to be driven by bluez-alsa?

**Comment by timothyjward** [comment]
> OK, so it looks like the "copy" plugin correctly registers the PCM device in MPD's I/O event loop, and MPD receives 4 of those events and acts accordingly. After the 4th event, MPD actually starts the PCM (because the PCM ring buffer was filled), and after that, MPD receives no more events from the PCM device. Therefore, no playback progress.

That certainly matches what I see on my device. If I leave it running for a long time then I have (once or twice) had audio start playing after several minutes.

> What you could do is record another strace, this time with a "hw" device, and then I'll compare the two traces, to look for hints. (One or two seconds or successful playback is enough.)

I'll collect this for you now.

> Say, what is this "Headphones" card? I re-read your bug report, and found that you never tried to use that directly.
Does that just happen to be driven by bluez-alsa?

`Headphones` is the "pretty" name for the Raspberry Pi's headphone jack in ALSA, it's the same thing as `hw:1`

``` 
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
```

**Comment by timothyjward** [comment]
> OK, so it looks like the "copy" plugin correctly registers the PCM device in MPD's I/O event loop, and MPD receives 4 of those events and acts accordingly. After the 4th event, MPD actually starts the PCM (because the PCM ring buffer was filled), and after that, MPD receives no more events from the PCM device. Therefore, no playback progress.

Given that I saw the same problem when trying the `route` plugin as an alternative I'm guessing that it's a common issue across most of the ALSA plugins...

**Comment by MaxKellermann** [comment]
So there's a major difference between the two.
This is HW:
```
ioctl(18, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0xac15a7d0) = 0 <0.001409>
ioctl(18, SNDRV_PCM_IOCTL_SYNC_PTR, 0xaa601188) = 0 <0.000136>
ioctl(18, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0xac15a7d0) = 0 <0.000801>
ioctl(18, SNDRV_PCM_IOCTL_SYNC_PTR <unfinished ...>
[...]
```
And this is COPY:
```
ioctl(18, SNDRV_PCM_IOCTL_SYNC_PTR, 0xaa601360) = 0 <0.000144>
ioctl(18, SNDRV_PCM_IOCTL_SYNC_PTR, 0xaa601360) = 0 <0.000115>
[...]
ioctl(18, SNDRV_PCM_IOCTL_SYNC_PTR, 0xaa601360) = 0 <0.000122>
ioctl(18, SNDRV_PCM_IOCTL_START, 0xaa601360) = 0 <0.000232>
[the end]
```
These are the things that happen inside `libasound2`, not by MPD. This still suggests that this is not a MPD bug.

**Comment by MaxKellermann** [comment]
Some more information:
- with a "hw" PCM, libasound uses `SNDRV_PCM_IOCTL_WRITEI_FRAMES`
- with a "copy" PCM, libasound uses mmap
- on my computer, it "copy" works (via mmap and `SNDRV_PCM_IOCTL_HWSYNC`)
- on your Raspi, "copy" doesn't work, but it uses mmap and `SNDRV_PCM_IOCTL_SYNC_PTR` which is a fallback mode called `mmap_status_fallbacked` in libasound; this mode is used if mapping the status area fails:
```
mmap2(NULL, 4096, PROT_READ, MAP_SHARED, 18, 0x80000000) = -1 ENXIO (No such device or address) <0.000190>
```
This also fails in your "hw" trace, but since direct "hw" access doesn't use mmap, this still works.
So apparently, the problem occurs only in `mmap_status_fallbacked` mode!

**Comment by MaxKellermann** [comment]
This is how it looks on my Rpi3 with kernel 4.19.97-v7+ (same libasound2 version):
```
epoll_ctl(8, EPOLL_CTL_ADD, 16, {EPOLLOUT|EPOLLERR|EPOLLNVAL, {u32=1954547708, u64=9121850866041620476}}) = 0
[...]
ioctl(16, SNDRV_PCM_IOCTL_SYNC_PTR, 0x73100de8) = 0
ioctl(16, SNDRV_PCM_IOCTL_START, 0x73100de8) = 0
epoll_wait(8, [{EPOLLOUT, {u32=1954547708, u64=9121850866041620476}}], 16, -1) = 1
futex(0xdbb8f4, FUTEX_WAKE_PRIVATE, 1)  = 1
ioctl(16, SNDRV_PCM_IOCTL_SYNC_PTR, 0x73100de8) = 0
```
This is different: on your Pi, after the `SNDRV_PCM_IOCTL_START`, the file descriptor is never again reported "ready" by the kernel. But it's also using `mmap_status_fallbacked` (using `SNDRV_PCM_IOCTL_SYNC_PTR` instead of `SNDRV_PCM_IOCTL_HWSYNC`).
Where did you get your 5.10.3 kernel? That's the only obvious difference I see. (And you're using a Pi1 instead of Pi3?)

**Comment by timothyjward** [comment]
> Where did you get your 5.10.3 kernel?

I'm 99% certain that it's from here: https://github.com/raspberrypi/firmware/tree/1.20210107.master

> This also fails in your "hw" trace, but since direct "hw" access doesn't use mmap, this still works.
So apparently, the problem occurs only in mmap_status_fallbacked mode!

Would it help to try to force (or disable) mmap?

**Comment by MaxKellermann** [comment]
I just updated my Pi3 to the latest Buster kernel (5.4.83-v7+) and it works.

> Would it help to try to force (or disable) mmap?

Everything would help at this point. So yes, please.

**Comment by timothyjward** [comment]
I've tried setting mmap in `mpd.conf`, and using mmap_emul at various points in the alsa config, but nothing seems to work. 😞

**Comment by MaxKellermann** [comment]
I just updated to kernel 5.10.7-v7+, and now I can reproduce the problem. This really looks like a kernel bug. Only fixing the kernel will help. Report it to the Raspberry Pi foundation (stated there: https://www.raspberrypi.org/forums/viewtopic.php?t=288234).
I don't think I can help with this issue.

**Comment by timothyjward** [comment]
> I just updated to kernel 5.10.7-v7+, and now I can reproduce the problem. This really looks like a kernel bug. Only fixing the kernel will help. Report it to the Raspberry Pi foundation (stated there: https://www.raspberrypi.org/forums/viewtopic.php?t=288234).
> I don't think I can help with this issue.

Thanks for the confirmation, and the help debugging! I tried downgrading my kernel earlier and it killed my Pi - I was planning to reflash in the morning. It’s good to know that there is a sensible solution for me.

**Comment by DictumMortuum** [comment]
I have exactly the same issue, but with a twist: even though I didn't play around with your PCM configurations, I'm able to play _some_ audio formats, e.g. audio_format=44100:24:2 isn't playable, but other ones are.

**Comment by timothyjward** [comment]
> I have exactly the same issue, but with a twist: even though I didn't play around with your PCM configurations, I'm able to play _some_ audio formats, e.g. audio_format=44100:24:2 isn't playable, but other ones are.

That’s useful to know. If it has the same symptoms could you let the Pi foundation know in bug https://github.com/raspberrypi/linux/issues/4108
