### ISSUE TITLE
Android: include https support

### ISSUE THREAD

**Issue by davidalben** [MusicPlayerDaemon/MPD#1059]
In Raspberry Pi, MPD supports https links from client and plays them. In Android, don't.

I intend to use an old Android Phone as announcer to TTS sound files generated by Home Assistant / Google TTS integration, but these files are hosted in Home Assistant web server, under https. My system can play them in Raspberry Pi MPD, but can't in Android MPD.

Error: "Unsupported URI scheme".

**Comment by davidalben** [comment]
Thank you!

**Comment by captainnapalm** [comment]
I see this as closed as completed over 2 years ago. I do not get the same error, but it is still not working for me. I have the same use case as above, and I'm getting 

```
E/ exception: Failed to decode http://192.168.X.XXX:8123/api/tts_proxy/<random-sting>_en-gb_<random-string>_cloud.mp3; Error
```

@davidalben did you get this working?

**Comment by davidalben** [comment]
> @davidalben did you get this working?
@captainnapalm my problem was the lack of support of https in Android (it always worked using http). After update, yes, it is working fine with https.

Port 8123 means Home Assistant? I've just added MPD integration pointing to Android's IP and it works to TTS announces.

**Comment by captainnapalm** [comment]
I tried it on a different device and it seems to be working fine, so there must be something unique or different about my Pixel 1.

**Comment by davidalben** [comment]
> I tried it on a different device and it seems to be working fine, so there must be something unique or different about my Pixel 1.

Fine!
