### ISSUE TITLE
Permission error on Android 11 when reading mpd.conf

### ISSUE THREAD

**Issue by FeralHedgehog** [MusicPlayerDaemon/MPD#1061]
### Describe the bug
MPD running on Android 11 cannot access /storage/emulated/0/mpd.conf
MPD's app permissions in Android settings only show "Allow access to media only".
Probably has something to do with [scoped storage enforcement](https://developer.android.com/about/versions/11/privacy/storage).

## Expected Behavior
Settings in /storage/emulated/0/mpd.conf get loaded.

## Actual Behavior
Permission denied exception gets thrown.

## Version
0.22.4

## Log
D/ config_file: loading file /storage/emulated/0/mpd.conf
E/ exception: Failed to open '/storage/emulated/0/mpd.conf': Permission denied

**Comment by MaxKellermann** [comment]
Yeah, thanks to Google. This kind of access is now ultimately forbidden with no chance to go back.
