### ISSUE TITLE
Missing WinSelectEvents.hxx

### ISSUE THREAD

**Issue by brechtsanders** [MusicPlayerDaemon/MPD#1064]
I tried to build ncmpc 0.43 with MinGW-w64 and got the following error:
```
../src/event/BackendEvents.hxx:27:10: fatal error: WinSelectEvents.hxx: No such file or directory
```

I can't find the file `BackendEvents.hxx` or the definition `WinSelectEvents` anywhere.

**Comment by MaxKellermann** [comment]
There's no working port of ncmpc for Windows - at least I've never tried. That file missing is simple to solve: we could copy it over from MPD (ncmpc uses MPD's I/O event loop), but I'm certain there are other major problems with the port.
What curses implementation were you going to use?

**Comment by brechtsanders** [comment]
I have ncurses and pdcurses, so I can try with either.

**Comment by MaxKellermann** [comment]
I have copied the missing files from MPD now, but I have no time to test the Windows build right now. You're very welcome to report the problems that I expect to occur to you now - I'm not interested in ncmpc on Windows myself, but I'd be happy to support it for others.
