### ISSUE TITLE
Another assertion failure when scanning DB (ISO9660 archive plugin)

### ISSUE THREAD

**Issue by tobiasjakobi** [MusicPlayerDaemon/MPD#1067]
## Bug report
Hello folks,

I just updated mpd from 0.21.26 to 0.22.3 which triggered a complete flush and rescan of the database:
`exception: Tag list mismatch, discarding database file`

I guess this is correct behaviour.

However during the DB scan an assertion triggers:
```
mpd: ../mpd-0.22.3/src/archive/plugins/Iso9660ArchivePlugin.cxx:263: virtual size_t Iso9660InputStream::Read(std::unique_lock<std::mutex>&, void*, size_t): Assertion `offset % ISO_BLOCKSIZE == 0' failed.
```

Interestingly this happens with the exact same ISO I had trouble some while ago (bug #776). For the time being I disabled the ISO9660 plugin to avoid the crash.

Anything I can do to triage the problem (backtrace, debug output, e.g. for 'offset')?

With best wishes,
Tobias

## Expected Behavior
DB scan completes successfully.

## Actual Behavior
Assertion triggers during DB scan.

## Version
```
Music Player Daemon 0.22.3 (0.22.3)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local


Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [mpcdec] mpc
 [wavpack] wv
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa pulse httpd

Encoder plugins:
 null vorbis wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file io_uring archive alsa curl ffmpeg

Playlist plugins:
 extm3u m3u pls flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// srtp://

Other features:
 avahi dbus epoll icu inotify ipv6 tcp un
```

## Log
[Log snippet](https://gist.github.com/tobiasjakobi/7fd5a6d6af660a2a829992f6c67e8164)

**Comment by MaxKellermann** [comment]
Please don't link to logs - just paste them here as-is. In your other bug report, I can't access the log anymore.
And in your other bug report, you didn't make your ISO file available. In that bug, I could guess and deduce the problem from the log, which was enough to fix it. But in this case, I don't have anything.

**Comment by tobiasjakobi** [comment]
Hallo Max,
yes, you're right, that was probably not a good idea. I must have cleaned up my Gists in the last year.

Concerning the ISO, let me see what I can do about that...

-- Tobias

**Comment by tobiasjakobi** [comment]
I guess I never said thanks for fixing this, even though I failed to provide the ISO. So better late than never, thanks a bunch!
