### ISSUE TITLE
Status command returns wrong "volume" value after "play" command was executed

### ISSUE THREAD

**Issue by sumthief** [MusicPlayerDaemon/MPD#107]
Hello
I am trying to use command list to execute playback control command "play" and fetch updated status info.

Here is an output for MPD --version:
<pre>gregory@feihtmus ~ (master) $ mpd --version
Music Player Daemon 0.20.9

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un
</pre>

Query which I am sending to MPD is:
<pre>command_list_ok_begin
play
status
command_list_end</pre>

There is response which I got (tested via telnet and also my local project):
<pre>list_OK
volume: -1
repeat: 0
random: 1
single: 0
consume: 0
playlist: 2
playlistlength: 65
mixrampdb: 0.000000
state: play
song: 21
songid: 22
time: 0:246
elapsed: 0.000
bitrate: 0
duration: 245.551
nextsong: 47
nextsongid: 48
list_OK
OK</pre>

As you can see response contains state prop equal to "play" but volume prop is equal to -1 which is not what I am expecting to see.

Please could someone tell me if it's bug or not? And if it's not a bug what is a correct way to get actual value of volume prop after "play" command was executed.

Thanks.

**Comment by MaxKellermann** [comment]
This is just incomplete protocol documentation; MPD emits `-1` if it cannot determine the volume, e.g. if all mixers have failed, or if no mixer is configured at all.

**Comment by sumthief** [comment]
But when I am making an additional request (status command) through 500 ms I am getting actual result with right volume value.
What is correct way to handle this?

**Comment by sumthief** [comment]
Hope my comment will relieve someone for wasting time:
It looks like bug with Pulseaudio (with ALSA it works OK). Here is a link on additional source which confirms that it's a bug of Pulseaudio (https://help.ubuntu.com/community/MPD#Bugfix:_Pausing_loses_connection_with_Pulse_server)

**Comment by cykerway** [comment]
Had the same problem. It would be nice if the protocol always returns a valid volume in range `[0, 100]` if state is `play` or `pause`. If all mixers are down then it shouldn't be playing anyway.
