### ISSUE TITLE
How query all album with artist name?

### ISSUE THREAD

**Issue by entuccio** [MusicPlayerDaemon/MPD#1075]
I tried

>> list album 

but  it gives me only the name of the album.

What I want also the artist?

Thanks

**Comment by MaxKellermann** [comment]
`list artist group album`

**Comment by entuccio** [comment]
Thank you Max.

What If I want to obtain all the info? For example , album, artist, albumartist, folder, etc...etc....

I would like to have a list of all the album's info

**Comment by MaxKellermann** [comment]
You can specify more `group` clauses.  Why don't you read the protocol documentation? https://www.musicpd.org/doc/html/protocol.html#the-music-database

**Comment by entuccio** [comment]
Max, I carefully read it. 

But actually there'are a few example to better understand how to query, especially for more complex queries.

Example: 

I would like to obtain a list of all albums with artists and  path:_
>list album group artist group file

does it make sense?

Thank you for your patience and help
