### ISSUE TITLE
Query for filename

### ISSUE THREAD

**Issue by entuccio** [MusicPlayerDaemon/MPD#1076]
I just read the protocol documentation and seem that "list file" is deprecated.

So How can I query the list of all Album with their paths files?
I tried:
list file group Album 

but it doesn't work.

Sorry I don't want to bother you :-(

Thanks

**Comment by MaxKellermann** [comment]
What exactly does "their paths files" mean?

**Comment by entuccio** [comment]
Example: I would like to retrieve all album of The Beatles. But not only the name list. But also the path of the album (the folder which contains the song)

Example: 

output:
Artist: Beatles
Album: album 1
file: /dir/dir/dir/album 1
Artist: Beatles
Album: album 2
file: /dir/dir/dir/album 2
Artist: Beatles
Album: album 2
file: /dir/dir/dir/album 3

Thanks

**Comment by MaxKellermann** [comment]
"the folder which contains the song" -> which song? You were talking about album names previously.
If you know an album name, you can search for songs in that album, but that's a separate step. But I'm just guessing what you may want - you didn't spell it out clearly enough.

**Comment by entuccio** [comment]
Ok let me explain better mate.

I wrote song instead of songs.

I know that "list album group artist" give me a list containing all the album and the respective artist.

Since every album contains songs, Is there a way to obtain also the path of that folder?

Example output:

Artist: Beatles
Album: One
file: /dir/music/Beatles/One (which One is a folder)
Artist: XXX
Album: YY
file: /dir/music/XXX/YYY

What would be the bests queries to obtain this result? Thanks

**Comment by MaxKellermann** [comment]
You seem to assume that all songs matching a certain album name are in the same folder, but what if you have two copies of the same album? Or two artists release an album with the same name? Or if you didn't organize your music well, and files aren't sorted by album in the filesystem? Or it's a multi-disc album, and you have one folder for each ripped disc?
As I said, you can search for songs in an album, so just do that. MPD gives you everything then, and it's up to you to do something useful with it.

**Comment by entuccio** [comment]
I know it. Obviously, I assume that my library is well organized with Beets. 
My idea is this:

Since  "> list file group artist " doesn't work, one solution to use would be:

> list file "(album contains \"\")"

that  gives me the path of all files which tag "album" contains "" (empty)  
In this way I obtain a list similar to this:

...
~/Artist1/Album1/song1.mp3
~/Artist1/Album1/song2.mp3
~/Artist1/Album1/song3.mp3
~/Artist2/AlbumF/song1.mp3
~/Artist2/AlbumF/song2.mp3
~/Artist2/AlbumF/song3.mp3
~/ArtistX/AlbumC/song1.mp3
~/ArtistX/AlbumC/song2.mp3
~/ArtistX/AlbumC/song3.mp3
...
I can simply split every line with a script and put every artist, album, file, in an array. So I could manage it.

Does it make sense? There's a more elegant way to query MPD?

**Comment by MaxKellermann** [comment]
I already told you how to obtain information about an album. Doing `list file` is not a good idea, because you get too much data and it may overflow the output buffer, resulting in MPD aborting the connection to your client.

**Comment by entuccio** [comment]
Thank you
