### ISSUE TITLE
Why does a 88.2kHz flac take 100% of my CPU

### ISSUE THREAD

**Issue by monnier** [MusicPlayerDaemon/MPD#1077]
I recently got an album in wav format using 88.2kHz which I converted to flac with `ffmpeg` and I'm finding that my MPD server skips frequently when playing it because its CPU can't keep up: the CPU is pegged at 99%.

Clearly, my machine is not high powered (it's an old ARM SoC (Allwinner A10) using a Core A8 at 900MHz or so), but when playing my usual 44.1kHz flacs, MPD doesn't even get close to 10% of the CPU, so I'm rather surprised by the enormous jump in CPU use.

Obviously, I can convert my flac to a more "normal" 44.1kHz (the rest of my audio system is poor enough that I wouldn't be able to tell the difference), but I'd like to better understand the problem before I go there.

FWIW, this is on a Debian stable armhf system running Debian's `mpd` package (version 0.21.5-3).

**Comment by MaxKellermann** [comment]
Your MPD version is very old and unsupported.
If you see this with the latest version, post a "perf report".

**Comment by monnier** [comment]
> Your MPD version is very old and unsupported.
> If you see this with the latest version, post a "perf report".

I'm unlikely to run a "latest" version any time soon (I'll probably try
with Debian testing's 0.22.4, no idea how recent this is), but my
message was not meant as a bug report, more as a question of what might
be the source of the slowdown and what I can try to do as an end user to
diagnose (and later maybe fix or at least circumvent) the problem.

Which brings me to my next question: what would be a "perf report"?
Is there some debugging info that I can enable to get this or is there
a tool you recommend for that?

**Comment by MaxKellermann** [comment]
I've written a documentation section about it: https://www.musicpd.org/doc/html/user.html#profiler
You can get the latest MPD version for Debian Stable from: https://www.musicpd.org/download-unoff-debian/

**Comment by monnier** [comment]
> I've written a documentation section about it: https://www.musicpd.org/doc/html/user.html#profiler

Perfect, thanks,
