### ISSUE TITLE
Seeking backwards does not work (on Raspberry Pi Zero)

### ISSUE THREAD

**Issue by Mettanine** [MusicPlayerDaemon/MPD#1082]
Hi, I hope this is the right place to report this, apologies if not.

I'm running mpd on a Raspberry Pi (Zero) with Raspbian and it won't seek backwards.

mpc seek 10 works fine,
mpc seek -10 (or any other value) does not, it just skips a few milliseconds apparently.

I can however seek backwards with discrete values, i.e. jumping from 00:20 to 00:10 with mpc seek 00:10 works fine.

The mpd version is current (0.21.4) according to "apt-get install mpd"

**Comment by geneticdrift** [comment]
MPD had seeking bugs fixed in the following versions since 0.21.4

- 0.21.24 (2020/06/10)
- 0.21.20 (2020/02/16)
- 0.21.14 (2019/08/21)
- 0.21.12 (2019/08/03)
- 0.21.6 (2019/03/17)

Updating to a newer version might solve the problem or at least rule out it being already fixed.

**Comment by MaxKellermann** [comment]
True, 0.21.4 hasn't been supported for 2 years.
Sad Raspbian user, here's help: https://www.musicpd.org/download-unoff-debian/

**Comment by Mettanine** [comment]
Thank you, this is very helpful. Sorry for wasting your time, though. I
should have checked the current version beforehand.

Max Kellermann <notifications@github.com> schrieb am Mi., 10. Feb. 2021,
14:52:
