### ISSUE TITLE
How to install MPD on Mac OS Sierra

### ISSUE THREAD

**Issue by entuccio** [MusicPlayerDaemon/MPD#1083]
Hello,

I have an old MAc Mini 2011 with Mac Os Sierra 10.12.6

If I try to install mpd with homebrew it says:

mpd: macOS Mojave or newer is required for this software.

I tried to install an old version with 

brew install mpd@otherversion 

but it doesn't work.

Any suggestion?

Thank you

**Comment by MaxKellermann** [comment]
That is a Homebrew problem, not a MPD problem. This is not the right place to get help for Homebrew.
You can always compile MPD manually, without any distributions like Homebrew (if you don't want to ask the Homebrew people for help): https://www.musicpd.org/doc/html/user.html#compiling-from-source

**Comment by entuccio** [comment]
Thank you very much for your support. I'll do that :-)
