### ISSUE TITLE
Return audio format for queue / currentsong

### ISSUE THREAD

**Issue by gilphilbert** [MusicPlayerDaemon/MPD#1094]
## Feature request
I'm working on an audio player that focuses on audio quality; both viewing it in the library and filtering by it. Most of it is in place, but at the moment, displaying the queue and current song can require multiple requests since the current protocol doesn't return audio format information in the queue at all, and the currentsong API only returns audioformat information when the song is playing - if playback is stopped, no audioformat information is included in the response. The result is that I have to fetch this manually, meaning that a queue of 100 songs results in 101 requests instead of 1 and a status request has to be followed by a find/search.

It would be good if the queue and currentsong implementations always returned audioformat in the same response format as search/find to allow the client to quickly get audio format information when the queue changes/currently playing song changes.

If you have questions, ask away

**Comment by MaxKellermann** [comment]
c729f16dcdd37dd7a528ef8cb531f2e72aea12d6
