### ISSUE TITLE
Peculiar DSD pop/click issue on ARM iMx7d

### ISSUE THREAD

**Issue by kiwi-ed** [MusicPlayerDaemon/MPD#1096]
Hi, 

I'm experiencing a strange pop/click issue when playing DSDs on an iMx7D ARM platform. I've followed various DSD noise issues on this forum and until now I thought it was fixed. What is really strange is when the pops and clicks happen. After boot DSD rendering seems good, clean, but if for whatever reason MPD has to be restarted then the pops and clicks may appear.

Not every restart after boot will encourage the problem. Once the pop/clicks are present they remain for any DSD played. If MPD is then restarted a few more times then pops/clicks will disappear for the time MPD is up.

The pops and clicks have an interval of ~10-20 seconds yet still random is nature.

I've disabled most of the other applications in case they're interrupting somehow, the CPU usage is around %11 on DSD64. The network can be disabled leaving only MPD reading from a local SD card then outputting to an audiophile grade USB DAC.

I've tried a number of MPD 0.21.x versions and are currently on 0.21.26. At the moment due to an outdated compiler upgrading to MPD 0.22 is not possible.  

Platform: iMx7D
Kernel: 4.9.88
MPD 0.21.26

Any thoughts would be appreciated!

**Comment by MaxKellermann** [comment]
Your MPD version is too old and unsupported.
