### ISSUE TITLE
Build on x86_64 failed

### ISSUE THREAD

**Issue by AndriiZ** [MusicPlayerDaemon/MPD#1097]
## Bug report
Build from source failed 

## Expected Behavior
Build succed

## Actual Behavior
ninja: Entering directory `output/release'
[3/650] Compiling C++ object src/util/libutil.a.p/Alloc.cxx.o
../../src/util/Alloc.cxx: In function ‘void oom()’:
../../src/util/Alloc.cxx:32:2: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  (void)write(STDERR_FILENO, "Out of memory\n", 14);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[268/650] Compiling C++ object src/db/plugins/libdb_plugins.a.p/ProxyDatabasePlugin.cxx.o
../../src/db/plugins/ProxyDatabasePlugin.cxx: In function ‘bool SendGroup(mpd_connection*, TagType)’:
../../src/db/plugins/ProxyDatabasePlugin.cxx:413:47: warning: unused parameter ‘group’ [-Wunused-parameter]
 SendGroup(mpd_connection *connection, TagType group)
                                               ^~~~~
[419/650] Compiling C++ object src/decoder/plugins/libdecoder_plugins.a.p/FfmpegDecoderPlugin.cxx.o
FAILED: src/decoder/plugins/libdecoder_plugins.a.p/FfmpegDecoderPlugin.cxx.o
c++ -Isrc/decoder/plugins/libdecoder_plugins.a.p -Isrc/decoder/plugins -I../../src/decoder/plugins -Isrc -I../../src -I. -I../.. -I/usr/include/libbinio -I/usr/include/x86_64-linux-gnu -I/usr/include/opus -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O2 -g -Wvla -Wdouble-promotion -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wunused -Wno-non-virtual-dtor -ffunction-sections -fdata-sections -D_GNU_SOURCE -fPIC -DHAVE_UNIX -MD -MQ src/decoder/plugins/libdecoder_plugins.a.p/FfmpegDecoderPlugin.cxx.o -MF src/decoder/plugins/libdecoder_plugins.a.p/FfmpegDecoderPlugin.cxx.o.d -o src/decoder/plugins/libdecoder_plugins.a.p/FfmpegDecoderPlugin.cxx.o -c ../../src/decoder/plugins/FfmpegDecoderPlugin.cxx
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx: In function ‘void FfmpegDecode(DecoderClient&, InputStream*, AVFormatContext&)’:
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx:524:38: error: ‘AVFMTCTX_UNSEEKABLE’ was not declared in this scope
        : (format_context.ctx_flags & AVFMTCTX_UNSEEKABLE) != 0,
                                      ^~~~~~~~~~~~~~~~~~~
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx:524:38: note: suggested alternative: ‘AVFMTCTX_NOHEADER’
        : (format_context.ctx_flags & AVFMTCTX_UNSEEKABLE) != 0,
                                      ^~~~~~~~~~~~~~~~~~~
                                      AVFMTCTX_NOHEADER
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx: In function ‘std::set<std::__cxx11::basic_string<char> > ffmpeg_protocols()’:
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx:671:19: error: ‘av_demuxer_iterate’ was not declared in this scope
  while ((format = av_demuxer_iterate(&opaque)) != nullptr) {
                   ^~~~~~~~~~~~~~~~~~
../../src/decoder/plugins/FfmpegDecoderPlugin.cxx:671:19: note: suggested alternative: ‘av_demuxer_open’
  while ((format = av_demuxer_iterate(&opaque)) != nullptr) {
                   ^~~~~~~~~~~~~~~~~~
                   av_demuxer_open
[424/650] Compiling C++ object src/decoder/plugins/libdecoder_plugins.a.p/FluidsynthDecoderPlugin.cxx.o
ninja: build stopped: subcommand failed.

## Version
latest master

## Log
Ubuntu 18.04

**Comment by MaxKellermann** [comment]
Which FFmpeg version?

**Comment by MaxKellermann** [comment]
What was the latest version of MPD which succeeded to compile on that computer?

**Comment by AndriiZ** [comment]
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared

**Comment by AndriiZ** [comment]
I am building using this manual https://www.musicpd.org/doc/html/user.html

**Comment by AndriiZ** [comment]
First build on x86_64, previously I have built on arm

**Comment by MaxKellermann** [comment]
I've added a fix to branch v0.22.x
... but note that GCC 7 is too old to compile MPD; MPD requires a C++17 compiler, and GCC 8 is the first version which supports C++17 properly.
