### ISSUE TITLE
Will dop be supported on Windows 

### ISSUE THREAD

**Issue by aeeq** [MusicPlayerDaemon/MPD#1102]
## Feature request
Will dop be supported under Windows WASAPI ?

**Comment by MaxKellermann** [comment]
I don't think anybody is working on that.
But @ibmibmibm would the right guy to implement it, I guess!

**Comment by ibmibmibm** [comment]
Hi, I've implemented a version at https://github.com/ibmibmibm/MPD/tree/feature/wasapi-dop
I'm waiting #1014 being merged before creating a pull request.

**Comment by MaxKellermann** [comment]
Thanks @ibmibmibm! I've cherry-picked that feature.
