### ISSUE TITLE
Database proxy plugin modifies command

### ISSUE THREAD

**Issue by tonwi** [MusicPlayerDaemon/MPD#1108]
1.LOCAL SETUP (the good case):
    -) both mpd-music-files and mpd-database lie on MPD-SERVER (Debian);
    -) music-files are MOUNTED via NFS on MPD-CLIENT (raspberry);
    -) MPD-CLIENT manages its own mpd-database (parallel to 
       the SERVER's database).
    
    A command
    	[mpc] list "Artist" "Genre" "Chanson"
    	(retrieve all artists where genre="Chanson")
    given on either machines works WELL on both 
    MPD instances (SERVER, CLIENT).
    
    with: log_level "verbose"
    the logfiles show:
    
    MPD-CLIENT mpd.log:
    ....client: [0] opened from local
    ....client: [0] process command "list Album Genre "Chanson""
    ....client: [0] command returned 0
    
    MPD-SERVER mpd.log:
    ....client: [0] opened from local
    ....client: [0] process command "list Album Genre "Chanson""
    ....client: [0] command returned 0

    the result is easy to understand, for the command has been 
    sent twice: 
    first time on the CLIENT site; 
    a second time on the SERVER site.
    Both instances run independently;
    The installation of either mpd's seems to be ok.
    
    
2.SATELLITE SETUP (the bad case):
    as described in Documentation 
    https://www.musicpd.org/doc/html/user.html#configuring-database-plugins
    
    -) both mpd-music-files and mpd-database lie on MPD SERVER (Debian) again;
    -) music-files are NOT mounted but accessed from MPD-CLIENT (raspberry) via NFS;
    -) MPD-CLIENT (raspberry) uses the "database proxy plugin" 
       in order to access the very only mpd-database lying on MPD-SERVER.
    
    The same command as in 1.setup
    	[mpc] list "Artist" "Genre" "Chanson"
    fails on MPD-CLIENT site.
    
    with: log_level "verbose"
    the logfiles show:
    
    CLIENT mpd.log:
    .....client: [19] opened from local
    .....client: [19] process command "list Artist Genre "Chanson""
    .....exception: should be "Album" for 3 arguments
    .....client: [19] command returned 2

    SERVER mpd.log:
    ....client: [0] opened from MPD-SERVER:port
    ....client: [0] process command "list Artist "(Genre == \"Chanson\")""
    ....client: [0] command returned 2
    
    IMHOP the result can be understand as follows:
        -) mpc (on MPD-CLIENT site) sends a command (list "Artist" "Genre" "Chanson")
           to mpd-CLIENT;
        -) MPD-CLIENT gets a string (list "Artist" "Genre" "Chanson");
        -) MPD-CLIENT modifies the string - propably for further processing -
           but further processing doesn't take place in MPD-CLIENT,
           but the (now modified) command is forwarded to MPD-SERVER.
        -) MPD-SERVER gets the modified string 
           [list Artist "(Genre == \"Chanson\")"]
           instead of the original one
           [list "Artist" "Genre" "Chanson"];
        -) MPD-SERVER doesn't understand the string and returns error.
   
CONFIGURATION:

MPD SERVER (Debian 5.10.13-1~bpo10+1):
    libmpdclient2.....2.16-1
    mpd...............0.21.5-3
    
MPD CLIENT (Raspberrypi 5.10.11-v7+):
    libmpdclient2.....2.16-1
    mpd...............0.21.5-3
    
MPD SERVER
    Database:
        /var/lib/mpd/mpd.db
   
    music files:
        /home/Musik/Collection

MPD CLIENT 
    mpd.conf:
        ...
        music_directory "nfs://MPD-SERVER/home/Musik/Collection"
        ...
        ...
        database {
            plugin "proxy"
            host "MPD-SERVER"
            port "6600"
        }
        ...

## Expected Behavior
command given on CLIENT site
[mpc] list "Artist" "Genre" "Chanson"
retrieves all artists where genre="Chanson" 
from SERVER site database

## Actual Behavior
command given on CLIENT site
[mpc] list "Artist" "Genre" "Chanson"
returns nothing 
but an error message in CLIENT's logfile
exception: should be "Album" for 3 arguments

**Comment by tonwi** [comment]
using the backport versions on Debian (0.22.3-1~bpo10+2) as well as on Raspberry (0.22.3-1~bpo10+2) from KALIKO repository the described issue is solved.
A command
[mpc] list "Artist" "Genre" "Chanson"
sent from MPD-CLIENT to MPD-SERVER retrieves answer as expected!!

Sorry for any inconvenience
TONWI

**Comment by MaxKellermann** [comment]
See https://www.musicpd.org/help/
> make sure you have the latest MPD version (0.22.6)

That's why.
