### ISSUE TITLE
Playlists are missing tags

### ISSUE THREAD

**Issue by YellowOnion** [MusicPlayerDaemon/MPD#1113]
### Describe the bug
Adding songs to a playlist, then looking at the playlist (or reloading mpd), shows "unknown" for everything but the song title.

![image](https://user-images.githubusercontent.com/364160/109368169-15a31380-78fd-11eb-8ecb-2eb77a81c4fe.png)

Maybe related to file names?

![image](https://user-images.githubusercontent.com/364160/109368993-beeb0900-78ff-11eb-9f48-dbd06be72cff.png)

They do in fact play, it just doesn't load the tags.

## Expected Behavior

Should maintain tags when creating playlists.

## Addition info

These songs were "Cue" files which I previously deleted to remove duplication in MPD

related to #1010 ?

## Version
0.22.5

## Log

```
$ mpd --no-daemon -v
config_file: loading file /home/daniel/.config/mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.74.0
curl: with OpenSSL/1.1.1i
```

**Comment by MaxKellermann** [comment]
Your MPD version is outdated.
