### ISSUE TITLE
Compile from source: mpd.service startup issues

### ISSUE THREAD

**Issue by snflh47** [MusicPlayerDaemon/MPD#1114]
## Question
Hi MaxKellermann,

first of all: thanks a lot for all the work you put into mpd. It's a great piece of software and I've been using it (pre-compiled or as part of products like moode, volumio, etc.) for years.

Since most distributions have pretty old versions in their repositories, I was forced to compile from source for the first time and as I'm not too much of a developer myself, this turned out to be quite time consuming.

I'm not sure if this considered a bug or feature request, so here it is as a question:

mpd is supposed to be run as a service. When running install after compile, there are a few steps needed to get it to a running state, that I felt should be part of the installation script (just like they are when installing from a repository) or at least part of the documentation.

Here's some input you might want to add to the documentation (sorry this is no pull-request), based on a vanilla Ubuntu 20.04 LTS installation and mpd 0.22.7 in satellite configuration. The systemd part is actually kind of a change request, I guess?

**Installation pre-requisites**
`apt install cmake` is missing in the documentation

**First time installation steps**
```
# create service user and add to audio group to access sound devices
useradd -r -s /sbin/nologin mpd
usermod -a -G audio mpd

# create default directories in case mpd is started with default configuration
mkdir /var/lib/mpd/
mkdir /var/lib/mpd/playlists
touch /var/lib/mpd/sticker.sql
chown -R mpd:mpd /var/lib/mpd/
mkdir /var/log/mpd
chown -R mpd:mpd /var/log/mpd/

# enable service
systemctl enable mpd.service

# optional: disable socket so systemd does not occupy 6600/tcp
systemctl disable mpd.socket
```

Still, the service didn't start, as creation of the `pid` file was not possible due to a permission issue (`/run/mpd `is owned by `root` in a default setup). As a reboot-persistent workaround, I modified `[SERVICE] `part of `/usr/local/lib/systemd/system/mpd.service`. Not sure if this is the best way though:

```
 # Run ExecStartPre with root-permissions
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir /run/mpd
ExecStartPre=/usr/bin/chown -R mpd:mpd /run/mpd
# Run ExecStart with User=mpd / Group=mpd
ExecStart=/usr/local/bin/mpd --no-daemon
```

Reference: https://blog.hqcodeshop.fi/archives/93-Handling-varrun-with-systemd.html

**Comment by MaxKellermann** [comment]
Don't configure a pid file! This isn't needed, ever, if you use systemd. Back in the dark days of Linux, without systemd, pid files were an ugly kludge for sysvinit scripts.
Why do you believe cmake is necessary to build MPD?

**Comment by snflh47** [comment]
Well, I wouldn't know why, but the service seems to try and create a pid file. I just removed the `PermissionStartOnly` and `ExecPreStart` lines now, restarted and here we go again:

```
Feb 27 13:31:19 mpd systemd[1]: Starting Music Player Daemon...
Feb 27 13:31:21 mpd mpd[617]: Feb 27 13:31 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Feb 27 13:31:21 mpd mpd[617]: Feb 27 13:31 : exception: Failed to create pid file "/run/mpd/pid": Permission denied
Feb 27 13:31:21 mpd systemd[1]: mpd.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 13:31:21 mpd systemd[1]: mpd.service: Failed with result 'exit-code'.
Feb 27 13:31:21 mpd systemd[1]: Failed to start Music Player Daemon.
```

cmake: again, no developer here, but I tried to compile from source on a vanilla Ubuntu 20.04 box a couple of days ago, guided by the official docs, and somewhere in the process it was requested, else it wouldn't build. (I believe the error message was "try cmake or (somealternative)" - unfortunately I only documented the solution not the complete output. If it helps, I can spin up another box and retry the whole process.

Any thoughts about the documentation part mentioned above?

**Comment by MaxKellermann** [comment]
> Well, I wouldn't know why, but the service seems to try and create a pid file.

Only if you told MPD to create one. By default, MPD will *not* create a pid file!

**Comment by snflh47** [comment]
Oh, now I see where this is coming from: it's in the `mpd.conf` that was copied from another machine. That's the default config being installed when installing from an Ubuntu repository. _Wonder why they do that?_

Thanks for the hint!

**Comment by snflh47** [comment]
closing this issue/question: pid file problem resolved through comments. assuming hints about the documentation of the initial installation are not considered relevant.

Thanks again, MaxKellermann.
