### ISSUE TITLE
Windows cross-compile. Add jack support.

### ISSUE THREAD

**Issue by ansanes** [MusicPlayerDaemon/MPD#1116]
I've manage to crosscompile mpd for windows on a Debian buster environment.
The mpd.exe file generated doesn't include the jack output plugin.

What do I have to put in the build script to add the jack plugin to the generated binaries?

**Comment by MaxKellermann** [comment]
You need to cross-compile libjack and make it available during the MPD build.

**Comment by ansanes** [comment]
Thank you. I'll give it a try :-). 
Do you know about any guide or where to look for instructions on how to do this?

**Comment by MaxKellermann** [comment]
No, ask the JACK project for help.
