### ISSUE TITLE
dynamic playlist

### ISSUE THREAD

**Issue by kurt-vd** [MusicPlayerDaemon/MPD#1129]
How can I implement dynamic playlists, i.e. the content of the playlist is generated when the user loads it.
can .m3u files be taken over http? I could produce some .cgi behind

**Comment by MaxKellermann** [comment]
Yes, you can do `mpc load http://foo/bar.m3u`

**Comment by kurt-vd** [comment]
local files are stripped then.

I tought to serve a m3u generator on a local webserver, but I can't find a way to MPD accept the local file.
I don't want mpd to queue local files over a webserver

**Comment by naglis** [comment]
> local files are stripped then.

Yes, IIUC, adding arbitrary (outside `music_directory`) local files [is only allowed](https://musicpd.org/doc/html/protocol.html#command-add) when the client connects over local socket. Did a small test, if the webserver returns m3u with absolute paths to local files and `mpc load http://localwebserver/playlist.m3u` is done when connecting via local socket it should work.

**Comment by kurt-vd** [comment]
Thanks for your test.
I don't need to load arbitrary local files, I want to add known files from the database, so the metadata is already known before playing each file individually.

Some of my devices use the curl plugin to fetch the audio over network, so you might think you could load the streams there. but mpc does not correlate the files back to the metadata it has in the database, so even there it's not exactly where I wanted to get.

**Comment by MaxKellermann** [comment]
After answering the question, I assume the issue is solved.
