### ISSUE TITLE
Audible clicks while playing single flac + cue sheet

### ISSUE THREAD

**Issue by DenisSbragion** [MusicPlayerDaemon/MPD#113]
Hello,

I noticed audible clicks at track boundaries while playing single big flac albums along with cuesheets providing track lists into them. I have been able to reproduce the problem by creating a small flac file + cuesheet with a simple continuous sine tone in it and few tracks in the cuesheet and by reproducing it to a file through the recorder output plugin.

Attached a screenshot of the relevant portion of the resulting file loaded into Audacity, clearly showing the click at the track change. Attached there's also a zip with the test flac file and corresponding cuesheet.

I'm pretty sure I heard this happening also with some other compressed formats (like APE+CUE), but I didn't tested them explicitly. May be the root cause of the problem is the same.

Mpd is version 0.19.21, as provided by a stock Debian Stretch.

Hope this helps in solving the problem, and thanks for this excellent software.

Bye,

Denis Sbragion

![click](https://user-images.githubusercontent.com/32162088/30690332-1b1613e2-9ec4-11e7-86f3-f2b59e93b039.png)

[Sine.zip](https://github.com/MusicPlayerDaemon/MPD/files/1320725/Sine.zip)

**Comment by MaxKellermann** [comment]
Sorry, your MPD version is unsupported. Complain to the Debian project.

**Comment by DenisSbragion** [comment]
Hello Max,

thanks for replying. I quickly upgrade to 0.20.9 from Debian testing. It shows the same exact behaviour. 

Bye,

Denis Sbragion

**Comment by fschlich** [comment]
I can confirm this is still happening with mpd 0.20.14, so perhaps this issue should be reopened?
