### ISSUE TITLE
Playlists in satellite setup

### ISSUE THREAD

**Issue by SimonPersson** [MusicPlayerDaemon/MPD#1131]
## Feature request
When running multiple MPD servers in satellite mode, it would be nice to be able to share playlists in a central location on the "master" mpd server.

In fact, `mpc lsplaylist` is already able to list the available playlists on the master (although I have no idea how, because when I run the `listplaylists` command in a netcat session I get `ACK [5@0] {listplaylists} Stored playlists are disabled` back). It just isn't able to read them, or add them to the queue.

I can think of a couple of solutions:
* Add support for playlists in the proxy database plugin
* Create a proxy playlist plugin, similar to the database proxy plugin
* Allow `playlist_directory` to be an `nfs` mount, similar to `music_directory`

**Comment by MaxKellermann** [comment]
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/848
