### ISSUE TITLE
Read WebM TITLE information also from the tags

### ISSUE THREAD

**Issue by lbrayner** [MusicPlayerDaemon/MPD#1143]
## Feature request

Read WebM TITLE information also from the tags, not only from the TITLE segment
information element! In particular, the former should override the latter.

The WebM container is based on a profile of Matroska. MPD `0.22.6-1` ignores the
TITLE tag of TargetType 30, as in:

```
    <!-- ... -->
    <Tag>
        <Targets>
            <TargetTypeValue>30</TargetTypeValue>
        </Targets>
        <Simple>
            <Name>TITLE</Name>
            <String>12D3</String>
        </Simple>
        <Simple>
            <Name>PART_NUMBER</Name>
            <String>16</String>
        </Simple>
    </Tag>
    <!-- ... -->
```

**Comment by MaxKellermann** [comment]
MPD itself doesn't support this container format; it relies on FFmpeg to parse it, and FFmpeg is also responsible for extracting tags. Are you sure this is about MPD and not about FFmpeg?

**Comment by lbrayner** [comment]
> MPD itself doesn't support this container format; it relies on FFmpeg to parse it, and FFmpeg is also responsible for extracting tags. Are you sure this is about MPD and not about FFmpeg?

I did not know that! Will look into it.

**Comment by MaxKellermann** [comment]
Try `ffprobe` on that file. If it doesn't show the expected tags, it's a FFmpeg problem and has nothing to do with MPD.

**Comment by lbrayner** [comment]
`ffprobe` reports the tag as *TITLE-eng*; and the segment information element as *title*:

~~~
Input #0, matroska,webm, from '********-M1 A1-********.webm':
  Metadata:
    title           : M1 A1
    encoder         : *****************
    TOTAL_PARTS     : 20
    ALBUM           : ********
    ARTIST          : ********
    TITLE-eng       : M1 A1
    track           : 15
  Duration: 00:03:49.44, start: -0.007000, bitrate: 129 kb/s
~~~

This is the output of `ffprobe` with and mp3 file:

~~~
Input #0, mp3, from '10 You Ain't Gonna Find.mp3':
  Metadata:
    title           : You Ain't Gonna Find
    artist          : **********
    album           : Delay
    TYER            : 0
    track           : 10/0
    disc            : 0/0
  Duration: 00:04:22.84, start: 0.011995, bitrate: 256 kb/s
~~~

With an m4a file:

~~~
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '09 Clean.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    title           : Clean
    artist          : ************
    album_artist    : ************
    album           : ********
    genre           : Rock
    track           : 9/9
    disc            : 1/1
    compilation     : 0
    date            : 1990-03-19T12:00:00Z
    media_type      : 1
    sort_name       : Clean
    sort_album      : ********
    sort_artist     : ************
  Duration: 00:05:31.56, start: 0.047889, bitrate: 284 kb/s
~~~

MPD reads the ALBUM and ARTIST (in caps) metadata correctly, but may it doesn't
pick up TITLE-eng beacuse of the suffix? I have yet to look at the source code.

**Comment by MaxKellermann** [comment]
"TITLE-eng" is not "TITLE". Of course MPD doesn't use that. It doesn't match any tag name known to MPD. But any client can use the "readcomments" command to get all tags, even those not known to MPD.

**Comment by lbrayner** [comment]
I understand the problem lies with the container. MPD is already remarkable for its indirect support of multiple formats via `ffmpeg`.

My solution will be using a shell script to set the TITLE segment information element from the correct tag, like so:

~~~
title="$(xmllint --xpath "string(/Tags/Tag[Targets/TargetTypeValue = '30']/Simple[Name = 'TITLE']/String)" <( mkvextract tags audio_file.webm ))"
mkvpropedit audio_file.webm --set "title=${title}"
~~~

**Comment by MaxKellermann** [comment]
I guess we can close that because the file did not have proper tags.
