### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by zhouguannan** [MusicPlayerDaemon/MPD#1144]
## Permission denied
when I run "sudo systemctl start mpd"
### log:
Apr 24 20:54:39 ArchLinux mpd[43116]: exception: Failed to access /home/kevin/.config/mpd/playlists: Permission denied
Apr 24 20:54:39 ArchLinux mpd[43116]: exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Apr 24 20:54:39 ArchLinux mpd[43116]: exception: Failed to access /home/kevin/Music: Permission denied
Apr 24 20:54:39 ArchLinux mpd[43116]: exception: Failed to open '/etc/mpd/database': No such file or directory
Apr 24 20:54:39 ArchLinux mpd[43116]: exception: Failed to open database plugin; Can't create db file in "/etc/mpd": Permission denied
Apr 24 20:54:39 ArchLinux systemd[1]: mpd.service: Main process exited, code=exited, status=1/FAILURE
### this is my config /home/kevin/.config/mpd/mpd.conf

db_file            "/home/kevin/.config/mpd/database"
log_file "syslog"
bind_to_address "0.0.0.0"

user "mpd"
group "mpd"
music_directory    "/home/kevin/Music"
playlist_directory "/home/kevin/.config/mpd/playlists"
pid_file           "/home/kevin/.config/mpd/pid"
state_file         "/home/kevin/.config/mpd/state"
sticker_file       "/home/kevin/.config/mpd/sticker.sql"
audio_output {
    type        "pulse"
    name        "My Pulse Output"
    server        "127.0.0.1"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

**Comment by MaxKellermann** [comment]
That's a simple file permission problem. The user "mpd" doesn't have permission to access your music directory. This has nothing to do with MPD.
