### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by zhouguannan** [MusicPlayerDaemon/MPD#1146]
## All files in mpd.conf exist , which file is missing?
##config /etc/mpd.conf

audio_output {
    type        "pulse"
    name        "My Pulse Output"
    server        "127.0.0.1"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
## Version
Music Player Daemon 0.22.6 (0.22.6)
## Log
log file is empty

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by zhouguannan** [comment]
I tried many times and I could not find any useful information in the help and manual page,I don't know where the problem is.
### this is my configfile now
audio_output {
    type        "pulse"
    name        "My Pulse Output"
    server        "127.0.0.1"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory		"/var/lib/mpd/music"
log_file			"/home/kevin/.config/mpd/log"
log_level			"verbose"
default_permissions "admin"
port "2333"
### log
config_file: loading file /etc/mpd.conf
exception: bind to '0.0.0.0:2333' failed (continuing anyway, because binding to '[::]:2333' succeeded): Failed to bind socket: Address already in use
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.31
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.76.1
curl: with OpenSSL/1.1.1k
avahi: Initializing interface
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /var/lib/mpd/mpdstate
#### and
Apr 25 17:23 : zeroconf: No global port, disabling zeroconf
Apr 25 18:20 : zeroconf: No global port, disabling zeroconf
Apr 25 18:24 : zeroconf: No global port, disabling zeroconf
Apr 25 18:24 : state_file: Loading state file /var/lib/mpd/mpdstate
Apr 25 18:44 : state_file: Saving state file /var/lib/mpd/mpdstate
Apr 25 18:44 : fifo_output: Removing FIFO "/tmp/mpd.fifo"
Apr 25 18:46 : zeroconf: No global port, disabling zeroconf
Apr 25 18:46 : state_file: Loading state file /var/lib/mpd/mpdstate
