### ISSUE TITLE
What's the point of stickers when searching for them returns just a filename and not a playlist position?

### ISSUE THREAD

**Issue by Lovewyrm** [MusicPlayerDaemon/MPD#1152]
## Question
Tagged a few songs with a fave sticker, but querying for them just gives filenames, which are not that easy to use to tell MPD to play em in the playlist via mpc.

Am I missing something here? Other than a potential spoonfeeding?

mpc play wants a playlist position
mpc find with the filename tag just results in the same filename found
mpc find with the format of %position% while combining it with find only gives me the position '1'

Bleh.

P.S.:
I suppose
`mpc playlist -f ' [%position% %file%]' `
could prep a dataset that can be grepped for that, but my playlist is huge.

**Comment by MaxKellermann** [comment]
Sticker searches the database, not the queue/playlist. Therefore, there is no queue/playlist position associated with them.
