### ISSUE TITLE
Should playlists' tag scanners use GetRealURI instead of GetURL

### ISSUE THREAD

**Issue by Rio6** [MusicPlayerDaemon/MPD#1154]
## Question

While browsing the code, I noticed DetachedSong has a GetRealURI that can be used to separate visual URIs and actual resource URIs. I also found that the tag scanner used by playlist doesn't use this function. Is this intended or a bug?

This is the code I'm talking about
```diff
diff --git a/src/command/PlaylistCommands.cxx b/src/command/PlaylistCommands.cxx
index 74aa9596c..c6c95706b 100644
--- a/src/command/PlaylistCommands.cxx
+++ b/src/command/PlaylistCommands.cxx
@@ -92,7 +92,7 @@ handle_load(Client &client, Request args, [[maybe_unused]] Response &r)
        auto &instance = client.GetInstance();
        const unsigned new_size = playlist.GetLength();
        for (unsigned i = old_size; i < new_size; ++i)
-               instance.LookupRemoteTag(playlist.queue.Get(i).GetURI());
+               instance.LookupRemoteTag(playlist.queue.Get(i).GetRealURI());
 
        return CommandResult::OK;
 }
```

Thanks

**Comment by MaxKellermann** [comment]
You are right. Though this is a theoretical problem, because there is no playlist plugin which has differente values for "uri" and "real_uri".

**Comment by Rio6** [comment]
Thanks, good to know.

I saw this when reading the playlist plugin code from youtube-dl fork. (youtube-dl doesn't need real_uri either, but I found this code anyway).

You think this worth a PR? I think it can benefit future plugins in case they need it, I'm just not sure if any existing plugins depend on this behaviour. But if no plugins uses real_uri as you mentioned then it should be fine.

**Comment by Rio6** [comment]
nvm, just saw the commit
