### ISSUE TITLE
F-Droid version incompatible with HiMedia Q10 Pro (Android 7)

### ISSUE THREAD

**Issue by andreimpopescu** [MusicPlayerDaemon/MPD#1160]
Hello,

MPD is shown as "Incompatible" on F-Droid app store on HiMedia Q10 Pro (Android 7).

Forcing the install results in a rather uninformative error:

> Error installing MPD
> Failed to install due to an unknown error

With `adb` there is slightly more information:

`$ adb install org.musicpd_41.apk
adb: failed to install org.musicpd_41.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

The version from Google Play Store installs and works fine, but I'd rather get rid of the Play Store completely on this device (latest firmware requires installing it manually and MPD is the only app that I can't get from other sources).

**Comment by MaxKellermann** [comment]
This project does not publish any releases to F-Droid. I don't know who does, but it's not this project.

**Comment by andreimpopescu** [comment]
Sorry for the noise, I wasn't aware of that.
