### ISSUE TITLE
AAC low volume

### ISSUE THREAD

**Issue by ArturNadolski** [MusicPlayerDaemon/MPD#1162]
Example stream: https://stream.open.fm/11

Stream info from VLC:
AAC(mp4a)
sample rate: 44100 Hz
bits per sample: 32
AAC extension: SBR+PS

AAC streams are at very low volume corespondig to other streams (mp3, flac).
Any suggestion how to "normalize" volume switching between mp3 stream and aac? Maybe bump up volume olny for AAC streams?

**Comment by MaxKellermann** [comment]
There's the "normalize" filter plugin: https://mpd.readthedocs.io/en/stable/plugins.html#normalize
.. which can be enabled with the global option `volume_normalization`
