### ISSUE TITLE
How to build multi arch apk for Android

### ISSUE THREAD

**Issue by linsui** [MusicPlayerDaemon/MPD#1164]
## Question
How to build multi arch apk for Android?  I tried

```
../../android/build.py $$SDK$$ $$NDK$$ armeabi-v7a
../../android/build.py $$SDK$$ $$NDK$$ arm64-v8a
meson configure
ninja android/apk/mpd-unsigned.apk
```

but in the apk there is only a libmpd.so in armeabi-v7a.

**Comment by MaxKellermann** [comment]
That needs another script which is out-of-tree ... but your report is a good time to fix this up properly and commit it to git.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
Kindly ping. Could you please share the script? Thanks!

**Comment by linsui** [comment]
Just remove the `rm -rf` line from android/apk/make-unsigned-apk.sh and add `--reconfigure` to android/build.py is enough.
