### ISSUE TITLE
Random core dump

### ISSUE THREAD

**Issue by Wumianzhe** [MusicPlayerDaemon/MPD#1168]
### Describe the bug
Probably since update to 22.7 mpd sometimes crashes. Usually happens in first couple minutes of playing.
Was unable to cause this in any method other than waiting

## Expected Behavior
Continue playing music

## Actual Behavior
Core dump

## Version
Music Player Daemon 0.22.7 (0.22.7)

## Log
mpd: ../src/input/LastInputStream.cxx:42: void LastInputStream::OnCloseTimer(): Assertion `is' failed.

**Comment by MaxKellermann** [comment]
This is impossible. This code does not exist in version 0.22.7. Please post correct information.
