### ISSUE TITLE
Cannot compile under MinGW

### ISSUE THREAD

**Issue by neheb** [MusicPlayerDaemon/MPD#1171]
## Version
lasest master

## Log
```
../src/sticker/Database.cxx:85:3: error: no matching constructor for initialization of 'Sqlite::Database'
        :db(path.c_str())
         ^  ~~~~~~~~~~~~
../src/lib/sqlite/Database.hxx:29:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'StringPointer<wchar_t>::const_pointer' (aka 'const wchar_t *') to 'const Sqlite::Database' for 1st argument
class Database {
      ^
../src/lib/sqlite/Database.hxx:35:11: note: candidate constructor not viable: no known conversion from 'StringPointer<wchar_t>::const_pointer' (aka 'const wchar_t *') to 'const char *' for 1st argument
        explicit Database(const char *path);
                 ^
../src/lib/sqlite/Database.hxx:42:2: note: candidate constructor not viable: no known conversion from 'StringPointer<wchar_t>::const_pointer' (aka 'const wchar_t *') to 'Sqlite::Database' for 1st argument
        Database(Database &&src) noexcept
        ^
../src/lib/sqlite/Database.hxx:33:2: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
        Database() = default;
        ^
1 error generated.
ninja: build stopped: subcommand failed.
```

And many more like it. The issue is that path in this case is an std::wstring being sent to a constructor that expects const char* instead of const wchar_t *.  Related to https://github.com/MusicPlayerDaemon/MPD/blob/master/src/fs/Traits.hxx#L45 I think. I had to pass -Dudisks=disabled -Dicu=disabled -Dbzip2=disabled to even get this far.

As an aside, can't std::filesystem be used here?

**Comment by MaxKellermann** [comment]
> As an aside, can't std::filesystem be used here?

I wish. But `std::filesystem` is a horrible and bloated API. And anyway, switching to `std::filesystem` doesn't change anything about this problem: this problem comes from the fact that `sqlite3_open()` wants a `char*`, but both MPD's `Path` and `std::filesystem::path` contain a `wchar_t*`
