### ISSUE TITLE
Support M4A tag "AlbumSortOrder"

### ISSUE THREAD

**Issue by Sonico98** [MusicPlayerDaemon/MPD#1173]
I feel like this fits more as a feature request than a bug.

Tagging programs don't tend to write, for example, "ALBUMSORT" explicitly to AAC files. Instead, "ALBUMSORTORDER" [seems to be used](https://help.mp3tag.de/main_tags.html) ([image](https://a.pomf.cat/uaiobn.png)). I've tried this with mp3tag, foobar2000, kid3-qt, and letting qaac handle the conversion from FLAC to AAC automatically.
Using ffprobe, the tag shows as:
```
     sort_album      : Kantai at All Speed! Trancetic EURO
     album           : 『艦隊全速！Trancetic EURO』
```
This, of course, results in mpd not reading the tag at all.
```
mpc -f "[%albumsort%] // %artist% - %title%" -p 7070
 // 神斬ゼロ式 - Trancetic EUROで『第五戦隊の出撃』
```
If we, however, force the "ALBUMSORT" tag, which is only possible to do with kid3-qt (as far as I know), then mpd can read the sort tag correctly.
```
mpc -f "[%albumsort%] // %artist% - %title%" -p 7070
Kantai at All Speed! Trancetic EURO // 神斬ゼロ式 - Trancetic EUROで『鎮守府の午後』
```
While forcing the tag with kid3 works, it is not ideal: modifying the tags in any way with any other program will just result in the forced tag being converted back to "ALBUMSORTORDER". And kid3 doesn't handle multiple tag values, but that's another problem.

If any additional information is needed, please ask. I've tried to look at the code to see if I could do anything but since I don't know C++ yet, I couldn't figure out what to do :(

**Comment by MaxKellermann** [comment]
Your link states that "AlbumSortOrder" is a WMA tag, but not a M4A tag. And anyway, mp3tag is a proprietary application and its use with MPD is not supported.
Do you have an authoritative definition of the M4A tag "AlbumSortOrder"?

**Comment by Sonico98** [comment]
You're right, I got it wrong. I confused the tag name because of reading both the iTunes column on the link provided and on the foobar2000 properties dialog.
Looking more into it, seems like the information is stored as the "soal" atom in the file, as it can be seen on the [Musicbrainz Picard documentation](https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_v2.6_[en].pdf) (page 192), on the [metamorphose documentation](https://fossies.org/dox/metamorphose2_0.8.2/classmutagen_1_1mp4_1_1MP4Tags.html) (a mass file renamer), on [mutagen's documentation](https://mutagen.readthedocs.io/en/latest/api/mp4.html) and on the [hydrogenaudio wiki](https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping), as there's no defined standard for m4a tags. 
Since Picard is open source, I guess it works better as an example. The program shows the tag to the user as "Album Sort Order"

As for a definition of the tag, it'd be the same as for the one defined in [the id3 standard](https://id3.org/id3v2.4.0-frames):
> The 'Album sort order' frame defines a string which should be used instead of the album name (TALB) for sorting purposes. E.g. an album named "A Soundtrack" might preferably be sorted as "Soundtrack".
So, its purpose is the same as the AlbumSort tag mpd already uses. Hope this helps, and thanks.

**Comment by MaxKellermann** [comment]
MPD supports the ID3 tag "TSOA" and maps it to AlbumSort:
https://github.com/MusicPlayerDaemon/MPD/blob/8a9d678bac2fa23af850343975059297bcbbae2a/src/tag/Id3Scan.cxx#L337
There is no "AlbumSortOrder" in ID3. The frame name is "TSOA", nothing else. "Album sort order" is part of the explanatory text, but is not a technical name.
All tags named "AlbumSort" are supported by all codecs, as described in the Picard manual.

But this request is about M4A. Your references say its name is "soal" and not "AlbumSortOrder", which means your initial feature request was wrong.

**Comment by Sonico98** [comment]
Yes, my initial feature request was wrong, I'm sorry. Should I edit it, or just leave it as is? Thanks

**Comment by MaxKellermann** [comment]
No that's ok, I just wanted to know explicitly, so we both agree what we're talking about.
But what would be useful is an example M4A file. It doesn't need to contain any real (copyrighted) music, just the tag you wish to see supported by MPD.

**Comment by Sonico98** [comment]
Here is an example file, zipped so I could upload it to github. I've downloaded a [freely available flac from archive.org](https://archive.org/details/cj2009-10-05.ku100_at37) and converted it to m4a using ffmpeg. Using Picard, added the tag to it with the value "this is an example for mpd" and removed all other tags. Hope this helps.
[example_m4a.zip](https://github.com/MusicPlayerDaemon/MPD/files/6542253/example_m4a.zip)

Sorry for the inaccuracies on my side, but I'm glad we could agree in what we're talking about in the end. Thanks for your time.
