### ISSUE TITLE
MPD stops playing the current queue when not empty

### ISSUE THREAD

**Issue by owl770** [MusicPlayerDaemon/MPD#119]
Hi,

I’m having a problem whereby mpd stops playing the current queue even when there are still songs to play.

I am running Music Player Daemon 0.21 (v0.20.10-423-g030f87c) on a Raspberry Pi Model 3.

I normally run mpd with consume=on, random=on, single=off, repeat=off, xfade=10 so that it gradually ‘eats’ the songs in the queue as they are played randomly.

I also have a python script that plays ‘announcements’ (eg, someone at the front door, we lose internet access, it recognises a number plate at the front gate etc). It does this by:
1)	Getting the position of the currently playing song
2)	Stops the current song
3)	Sets single=on, crossfade=0
4)	Adds the announcement track at position 0
5)	Plays the announcement track
6)	Waits for it to play completely
7)	Resets single=off, crossfade=10
8)	Seeks the previous song to the point where we stopped it
9)	Plays the previous song from that point

It works perfectly 98% of the time.

From my investigation, it appears the problem is introduced at step 8 where the script does the “seek” and I believe it might be a bug in mpd.

My debugging so far has shown:

Player::Run() is falling out of the while(true) loop at the break just after pc.outputs.Drain(); indicating that the queue is empty (which it is not) and causing the player to stop.
Under normal conditions _order as passed to Queue::GetNextOrder() is zero when it goes to get the next song. This means that GetNextOrder() “normally” returns 1 (_order + 1) as long as there is something in the queue.
When the announcement script does the seek (step 8 above), handle_seek() in PlayerCommands.cxx calls playlist::SeekSongPosition() which calls playlist::SeekSongOrder() which sets current to the song being seeked on.
If the song being seeked on is second last or last in the queue (ie. current is close to length), the next time Queue::GetNextOrder() is called, it returns -1 indicating the queue is empty, which causes mpd to stop playing after the current song, even though there may be other songs in the queue.

Is anyone able to verify my analysis and confirm the issue?

Please let me know if I am doing “something wrong”.  ;) 

Thanks in advance.

**Comment by MaxKellermann** [comment]
Your bug report was an excellent starting point to find the problem. I wish all bug reports were like this!

**Comment by owl770** [comment]
Hey Max, I have found another condition where mpd stops playing even when there are still songs in the queue. Do you want me to open a new issue or add it to this one? Thanks.

**Comment by MaxKellermann** [comment]
New one.
