### ISSUE TITLE
Strange Seeking Issues on opus/ogg files

### ISSUE THREAD

**Issue by jaredreardon** [MusicPlayerDaemon/MPD#1202]
### Describe the bug
When seeking on opus or ogg files, using either ncmpcpp's seeking functionality or with mpc, the seeking is far from normal. It often skips directly to the next or previous song if you skip too early after beginning a song. On other occasions, if you play a song then skip 5 seconds or so, it will simply boot you back to the beginning of the song rather than advancing you forward 5 seconds.

## Expected Behavior
If you seek forward or backwards it should seek in the song by that amount in opus and ogg files, just as it does in mp3 files.

## Actual Behavior
When seeking opus or ogg files within the first few moments of opening a song, it will either skip to the next or previous song or go back to the beginning of the current song, rather than skipping forward or backwards by the amount specificed.

## Version

mpd-0.22.9-1

## Log

Jul 07 22:04 : exception: Default TCP listener setup failed, but this is okay because we have a $XDG_RUNTIME_DIR listener: Failed to bind to '[::]:6600'; Failed to bind socket: Address already in use
Jul 07 22:04 : libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
Jul 07 22:04 : vorbis: Xiph.Org libVorbis 1.3.7
Jul 07 22:04 : opus: libopus 1.3.1
Jul 07 22:04 : sndfile: libsndfile-1.0.31
Jul 07 22:04 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Jul 07 22:04 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Jul 07 22:04 : simple_db: reading DB
Jul 07 22:04 : exception: Input plugin 'tidal' is not configured: No Tidal application token configured
Jul 07 22:04 : exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
Jul 07 22:04 : curl: version 7.77.0
Jul 07 22:04 : curl: with OpenSSL/1.1.1k

**Comment by MaxKellermann** [comment]
You omitted vital parts of the bug report.

**Comment by jaredreardon** [comment]
> You omitted vital parts of the bug report.

My apologies for that! I updated the bug report. Hopefully this is sufficient? If not, just inform me of what to do so I can update it to be of more use!

**Comment by MaxKellermann** [comment]
The log doesn't show any attempt of playback. This part is important for me to see, because this way I know which decoder plugin is used.

**Comment by jaredreardon** [comment]
> The log doesn't show any attempt of playback. This part is important for me to see, because this way I know which decoder plugin is used.

My bad for not putting it in there the first time. If anything else is needed that could be of help narrowing the issue down, don't hesitate to let me know.

**Comment by jarnos** [comment]
Why is this issue closed?  I have 0.22.11 and I am not able to seek opus stream.

**Comment by jarnos** [comment]
My stream was recorded by `ffmpeg -i "$stream" -c copy output.opus`
