### ISSUE TITLE
audion plays for 2 seconds 

### ISSUE THREAD

**Issue by RickyBurton** [MusicPlayerDaemon/MPD#1205]
Hi, I hope someone can help. I add a URL, http://ais.absoluteradio.co.uk/absolute80s.aac

Update database and play, but audio plays for around 2 seconds and cuts off. Any guidance would be appreciated.

**Comment by skidoo23** [comment]
Could not reprocude with MPD from git master on Debian testing x64. Plays music and commercials with 50 kbit/s - Please have a look at https://mpd.readthedocs.io/en/stable/user.html#troubleshooting

**Comment by RickyBurton** [comment]
I don't get what you are saying?

**Comment by skidoo23** [comment]
Click on link, read text, follow instructions and post output as a start.

**Comment by MaxKellermann** [comment]
Can't reproduce. Since the submitter decided not to post the information they were asked to, I'm closing this.
