### ISSUE TITLE
Pipewire: audio_output "pipewire" and "alsa" makes MPD hang after switnching to next song

### ISSUE THREAD

**Issue by zarkone** [MusicPlayerDaemon/MPD#1207]
## Bug report

`alsa`, `pipewire` outputs are hanging after fisrt\second song switch on Pipewire. `pulse` works good though.

**I've switched `audio_output` to "pulse" and it get back to normal -- using this as a workaround at the moment**

```
audio_output {
  type "pulse"
}
```

### Describe the bug

MDP player started to hang after song switch after I've switched to  Pipewire. 

I've built MPD master with pipewire support, but I see the same behavior -- still hangs on song switch. After removing audio output, MPD falls back to `alsa` -- and same behavior again. sometimes it is first song, sometimes second. 

`log_level "verbose"` doesn't give any additional info when hang happens.

I came across this issue which looks related: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1350
Couple of people who seem to have the same issue: https://github.com/samhh/dotfiles/issues/209

## Expected Behavior

song should switch without hang

## Actual Behavior

player hangs. Switching to next song doesn't work. Restart doesn't help.

## Version

https://github.com/MusicPlayerDaemon/MPD/commit/d39b11ba5d0f9e36e59f1fdf7321bcd64c3bfe26
```
Music Player Daemon 0.23~git (0.23~git)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify systemd tcp un
```

## Log

no log were emitted at the moment of song switch

**Comment by MaxKellermann** [comment]
The PipeWire related bug was fixed in commit 6015960871bd6267f0565601718f517cd4c97652
Since this bug report mixes two different bugs, and you provided no information about the ALSA problem, I suggest you write a new bug report for that, and include a verbose log since the start of playback until the problem occurs.
