### ISSUE TITLE
No sound and only Dummy output on Home Assistant supervised

### ISSUE THREAD

**Issue by nmisha** [MusicPlayerDaemon/MPD#1215]
### Describe the bug
No sound and only Dummy output on Home Assistant supervised.

I tried speaker-test in audio docker and test ok.

## Expected Behavior
sound via 3.5 jack

## Actual Behavior
Clean installation. On raspberian and dietpi.

## Version

 1.7.0 

## Log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[17:15:16] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[17:15:17] INFO: Setup settings
[17:15:17] INFO: Use custom config
[cont-init.d] setup-settings: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:15:18] INFO: Start MPD
[17:15:20] INFO: Start ympd
MPD Connecting to 127.0.0.1:6600
MPD connected.
player: played "1.mp3"

**Comment by MaxKellermann** [comment]
MPD version 1.7.0 does not exist, and no MPD version ever printed that message on `mpd --version`. Therefore I must assume you're not actually using MPD.

**Comment by nmisha** [comment]
I wrote version of add-on from Home Assistant interface.

Right version of mpd: Music Player Daemon 0.22.3 (v20200917-4836-g01e95b3599)

**Comment by MaxKellermann** [comment]
Version 0.22.3 is old and not supported.
