### ISSUE TITLE
mpd - pipewire

### ISSUE THREAD

**Issue by dksoftware2130** [MusicPlayerDaemon/MPD#1223]
### Describe the bug
no audio output on my fedora 34 (pipewire) machine - on fedora 33 (pulseaudio) if had works
what should pipewire do? TARGET ID?????

Setting | Description
-- | --
target ID | Link to the given target id.

## Version
mpd-0.22.10-1.fc34.20210809.dk.sandybridge.x86_64

[root@buildserver:~]$ cat /home/builduser/rpmbuild/SPECS/mpd.spec 
# Paket ist nicht auf alten Systemen im Einsatz
%global optflags $(sed "s/sandybridge/%{mtune2}/g" <<< "%{optflags}")

Name:              mpd
Version:           0.22.10
Release:           1%{?dist}.%{mtune2}
Epoch:             3
Summary:           The Music Player Daemon
License:           GPLv2+
URL:               https://www.musicpd.org/
Source:            %{name}-%{version}.tar.xz
Source1:           %{name}.service
BuildRequires:     autoconf
BuildRequires:     boost-devel
BuildRequires:     ffmpeg-devel
BuildRequires:     glib2-devel
BuildRequires:     lame-devel
BuildRequires:     libupnp-devel
BuildRequires:     libid3tag-devel
BuildRequires:     pulseaudio-libs-devel
Requires(pre):     shadow-utils

%description
Music Player Daemon allows remote access for playing music and
managing playlists. MPD is designed for integrating a computer
into a stereo system that provides control for music playback
over a local network

%prep
%setup -q

%build
export CFLAGS="%{optflags} -fPIE -flto=%(nproc)"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -pie %{optflags} -flto=%(nproc)"
%meson --buildtype=release --strip -Db_ndebug=true --auto-features=disabled -Dffmpeg=enabled -Dhttpd=true -Did3tag=enabled -Dlame=enabled -Dpulse=enabled -Dalsa=enabled -Dpipewire=enabled -Dflac=enabled
ninja -C x86_64-redhat-linux-gnu

%install
cd x86_64-redhat-linux-gnu
DESTDIR=%{buildroot} ninja install
mkdir -p %{buildroot}%{_sharedstatedir}/%{name}/playlists %{buildroot}%{_sharedstatedir}/%{name}/music %{buildroot}%{_unitdir}
rm -rf %{buildroot}%{_docdir}/%{name} %{buildroot}/usr/share/icons/hicolor/scalable/apps/mpd.svg
install -m 0644 %{SOURCE1} %{buildroot}%{_unitdir}
strip --strip-unneeded %{buildroot}%{_bindir}/%{name}

%pre
getent group %{name} &> /dev/null || groupadd -r %{name}
getent passwd %{name} &> /dev/null || useradd -r -g %{name} -d %{_sharedstatedir}/%{name} -s %{_sbindir}/nologin -c "Music Player Daemon" %{name}
exit 0

%post
chown -R %{name}:%{name} %{_sharedstatedir}/%{name}/ &> /dev/null
%{_sbindir}/groupmems -a %{name} -g audio &> /dev/null
%{_sbindir}/groupmems -a %{name} -g jackuser &> /dev/null
%{_sbindir}/groupmems -a %{name} -g polkituser &> /dev/null
%{_sbindir}/groupmems -a %{name} -g pulse &> /dev/null
%{_sbindir}/groupmems -a %{name} -g pulse-access &> /dev/null
%{_sbindir}/groupmems -a %{name} -g pulse-rt &> /dev/null
%{_sbindir}/groupmems -a %{name} -g rtkit &> /dev/null
exit 0

%files
%{_bindir}/%name
%attr(0644, root, root) %{_unitdir}/%{name}.service
%attr(-,%{name},%{name}) %dir %{_sharedstatedir}/%{name}
%attr(-,%{name},%{name}) %{_sharedstatedir}/%{name}/playlists
%attr(-,%{name},%{name}) %{_sharedstatedir}/%{name}/music

**Comment by dksoftware2130** [comment]
[root@srv-dksoft:~]$ cat /etc/mpd.conf
music_directory                  "/data/Musik"
playlist_directory               "/data/Musik/Playlists"
db_file                          "/var/lib/mpd/mpd.db"
log_file                         "/dev/stdout"
#state_file                       "/run/mpd/mpdstate"
state_file                       "/var/lib/mpd/mpdstate"
user                             "mpd"
bind_to_address                  "0.0.0.0"
port                             "6600"
log_level                        "default"

connection_timeout                "60"
max_connections                   "20"
max_playlist_length               "100000"
max_command_list_size             "2048"
max_output_buffer_size            "32768"
audio_buffer_size                 "32768"

save_absolute_paths_in_playlists  "no"
metadata_to_use                   "artist,album,title,track,name,genre,date"

audio_output {
 type                             "pulse"
 enabled                          "yes"
 always_on                        "yes"
 name                             "Pulseaudio"
 auto_channels                    "no"
 auto_format                      "no"
 auto_resample                    "no"
 replaygain                       "track"
 replay_gain_handler              "mixer"
 mixer_type                       "hardware"
 volume_normalization             "no"
}
 
audio_output {
enabled                          "yes"
always_on                        "yes"
type                             "httpd"
name                             "mpd-stream"
encoder                          "lame"
bind_to_address                  "0.0.0.0"
port                             "8000"
bitrate                    "320"
format                           "44100:16:2"
replay_gain_handler              "none"
}
audio_output {
type                             "alsa"
name                             "My ALSA Device"
device                           "hw:0,0"
mixer_type                       "hardware"
mixer_device                     "default"
mixer_control                    "PCM"
mixer_index                      "0"
auto_channels                    "no"
auto_format                      "no"
auto_resample                    "no"
replaygain                       "track"
replay_gain_handler              "mixer"
volume_normalization             "no"
}

**Comment by dksoftware2130** [comment]
???? why not work

audio_output {
type "pipewire"
name "Pipewire"
}

**Comment by MaxKellermann** [comment]
This bug report confuses me. I have no idea what all of this means. But I can answer this one:

> ???? why not work
> 
> audio_output {
> type "pipewire"
> name "Pipewire"
> }

This is a MPD 0.23 feature, but you're using MPD 0.22.

**Comment by jansol** [comment]
You can make pipewire emulate pulseaudio by installing the pipewire-pulse (or something similar) package. Then the old pulse output should work exactly as it did on the previous version of fedora.
