### ISSUE TITLE
0.22.10 wav files with embedded information, the information obtained is garbled

### ISSUE THREAD

**Issue by lazybat** [MusicPlayerDaemon/MPD#1226]
### Describe the bug
Using MPD 0.22.10 to scan wav files with embedded information, the information obtained is garbled.
MPD 0.21.11 is correct.
ex:0.22.10
rock64@rock64:~$ mpc
??▒??????֮?? - Citizen of the Sun
[playing] #1/2   0:26/7:14 (5%)
volume: n/a   repeat: off   random: off   single: off   consume: off

ex:0.21.11
rock64@rock64:~$ mpc
阿拉伯音乐之旅 - Citizen of the Sun
[playing] #1/2   0:06/7:14 (1%)
volume: n/a   repeat: off   random: off   single: off   consume: off

**Comment by MaxKellermann** [comment]
What is "wav files with embedded information"? Can you provide a demo file?

**Comment by MaxKellermann** [comment]
Also, you decided to delete the bug reporting instructions, and decided not to provide the information it requested from you.
