### ISSUE TITLE
MPD unavailable  in homeassistant !!!

### ISSUE THREAD

**Issue by wojoco** [MusicPlayerDaemon/MPD#123]
I use mpd in homeassistant(tts),send two messages so fast,mpd  will be unavailable ! It work again must reboot!   config something wrong? please help !

**Comment by MaxKellermann** [comment]
This bug report is completely devoid of information. It is impossible to solve it.

**Comment by wojoco** [comment]
config
[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
visualizer =

[proxy]
scheme =
hostname =
port =
username =
password =

[local]
enabled = true
library = json
media_dir = $XDG_MUSIC_DIR
data_dir = $XDG_DATA_DIR/mopidy/local
playlists_dir = $XDG_DATA_DIR/mopidy/local/playlists
scan_timeout = 1000
scan_flush_threshold = 1000
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 100
zeroconf = Mopidy MPD server on $hostname

[softwaremixer]
enabled = true

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  file
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

**Comment by MaxKellermann** [comment]
WTF. You're not using MPD at all!

**Comment by wojoco** [comment]
@MaxKellermann  why？
this is log
Oct 05 19:07 : errno: Failed to open /var/lib/mpd/state: No such file or direct$
Oct 05 19:07 : avahi: Service 'Music Player' successfully established.
Oct 05 19:29 : zeroconf: No global port, disabling zeroconf
Oct 05 19:36 : zeroconf: No global port, disabling zeroconf
Oct 05 19:37 : client: [0] opened from 192.168.0.108:43646
Oct 05 19:37 : alsa_mixer: Failed to read mixer for 'My ALSA Device': no such m$
Oct 05 19:45 : zeroconf: No global port, disabling zeroconf
Oct 05 19:46 : client: [0] opened from 192.168.0.108:56448
Oct 05 19:46 : alsa_mixer: Failed to read mixer for 'My ALSA Device': no such m$
Oct 05 19:54 : zeroconf: No global port, disabling zeroconf
Oct 05 19:54 : client: [0] opened from 192.168.0.108:37686
Oct 05 19:54 : alsa_mixer: Failed to read mixer for 'My ALSA Device': no such m$
Oct 05 19:56 : output: Failed to open mixer for 'My ALSA Device'
Oct 05 19:56 : player: played "http://192.168.0.108:8123/api/tts_proxy/021bd668$
Oct 05 19:56 : output: Failed to open mixer for 'My ALSA Device'
Oct 05 19:54 : zeroconf: No global port, disabling zeroconf
Oct 05 20:05 : client: [0] opened from 192.168.0.108:48124
Oct 05 20:05 : alsa_mixer: Failed to read mixer for 'My ALSA Device': no such m$
Oct 05 20:13 : zeroconf: No global port, disabling zeroconf

**Comment by MaxKellermann** [comment]
Because you pasted a Mopidy configuration, which is a software which is not MPD, but pretends it is (it emulates the MPD protocol). This implies that you use Mopidy, not MPD.
