### ISSUE TITLE
Changes to MPD systemd service file?

### ISSUE THREAD

**Issue by ArchangeGabriel** [MusicPlayerDaemon/MPD#124]
Hi,

I’ve recently realized that if MPD is built without `systemd-daemon` support (which, according to the configure script, is for socket activation), the `Type=notify` makes the service useless because it apparently doesn’t support notify in this case. Changing to `simple` (or removing the line altogether since this is the default). I understand per #121 that you want to keep `notify`, so I’m only proposing to remove that when compiling without `systemd-daemon`. Or change the configure script so that systemd-daemon support is said mandatory for systemd support and do not allow to package systemd units files without it.

Looking at the service file, I realized that some more changes could be made depending on the compilation options:

- if compiling without network support, maybe `network.target` and `AF_INET AF_INET6 AF_NETLINK` should be removed.
- if compiling without IPv6 support, removing only `AF_INET6`?

Thanks.

**Comment by MaxKellermann** [comment]
I consider it useless to use MPD with systemd without compiling it with libsystemd. It is not a supported use case.

**Comment by ArchangeGabriel** [comment]
OK. What about units changes regarding network support?
