### ISSUE TITLE
Because log rotation has to be done externally, there are rooms for mistakes.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#125]
Usually, linux distributions take care of log rotation for mpd.
However, if I changed log_file, I should remember to change log rotation configuration as well.
System administrators can make mistakes when they are sleepy or in hurry.

I once forgot to keep log rotation configurations up to date, and some program filled `/var` full.
When `/var` partition is full, various anomalies manifest.

If log rotation was built in mpd and enabled by default, there would be no room for log rotation mistake.

**Comment by MaxKellermann** [comment]
No. This doesn't belong in MPD.

**Comment by Phrogz** [comment]
@crocket Asked me to explain my thumbs down. Thus: 

I feel that thid feature was not appropriate for MPD, or any other program running in Linux. It would be similar, in my mind, to a feature request like: "I know package managers exist on most platforms, but sometimes it's hard to find an updated version. I'd like MPD to support checking for updates and updating its own software over the 'net."

Like that strawman suggestiostraw man feature request has _some_ merit and good rationale...but IMO it too-heavily overlaps with features already best covered by other, existing, software.
