### ISSUE TITLE
Make the idle events less generic

### ISSUE THREAD

**Issue by duarm** [MusicPlayerDaemon/MPD#1258]
## Feature request

While making a script for my status bar, I've encountered what I consider a silly limitation if you consider scripting as one the primary use cases for idle events. I have a script which scrolls the music currently playing on my statusbar, it worked perfectly and easily with 'mpc idle', the best feature ever. I was idling for the 'player' event, and just updated the statusbar on every event. I wanted to modify the script to update my scroll program to start scrolling again from the start everytime the music changed, otherwise the next music name would start from an arbitrary position. This would be a very easy change, but since the 'player' event bundles the started, stopped, seeked,  everytime I pause, unpause or seek, the scroll resets too, the problem is that this limitation exists for no apparent good reason.

I propose splitting the IDLE_PLAYER flag, and if possible, every other flag to a more specific version of itself, there would be no problem keeping the current ones for compatibility and as a shorthand for every event of each subsystem.
As an example, IDLE_PLAYER would become:
```
IDLE_PLAYER_SEEK
IDLE_PLAYER_PAUSE
IDLE_PLAYER_UNPAUSE
IDLE_PLAYER_CHANGED
IDLE_PLAYER  = IDLE_PLAYER_SEEK | IDLE_PLAYER_PAUSE | IDLE_PLAYER_UNPAUSE | IDLE_PLAYER_CHANGED
```
and my script would just become
```shell
while mpc idle player_changed  >/dev/null
do
	reset_music_scroll &&
	update_statusbar
done
```

**Comment by MaxKellermann** [comment]
No. The idea of idle events is that your client gets a notification, and then it's up to the client to check MPD's new state and check which detail exactly changed. In your case, your script would need to be extended to compare `mpc current -f %id%` with the previous value. That's simple, and doesn't justify making the MPD protocol more complex.
btw. there's a race condition bug in your script: if an idle event occurs between `do` and `done`, your script will miss it. What you can do to fix it is `mpc idleloop player |while read; do ... done` - this keeps mpc persistent (with a persistent MPD connection) and doesn't miss events.
