### ISSUE TITLE
Record and expose playback meta information

### ISSUE THREAD

**Issue by Phrogz** [MusicPlayerDaemon/MPD#126]
## Feature Request
At a minimum, please add to the API a dynamic tag for a song that is the date/time when the song was `LastPlayed.` Optionally, please also add dynamic tags for:
* The date/time when a song was `LastSkipped`.
* The number of times a song has been played `PlayCount`
* The number of times a song has been skipped `SkipCount`
* Allow these four tags to be used as sort criteria for `find`.

Offering the same information in a different manner (not as a `tag`) would also be acceptable.

## Motivation
* I want to select music to play ~randomly, but excluding songs that have been played 'recently' (~4 weeks), or that have been skipped semi-recently (~6 weeks).
* I want to select a bunch of music that I like (e.g. a playlist) but then I want to sort those songs by when I last played them.

Since MPD is in charge of playing songs, and already records some of this information (albeit only in the log right now), it seems reasonable to ask MPD to keep track of this and make it available. Currently I have to keep track of a separate database (actually a custom table added to the sticker database) and detect plays and skips myself, recording (in a denormalized way) the URI along with each play/skip action. If someone reaches MPD via a client other than my own, play counts, play date, skips, etc. are not recorded.

**Comment by MaxKellermann** [comment]
This rule set what to record sounds pretty arbitrary. The next guy will complain that his favorite rules are not considered. It would be very specific to your personal choices, but to nobody else's. Hard-coding the personal choices of one single user in the MPD core certainly isn't a good idea. Even less so if this requires a whole new subsystem for storing dynamic metadata managed by MPD itself.
What you could do instead is write an extra daemon which tracks playbacks and stores its data in MPD stickers, which can be queries by MPD clients. This way, you have a rule set tailored to your own needs, and the next guy has a different software for his own taste.
If you are convinced that you can come up with a generic concept scalable to everybody, we can talk about it. But this is not.

**Comment by Phrogz** [comment]
I suppose a generic concept would be to either (a) record every MPD action in a DB, or (b) have a configuration setting that specified what types of actions to record, or (c) be able to issue a command that specified the types of actions to record until next changed. For this to work with the stickers table, though, it would require that the schema be changed to remove the `CREATE UNIQUE INDEX sticker_value ON sticker(type, uri, name);` index, so that the same event could be recorded for multiple times. Perhaps a schema like:

```sql
CREATE TABLE sticker(
    type  VARCHAR NOT NULL,
    stamp DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'NOW', 'localtime')),
    uri   VARCHAR NOT NULL,
    name  VARCHAR NOT NULL,
    value VARCHAR NOT NULL
);
CREATE UNIQUE INDEX sticker_value ON sticker(type, uri, name, stamp);
```

Would you be amenable to modifying the sticker table to allow multiple entries for the same sticker name? If so, I would like to pursue a general mechanism for recording events. Assuming you are not, then I'll have to continue using a separate table and daemon as you suggest.

Thank you for your consideration.

**Comment by owl770** [comment]
Hi Phrogz,

Have you looked at the utility called mpdcron? This may help you on your quest for mpd metadata. I use the stats module to track the number of times artists and tracks are played.
