### ISSUE TITLE
error on Directory.cxx:89

### ISSUE THREAD

**Issue by cumulus13** [MusicPlayerDaemon/MPD#1264]
i got error while scanning/updating process then mpd stopped/terminated itself, I've tried re-run many times, but still I get an error like this:

    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/07. Gibraltar.mp3
    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/08. The Traveller.mp3
    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/09. Monolith.mp3
    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/10. Deep In Our Hearts.mp3
    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/11. Freestyle.mp3
    Sep 14 07:00 : update: added music_06/Pascal Allaigre - Firelight (2004)/12. The Undiscovered Land.mp3
    mpd: ../src/db/plugins/simple/Directory.cxx:89: Directory* Directory::CreateChild(std::string_view): Assertion 
    `!name_utf8.empty()' failed.

**Comment by MaxKellermann** [comment]
Why do you refuse to post the information you were asked to post?

**Comment by MaxKellermann** [comment]
No reply, no information. Bye.
