### ISSUE TITLE
how to get embedded album art from songs in the notification via dunst?

### ISSUE THREAD

**Issue by onlyvip** [MusicPlayerDaemon/MPD#1269]
## Question
1. i am using mpd [version](https://ezup.dev/p/0dcour), and i have album-art embedded with the songs which i have downloaded using youtube-dl using this [command](https://ezup.dev/p/93bl56), i am using dunst to have notification for every song change. so what should i have configured in order to get 
a. notification when a song changes. and b. album art for the song in the notifcation?

**Comment by MaxKellermann** [comment]
I can only answer these questions on the MPD protocol level.
For getting notications, there's the "idle" command, and it will emit the "player" event when the song changes. See https://mpd.readthedocs.io/en/stable/protocol.html#querying-mpd-s-status
For album art / cover art, there are two commands: `albumart` which reads from an external file, and `readpicture` which reads a picture embedded in the music file. See https://mpd.readthedocs.io/en/stable/protocol.html#the-music-database for documentation.

**Comment by onlyvip** [comment]
> I can only answer these questions on the MPD protocol level.
> For getting notications, there's the "idle" command, and it will emit the "player" event when the song changes. See https://mpd.readthedocs.io/en/stable/protocol.html#querying-mpd-s-status
> For album art / cover art, there are two commands: `albumart` which reads from an external file, and `readpicture` which reads a picture embedded in the music file. See https://mpd.readthedocs.io/en/stable/protocol.html#the-music-database for documentation.

i am sorry, but how or where do i put these options? i am totally confused. should i add it in mpd.conf? if yes, how or what exactly? or in dunstrc?

**Comment by MaxKellermann** [comment]
These are not options, they are protocol commands, and can be used without configuring anything. That's the language MPD clients talk to MPD, and the document describes this language. If you're not a developer, then this document is not for you, then you need a MPD client which already implements what you want. MPD itself is just a dumb server - it does what clients tell it to do.

**Comment by onlyvip** [comment]
understood. i guess i gotta ask at the client and the notification daemons discussion side. thanks for the valauable information. nonetheless. i am now sure it can be implemented.
