### ISSUE TITLE
Changed behavior of command playlistclear breaks clients

### ISSUE THREAD

**Issue by geneticdrift** [MusicPlayerDaemon/MPD#127]
gmpc (possibly other clients too) uses command playlistclear to create a new stored playlist.

In mpd 0.21.0 this command returns "No such playlist"

```
bin/mpd --version
Music Player Daemon 0.21 (v0.20.10-420-g8a81b986c)
```

```
OK MPD 0.21.0
playlistclear NewPlaylist
ACK [50@0] {} No such playlist
```
vs.
```
OK MPD 0.19.0
playlistclear NewPlaylist
OK
```

**Comment by MaxKellermann** [comment]
This is not a breakage. Only your client is broken, because it depends on surprising undocumented behavior.
