### ISSUE TITLE
PipeWire output plugin does not set sample rate

### ISSUE THREAD

**Issue by jpalus** [MusicPlayerDaemon/MPD#1283]
### Describe the bug
With new `pipewire` output plugin in `mpd 0.23` sample rate is no longer set dynamically based on input file. When using ALSA as well as PulseAudio plugins, both backed by pipewire, sample rate is changed correctly. `pw-top` shows as if `mpd` didn't set `rate` (value 0) hence device seems to always be set to default rate (48kHz) instead of matching rate from input file:
![image](https://user-images.githubusercontent.com/484155/137584745-1eacdca6-ce24-4d6f-a6b5-1367431da455.png)

## Expected Behavior
Sample rate of output device matches input file.

## Actual Behavior
Sample rate of output device remains constant.

## Version

```
Music Player Daemon 0.23 (0.23)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

**Comment by MaxKellermann** [comment]
First of all, why did you refuse to post your log?

Second: can you explain how to do that, and what MPD is doing wrong?
MPD sets `spa_audio_info_raw.rate` here:
https://github.com/MusicPlayerDaemon/MPD/blob/771c46032f4dd60097d46524ef6873a49b051a01/src/output/plugins/PipeWireOutputPlugin.cxx#L284
... which gets passed to `pw_stream_connect()` here:
https://github.com/MusicPlayerDaemon/MPD/blob/771c46032f4dd60097d46524ef6873a49b051a01/src/output/plugins/PipeWireOutputPlugin.cxx#L412-L422
Had you pasted your log, as I asked you to (but you refused), you would have seen that MPD's resampling code is disabled, and MPD passes whatever sample rate is in your source file to libpipewire. It is then libpipewire's decision to resample, if that really happens, no idea, you didn't post any data backing this up.

My point is: MPD told libpipewire the audio format, and my idea is that's all that's needed to convince PipeWire to use that audio format. The decision to use another audio format is now outside of MPD.

**Comment by MaxKellermann** [comment]
Is what you're asking even possible with PipeWire?
See https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#setting-sample-rates
> PipeWire uses a global sample rate in the processing pipeline. All signals are converted to this sample rate and then converted to the sample rate of the device.

**Comment by MaxKellermann** [comment]
So... an application should always set both `spa_audio_info_raw.rate` and `NODE_RATE` to the same value?
What's the use of redundant information in `NODE_RATE` if PipeWire already knows the sample rate?
