### ISSUE TITLE
Multiple artists with multi-byte character get garbled

### ISSUE THREAD

**Issue by estshorter** [MusicPlayerDaemon/MPD#131]
The title describes the symptom.

I use a semicolon as a artist-separator.
For example, if I set "Müza Rubackyté; Vilnius String Quartet" as artists, "嘀椀氀渀椀甀猀 匀琀爀椀渀最 儀甀愀爀琀攀琀" is shown in MPD clients.
In foobar2k, MusicBee and Mp3tag, the artist is correctly displayed.

This is not the bug in MPD clients because all the clients I tested result in the same problem.
Note: single artist with multi-byte character or multiple artists with single-byte character only are displayed correctly.

MPD: 0.20.10 on raspberry pi (OS: moode audio)

**Comment by MaxKellermann** [comment]
Upload an example file. And upload a dump of the traffic between MPD client and server.

**Comment by estshorter** [comment]
I found that re-saving tags using Mp3tag can resolve the problem.
So, I close this issue.
Maybe tag edit using MusicBee resulted in it.

Thank you for your reply.
