### ISSUE TITLE
Replaygain doesn't work for AAC files

### ISSUE THREAD

**Issue by estshorter** [MusicPlayerDaemon/MPD#132]
It seems that replaygain doesn't work for AAC (m4a) files.
The tags are written by foobar 2k and it works in foobar 2k and MusicBee.

Is it intentional or a glitch?
I hope it will be implemented or fixed.

MPD: 0.20.10 on raspberry pi (OS: moode audio)

**Comment by MaxKellermann** [comment]
Upload an example file.

**Comment by estshorter** [comment]
I uploaded the example file in the url below.
https://www.dropbox.com/s/i54rlu1pm93u6bl/Mp4Test.zip?dl=1

+12.32 dB is specified as replaygain in "01 M4A Test File with replaygain.m4a" by foobar2k.
"02 M4A Test File without replaygain.m4a" is without replaygain and from [here](http://samplephotovideo.com/2015/12/m4a-mpeg-4-audio-layer-sample-file-m4a).

**Comment by MaxKellermann** [comment]
ReplayGain works here (tested with MPD 0.20.11).

    audio_format=44100:f:2 duration=36.647000
    replay_gain[album]: gain=12.320000 peak=0.511007
    replay_gain[track]: gain=12.320000 peak=0.511007
    195 kbit/s

Upload a verbose log which shows playback of that file, and additionally of the playback of another file which has working replay gain.

**Comment by estshorter** [comment]
These are verbose logs.

[aacfile.log](https://github.com/MusicPlayerDaemon/MPD/files/1406740/aacfile.log)
[working-replaygain.log](https://github.com/MusicPlayerDaemon/MPD/files/1406741/working-replaygain.log)

For non-aac files, there is an output like 
`replay_gain: scale=0.861986
`
, but there isn't for aac files.

**Comment by MaxKellermann** [comment]
I tried to find out which FFmpeg versions you have, and then I found out you're using MPD from a proprietary non-free distribution which does not provide the source code. This is illegal!
I'm sorry I cannot provide any support for Moode users, as a general rule.

**Comment by estshorter** [comment]
I got it.
Thank you for your cooperation.

**Comment by estshorter** [comment]
Note:
This problem doesn't occur in the latest raspbian (debian stretch based).
I compiled MPD 20.11 from the source and tested.
The ffmpeg version might be the cause as you told.

**Comment by MaxKellermann** [comment]
See, usually I refuse to even read a bug report about an outdated version, see https://www.musicpd.org/help/
People crititicize me for being too harsh. But again and again, I turn out to be right.
And every time I do read such a bug report like yours, I regret it. This is exactly what turns me harsh.
