### ISSUE TITLE
Files/Folder found from inotify gives corrupt directory 

### ISSUE THREAD

**Issue by snake3ca** [MusicPlayerDaemon/MPD#1320]
### Describe the bug
File found during an auto update in mpd 0.23.2 are not added.  Log shows corrupt dir/file name.

Oct 30 11:01 : exception: Failed to open `Ω"ΈU: No such file or directory

File names show up correctly when using inotifywait to monitor the directories.

If you do a manual update or rescan the files are added correctly.

## Expected Behavior

Expect it to add the new music found with inotify.

## Actual Behavior

Doesnt add new music and shows corrupt directory in log.

## Version
Music Player Daemon 0.23.2 (0.23.2)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mpg123] mp3
 [oggflac] ogg oga
 [flac] flac
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [wavpack] wv
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 null alsa

Input plugins:
 file alsa

Playlist plugins:
 extm3u m3u pls flac

Protocols:
 alsa://

Other features:
 epoll icu inotify tcp

## Log
Oct 30 11:01 : exception: Failed to open `Ω"ΈU: No such file or directory

**Comment by snake3ca** [comment]
When downgrading to MPD 0.22.11 this issue goes away.

**Comment by MaxKellermann** [comment]
Probably fixed by bfb1b641f990968558f9b23ced663a387a19bde6

**Comment by snake3ca** [comment]
I can confirm bfb1b64 fixed the issue.
