### ISSUE TITLE
Support whence for searchadd and position for searchaddpl

### ISSUE THREAD

**Issue by jcorporation** [MusicPlayerDaemon/MPD#1328]
## Feature request

Thew new position and whence parameters are very useful.

With current master I miss two features:
- whence support for the searchadd command (libmpdclient supports this already)
- position parameter for the searchaddpl command

**Comment by MaxKellermann** [comment]
It's supported already by `searchadd`: https://mpd.readthedocs.io/en/stable/protocol.html#command-searchadd

**Comment by jcorporation** [comment]
Sorry, but I think both features are not implemented or there is a bug. 

### whence for searchadd

I tested again with current master:
- one paused song in the playlist
- issueing `searchadd "((Title == 'Blume'))" position +0`
- search result is inserted at pos 0, not right after the paused song

[log.txt](https://github.com/MusicPlayerDaemon/MPD/files/7507833/log.txt)

### position for searchaddpl

The documentation says there is no position argument.

**Comment by MaxKellermann** [comment]
> I tested again with current master:
> 
>     * one paused song in the playlist
> 
>     * issueing `searchadd "((Title == 'Blume'))" position +0`
> 
>     * search result is inserted at pos 0, not right after the paused song

The documentation I linked to does not say that relative positions are supported, and your feature request does not mention it either.

> The documentation says there is no position argument.

Right. And that's the only thing remaining to be implemented for this feature request.
