### ISSUE TITLE
No unix socket after upgrade to 23.3 

### ISSUE THREAD

**Issue by jeroenhabets** [MusicPlayerDaemon/MPD#1329]
### Describe the bug
I upgraded on Ubuntu 20.04 LTS from 22.10 to 23.3 and now mpd does not create /run/mpd/socket anymore. I've tried a couple of things but since I don't see any error anywhere I'm a bit stuck. Any ideas?

22.10->23.3 introduced RuntimeDirectory=mpd in my /lib/systemd/system/mpd.service  
NOTE: I had to fix the mpd.service to add "RuntimeDirectoryMode=0777" as in mpd.conf I switch to user mpd.mpd.

My /etc/mpd.conf contains:
bind_to_address         "/run/mpd/socket"

## Expected Behavior
mpd creates /run/mpd/socket like it used to, or shows an error in /var/log/mpd/mpd.log

## Actual Behavior
mpd creates /run/mpd/pid like before (w/ RuntimeDirectoryMode=0777 fix) but _no_  /run/mpd/socket :(
P.S. network binding is working fine.

## Version
```Music Player Daemon 0.23.3 (v0.23.3)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log (/var/mpd/mpd.log)
```Nov 07 14:27 : zeroconf: No global port, disabling zeroconf
Nov 07 14:27 : state_file: Loading state file /var/lib/mpd/state
```
## Log (journalctl)
```-- A start job for unit mpd.service has begun execution.
--
-- The job identifier is 45667.
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : path: SetFSCharset: fs charset is
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : vorbis: Xiph.Org libVorbis 1.3.6
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : opus: libopus 1.3.1
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : sndfile: libsndfile-1.0.28
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : adplug: adplug 2.3.1
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : simple_db: reading DB
nov 07 14:29:59 mediaserf kernel: [UFW BLOCK] IN=enp8s0 OUT= MAC=01:00:5e:00:00:01:24:4b:fe:2a:ce:70:08:00 SRC=192.168.1.1 DST=224.0.0>
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : curl: version 7.68.0
nov 07 14:29:59 mediaserf mpd[755022]: Nov 07 14:29 : curl: with GnuTLS/3.6.13
nov 07 14:29:59 mediaserf systemd[1]: Started Music Player Daemon.
-- Subject: A start job for unit mpd.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit mpd.service has finished successfully.
--
-- The job identifier is 45667.
```

**Comment by MaxKellermann** [comment]
Are you using the systemd socket unit?

**Comment by jeroenhabets** [comment]
@MaxKellermann Thanks! I thought not but after disabling and stopping mpd.socket and then restarting mpd.service I now have a /run/mpd/mpd.socket!

Would it be an idea to add a message in the mpd.log if a unix socket is configured and during mpd start it find an mpd.socket is active?

**Comment by MaxKellermann** [comment]
I'm a bit confused. The MPD socket unit binds to this address by default:
https://github.com/MusicPlayerDaemon/MPD/blob/c93195c94b213bf4718ba5a21a6a9cb19826992a/systemd/system/mpd.socket#L2-L3
Here `%t` is `/run`, so this binds to `/run/mpd/socket`, the same path configured in your `mpd.conf`. Whether or not you're using systemd socket activation (i.e. `mpd.socket`) or not should both result in a socket on `/run/mpd/socket`.
You did not answer my question, but you apparently solved your problem, but you did not answer my question. This leaves me without any perspective on how to proceed here.

**Comment by jeroenhabets** [comment]
Hi @MaxKellermann,

Apologies for the delay. Never submit a personal Bug report right before a tender deadline, I suppose.

Also I noticed I had made a copy-paste mistake in [my comment](https://github.com/MusicPlayerDaemon/MPD/issues/1329#issuecomment-962679355): the socket path I have is  `/run/mpd/socket`! (Not: `/run/mpd/mpd.socket`).

I actually had tried  to answer your question "Are you using the systemd socket unit?" and I meant to say that I am not an consciously active user of the systemd socket for MPD as I run it as a service from start up.

Although now that I check I do see previous events in the output of `sudo systemctl status mpd.socket`:
```
nov 05 20:04:04 mediaserf systemd[1]: Listening on mpd.socket.
nov 07 21:53:55 mediaserf systemd[1]: mpd.socket: Succeeded.
```

Going forward:
1. I think it would be good to add "RuntimeDirectoryMode=0777" in mpd.service. Of course it opens that socket to any user, but I don't see a way how to make systemd create a socket owned by a specified non-root user.
2. It would be an improvement to get a warning if a socket cannot be created (in particular with log_level=verbose).
3. Is there anything else I can do to test for you? Other than my hints of 1. and 2. I feel this request can be Closed.

P.S. I'm going to a 4 day festival starting tomorrow ([Le Guess Who](https://www.leguesswho.nl/) so will be slow to respond again, I'm afraid.

**Comment by MaxKellermann** [comment]
>     1. I think it would be good to add "RuntimeDirectoryMode=0777" in mpd.service. Of course it opens that socket to any user, but I don't see a way how to make systemd create a socket owned by a specified non-root user.

How would this solve your problem, which is that the listener socket is missing?

>     2. It would be an improvement to get a warning if a socket cannot be created (in particular with log_level=verbose).

MPD doesn't create the socket (because you're using systemd socket activation), and therefore cannot fail to do so, and thus asking it to log something doesn't make sense.

>     3. Is there anything else I can do to test for you? Other than my hints of 1. and 2. I feel this request can be Closed.

Since this is about a socket created by systemd, you could report your problem to the systemd project.
