### ISSUE TITLE
Runtime memory allocation error running as user

### ISSUE THREAD

**Issue by danielittlewood0** [MusicPlayerDaemon/MPD#1332]
### Describe the bug
I can run mpd as a system service just fine. I'm running v0.22.11 on Gentoo, running openrc. However, when I run it as a user, it fails with a memory error. I am not short of memory:

```
$ free -m
               total        used        free      shared  buff/cache   available
Mem:            7833        3884        1410         442        2538        3079
Swap:           7628         270        7358
```

## Expected Behavior

mpd should start normally in per-user mode.

## Actual Behavior

```
$ mpd
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
```

## Version
Music Player Daemon 0.22.11 (0.22.11)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local smbclient udisks

Neighbor plugins:
 smbclient udisks

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:

Tag plugins:
 id3tag

Output plugins:
 shout null fifo alsa pulse httpd

Encoder plugins:
 null vorbis opus wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file io_uring archive alsa curl ffmpeg smbclient

Playlist plugins:
 extm3u m3u pls flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// smb:// srtp://

Other features:
 dbus udisks epoll icu inotify ipv6 tcp un

## Log
```
$ mpd --verbose
config_file: loading file /home/daniel/.config/mpd/mpd.conf
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory

$ mpd --no-daemon --stderr --verbose
config_file: loading file /home/daniel/.config/mpd/mpd.conf
exception: Default TCP listener setup failed, but this is okay because we have a $XDG_RUNTIME_DIR listener: Failed to bind to '[::]:6600'; Failed to bind socket: Address already in use
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
curl: version 7.79.1
curl: with OpenSSL/1.1.1l
state_file: Loading state file /home/daniel/.config/mpd/state
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler
failed: Operation not permitted
inotify: initializing inotify
inotify: watching music directory
```

**Comment by MaxKellermann** [comment]
See https://mpd.readthedocs.io/en/stable/user.html#error-failed-to-initialize-io-uring
