### ISSUE TITLE
MPD fails to launch

### ISSUE THREAD

**Issue by ace510** [MusicPlayerDaemon/MPD#1346]
## Bug report
MPD fails to start when invoked from commandline, or when MPD.service is started

## Expected Behavior
MPD starts

## Actual Behavior
MPD fails with
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libmsrpc3.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/liblibsmb.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsmbconf.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libutil-cmdline.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamba-credentials.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcliauth.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libgensec.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libauthkrb5.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamdb-common.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libldbsamba.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamba-net.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libdcerpc.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcli-ldap.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamdb.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcommon-auth.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamba-python.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libhttp.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libnetif.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libMESSAGING.so.0)

## Version
mpd --version
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libmsrpc3.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/liblibsmb.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsmbconf.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libutil-cmdline.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamba-credentials.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcliauth.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libgensec.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libauthkrb5.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamdb-common.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libldbsamba.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamba-net.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libdcerpc.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcli-ldap.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /lib/arm-linux-gnueabihf/libsamdb.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libcommon-auth.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libsamba-python.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libhttp.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libnetif.so.0)
mpd: /lib/arm-linux-gnueabihf/libsamba-hostconfig.so.0: version `SAMBA_HOSTCONFIG_0.0.1' not found (required by /usr/lib/arm-linux-gnueabihf/samba/libMESSAGING.so.0)

OS info:
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

MPD installed through APT

## Log
no relevant log (same as above)

**Comment by leigh123linux** [comment]
You should close this non-issue here and file the issue at the debian bug tracker so they can fix their broken packaging.

**Comment by ace510** [comment]
for anyone who finds this in google results a year from now, updating to Bullseye (Debian 11) brought a new MPD version and fixed everything

**Comment by MaxKellermann** [comment]
For being able to google this, you should have posted the information you were asked to post.
