### ISSUE TITLE
Software volume control in DSD to PCM on the fly conversion

### ISSUE THREAD

**Issue by domisol** [MusicPlayerDaemon/MPD#1350]
## Feature request
Hi
Using MPD through Moodeaudio, I can't set software volume when I play DSF files with on the fly PCM conversion. That means they are always played at max volume. Is there a way to have volume control applied in this case?
Thanks
Jean-David

**Comment by MaxKellermann** [comment]
Need more information, see https://www.musicpd.org/help/

**Comment by MaxKellermann** [comment]
No reply

**Comment by domisol** [comment]
well sorry, but your message was not expecting any reply. I just made a feature request, that's all. I don't need further help.
THanks
Jean-David

**Comment by MaxKellermann** [comment]
The thing is that you did not post enough information to be able to work on your feature request. I said that I needed more information, and if you believe my need for more information means I don't expect a reply with more information, then something has gone very wrong.
