### ISSUE TITLE
How to add cover image to a track via MPD command protocol?

### ISSUE THREAD

**Issue by THMonster** [MusicPlayerDaemon/MPD#1368]

**Comment by MaxKellermann** [comment]
You can't. The images needs to be embedded inside the file's tags.
MPD is designed to never write any song file, read-only access.

**Comment by THMonster** [comment]
> You can't. The images needs to be embedded inside the file's tags. MPD is designed to never write any song file, read-only access.

I'm not trying to modify a music file. I just want to add cover to a track(http source) in MPD

**Comment by MaxKellermann** [comment]
I repeat: MPD reads cover images from the music files.
Therefore, to add cover images, you need to modify the music files.
It would be possible to add code to MPD to make MPD fetch cover images from a different source, but that feature does not exist currently. It's open source - write it!

**Comment by THMonster** [comment]
Thanks, I'm not asking anyone to implement anything. I open this issue just for a double check, because I didn't find it after reading doc but maybe it's a undocumented feature.
