### ISSUE TITLE
ID3 tag second artist displayed with garbled charaters

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#1380]
### Describe the bug
Two artists in one TPE1 tag. First one is shown correct, second results in some weired (but beautiful) asian characters. Affected clients are ncmpc (from git) and Cantata 2.3.2 on Windows 10 x64.

## Expected Behavior
Proper display of all artist namnes in MPD clients.

## Actual Behavior
See above.

## Version

Music Player Daemon 0.24 (v0.23.5-56-gdda0dfc14)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [sidplay] sid mus str prg P00
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo pipe alsa httpd snapcast

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus epoll icu inotify ipv6 systemd tcp un

## Log

Log contains filenames only.

**Comment by MaxKellermann** [comment]
Need a sample file demonstrating the problem.

**Comment by skidoo23** [comment]
No problem. How to make it available to you?

**Comment by MaxKellermann** [comment]
Post link for wget (no javascript crap) or send email.

**Comment by skidoo23** [comment]
File is on its way to your gmail account.

**Comment by MaxKellermann** [comment]
I can confirm this problem, but this is how libid3tag returns it. I think libid3tag mixes up the byte order of the second tag. Not a MPD bug, but in libid3tag.

**Comment by MaxKellermann** [comment]
Look:
```
$ madplay 01\ -\ Running\ Through\ My\ Veins.mp3 
MPEG Audio Decoder 0.15.2 (beta) - Copyright (C) 2000-2004 Robert Leslie et al.
          Title: Running Through My Veins
         Artist: Matt Lange
                 䐀攀渀椀稀 刀攀渀漀
      Orchestra: Matt Lange
                 䐀攀渀椀稀 刀攀渀漀
          Album: Running Through My Veins
          Track: 1
           Year: 2020-10-16
      Publisher: isorhythm
          Genre: Electro
```
The "䐀" is Unicode code point `U+4400`, and if you swap the bytes, it becomes `U+0044` which is `D` - the first letter of the second artist ("Deniz Reno").
madplay also uses libid3tag, therefore the same bug.
