### ISSUE TITLE
FR: TagLib support for more robust metadata handling 

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#1381]
Please support [https://taglib.org/](https://taglib.org/) for more robust metadata handling and faster indexing. TagLib claims to run six times faster than libid3tag.

**Comment by MaxKellermann** [comment]
TagLib is faster than libid3tag? Is that so? There's no data to back up this claim on the TagLib website.

I tried with a tiny program which scans the tags of a file 100,000 times in a row.
```
#include <taglib/fileref.h>
#include <taglib/tag.h>
#include <taglib/taglib.h>
#include <taglib/tpropertymap.h>
int main(int argc, char **argv) {
	for (int i = 0; i < 100000; ++i) {
		TagLib::FileRef f(argv[1]);
		for (const auto &[name, values] : f.tag()->properties()) {
			auto n8 = name.to8Bit();
			for (const auto &value : values)
				printf("%s = %s\n", n8.c_str(), value.to8Bit().c_str());
		}
	}
}
```
Benchmarking against MPD's `read_tag` program which uses whatever library usually chooses - libid3tag, libvorbis or MPD's own APE parser; plus it parses MPD's supported tag names, i.e. it has more features and should be slower.

Reading ID3v2 tags:
- TagLib: 9,408.85 msec task-clock:u
- MPD/libid3tag: 1,187.96 msec task-clock:u

Reading ID3v1 tags:
- TagLib: 4,263.36 msec task-clock:u
- MPD/libid3tag: 1,403.42 msec task-clock:u

Reading APE tags:
- TagLib: 9,241.14 msec task-clock:u
- MPD: 793.63 msec task-clock:u

Reading VorbisComments from an OggVorbis file:
- TagLib: 7,364.38 msec task-clock:u
- MPD/libvorbis: 6,009.95 msec task-clock:u

I'm not convinced of TagLib's claimed performance advantage. This looks really bad.

And more robust? Source and data for this claim?

Also TagLib doesn't support many tags such as AlbumArtist, Performer and many others - it simply omits them from the result. And it omits duplicate tag values (e.g. a song with multiple artists) - it shows only the first one. This is bad.

**Comment by MaxKellermann** [comment]
I ran the profiler on both libid3tag and TagLib.
TagLib is *very* inefficient code; it does allocations all the time. 25% of the CPU time is wasted inside `malloc()` and `free()`.
libid3tag on the other hand spends only 7.5% inside `malloc()` and `free()`.

Considering that the absolute CPU time used by libid3tag is already 8 times smaller than TagLib, that means **libid3tag is 26 times more efficient at memory allocation than TagLib**.

Another perspective on the same results: TagLib spends 2.35 seconds CPU only for memory allocations; that is **twice as much** as the **total** CPU time spent by the whole MPD/libid3tag program (everything, not just memory allocation).

How can TagLib claim they are "about 6 times faster than id3lib" ...?

**Comment by skidoo23** [comment]
Ouch. I hoped to get grid of asian characters mentioned in #1380. Looks like I better fix my metadata before messing with obscure libraries.

Request closed.
