### ISSUE TITLE
List playlists sorted

### ISSUE THREAD

**Issue by monolied** [MusicPlayerDaemon/MPD#1391]
## Feature request
When I use `mpc lsplaylists`, there is no discernible order. And all mpc frontends I'm using take this arbitrary order (it seems to be directory order), and don't sort either, so I'm stuck with this and have a hard time finding what I'm looking for. I already tried to modify my favorite mpd frontend, but that uses a very outdated android environment and libraries, and I can't for the life of me set up a development environment where I wouldn't have to essentially rewrite it from scratch. Also, I believe this would be an easy and nice feature for mpc, a `-o` switch or somesutch, doesn't even have to have further options.

**Comment by jcorporation** [comment]
myMPD sorts the playlists manually by name. The MPD protocol itself has no options for the `listplaylists` command.

**Comment by MaxKellermann** [comment]
Sorting the playlist names on the server is rather pointless; this should be a pure client side thing.
ncmpc sorts by name, and mpc's output can be piped to `sort` (it doesn't need that feature).
