### ISSUE TITLE
Queue does not populate "comment" metadata, only if the song is actually being played

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#1399]
### Describe the bug
mpd.conf consist of the following line
`metadata_to_use "artist,album,title,track,genre,date,comment"`

Queue does not populate "comment" metadata, only if the song is actually being played, this used to be OK in the past, not sure when exactly it got broken - I believe in recet versions

## Expected Behavior
query the queue should present all the available comments
`mpc -f %comment% playlist | sort | uniq | wc -l` = 0

## Actual Behavior
but unlike "genre" when pulling all available comments, the command comes up empty
`mpc -f %genre% playlist | sort | uniq | wc -l` = 3

the comments are "added" to the queue only if the song is actually being played
this happens also with graphical mpd clients which makes sense as this is all happening on the MPD server

## Version
Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

**Comment by MaxKellermann** [comment]
You omitted the log. I don't see anything about how you populate the queue.

**Comment by roizcorp** [comment]
`[roi@x250 mpd]$ mpc -w add /
[roi@x250 mpd]$ cat mpd.log
Jan 05 12:38 : event: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Jan 05 12:38 : state_file: Loading state file /home/roi/.config/mpd/mpdstate
Jan 05 12:38 : client: [0] opened from [::1]:58230
Jan 05 12:38 : client: [0] process command "config"
Jan 05 12:38 : client: [0] command returned 3
Jan 05 12:38 : client: [0] process command list
Jan 05 12:38 : client: process command "add """
Jan 05 12:38 : client: command returned 0
Jan 05 12:38 : client: [0] process command list returned 0
Jan 05 12:38 : client: [0] closed
`

mpd.cond db configuration - satelite
`database {
        plugin "proxy"
        host "piamos"
        port "6600"
}

music_directory         "nfs://white-nas/nfs/Public/Music"`

**Comment by roizcorp** [comment]
ack?

**Comment by MaxKellermann** [comment]
You're using the "proxy" plugin - what is the configuration on that MPD instance?

**Comment by MaxKellermann** [comment]
No reply

**Comment by roizcorp** [comment]
That's odd, I recall I answered, I took your hint and added "comment" to the MPD of the proxy, it worked...
I literally remember thanking you and asking you to close the issue...(I wonder which issue i actually typed these words)
Thanks anyway and sorry for the delay
