### ISSUE TITLE
MPD stops playing the current queue when not empty #2

### ISSUE THREAD

**Issue by owl770** [MusicPlayerDaemon/MPD#143]
Hi - I am running MPD 0.21 (v0.20.11-451-gb4b468e) on a RPi3 (stretch).

I run MPD with single=off, repeat=off, consume=on, random=on, xfade=10. MPD sometimes stops playing even when there are songs in the queue.
Player::Run() is falling out of the while(true) loop at the break just after pc.outputs.Drain(); indicating that the queue is empty (which it is not) and causing the player to stop.
When MPD first starts (with my config), "current" is zero and stays at zero as long as you let the queue play without interruption - it empties the queue as expected.
However, if you change songs whilst one is already playing, "current" gets incremented for each change. PlayPosition() calls MoveOrderToCurrent() which calls MoveOrderAfter which increments "current".
This means that "current" can approach "length" and if "current" gets to within 1 of "length", GetNextOrder will return -1 and MPD will stop playing but there will still be songs in the queue.

Please let me know if you need more info. Thanks.

**Comment by MaxKellermann** [comment]
Works as designed (but not as you thought it was designed). MPD plays each song exactly once (unless you enable "repeat"). What you did was skip songs, and those songs will not be played again.
Don't get confused by your use of "consume" mode: all "consume" does is delete songs which have been played to the end, but it does not change the rule I described above. What "consume" does **not** is imply that the queue will be empty when MPD stops playback. If you want that, enable "repeat" as well, so MPD restarts the queue until "consume" has deleted everything.
