### ISSUE TITLE
Mpd don't update all the songs of directory

### ISSUE THREAD

**Issue by gabrielzschmitz** [MusicPlayerDaemon/MPD#1440]
### Describe the bug
When I exec 'mpd update' or 'mpc rescan' there're some songs that dont appear into database

## Version
Music Player Daemon 0.23.5 (0.23.5)

## Log
'mpd --verbose'=
config_file: loading file /home/gabrielzschmitz/.config/mpd/mpd.conf
exception: Default TCP listener setup failed, but this is okay because we have a $XDG_RUNTIME_DIR listener: Failed to bind to '[::]:6600'; Failed to bind socket: Address already in use
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.31
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
exception: Database corrupted
input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.81.0
curl: with OpenSSL/1.1.1m

**Comment by gabrielzschmitz** [comment]
## Expected Behavior
It should read 242 musics

## Actual Behavior
But read just 103 of them

**Comment by owl770** [comment]
The line in the log file `exception: Database corrupted` indicates that the database is corrupted.
You could try stopping MPD, deleting the database (whatever `db_file` in `mpd.conf` points to) and restarting MPD.
MPD will then rebuild the database.

**Comment by MaxKellermann** [comment]
> The line in the log file `exception: Database corrupted` indicates that the database is corrupted. You could try stopping MPD, deleting the database (whatever `db_file` in `mpd.conf` points to) and restarting MPD. MPD will then rebuild the database.

MPD will rebuild the database automatically when it's corrupt. But @gabrielzschmitz's log does not show that the update ever finishes; it's incomplete.

Also the bug report does not contain any description about which songs are omitted, and the `mpd --version` output is incomplete.

See https://www.musicpd.org/help/

**Comment by gabrielzschmitz** [comment]
Full `mpd --version` =

Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 tcp un

**Comment by gabrielzschmitz** [comment]
> The line in the log file `exception: Database corrupted` indicates that the database is corrupted. You could try stopping MPD, deleting the database (whatever `db_file` in `mpd.conf` points to) and restarting MPD. MPD will then rebuild the database.

I've tried that multiple times, but nothing changes.

`mpd --verbose` now:

config_file: loading file /home/gabrielzschmitz/.config/mpd/mpd.conf
exception: Default TCP listener setup failed, but this is okay because we have a $XDG_RUNTIME_DIR listener: Failed to bind to '[::]:6600'; Failed to bind socket: Address already in use
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.31
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
exception: Database corrupted
input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.81.0
curl: with OpenSSL/1.1.1m

**Comment by MaxKellermann** [comment]
Your log is still incomplete, and you still did not describe which files are missing.

**Comment by gabrielzschmitz** [comment]
> Also the bug report does not contain any description about which songs are omitted

`mpd --verbose --stdout --no-daemon` output=

config_file: loading file /home/gabrielzschmitz/.config/mpd/mpd.conf
server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.31
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
decoder: Decoder plugin 'wildmidi' is unavailable: confiuration file does not exist: /etc/timidity/timidity.cfg
exception: Failed to open '/home/gabrielzschmitz/.config/mpd/mpddatabase.db': No such file or directory
input: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.81.0
curl: with OpenSSL/1.1.1m
event: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
update: spawned thread for update job id 1
update: starting
state_file: Loading state file /home/gabrielzschmitz/.config/mpd/mpdstate
inotify: initializing inotify
update: reading /slow hours.mp3
inotify: watching music directory
config: option 'device' on line 23 was not recognized
config: option 'buffer_time' on line 25 was not recognized
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: LAME track gain found: -7
mad: encoder delay is 576, encoder padding is 827
update: added /slow hours.mp3
update: reading /witchblades (ft. Lil Tracy).mp3
update: reading /mixtape pra você ouvir enquanto sente saudade da pessoa amada.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1328
update: added /mixtape pra você ouvir enquanto sente saudade da pessoa amada.mp3
update: reading /Hung Up (Chediak HYPERDRIVE Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 917
update: added /Hung Up (Chediak HYPERDRIVE Remix).mp3
update: reading /Bring Me Home.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1046
update: added /Bring Me Home.mp3
update: reading /waiting for u w_ swell.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 936
update: added /waiting for u w_ swell.mp3
update: reading /Mountains (Chediak Flip).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1177
update: added /Mountains (Chediak Flip).mp3
update: reading /Flamingos (ft. Tuyo).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1681
update: added /Flamingos (ft. Tuyo).mp3
update: reading /coisas que eu sei remix (w allex).mp3
update: added /coisas que eu sei remix (w allex).mp3
update: reading /Tightrope (Feat. Scott James).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1188
update: added /Tightrope (Feat. Scott James).mp3
update: reading /right here w horse head (prod. nedarb).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1188
update: added /Tightrope (Feat. Scott James).mp3
update: reading /right here w horse head (prod. nedarb).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /right here w horse head (prod. nedarb).mp3
update: reading /New Wave.mp3
update: added /New Wave.mp3
update: reading /musa + jedwill = old ways.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1440
update: added /musa + jedwill = old ways.mp3
update: reading /Macete.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1372
update: added /Macete.mp3
update: reading /LOST ROOM 001 (BROONO).mp3
update: added /LOST ROOM 001 (BROONO).mp3
update: reading /Coast Is Clear with Chance the Rapper and The Social Experiment.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1416
update: added /Coast Is Clear with Chance the Rapper and The Social Experiment.mp3
update: reading /Formula (IMANU Remix).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1266
update: added /Formula (IMANU Remix).mp3
update: reading /Piloto.mp3
update: added /Piloto.mp3
update: reading /crazy (enzo dicarlo remix).mp3
update: added /crazy (enzo dicarlo remix).mp3
update: reading /sometimes things change.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 996
update: added /sometimes things change.mp3
update: reading /Ela Fode Na Onda.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1186
update: added /Ela Fode Na Onda.mp3
update: reading /San Holo @ Secret Sky 2020 [mixed feelings 1].mp3
update: added /San Holo @ Secret Sky 2020 [mixed feelings 1].mp3
update: reading /feelingssss.mp3
update: added /feelingssss.mp3
update: reading /whoa (mind in awe) (Instrumental).mp3
update: added /whoa (mind in awe) (Instrumental).mp3
update: reading /Me Desculpa Jay Z.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Me Desculpa Jay Z.mp3
update: reading /WingRiddenAngel.mp3
update: added /WingRiddenAngel.mp3
update: reading /IFHY.mp3
update: added /IFHY.mp3
update: reading /Star Shopping.mp3
update: added /Star Shopping.mp3
update: reading /Akatsuki de Vila.mp3
update: added /Akatsuki de Vila.mp3
update: reading /Gemini Ft. George Maple (Ekali Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Gemini Ft. George Maple (Ekali Remix).mp3
update: reading /Bonde Do Neo Soul (Chediak Remix).mp3
update: added /Bonde Do Neo Soul (Chediak Remix).mp3
update: reading /Lilith.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 865
update: added /Lilith.mp3
update: reading /mel.mp3
update: added /mel.mp3
update: reading /posição.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /posição.mp3
update: reading /Banho de Sol [Prod. DKVPZ].mp3
update: added /Banho de Sol [Prod. DKVPZ].mp3
update: reading /bye bye navigator (mashup).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1224
update: added /bye bye navigator (mashup).mp3
update: reading /Sem Querer (slashrr Remix).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Sem Querer (slashrr Remix).mp3
update: reading /Sinto Tanta Raiva....mp3
update: added /Sinto Tanta Raiva....mp3
update: reading /rocket.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 864
update: added /rocket.mp3
update: reading /Hacker Dresscode.mp3
update: added /Hacker Dresscode.mp3
update: reading /Need Chill.mp3
update: added /Need Chill.mp3
update: reading /Beat It.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Beat It.mp3
update: reading /20 Ligações.mp3
update: added /20 Ligações.mp3
update: reading /Between The Sun And I (feat. Ardlez).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1452
update: added /Between The Sun And I (feat. Ardlez).mp3
update: reading /the way i see things (prod. kryptik).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /the way i see things (prod. kryptik).mp3
update: reading /Riders.mp3
update: added /Riders.mp3
update: reading /backseat (prod. smokeasac).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1105
update: added /backseat (prod. smokeasac).mp3
update: reading /Rosa Norte ft. Vhoor.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Rosa Norte ft. Vhoor.mp3
update: reading /Imortais e Fatais 2 [ft. Vinicius de Moraes].mp3
update: added /Imortais e Fatais 2 [ft. Vinicius de Moraes].mp3
update: reading /A Música Mais Triste do Ano.mp3
update: added /A Música Mais Triste do Ano.mp3
update: reading /Akatsuki de Vila, Pt. II.mp3
update: added /Akatsuki de Vila, Pt. II.mp3
update: reading /Sacanagem (ft. Chediak).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: LAME track gain found: -10.900001
mad: encoder delay is 576, encoder padding is 1566
update: added /Sacanagem (ft. Chediak).mp3
update: reading /Hope That It's You (feat. Annamarie Rosanio).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1152
update: added /Hope That It's You (feat. Annamarie Rosanio).mp3
update: reading /Plaqtudum (Chediak Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1152
update: added /Plaqtudum (Chediak Remix).mp3
update: reading /Give U The Moon.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1385
update: added /Give U The Moon.mp3
update: reading /SEE YOU AGAIN featuring Kali Uchis.mp3
update: added /SEE YOU AGAIN featuring Kali Uchis.mp3
update: reading /Por Cima.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1000
update: added /Por Cima.mp3
update: reading /Go Home (Very Rare).mp3
update: added /Go Home (Very Rare).mp3
update: reading /Envolvencia.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 652
update: added /Envolvencia.mp3
update: reading /Thom.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1439
update: added /Thom.mp3
update: reading /Life Is Beautiful.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 721
update: added /Life Is Beautiful.mp3
update: reading /I spoke to the devil in miami he said everything would be fine.mp3
update: added /I spoke to the devil in miami he said everything would be fine.mp3
update: reading /Supersonic (My Existence).mp3
update: added /Supersonic (My Existence).mp3
update: reading /Kurt Cobain.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Kurt Cobain.mp3
update: reading /Você.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 650
update: added /Você.mp3
update: reading /Crônicas do Meu Ego.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 936
update: added /Crônicas do Meu Ego.mp3
update: reading /quinto elemento [prod biffe].mp3
update: added /quinto elemento [prod biffe].mp3
update: reading /ULTRAVIØLENT [adrenochrome] (slashrr Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1156
update: added /ULTRAVIØLENT [adrenochrome] (slashrr Remix).mp3
update: reading /Better Off [Dying] (prod. by smokeasac & IIVI).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1156
update: added /Better Off [Dying] (prod. by smokeasac & IIVI).mp3
update: reading /absolute in doubt w wicca phase springs eternal (prod. foxwedding).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1272
update: added /absolute in doubt w wicca phase springs eternal (prod. foxwedding).mp3
update: reading /ghostin..mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /ghostin..mp3
update: reading /attached.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 766
update: added /attached.mp3
update: reading /Where'd You Go (i miss you.).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Where'd You Go (i miss you.).mp3
update: reading /Not Lost. (Exploring).mp3
update: added /Not Lost. (Exploring).mp3
update: reading /Madrugada Dos Mortos.mp3
update: added /Madrugada Dos Mortos.mp3
update: reading /FOR YOUR EYES ONLY [acloudyskye bootleg].mp3
update: added /FOR YOUR EYES ONLY [acloudyskye bootleg].mp3
update: reading /Samba in Paris [ft. Gloria Groove].mp3
update: added /Samba in Paris [ft. Gloria Groove].mp3
update: reading /your heart was once like mine.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 705
update: added /your heart was once like mine.mp3
update: reading /Jesus Chorou Pt. II.mp3
update: added /Jesus Chorou Pt. II.mp3
update: reading /Caminhos.mp3
update: added /Caminhos.mp3
update: reading /Sua Alegria Foi Cancelada (Maffalda Remix).mp3
update: added /Sua Alegria Foi Cancelada (Maffalda Remix).mp3
update: reading /naive unprepared child.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1253
update: added /naive unprepared child.mp3
update: reading /Nego Drama parte 2 Prod. O Adotado.mp3
update: added /Nego Drama parte 2 Prod. O Adotado.mp3
update: reading /Rosa Norte 2 (ending) ft. Vhoor.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /Rosa Norte 2 (ending) ft. Vhoor.mp3
update: reading /Sex With My Ex.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1003
update: added /Sex With My Ex.mp3
update: reading /Venture.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 791
update: added /Venture.mp3
update: reading /Never.mp3
update: added /Never.mp3
update: reading /Vem Me Satisfazer.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1570
update: added /Vem Me Satisfazer.mp3
update: reading /walk away as the door slams w lil tracy (prod. yung cortex).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1224
update: added /walk away as the door slams w lil tracy (prod. yung cortex).mp3
update: reading /De Fato part niLL prod Maffalda.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /De Fato part niLL prod Maffalda.mp3
update: reading /Chanel.mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1336
update: added /Chanel.mp3
update: reading /lift me from the ground (Jaron Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 576
update: added /lift me from the ground (Jaron Remix).mp3
update: reading /Confessionário (prod. Vhulto).mp3
update: added /Confessionário (prod. Vhulto).mp3
update: reading /corro na cidade (feat. 33).mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
update: reading /Passinho.mp3
mad: detected LAME version 3.100 ("LAME3.100")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1344
update: added /Passinho.mp3
update: reading /Ninety.mp3
update: added /Ninety.mp3
update: reading /Anbu.mp3
update: added /Anbu.mp3
update: reading /Ought (slashrr Remix).mp3
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 720
update: added /Ought (slashrr Remix).mp3
update: reading /Makiko Hirohashi - The Name of Life いのちの名前.mp3
update: added /Makiko Hirohashi - The Name of Life いのちの名前.mp3
update: reading /All We Ever Do (feat. DRS & Paige Eliza).mp3
mpg123: mpg123_getformat() failed: Message: I am done with this track.

**Comment by MaxKellermann** [comment]
> you still did not describe which files are missing.

Sigh.

**Comment by gabrielzschmitz** [comment]
It just resolve it self...
