### ISSUE TITLE
RT not used with RT kernel

### ISSUE THREAD

**Issue by jer1956** [MusicPlayerDaemon/MPD#1450]
### Describe the bug
The service rt commands do not trigger real time priority 

## Expected Behavior
Using ps -eo pid, pri , ni, comm 
Should show a pri of 40 and a blank ni

## Actual Behavior
It shows a pri of 19 and a ni of 0.

## Version
Debian 0.22,6

## fix 
Add the command CPUSchedularProfile=fifo after the current rt commands

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported, but this issue probably stems from a different kind of misconfiguration. I can't tell because you didn't provide any information.
But adding `CPUSchedularProfile=fifo` as you suggested is a very bad idea. Never do that!

**Comment by jer1956** [comment]
Old? Is the latest offered by Debian . Ubuntu is even older. 
So what do you get using PS?
