### ISSUE TITLE
Occasional core dump with NFS music_directory

### ISSUE THREAD

**Issue by buckmelanoma** [MusicPlayerDaemon/MPD#1456]
### Describe the bug
MPD occasionally core dumps when using an NFS path as a music_directory. 

## Expected Behavior
No crash/core

## Actual Behavior
Occasional inconsistent crash

## Version
0.23.5

## Log
Feb 20 22:25:16 hostname systemd-coredump[3834]: [🡕] Process 3794 (mpd) of user 1000 dumped core.
                                              
                                              Module linux-vdso.so.1 with build-id 2ad6b24b487ac2a9c2901c8ddf457eeb465c1d5a
                                              Module libspa-journal.so with build-id 06592895de2df06a6c5352f10df43acc1c06fc74
                                              Module libspa-support.so with build-id 616a8aeaf15a6f76012067b6f495936d212b3aa5
                                              Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                                              Module libblkid.so.1 with build-id 9e4bb910a2e63ba71cae0e3b89c07fdd45033ff2
                                              Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                                              Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                                              Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                                              Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                                              Module libpangoft2-1.0.so.0 with build-id 9b0353693557b4fb68124a9dffac9b07678d86a1
                                              Module libmount.so.1 with build-id 765508fe9812e693ac41fd3d0aedd65d7a78b287
                                              Module libtiff.so.5 with build-id e8d89a0fb0847641ddb75c5f03fa89d68155a75d
                                              Module libjpeg.so.8 with build-id 879ca18a2f58c25d77ba881db3a44a5676ef6c7d
                                              Module libncursesw.so.6 with build-id 1f873ddb2c32ab39d0b7d8646d03680ffe99de7c
                                              Module libasyncns.so.0 with build-id 6acff139d56b5139ce5eb50a66c62b215e1d332d
                                              Module libbrotlicommon.so.1 with build-id a4ba3f4b4571c8272343b621da812a6e24a202a7
                                              Module libresolv.so.2 with build-id 46ffdf3d477a170314060c26927470d7399bc900
                                              Module libkeyutils.so.1 with build-id ac405ddd17be10ce538da3211415ee50c8f8df79
                                              Module libkrb5support.so.0 with build-id adf65240a4d2aba772d7a0772b4d015469934113
                                              Module libcom_err.so.2 with build-id 358b783c9b3d12ba8248519ea2e7f3da4c4e0297
                                              Module libk5crypto.so.3 with build-id eb8220b8f36675aac769450be4cb6bb7f97ec38a
                                              Module libkrb5.so.3 with build-id 72d26767c5cb1097db75a5f5bff88860233c902b
                                              Module libswresample.so.4 with build-id 4d48618e2741ffb88409e04795797c773a2fa8b8
                                              Module libXfixes.so.3 with build-id 0a05c7e8714522bfbdd7c0027c3e2a94965664b0
                                              Module libharfbuzz.so.0 with build-id 716df25c59c91f456ae107457e4250f7c32bde1b
                                              Module libmvec.so.1 with build-id 760a099552c4783b979e942bf839c2bbc5ff603d
                                              Module libpixman-1.so.0 with build-id 341f793dcada3a48a306a793d265a517e3f2e7d6
                                              Module libxcb-shm.so.0 with build-id fb797f299a446f559a95afcc168227482cc800d1
                                              Module libxcb-render.so.0 with build-id a37bdb37744b508be9dd29fd9ccb9bb0170d43e5
                                              Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
                                              Module libXrender.so.1 with build-id 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                                              Module libXext.so.6 with build-id d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                                              Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                                              Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                                              Module libffi.so.8 with build-id f90d8b734f6de9b25faedb8cbfab7054dafc0a42
                                              Module libpango-1.0.so.0 with build-id f7a7e74f7ade4cbcf3840f685d760da19b0dc38c
                                              Module libpangocairo-1.0.so.0 with build-id a47bf17ab99c1840764fca52a2d772800d81d6e1
                                              Module libgio-2.0.so.0 with build-id c4e89ca22afc7f17db176d2063fe379dbc88d99b
                                              Module libgdk_pixbuf-2.0.so.0 with build-id ca4beb15a30de8d8767f7bca8222038c61b58b36
                                              Module libcairo-gobject.so.2 with build-id abbf5a8a182ea1b8b7d68540df5c2e25c0bdae0c
                                              Module libhogweed.so.6 with build-id 2d70cff7b1841b4d9ca4e8e7726cd4b944c07fdc
                                              Module libnettle.so.8 with build-id 9a878e513c02007598fcf1e2e286c2203f13536e
                                              Module libtasn1.so.6 with build-id ee3429ca5e94718aea4fe5249fc859e0cd88e4e9
                                              Module libunistring.so.2 with build-id 015ac6d6bcb60b7d8bea31a80d1941b06e8636ab
                                              Module libp11-kit.so.0 with build-id cc372ea3c28c4d3dfc633b4d2e933c8584d2af16
                                              Module libcap.so.2 with build-id eb6dae97527fc89dbb0d5bb581a15acd02ae9f56
                                              Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                              Module libgpg-error.so.0 with build-id 82524ee3d1c4c2244d7cfdcc1e6eea5f9855f6c6
                                              Module libgcrypt.so.20 with build-id db45f5d5e0f7af1e77324fea1885f974619ad268
                                              Module libvorbisfile.so.3 with build-id 0010b21da05e318b42e718d90738febf58028141
                                              Module libubsan.so.1 with build-id 389a0335b986fa237d86c70c9a80b60cc89c0196
                                              Module libinstpatch-1.0.so.2 with build-id be6cf8f475d8e460ce2046e6cb8d822c11008398
                                              Module libreadline.so.8 with build-id 03c124180216a8077784ca035346856bd16060b9
                                              Module libSDL2-2.0.so.0 with build-id 22fe96b7d3f81263619557b09d5e2f55b763eb2f
                                              Module libportaudio.so.2 with build-id 305f95e5abdce86725f76773b241fbe88342102f
                                              Module libpulse-simple.so.0 with build-id 9d64e75bf1b71bac618a44d284d84bbd2397fff9
                                              Module libgmodule-2.0.so.0 with build-id 5da4523e8d6b5c244a0193e27093d1e61f6ac9e4
                                              Module libtheora.so.0 with build-id 8ac339551c67c0f716d70bd41c411e9c7f9e1ac9
                                              Module libdb-5.3.so with build-id 9422fdf20e44ff3d5c58f76ef36be3432c6057c3
                                              Module libpulsecommon-15.0.so with build-id 1ff39f66b974fdf20be485f556b48ff4e6c33868
                                              Module libgomp.so.1 with build-id 75d4bedf51d8d7bc41d78a1189d780a82c8ebaaf
                                              Module librt.so.1 with build-id 4761858b348db8303e872e515aa8d56c046c921c
                                              Module libbrotlidec.so.1 with build-id 45defc036e918e0140a72f1fbce6e7692d38241d
                                              Module libzstd.so.1 with build-id 72f3511cba7db578f6a2647925f35664da6c838b
                                              Module libgssapi_krb5.so.2 with build-id e6e098ad51ce7bdd3dbe902d7b0f69a90f8a9e08
                                              Module libcrypto.so.1.1 with build-id 4c926b672d97886b123e03a008387aecf0786de4
                                              Module libssl.so.1.1 with build-id 1024424ab33a3767da03f4fdb1fc1b02479f160f
                                              Module libpsl.so.5 with build-id 0229a201aaf5652186c9fdc192ebe52baf19d7f1
                                              Module libssh2.so.1 with build-id a4adfe44cc7ebd295b3b783361acc3dcfcea1d50
                                              Module libidn2.so.0 with build-id 1ce2b50ad9f9821c2c629b521cf5a3c99593d332
                                              Module libnghttp2.so.14 with build-id eca975f5266a67fc4895065727647e98ff99a128
                                              Module ld-linux-x86-64.so.2 with build-id c09c6f50f6bcec73c64a0b4be77eadb8f7202410
                                              Module libicudata.so.70 with build-id e1dcc2a88cfaafed882d09c90c668af0eed4efed
                                              Module libavutil.so.57 with build-id 5ead4c7d60a6063d382d23a53e253c879dd4d3c0
                                              Module libavcodec.so.59 with build-id 8f59ceada81ac689f4a84ca636ff815b7f703e84
                                              Module libdl.so.2 with build-id bb9bd2657bfba9f60bd34d2050cc63a7eb024bc4
                                              Module libdrm.so.2 with build-id 00816f0a71c7e4e388c10db6245dbb9c031732a9
                                              Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
                                              Module libvdpau.so.1 with build-id 96ac4ef0ce4b2bdbe091782d97eafadd6e4cea90
                                              Module libva-x11.so.2 with build-id e6a0ffef32570ba034a3724e735ba0fa90d39eee
                                              Module libva-drm.so.2 with build-id 5ac46263a883c725bfed65d98ff2e3162fd464ad
                                              Module libfreetype.so.6 with build-id 26c5f833068ff72660d1975cbc2074c3eb47fad8
                                              Module libfontconfig.so.1 with build-id 9fdeb38479c4090d673efc2e8cb60176efe65da1
                                              Module libzimg.so.2 with build-id 25c3481f3b09acafae5fb2cc6adb7791148941d6
                                              Module libvidstab.so.1.1 with build-id 8f75d19083cbc44f1cfda8fca285a23424dd2b2a
                                              Module libass.so.9 with build-id c3d3ce271a32a7749234134657aef9a1ab51690b
                                              Module libfribidi.so.0 with build-id 79124bad061c2aab4ec89f25d067363d5b781114
                                              Module libpostproc.so.55 with build-id ee689d58d0824c4bd1d4b3278bcf186d2719285c
                                              Module libswscale.so.5 with build-id c217dc87e1f76dbb488e21eee89bf1b11a22ca88
                                              Module libmfx.so.1 with build-id 8281ba744d2215511b252db50250f1d4e073d36d
                                              Module libva.so.2 with build-id d0042003bbdf0c10b26dbc25c80cb06eb64b4f5c
                                              Module libxvidcore.so.4 with build-id 43bc390a7842a7ca3a0302e93442ea561d7f013a
                                              Module libx265.so.199 with build-id 22130b9b0d2aa957b148b0fdeb27e3fd04f0fb58
                                              Module libx264.so.164 with build-id 75d0a8962c91bc5d81b3add303ba0b6c2fcef8eb
                                              Module libtheoradec.so.1 with build-id 19d321fd5455c7b7611ca9602a804b496124e06f
                                              Module libtheoraenc.so.1 with build-id cde750f0621140f313e4ef4e5f212e662f24a38b
                                              Module libSvtAv1Enc.so.0 with build-id 16a86797b9743608665ae8dffaebba7d492f7d05
                                              Module libspeex.so.1 with build-id 39721dbe21b62978562c2943279f6dffbffe8946
                                              Module librav1e.so.0 with build-id 2e9e70e2433e4d2955a870f2de730172729fbe4f
                                              Module libopenjp2.so.7 with build-id 0a329c12468c33c92ecbc3968f4dc9c79cc5db96
                                              Module libopencore-amrnb.so.0 with build-id a3d78948c85fa235e66549119b2f130e69af7b70
                                              Module libgsm.so.1 with build-id 1cc6240f7eaedaaac302bc7c0f64ebbeae596f22
                                              Module libaom.so.3 with build-id 3c057fe8c5fa7033366274352148acb4dbb42728
                                              Module libcairo.so.2 with build-id 06820af9cf79c2deb207d9533a61caf04e67a8ad
                                              Module libglib-2.0.so.0 with build-id 24e675eddd4654b470e0a892f4a4aec012b04160
                                              Module libgobject-2.0.so.0 with build-id 6d7ff6c8e4e9c12caa92cf25a74d3ecdd9461c36
                                              Module librsvg-2.so.2 with build-id ee2b5961f905a5f62b70dc6222968aaca76a0d81
                                              Module libopencore-amrwb.so.0 with build-id 28da8ed3dfca59280e835c46bd40da295dae99e2
                                              Module libdav1d.so.5 with build-id 82862181dbe48302fde94240f68e17fb6f9a03c7
                                              Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa0437d95e
                                              Module libwebp.so.7 with build-id 0add7a572705244ed810b7e722cce7da0dcfb62c
                                              Module libwebpmux.so.3 with build-id 4232d5263a45719ba12f58ed7d8cae3a0fc887de
                                              Module libvpx.so.7 with build-id 0dce08d8df560a9817a17291a53f905fd7d17c62
                                              Module libswresample.so.3 with build-id d5611c5832017715a8404bd2703a16a1b9933535
                                              Module libssh.so.4 with build-id 8490056688e60790230f9d990c439b181236e9b6
                                              Module libsrt.so.1.4 with build-id ad13eeb20e5ea3f04a0b089de1152ff89a9fa65c
                                              Module libgnutls.so.30 with build-id 50f3a52ba3db67b822fd5888790238eb548b64aa
                                              Module libgmp.so.10 with build-id e58d34ab389d1b649c24195c2d145e3ff2e58290
                                              Module libbluray.so.2 with build-id ebaa74ef4d549c1d3f01fafb8625045d286b8940
                                              Module libxml2.so.2 with build-id 34aa03d6fadb52a051964f0e50a977efaea9482e
                                              Module libpthread.so.0 with build-id 7fa8b52fae071a370ba4ca32bf9490a30aff31c4
                                              Module libc.so.6 with build-id 85766e9d8458b16e9c7ce6e07c712c02b8471dbc
                                              Module libgcc_s.so.1 with build-id 5d817452a709ca3a213341555ddcf446ecee37fa
                                              Module libm.so.6 with build-id 596b63a006a4386dcab30912d2b54a7a61827b07
                                              Module libstdc++.so.6 with build-id 88ad4eff81a00c684abfe0f863e87434123d8943
                                              Module libsystemd.so.0 with build-id a83a62063b8098eda274d25251d619f0503bf011
                                              Module libmpdclient.so.2 with build-id ab5c2ec68c709cb98396047084066f1d4dd4520d
                                              Module libtwolame.so.0 with build-id 1590e3fa9f48316cfce042b3e552f76359022b8e
                                              Module libmp3lame.so.0 with build-id 48c901805551a3dd58d02502c4cd67f6aa848107
                                              Module libvorbisenc.so.2 with build-id 28ed815b8b1d322e6bf2bfdce4b0af2789b74335
                                              Module libWildMidi.so.2 with build-id 2f9017a5d413f868dfe62c1c225795b851a79f01
                                              Module libwavpack.so.1 with build-id 1ac2a2b6c0943a3b2b4bde94e6bec88e97b9f54f
                                              Module libvorbis.so.0 with build-id ad0a6c1af8f219b4e314090b6e8847223d424cbe
                                              Module libogg.so.0 with build-id ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
                                              Module libsndfile.so.1 with build-id 72d5531e74ed3e9afe49e95e449c40cb8984a258
                                              Module libsidplayfp.so.6 with build-id 2d2a94017c8ff94327804c77bc65923660a279fa
                                              Module libopus.so.0 with build-id 35fafc4024675e9cfe57c7d50c3965eac6bac358
                                              Module libmpg123.so.0 with build-id d407ec260259c0c44763f426829d868e0ecede63
                                              Module libmpcdec.so.6 with build-id 0794d516f1da996f22be7c54da384c6a6365d34e
                                              Module libopenmpt.so.0 with build-id 165a592d8ae3f4db6a18f00b7a6e33292f406df5
                                              Module libmodplug.so.1 with build-id b00dcb12e7d2d5882b4fa414295eba449875dae4
                                              Module libmikmod.so.3 with build-id b7727056483836e5d171207586c6f827a501cb02
                                              Module libmad.so.0 with build-id 9ce3fef26f9bcd9cb386e7147c02875b0e45f79e
                                              Module libgme.so.0 with build-id 34780ed55da1e6da65ff4f6c5a40a1d9c35fc5d3
                                              Module libfaad.so.2 with build-id 75e2ecdd670261f35855b77646f78d4e0e52b723
                                              Module libaudiofile.so.1 with build-id fdede1cb13565ed9119f68b41fc05330dd8bc467
                                              Module libfluidsynth.so.3 with build-id 7ef38e96844b5b4a05c2e57b2a79deffe98b3244
                                              Module libFLAC.so.8 with build-id e568dc3d434723c72d6d302eb0b2559f27e91faa
                                              Module libavahi-client.so.3 with build-id 1858551543958190c653b565cf0eb64609ad908a
                                              Module libavahi-common.so.3 with build-id 80fda945459a3476ccd1050783dfd5f5c17c479a
                                              Module libopenal.so.1 with build-id 3a1a35c74035e1493c7bf0c9b30c73fe5eba26bc
                                              Module libshout.so.3 with build-id 92b70fe2b20a023c1d9c98d7bd321a7a6c645d4d
                                              Module libpipewire-0.3.so.0 with build-id 86eb6e31f49d742ad29649c758f4b736b346a35d
                                              Module libjack.so.0 with build-id cd2c5ca3b195fe16a2cfcda1f5246ea2fc169b5a
                                              Module libao.so.4 with build-id afafaa6478de7f1d9e20b3f157943bbabd384955
                                              Module libpulse.so.0 with build-id b145e13bdb30c8327de7882ec9976fab38bc3e4a
                                              Module libzzip-0.so.13 with build-id 3c78894f81dac5d95a87ebd04ebbad3b36f54398
                                              Module libiso9660.so.11 with build-id 84807c7758b52a58d195041627393ba194c5f34b
                                              Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                              Module libid3tag.so.0 with build-id d85400f3117db0f000f5b9f95c11a13cfb3f49a1
                                              Module libsoxr.so.0 with build-id 9e49936ed807c1e52705b88d5d71706fe11d9ed1
                                              Module libsamplerate.so.0 with build-id e7eba744904f8220874bf5883c90c15b887e4deb
                                              Module libasound.so.2 with build-id b17fc1317a484842433c772360376623b64ec3d8
                                              Module libnfs.so.14 with build-id 519a648cd06b4f523b18e53b703a269bd38d1be4
                                              Module libmms.so.0 with build-id bf9be39d5c7cd76d2ae9b617508f291ce9f09c80
                                              Module libcdio.so.19 with build-id b378a41a8f3f007797133df4ed03790f3de12e3d
                                              Module libcdio_cdda.so.2 with build-id 0df8d5e677509a15d63574927e126483fbe418e0
                                              Module libcdio_paranoia.so.2 with build-id c098ca2399ac750022db5457ba1ab5acf14e8bcb
                                              Module libexpat.so.1 with build-id 3174e8ac54cc06c4aea87cc79bd0fbaf5f7d311a
                                              Module libcurl.so.4 with build-id d4dec3d9f8c789ec28d441f2a3f73d532809e6ef
                                              Module libixml.so.11 with build-id 60d6fbead5a8974cc94e00de7a66eb68f488b29a
                                              Module libupnp.so.17 with build-id d4306e3e17478a591eb4d2e1620a0aca293947d7
                                              Module libicuuc.so.70 with build-id 2e245c2bf12f95fd8ab79b3a4be99524677cbd70
                                              Module libicui18n.so.70 with build-id 95af755fca990df26753a7d720b8e3ae24270e42
                                              Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6a6a26
                                              Module libchromaprint.so.1 with build-id 15a9aeba93f20a44d08de392ea8b60ba5aea3bca
                                              Module libsqlite3.so.0 with build-id 5f711261aabe285f02a673ded77a37b413afbfa2
                                              Module libpcre2-8.so.0 with build-id 7ade7d8b44c84833a41fe87f30330ce17458808a
                                              Module libyajl.so.2 with build-id 392467faca2d964441b8226ee48d994ffc70e545
                                              Module libavutil.so.56 with build-id f51e23b257f3c51881c1fafc553c3af2202eb105
                                              Module libavfilter.so.7 with build-id a56e88b3f4835a09c18a7387c96b72ec07784a02
                                              Module libavcodec.so.58 with build-id 5d85767cd5be978f10e4e06efabf0d62de5dbbbd
                                              Module libavformat.so.58 with build-id a7731af49d5004c33553da56ea4c81893de6f5bf
                                              Module libfmt.so.8 with build-id c3f6708fe8ace56083397602097e9964d80a020f
                                              Module liburing.so.2 with build-id c7f5471ffaddf14493c661e39976cf4f43aa43a1
                                              Module libdbus-1.so.3 with build-id 74f2ab9c60512f3a93c932c3f627564d42e0b11e
                                              Module mpd with build-id 0a931da20a24a480841147d2be952ee4abbd2996
                                              Stack trace of thread 3794:
                                              #0  0x00007f76aad5f8a4 __pthread_mutex_lock@GLIBC_2.2.5 (libc.so.6 + 0x908a4)
                                              #1  0x00007f76ad3c4c92 pw_thread_loop_lock (libpipewire-0.3.so.0 + 0x8ac92)
                                              #2  0x0000558a969e3e92 n/a (mpd + 0xc5e92)
                                              #3  0x0000558a96a2d2fc n/a (mpd + 0x10f2fc)
                                              #4  0x0000558a969eb4bd n/a (mpd + 0xcd4bd)
                                              #5  0x0000558a969eb79f n/a (mpd + 0xcd79f)
                                              #6  0x0000558a9697c92c n/a (mpd + 0x5e92c)
                                              #7  0x0000558a9696d9e5 n/a (mpd + 0x4f9e5)
                                              #8  0x0000558a969781ed n/a (mpd + 0x5a1ed)
                                              #9  0x0000558a969a7271 n/a (mpd + 0x89271)
                                              #10 0x0000558a969ab506 n/a (mpd + 0x8d506)
                                              #11 0x0000558a969a88f6 n/a (mpd + 0x8a8f6)
                                              #12 0x0000558a969719e6 n/a (mpd + 0x539e6)
                                              #13 0x0000558a96972a74 n/a (mpd + 0x54a74)
                                              #14 0x0000558a96968fce n/a (mpd + 0x4afce)
                                              #15 0x00007f76aacfc310 __libc_start_call_main (libc.so.6 + 0x2d310)
                                              #16 0x00007f76aacfc3c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d3c1)
                                              #17 0x0000558a969692c5 n/a (mpd + 0x4b2c5)
                                              
                                              Stack trace of thread 3800:
                                              #0  0x00007f76aade19ae epoll_wait (libc.so.6 + 0x1129ae)
                                              #1  0x0000558a969a86cc n/a (mpd + 0x8a6cc)
                                              #2  0x0000558a969a3d71 n/a (mpd + 0x85d71)
                                              #3  0x00007f76aad5c5c2 start_thread (libc.so.6 + 0x8d5c2)
                                              #4  0x00007f76aade1584 __clone (libc.so.6 + 0x112584)
                                              
                                              Stack trace of thread 3801:
                                              #0  0x00007f76aade19ae epoll_wait (libc.so.6 + 0x1129ae)
                                              #1  0x0000558a969a86cc n/a (mpd + 0x8a6cc)
                                              #2  0x0000558a969a3d71 n/a (mpd + 0x85d71)
                                              #3  0x00007f76aad5c5c2 start_thread (libc.so.6 + 0x8d5c2)
                                              #4  0x00007f76aade1584 __clone (libc.so.6 + 0x112584)
                                              ELF object binary architecture: AMD x86-64
Feb 20 22:25:16 hostname systemd[1614]: mpd.service: Main process exited, code=dumped, status=11/SEGV
Feb 20 22:25:16 hostname systemd[1614]: mpd.service: Failed with result 'core-dump'.

**Comment by buckmelanoma** [comment]
Output of mpd -V:

Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

**Comment by MaxKellermann** [comment]
Your MPD executable is stripped, which makes your backtrace useless.

**Comment by buckmelanoma** [comment]
Sorry to waste your time.
