### ISSUE TITLE
Lots of compiler warnings...

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#146]
... introduced with todays changes.

MPD from git, made clean, gcc version 7.2.1 20171025 (Debian 7.2.0-12) on Debian testing x64

eg `warning: mangled name for ‘BoundMethod<R(Args ...)>::operator bool() const [with R = void; Args = {}]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]`

**Comment by MaxKellermann** [comment]
This warning is bogus, because MPD explicitly chooses C++14, not C++17.
