### ISSUE TITLE
MPD‘s rule for format recognizing 

### ISSUE THREAD

**Issue by ltrsunny** [MusicPlayerDaemon/MPD#1467]
### Describe the bug
In some apps like NetEase Cloud Music, if you push a song in wav/m4a format via DLNA (by upmpdcli) to MPD, MPD will get a path like "http://[host:port]/mp3?filepath=xxx.wav",
then MPD try using mad to decode the file which is not a real mp3 stream, and then there will be loud noise generated from the output. 

If I disabled mad in config, then MPD will use ffmpeg to decode the "fake mp3 stream", and played the wav/m4a successfully.

## Expected Behavior
Use the correct decoder.

## Actual Behavior
Use mad to decode non-mp3 file.

## Version

Music Player Daemon 0.23.4 (v3.15.0_rc1-162-ga5cf1519d8)

## Log

player: played "http://192.168.50.26:61323/mp3?filepath=%2Fstorage%2Femulated%2F0%2F%E9%9F%B3%E4%B9%90%2F05_Move.wav&decode=false"

**Comment by ltrsunny** [comment]
There is another format from NetEase Cloud Music which cannot be decoded by mad but can by ffmpeg.

**Comment by MaxKellermann** [comment]
Your log is incomplete.

> Use the correct decoder.

What is the "correct decoder"? Describe one example - which container and which codec is used? What MIME type does the web server specify?

**Comment by ltrsunny** [comment]
> What is the "correct decoder"? Describe one example - which container and which codec is used? What MIME type does the web server specify?

In my log, it is a .wav file but there is an "mp3" string in the path and mpd try using mad to decode it.

**Comment by MaxKellermann** [comment]
That answers zero of my questions.
