### ISSUE TITLE
License

### ISSUE THREAD

**Issue by iamjkdn** [MusicPlayerDaemon/MPD#147]
Hey
Like to know about the commercial usage?
Basically, can I use it in a raspberry pi and sell this?
The Pi would have other programs as well like my own touch screen controller and music dsp enhancement software and one Apache 2 licensed tts software.
I understand I need to show the license notice with my product somewhere. 
I am not clear on the source code part. 
Clearly, what part of source needs to be made public,
1. Only MPD
2. MPD with my 2 personal code
3. MPD with my 2 personal code and Apache code as well

Alternatively, will it be cool I can enter into a commercial agreement with you?

Regards.

**Comment by MaxKellermann** [comment]
For legal advice, you should consult a lawyer. IANAL!
The GPL allows selling the software, as long as you fulfull all of the GPL requirements (which are basically the same for non-commercial distribution).
You must provide the source code for all code which is a combined/derived work with/of MPD. What constitutes a "combined work" is a question for your lawyer, but I'm pretty sure that a software which communicates with MPD over a socket (i.e. a MPD client) is not a "combined work", even if it's part of the same filesystem/firmware image.
