### ISSUE TITLE
Android: unable to decode - HTTPS storage

### ISSUE THREAD

**Issue by MrPixelized** [MusicPlayerDaemon/MPD#1477]
### Describe the bug
When using a webdav server with https:// prefix for "music_directory", MPD fails to play any of the songs. When using the same server over http, there is no problem.

## Expected Behavior
The songs would be played.

## Actual Behavior
An "unable to decode" error is returned, and no song can be played.

## Version
Both F-droid and Google Play versions.

**Comment by MaxKellermann** [comment]
Incomplete bug report.
