### ISSUE TITLE
decoder: Decoder plugin 'wildmidi' is unavailable

### ISSUE THREAD

**Issue by chwt163** [MusicPlayerDaemon/MPD#1478]
Windows10，Start reporting errors：

C:\Users\123\AppData\Local\mpd>mpd mpd.conf
Mar 09 17:04 : decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg

My mpd.conf:

music_directory		"D:\music"
playlist_directory		"D:\music/mpd/playlists"
db_file			"D:\music/mpd/tag_cache"
log_file			"D:\music/mpd/mpd.log"
pid_file			"D:\music/mpd/pid"
state_file			"D:\music/mpd/state"
sticker_file                   "D:\music/mpd/sticker.sql"
#######################################
#user				"123"
#group                          "nogroup"
bind_to_address		        "localhost"
port				"6600"
#######################################
input {
        plugin "curl"
#proxy "proxy.isp.com:8080"
#proxy_user "user"
#proxy_password "password"
}
audio_output {
    type "winmm"
    name "Speakers"
#device "Speakers (Realtek High Definition Audio)"
}
audio_output {
    type "httpd"
    name "My HTTP Stream"
    encoder "vorbis" # optional, vorbis or lame
    port "8000"
    # quality "5.0" # do not define if bitrate is defined
    bitrate "128" # do not define if quality is defined
    format "44100:16:1"
}
decoder {
    plugin "wildmidi"
    config_file "/etc/timidity/timidity.cfg"
}
#############################################
filesystem_charset		"UTF-8"
#id3v1_encoding			"UTF-8"
#############################################

**Comment by MaxKellermann** [comment]
That's because you configured a config_file which does not exist!

**Comment by chwt163** [comment]
"decoder {
    plugin "wildmidi"
    config_file "/etc/timidity/timidity.cfg"
}" 
At the beginning, there was no code above, and it was the same startup error, which I added later.

**Comment by chwt163** [comment]
> That's because you configured a config_file which does not exist!

Can you tell me how to write mpd.conf? Thanks!

**Comment by lmoellendorf** [comment]
I get  a similar error:

```
2025-09-17T22:22:34 decoder: Decoder plugin "wildmidi" is unavailable: System Error (_WM_BufferFileImpl:227) ~/.timidity/current/timidity.cfg (Unable to stat) : No such file or directory                                              [ ok ]
```

This is my `/etc/mpd.conf` (note: no mention of "wildmidi" or the path `~/.timidity/current/timidity.cfg`):

```
music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"

log_file "/var/log/mpd/mpd.log"

pid_file "/run/mpd/mpd.pid"

state_file "/var/lib/mpd/state"

user "mpd"
group "audio"
bind_to_address "localhost"
bind_to_address "/var/lib/mpd/socket"

input {
        plugin "curl"
}

audio_output {
        type            "pulse"
        name            "Stereo Pulse Output"
        mixer_type      "software"
        format          "44100:16:2"
}

audio_output {
        type            "pulse"
        name            "Mono Pulse Output"
        mixer_type      "software"
        format          "44100:16:1"
}

audio_output {
        type  "fifo"
        name  "mpdFIFO"
        path  "/tmp/mpd.fifo"
        enabled  "yes"
        format  "44100:16:2"
}
```

`mpd` runs well, but this error is annoying.
