### ISSUE TITLE
libsoundfile plugin misstreats wave files

### ISSUE THREAD

**Issue by helohe** [MusicPlayerDaemon/MPD#148]
I have two wave files which play fine using aplay and for which libsoundfile can extract correct information. Here the soxi output:

Input File     : 'stream.wav'
Channels       : 2
Sample Rate    : 176400
Precision      : 24-bit
Duration       : 00:50:43.49 = 536870906 samples ~ 228261 CDDA sectors
File Size      : 5.16M
Bit Rate       : 13.6k
Sample Encoding: 32-bit Floating Point PCM

Input File     : 'stream2.wav'
Channels       : 2
Sample Rate    : 176400
Precision      : 24-bit
Duration       : 01:07:37.98 = 715827874 samples ~ 304349 CDDA sectors
File Size      : 6.78M
Bit Rate       : 13.4k
Sample Encoding: 24-bit Signed Integer PCM

However MPD handles those files wrong and they just produce noise. Here the log of MPD at the relevant parts:

Nov 13 09:42 : client: [9] opened from local
Nov 13 09:42 : client: [9] process command "play"
Nov 13 09:42 : playlist: play 0:"stream.wav"
Nov 13 09:42 : decoder_thread: probing plugin sndfile
Nov 13 09:42 : decoder: audio_format=176400:f:2, seekable=true
Nov 13 09:42 : client: [9] command returned 0
Nov 13 09:42 : alsa_output: opened hw:0,0 type=HW
Nov 13 09:42 : alsa_output: buffer: size=64..65536 time=362..371520
Nov 13 09:42 : alsa_output: period: size=32..32768 time=181..185760
Nov 13 09:42 : alsa_output: default period_time = buffer_time/4 = 371519/4 = 92879
Nov 13 09:42 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Nov 13 09:42 : alsa_output: buffer_size=65536 period_size=16384
Nov 13 09:42 : output: opened plugin=alsa name="My ALSA Device" audio_format=176400:32:2
Nov 13 09:42 : output: converting in=176400:f:2 -> f=176400:f:2 -> out=176400:32:2
Nov 13 09:42 : client: [9] process command list
Nov 13 09:42 : client: process command "status"
Nov 13 09:42 : client: command returned 0
Nov 13 09:42 : client: process command "currentsong"

...
Nov 13 09:44 : client: [13] process command "play"
Nov 13 09:44 : playlist: play 0:"stream2.wav"
Nov 13 09:44 : decoder_thread: probing plugin sndfile
Nov 13 09:44 : decoder: audio_format=176400:32:2, seekable=true
Nov 13 09:44 : client: [13] command returned 0
Nov 13 09:44 : client: [13] process command list
Nov 13 09:44 : client: process command "status"
Nov 13 09:44 : client: command returned 0
Nov 13 09:44 : client: process command "currentsong"
Nov 13 09:44 : client: command returned 0
Nov 13 09:44 : client: [13] process command list returned 0
Nov 13 09:44 : client: [13] closed
Nov 13 09:44 : alsa_output: opened hw:0,0 type=HW
Nov 13 09:44 : alsa_output: buffer: size=64..65536 time=362..371520
Nov 13 09:44 : alsa_output: period: size=32..32768 time=181..185760
Nov 13 09:44 : alsa_output: default period_time = buffer_time/4 = 371519/4 = 92879
Nov 13 09:44 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Nov 13 09:44 : alsa_output: buffer_size=65536 period_size=16384
Nov 13 09:44 : output: opened plugin=alsa name="My ALSA Device" audio_format=176400:32:2
Nov 13 09:44 : client: [1] process command list

[files.zip](https://github.com/MusicPlayerDaemon/MPD/files/1466311/files.zip)

I think the problem might be in those two parts of the code (https://github.com/MusicPlayerDaemon/MPD/blob/master/src/decoder/plugins/SndfileDecoderPlugin.cxx) which do not handle 24 bit files correctly:

```
gcc_pure
static SampleFormat
sndfile_sample_format(const SF_INFO &info) noexcept
{
	switch (info.format & SF_FORMAT_SUBMASK) {
	case SF_FORMAT_PCM_S8:
	case SF_FORMAT_PCM_U8:
	case SF_FORMAT_PCM_16:
		return SampleFormat::S16;

	case SF_FORMAT_FLOAT:
	case SF_FORMAT_DOUBLE:
		return SampleFormat::FLOAT;

	default:
		return SampleFormat::S32;
	}
}

static sf_count_t
sndfile_read_frames(SNDFILE *sf, SampleFormat format,
		    void *buffer, sf_count_t n_frames)
{
	switch (format) {
	case SampleFormat::S16:
		return sf_readf_short(sf, (short *)buffer, n_frames);

	case SampleFormat::S32:
		return sf_readf_int(sf, (int *)buffer, n_frames);

	case SampleFormat::FLOAT:
		return sf_readf_float(sf, (float *)buffer, n_frames);

	default:
		assert(false);
		gcc_unreachable();
	}
}
```

**Comment by MaxKellermann** [comment]
The code you pasted above is correct. Yes, it **does** handle 24 bit files correctly. The thing is that `libsndfile` (not `libsoundfile`!) has no API for 24 bit data, so MPD uses the next best API, which is 32 bit. And `libsndfile` guarantees to shift 24 bit to 32 bit, so MPD is correct.
I can play both of your files perfectly fine with this plugin. My random guess (since you provided no information at all! I don't even know your MPD version number or your libsndfile version number) is that your sound chip or your DSP are incapable of these audio formats, and instead emit noise. But I don't know. In any case, the `sndfile` plugin looks correct.
