### ISSUE TITLE
hiccup in cdio_paranoia 

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#149]
Every few seconds there is a "pause", mpd becomes unresponsive and so on.
Both 0.20.11 and current git.
libc is musl, kernel is 4.13.12, architecture x86 (32bit),
libcdio-0.94, libcdioparanoia-10.2+0.94+2

maybe paranoia is too paranoid? maybe accuracy is not priority here?
cdrom is connected via usb.

**Comment by MaxKellermann** [comment]
What does "becomes unresponsive" mean? What does "pause" mean? Check the verbose log for relevant messages.

**Comment by mistepien** [comment]
"Pause" means "lack of music" without setting player state to pause according to protocol.
During such "pause" sderr is also paused, meanwhile normally there is

> client: [2] process command "status"
client: [2] command returned 0
client: [2] process command "currentsong"
client: [2] command returned 0
client: [2] process command "playlistinfo "1437""
client: [2] command returned 0
client: [22] process command "status"

The only residue of "pause" lasting few seconds is

> alsa_output: Underrun on ALSA device "hw:V102,0"

hw:V102,0 is my dac, and when files are played there no underruns.
dmesg says nothing. mpd 0.20.1 is solid like a rock in case of files.

**Comment by MaxKellermann** [comment]
Even if the decoder thread stalls, the main thread which handles client commands should continue to run normally. A stall in the main thread is unusual. Please use `strace -tttTp $(pidof mpd) -o /tmp/trace` during such a hiccup and upload the output file. That can I hope I can see where the main thread stalls.
Of course, a stall in the decoder thread and xrun in the output thread is expected when the input is too slow.

**Comment by mistepien** [comment]
mpd can be striped or no? should it be compiled in some special way?

**Comment by MaxKellermann** [comment]
At this stage, stripped is ok. Use the same binary which you used to observe the problem.

**Comment by mistepien** [comment]
ok, this trace, I stopped strace when mpd "paused".
[trace1.txt](https://github.com/MusicPlayerDaemon/MPD/files/1466839/trace1.txt)

**Comment by mistepien** [comment]
I changed by bluray writer to old cd-rom. Pauses are now 1-2 seconds long every 15 seconds.

**Comment by MaxKellermann** [comment]
Thanks, that trace was very useful. I think I found the problem. Please test with branch unlock_cdio (https://github.com/MusicPlayerDaemon/MPD/tree/unlock_cdio)

**Comment by mistepien** [comment]
It works like a charm. Thanks a lot. No hiccups, even with bluray writer it works just great.

**Comment by MaxKellermann** [comment]
Yay! This was an obvious mistake with MPD's mutex locking inside various input plugins, including the plugin which reads static file (what nearly everybody uses). This change will improve MPD by a biiig margin!

**Comment by mistepien** [comment]
Maybe this is the same problem?

This time this is git version.
In playlist there are a lot of heavy files (eg. 192/24, dsd64 in wavpack) mixed with 44.1/16, meanwhile available output is 96/24.
Script with "sleep 0.3" randomly switches with "play" protocol command, after minute mpd is stalled and permanently unresponsive. I'm stuck with 20.x because git is not usefull. In normal usage it will hang up.

This is output of strace:

[trace2.txt](https://github.com/MusicPlayerDaemon/MPD/files/1469311/trace2.txt)

**Comment by project-owner** [comment]
From which MPD version the fix is available? Thanks!

**Comment by iglosiggio** [comment]
I just want to thank you for this fix, i recently bought a laptop and the wakeups from the HDD made mpd hiccup a lot. Updating solved the problem (and i think this issue solved it all).
