### ISSUE TITLE
Return FILE value from cuesheet virtual tracks lsinfo

### ISSUE THREAD

**Issue by jcorporation** [MusicPlayerDaemon/MPD#1495]
## Feature request

It would be great if the `lsinfo` command returns the `FILE` value from the cuesheet additionally to the other returned pairs for cuesheet virtual tracks.

**Comment by MaxKellermann** [comment]
Why?

**Comment by jcorporation** [comment]
My myMPD client displays a link to download the song in a detail view. This is without the file value from cuesheet virtual tracks not possible.

**Comment by MaxKellermann** [comment]
This would pollute the MPD protocol for a feature that is completely out of MPD's scope.
