### ISSUE TITLE
Add support for nonstandard "display artist" tag

### ISSUE THREAD

**Issue by apfelkuchen6** [MusicPlayerDaemon/MPD#1501]
## Feature request

For music with multiple artists, it's currently not possible to have access to the individual artists and the artist string with the correct join phrases as credited in the release (foo feat. bar; foo vs. bar; foo with bar; foo X bar; foo & bar etc). I would like a client to use the former for navigating the library, but display the latter in playlists and the now-playing indicator. This is only possible by using separate tags for the individual artists and the string for display use.

By default, MusicBrainz Picard puts the "display artist" into the artist tag (id3: TPE1, VorbisComment: ARTIST, APEv2: Artist)) and uses nonstandard "Artists" tags for the individual artists. This has been requested in #150.

I want to propose the converse approach: Keep the individual artists in separate instances of the artist tag and add support for a nonstandard display artist tag. More concretely, I propose a new "displayartist" mpd tag which will be populated by id3 "TXXX:DISPLAYARTIST", APEv2 "Display Artist" and VorbisComment "DISPLAYARTIST" tags.

These tags are obviously nonstandard and I was unable to find any other software using these or other tags for this purpose; I have only found people using this tagging approach with software supporting arbitrary tag names (like foobar2000 or MusicBee).

I would be willing to implement this if there is a chance that it will be accepted.

**Comment by MaxKellermann** [comment]
You have not explained what is wrong with what MPD clients are currently doing, and why your proposed change would be necessary (or even helpful). There is a very high bar for MPD to implement a new proprietary tag which is not standardized or even implemented anywhere.
