### ISSUE TITLE
rAudio +Re6: no audio from embedded DAC on Raspberry PI 3B+

### ISSUE THREAD

**Issue by diego-biz** [MusicPlayerDaemon/MPD#1522]
Hello. After a clean installation of RuneAudio +R e6 I was unable to have audio from the embedded DAC of the RaspBerry Pi 3B+ (3.5mm jack outputs).
I came from an old release (+R e3) where I use the same board connected to an audio amplifier: we use the RuneAudio as a JukeBox in our office where each colleague could select its prefered song so we don't need an excellent audio quality.
Last day I upgrade the SW to +Re6, select RPi-DAC as I2S dac (as in +Re3) but audio didn't work. I try to enabkle the resampler, the DSP but nothing works.

Anyone can help me?

The status of the running softwares is providing me with those errors.

May 02 14:32:49 TEMIS systemd[1]: Starting Music Player Daemon...
May 02 14:32:50 TEMIS taskset[10653]: decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
May 02 14:32:50 TEMIS systemd[1]: Started Music Player Daemon.
May 02 14:32:53 TEMIS taskset[10653]: alsa_output: Decoder is too slow; playing silence to avoid xrun
May 02 14:33:02 TEMIS taskset[10653]: alsa_output: Decoder is too slow; playing silence to avoid xrun
May 02 14:33:27 TEMIS taskset[10653]: alsa_output: Decoder is too slow; playing silence to avoid xrun

**Comment by MaxKellermann** [comment]
You decided to delete the bug reporting template and decided not to post the information requested there. Therefore I decide to close this issue.
