### ISSUE TITLE
Network streams

### ISSUE THREAD

**Issue by alxchk** [MusicPlayerDaemon/MPD#1523]
It's impossible to listen something long, like podcast.
In case stream interrupted, mpd jumps immediately to next item in playlist, without retry to reestablish connection and continue from last position.

> exception: CURL failed: transfer closed with 117971143 bytes remaining to read
> player: played "http://cdn. .....

**Comment by MaxKellermann** [comment]
You chose to refuse to post the information asked from you, so I choose to close your issue.

**Comment by alxchk** [comment]
Your project, your rules. In case you need some meaningless details for this case, they are here -> https://github.com/MusicPlayerDaemon/MPD/issues/1524.
