### ISSUE TITLE
Input "curl" - large media file is not played to the end

### ISSUE THREAD

**Issue by alxchk** [MusicPlayerDaemon/MPD#1524]
### Describe the bug

MusicPD can not finish playing of CDN hosted media file.
For example this one: http://cdn.radio-t.com/rt_podcast804.mp3#SongDetails=%7B%22album%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%22%2C%22artist%22%3A%22Podcasts%22%2C%22imgcache%22%3A%22%2Fhome%2Favatar%2F.local%2Fshare%2Fcantata%2Fpodcasts%2Feedd4e3c78f945cfe060c21d2f8078bc.jpg%22%2C%22imgurl%22%3A%22https%3A%2F%2Fradio-t.com%2Fimages%2Fcover.jpg%22%2C%22service%22%3A%22podcasts%22%2C%22title%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%20804%22%7D

## Expected Behavior

Large media file hosted at CDN played from the beginning to the end.

## Actual Behavior

1. There is large media file, hosted at CDN
2. MusicPD plays this media file as http stream
3. For some unknown reason playing this stream interrupted somewhere at beginning
4. There is error in log:  "exception: CURL failed: transfer closed with 117971143 bytes remaining to read" (Number may be different)
5. MusicPD switches to next item in playlist

## Version

Music Player Daemon 0.23.6 (0.23.6)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple upnp

Storage plugins:
 local smbclient udisks curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa pipewire pulse httpd

Encoder plugins:
 null vorbis opus wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file io_uring archive alsa curl ffmpeg smbclient

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log

> exception: CURL failed: transfer closed with 117971143 bytes remaining to read
> player: played "http://cdn.radio-t.com/rt_podcast804.mp3#SongDetails=%7B%22album%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%22%2C%22artist%22%3A%22Podcasts%22%2C%22imgcache%22%3A%22%2Fhome%2Favatar%2F.local%2Fshare%2Fcantata%2Fpodcasts%2Feedd4e3c78f945cfe060c21d2f8078bc.jpg%22%2C%22imgurl%22%3A%22https%3A%2F%2Fradio-t.com%2Fimages%2Fcover.jpg%22%2C%22service%22%3A%22podcasts%22%2C%22title%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%20804%22%7D"

In case build without curl (with ffmpeg):

## Log

ffmpeg/http: Stream ends prematurely at 13605408, should be 139888959
exception: avio_read() failed: Input/output error
ffmpeg/mp3float: Could not update timestamps for skipped samples.
player: played "http://cdn.radio-t.com/rt_podcast804.mp3#SongDetails=%7B%22album%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%22%2C%22artist%22%3A%22Podcasts%22%2C%22imgcache%22%3A%22%2Fhome%2Favatar%2F.local%2Fshare%2Fcantata%2Fpodcasts%2Feedd4e3c78f945cfe060c21d2f8078bc.jpg%22%2C%22imgurl%22%3A%22https%3A%2F%2Fradio-t.com%2Fimages%2Fcover.jpg%22%2C%22service%22%3A%22podcasts%22%2C%22title%22%3A%22%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE-%D0%A2%20804%22%7D"

**Comment by MaxKellermann** [comment]
The error means that the web server has closed the connection. I don't know how else MPD should deal with such a server-side problem, and you did not describe a solution, so you better fix the web server.

**Comment by alxchk** [comment]
> The error means that the web server has closed the connection. I don't know how else MPD should deal with such a server-side problem, and you did not describe a solution, so you better fix the web server.

Well, mpv works fine. Continuing from the broken position - this is what expected in this situation. Http Range exists especially for that.

**Comment by GK-774** [comment]
url defaults to not reconnect (retry) on a closed connection. According to the documentation MPD does honor the entries in .curlrc.
So, a /var/lib/mpd/.curlrc (or whatever the home directory of mpd is on your setup - if you start it as your id it would be your home directory) with (for example) these entries could help:

retry-delay 1
retry 3

This should try three times to reconnect at 1s intervals, if MPD really reads .curlrc that is. (Not tested).
