### ISSUE TITLE
Mpd crashing while trying to update the database

### ISSUE THREAD

**Issue by raaffaaeell** [MusicPlayerDaemon/MPD#1528]
### Describe the bug
Tried to update the database with no special things new, it just crashes

## Expected Behavior
Should update the database

## Version
Music Player Daemon 0.23.6 (0.23.6)

## Log
mai 09 00:15:28 fedora systemd-coredump[28769]: [🡕] Process 28761 (mpd) of user 1000 dumped core.
                                                
                                                Module linux-vdso.so.1 with build-id 1d7bc1d93a215fed11d8c29db03835197ef89d44
                                                Module libspa-journal.so with build-id 283d4c0a2d8057fbfb9cdaf3354b5bbec5721131
                                                Metadata for module libspa-journal.so owned by FDO found: {
                                                        "type" : "rpm",
                                                        "name" : "pipewire",
                                                        "version" : "0.3.51-1.fc36",
                                                        "architecture" : "x86_64",
                                                        "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                                }
                                                
                                                Module libspa-support.so with build-id ffba1904817cbc6782cea99defb94eebfe2d046b
                                                Metadata for module libspa-support.so owned by FDO found: {
                                                        "type" : "rpm",
                                                        "name" : "pipewire",
                                                        "version" : "0.3.51-1.fc36",
                                                        "architecture" : "x86_64",
                                                        "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                                }
                                                
                                                Module libjbig.so.2.1 with build-id 208c20ec20c71e7cce019a94027f0c811f89fdba
                                                Metadata for module libjbig.so.2.1 owned by FDO found: {
                                                        "type" : "rpm",
                                                        "name" : "jbigkit",
                                                        "version" : "2.1-23.fc36",
                                                        "architecture" : "x86_64",
                                                        "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                                }
                                                
                                                Module libdatrie.so.1 with build-id 768a842bc0741478ded11a6209b709b6ff6ea43f
                                                Stack trace of thread 28767:
                                                #0  0x00007f57804eaaec __pthread_kill_implementation (libc.so.6 + 0x92aec)
                                                #1  0x00007f578049a9c6 raise (libc.so.6 + 0x429c6)
                                                #2  0x00007f578048482f abort (libc.so.6 + 0x2c82f)
                                                #3  0x00007f5780830e60 _ZSt21__glibcxx_assert_failPKciS0_S0_ (libstdc++.so.6 + 0xd7e60)
                                                #4  0x00005589aff92c5f _ZN18Iso9660InputStream4ReadERSt11unique_lockISt5mutexEPvm (mpd + 0x126c5f)
                                                #5  0x00005589aff201e5 _ZN11InputStream8LockReadEPvm (mpd + 0xb41e5)
                                                #6  0x00005589aff91bc6 _ZN17InputStreamReader4ReadEPvm (mpd + 0x125bc6)
                                                #7  0x00005589aff9e528 _ZN12OggSyncState4FeedEm.constprop.0 (mpd + 0x132528)
                                                #8  0x00005589aff5d280 _ZN12OggSyncState10ExpectPageER8ogg_page (mpd + 0xf1280)
                                                #9  0x00005589aff4e5a6 _ZN12_GLOBAL__N_1L20mpd_opus_scan_streamER11InputStreamR10TagHandler.lto_priv.0 (mpd + >
                                                #10 0x00005589afeeb2ae _Z15tag_stream_scanR11InputStreamR10TagHandler (mpd + 0x7f2ae)
                                                #11 0x00005589afeeb45e _Z15tag_stream_scanR11InputStreamR10TagBuilderP11AudioFormat (mpd + 0x7f45e)
                                                #12 0x00005589afeeb9e4 _ZN4Song19UpdateFileInArchiveER11ArchiveFile (mpd + 0x7f9e4)
                                                #13 0x00005589afef4d4e _ZN10UpdateWalk17UpdateArchiveTreeER11ArchiveFileR9DirectoryPKc (mpd + 0x88d4e)
                                                #14 0x00005589aff9c36c _ZN18Iso9660ArchiveFile5VisitEPcmmR14ArchiveVisitor.constprop.0 (mpd + 0x13036c)
                                                #15 0x00005589aff9c420 _ZN18Iso9660ArchiveFile5VisitEPcmmR14ArchiveVisitor.constprop.0 (mpd + 0x130420)
                                                #16 0x00005589aff9296e _ZN18Iso9660ArchiveFile5VisitER14ArchiveVisitor (mpd + 0x12696e)
                                                #17 0x00005589aff6b215 _ZN10UpdateWalk20UpdateDirectoryChildER9DirectoryRK11ExcludeListPKcRK15StorageFileInfo >
                                                #18 0x00005589aff6cf25 _ZN10UpdateWalk15UpdateDirectoryER9DirectoryRK11ExcludeListRK15StorageFileInfo (mpd + 0>
                                                #19 0x00005589aff6af6d _ZN10UpdateWalk20UpdateDirectoryChildER9DirectoryRK11ExcludeListPKcRK15StorageFileInfo >
                                                #20 0x00005589aff6cf25 _ZN10UpdateWalk15UpdateDirectoryER9DirectoryRK11ExcludeListRK15StorageFileInfo (mpd + 0>
                                                #21 0x00005589aff679d4 _ZN13UpdateService4TaskEv (mpd + 0xfb9d4)
                                                #22 0x00005589aff004e7 _ZN6Thread10ThreadProcEPv (mpd + 0x944e7)
                                                #23 0x00007f57804e8cc7 start_thread (libc.so.6 + 0x90cc7)
                                                #24 0x00007f578056de00 __clone3 (libc.so.6 + 0x115e00)
                                                
                                                Stack trace of thread 28761:
                                                #0  0x00007f578056d3de epoll_wait (libc.so.6 + 0x1153de)
                                                #1  0x00005589aff039e1 _ZN9EventLoop3RunEv (mpd + 0x979e1)
                                                #2  0x00005589afec4018 _ZL14MainConfiguredRK18CommandLineOptionsRK10ConfigData (mpd + 0x58018)
                                                #3  0x00005589afec51dc _ZL11MainOrThrowiPPc (mpd + 0x591dc)
                                                #4  0x00005589afebcc9e main (mpd + 0x50c9e)
                                                #5  0x00007f5780485590 __libc_start_call_main (libc.so.6 + 0x2d590)
                                                #6  0x00007f5780485649 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d649)
                                                #7  0x00005589afebcfc5 _start (mpd + 0x50fc5)
                                                
                                                Stack trace of thread 28762:
                                                #0  0x00007f578056d3de epoll_wait (libc.so.6 + 0x1153de)
                                                #1  0x00005589aff039e1 _ZN9EventLoop3RunEv (mpd + 0x979e1)
                                                #2  0x00005589aff004e7 _ZN6Thread10ThreadProcEPv (mpd + 0x944e7)
                                                #3  0x00007f57804e8cc7 start_thread (libc.so.6 + 0x90cc7)
                                                #4  0x00007f578056de00 __clone3 (libc.so.6 + 0x115e00)
                                                
                                                Stack trace of thread 28763:
                                                #0  0x00007f578056d3de epoll_wait (libc.so.6 + 0x1153de)
                                                #1  0x00005589aff039e1 _ZN9EventLoop3RunEv (mpd + 0x979e1)
                                                #2  0x00005589aff004e7 _ZN6Thread10ThreadProcEPv (mpd + 0x944e7)
                                                #3  0x00007f57804e8cc7 start_thread (libc.so.6 + 0x90cc7)
                                                #4  0x00007f578056de00 __clone3 (libc.so.6 + 0x115e00)
                                                ELF object binary architecture: AMD x86-64
mai 09 00:15:28 fedora systemd[2100]: mpd.service: Main process exited, code=dumped, status=6/ABRT
mai 09 00:15:28 fedora systemd[2100]: mpd.service: Failed with result 'core-dump'.

**Comment by MaxKellermann** [comment]
Assertion message is missing in your log output.
Can you upload the faulty ISO file, so I can reproduce the bug?

**Comment by raaffaaeell** [comment]
Wow, it was indeed the ISO file. I'm sorry for the late response. It happened because I run mpd on a Downloads folder and sometimes it'll have some non music files.

The ISO file is rather big (8gb), but if you think it's worth it for you, I can try a link
