### ISSUE TITLE
is it possible to use a single `.mpdignore` in root directory?

### ISSUE THREAD

**Issue by othmar52** [MusicPlayerDaemon/MPD#1532]
## Question
I am struggling to figure out the correct "syntax" for mpd ignore patterns   
lets asssume we have a filesystem like this:  
```
musicroot/
├── drum & bass
│   ├── artist 1
│   │   ├── album 1
│   │   │   ├── .mpdignore
│   │   │   └── song 1.mp3
│   │   └── album 11
│   │       ├── .mpdignore
│   │       └── song 1.mp3
│   └── artist 2
│       └── album 1
│           └── song 1.mp3
├── hip hop
│   └── artist 1
│       ├── album 1
│       │   └── song 1.mp3
│       └── album 11
│           └── song 1.mp3
└── .mpdignore
```

### how can i add `drum & bass/artist 1/album 1/` to my `musicroot/.mpdignore`?  

creating `drum & bass/artist 1/album 1/.mpdignore` with content `*` works perfectly but i prefer to specify all ignored directories in a single `musicroot/.mpdignore`   

adding `**album 1**` to my `musicroot/.mpdignore` removes everything from the mpd database  
```
 update: removing musicroot/drum & bass/artist 1/album 1/song 1.mp3
 update: removing musicroot/drum & bass/artist 1/album 11/song 1.mp3
 update: removing musicroot/drum & bass/artist 2/album 1/song 1.mp3
 update: removing musicroot/hip hop/artist 1/album 1/song 1.mp3
 update: removing musicroot/hip hop/artist 1/album 11/song 1.mp3
```

adding `**drum & bass/artist 1/album 1/**` to my `musicroot/.mpdignore` does not work. (i also tried to escape slashes, whitespaces, etc. without success)   

it would be great to have a few examples in the [documentation](https://mpd.readthedocs.io/en/stable/user.html?highlight=mpdignore#the-music-directory-and-the-database) for noobs like me.  
Thanks in advance for any help!

**Comment by MaxKellermann** [comment]
The patterns in `.mpdignore` match on file or directory names, but not on nested path names.
