### ISSUE TITLE
exception handling: shouldn't partly updates be persisted?

### ISSUE THREAD

**Issue by othmar52** [MusicPlayerDaemon/MPD#1533]
## Question
im am wondering if this behaviour is correct or if this should be improved:

during database update i get `May 17 13:13 : exception: Read failed: Input/output error`  
due to a huge harddisk it always takes a few hours until i get to such occurrences.  
there is no hint to a path in filesystem where this error occurs  
i can only guess the parent directory when i look to the line above (`May 17 13:13 : update: added <some-path>`) 
the import seems to stop immediatly on this exception without persisting what's already successfully read from filesystem  
one hour after this exception mpd still claims that it is currently updating (which seems to be not true)  

i have to admit that it's really an edge case to have I/O errors but is this the correct/intended behaviour?  
its pretty tedious to start from zero over and over again without having persisted several hours of scanning music files

**Comment by MaxKellermann** [comment]
I don't understand the question.

**Comment by othmar52** [comment]
Thank you for your fast reply!  
i would expect to have several hours of scanning music files persisted in the mpd database.  
but if there is an I/O error during update nothing gets persisted in the database.  
is this the correct/intended behaviour?

**Comment by othmar52** [comment]
the update seems to stop on this exception (even if mpd claims to be still updating).  
and from my point of view it is some kind of "finished" because there is no further progress to be expected.

**Comment by MaxKellermann** [comment]
I don't know where to go from here with your question. Your question did not make sense in the context, because it implied something that was not true, therefore I cannot answer your question in a meaningful way. If you need further help, you need to be more specific about what kind of help you need.
