### ISSUE TITLE
exception: Unsupported URI scheme

### ISSUE THREAD

**Issue by emmatebibyte** [MusicPlayerDaemon/MPD#1560]
### Describe the bug
mpd crashes upon pressing play in Cantata

## Expected Behavior
mpd does not crash

## Actual Behavior
see above

## Version

Music Player Daemon 0.23.7 (0.23.7)

## Configuration

```
music_directory		"~/Music"
playlist_directory		"~/.config/mpd/playlists"
db_file			"~/.config/mpd/database"
log_file			"~/.config/mpd/log"
pid_file			"~/.config/mpd/pid"
state_file			"~/.config/mpd/state"
sticker_file			"~/.config/mpd/sticker.sql"
user				"emma"
bind_to_address		"any"
bind_to_address		"~/.config/mpd/socket"
port				"6600"
log_level			"notice"
restore_paused "yes"
save_absolute_paths_in_playlists	"yes"
metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update	"yes"
input {
        plugin "curl"
}
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
audio_output {
	type		"httpd"
	name		"Emma's MPD Stream"
	encoder		"vorbis"		# optional, vorbis or lame
	port		"8000"
	bitrate		"320"			# do not define if quality is defined
	format		"44100:16:2"
	max_clients	"0"			# optional 0=no limit
}
replaygain			"auto"
replaygain_limit		"yes"
volume_normalization		"no"
filesystem_charset		"UTF-8"
```

## Log

```
Jul 03 18:13 : client: [3] process command "lsinfo "mpd-client://cantata/2.5.0""
Jul 03 18:13 : exception: Unsupported URI scheme
```

**Comment by MaxKellermann** [comment]
You wrote "mpd crashes", but your log shows no crash at all. It shows that MPD replies to an invalid command with an error message, which is perfectly valid behavior.
The URI scheme passed to the "lsinfo" command is "mpd-client://", but what kind of URI scheme is that? MPD doesn't support that, and that is what MPD tells you.
This bug report is bogus (or incomplete).

**Comment by emmatebibyte** [comment]
it reports a segfault when I run it in a terminal with --no-daemon, and it just started last night, despite never occurring before—I had not changed any settings in my client nor my server, and no updates had occurred for either.

**Comment by MaxKellermann** [comment]
Your bug report does not mention any segfault, and it does not contain a backtrace. See https://www.musicpd.org/help/ (You were asked to read this link when you reported this bug, but apparently you didn't.)
