### ISSUE TITLE
exception: OutputThread could not get realtime scheduling

### ISSUE THREAD

**Issue by simistef** [MusicPlayerDaemon/MPD#1565]
Hi there,

I am running MPD 0.20.23-1 on Synology DS218+ NAS. Managed to configure it and run it via icecast2 as well. I installed Parsephone controller and can see and control music. 
BUT
I cannot hear anything neither on Parsephone nor Icecast stream.

The only error i get in the logs is the following: 

`exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted `

Can anyone help me please ?

**Comment by MaxKellermann** [comment]
It's all documented: https://mpd.readthedocs.io/en/stable/user.html#real-time-scheduling

**Comment by simistef** [comment]
Thanks, but unclear to me if this is stopping the audio being heard or not.

**Comment by MaxKellermann** [comment]
You chose not to post the information I asked from you, so everything is unclear to me.
