### ISSUE TITLE
Compile error on mac mini M1

### ISSUE THREAD

**Issue by dhocker** [MusicPlayerDaemon/MPD#1569]
### Describe the bug
[369/590] Compiling C++ object src/io/libio.a.p/FileOutputStream.cxx.o
FAILED: src/io/libio.a.p/FileOutputStream.cxx.o 
c++ -Isrc/io/libio.a.p -Isrc/io -I../../src/io -Isrc -I../../src -I. -I../.. -I/opt/homebrew/Cellar/fmt/8.1.1_1/include -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++2a -O2 -g -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wunreachable-code-aggressive -Wused-but-marked-unused -fno-threadsafe-statics -fmerge-all-constants -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wno-non-virtual-dtor -Wcomma -Wheader-hygiene -Winconsistent-missing-destructor-override -Wsuggest-override -fvisibility=hidden -ffunction-sections -fdata-sections -D_GNU_SOURCE -MD -MQ src/io/libio.a.p/FileOutputStream.cxx.o -MF src/io/libio.a.p/FileOutputStream.cxx.o.d -o src/io/libio.a.p/FileOutputStream.cxx.o -c ../../src/io/FileOutputStream.cxx
../../src/io/FileOutputStream.cxx:255:6: error: use of undeclared identifier 'fdatasync'
        if (fdatasync(fd.Get()) < 0)
            ^
1 error generated.
[378/590] Compiling C++ object src/io/libio.a.p/BufferedOutputStream.cxx.o
ninja: build stopped: subcommand failed.

It appears that commit 270a74e53bd536b019a7afcf71feaa672fcf6d81 introduced the function Sync() into FileOutputStream.cxx. The non-WIN32 version of the new function calls fdatasync() which is typically defined in unistd.h. However, fdatasync is not defined in the macos version of unistd.h and does not appear to exist under macos. An Internet search indicates that others have encountered this problem. Under macos you might be limited to using fsync() instead of fdatasync(). See [Apple doc](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html).

## Expected Behavior
Clean build.

## Actual Behavior
Build fails with compile error

## Version

Repo at commit 2670bbdcc870ab228b1d5d8e4c128406c1f956e4

**Comment by MaxKellermann** [comment]
150e8f78bf78213a7ebaed38e96ebcf2d2a7bfed
