### ISSUE TITLE
cannot open mpd.conf on android after 0.23.8 update

### ISSUE THREAD

**Issue by lschierer** [MusicPlayerDaemon/MPD#1570]
### Describe the bug
since the update to mpd on android to 0.23.8 when I go to start mpd, it says 
```
exception: Failed to open '/storage/emulated/0/mpd.conf': Permission denied
```

## Expected Behavior
mpd continues to start as normal

## Actual Behavior
prints an error message in the console log and fails to allow connections

## Version
0.23.8 per google play store. 

## Configuration
it cannot open the configuration file, so I doubt this is relevant.

**Comment by MaxKellermann** [comment]
See https://github.com/MusicPlayerDaemon/MPD/issues/1061#issuecomment-1185664551=
It's no longer possible to grant an app permission to all files.

**Comment by MaxKellermann** [comment]
I've marked this as bug, not because it's a MPD bug (it's an Android design decision); but MPD needs to use an app-specific directory for its configuration file.

**Comment by roizcorp** [comment]
OR perhaps provide a text box in the app to paste the content of mpd.conf (then later generate it as a file anywhere you like and android permits)

**Comment by drew1kun** [comment]
Is there any way to provide mpd.conf to the app on Android 14? (installed the last Version 0.23.14 (72) from [FDroid](https://f-droid.org/en/packages/org.musicpd/#:~:text=Music%20Player%20Daemon%20(MPD)%20is,controlled%20by%20its%20network%20protocol.) but cannot find where to put the config file). Could you please suggest?
