### ISSUE TITLE
Can not play music to http output

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#1573]
### Describe the bug
Can not play music to http port of MPD any longer.

## Expected Behavior
Connect with clients eg. VLC, Firefox (no supported mime type) or Sonos (connect but does not show metadata or plays music) to MPD. Worked a few weeks ago no change in configuration.

## Actual Behavior
No sound on http clients.

## Version

Music Player Daemon 0.24 (v0.23.8-334-g0c98d93e9)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [sidplay] sid mus str prg P00
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo pipe alsa httpd snapcast

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus epoll icu inotify ipv6 systemd tcp un

## Configuration

music_directory                 "/storage01/music"
playlist_directory              "/storage01/playlists"
log_file                        "/var/log/mpd/mpd.log"
pid_file                        "/run/mpd/pid"
state_file                      "/var/lib/mpd/state"
user                            "mpd"
bind_to_address                 "any"
bind_to_address                 "/run/mpd/socket"
log_level                       "verbose"
auto_update                     "no"
zeroconf_enabled                "yes"
zeroconf_name                   "Music Player Daemon @ %h"
database {
        plugin                  "simple"
        path                    "/var/lib/mpd/tag_cache"
        compress                "no"
}
audio_output {
        type            "httpd"
        tags            "yes"
        name            "httpd on port 8000"
        always_on       "yes"
        encoder         "lame"
        port            "8000"
        bind_to_address "0.0.0.0"
        bitrate         "320"
        format          "44100:16:2"
        max_clients     "0"
}
audio_output {
       type            "null"
       name            "Null"
       mixer_type      "none"
}
filesystem_charset              "UTF-8"
decoder {
        plugin                  "sidplay"
        songlength_database     "/var/lib/mpd/Songlengths.md5"
        default_genre           "SID"
        kernal                  "/var/lib/mpd/kernal"
        basic                   "/var/lib/mpd/basic"
        filter                  "true"
}
decoder {
        plugin                  "mad"
        enabled                 "yes"
}
decoder {
        plugin                  "mpg123"
        enabled                 "yes"
}
decoder {
        plugin                  "ffmpeg"
        enabled                 "yes"
}
decoder {
        plugin                  "mpcdec"
        enabled                 "yes"
}
audio_output {
        type                    "alsa"
        name                    "Lexicon Omega"
        device                  "hw:Omega"
        mixer_type              "software"
        format                  "*:*:2"
}
audio_output {
        type                    "alsa"
        name                    "U-Control UCA202"
        device                  "hw:CARD=CODEC,DEV=0"
        mixer_type              "hardware"
        format                  "*:16:2"
        mixer_device            "hw:CODEC"
        mixer_control           "PCM"
}
audio_output {
        type                    "alsa"
        name                    "U-Phoria UMC202HD"
        device                  "hw:CARD=U192k,DEV=0"
        mixer_type              "hardware"
        format                  "44100:24:2"
        mixer_device            "hw:U192k"
        mixer_control           "UMC202HD 192k Output"
}
audio_output {
        type                    "alsa"
        name                    "Intel HDA, ALC662"
        device                  "hw:CARD=Intel,DEV=0"
        mixer_type              "hardware"
        mixer_device            "hw:Intel"
        mixer_control           "Master"
}
decoder {
        plugin                  "dsdiff"
        enabled                 "no"
}
decoder {
        plugin                  "dsf"
        enabled                 "no"
}
decoder {
        plugin                  "fluidsynth"
        enabled                 "no"
}
decoder {
        plugin                  "mikmod"
        enabled                 "no"
}
decoder {
        plugin                  "modplug"
        enabled                 "no"
}
decoder {
        plugin                  "wildmidi"
        enabled                 "no"
}
resampler {
        plugin                  "libsamplerate"
        type                    "Medium Sinc Interpolator"
}
max_output_buffer_size          "65536"

## Log

# mpd --verbose --no-daemon --stderr
config_file: loading file /etc/mpd.conf
server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is
libsamplerate: libsamplerate converter 'Medium Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.31
simple_db: reading DB
curl: version 7.84.0
curl: with GnuTLS/3.7.6
event: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
state_file: Loading state file /var/lib/mpd/state
playlist: queue song 1:"sampler/Tour de Traum/Tour de Traum - XXII/24 - We Need Cracks - Signals.mp3"
output: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
decoder_thread: probing plugin mad
mad: detected LAME version 3.99 ("LAME3.99r")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 1698
decoder: audio_format=44100:24:2, seekable=true
output: opened "httpd on port 8000" (httpd) audio_format=44100:16:2
output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:16:2
client: [0] opened from local
client: [0] process command list
client: process command "tagtypes "all""
client: command returned 0
client: process command "tagtypes"
client: command returned 0
client: [0] process command list returned 0
client: [0] process command list
client: process command "tagtypes "clear""
client: command returned 0
client: process command "tagtypes enable Artist Album AlbumArtist Title Track Name Genre Date Composer Performer Disc Work Conductor"
client: command returned 0
client: [0] process command list returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "listpartitions"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
(...)

state_file: Saving state file /var/lib/mpd/state
player: played "sampler/Tour de Traum/Tour de Traum - XXII/23 - UCCELLI - Front Door.mp3"
output: closed "httpd on port 8000" (httpd)

**Comment by skidoo23** [comment]
Duplicate of #1585

**Comment by MaxKellermann** [comment]
2afe427ab382b18135d57c5a1414d6d6a3eaa1a2
