### ISSUE TITLE
AAC streams stops playing after short time

### ISSUE THREAD

**Issue by darxmurf** [MusicPlayerDaemon/MPD#1595]
### Describe the bug
I have a couple of online radios configured in my MPD but all the aac streams stops playing after a random time between 10 sec and 2 minutes. It simply stops without any errors in logs or anything, even if I enable verbose mode. Everything is fine if I use MP3 streams from the same radios.

Examples
http://stream.srg-ssr.ch/m/option-musique/aacp_96 (stops after 30 sec)
http://stream.srg-ssr.ch/m/option-musique/mp3_128 is working fine

This MPD is running on an "old" Asus Tinker Board running Debian 10, unfortunately I can't update to newer version.

## Expected Behavior
Should not stop

## Actual Behavior
Playback stops after a random period of time between 30 sec and 2 min

## Version
Music Player Daemon 0.21.5 (0.21.5)

Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration
music_directory         "/Music/"
#
playlist_directory              "/configs/mpd/playlists"
#
db_file                 "/var/lib/mpd/tag_cache"
#
log_file                        "/var/log/mpd/mpd.log"
#
pid_file                        "/run/mpd/pid"
#
state_file                      "/var/lib/mpd/state"
#
sticker_file                   "/var/lib/mpd/sticker.sql"
#
user                            "mpd"
#
bind_to_address         "localhost"
bind_to_address         "192.168.1.101"
#
port                            "6600"
#
log_level                       "default"
#
# This setting defines a list of tag types that will be extracted during the
# audio file discovery process. The complete list of possible values can be
# found in the mpd.conf man page.
#metadata_to_use        "artist,album,title,track,name,genre,date,composer,performer,disc"
#
auto_update    "no"
#
zeroconf_enabled                "no"
#

# Input #######################################################################
input {
        plugin "curl"
}

#

# Audio Output ################################################################
audio_output {
        type            "alsa"
        name            "Default-Output"
        device          "hw:0,2"        # optional
        mixer_type      "software"      # optional
}
#
#
filesystem_charset              "UTF-8"
#
id3v1_encoding                  "UTF-8"

## Log
nothing special here

**Comment by MaxKellermann** [comment]
Your MPD version is very old and unsupported.

**Comment by darxmurf** [comment]
Sorry I'm back after a few tests.

I could compile version 0.23.9 and the problem remains.
This time I have some lines in the logs

`Oct 02 21:47 : alsa_output: Decoder is too slow; playing silence to avoid xrun`

I have no issues with RadioParadise stream but this one is cut quite quickly: https://radiovostok.ice.infomaniak.ch/radiovostok.aac
For information, I'm running MPD on an Asus TinkerBoard connected by WIFI.

Thanks in advance for your help
