### ISSUE TITLE
Keep ALSA device open at all times

### ISSUE THREAD

**Issue by Cleric-K** [MusicPlayerDaemon/MPD#1599]
## Feature request
Currently I'm using a NanoPi Neo2 with its internal DAC. There's a slight problem unrelated to MPD itself since it is present with any player, so it seems it's something to do with the driver layer. Anyway, the behavior is as follows:

1. If the player hasn't been playing for a while then when a track is started the first second or so is cut off. If I press stop and then quickly play again from the beginning it starts without chopping off.

2. If I stop and leave it for few seconds, a specific popping/clicking sound is heard (the same for every player, not only MPD). If I try to play after this sound has been heard, the initial cut off is present again.

I'm not familiar with the Linux sound subsystem bit it seems that the clicking sound happens when the audio device is _closed_.  If I keep playing and changing tracks without letting it stay stopped for more than few seconds, everything is fine.

So my thought is: is it possible to make MPD never close the audio device and instead, while stopped, to continue play silence as it were? If I'm correct about the underlying problem this should prevent the pop/click sound ever occurring and thus starting tracks after some time should run without cutting off. Maybe some configuration option like `keep_audio_output_open` or something like that.

**Comment by Cleric-K** [comment]
Thank you, unfortunately this option seems not to have any effect.

The config is:
```
audio_output {
        type            "alsa"
        name            "My ALSA Device"
##      device          "hw:0,0"        # optional
##      mixer_type      "hardware"      # optional
##      mixer_device    "default"       # optional
        mixer_control   "Line Out"      # optional
##      mixer_index     "0"             # optional
        always_on       "yes"
}
```

MPD output is:
```
alsa_output: opened default type=PLUG
alsa_output: buffer: size=64..65536 time=1451..1486078
alsa_output: period: size=32..8192 time=725..185760
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S24_LE (Signed 24 bit Little Endian)
alsa_output: buffer_size=22050 period_size=7350
output: opened "My ALSA Device" (alsa) audio_format=44100:24:2
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistid "4""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "pause 1"
client: [0] command returned 0
output: closed "My ALSA Device" (alsa)
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistid "4""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
```

It still closes the output.

MPD version is `Music Player Daemon 0.22.6 (0.22.6)`.

It seems the `always_on` option is recognized because if I deliberately misspell it, I get option not recognized error. Am I missing something else?

**Comment by Cleric-K** [comment]
Upon some digging I see that the Alsa method
```c++
bool
AlsaOutput::Pause() noexcept
{
	std::unique_lock<Mutex> lock(mutex);
	interrupted = false;

	/* not implemented - this override exists only to reset the
	   "interrupted" flag */
	return false;
}
```
is not implemented and thus inside `AudioOutputControl::InternalPause()` it falls back to closing.
```c++
success = output->IteratePause();

...

if (!success) {
	InternalClose(false);
	break;
}
```

Does this mean that the `awalys_on` can't be implemented for Alsa?

**Comment by Cleric-K** [comment]
A made a simple change to the source code:

https://github.com/MusicPlayerDaemon/MPD/blob/c14484a5cc7f8775fc7c6dd6d21c04fd84ee3104/src/output/plugins/AlsaOutputPlugin.cxx#L1152-L1161

changing the return value from `false` to `true`. I'm using MPD for few weeks now and it works flawlessly, the Alsa device stays open all the time so now clicking sounds and delays anymore.

Is there any special reason why the method is marked as 'not implemented', while it seems that everything works quite well only by returning `true`?

**Comment by mth** [comment]
I'm using a workaround with ALSA dmix plugin and following systemd service:

```
[Service]
ExecStart=/usr/bin/aplay -t raw -f dat /var/lib/mpd/keep-alsa-open
ExecStop=/usr/bin/dd if=/dev/zero of=/var/lib/mpd/keep-alsa-open bs=4 count=1

```
The /var/lib/mpd/keep-alsa-open is a pipe created with mkfifo, so aplay blocks on it until ExecStop write, keeping the kernel sound device open and avoiding clicking noise.

**Comment by Cleric-K** [comment]
@mth That's an interesting solution.

Actually I solved the problem by implementing the pause capability of the Alsa plugin:

```diff
diff --git a/src/output/plugins/AlsaOutputPlugin.cxx b/src/output/plugins/AlsaOutputPlugin.cxx
index 19e57b4dd..a9fe830ea 100644
--- a/src/output/plugins/AlsaOutputPlugin.cxx
+++ b/src/output/plugins/AlsaOutputPlugin.cxx
@@ -220,6 +220,8 @@ class AlsaOutput final
 	 */
 	bool interrupted;
 
+	bool paused;
+
 	/**
 	 * This buffer gets allocated after opening the ALSA device.
 	 * It contains silence samples, enough to fill one period (see
@@ -289,6 +291,9 @@ private:
 	void Drain() override;
 	void Cancel() noexcept override;
 	bool Pause() noexcept override;
+	std::chrono::steady_clock::duration Delay() const noexcept override {
+		return paused ? std::chrono::milliseconds(500) : std::chrono::steady_clock::duration::zero();
+	}
 
 	/**
 	 * Set up the snd_pcm_t object which was opened by the caller.
@@ -437,7 +442,7 @@ GetAlsaOpenMode(const ConfigBlock &block)
 }
 
 AlsaOutput::AlsaOutput(EventLoop &_loop, const ConfigBlock &block)
-	:AudioOutput(FLAG_ENABLE_DISABLE),
+	:AudioOutput(FLAG_ENABLE_DISABLE|FLAG_PAUSE),
 	 MultiSocketMonitor(_loop),
 	 defer_invalidate_sockets(_loop, BIND_THIS_METHOD(InvalidateSockets)),
 	 silence_timer(_loop, BIND_THIS_METHOD(OnSilenceTimer)),
@@ -878,6 +883,7 @@ AlsaOutput::Open(AudioFormat &audio_format)
 
 	drain = false;
 	interrupted = false;
+	paused = false;
 
 	size_t period_size = period_frames * out_frame_size;
 	ring_buffer = new boost::lockfree::spsc_queue<uint8_t>(period_size * 4);
@@ -1160,10 +1166,9 @@ AlsaOutput::Pause() noexcept
 {
 	std::unique_lock<Mutex> lock(mutex);
 	interrupted = false;
+	paused = true;
 
-	/* not implemented - this override exists only to reset the
-	   "interrupted" flag */
-	return false;
+	return true;
 }
 
 void
@@ -1231,6 +1236,8 @@ AlsaOutput::Play(const void *chunk, size_t size)
 	assert(size > 0);
 	assert(size % in_frame_size == 0);
 
+	paused = false;
+
 	const size_t max_frames = LockWaitWriteAvailable();
 	const size_t max_size = max_frames * in_frame_size;
 	if (size > max_size) 
```

I haven't submitted a PR because I have no idea if this is sufficient or if it is at all the proper way to do it. It seems to work for me or at least I haven't noticed any side effects so far.

**Comment by mth** [comment]
> I haven't submitted a PR because I have no idea if this is sufficient or if it is at all the proper way to do it.

IMHO easiest way to know that would be submitting a PR. :) It might be likely to be rejected, but the maintainers familiar with MPD code can then give suggestions about problems/fixes.

**Comment by Cleric-K** [comment]
I guess you are right. Maybe I'll push a PR, if nothing else, at least to have it as an archive for anyone wanting to use it as a patch.
