### ISSUE TITLE
Queue does not survive MPD restart

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#162]
git master, made clean, compiled with clang 5.0. did work till 25-November of MPD.

**Comment by mistepien** [comment]
Yes, state files seems to be not read at the mpd's start.

**Comment by mistepien** [comment]
OK, pre-25 november version:
- full playlist
- kill protocol command
- mpd started once again
- full playlist

current mpd-git:
- full playlist 
- kill protocol command
- mpd started once again
- full playlist
