### ISSUE TITLE
(Reopen) "always_on" not working for ALSA devices

### ISSUE THREAD

**Issue by Cleric-K** [MusicPlayerDaemon/MPD#1623]
I'm not sure if #1599 gets attention since it is closed but the `always_on` option currently doesn't work for ALSA. I have described in the [last post](https://github.com/MusicPlayerDaemon/MPD/issues/1599#issuecomment-1247300917) of the issue that simple change in the code makes it work. Is it intended that ALSA doesn't support `always_on`? From my experience everything works perfectly well with the above mentioned code change.

**Comment by GK-774** [comment]
Yes, correct "always_on"does not work, reports as "closed". If this cannot cannot be controlled from within mpd it would preferable to remove the option.

**Comment by Cleric-K** [comment]
Yes, in the way the code is compiled right now it does *not* work. But as explained in the linked issue, by modifying `AlsaOutput::Pause()` to return `true`, everything works great, as far as my tests have gone. So my question is why don't we simply change the return value of the method and make `always_on` work with ALSA? Is there something I'm overlooking? Maybe something that will break down in this way, something that I haven't covered in my tests?

**Comment by GK-774** [comment]
If you simply return "true", always_on       "no" (or having it not defined at all) would not work, it would be "on" in any case, no? Or have I misunderstood this?

**Comment by GK-774** [comment]
Please disregard my last comment. Just tried it and yes, this makes it work as expected.

**Comment by GK-774** [comment]
Well, no. It keeps the output open but consumes 100% cpu when stopped. With always_on "no" it behaves normal. It´s probably not a good idea at all at least not for an USB audio device.

**Comment by Cleric-K** [comment]
Hm, you are right. Since I use the device only for audio player I haven't noticed the high cpu. I'll try to look through the code if I can spot something. Most certainly the high cpu comes from some code that keeps looping as fast as the cpu allows.

**Comment by mth** [comment]
I'm using a workaround with ALSA dmix plugin and following systemd service:

```
[Service]
ExecStart=/usr/bin/aplay -t raw -f dat /var/lib/mpd/keep-alsa-open
ExecStop=/usr/bin/dd if=/dev/zero of=/var/lib/mpd/keep-alsa-open bs=4 count=1

```
The /var/lib/mpd/keep-alsa-open is pipe created with mkfifo, so aplay blocks on it until ExecStop write, keeping the kernel sound device open and avoiding clicking noise.
