### ISSUE TITLE
I need a windows build with shout compiled in it...

### ISSUE THREAD

**Issue by refriedfood** [MusicPlayerDaemon/MPD#1635]
Is this even possible?

**Comment by MaxKellermann** [comment]
That's not a MPD problem, that's a libshout problem. If you can build libshout for Windows, then you can also enable MPD's plugin.

**Comment by refriedfood** [comment]
That's pretty much what I'm asking for?

Much like the title: I need a windows build with shout compiled in it.

The only problem would be the compiled version already on their site, which I've gone through, and they are all missing libshout in their windows builds.

**Comment by MaxKellermann** [comment]
I don't understand your response. You need a Windows build, so go and do a Windows build, you have the source code. You asked if it's possible, and I explained how (implying the answer is "yes").
All of your response confuses me, even the question "That's pretty much what I'm asking for?" - what, is that a serious question? How shall I answer it and how does it help you produce a Windows build with shout suport?

**Comment by refriedfood** [comment]
The question was it possible if you can make a windows build with shout in it, YOU, not me, YOU. And you answered that it isn't mpd's problem, and you can do it if you add it, which doesn't answer the question at all. You're not saying I should build it or how.

I cannot make a windows build of mpd, and need one with shout in it. If I could build it myself I wouldn't even be here--hence my damn question. You said that it's possible to do so, so what is the problem? Why are all the builds on the site missing shout? That's the compiler failing to compile it into it on purpose. Where's the confusion? Is english not your first language?

*Never mind, after reading some of your insulting replies to people wanting help, English definitely isn't your first language. I'm not sure of how else to ask you to compile a version with shout in it. And if you refuse to do it with the releases, remove it from your docs page or have a note saying it isn't in windows builds.

**Comment by MaxKellermann** [comment]
Oh well.
