### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [MusicPlayerDaemon/MPD#1644]
### Describe the bug

```
[603/616] Compiling C++ object libmpd.so.p/src_android_Context.cxx.o
FAILED: libmpd.so.p/src_android_Context.cxx.o 
/opt/android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Ilibmpd.so.p -I. -I../.. -Isrc -I../../src -I../../subprojects/fmt-8.1.1/include -Isubprojects/sqlite-amalgamation-3380000 -I../../subprojects/sqlite-amalgamation-3380000 -Iandroid -I/builds/linsui/fdroiddata/build/org.musicpd/output/android/lib/arm-linux-androideabi/root/include -I/builds/linsui/fdroiddata/build/org.musicpd/output/android/android/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wunreachable-code-aggressive -Wused-but-marked-unused -fno-threadsafe-statics -fmerge-all-constants -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wno-non-virtual-dtor -Wcomma -Wheader-hygiene -Winconsistent-missing-destructor-override -Wsuggest-override -fvisibility=hidden -ffunction-sections -fdata-sections -D_GNU_SOURCE -DANDROID -isystem /builds/linsui/fdroiddata/build/org.musicpd/output/android/lib/arm-linux-androideabi/root/include -Os -g -fpic -mfpu=neon -mfloat-abi=softfp -target armv7-linux-androideabi21 -fvisibility=hidden -fdata-sections -ffunction-sections -fPIC -DBOOST_ALL_NO_LIB -MD -MQ libmpd.so.p/src_android_Context.cxx.o -MF libmpd.so.p/src_android_Context.cxx.o.d -o libmpd.so.p/src_android_Context.cxx.o -c ../../src/android/Context.cxx
../../src/android/Context.cxx:49:9: error: use of undeclared identifier '_type'; did you mean 'type'?
        assert(_type != nullptr);
               ^~~~~
               type
/opt/android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/assert.h:55:23: note: expanded from macro 'assert'
#  define assert(e) ((e) ? __assert_no_op : __assert2(__FILE__, __LINE__, __PRETTY_FUNCTION__, #e))
                      ^
../../src/android/Context.cxx:47:55: note: 'type' declared here
Context::GetExternalFilesDir(JNIEnv *env, const char *type) noexcept
                                                      ^
1 error generated.
[604/616] Compiling C++ object libmpd.so.p/src_PlaylistFile.cxx.o
ninja: build stopped: subcommand failed.
```

https://gitlab.com/linsui/fdroiddata/-/jobs/3160596383

Could you please take a look? Thanks!

**Comment by MaxKellermann** [comment]
This bug is real, but only occurs in debug builds (which have runtime overhead). I recommend not doing debug builds for regular users.

**Comment by linsui** [comment]
We use `python3 ../../android/build.py $$SDK$$ $$NDK$$ armeabi-v7a`. It seems the debug mode is default... Could you share your config for the release apk? The doc uses `--buildtype=debugoptimized` which is also debug mode.

**Comment by MaxKellermann** [comment]
> We use `python3 ../../android/build.py $$SDK$$ $$NDK$$ armeabi-v7a`. It seems the debug mode is default... Could you share your config for the release apk?

It's exactly this one from the docs:
https://github.com/MusicPlayerDaemon/MPD/blob/d6d0f78e93dfd73065d9384f58c486c175383134/doc/user.rst#L217-L219

> The doc uses `--buildtype=debugoptimized` which is also debug mode.

The term "debug build" is indeed confusing. Don't mix up compiler optimizations, debug symbols and debug build (= with runtime assertions = runtime overhead). That's 3 independent aspects of a build.

- `--buildtype=debugoptimized` enables debug symbols while also enabling compiler optimizations
- `-Db_ndebug=true` (note the confusing double negation) disables runtime assertions

Unrelated note: you can do the Android build without `./android/build.py`; all this script does is download & build all the third-party libraries MPD can use, and then invokes `meson`. If your build system happens to already have Android builds of those libraries (or you choose to disable those features), you can invoke `meson` directly.

**Comment by linsui** [comment]
Thanks for your help! I'll use the command in the doc.

> If your build system happens to already have Android builds of those libraries

I thought we don't have them since the buildserver is a clean debian vm.
