### ISSUE TITLE
Cannot play aac or mp3 radio streams in Android v0.23.10

### ISSUE THREAD

**Issue by noelj62** [MusicPlayerDaemon/MPD#1662]
Hello,

It's a problem that I can no longer play aac or mp3 radio streams in version 0.23.10 on Android 6.0.

MPD just throws out an ffmpeg not available error and schedualer problem.

Thank you for this awesome piece of software.

**Comment by MaxKellermann** [comment]
No, you can't just delete the bug reporting template and not answer all the questions. Your cooperation is necessary to be able to help you.
