### ISSUE TITLE
.ape files are showing as playlists

### ISSUE THREAD

**Issue by Emilot** [MusicPlayerDaemon/MPD#1663]
## Bug report
every .ape file in library is handled as playlist

## Expected Behavior
play it like a regular audio file

## Version
Music Player Daemon 0.23.10 (0.23.10)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo pipe alsa httpd snapcast recorder

Encoder plugins:
 null vorbis wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file io_uring archive alsa curl nfs mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// scp:// sftp:// smb://

Other features:
 dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration
follow_outside_symlinks         "yes"
follow_inside_symlinks  "yes"
db_file         "/var/lib/mpd/mpd.db"
#log_file        "/var/log/mpd.log"
#pid_file        "/var/run/mpd/pid"
music_directory         "/var/lib/mpd/music"
playlist_directory      "/var/lib/mpd/playlists"
state_file      "/var/lib/mpd/mpdstate"
sticker_file    "/var/lib/mpd/sticker.sql"
user    "mpd"
bind_to_address     "any"
bind_to_address     "/run/mpd/socket"
port    "6600"
log_level       "verbose"
volume_normalization    "no"
audio_buffer_size       "4096"
filesystem_charset      "UTF-8"
auto_update     "no"
mixer_type "software"
group   "audio"
max_connections "20"
restore_paused "yes"

input_cache {
size "256 MB"
}

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

input {
plugin "io_uring"
}

audio_output {
enabled         "yes"
type            "alsa"
name            "MY DAC"
device          "hw:0,0"
auto_resample   "no"
auto_channels   "no"
auto_format     "no"
dop "no"
stop_dsd_silence "yes"
thesycon_dsd_workaround "yes"
always_on "yes"
}

## Log
Nov 07 18:04 : client: [2] process command "load "nas-samba/Cyndi Lauper - Twelve Deadly Cyns... And Then Some (1994)/(01) [Cyndi Lauper] I'm Gonna Be Strong.ape""
Nov 07 18:04 : exception: No such playlist
Nov 07 18:04 : client: [2] command returned 3
Nov 07 18:04 : client: [2] process command list

**Comment by Emilot** [comment]
[(01) [Cyndi Lauper] I'm Gonna Be Strong.zip](https://github.com/MusicPlayerDaemon/MPD/files/9953799/01.Cyndi.Lauper.I.m.Gonna.Be.Strong.zip)

test file

**Comment by jcorporation** [comment]
There is no decoder plugin to handle .ape files in your `mpd --version` output. I think you need ffmpeg to play ape files. The real bug is that lsinfo displays ape files as playlist if MPD is not compiled with ffmpeg?

**Comment by Emilot** [comment]
JC Thank you. My mistake. You are right but i keep it open if Max needs to see the "real issue" you mention.

**Comment by jcorporation** [comment]
I copy the the mpd response from the myMPD bug here:
This is the response of `lsinfo`:
```
playlist: nas-samba/Cyndi Lauper - Twelve Deadly Cyns... And Then Some (1994)/(01) [Cyndi Lauper] I'm Gonna Be Strong.ape
```
