### ISSUE TITLE
Debian Bullseye /raspbian : no httpd port listen and no error message

### ISSUE THREAD

**Issue by gbulot** [MusicPlayerDaemon/MPD#1668]
### Describe the bug

My conf worked with output httpd for months and after reboot : nothing work on tcp/8000 
  `netstat -peanut | grep 8000` ==> nothing
`  rm /var/lib/mpd/state ; mpd --verbose --stderr --no-daemon /etc/mpd.conf`  ==> no error message / nothing about http

I try also with "disable" mpd.socket, only output httpd, many reboot , disable avahi, another port (8001) , strace, nothing help me 
### other issues
no answer in 
-   issues/1585
-   issues/1573
### dependencies ? 
```
dpkg -l | grep -e lame -e vorbis
ii  libmp3lame0:armhf              3.100-2+b1                          armhf        MP3 encoding library
ii  libtwolame0:armhf              0.3.13-4                            armhf        MPEG Audio Layer 2 encoding library
ii  libvorbis0a:armhf              1.3.6-2                             armhf        decoder library for Vorbis General Audio Compression Codec
ii  libvorbisenc2:armhf            1.3.6-2                             armhf        encoder library for Vorbis General Audio Compression Codec
ii  libvorbisfile3:armhf           1.3.6-2                             armhf        high-level API for Vorbis General Audio Compression Codec
```
### manual start with logs
=== manual start mpd --verbose --stderr --no-daemon /etc/mpd.conf
```
config_file: loading file /etc/mpd.conf
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg
adplug: adplug 2.2.1
simple_db: reading DB
curl: version 7.64.0
curl: with GnuTLS/3.6.7
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player @ pisound
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
exception: Failed to open '/var/lib/mpd/state': No such file or directory
inotify: initializing inotify
inotify: watching music directory
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
avahi: Service group changed to state 2
avahi: Service 'Music Player @ pisound' successfully established.

```

## Expected Behavior

mpd is listenning on 8000/tcp to play music 

## Actual Behavior

netstat shown nothing on 8000/tcp

## Version

Music Player Daemon 0.21.5 (0.21.5)

Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## my /etc/mpd.conf

```
## Configuration
music_directory         "/media/NAS/musiques"
playlist_directory      "/var/lib/mpd/playlists"
db_file                 "/var/lib/mpd/tag_cache"
log_file                "/var/log/mpd/mpd.log"
pid_file                "/run/mpd/pid"
state_file              "/var/lib/mpd/state"
sticker_file            "/var/lib/mpd/sticker.sql"
user                    "mpd"
bind_to_address         "0.0.0.0"
auto_update                                                     "yes"
input {
        plugin                                  "curl"
}
audio_output {
        type            "alsa"
        name            "Hifi Berry DAC"
}
filesystem_charset      "UTF-8"
audio_output {
    type            "httpd"
    name            "Pi HTTP Stream"
    bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
   encoder         "lame"                # same with vorbis
    port            "8000"
    bitrate         "128"                   # do not define if quality is defined
    format          "44100:16:1"
    always_on       "yes"                   # prevent MPD from disconnecting all listeners when playback is stopped.
    tags            "yes"                   # httpd supports sending tags to listening streams.
    enabled         "yes"
}
input {
    plugin      "tidal"
    enabled     "no"
}
input {
    plugin      "qobuz"
    enabled     "no"
}

```

## Log
see manual start on top on this issue

**Comment by MaxKellermann** [comment]
Your MPD version is very old and unsupported.

**Comment by gbulot** [comment]
https://github.com/MusicPlayerDaemon/MPD/issues/1668 => it concerned with versions ?
