### ISSUE TITLE
Android: Unhelpful error message (curl/webdav)

### ISSUE THREAD

**Issue by avuton** [MusicPlayerDaemon/MPD#1670]
### Describe the bug
When attempting to play audio over WebDav with curl on Android, a error message is output to the log, but it's not particularly helpful in diagnosing the issue.

## Expected Behavior
A more informational error, probably telling me more particularly that support doesn't exist for curl/webdav in android.

## Actual Behavior
Error.

## Version

0.23.10 (F-Droid)

## Configuration

music_directory			"https://user:pass@nc.domain.com/remote.php/dav/files/sound/Stored/Sound"
bind_to_address		"any"
log_level			"default"
restore_paused "yes"
auto_update    "yes"

database {
       plugin "proxy"
       host "domain.com"
}

## Log

E/ exception: Failed to decode https://nc.domain.com/remote.php/dav/files/sound/Stored/Sound/1.wav: Error

**Comment by jasiup** [comment]
Hello,
same problem with compiled from source for Android version mpd-0.23.10 or git mpd-0.23.11, newest f-droid version also not working (https://f-droid.org/repo/org.musicpd_69.apk)
Windows version is not working (binary install) Music Player Daemon 0.23.10 (0.23.10)

exception: Failed to decode http://radio.rockserwis.fm/live#Rockserwis; Error
playlist: play 0:"http://radio.rockserwis.fm/live#Rockserwis"
client: [1] command returned 0
exception: Failed to decode http://radio.rockserwis.fm/live#Rockserwis; Error
player: played "http://radio.rockserwis.fm/live#Rockserwis"
playlist: stop

Older version is working, tested f-droid build: https://f-droid.org/repo/org.musicpd_59.apk
