### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [MusicPlayerDaemon/MPD#1685]
### Describe the bug
Our 0.23.11 build produces an invalid apk. 
[org.musicpd_70_32.zip](https://github.com/MusicPlayerDaemon/MPD/files/10148068/org.musicpd_70_32.zip)

We build it with

```
      - cd output/android/
      - python3 ../../android/build.py $$SDK$$ $$NDK$$ armeabi-v7a --buildtype=debugoptimized
        -Db_ndebug=true -Dwrap_mode=forcefallback
      - ninja android/apk/mpd-unsigned.apk
```

You can check the metadata at https://gitlab.com/linsui/fdroiddata/-/blob/2a9c155cb5a029766d467b227985004a84a6ce1d/metadata/org.musicpd.yml

## Expected Behavior
A valid apk is built.

## Actual Behavior
The apk is invalid.

## Version
0.23.11

**Comment by MaxKellermann** [comment]
What makes the APK invalid?

**Comment by linsui** [comment]
I'm not sure... I can't install it with an error failed parsing the package.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/2843 Maybe this can provide more info.

**Comment by linsui** [comment]
I also see something like `ApplicationInfo is null` in MaterialFiles.

**Comment by MaxKellermann** [comment]
Uh, of course, `mpd-unsigned.apk` is not aligned. See:
https://github.com/MusicPlayerDaemon/MPD/blob/756621c6e4a63797bfe4c0372df6e3fac1330a44/android/apk/meson.build#L1
https://github.com/MusicPlayerDaemon/MPD/blob/756621c6e4a63797bfe4c0372df6e3fac1330a44/android/apk/meson.build#L15-L21
`mpd-unsigned.apk` is the input for `mpd-aligned.apk` (now aligned but still unsigned), and the final step is to sign the aligned APK.
You took the wrong ninja target.

**Comment by linsui** [comment]
I tried that. It's not the problem. I thought zipalign can't make the apk invalid and we use the same code since 0.21.8. It seems there is no change in the Android code, either. But it just suddenly build an invalid apk. Very strange.

**Comment by MaxKellermann** [comment]
> I thought zipalign can't make the apk invalid

That's the wrong way around. zipalign makes the APK valid (as in: unaligned ZIPs are considered invalid, per your error message). Not running zipalign is a mistake, one you have been making, according to your data.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/commit/93b3a906ff02316bb92739b3a5f69b79db27f52e It still produced an invalid apk so there is another problem...

**Comment by avuton** [comment]
I'm not sure what the issue is, but I just had no issue getting v0.23.11 working as a debug build. I wish I could help more in tracking down the issue, but right now, to me, it appears to be a problem with the F-Droid build. (Built in a Debian chroot using the user documentation).

**Comment by linsui** [comment]
You are right, the problem is that the apk is not aligned. When I tested it I built a unaligned apk but picked the unaligned one.

I did a bisect and I found https://github.com/MusicPlayerDaemon/MPD/commit/8c9d7bf07ef9e48edad534e780836da19af88948 make the unaligned apk broken. This is very interesting...

Thanks for your help!
