### ISSUE TITLE
Problem Crosscompiling for Windows 64bit

### ISSUE THREAD

**Issue by 10milesrabbit** [MusicPlayerDaemon/MPD#169]
There are (confirmed) compile errors when build with 'build.py'
Version: 0.20.12
System: Linux Mint 18.2
Replay:
- with fileset from git do:
- run './autogen.sh'
- run './win32/build.py --64'
=> errors

More info (including log with errors): https://forum.musicpd.org/viewtopic.php?f=7&t=6364

Versions C++ / Yasm:
`x86_64-w64-mingw32-g++ (GCC) 5.3.1 20160211
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

yasm 1.3.0
Compiled on May  6 2015.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
`

**Comment by MaxKellermann** [comment]
I don't see an error here.

**Comment by 10milesrabbit** [comment]
Clarified by putting the link to MPD site direct under "errors".
