### ISSUE TITLE
Glitch in gapless playback when oversampling

### ISSUE THREAD

**Issue by charleski** [MusicPlayerDaemon/MPD#1692]
## Bug report
Using moode (mpd version 0.23.5). When oversampling (soxr) is turned on a small snippet of the following track is skipped, causing a glitch on playback.  Turning oversampling off removes the glitch. This is repeatable and happens with two different DACs. 
The following image shows two recordings from moode playing a couple of files. The top trace was recorded with oversampling on (192kHz), and the glitch can be seen at Marker 1. The bottom trace shows the same two files being played without oversampling. Approximately 2866 samples have been skipped from the start of the second track.
![MPD_oversampling_gapless_bug](https://user-images.githubusercontent.com/4446874/207627277-2cb09014-b028-4c5c-86f3-29f493df5299.jpg)

## Expected Behavior
Glitch-free playback

## Actual Behavior
The glitch happens only when oversampling is on. This occurs no matter which parameters are used for the oversampling.

## Version
Music Player Daemon 0.23.5 (v8.0.2-6-gf45f823+)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus epoll icu inotify systemd tcp un

#########################################
# This file is automatically generated
# by the MPD configuration page.
#########################################

music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"
log_file "/var/log/mpd/log"
pid_file "/var/run/mpd/pid"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
restore_paused "yes"
auto_update "no"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
zeroconf_enabled "no"
zeroconf_name "Moode MPD"
filesystem_charset "UTF-8"
metadata_to_use "+comment"
replaygain "album"
replaygain_preamp "0"
volume_normalization "no"
audio_buffer_size "32768"
max_output_buffer_size "262144"
max_playlist_length "16384"
max_connections "128"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

resampler {
plugin "soxr"
quality "custom"
threads "0"
precision "28"
phase_response "46"
passband_end "95"
stopband_begin "105"
attenuation "0"
flags "0"
}

audio_output {
type "alsa"
name "ALSA Default"
device "_audioout"
mixer_type "none"
dop "no"
stop_dsd_silence "no"
thesycon_dsd_workaround "no"
}

audio_output {
type "alsa"
name "ALSA Bluetooth"
device "_audioout"
mixer_type "software"
}

audio_output {
type "httpd"
name "HTTP Server"
port "8000"
encoder "lame"
bitrate "320"
tags "yes"
always_on "yes"
}

## Log
Dec 14 13:06 : client: [14] opened from 127.0.0.1:38230
Dec 14 13:06 : client: [14] process command list
Dec 14 13:06 : client: process command "clear"
Dec 14 13:06 : client: command returned 0
Dec 14 13:06 : client: process command "add "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac""
Dec 14 13:06 : client: command returned 0
Dec 14 13:06 : client: process command "add "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac""
Dec 14 13:06 : client: command returned 0
Dec 14 13:06 : client: process command "play"
Dec 14 13:06 : playlist: play 0:"USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac"
Dec 14 13:06 : client: command returned 0
Dec 14 13:06 : client: [14] process command list returned 0
Dec 14 13:06 : playlist: queue song 1:"USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac"
Dec 14 13:06 : client: [10] process command "status"
Dec 14 13:06 : client: [10] command returned 0
Dec 14 13:06 : client: [3] process command "status"
Dec 14 13:06 : client: [3] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [10] process command "currentsong"
Dec 14 13:06 : client: [10] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [3] process command "currentsong"
Dec 14 13:06 : client: [3] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : decoder_thread: probing plugin flac
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : decoder: audio_format=44100:16:2, seekable=true
Dec 14 13:06 : decoder: converting to 192000:24:2
Dec 14 13:06 : client: [14] process command "close"
Dec 14 13:06 : client: [14] command returned 4
Dec 14 13:06 : client: [14] closed
Dec 14 13:06 : soxr: soxr engine 'cr64'
Dec 14 13:06 : soxr: soxr precision=28, phase_response=46.00, passband_end=0.95, stopband_begin=1.05 scale=1.00
Dec 14 13:06 : soxr: samplerate conversion ratio to 4.35
Dec 14 13:06 : alsa_output: opened _audioout type=COPY
Dec 14 13:06 : alsa_output: buffer: size=48..131072 time=250..682667
Dec 14 13:06 : alsa_output: period: size=24..65536 time=125..341334
Dec 14 13:06 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Dec 14 13:06 : alsa_output: format=S24_LE (Signed 24 bit Little Endian)
Dec 14 13:06 : alsa_output: buffer_size=96000 period_size=24000
Dec 14 13:06 : output: opened "ALSA Default" (alsa) audio_format=192000:24:2
Dec 14 13:06 : client: [3] process command "lsinfo "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac""
Dec 14 13:06 : client: [3] command returned 0
Dec 14 13:06 : client: [3] process command "close"
Dec 14 13:06 : client: [3] command returned 4
Dec 14 13:06 : client: [3] closed
Dec 14 13:06 : client: [10] process command "lsinfo "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac""
Dec 14 13:06 : client: [10] command returned 0
Dec 14 13:06 : client: [10] process command "close"
Dec 14 13:06 : client: [10] command returned 4
Dec 14 13:06 : client: [10] closed
Dec 14 13:06 : client: [15] opened from 127.0.0.1:38232
Dec 14 13:06 : client: [15] process command "status"
Dec 14 13:06 : client: [15] command returned 0
Dec 14 13:06 : client: [15] process command "idle"
Dec 14 13:06 : client: [15] command returned 1
Dec 14 13:06 : replay_gain: replay gain mode has changed off->album
Dec 14 13:06 : replay_gain: scale=1
Dec 14 13:06 : client: [16] opened from 127.0.0.1:38236
Dec 14 13:06 : client: [16] process command "playlistinfo"
Dec 14 13:06 : client: [16] command returned 0
Dec 14 13:06 : client: [16] process command "close"
Dec 14 13:06 : client: [16] command returned 4
Dec 14 13:06 : client: [16] closed
Dec 14 13:06 : decoder_thread: probing plugin flac
Dec 14 13:06 : decoder: audio_format=44100:16:2, seekable=true
Dec 14 13:06 : decoder: converting to 192000:24:2
Dec 14 13:06 : soxr: soxr engine 'cr64'
Dec 14 13:06 : soxr: soxr precision=28, phase_response=46.00, passband_end=0.95, stopband_begin=1.05 scale=1.00
Dec 14 13:06 : soxr: samplerate conversion ratio to 4.35
Dec 14 13:06 : client: [4] process command "idle playlist player mixer options"
Dec 14 13:06 : client: [4] command returned 1
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [17] opened from 127.0.0.1:38238
Dec 14 13:06 : client: [17] process command "currentsong"
Dec 14 13:06 : client: [17] command returned 0
Dec 14 13:06 : client: [17] process command "close"
Dec 14 13:06 : client: [17] command returned 4
Dec 14 13:06 : client: [17] closed
Dec 14 13:06 : client: [4] process command "idle playlist player mixer options"
Dec 14 13:06 : client: [4] command returned 1
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [18] opened from 127.0.0.1:38240
Dec 14 13:06 : client: [18] process command "currentsong"
Dec 14 13:06 : client: [18] command returned 0
Dec 14 13:06 : client: [18] process command "close"
Dec 14 13:06 : client: [18] command returned 4
Dec 14 13:06 : client: [18] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [19] opened from 127.0.0.1:38242
Dec 14 13:06 : client: [19] process command "currentsong"
Dec 14 13:06 : client: [19] command returned 0
Dec 14 13:06 : client: [19] process command "close"
Dec 14 13:06 : client: [19] command returned 4
Dec 14 13:06 : client: [19] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [20] opened from 127.0.0.1:38244
Dec 14 13:06 : client: [20] process command "currentsong"
Dec 14 13:06 : client: [20] command returned 0
Dec 14 13:06 : client: [20] process command "close"
Dec 14 13:06 : client: [20] command returned 4
Dec 14 13:06 : client: [20] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [21] opened from 127.0.0.1:38248
Dec 14 13:06 : client: [21] process command "currentsong"
Dec 14 13:06 : client: [21] command returned 0
Dec 14 13:06 : client: [21] process command "close"
Dec 14 13:06 : client: [21] command returned 4
Dec 14 13:06 : client: [21] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "1""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac"
Dec 14 13:06 : client: [15] process command "status"
Dec 14 13:06 : client: [15] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [15] process command "currentsong"
Dec 14 13:06 : client: [15] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [15] process command "lsinfo "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac""
Dec 14 13:06 : client: [15] command returned 0
Dec 14 13:06 : client: [15] process command "close"
Dec 14 13:06 : client: [15] command returned 4
Dec 14 13:06 : client: [15] closed
Dec 14 13:06 : client: [22] opened from 127.0.0.1:38250
Dec 14 13:06 : client: [22] process command "status"
Dec 14 13:06 : client: [22] command returned 0
Dec 14 13:06 : client: [22] process command "idle"
Dec 14 13:06 : client: [22] command returned 1
Dec 14 13:06 : client: [23] opened from 127.0.0.1:38252
Dec 14 13:06 : client: [23] process command "playlistinfo"
Dec 14 13:06 : client: [23] command returned 0
Dec 14 13:06 : client: [23] process command "close"
Dec 14 13:06 : client: [23] command returned 4
Dec 14 13:06 : client: [23] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [4] process command "idle playlist player mixer options"
Dec 14 13:06 : client: [4] command returned 1
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [24] opened from 127.0.0.1:38256
Dec 14 13:06 : client: [24] process command "currentsong"
Dec 14 13:06 : client: [24] command returned 0
Dec 14 13:06 : client: [24] process command "close"
Dec 14 13:06 : client: [24] command returned 4
Dec 14 13:06 : client: [24] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [25] opened from 127.0.0.1:38258
Dec 14 13:06 : client: [25] process command "currentsong"
Dec 14 13:06 : client: [25] command returned 0
Dec 14 13:06 : client: [25] process command "close"
Dec 14 13:06 : client: [25] command returned 4
Dec 14 13:06 : client: [25] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [26] opened from 127.0.0.1:38260
Dec 14 13:06 : client: [26] process command "currentsong"
Dec 14 13:06 : client: [26] command returned 0
Dec 14 13:06 : client: [26] process command "close"
Dec 14 13:06 : client: [26] command returned 4
Dec 14 13:06 : client: [26] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [27] opened from 127.0.0.1:38262
Dec 14 13:06 : client: [27] process command "currentsong"
Dec 14 13:06 : client: [27] command returned 0
Dec 14 13:06 : client: [27] process command "close"
Dec 14 13:06 : client: [27] command returned 4
Dec 14 13:06 : client: [27] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "currentsong"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [5] process command "playlistinfo "2""
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : client: [28] opened from 127.0.0.1:38264
Dec 14 13:06 : client: [28] process command "currentsong"
Dec 14 13:06 : client: [28] command returned 0
Dec 14 13:06 : client: [28] process command "close"
Dec 14 13:06 : client: [28] command returned 4
Dec 14 13:06 : client: [28] closed
Dec 14 13:06 : client: [5] process command "status"
Dec 14 13:06 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac"
Dec 14 13:06 : client: [5] command returned 0
Dec 14 13:06 : playlist: stop
Dec 14 13:06 : output: closed "ALSA Default" (alsa)

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported.

**Comment by charleski** [comment]
The latest version of moode incorporates version 0.23.11, which is also the latest version of mpd available in the kaliko respository.
The bug is still present and needs to be fixed.


pi@moode:~ $ mpd --version
Music Player Daemon 0.23.11 (r822prod-18-gb35b25b)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local


Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus epoll icu inotify systemd tcp un

#########################################
# This file is automatically generated   
# by the MPD configuration page.         
#########################################

music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"
log_file "/var/log/mpd/log"
pid_file "/var/run/mpd/pid"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
restore_paused "yes"
auto_update "no"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
zeroconf_enabled "no"
zeroconf_name "Moode MPD"
filesystem_charset "UTF-8"
metadata_to_use "+comment"
audio_output_format "192000:24:2"
replaygain "album"
replaygain_preamp "0"
volume_normalization "no"
audio_buffer_size "8192"
max_output_buffer_size "262144"
max_playlist_length "16384"
max_connections "128"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

resampler {
plugin "soxr"
quality "very high"
threads "0"
}

audio_output {
type "alsa"
name "ALSA Default"
device "_audioout"
mixer_type "none"
dop "no"
stop_dsd_silence "no"
thesycon_dsd_workaround "no"
}

audio_output {
type "alsa"
name "ALSA Bluetooth"
device "_audioout"
mixer_type "software"
}

audio_output {
type "httpd"
name "HTTP Server"
port "8000"
encoder "flac"
compression "0"
tags "yes"
always_on "yes"
}

Log:
Jan 18 10:15 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac"
Jan 18 10:15 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac"
Jan 18 10:17 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac"
Jan 18 10:17 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac"
Jan 18 10:27 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/15 Scena 5 - Furie terribili (Aria - Armida)-frgm.flac"
Jan 18 10:27 : player: played "USB/Music_Ext/Unfiled/Rinaldo test/16 Come a tempo giungesti, cara (Recitativo ed accopagnato - Argante, Armida)-frgm.flac"


![resampleglitch2](https://user-images.githubusercontent.com/4446874/213152193-b1dd9b28-e915-424c-8dcc-2727888b63c8.jpg)

**Comment by MaxKellermann** [comment]
Your log is incomplete. It doesn't show the start of playback.

Also note that the MPD fork distributed with Moode is unsupported because it was patched. In particular, MPD's resampling code has been modified. It is impossible for this project to support modified MPD builds.

**Comment by charleski** [comment]
Ok, well I let Tim Curtis know about it as well, though it doesn't seem this is related to the Selective Resampling patch he uses. 
So you both know about the defect,
