### ISSUE TITLE
Add Smart Playlist Support

### ISSUE THREAD

**Issue by MickMorley** [MusicPlayerDaemon/MPD#1694]
## Feature request
I recently tested OwnTone because it supported the ability to control the volume of an individual sink/output.  It is not as stable as MPD and I would like to stay with using my MPD server.

One great feature of OwnTone was the abilty to support smart playlists.  See https://owntone.github.io/owntone-server/smart-playlists/

Instead of being an m3u file it, it is a smartpl file.  I believe this is a feature of iTunes but the logic of a smart playlist was very simple to set up and the server mixed the songs based on the expressions at runtime.

I am continually adding music to my library and smart playlists were great because they would not require any update to any playlist on my part.

**Comment by MaxKellermann** [comment]
I don't quite understand the feature. There's nothing smart with "smart playlists", is there? It's just a search expression for the music database, or am I missing something?

**Comment by martadinata666** [comment]
In simple terms, i define some parameter to "smart playlist", MPD will generate playlist based my parameter. I think MPD is already half way there.

In owntone:
1. Define a smart playlist
```
playlistname.smartpl
```
```
"playlistname" {
  artist is "some-artist"
}
```

2. Then owntone will create playlist based on `some-artist`.

**Comment by MaxKellermann** [comment]
@martadinata666, why don't you just answer my question, instead of adding more confusion?

**Comment by martadinata666** [comment]
"i want ariana grande for this playlist, then MPD will generate a playlist with all ariana grande songs from my library." Without i need to search up database and adding it manually to playlist.

I think that simple enough to understand. 🤔

**Comment by Emilot** [comment]
@martadinata666 you can use myMPD for this:

https://jcorporation.github.io/myMPD/references/smart-playlists

**Comment by martadinata666** [comment]
yep, exactly same function like that owntone, just explaining about the `smart` thing. And I think this pretty interesting if implemented to MPD.

MYMPD ftw

**Comment by MaxKellermann** [comment]
3 more replies and still no answer to my question. If it's so simple to understand, what's so hard about answering a yes/no question?

**Comment by martadinata666** [comment]
> I don't quite understand the feature. There's nothing smart with "smart playlists", is there? It's just a search expression for the music database, or am I missing something?

Yes, that is no smart, it just `Search DB`, add to `Playlist`.

**Comment by MaxKellermann** [comment]
So ... MPD already provides all the pieces for a client to implement the feature with one single MPD command (i.e. `searchadd`).

**Comment by martadinata666** [comment]
Yes, myMPD https://jcorporation.github.io/myMPD/references/smart-playlists already implemented it.
I assume this kind of feature will depends on `client` then it fine. It just niche feature to MPD generate the playlist rather than depend on `client`. But well the solution is there, using myMPD.

**Comment by MaxKellermann** [comment]
Since nobody explained why this should be a server-side feature, I'll close the feature request.

**Comment by MickMorley** [comment]
Hi @MaxKellermann, I think the best argument for it to be a server side feature is the ability to use any client.  I use Home Assistant to manage my MPD controls and sometimes an MPD iOS app.  

I keep all of my playlists in `m3u` and in this case, `smartpl`, files in a directory shared by other apps (Jellyfin).

The granularity of the `smartpl` that Owntone uses is great because you can negate expressions and by using `order by random` the playlists will always change.  My biggest gripe of my personal library is its mixed with Christmas music.  So in July when I want to shuffle all songs by George Strait and Alan Jackson, a few Christmas songs will get in there. 

With the smart playlists I can have a `smartpl` file with the contents below and no holiday music will play.

This can be a very convenient feature that will be make MPD that much better.

```
"Country Mix" {
  (
    artist includes "George Strait"
    or artist includes "Alan Jackson"
  )
  and not genre includes "Holiday"
  order by random desc
  limit 50
}
```

**Comment by DarkArc** [comment]
> I don't quite understand the feature. There's nothing smart with "smart playlists", is there? It's just a search expression for the music database, or am I missing something?

Arguably there's nothing special about playlist at all. Playlist could be an entirely client side concept. However, it's a useful concept to have shared playlist.

Similarly, it's a useful concept to have shared playlist that are defined not by a fixed list but by a query. Arguably "smart playlist" is not about being smart, it's just a different playlist definition format (by a query vs by a fixed list of tracks).

**Comment by groutoutlook** [comment]
then... you know, you could make a PR over `mpc`  no? since this is obviously a QoL over client.

better decouple those logic and put them in the right place.
