### ISSUE TITLE
Android: Failed to load the native MPD library.

### ISSUE THREAD

**Issue by 7kilobytes** [MusicPlayerDaemon/MPD#1695]
## Bug report
Unable to start the MPD version 0.23.11 after update from F-Droid repository. It says that libmpd.so is 32-bit instead of 64-bit.

Please look at the full error message on the screenshot
![Screenshot_20221218-210525_MPD](https://user-images.githubusercontent.com/21251486/208319324-ef82a7a5-02b6-4388-b268-0345ec2ea6ce.png)

## Expected Behavior
The MPD is running

## Actual Behavior
The MPD is not starting

## Version
0.23.11

## Configuration

Not specified

**Comment by MaxKellermann** [comment]
Please report to F-Droid. This project does not publish 32 bit binaries.
