### ISSUE TITLE
mpd does not quit when parent process is killed

### ISSUE THREAD

**Issue by UtkarshVerma** [MusicPlayerDaemon/MPD#1706]
### Describe the bug
I launch `mpd` as a subprocess using `mpd --no-daemon &` from a terminal. But, when I quit the terminal, I expect `mpd` subprocess to be killed as well, like other applications. However, even after the terminal is killed, `mpd` doesn't still runs.

This problem rears its head when `mpd` is launched in my `~/.xinitrc` and a new process is spawned every time I logout and login.

## Expected Behavior
`mpd`  child process should die with the parent.

## Actual Behavior
`mpd` child process remains alive event after the parent dies.

## Version
```
Music Player Daemon 0.23.11 (0.23.11)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## Configuration
```
music_directory     "~/music"
playlist_directory  "~/.config/mpd/playlists"
state_file          "~/.cache/mpd/state"

auto_update         "yes"
restore_paused      "yes"

audio_output {
    type    "pipewire"
    name    "PipeWire Sound Server"
}

audio_output {
    type    "fifo"
    name    "Visualizer feed"
    path    "/tmp/mpd.fifo"
    format  "44100:16:2"
}

# Suppress warnings
bind_to_address "localhost"
decoder {
    enabled "no"
    plugin  "wildmidi"
}
```

**Comment by MaxKellermann** [comment]
How is MPD supposed to know that the parent process was killed?

**Comment by UtkarshVerma** [comment]
> How is MPD supposed to know that the parent process was killed?

The default behaviour is that the parent sends `SIGHUP` to its children when it dies and the child processes kill themselves. However, in case of `mpd`, `SIGHUP` is handled differently, so this doesn't happen.

I've prepared a short example to allow you to reproduce this behaviour:
```c
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include <signal.h>
#include <sys/prctl.h>

void sighupHandler() {
    printf("Received SIGHUP!\n");
}

int main() {
    signal(SIGHUP, sighupHandler);
    prctl(PR_SET_PDEATHSIG, SIGTERM);     // This line tells our parent to send SIGTERM on its death

    time_t t;
    struct tm *tm;
    while (1) {
        t = time(NULL);
        tm = localtime(&t);
        char s[64];
        strftime(s, sizeof(s), "%c", tm);
        printf("%s: Still alive!\n", s);
        sleep(1);
    }
}
```

You can test this by running the program with and without `prctl(PR_SET_PDEATHSIG, SIGTERM);`. In the first case, the program will die when the calling parent dies. In the second case, the program will be alive even after the parent is killed, which is how `mpd` is behaving right now.

Now, I believe `mpd` should follow the first case, as it is usually called by `systemd` or `xinit`. It doesn't make sense for `mpd` to be alive even after `systemd` or the X session has finished.

**Comment by UtkarshVerma** [comment]
@MaxKellermann Any updates regarding this?
