### ISSUE TITLE
MDP 0.23.6 MP3 crash

### ISSUE THREAD

**Issue by zj3t** [MusicPlayerDaemon/MPD#1707]
### Describe the bug
Vulnerability in MDP version 0.23.6.
When a malicious MP3 is played, the MDP is crashed.

## Actual Behavior
A vulnerability has been discovered in Automotive Grade Linux (AGL) using MDP version 0.23.6.
As a result of checking, it is confirmed that the corresponding part is not patched even in the latest version, 0.23.11.

MP3 files were moved and played in the environment.
After that, it was confirmed that MDP Crashed.

## Version

MDP 0.23.6

## Log

<img width="726" alt="MDP_0 23 6" src="https://user-images.githubusercontent.com/35731091/210047761-9d08af4c-f5fb-4281-977b-95c8a830a7db.png">

Checking the log, mpd_status_get_elapsed_ms: Assertion `status != NULL' faile.
That part appears to be the cause of the crash.

## crash file
I will attach different files that cause the crash.
[exp.zip](https://github.com/MusicPlayerDaemon/MPD/files/10323544/exp.zip)

Thanks!!

**Comment by MaxKellermann** [comment]
What is MDP? Did you mean MDP?
Your log shows no crash of MPD, and `mpd_status_get_elapsed_ms` does not exist in the MPD code base.
Your log shows an application called "mediaplayer" crashing, but this project has no process called "mediaplayer".
Everything is wrong with your bug report, and I think you reported it to the wrong project.

**Comment by zj3t** [comment]
Thanks for your answer,

What I said was MPD. Not MDP,,,(Sorry)

I first reported it to AGL, but I also reported it to you as it might be a problem with MPD.

https://jira.automotivelinux.org/browse/SPEC-4661

**Comment by zj3t** [comment]
As a result of checking, it was confirmed that it was a problem with libmpdclient. I raised an issue on the project again.
