### ISSUE TITLE
While streaming DLNA mpd locks up (100% CPU usage)

### ISSUE THREAD

**Issue by Ghoost666** [MusicPlayerDaemon/MPD#1710]
### Describe the bug
Im using "moode audio" distro which is a little modified (underclocked and MPD has its own core basicly) and sometimes when streaming Qobuz over upnpcli (DLNA) the stream stops, one or two mpd subproccesses go to 100% cpu usage and it hangs till i restart MPD, i just noticed this as long i have MPD run on just one core and the core is isolated with "isolcpu=1"

this just happens when streaming over DLNA to MPD, local playback is running without issue
if i underclock the CPU of the RPI4 to UNDER 1050mhz these lock ups happen way more frequently and always on the end of a song/when the song changes (also its "normal" that the cpu jumps to 100% for a short period of time, either that or it stays at 100%)
with cpu clock of 1050/1100 it was running fine for the most part but i got now the second mid-song hangup, tho im wondering if its right that cpu clock plays a role here, it seems strange that i cant underclock the cpu while using isolcpu

if i use the default moode settings (normal clock, no isolcpu) everything is working but i would like to keep isolcpu and possibly be able to underclock as far as i can without hangups

## Expected Behavior
No hang ups

## Actual Behavior
MPD`s Cpu core goes to 100% and "locks" the system, i can still use SSH commands but moode`s webinterface and playback freezes

## Version

Music Player Daemon 0.23.5 (v8.0.2-6-gf45f823+)

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported.

**Comment by Ghoost666** [comment]
hmm its the version "Moode Audio" uses, im not sure if i can update MPD without getting trouble :(

**Comment by MaxKellermann** [comment]
Complain to Moode Audio. They make money with MPD, without ever contributing anything.
