### ISSUE TITLE
Raising Nice Priority to atleast -1

### ISSUE THREAD

**Issue by Ghoost666** [MusicPlayerDaemon/MPD#1711]
## Feature request
Hello as said in my Issue #1710, i tried to fix my issue and i actually think i found a solution, raising the nice level of the mpd systemd service to -1 , tho i have to test further to make sure its actually fixed

BUT i discovered this has made quite a huge sound quality difference, please someone try this, the difference was actually that huge that i think something is wrong with MPD, it needs more priority to function "properly"
i checked and two tasks where already running at RT priority, like in the MPD documentation, but some other task needs apparantly more priority or better buffer handling or something like that

is this maybe something that was fixed after version 20.5 ? i actually cant believe that this is undiscovered if not

**Comment by MaxKellermann** [comment]
I don't understand half of what you wrote, and the other half sounds utterly wrong.

**Comment by Ghoost666** [comment]
basicly increasing the nice level to -1 in the systemd service file with "Nice=-1" increases sound quality dramaticly 

well you can say its bogus and insist that this doesnt make a sound quality difference logically, but it did and it was not minor
please atleast try it

**Comment by MaxKellermann** [comment]
I would prefer you to keep your advice to yourself, to avoid confusing others with this bullshit.

If this change has any (seemingly reproducible) effect, then this is only due to slight timing differences, and your "trick" changes the timing, but only hides the real problem (temporarily).

Your advice may keep others from analyzing the real problem, so your advice is really harmful. Please don't.

**Comment by Ghoost666** [comment]
well i just reported what i heared, im not a dev

what you mean by timing difference? where does it come from and how should i fix this without raising priority?

**Comment by MaxKellermann** [comment]
It's pointless to discuss this with you because you are using an unsupported version of an unsupported MPD fork. Nobody knows if the latest version of the "real" MPD has this problem.

As long as you're not using a supported MPD version, please keep away from this bug tracker.

**Comment by Ghoost666** [comment]
Oh i didnt saw Moode uses its own MPD fork, then this is probably wrong here, tho maybe you can try it yourself just in case, since the sound quality change was kinda big...

**Comment by Ghoost666** [comment]
One thing i think it did too, was reduce the pop noise you get when switching songs in the middle of a song, its not completely gone but greatly reduced, this would be probably even easier to listen for 

like one song plays and when volume is "high" you switch to another song, this always gave me a somewhat loud "pop" sort of noise and is now reduced with greater priority

i actually think there isnt much done on the MPD fork of moode audio but i could be wrong, i probably will test DietPi soon, so i can try the generic MPD version
