### ISSUE TITLE
mpd 0.23.11 fails build with boost 1.81

### ISSUE THREAD

**Issue by sonic42** [MusicPlayerDaemon/MPD#1722]
The build is failing with boost version 1.81
mpd version 0.23.11

Build Log:
[593/595] Compiling C++ object mpd.p/src_RemoteTagCache.cxx.o
FAILED: mpd.p/src_RemoteTagCache.cxx.o 
ccache c++ -Impd.p -I. -I.. -Isrc -I../src -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O0 -g -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wno-stringop-overflow -fno-threadsafe-statics -fmerge-all-constants -Wcomma-subscript -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wvolatile -Wvirtual-inheritance -Wno-non-virtual-dtor -Wsuggest-override -fvisibility=hidden -D_GNU_SOURCE -O3 -pipe -Wall -fexceptions -fPIC -m64 -mtune=native -fstack-clash-protection -fcf-protection -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -DPCRE2_CODE_UNIT_WIDTH=0 -DBOOST_ALL_NO_LIB -MD -MQ mpd.p/src_RemoteTagCache.cxx.o -MF mpd.p/src_RemoteTagCache.cxx.o.d -o mpd.p/src_RemoteTagCache.cxx.o -c ../src/RemoteTagCache.cxx
In file included from ../src/RemoteTagCache.cxx:20:
../src/RemoteTagCache.hxx:122:55: error: field 'buckets' has incomplete type 'std::array<boost::intrusive::bucket_impl<boost::intrusive::slist_node_traits<void*> >, 127>'
  122 |         std::array<typename KeyMap::bucket_type, 127> buckets;
      |                                                       ^~~~~~~
In file included from /usr/include/c++/12.2.0/bits/unique_ptr.h:36,
                 from /usr/include/c++/12.2.0/memory:76,
                 from ../src/tag/Tag.hxx:28,
                 from ../src/RemoteTagCache.hxx:24:
/usr/include/c++/12.2.0/tuple:1595:45: note: declaration of 'struct std::array<boost::intrusive::bucket_impl<boost::intrusive::slist_node_traits<void*> >, 127>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
[594/595] Compiling C++ object mpd.p/src_db_update_Archive.cxx.o
ninja: build stopped: subcommand failed.
make: *** [mpd:87: /usr/src/log/mpd-0.23.11] Error 1

Meson Log:
cd /usr/src/mpd-0.23.11 && meson	--prefix=/usr 		\
			--sysconfdir=/etc	\
			--libdir=/usr/lib	\
			-Dipv6=disabled 	\
			-Dsqlite=disabled	\
			-Dsmbclient=disabled	\
			-Did3tag=enabled	\
			-Dvorbis=enabled	\
			-Dexpat=enabled		\
			-Dffmpeg=enabled	\
			-Dflac=enabled		\
			-Dlame=enabled		\
			-Dupnp=disabled		\
			builddir/
The Meson build system
Version: 0.64.1
Source dir: /usr/src/mpd-0.23.11
Build dir: /usr/src/mpd-0.23.11/builddir
Build type: native build
Project name: mpd
Project version: 0.23.11
C compiler for the host machine: ccache cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39
C++ compiler for the host machine: ccache c++ (gcc 12.2.0 "c++ (GCC) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring Version.h using configuration
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Compiler for C++ supports arguments -ftree-vectorize: YES 
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wdouble-promotion: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wunused: YES 
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Wunreachable-code-aggressive: NO 
Compiler for C++ supports arguments -Wused-but-marked-unused: NO 
Compiler for C++ supports arguments -Wno-stringop-overflow: YES 
Compiler for C++ supports arguments -fno-threadsafe-statics: YES 
Compiler for C++ supports arguments -fmerge-all-constants: YES 
Compiler for C++ supports arguments -Wcomma-subscript: YES 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wmismatched-tags: YES 
Compiler for C++ supports arguments -Woverloaded-virtual: YES 
Compiler for C++ supports arguments -Wsign-promo: YES 
Compiler for C++ supports arguments -Wvolatile: YES 
Compiler for C++ supports arguments -Wvirtual-inheritance: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wcomma: NO 
Compiler for C++ supports arguments -Wheader-hygiene: NO 
Compiler for C++ supports arguments -Winconsistent-missing-destructor-override: NO 
Compiler for C++ supports arguments -Wsuggest-override: YES 
Compiler for C supports arguments -ffast-math: YES 
Compiler for C supports arguments -ftree-vectorize: YES 
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wdouble-promotion: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -Wunreachable-code-aggressive: NO 
Compiler for C supports arguments -Wused-but-marked-unused: NO 
Compiler for C supports arguments -Wno-stringop-overflow: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C++ supports link arguments -Wl,-z,relro: YES 
Compiler for C++ supports link arguments -Wl,-z,now: YES 
Checking for function "getpwnam_r" : YES 
Checking for function "getpwuid_r" : YES 
Checking for function "initgroups" : YES 
Checking for function "fnmatch" : YES 
Checking for function "strndup" : YES 
Checking for function "strcasestr" : YES 
Checking for function "syslog" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency Boost found: YES 1.81.0 (/usr)
Run-time dependency fmt found: YES 9.1.0
Found CMake: /usr/bin/cmake (3.24.2)
Run-time dependency liburing found: NO (tried pkgconfig and cmake)
Configuring Features.h using configuration
Run-time dependency threads found: YES
Checking for function "pthread_setname_np" with dependency threads: YES 
Header "sys/socket.h" has symbol "struct ucred" : YES 
Header "sys/socket.h" has symbol "SO_PEERCRED" : YES 
Checking for function "getpeereid" : NO 
Configuring Features.h using configuration
Run-time dependency dbus-1 found: YES 1.14.4
Run-time dependency icu-i18n found: YES 72.1
Dependency smbclient skipped: feature smbclient disabled
Run-time dependency zlib found: YES 1.2.13
Run-time dependency alsa found: YES 1.2.5.1
Run-time dependency libchromaprint found: NO (tried pkgconfig and cmake)
Run-time dependency libcurl found: YES 7.87.0
Run-time dependency expat found: YES 2.5.0
Run-time dependency libavformat found: YES 59.27.100
Run-time dependency libavcodec found: YES 59.37.100
Run-time dependency libavutil found: YES 57.28.100
Run-time dependency libavfilter found: YES 8.44.100
Run-time dependency libnfs found: NO (tried pkgconfig and cmake)
Run-time dependency libpcre2-8 found: YES 10.42
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)
Run-time dependency libpulse found: NO (tried pkgconfig and cmake)
Library sndio found: NO
Dependency sqlite3 skipped: feature sqlite disabled
Run-time dependency libsystemd found: NO (tried pkgconfig and cmake)
Run-time dependency yajl found: NO (tried pkgconfig and cmake)
Run-time dependency avahi-client found: YES 0.8
Run-time dependency id3tag found: YES 0.15.1b
Run-time dependency samplerate found: NO (tried pkgconfig and cmake)
Run-time dependency soxr found: YES 0.1.3
Run-time dependency libcdio_paranoia found: NO (tried pkgconfig and cmake)
Run-time dependency libmms found: NO (tried pkgconfig and cmake)
Configuring Features.h using configuration
Run-time dependency libiso9660 found: NO (tried pkgconfig and cmake)
Library bz2 found: YES
Run-time dependency zziplib found: NO (tried pkgconfig and cmake)
Configuring Features.h using configuration
Run-time dependency ao found: NO (tried pkgconfig and cmake)
Run-time dependency jack found: NO (tried pkgconfig and cmake)
Run-time dependency openal found: NO (tried pkgconfig and cmake)
Run-time dependency shout found: YES 2.4.3
Configuring Features.h using configuration
Run-time dependency flac found: YES 1.4.2
Run-time dependency opus found: YES 1.3.1
Run-time dependency vorbis found: YES 1.3.7
Run-time dependency vorbisenc found: YES 1.3.7
Run-time dependency ogg found: YES 1.3.5
Run-time dependency adplug found: NO (tried pkgconfig and cmake)
Run-time dependency fluidsynth found: NO (tried pkgconfig and cmake)
Run-time dependency audiofile found: NO (tried pkgconfig and cmake)
Library faad found: YES
Library gme found: NO
Library mad found: YES
Run-time dependency libmikmod found: NO (tried pkgconfig and cmake)
Run-time dependency libmodplug found: NO (tried pkgconfig and cmake)
Run-time dependency libopenmpt found: NO (tried pkgconfig and cmake)
Library mpcdec found: NO
Run-time dependency libmpg123 found: NO (tried pkgconfig and cmake)
Run-time dependency sndfile found: NO (tried pkgconfig and cmake)
Run-time dependency wavpack found: NO (tried pkgconfig and cmake)
Run-time dependency wildmidi found: NO (tried pkgconfig and cmake)
Library WildMidi found: NO
Run-time dependency libsidplayfp found: NO (tried pkgconfig and cmake)
Run-time dependency libsidplay2 found: NO (tried pkgconfig and cmake)
Configuring Features.h using configuration
Library mp3lame found: YES
Run-time dependency twolame found: NO (tried pkgconfig and cmake)
Run-time dependency shine found: NO (tried pkgconfig and cmake)
Configuring Features.h using configuration
Configuring Features.h using configuration
Run-time dependency libmpdclient found: NO (tried pkgconfig and cmake)
Configuring config.h using configuration
Program sphinx-build found: NO
Build targets in project: 65

mpd 0.23.11

  User defined options
    libdir    : /usr/lib
    prefix    : /usr
    sysconfdir: /etc
    expat     : enabled
    ffmpeg    : enabled
    flac      : enabled
    id3tag    : enabled
    ipv6      : disabled
    lame      : enabled
    smbclient : disabled
    sqlite    : disabled
    upnp      : disabled
    vorbis    : enabled

**Comment by MaxKellermann** [comment]
e4b055eb6d08c5c8f8d85828ce4005d410e462cb
