### ISSUE TITLE
Failed to bind socket: Address already in use

### ISSUE THREAD

**Issue by cyberdynesoftware** [MusicPlayerDaemon/MPD#1725]
### Discussed in https://github.com/MusicPlayerDaemon/MPD/discussions/1724

<div type='discussions-op-text'>

<sup>Originally posted by **cyberdynesoftware** January 15, 2023</sup>
I did struggle a bit to get mpd working, because mpd produces this error:

> Jan 14 15:46:07 butler mpd[2174]: server_socket: bind to ‘0.0.0.0:6600’ failed (continuing anyway, because binding to ‘[::]:6600’ succeeded): Failed to bind socket: Address already in use

Turns out that I had problems for other reasons: I think that the user in mpd.conf needs to match the user with which I start mpd with systemctl. Maybe this is obvious, but I stumbled on it.

Anyway, I got it working. Above error message persists in the log though. My understanding is this: mpd binds itself first to [::]:6600, which also binds to 0.0.0.0:6600 automatically. Afterwards, mpd tries to bind to 0.0.0.0:6600, which fails with above error. If this is true, the error message is useless and I would consider it a bug.

The problem with the message is that it got me hunting in the wrong direction when I struggled to get mpd working. In the end, it had nothing to do with port 6600.</div>

**Comment by MaxKellermann** [comment]
> If this is true, the error message is useless and I would consider it a bug.

I don't. And you needn't struggle with this. If you don't know enough about networking to understand the error message, you could have consulted the MPD documentation: https://mpd.readthedocs.io/en/stable/user.html#error-bind-to-0-0-0-0-6600-failed-continuing-anyway-because-binding-to-6600-succeeded
