### ISSUE TITLE
100% CPU usage in BufferingInputStream doing http streaming when http  server close the connection unexpectedly mid-stream 

### ISSUE THREAD

**Issue by bubbleguuum** [MusicPlayerDaemon/MPD#1727]
### Describe the bug

When mpd is doing http streaming, if the underlying http server closes the connection unexpectedly mid-stream while it was sending audio data in the http response, mpd will use 100% CPU usage.

After analysis with `perf top` and  running mpd under GDB, it appears it is the "buffering" thread is busy in an active loop:

```
Thread 6 (Thread 0x7f60aa35c6c0 (LWP 28594) "buffering"):
#0  ProxyInputStream::Seek(std::unique_lock<std::mutex>&, unsigned long) (this=0x7f60a0000f80, lock=..., new_offset=1010626) at ../src/input/ProxyInputStream.cxx:95
#1  0x000055f7da37bdb2 in BufferingInputStream::RunThreadLocked(std::unique_lock<std::mutex>&) (lock=..., this=0x7f60a0011260) at ../src/input/BufferingInputStream.cxx:138
#2  BufferingInputStream::RunThread() (this=0x7f60a0011260) at ../src/input/BufferingInputStream.cxx:185
#3  BindMethodDetail::WrapperGenerator<void (BufferingInputStream::*)() noexcept, &BufferingInputStream::RunThread>::Invoke(void*) (_instance=0x7f60a0011260) at ../src/util/BindMethod.hxx:130
#4  0x000055f7da36d473 in BoundMethod<void () noexcept>::operator()() const (this=0x7f60a0011278) at ../src/util/BindMethod.hxx:77
#5  Thread::Run() (this=0x7f60a0011278) at ../src/thread/Thread.cxx:63
#6  Thread::ThreadProc(void*) (ctx=0x7f60a0011278) at ../src/thread/Thread.cxx:92
#7  0x00007f60ba29398d in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007f60ba319344 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
``` 

Looking at relevant code in BufferingInputStream:

```
inline void
BufferingInputStream::RunThreadLocked(std::unique_lock<Mutex> &lock)
{
	while (!stop) {
		 ...
                 else if (input->IsEOF()) {
			/* our input has reached its end: prepare
			   reading the first remaining hole */

			size_t new_offset = FindFirstHole();
			if (new_offset == INVALID_OFFSET) {
				/* the file has been read completely */
				break;
			}

			/* seek to the first hole */
			input->Seek(lock, new_offset);
		}
               ...
        }
}
```

So when the http server unexpectedly closes the connection mid-stream, execution is stuck forever in the `input->IsEOF()` block, causing the 100% usage due to the `while(true)` loop.
It does not detect properly that it should exit that block, and mpd is stuck there until being force killed.
I do not know what this `FindFirstHole()` function does but it sure never returns `INVALID_OFFSET` to exit the loop.

I would not be surprised this is the issue happening in #1710

I cannot provide an easy way to reproduce this bug as I use a custom streaming http server and I noticed this issue while  explicitly testing closing the http connection mid-stream to check if my server code handled that exceptional situation properly.

## Expected Behavior

mpd should detect unexpected mid-stream EOF from the server properly and exit buffering thread accordingly.

## Version
0.23.12

**Comment by MaxKellermann** [comment]
Hey, excellent bug report with complete analysis! I'll check this out later, tomorrow or so.

**Comment by bubbleguuum** [comment]
I have tested the fix and confirm that it is working. Thanks !
