### ISSUE TITLE
exception: Failed to set group 997: Operation not permitted

### ISSUE THREAD

**Issue by levdopa** [MusicPlayerDaemon/MPD#1728]
mpd --verbose
config_file: loading file /home/levdopa/.config/mpd/mpd.conf
server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
exception: Failed to set group 997: Operation not permitted

I have mpd & in my .xprofile

If I do mpc update then it returns MPD error: Connection refused

**Comment by MaxKellermann** [comment]
Incomplete bug report.
