### ISSUE TITLE
Incorrect buffer_size / period_size for DSD_U32 ALSA output

### ISSUE THREAD

**Issue by coroner21** [MusicPlayerDaemon/MPD#1749]
### Describe the bug
It appears that mpd considers DSD samples to be hardcoded in 8bit / 1byte format with the respective sample rate (DSD_U8 format is assumed), however ALSA supports also DSD_U16 or DSD_U32 where the same stream is basically played but with lower sample rates / clock frequencies.

Due to the calculation of buffer_size in bytes in terms of buffer_time in microseconds this leads to very small buffer sizes for DSD_U32 format (mpd seems to assume that sample rate times 2 bytes is a full second for stereo, which for DSD_U32 is not the case but rather it is only a quarter of a second). For my DAC / embedded SBC I can configure the DSD formats ALSA accepts by recompiling the SOC codec driver. Below in the log section you find the output configuration snippets for the same song first with DSD_U8 and then with DSD_U32. Clearly the final buffer is way too small for DSD_U32 compared with DSD_U8 which seems to lead to playback issues.

## Expected Behavior
Regardless of the width of the DSD format output to ALSA the same buffer_size (in bytes) should be used for both 8bit and 32bit DSD playback.

## Actual Behavior
For DSD_U8 buffer_size is correct and corresponds to 500ms as expected. For DSD_U32 (all else equal), mpd sets up only a quarter of the default 500ms buffer. This tends to lead to more x-runs / issues with playback, maybe because mpd still assumes internally that the size in bytes actually corresponds to a full 500ms period.

## Version

Music Player Daemon 0.23.12 (0.23.12)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration

bind_to_address "any"
#bind_to_address "/var/lib/mpd/socket"

music_directory "/mnt/music"
#pid_file "/run/mpd/mpd.pid"
state_file "~/.config/mpd/mpdstate"
playlist_directory "~/.config/mpd/playlists"
sticker_file "~/.config/mpd/sticker.db"

connection_timeout "120"
max_connections "500"
#max_playlist_length "32768"
max_command_list_size "16384"

#audio_buffer_size "4MB"

restore_paused "yes"

database {
  plugin "proxy"
  host "helios4"
  port "6600"
}

audio_output {
  type "alsa"
  name "Alsa Botic"
  device "hw:0,0"
  mixer_control "Master"
  auto_resample "no"
}

## Log

**DSD_U8**
playlist: play 9:"Marvin Gaye/What’s Going On/01 What’s Going On.wv"
decoder_thread: probing plugin wavpack
decoder: audio_format=dsd64:2, seekable=true
alsa_output: opened hw:0,0 type=HW
alsa_output: buffer: size=128..1572864 time=362..4458232
alsa_output: period: size=64..786432 time=181..2229116
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=DSD_U8 (Direct Stream Digital, 1-byte (x8), oldest bit in MSB)
alsa_output: buffer_size=176400 period_size=44100
output: opened "Alsa Botic" (alsa) audio_format=dsd64:2
client: [0] command returned 0
playlist: queue song 10:"Marvin Gaye/What’s Going On/02 What’s Happening Brother.wv"

**DSD_U32**
playlist: play 9:"Marvin Gaye/What’s Going On/01 What’s Going On.wv"
alsa_output: opened hw:0,0 type=HW
alsa_output: buffer: size=128..393216 time=1451..4458232
alsa_output: period: size=64..196608 time=725..2229116
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=DSD_U32_LE (Direct Stream Digital, 4-byte (x32), little endian, oldest bits in MSB)
alsa_output: buffer_size=44100 period_size=11025
output: opened "Alsa Botic" (alsa) audio_format=dsd64:2
client: [0] command returned 0
playlist: queue song 10:"Marvin Gaye/What’s Going On/02 What’s Happening Brother.wv"

**Comment by coroner21** [comment]
Hmm, sorry, I am reading now that period_size and buffer_size is apparently in number of frames and not bytes, is this correct? In that case the behavior is actually already as expected since bytes for frames for DSD_U32 are simply four times the bytes for DSD_U8 and therefore in terms of bytes indeed the same buffer_size is used.

Still it seems odd that there are apparently significantly more playback issues for DSD_U32 in my setup than for DSD_U8 playback... Probably will need to do some further testing. Does anybody have any pointers what else might be causing more playback problems when using larger widths for DSD samples?

**Comment by MaxKellermann** [comment]
In ALSA, period size and buffer size are the number of frames, not bytes, that's true.

**Comment by coroner21** [comment]
OK, sorry for bothering, will dig further to see what is going on and potentially raise some other issue.
