### ISSUE TITLE
/var/log/mpd/mpd.log  and tmpfs

### ISSUE THREAD

**Issue by albanmeffre** [MusicPlayerDaemon/MPD#175]
hi 
mpd version :
0.19.21-1 from the raspbian/debian stretch repo

issue :
i changed /var/log to a tmpfs in /etc/fstab on my raspberrypi 3 in order to prevent sdcard wear out
mpd does not start if /var/log/mpd/mpd.log doesnot already exist in the filesystem,
but  /var/log is emptied at shutdown mounted as tmpfs !

how to reproduce :
clear /var/log/mpd and reboot -> error
touch /var/log/mpd/mpd.log then restart mpd service -> ok !

proposed solution :
if /var/log/mpd/mpd.log does not exist please just create it instead of throwing an error

thanks
A.M

**Comment by MaxKellermann** [comment]
Your MPD version is ancient and unsupported. Sorry. Ask the Raspbian project for help.

**Comment by albanmeffre** [comment]
hi thanks for your answer 
does the last version contain a fix for my issue ? 



Alban MEFFRE 
Ingénieur GEII / EE & Embedded Software Design Engineer 

RSI Video Technologies - RSI is now part of Honeywell 
Honeywell | Security & Fire (Automation and Control Solutions) 

25, rue Jacobi-Netter - 67200 STRASBOURG, France 
Office: +33 (0)3 88 18 30 23 



----- Mail original -----

De: "Max Kellermann" <notifications@github.com> 
À: "MusicPlayerDaemon/MPD" <MPD@noreply.github.com> 
Cc: "albanmeffre" <alban.meffre@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 19 Décembre 2017 11:09:30 
Objet: Re: [MusicPlayerDaemon/MPD] /var/log/mpd/mpd.log and tmpfs (#175) 



Your MPD version is ancient and unsupported. Sorry. Ask the Raspbian project for help.

**Comment by albanmeffre** [comment]
no such an entry in the change log 
my issue seems still to be an issue ;) 



----- Mail original -----

De: "alban meffre" <alban.meffre@laposte.net> 
À: "MusicPlayerDaemon/MPD" <reply@reply.github.com> 
Cc: "MusicPlayerDaemon/MPD" <MPD@noreply.github.com>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 19 Décembre 2017 14:01:50 
Objet: Re: [MusicPlayerDaemon/MPD] /var/log/mpd/mpd.log and tmpfs (#175) 

hi thanks for your answer 
does the last version contain a fix for my issue ? 



Alban MEFFRE 
Ingénieur GEII / EE & Embedded Software Design Engineer 

RSI Video Technologies - RSI is now part of Honeywell 
Honeywell | Security & Fire (Automation and Control Solutions) 

25, rue Jacobi-Netter - 67200 STRASBOURG, France 
Office: +33 (0)3 88 18 30 23 



----- Mail original -----

De: "Max Kellermann" <notifications@github.com> 
À: "MusicPlayerDaemon/MPD" <MPD@noreply.github.com> 
Cc: "albanmeffre" <alban.meffre@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 19 Décembre 2017 11:09:30 
Objet: Re: [MusicPlayerDaemon/MPD] /var/log/mpd/mpd.log and tmpfs (#175) 



Your MPD version is ancient and unsupported. Sorry. Ask the Raspbian project for help.

**Comment by mistepien** [comment]
Don't log to mpd.log but to syslog. This is much better option. BTW, mpd.log can grow and grow and tmpfs is not unlimited.

**Comment by albanmeffre** [comment]
i commented the corresponding line in mpd.conf 
hope it is enough 

----- Mail original -----

De: "mistepien" <notifications@github.com> 
À: "MusicPlayerDaemon/MPD" <MPD@noreply.github.com> 
Cc: "albanmeffre" <alban.meffre@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 22 Décembre 2017 14:09:42 
Objet: Re: [MusicPlayerDaemon/MPD] /var/log/mpd/mpd.log and tmpfs (#175) 



Don't log to mpd.log but to syslog. This is much better option. BTW, mpd.log can grow and grow and tmpfs is not unlimited.

**Comment by mistepien** [comment]
`log_file		"syslog"`

This what you need.
