### ISSUE TITLE
What characters in audio file names—aside from square brackets—are not recognized unescaped by mpd in .mpdignore files ?

### ISSUE THREAD

**Issue by iconoclasthero** [MusicPlayerDaemon/MPD#1761]
## Bug report
This isn't quite so much as a bug since the behavior appears to be well characterized for square brackets (though perhaps mpd could be modified to accept them unescaped), but rather a lack of documentation.  I've already put in a pull request to include this info in the docs, but I have yet to hear about any other characters which are incompatible with .mpdignore files.  

Greater and less than signs appear to be acceptable unescaped in .mpdignore files.

### Describe the bug
mpd does not recognize e.g., `24 - Taj Mahal -- [ talking ].flac` in an otherwise properly-formatted .mpdignore file because all square brackets in a file name must be individually escaped, e.g., `24 - Taj Mahal -- \[ talking \].flac` 

## Expected Behavior
Since there was no mention of this in the documentation, I did not expect that mpd would ignore the files with square brackets in the .mpdignore file

## Actual Behavior
MPD fails to recognize the file name in .mpdignore file

## Version
Music Player Daemon 0.23.5 (0.23.5)

## Configuration
not relevant f/this

## Log
not relevant f/this

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported.

**Comment by iconoclasthero** [comment]
I'm not sure I understand how it isn't the supported version when the documentation specifically instructs users to install from apt and, if you look, it is the current APT repo version for Ubuntu 22.10 (i.e., the most current version of Ubuntu)

`$ mpd --version|grep Music; apt show mpd|grep Version
Music Player Daemon 0.23.5 (0.23.5)

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Version: 0.23.5-1build7
`

So, where in the documentation are instructions for build from source so I can test this behavior in the newest version...which you haven't actually said does not exhibit this same behavior?

**Comment by MaxKellermann** [comment]
> when the documentation specifically instructs users to install from apt

Oh, let's read https://mpd.readthedocs.io/en/stable/user.html#installing-on-debian-ubuntu

"Debian and Ubuntu are infamous for shipping heavily outdated software. The MPD version in their respective stable releases are usually too old to be supported by this project."

Please don't waste my time with complaints like that.

**Comment by iconoclasthero** [comment]
You're right, I missed that.
The issue still occurs in the current git version (0.24) and it is horribly unstable.

It's a simple question:  what characters aren't recognized in a .mpdignore file?

Why are you wasting my time by not giving me a straight answer?
