### ISSUE TITLE
URL Error Reporting

### ISSUE THREAD

**Issue by trex101** [MusicPlayerDaemon/MPD#1762]
I use mpd/mpc in my internet radio application. I notice that some broken URLs won't play in mpd/mpc yet no error is thrown; wondering if there's a way these dead URLs can throw an error reliably.

**Comment by MaxKellermann** [comment]
Incomplete bug report

**Comment by trex101** [comment]
This is not a bug report. This is a request for assistance regarding mpd
error reporting. If you wish to close this issue, please explain what I'm
doing wrong and how to correct it. Thank you.
