### ISSUE TITLE
Can't call and download file to play it

### ISSUE THREAD

**Issue by entuccio** [MusicPlayerDaemon/MPD#1764]
## Expected Behavior
Can't play music on a synced folder with iCloud.  before update to Ventura the system automatically download file and play it.
Now it see thee file but it can't play.
mpc said:

## Actual Behavior
MPD error: Failed to decode /Users/daniele/Library/CloudStorage/GoogleDrive-info@foundminiatures.com/Il mio Drive/DaniSynologyNas/Musica.nosync/Adriano Celentano/Adriano Celentano/07 Si E Spento Il Sole.mp3; avformat_open_input() failed: Invalid argument

## Version
 0.23.12

## Configuration
music_directory		"/Users/daniele/Library/CloudStorage/GoogleDrive-info@foundminiatures.com/Il mio Drive/DaniSynologyNas/Musica.nosync"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log"
pid_file                "~/.mpd/mpd.pid"
state_file              "~/.mpd/mpdstate"
auto_update             "yes"
auto_update_depth       "2"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

auto_update "yes"

audio_output {
    type                  "osx"
    name                  "CoreAudio"
    mixer_type            "software"
}

bind_to_address         "127.0.0.1"
port                    "6600"

**Comment by MaxKellermann** [comment]
Please explain how the fact that you synced a folder with iCloud should be relevant here. What difference does MPD see? I don't have iCloud and I don't know how it works.

**Comment by entuccio** [comment]
Yes, dear, indeed, it was a problem by iCloud. Thank you for your assistance
Il 21 mar 2023, 15:09 +0100, Max Kellermann ***@***.***>, ha scritto:
