### ISSUE TITLE
Repeat mode not working

### ISSUE THREAD

**Issue by levdopa** [MusicPlayerDaemon/MPD#1765]
### Describe the bug
Repeat mode doesn't do anything

## Expected Behavior
While repeat mode is on, the current song keeps repeating after finishing untill I turn off repeat mode.

## Actual Behavior
A new song plays like when repeat mode is off.

## Version

Music Player Daemon 0.23.12 (0.23.12)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 tcp un

## Configuration

music_directory         "~/audio/music"
playlist_directory      "~/audio/playlists"

auto_update "yes"
bind_to_address "127.0.0.1"
restore_paused "yes"
max_output_buffer_size "16384"

audio_output {
        type "alsa"
        name "ALSA"
        mixer_type     "hardware"
}

audio_output {
    type                    "fifo"
    name                    "visualizer"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

## Log

config_file: loading file /home/levdopa/.config/mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.2.0
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
curl: version 7.87.0
curl: with OpenSSL/1.1.1t

**Comment by geneticdrift** [comment]
To repeat a single track you have to set both `repeat` and `single` to `1`.

Otherwise the whole queue is repeated.

This is a quote from the [protocol documentation](https://mpd.readthedocs.io/en/latest/protocol.html):
> repeat {STATE}
> 
> Sets repeat state to STATE, STATE should be 0 or 1.
>
>    If enabled, MPD keeps repeating the whole queue ([single mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-single) disabled) or the current song ([single mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-single) enabled).
>
>    If [random mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-random) is also enabled, the playback order will be shuffled each time the queue gets repeated.

**Comment by levdopa** [comment]
> To repeat a single track you have to set both `repeat` and `single` to `1`.
> 
> Otherwise the whole queue is repeated.
> 
> This is a quote from the [protocol documentation](https://mpd.readthedocs.io/en/latest/protocol.html):
> 
> > repeat {STATE}
> > Sets repeat state to STATE, STATE should be 0 or 1.
> > If enabled, MPD keeps repeating the whole queue ([single mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-single) disabled) or the current song ([single mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-single) enabled).
> > If [random mode](https://mpd.readthedocs.io/en/latest/protocol.html#command-random) is also enabled, the playback order will be shuffled each time the queue gets repeated.

That was why it wasen't working, thanks
