### ISSUE TITLE
access denied on android with nfs.

### ISSUE THREAD

**Issue by Tokariew** [MusicPlayerDaemon/MPD#1766]
### Describe the bug

Newer version of mpd on Android stopped working with NFS mount. I can no longer, use my mpd in satallite mode on Android.
Loaded songs skipped to the last and refuse to play.  The pc on the same network work fine with quite similiar config. 
My config worked for me still when the mpd.conf file was in media directory and not in `Android/data/org.musicpd/files/`

## Expected Behavior
The audio playback work

## Actual Behavior
Example error from mpc (via termux) on the phone
```
ERROR: Failed to decode nfs://192.168.0.113/media/btrfs/Media/Music/jamendo/gregoire-lourme/2016-1914-1918-never-forget/15-as-long-as-we-remember.flac; NFS: ACCESS denied. Required access r--. Allowed access ---
```

## Version
MPD from google play store in version 0.23.10
tried with f-droid version in version 0.23.12
Android 13.

## Configuration
```
music_directory "nfs://192.168.0.113/media/btrfs/Media/Music"
restore_paused "no"
max_output_buffer_size "32768"
replaygain "auto"

database {
    plugin "proxy"
    host "192.168.0.113"
}
```

My pc config in satellite mode:
```
#music_directory "/home/tokariew/NFS/Media/Music"
music_directory "nfs://192.168.0.113/media/btrfs/Media/Music"
playlist_directory "/home/tokariew/.local/share/mpd/playlist"
log_file "~/.local/share/mpd/mpd.log"
pid_file "~/.local/share/mpd/pid"
state_file "~/.local/share/mpd/mpdstate"
restore_paused "no"
max_output_buffer_size "32768"
replaygain "auto"


database {
    plugin "proxy"
    host "192.168.0.113"
}
audio_output {
    type "pipewire"
    name "Pipewire"
}


audio_output {
    type "pulse"
    name "Pulse"
}
```

**Comment by MaxKellermann** [comment]
This is an error generated by your NFS server, not by MPD. Maybe you have used the wrong file permissions.
