### ISSUE TITLE
Support `musicbrainz_releasegroupid` tag

### ISSUE THREAD

**Issue by JakeStanger** [MusicPlayerDaemon/MPD#1767]
## Feature request

The current set of supported MusicBrainz tags does not include the release group (`musicbrainz_releasegroupid`). While this is not essential (you can get the release group ID by looking up the release), this would be nice to have alongside the existing tags.

**Comment by jcorporation** [comment]
I also created a pull request for libmpdclient: https://github.com/MusicPlayerDaemon/libmpdclient/pull/103
