### ISSUE TITLE
In the case of a stream configured for mono, it plays on two channels. (with mono content)

### ISSUE THREAD

**Issue by DroidU** [MusicPlayerDaemon/MPD#1772]
### Describe the bug
If I send a mono stream to Icecast2, it is still played on 2 channels, but with mono content.
The following encoders are affected:
- LameEncoderPlugin
- TwolameEncoderPlugin
- ShineEncoderPlugin

## Expected Behavior
It should send the stream on 1 channel.

## Actual Behavior
It sends the stream on 2 channels instead of 1.

## Version

Music Player Daemon 0.23.12 (0.23.12)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [faad] aac
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null

Encoder plugins:
 null vorbis opus lame twolame flac

Input plugins:
 file curl ffmpeg

Playlist plugins:
 extm3u m3u pls flac

Protocols:
 file:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 epoll inotify ipv6 tcp un

## Configuration

zeroconf_enabled "no"
music_directory "/mscp/users/testuser/media"
playlist_directory "/mscp/users/testuser/media"
db_file "/mscp/users/testuser/autodj/1/tag_cache"
log_file "/mscp/users/testuser/autodj/1/mpd.log"
pid_file "/mscp/users/testuser/autodj/1/mpd.pid"
bind_to_address "127.0.0.1"
port "60362"
log_level "default"
audio_buffer_size "16384"
input {
plugin "curl"
verify_peer "no"
verify_host "no"
}
audio_output {
type "shout"
protocol "icecast2"
host "127.0.0.1"
port "8000"
mount "/live.mp3"
user "source"
password "test123"
encoding "mp3"
bitrate "128"
format "44100:16:1"
name ""
description ""
genre ""
url ""
public "0"
mixer_type "software"
}
audio_output_format "44100:16:1"
filesystem_charset "UTF-8"

**Comment by MaxKellermann** [comment]
Incomplete bug report. You decided to keep your log secret.

**Comment by DroidU** [comment]
The log does not contain any indication of this. The LameEncoderPlugin.cxx file, on the other hand, contains the fact that it is fixed to 2 channels:
PreparedLameEncoder::Open(AudioFormat &audio_format)
{
     audio_format.format = SampleFormat::S16;
     **audio_format.channels = 2;**

**Comment by MaxKellermann** [comment]
> The log does not contain any indication of this

If you ask for help, don't pretend you know it better than the people who you ask for help. Let them judge what contains an indication for something.

The code snipped you pasted proves that your assumption is wrong.

**Comment by DroidU** [comment]
If this is the attitude, there is no need to fix the bug. As in the case of my previous problem, you can delete and close this one as well. At most, this bug will remain.

**Comment by MaxKellermann** [comment]
Your attitude is that you refuse to follow the instructions that are necessary to enable others to help you.
