### ISSUE TITLE
Windows 10 64bit 0.23.12: libwinpthread-1.dll not found

### ISSUE THREAD

**Issue by eduardoeae** [MusicPlayerDaemon/MPD#1773]
MPD 0.23.12 fails to start on Windows 10 with error "libwinpthread-1.dll not found".
0.23.11 works.

This was reported previously in #507 and fixed in [98b29f6](https://github.com/MusicPlayerDaemon/MPD/commit/98b29f6d1c3d14ec2a6fd83f72c3b96f7a7ce171)

**Comment by roizcorp** [comment]
had the same issue this week, I suspect due to some windows update, took 0.23.9 binary in the meanwhile, seems to work

**Comment by MaxKellermann** [comment]
I don't know what caused the 0.23.12 build to be broken, but I can confirm that it is, and the current 0.23.13~git builds are not. Strange! In any case, it's fixed, and next time this happens, I'll try to bisect it.
