### ISSUE TITLE
Cannot set song duration through tags with addtagid

### ISSUE THREAD

**Issue by X-dark** [MusicPlayerDaemon/MPD#1774]
Hi,

Among tags, the duration seems to be defined:

https://github.com/MusicPlayerDaemon/MPD/blob/53ec02d5e968b0af3b01b42cdbb812a141d7cd6e/src/tag/Tag.hxx#L24

However there does not seem to be a way to set this through addtagid:

https://github.com/MusicPlayerDaemon/MPD/blob/53ec02d5e968b0af3b01b42cdbb812a141d7cd6e/src/tag/Type.hxx#L11-L48

As a result, external clients like upmpdcli that add streaming tracks to mpd, cannot set the duration and it stays at 0:00, until mpd start playing the track. This breaks other tools that relies on track duration as soon as they are in the playlist.

**Comment by MaxKellermann** [comment]
This bug report makes no sense because a song duration is not a tag.

**Comment by X-dark** [comment]
OK, then what would be the proper way to get the track to have its duration set as soon as it is added to the playlist?

**Comment by MaxKellermann** [comment]
Not at all. Let MPD figure it out automatically, as you already described.

**Comment by X-dark** [comment]
Yes, but as I have been trying to explain, the duration is unset until the track get played:

```
❯ mpc playlist --format='%position% - %artist% - %title% - %time%'
[...]
50 - Lars Danielsson - Intermedium -
51 - Lars Danielsson - III. Le Bagatelle -
52 - Lars Danielsson - IV. Scherzo -
[...]
```

```
❯ mpc
Lars Danielsson - III. Le Bagatelle
[playing] #51/62   1:32/13:38 (11%)
volume:100%   repeat: off   random: off   single: off   consume: off
```
