### ISSUE TITLE
MPD hangs on playing a flv file, when ‘single’ mode is on

### ISSUE THREAD

**Issue by deterenkelt** [MusicPlayerDaemon/MPD#178]
I know that playing flv is bad, but I guess many people have a folder, where they store random trash, that they play from time to time.

The issue is that I’ve added such a folder to playlist and after playing an flv file – it should be attached below –
[Earth Science - Whiskey Tango Foxtrot - YouTube.flv.zip](https://github.com/MusicPlayerDaemon/MPD/files/1584049/Earth.Science.-.Whiskey.Tango.Foxtrot.-.YouTube.flv.zip)
the mpd stopped playing.
ncmpcpp showed the playlist, but couldn’t navigate on it or send commands.
mpc could show status, but couldn’t send commands either.

I killed mpd process and started it with `--stderr --no-daemon`, but no related errors were there – only ‘OutputThread could not get realtime scheduling’ because I don’t have CONFIG_RT_GROUP_SCHED set.
mpd still wouldn’t start playing the list or accept commands from neither ncmpcpp nor mpc. 

I restarted X and tried again – no result.

Then I thought that if I make mpd skip that flv file I could probably make it work again, and changed the number of the ‘current’ parameter in the state file to the next one – and that helped. After I started mpd, it started playing, ncmpcpp could navigate (only after I reopened it, though) and mpc could send commands. 

I played that flv again, tried to Ctrl+H – I remember doing it too – but it didn’t trigger the problem. But once the file ended the mpd stopped and hanged again. So the issue is reproducible. The exact modes are ‘repeat’ and ‘single’.

**Comment by MaxKellermann** [comment]
What is your MPD version? Post a verbose log.

**Comment by deterenkelt** [comment]
version: http://sprunge.us/iWeg
verbose log: [log.zip](https://github.com/MusicPlayerDaemon/MPD/files/1584167/log.zip)

I started playing that flv file, then killed mpd, cleaned its log file, launched mpd again and let the file play till the end. When it’s finished playing and ncmpcpp lost connection to mpd, the log was on the 42217 line.

**Comment by MaxKellermann** [comment]
"500 Internal Server Error" on your version link. Which makes me wonder why you put this behind a link instead of posting it. This is the best demonstration why this is a bad idea.

**Comment by deterenkelt** [comment]
I can’t remember, wht I bothered to redownload that flv.
![you humans are a pain](https://user-images.githubusercontent.com/2245254/34323242-08d6f92c-e851-11e7-96b6-780768131297.png)
