### ISSUE TITLE
Upgrading vid.stab caused MPD to fail to start

### ISSUE THREAD

**Issue by BYT0723** [MusicPlayerDaemon/MPD#1791]
### Describe the bug
mpd don't work after upgrade package `vid.stab`, only `libvidstab.so.1.2` is available in `/usr/lib`.
![图片](https://user-images.githubusercontent.com/59989961/234206604-89b57621-bfc6-4eff-8810-c905c0adb4fe.png)
![图片](https://user-images.githubusercontent.com/59989961/234207000-6c1ff358-3391-41af-a78e-0222d6a0c706.png)

## Expected Behavior
mpd startup

## Actual Behavior
mpd don't work

## Version

sorry, mpd dont' work. i can't get version.

**Comment by BYT0723** [comment]
sorry, I just upgrade `vid.stab` to 1.1.1 and won't be able to find this library. I have downgrade `vid.stab` to 1.1 and MPD can start now.

**Comment by leigh123linux** [comment]
@BYT0723  You need to rebuild ffmpeg against the new vid.stab lib.

**Comment by BYT0723** [comment]
> @BYT0723 You need to rebuild ffmpeg against the new vid.stab lib.

It' worked. thanks a lot for your help.
