### ISSUE TITLE
[feature request] Add Support for work Tag 

### ISSUE THREAD

**Issue by loujine** [MusicPlayerDaemon/MPD#181]
As an amateur of classical music, I'm interested in having support of work tag(s) in mpd (so that I could  select all my recordings of sonata X or symphony Y easily)

As far as I can see from [picard tag mappings](https://picard.musicbrainz.org/docs/mappings/), there's no standard tag for works. I started implementing support for MUSICBRAINZ_WORKID in my [fork](https://github.com/loujine/MPD/commit/42959982a986b5eab4c0d6d8da41a283bb15a8a7) and checked tag_cache was filled properly.

Did someone already try to implement this in mpd / libmpd / clients?
Is there an interest in merging my branch later in master? (I understand the mpd project is conservative about taking into account custom tags)

**Comment by MaxKellermann** [comment]
Do we need a special tag for "work"? I thought "album" is the contemporary-music equivalent for what "work" used to be.

**Comment by loujine** [comment]
Note quite equivalent, an album often regroups different works/compositions (depending on their duration)

Granted, a "work" makes sense mostly for classical music, where the same composition written centuries ago is played by different performers on different albums. In pop music probably the only use-cases are for live performances and cover songs, where you might want to have the same tag to link your track to the original recording.

For pop usually the track name tag would be sufficient, for classical it is usually insufficient due to the various ways to write the track name (different languages, different numberings and catalogs, with or without tonality, or opus number, etc.). Thus my wish to have the unique MusicBrainz identifier as you already provide for artist/track/album

**Comment by MaxKellermann** [comment]
Ok, I understand. Do you want to have a machine-readable "work id", or a human-readable "work name"?

**Comment by MaxKellermann** [comment]
I read your commit and it looked pretty good, so I decided to just merge it. Next time, just send a pull request...

**Comment by loujine** [comment]
Great, thanks
Actually I didn't think the job was ready since I didn't touch the plugins (because it looked like libmpd had to be modified at the same time)

**Comment by MaxKellermann** [comment]
All decoder plugins which parse tags by the standard name list are supported automatically.
True, libmpdclient needs to support this, but that's a different project and a different pull request. Of course you're welcome to write this.
(Don't say libmpd - that's another project.)

**Comment by loujine** [comment]
OK, thanks for the explanation. I'll take a look at libmpdclient and submit a PR if I can build and test it
