### ISSUE TITLE
Plans for the next release

### ISSUE THREAD

**Issue by FtZPetruska** [MusicPlayerDaemon/MPD#1813]
Since the latest release (v0.23.12) does not build using fmt 10 (#1810, #1807), and since support for fmt 10 is added with large changes (move from custom `StringView` to `std::string_view`, and additional smaller patches), is there an expected timeframe for a new release ?

Alternatively, if v0.24 is not planned to be released soon, would there be an interest for a PR targeting the v0.23.x branch adding fmt 10 support with the goal of making a v0.23.13 release?

Thank you for your understanding.

**Comment by MaxKellermann** [comment]
I wanted to release 0.24 instead of doing another 0.23 bug fix release, but this is taking longer than I wanted (as always), so I'm going to release 0.23.13 very soon.
