### ISSUE TITLE
Fail to list songs in a playlist whose name has spaces

### ISSUE THREAD

**Issue by fingerknight** [MusicPlayerDaemon/MPD#1830]
It seems that `mpc playlist <name with spaces>` does not work.

![image](https://github.com/MusicPlayerDaemon/MPD/assets/56252828/30a41735-4696-4bb3-854e-7ef9d46fc23d)

( `mpc-unix` is just a alias for `mpc --host=/path/to/unix-socket`)

I have tried that four ways but failed. Is there a way to deal with this?  I have search in Issues and Discussions, no relative reports.

**Comment by MaxKellermann** [comment]
This is a bug in how you implemented the alias. Your alias splits parameters instead of passing them as-is with spaces.

**Comment by fingerknight** [comment]
Well, it truly is. The original command works well. I should try that before. Thanks :)
