### ISSUE TITLE
mpd changes permissions/owner for file on write

### ISSUE THREAD

**Issue by voskresenie** [MusicPlayerDaemon/MPD#1833]
### Describe the bug
When modifying a playlist (other than appending), mpd changes permissions of the file, both owner (possibly expected/desired) and permissions.

## Initial conditions
mpd user (`mpd`) has secondary group `audio` and write permissions to both directory and file via group (but not via user)
```
$ id -gn mpd   # primary group
mpd
$ id -Gn mpd   # all groups
mpd audio
$ ls -ld /mnt/media/playlists
drwxrwxr-x 2 root audio [filesize+datetime] /mnt/media/playlists
$ ls -l /mnt/media/playlists/my_playlist.m3u
-rw-rw-r-- 1 root audio [filesize+datetime] /mnt/media/playlists/my_playlist.m3u
```
## Expected Behavior
**After modifying playlist in any way:**
```
$ ls -l /mnt/media/playlists/my_playlist.m3u
-rw-rw-r-- 1 root audio [filesize+datetime] /mnt/media/playlists/my_playlist.m3u
```
Ideally, mpd should not modify the user/group owners of the playlist, nor should it modify the permissions.

## Actual Behavior
**After adding to playlist (with no rearrangement or deletion):**
```
$ ls -l /mnt/media/playlists/my_playlist.m3u
-rw-rw-r-- 1 root audio [filesize+datetime] /mnt/media/playlists/my_playlist.m3u
```
Note that owner and permissions are unchanged.

**After modifying playlist in any way other than appending:**
```
$ ls -l /mnt/media/playlists/my_playlist.m3u
-rw-r--r-- 1 mpd mpd [filesize+datetime] /mnt/media/playlists/my_playlist.m3u
```
Instead, it changes the owners to mpd (user) and mpd's primary group, and changes permissions to 644.

## Why this matters
I intentionally have set group owner and group write permissions so that I can share a library and playlist directory over the network, such that I can run mpd as a system-level service on my server (as user mpd), and as a user-level service on my laptop (as my own user). Ideally, modifying the playlist wouldn't change the permissions OR owner, but I can resolve the change of owner by making mpd's primary group `audio` and adding my personal user to the group `audio` as well. However, that doesn't work if mpd changes the permissions of the playlist file to remove write permissions for the owner group.

## Suspected root cause
I suspect mpd is modifying the original playlist file on add, but overwriting the playlist file on reorder or deletion. I believe this because:

* When adding to a playlist, the mpd running user must have write permissions (user, group, or world) to the file itself (regardless of write permissions for the directory) or there is an error (see first error in logs below). However, if the user has write permissions for the file, it successfully writes to the playlist file without modifying owning user/group or permissions. This is consistent with POSIX permissions/behavior for *modifying* a file.

* In contrast, when otherwise modifying a playlist (reordering or removing tracks), the mpd running user must have write permissions (user, group, or world) for the directory (regardless of write permissions for the file) or there is an error (see second error in logs below). However, if the user has write permissions for the directory, it successfully writes the playlist file but modifies owning user/group and permissions. This is consistent with POSIX permissions/behavior for *writing a new file* (potentially on top of an existing file).

## Version
0.23.13

## Configuration
```
playlist_directory        "/mnt/media/playlists"
user                      "mpd"
```

## Log
**When mpd does not have write permissions to the file (/mnt/media/playlists/my_playlist.m3u):**
```
Jun 06 13:01 : exception: Failed to append to /mnt/media/playlists/my_playlist.m3u: Permission denied
```
**When mpd does not have write permission to the directory (/mnt/media/playlists):**
```
Jun 06 13:02 : exception: Failed to create /mnt/media/playlists/my_playlist.m3u: Permission denied
```

**Comment by GioF71** [comment]
I don't want to anticipate any answer from project members, but why don't you run mpd with the user that is user for file sharing?
The audio group is required for playing to alsa devices and I do not believe it should be used for your use case.
It is not a hard requirement to start mpd with user mpd. You might use the same user used for samba or nfs shares. Doing so mpd will probably not change the group of those files or it will set to the primary group for that user. So you will be able to read/modify the files through the file sharing service.
If alsa is needed, you might want to add 'audio' as an additional group to the user that runs mpd.

**Comment by MaxKellermann** [comment]
This isn't a bug at all, and MPD doesn't need to fix anything.

When appending to a playlist, MPD opens the existing file with O_APPEND, thus only the contents of an existing file are changed.

Other operations require rewriting the whole file, which MPD does in a way that is atomic (= reliable without losing data, no matter what) - it first writes to a temporary new file, then when writing that file has completed, it replaces the old file with that temporary file.

This is a new file where the usual rules for new files apply: you need write permission to the containing directory, the file will be owned by the user that MPD runs as, and by the group that MPD runs as (unless your directory has g+s), and MPD's umask applies.

If you want it any other way, run MPD with a different umask and set g+s on the directory.
