### ISSUE TITLE
macOS: after sleep, awaken, and spending the buffer, MPD needs play to resume URL

### ISSUE THREAD

**Issue by entonio** [MusicPlayerDaemon/MPD#1835]
### Describe the bug

- MPD is playing a URL
- macOS goes to sleep 
- MPD stops being heard
- macOS resumes
- MPD immediately resumes being heard, 
  presumably playing what it had in its buffer before going to sleep
- Wait 30 seconds or similar (for the buffer to run out?)

## Expected Behavior

- MPD restores the connection to the URL to keep playing

## Actual Behavior

- MPD doesn't seem to restore the connection
- If MPD is sent a play command, then it resumes playing, 
  so there doesn't seem to be any inconsistent state, 
  just a broken connection.

I understand this is more a question for a forum, but I couldnt find a discussion anywhere.

## Version

Music Player Daemon 0.23.12 (0.23.12)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local nfs curl

Neighbor plugins:
 upnp

Decoders plugins:
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe ao openal osx httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg nfs

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// nfs:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// smb:// srtp://

Other features:
 icu ipv6 tcp un

## Configuration

 
bind_to_address "any"
port "32123"

volume_normalization "yes"

audio_output {
  type                  "osx"
  name                  "CoreAudio"
  mixer_type            "software"
}

**Comment by MaxKellermann** [comment]
Indeed a duplicate

**Comment by entonio** [comment]
I don't see that it's a duplicate. The underlying cause may or may not be the same, but the mismatch between actual and expected behaviour doesn't seem to be the same as in the other issue, and hence not solved by any of the proposed solutions there. (I may be wrong.)
