### ISSUE TITLE
albumart is returning "Access denied"

### ISSUE THREAD

**Issue by daveola** [MusicPlayerDaemon/MPD#1838]
### Describe the bug

Connecting to the MPD socket the albumart command is giving "Access denied" with the full path or "No file exists" with the relative path.

Example:  (Anything prefixed with '>>>> ' is user input)

>>>> telnet localhost 6600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.23.5
>>>> currentsong
file: Amazon/Adam_Ant/2009-The_Very_Best_Of/02-Goody_Two_Shoes.mp3
Last-Modified: 2020-11-03T07:27:27Z
Format: 44100:24:2
Artist: Adam Ant
AlbumArtist: Adam Ant
Title: Goody Two Shoes
Album: The Very Best Of
Track: 2
Date: 2009
Genre: Alternative Rock
Composer: Marco Pirroni
Disc: 1
Time: 210
duration: 209.737
Pos: 6304
Id: 6305
OK
>>>> albumart Amazon/Adam_Ant/2009-The_Very_Best_Of/02-Goody_Two_Shoes.mp3 0
ACK [50@0] {albumart} No file exists
>>>> albumart /data/Music/Amazon/Adam_Ant/2009-The_Very_Best_Of/02-Goody_Two_Shoes.mp3 0
ACK [4@0] {albumart} Access denied

This particular example has both a Cover.jpg in the song directory as well as an embedded image in the MP3, though the problem is not specific to this mp3 file, I get the same error on all files.

## Expected Behavior

Return the albumart as binary

## Actual Behavior

Access denied error

## Version

Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao oss openal pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration

music_directory		"/data/Music"
playlist_directory		"/data/Music/Playlist"
db_file			"/var/lib/mpd/tag_cache"
log_file			"/var/log/mpd/mpd.log"
pid_file			"/run/mpd/pid"
state_file			"/var/lib/mpd/state"
sticker_file                   "/var/lib/mpd/sticker.sql"
user				"dave"
bind_to_address			"localhost"
metadata_to_use "+comment"
input {
        plugin "curl"
}
input {
        enabled    "no"
        plugin     "qobuz"
}
input {
        enabled      "no"
        plugin       "tidal"
}
decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
}
decoder {
        plugin        "wildmidi"
        enabled       "no"
        #config_file "/etc/timidity/timidity.cfg"
}
audio_output {
	type		"pulse"
	name		"My Pulse Output"
	server  "localhost"
}
filesystem_charset		"UTF-8"

## Log

Jun 21 10:17 : client: [1] process command "albumart Amazon/Adam_Ant/2009-The_Very_Best_Of/02-Goody_Two_Shoes.mp3 0"
Jun 21 10:17 : client: [1] command returned 3
Jun 21 10:18 : client: [1] process command "albumart /data/Music/Amazon/Adam_Ant/2009-The_Very_Best_Of/02-Goody_Two_Shoes.mp3 0"
Jun 21 10:18 : exception: Access denied
Jun 21 10:18 : client: [1] command returned 3

**Comment by jcorporation** [comment]
Looks like the file permissions are incorrect.

**Comment by daveola** [comment]
The permissions for all my covers is the same user/permissions as all my music.

**Comment by daveola** [comment]
For the example in the log:

```
% pwd
/data/Music/Amazon/Adam_Ant/2009-The_Very_Best_Of
% ls -l
total 7740
7708 -rw-r--r-- 1 dave dave 7889317 Nov  2  2020 02-Goody_Two_Shoes.mp3
  32 -rw-r--r-- 1 dave dave   32176 Oct 13  2020 Cover.jpg

```

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported. Closing without looking any further.

**Comment by daveola** [comment]
This is the current version of mpd that is distributed with Ubuntu - does mpd have any plans of pushing an update forward?

**Comment by MaxKellermann** [comment]
How does this "pushing an update forward" look like, in your imagination?

Did you not know that it is against Ubuntu's policy to ship bug fixes to their users?
We can't go around this policy, and we can't "push" something to an external entity like Ubuntu/Canonical. All we can do is publish bug fixes, and it's up to everybody else to download those bugfixes from us. It's "pull" by you (and Ubuntu etc.), because there's no way we can "push" anything. "Pushing" isn't how open source works.

In any case, looking at bug reports of old MPD versions is a waste of our precious time, that's why such bug reports will be closed without even looking at them.
If you use a known-buggy MPD version, you'll have bugs! All versions but the latest are known-buggy (of course, because the latest release contains fixes for those known bugs).
