### ISSUE TITLE
Cant get MPD working (mpd trys to use audio output that isnt in the config file)

### ISSUE THREAD

**Issue by Ghoost666** [MusicPlayerDaemon/MPD#1840]
Hello i tried to setup MPD on fedora 38 workstation but i got a strange issue... after figuring out that i need to run mpd as user and making config files under ~/.mpd/mpd.conf, mpd starts and i set in the config file this :
```
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
```

mpd still shows this error when i try to play something:
`ERROR: Failed to enable output "My Pulse Output" (pulse); pa_context_connect() has failed: Connection refused
`

where does MPD get this audio output from? ... the config file i set up seems to work otherwise ... for example i set db file also to be at ~/.mpd/ and the db file also got created under this directory

but other strange issue is that i set music path to ~/Musik ... but mpc update doesnt seem to generate any database, as if the folder is empty... im not sure how to troubleshoot this further since i dont know where MPD gets the audio output config from

**Comment by MaxKellermann** [comment]
Don't delete the bug reporting template.

**Comment by Ghoost666** [comment]
Nevermind.. a reboot fixed both issues
