### ISSUE TITLE
Distortion of high frequency (>10kHz) sound

### ISSUE THREAD

**Issue by electroworlder** [MusicPlayerDaemon/MPD#1846]
### Describe the bug
MPD produces distorted sound. Starting at around 8kHz and very noticeable from 12kHz upward, a sine wave appears progressively amplitude modulated, as if a second frequency has been added.  While easy to measure, the problem is difficult to hear in source music,  presenting as a reduction in realism of well recorded cymbals. The modulation frequency can easily be heard in a 12kHz pure sine wave. I am running mpd on a Beaglebone black with Debian bullseye, but with the buster kernel and outputting via USB to a Navman ODAC. The same behaviour was observed under Debian buster.
I would like to know if anyone else is observing this behaviour, and whether there are any fixes/work arounds, as my system is based on mpd, and it will be a lot of difficult work for me to write mpd out of the system.

## Expected Behavior
I expect a sine wave at 1.00V RMS and with no distortion or modulation to be generated for sine wave sources from 5Hz through to just before 20kHz. This is what I get when playing the same files using the "play" command (part of the sox package) on the same system. 

## Actual Behavior
Please see attached file, "12kHz sine wave.pdf" being a snap shot from my scope. A sine wave was created at -6db using sox and this is the output from mpd. It can be seen that the signal is attenuated to 760mV RMS, where I was expecting 1.00V RMS and that the signal has an amplitude modulation of around 650Hz where there should be no modulation.  I get this same result when playing file formats .wav, .flac, .mp3 and .ogg.  I imagine a good sound card and audacity would find the same problem.

## Version

Music Player Daemon 0.22.6 (0.22.6)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration
uname -a
Linux beaglebone 4.19.94-ti-r42 #1buster SMP PREEMPT Tue Mar 31 19:38:29 UTC 2020 armv7l GNU/Linux

**_< I have deleted the comment lines for the sake of clarity>_**

playlist_directory		"/mnt/sdcard/mpd/var/playlists"
db_file			    "/mnt/sdcard/mpd/var/tag_cache"
log_file			"/mnt/sdcard/mpd/log/mpd.log"
pid_file			"/mnt/sdcard/mpd/run/pid"
state_file			"/mnt/sdcard/mpd/var/state"
sticker_file                   "/mnt/sdcard/mpd/var/sticker.sql"

user				"debian"
group                          "audio"
bind_to_address		"localhost"

input {
        plugin "curl"
}

input {
        enabled    "no"
        plugin     "qobuz"
}

input {
        enabled      "no"
        plugin       "tidal"
}

decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
}

audio_output {
	type		"alsa"
	name		"My ALSA Device"
}

filesystem_charset		"UTF-8"

## Log

This problem does not appear to generate any messages to the log.

[12kHz sine wave.pdf](https://github.com/MusicPlayerDaemon/MPD/files/12074706/12kHz.sine.wave.pdf)

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported. This bug report will be closed without looking at any details.
