### ISSUE TITLE
Starting playback of a large Opus file in MP4 container is slow

### ISSUE THREAD

**Issue by jarnos** [MusicPlayerDaemon/MPD#1872]
### Describe the bug

If I have a large Opus file, say several hours of audio, in MP4 container, it takes long time to start playback.

## Expected Behavior

Playback should start immediately

## Actual Behavior

It starts after several seconds, maybe even minutes, depending on computer speed and file size. After it starts I can seek without a delay.

## Version

Music Player Daemon 0.22.11 (0.22.11)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration

music_directory		"/var/lib/mpd/music"
playlist_directory		"/var/lib/mpd/playlists"
db_file			"/var/lib/mpd/tag_cache"
log_file			"/var/log/mpd/mpd.log"
state_file			"/var/lib/mpd/state"
sticker_file                   "/var/lib/mpd/sticker.sql"
user				"mpd"
bind_to_address			"any"
restore_paused "yes"
input {
        plugin "curl"
}
decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
}
decoder {
        plugin        "wildmidi"
        enabled       "no"
        #config_file "/etc/timidity/timidity.cfg"
}
audio_output {
	type		"httpd"
	name		"My HTTP Stream"
	enabled		"no"			# "no" = do not start on startup
	encoder		"opus"
	port		"8000"
	bitrate		"auto"                  # "auto", "max" or rate bits per second
	complexity	"10"			# setting for opus encoder 1-10
	signal		"music"			# Valid values are “auto” (the default), “voice” and “music”
	format		"48000:16:2"
	max_clients	"1"
}
audio_output {
	type		"pulse"
	name		"Optiplex Pulse Output"
	server		"jarnos-OptiPlex-9010.local"
}
audio_output {
        type            "pulse"
        name            "Compaq Pulse Output"
	enabled		"no"
        server          "jarnos-8510w.local"
}
resampler {
	plugin "soxr"
	quality "very high"
}
filesystem_charset		"UTF-8"

## Log

Default log_level:

Oct 01 17:11 : player: played "streaming/wappuradio-2023-04-27T0658+0300.m4a"
Oct 01 17:12 : ffmpeg/opus: Could not update timestamps for skipped samples.

Verbose log_level:
Oct 01 17:21 : player: played "streaming/wappuradio-2023-04-27T0658+0300.m4a"
Oct 01 17:21 : zeroconf: No global port, disabling zeroconf
Oct 01 17:21 : state_file: Loading state file /var/lib/mpd/state
Oct 01 17:21 : decoder_thread: probing plugin ffmpeg
Oct 01 17:21 : playlist: queue song 3:"streaming/wappuradio-2023-04-27T2359+0300.m4a"
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'ftyp' parent:'root' sz: 28 8 980676876
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ISO: File Type Major Brand: isom
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'free' parent:'root' sz: 8 36 980676876
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdat' parent:'root' sz: 980672328 44 980676876
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'moov' parent:'root' sz: 4512 980672372 980676876
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mvhd' parent:'moov' sz: 108 8 4504
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: time scale = 1000
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'trak' parent:'moov' sz: 4298 116 4504
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'tkhd' parent:'trak' sz: 92 8 4290
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'edts' parent:'trak' sz: 36 100 4290
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'elst' parent:'edts' sz: 28 8 28
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].edit_count = 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: duration=61292013 time=312 rate=1.000000
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdia' parent:'trak' sz: 4162 136 4290
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdhd' parent:'mdia' sz: 44 8 4154
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'hdlr' parent:'mdia' sz: 45 52 4154
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ctype=[0][0][0][0]
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stype=soun
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'minf' parent:'mdia' sz: 4065 97 4154
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'smhd' parent:'minf' sz: 16 8 4057
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'dinf' parent:'minf' sz: 36 24 4057
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'dref' parent:'dinf' sz: 28 8 28
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unknown dref type 0x206c7275 size 12
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stbl' parent:'minf' sz: 4005 60 4057
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsd' parent:'stbl' sz: 91 8 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: size=75 4CC=Opus codec_type=1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: audio channels 2
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: version =0, isom =1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'dOps' parent:'stsd' sz: 19 8 39
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'btrt' parent:'stsd' sz: 20 27 39
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stts' parent:'stbl' sz: 24 99 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].stts.entries = 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: sample_count=3064601, sample_duration=960
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsc' parent:'stbl' sz: 40 123 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].stsc.entries = 2
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsz' parent:'stbl' sz: 20 163 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: sample_size = 320 sample_count = 3064601
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stco' parent:'stbl' sz: 3760 183 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'sgpd' parent:'stbl' sz: 26 3943 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'sbgp' parent:'stbl' sz: 36 3969 3997
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 0, offset 2c, dts 0, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 1, offset 16c, dts 960, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 2, offset 2ac, dts 1920, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 3, offset 3ec, dts 2880, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 4, offset 52c, dts 3840, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 5, offset 66c, dts 4800, size 320, distance 0, keyframe 1
Oct 01 17:21 : ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, sample 6, offset 7ac, dts 5760, size 320, distance 0, keyframe 1
...

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported.

**Comment by jarnos** [comment]
Oh, but I hope the issue is fixed in a newer, supported release. I did not find anything matching in the changelog.
