### ISSUE TITLE
crossfade causes the music to pause

### ISSUE THREAD

**Issue by mantarimay** [MusicPlayerDaemon/MPD#1873]
### Describe the bug
crossfade causes the music to pause

## Expected Behavior
crossfade work properly

## Actual Behavior
crossfade causes the music to pause

## Version

[0.23.13+937~git.491cc8f5](https://build.opensuse.org/package/show/home:mantarimay:apps/mpd)

## Configuration

[mpd.conf](https://0x0.st/HW_P.conf)

## Screen Record

https://github.com/MusicPlayerDaemon/MPD/assets/42089808/96335da2-e77c-4ae5-8a0c-c5b1c8237c0a

**Comment by MaxKellermann** [comment]
Refusing to work on your bug report because you refused to post your log and deleted the section from the bug reporting template.

**Comment by mantarimay** [comment]
@MaxKellermann done insert log

**Comment by mantarimay** [comment]
@MaxKellermann sorry i think i missing  `--stderr `

```output: Failed to filter for "Pulse Output" (pulse): Cannot cross-fade format dsd
output: closed "Pulse Output" (pulse)
output: Failed to filter for "my_fifo" (fifo): Cannot cross-fade format dsd
output: closed "my_fifo" (fifo)
exception: Failed to open audio output```

**Comment by mantarimay** [comment]
output if i disable my fifo
```decoder_thread: probing plugin dsdiff
decoder: audio_format=dsd64:2, seekable=true
output: Failed to filter for "Pulse Output" (pulse): Cannot cross-fade format dsd
output: closed "Pulse Output" (pulse)
exception: Failed to open audio output```
