### ISSUE TITLE
Sign up for GitHub sponsors or similar

### ISSUE THREAD

**Issue by lpil** [MusicPlayerDaemon/MPD#1882]
Hello!

I'm enjoying this software and would love to be able to sponsor all the work you have done here while I continue to use it. :)

Thanks,
Louis

**Comment by lpil** [comment]
My stance on these sponsorship things is that they are not a way to solve problems, or to incentivise work, but just a way for folks like me to say thank you without further expectation. I totally understand your perspective though! Thank you again for mpd 💜

**Comment by jcorporation** [comment]
Should we start a discussion how we can support the project elsewhere? Code contributions and so on? A more agile community of mpd supporters would be great, let us create them!
