### ISSUE TITLE
Playback randomly pauses with alsa snd_pcm_writei() file descriptor in bad state

### ISSUE THREAD

**Issue by pacien** [MusicPlayerDaemon/MPD#1891]
### Describe the bug

Playback randomly pauses between tracks with an error in the logs.
Resuming playing manually works fine (without having to restart mpd).

Symptoms seem somewhat similar to those described in issue #1874,
also involving ALSA, but with a simpler configuration here.

Although I do not see any underrun here.
Increasing the buffer time does not seem to impact the issue.

This is happening with a generic USB sound card (ICUSDAUDIO7D).
No other program is using the audio output on the machine.

I suspect some kind of race condition with the hardware(?)
Is there a way to make mpd more "resilient" to this,
by automatically retrying playing a set number of times?

## Expected Behavior

Playback shouldn't be interrupted.

## Actual Behavior

Playback is paused.
The following error appears in MPD's logs:

```
output: Failed to play on "default" (alsa): snd_pcm_writei() failed: File descriptor in bad state
exception: Failed to open audio output
```

## Version

Music Player Daemon 0.23.13 (0.23.13)
Running on OpenWRT 23.05.0 (Raspberry Pi B, ARM v6l).
Using ffmpeg as decoder.

## Configuration

(File locations and permissions/passwords omitted).

```
audio_output {
  type "alsa"
  name "default"
  mixer_type "software"
}
```

**Comment by MaxKellermann** [comment]
A strace of all threads when this occurs would be necessary to analyze this. Right now, I can only guess that this is a bug in your sound card driver, because I have never seen this error anywhere before.
