### ISSUE TITLE
openwrt上安装mpd报错

### ISSUE THREAD

**Issue by 725216** [MusicPlayerDaemon/MPD#1903]
报错：
Configuring mpd-mini.
mkdir: can't create directory '': No such file or directory
BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.

Usage: chown [-Rh]... USER[:[GRP]] FILE...

Change the owner and/or group of FILEs to USER and/or GRP

        -h      Affect symlinks instead of symlink targets
        -R      Recurse
集成到固件也无法正常使用

**Comment by MaxKellermann** [comment]
I have no idea what this is about, but it's certainly not about MPD.
