### ISSUE TITLE
Add extra info to subsystem changes.

### ISSUE THREAD

**Issue by kori** [MusicPlayerDaemon/MPD#194]
My request is specifically about the player subsystem. It'd be nice to know what actually changes, whether it was a track play/stop/seek.

Rationale: Whenever the playlist is cleared and you start playing a new track, the player subsystem fires twice, once when the track starts playing, and once more, which I assume is mpd seeking to 00:00.

That's hard/impossible to handle in programs because the metadata for both subsystem updates is the same.

**Comment by MaxKellermann** [comment]
You can easily keep track of that by comparing old/new values.

**Comment by kori** [comment]
As stated in the original comment, the old/new values are the same for both of the subsystem updates, so that doesn't work.

Unless you mean from before the playlist clearing.

**Comment by MaxKellermann** [comment]
Yes, it does work. If no value relevant for you has changed, then the event that occurred is not relevant for you. Just ignore that idle event.
