### ISSUE TITLE
WASAPI plugin does not build under LLVM's lib++

### ISSUE THREAD

**Issue by neheb** [MusicPlayerDaemon/MPD#1948]
This is under MSYS2's CLANG32 and CLANG64 backends that use clang and LLVM's libc++.

## Log
```
../src/output/plugins/wasapi/WasapiOutputPlugin.cxx:173:15: error: no member named 'hardware_destructive_interference_size' in namespace 'std'
  173 |         alignas(std::hardware_destructive_interference_size) std::atomic<Status> status =
      |                 ~~~~~^
../src/output/plugins/wasapi/WasapiOutputPlugin.cxx:175:15: error: no member named 'hardware_destructive_interference_size' in namespace 'std'
  175 |         alignas(std::hardware_destructive_interference_size) struct {
      |                 ~~~~~^
```

**Comment by MaxKellermann** [comment]
Convince me that this is a MPD problem and not a LLVM bug.

**Comment by neheb** [comment]
I mean…MPD is using unimplemented functions in libc++. Which would also be an issue on the BSDs (not sure if supported).

**Comment by MaxKellermann** [comment]
This doesn't convince me at all. You didn't even try to. You explained that libc++ is lacking an implementation of a C++ standard library function, and this is obviously a libc++/LLVM problem.
