### ISSUE TITLE
autogen.sh Java warning

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#195]
Debian testing x_64

$ git clone https://github.com/MusicPlayerDaemon/MPD.git
$ cd MPD
$ ./autogen.sh
configure.ac:27: installing 'build/compile'
configure.ac:87: installing 'build/config.guess'
configure.ac:87: installing 'build/config.sub'
configure.ac:12: installing 'build/install-sh'
configure.ac:12: installing 'build/missing'
Makefile.am: installing 'build/depcomp'
parallel-tests: installing 'build/test-driver'
Makefile.am:322: warning: variable 'JAVA_SOURCES' is defined but no program or
Makefile.am:322: library has 'JAVA' as canonical name (possible typo)

**Comment by MaxKellermann** [comment]
Caused by fbdb8b406e79d282ed0c5b7fde723fcfbde43d28 because automake grabs all `*_SOURCES` variables and insists that there must be an output object for it.
