### ISSUE TITLE
tidal token

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#196]
There are three parameters of brand new tidal plugin: token, username and password.
First question is whether this example section is ok, and second: **how to find out token**?
Till now I was using exclusively tidal via website using chromium web browser.

input {
    plugin "tidal"
    username "YOUR_LOGIN"
    password "YOUR_PASSWORD"
    token "WTF"
}

**Comment by MaxKellermann** [comment]
This looks ok, and the token needs to be obtained from Tidal. It is meant to be specific to the product/software playing back Tidal songs, and all I have (for development) is a token from the sponsor of this feature, but I can't publish that token.

If you want to help, please contact Tidal and ask them whether assigning a token for the MPD project would be acceptable for them. The problem may be, of course, that this token is public because it's in the public source code; but tokens can just as well be extracted from proprietary software, just not so easily.

**Comment by mistepien** [comment]
I wrote to Tidal about problem. Now I have to wait for answer.

**Comment by mistepien** [comment]
This is the answer. I never used term "login token". I wrote to them: "Besides login and password I need also token".

> We do not provide any additional login tokens,
beside a username and password.

> You  can listen to TIDAL at listen.tidal.com,
or via our player, which can be downloaded
via tidal.com/download.

> I`d  reach back to the developer of the MPD
and advise them that TIDAL does not provide tokens.

It seems to me that there is something very not ok with them.
I will have try qobuz. At least they do not treat their customers as
idiots:
https://github.com/Qobuz/api-documentation
There is information how to obtain app_id and app_secret.

**Comment by MaxKellermann** [comment]
Obviously, that Tidal guy has no idea what he's talking about. From the [Tidal developer documentation](http://developer.tidal.com/technical/) (developer login required):

> To use the TIDAL API you must have an application token. This will be issued to you by your TIDAL contact.

**Comment by mistepien** [comment]
Ok, I've reiterated my request. Any way maybe you wil do it, too? Don't you, as a developer, have distinct contact to tidal? For regular customers there is only clueless staff.

**Comment by mistepien** [comment]
This what I got from tidal:

> We develop login information for approved developers only, not individual subscribers.

Now it seems that only you can get token for MPD. Otherwise
tidal plugin will be functional only for you :D

**Comment by mistepien** [comment]
And BTW it means that when you obtain token you can
hardcode token in code and simplify tidal section in mpd.conf
with cutting of token parameter.

**Comment by lambrusco** [comment]
In the meanwhile here you can find more infos about the token:
https://github.com/lucaslg26/TidalAPI

**Comment by cr4shydlo** [comment]
Hello. I got this token from lambrusco comment. But i can't add music from tidal... 
Im using ncmpcpp but here i dont know how to add stream tidal://
And in gmpc i got wrong protocol.
My version is : musicpd-0.20.15_1
Did anyone here get tidal work ?
Best regards.

**Comment by mistepien** [comment]
So you have reversed engineered windows tidal client to use something you pay for because tidal makes access more difficult? 
We all should think about tidal attitude and ask ourselves who pays whom.

**Comment by cr4shydlo** [comment]
Yes, but i still dont know how to use it :)

**Comment by MaxKellermann** [comment]
On 2018/02/07 23:59, cr4shydlo <notifications@github.com> wrote:
> Hello. I got this token from lambrusco comment. But i can't add music from tidal... 
> Im using ncmpcpp but here i dont know how to add stream tidal://
> And in gmpc i got wrong protocol.
> My version is : musicpd-0.20.15_1

This is not in 0.20.15, but in 0.21~git

**Comment by lambrusco** [comment]
Hi Max, so may I start testing Tidal integration in  0.21~git or is not ready yet?

**Comment by MaxKellermann** [comment]
On 2018/02/08 08:12, Pier Paolo Orioli <notifications@github.com> wrote:
> Hi Max, so may I start testing Tidal integration in  0.21~git or is not ready yet?

There is no release, but you can pull it from git and test it at any time.

**Comment by cr4shydlo** [comment]
Hmm... can you give me a hint from where exactly get 0.21 ? 
Master is 0.20 @ github 
Best regards.

**Comment by MaxKellermann** [comment]
@cr4shydlo this is wrong, and this whole discussion doesn't belong here. I delete your posts to avoid confusing other people reading this ticket.

**Comment by MaxKellermann** [comment]
I got a reply from Asbjørn Andersen (Tidal):

> We don't give out client tokens to private projects. All our tokens are given after the company building the implementation has signed an NDA.
> People or companies that wants to do a TIDAL integration should contact us,
and we would need to consider each project.

Which means there will be no Tidal token for MPD. And there will be no Tidal tokens for individual users.

Which boils down to: every MPD user needs to obtain a reverse-engineered Tidal token.
