### ISSUE TITLE
[Question] Tag for version v0.23.15

### ISSUE THREAD

**Issue by GioF71** [MusicPlayerDaemon/MPD#1981]
Hello, I am confused about these two commits:

Commit msg: "Merge tag 'v0.23.15'" <--- this is the first commit AFTER the tag 'v0.23.15' and does not have any tag
https://github.com/MusicPlayerDaemon/MPD/tree/5f54a8e94edb95b4652af000da168ce238b2a96d

Commit msg: "release v0.23.15", the commit is also tagged as: `v0.23.15`
https://github.com/MusicPlayerDaemon/MPD/tree/b8bfc986181a6824b7ee9c4f2c475369ca8ac931

Is this correct?
Checking the differences, I see for example that the tagged version does not include support for `mixramp_analyzer`.
Am I missing something?

Thank you very much for your attention.

EDIT: typos

**Comment by MaxKellermann** [comment]
It's correct. Why would it not be?

**Comment by GioF71** [comment]
Yes I see it's exactly the same for a the previous releases (I checked back to 0.23.12). Please indulge a dumb question, which commit corresponds to the 0.23.15 release?

**Comment by GioF71** [comment]
If I download the release file from [here](https://musicpd.org/download.html), it seems to be aligned to the tag `v0.23.15`. So I believe the 0.23.15 is the tagged version effectively, and that mixramp_analyzer is not included, and in fact it's not mentioned in the changelog.
So yes it seems all correct to me now, sorry for the inconvenience.

**Comment by MaxKellermann** [comment]
I don't understand your question. The commit that corresponds to the 0.23.15 release is the one that is tagged with the "v0.23.15" git tag.
mixramp_analyzer is not a 0.23 feature, why would you expect it to be? It's a different branch.

**Comment by GioF71** [comment]
Yes, an user of my docker image asked about it, and I did not notice that this feature wasn't part of a release yet, hence my confusion. It's clarified now, thank you!
