### ISSUE TITLE
playback of large files stops when used with curl 8.5

### ISSUE THREAD

**Issue by tflist** [MusicPlayerDaemon/MPD#1982]
### Describe the bug
When playing a larger file via the curl plugin the playback stops after 4 to 5 seconds. The critical file size is around 130MB, smalller files play nicely. 

This is somehow related to the version of curl in use. curl version 8.4 works as expected, with curl version 8.5 the playback stops. 

In my configuration mpd serves as backend to upmpdcli, Im using manjaro linux (arch based). A downgrade from curl 8.5 to 8.4 solves the problem.  

## Expected Behavior

normal playback

## Actual Behavior

playback stops after 3-4 seconds

## Version

Music Player Daemon 0.23.15 (0.23.15)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration

pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory  "/hdd/Media"
follow_outside_symlinks "yes"

log_level "verbose"
log_file "/tmp/mpd.log"

user                    "mpd"
group                   "mpd"

input {
        plugin          "curl"
}

decoder {
        plugin          "flac"
        enabled         "yes"
}

decoder {
        plugin          "ffmpeg"
        enabled         "no"
}

audio_output {
        type            "alsa"
        name            "name"
        device          "hw:CARD=DACxxx"
        mixer_type      "hardware"
        replay_gain_handler     "none"
}

## Log

Feb 02 21:30 : zeroconf: No global port, disabling zeroconf                                                           
Feb 02 21:30 : state_file: Loading state file /var/lib/mpd/mpdstate                                                   
Feb 02 21:30 : client: [0] opened from [::1]:59054                                                                    
Feb 02 21:30 : client: [1] opened from [::1]:59058                                                                    
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [0] process command "idle playlist player mixer options"                                       
Feb 02 21:30 : client: [0] command returned 1                                                                         
Feb 02 21:30 : client: [1] process command "consume "0""                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "single "0""                                                               
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playid "1""                                                               
Feb 02 21:30 : playlist: play 0:"http://192.xxx.xxx.xxx:9790/minimserver/*<...>/file.flac"                                    
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : decoder_thread: probing plugin flac                                                                    
Feb 02 21:30 : decoder: audio_format=192000:24:2, seekable=true                                                       
Feb 02 21:30 : alsa_output: opened hw:CARD=DACxxx type=HW                                                        
Feb 02 21:30 : alsa_output: buffer: size=48..384000 time=250..2000000                                                 
Feb 02 21:30 : alsa_output: period: size=24..192000 time=125..1000000                                                 
Feb 02 21:30 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000                                   
Feb 02 21:30 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)                                               
Feb 02 21:30 : alsa_output: buffer_size=96000 period_size=24000                                                       
Feb 02 21:30 : output: opened "xxx" (alsa) audio_format=192000:32:2                                         
Feb 02 21:30 : output: converting in=192000:24:2 -> f=192000:24:2 -> out=192000:32:2                                  
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo"                                                             
Feb 02 21:30 : client: [1] command returned 0           
**Feb 02 21:30 : exception: CURL failed: Out of memory**                                                                  
Feb 02 21:30 : client: [0] process command "idle playlist player mixer options"                                       
Feb 02 21:30 : client: [0] command returned 1                                                                         
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "currentsong"                                                              
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo "1""                                                         
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "playlistinfo"                                                             
Feb 02 21:30 : client: [1] command returned 0                                                                         
Feb 02 21:30 : client: [1] process command "status"                                                                   
Feb 02 21:30 : client: [1] command returned 0

**Comment by Emilot** [comment]
https://github.com/MusicPlayerDaemon/MPD/issues/1952

it was a curl problem and it is fixed.
