### ISSUE TITLE
When playing public webdav stream, curl fails "Out of memory"

### ISSUE THREAD

**Issue by avuton** [MusicPlayerDaemon/MPD#1984]
### Describe the bug

First I have reproduced this bug on Android, x86_64/linux; it does not reproduce in VLC and downloads fine with the curl command line. I tried, unsuccessfully to bisect; all versions I tried of v0.23 are affected.

To reproduce (with public link):

mpc add 'https://m9AtxjsmtajLEEb@nc.anpmech.com/public.php/webdav'
mpc play

After a while the stream ends prematurely (it's a 2 hour or so stream).

## Version

Music Player Daemon 0.23.15 (0.23.15)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Configuration

music_directory                 "https://xxxxxxx@nc.anpmech.com/public.php/webdav"
bind_to_address         "any"
log_level                       "verbose"
restore_paused "yes"
auto_update    "yes"

database {
       plugin "proxy"
       host "anpmech.com"
}

## Log

Feb 03 11:21:52 rocket mpd[10033]: playlist: play 0:"https://m9AtxjsmtajLEEb@nc.anpmech.com/public.php/webdav"
Feb 03 11:21:52 rocket mpd[10033]: client: [24] command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [24] process command list
Feb 03 11:21:52 rocket mpd[10033]: client: process command "status"
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: process command "currentsong"
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [24] process command list returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [24] closed
Feb 03 11:21:52 rocket mpd[10033]: decoder_thread: probing plugin vorbis
Feb 03 11:21:52 rocket mpd[10033]: decoder_thread: probing plugin oggflac
Feb 03 11:21:52 rocket mpd[10033]: decoder_thread: probing plugin opus
Feb 03 11:21:52 rocket mpd[10033]: decoder: audio_format=48000:16:2, seekable=false
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command list
Feb 03 11:21:52 rocket mpd[10033]: client: process command "status"
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: opened default type=IOPLUG
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: buffer: size=96..1048576 time=2000..21845334
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: period: size=32..349526 time=666..7281792
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: format=S16_LE (Signed 16 bit Little Endian)
Feb 03 11:21:52 rocket mpd[10033]: alsa_output: buffer_size=24000 period_size=6000
Feb 03 11:21:52 rocket mpd[10033]: output: opened "default detected output" (alsa) audio_format=48000:16:2
Feb 03 11:21:52 rocket mpd[10033]: output: Failed to open mixer for 'default detected output': no such mixer control: PCM
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: process command "currentsong"
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command list returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command "idle player message"
Feb 03 11:21:52 rocket mpd[10033]: client: [1] command returned 1
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command list
Feb 03 11:21:52 rocket mpd[10033]: client: process command "status"
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: process command "currentsong"
Feb 03 11:21:52 rocket mpd[10033]: client: command returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command list returned 0
Feb 03 11:21:52 rocket mpd[10033]: client: [1] process command "idle player message"
Feb 03 11:21:52 rocket mpd[10033]: client: [1] command returned 1
Feb 03 11:21:58 rocket mpd[10033]: exception: CURL failed: Out of memory
Feb 03 11:22:15 rocket mpd[10033]: player: played "https://m9AtxjsmtajLEEb@nc.anpmech.com/public.php/webdav"
Feb 03 11:22:15 rocket mpd[10033]: playlist: stop

**Comment by MaxKellermann** [comment]
CURL bug, see https://github.com/MusicPlayerDaemon/MPD/issues/1952
