### ISSUE TITLE
Unknown lvalue 'ControlGroup' in section 'Service'

### ISSUE THREAD

**Issue by norrest** [MusicPlayerDaemon/MPD#199]
[    3.940895] systemd[1]: [/lib/systemd/system/mpd.service:17] Unknown lvalue 'ControlGroup' in section 'Service'
[    3.951236] systemd[1]: [/lib/systemd/system/mpd.service:20] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
[

```
cat /lib/systemd/system/mpd.service
[Unit]
Description=Music Player Daemon
After=network.target sound.target

[Service]
EnvironmentFile=/etc/default/mpd
ExecStart=/usr/bin/mpd --no-daemon $MPDCONF

 allow MPD to use real-time priority 50
LimitRTPRIO=50
LimitRTTIME=-1

move MPD to a top-level cgroup, as real-time budget assignment fails
in cgroup /system/mpd.service, because /system has a zero real-time
 budget; see
http://www.freedesktop.org/wiki/Software/systemd/MyServiceCantGetRealtime/
ControlGroup=cpu:/mpd

 assign a real-time budget
ControlGroupAttribute=cpu.rt_runtime_us 500000

[Install]
WantedBy=multi-user.target

```

**Comment by MaxKellermann** [comment]
Sigh, yet another systemd feature that was removed, yet the documentation still refers to it: https://www.freedesktop.org/wiki/Software/systemd/MyServiceCantGetRealtime/

.. which means there is now no way left to allow MPD to get real-time scheduling!

**Comment by MaxKellermann** [comment]
Oh wait. Look at this: https://github.com/MusicPlayerDaemon/MPD/commit/0cbfb610f232c7a77272039698e5b137267c3159

This was already removed 3 years ago in release 0.19.11!

W T F

Yet another bullshit bug report by you. One without a version number, about a horribly outdated MPD version. I knew I remembered your name. And I will remember it next time.
