### ISSUE TITLE
opus support

### ISSUE THREAD

**Issue by iconoclasthero** [MusicPlayerDaemon/MPD#1999]
### Describe the bug
Opus support is deficient.

## Expected Behavior
The docs list a range of options for opus output which should work.

## Actual Behavior
$ tail mpd.log
Feb 29 15:51 : config: option 'complexity' on line 354 was not recognized
Feb 29 15:51 : config: option 'signal' on line 355 was not recognized
Feb 29 15:51 : config: option 'vbr' on line 356 was not recognized
Feb 29 15:51 : config: option 'opustags' on line 357 was not recognized
$ restart mpd
Job for mpd.service failed because the control process exited with error code.
See "systemctl status mpd.service" and "journalctl -xeu mpd.service" for details.
× mpd.service - Music Player Daemon
     Loaded: loaded (/usr/local/lib/systemd/system/mpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-02-29 15:52:44 EST; 9ms ago
TriggeredBy: × mpd.socket
       Docs: man:mpd(1)
             man:mpd.conf(5)
    Process: 721750 ExecStart=/usr/local/bin/mpd --systemd /etc/mpd.conf (code=exited, status=1/FAILURE)
   Main PID: 721750 (code=exited, status=1/FAILURE)
        CPU: 900ms

Feb 29 15:52:43 gigabyte systemd[1]: Starting Music Player Daemon...
Feb 29 15:52:43 gigabyte mpd[721750]: Ignoring the 'pid_file' setting in systemd mode
Feb 29 15:52:44 gigabyte mpd[721750]: Feb 29 15:52 : exception: Error in block on line 335; Failed to configure output in line 335; bitrate should be a positive integer
Feb 29 15:52:44 gigabyte systemd[1]: mpd.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 15:52:44 gigabyte systemd[1]: mpd.service: Failed with result 'exit-code'.
Feb 29 15:52:44 gigabyte systemd[1]: Failed to start Music Player Daemon.
Music Player Daemon 0.24 (v0.23.15-1177-g1efb9d41d)

## Version
0.24

## Configuration
what?

## Log
see above.

**Comment by iconoclasthero** [comment]
Also, there is no example of an audio_output stanza for opus in the config file or the docs.  
Please consider adding one of those for reference.

audio_output {
       type            "shout"
       name            "My Shout Stream"
       host            "localhost"
       port            "8000"
       mount           "/mpd.ogg"
#       quality         "5.0"
#       bitrate         "128"
#       format          "44100:16:1"
##      protocol        "icecast2"              # optional
##      user            "source"                # optional
##      description     "My Stream Description" # optional
##      url             "http://example.com"    # optional
##      genre           "jazz"                  # optional
##      public          "no"                    # optional
##      timeout         "2"                     # optional
##      mixer_type      "software"              # optional
       bitrate         "max"
       password        "seven314"
       complexity      "10"
       signal          "music"
       vbr             "constrained"
       opustags        "yes"
       format          "48000:16:2"
}

**Comment by MaxKellermann** [comment]
This bug report is bogus because your configuration file is wrong. Your "bitrate" setting is wrong.

**Comment by iconoclasthero** [comment]
Would you please explain what this means from the docs?
[bitrate Sets the data rate in bits per second. The special value “auto” lets libopus choose a rate (which is the default), and “max” uses the maximum possible data rate.
](https://mpd.readthedocs.io/en/latest/plugins.html#id27:~:text=Sets%20the%20data%20rate%20in%20bits%20per%20second.%20The%20special%20value%20%E2%80%9Cauto%E2%80%9D%20lets%20libopus%20choose%20a%20rate%20(which%20is%20the%20default)%2C%20and%20%E2%80%9Cmax%E2%80%9D%20uses%20the%20maximum%20possible%20data%20rate.)

As I said, there's no indication of how to use those plugin setting options in the docs or in the config file so I'm at a loss to understand the correct usage of max/auto bitrate in this context as decscribed.

**Comment by iconoclasthero** [comment]
encoder "opus" 
is what is at issue...documentation or config example would have been more instructive, though this is my error, but
