### ISSUE TITLE
MPD doesn't play file 

### ISSUE THREAD

**Issue by entuccio** [MusicPlayerDaemon/MPD#2001]
## Bug report

Hello

Is there a way, to "force" mpd to download the song before playing it? My music folder is on iCloud/Google Drive, and when I play a song, the operating system tells iCloud or Google Drive to download the song, but this doesn't happen with MPD.
I am forced to go to the Finder and manually download the song. Is there a way to tell the workflow to "download the song before playing it"? 
If I use every other player, it does that automatically.
Thank you very much.

## Expected Behavior
Download and play the file

## Actual Behavior
daniele@DaniMacBook-M2 ~ % mpc
volume:100%   repeat: off   random: on    single: off   consume: off
ERROR: Failed to decode /Users/daniele/song.mp3': Operation not permitted

## Version
Music Player Daemon 0.23.15 (0.23.15)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local nfs curl

Neighbor plugins:
 upnp

Decoders plugins:
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe ao openal osx httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg nfs

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// nfs:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// sftp:// smb:// srtp://

Other features:
 icu ipv6 tcp un

## Configuration
music_directory		"/Users/daniele/Library/CloudStorage/GoogleDrive-info@foundminiatures.com/Il mio Drive/DaniSynologyNas/Musica.nosync"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log"
pid_file                "~/.mpd/mpd.pid"
state_file              "~/.mpd/mpdstate"
auto_update             "yes"
auto_update_depth       "2"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

auto_update "yes"

audio_output {
    type                  "osx"
    name                  "CoreAudio"
    mixer_type            "software"
}

bind_to_address         "127.0.0.1"
port                    "6600"

**Comment by MaxKellermann** [comment]
I have no idea how this cloud storage thing works and how to tell the operating system to download it. MPD on macOS is unsupported because there's no developer with a Mac. Sorry.
