### ISSUE TITLE
Question: is there a MaxFileSize in MPD? 

### ISSUE THREAD

**Issue by skyhigh24** [MusicPlayerDaemon/MPD#2015]
Not a Bug, not a Feature Request, just a Question:

Is there a Max File Size? 

Background: 
I tried to play back a 499MB MP3 Audiobook, which translates to roughly 9hours of Playtime. 
Whenever i tried, the Audio cuts out between hour 7 and hour 9.
RAM is 512MB but had at least 200MB of free Space at all times, i checked.  (Pi Zero2W)

So i Re-Converted the Audiobook in a Lower Quality 348MB MP3. Now it works as Intended. 

then i checked the Original 499MB File: 
MD5 is correct
SanityCheck on PC -> file is Playable and has an AudioTrack till the EndMarker. so its not "Empty" due to conversion Error. 

i was just Curious if somebody experienced somthing similar.

**Comment by MaxKellermann** [comment]
MPD does not explicitly implement a limit, but some decoder libraries may, and implicit limitations may arise from certain other natural limitations or from bugs.
