### ISSUE TITLE
NetEase cloud music(V9.0.60.201911) upnp push mpd+upmpdcli tear sound

### ISSUE THREAD

**Issue by lazybat** [MusicPlayerDaemon/MPD#2022]
### Describe the bug

The hardware used is Raspberry PI 4b
The decoder : holo spring2 、Sony TA-ZH1ES
NetEase cloud music pushed is 96k, but the mpd output is recognized as 44.1k and the sound is tearing.
Using aprenderer-arm32 sound is normal

## Expected Behavior
sound is normal

## Actual Behavior
sound is tearing

## Version
mpd 0.22.6
mpd 0.23.7
upmpdcli 1.52
upmpdcli 1.86
moode6.x moode 8.x
NetEase cloud music(V9.0.60.201911)(andriod app)

**Comment by MaxKellermann** [comment]
I have no idea what this is about; this bug report is incomplete, you removed sections you were asked to fill out. But what I see is that the MPD versions you use are outdated and unsupported. I therefore have to close this bug report.
