### ISSUE TITLE
crash of mpd-git when disabling alsa output

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#203]
> clock_gettime(CLOCK_MONOTONIC, {tv_sec=21375, tv_nsec=508772079}) = 0
recvfrom(18, "disableoutput \"0\"\n", 8192, MSG_DONTWAIT, NULL, NULL) = 18
writev(2, [{iov_base="client: [15] process command \"di"..., iov_len=48}, {iov_base="\n", iov_len=1}], 2client: [15] process command "disableoutput "0""
) = 49
writev(2, [{iov_base="", iov_len=0}, {iov_base=NULL, iov_len=0}], 2) = 0
futex(0xb2b7e998, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xb3de9e80, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xbfb1e808, FUTEX_WAIT_PRIVATE, 2, NULLoutput: closed "V102,0 [USB-SPDIF V1.02 USB Audio]" (alsa)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open audio output
) = ?
+++ killed by SIGABRT +++
Aborted

mpd version: v0.20.15-849-gd084950b1-dirty
mpd is (was) in state play.

**Comment by mistepien** [comment]
It happens also in case of pulse output.
And the rest of system does not matter. I have it on musl+alsa 1.1.5 and on debian (glibc + alsa 1.1.3).

**Comment by MaxKellermann** [comment]
Can't reproduce. Post a backtrace. strace is not helpful for a crash bug.

**Comment by mistepien** [comment]
Could you write what exactly should I do?
I have strace and gdb, musl libc is compiled for debugging, mpd is unstripped.

This time mpd is not unresponsive but "killed" so howto from https://github.com/MusicPlayerDaemon/MPD/issues/151 does not work.

**Comment by mistepien** [comment]
this output of strace -tttfTp $(pidof mpd) -o trace3.txt
[trace3.txt](https://github.com/MusicPlayerDaemon/MPD/files/1658347/trace3.txt)

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/user/bugs.html#crash

As I said already, a strace is not helpful for a crash bug.

**Comment by mistepien** [comment]
I followed that tip:

> client: [1] command returned 0
client: [6] process command "disableoutput "0""
output: closed "V102,0 [USB-SPDIF V1.02 USB Audio]" (alsa)
terminate called after throwing an instance of 'std::runtime_error'
client: [6] command returned 0
  what():  Failed to open audio output
client: [6] process command "idle"
client: [6] command returned 1
client: [3] process command "status"

Thread 3 "player" received signal SIGABRT, Aborted.
[Switching to LWP 7536]
0xb7f6bab9 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7f6bab9 in __kernel_vsyscall ()
#1  0xb7f8a0b8 in __vsyscall () at src/internal/i386/syscall.s:19
#2  0xb7fb5408 in __syscall4 (a4=8, a3=0, a2=-1231215360, a1=2, n=175)
    at ./arch/i386/syscall_arch.h:37
#3  __restore_sigs (set=0xb69d2500) at src/signal/block.c:43
#4  0xb7fb55d6 in raise (sig=6) at src/signal/raise.c:13
#5  0xb7f880a6 in abort () at src/exit/abort.c:9
#6  0xb6c3a16b in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/libstdc++.so.6
#7  0xb6c3831c in ?? () from /usr/lib/libstdc++.so.6
#8  0xb6c3750b in ?? () from /usr/lib/libstdc++.so.6
#9  0xb6c37ded in __gxx_personality_v0 () from /usr/lib/libstdc++.so.6
#10 0xb6bbcd5b in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x9b76d90, 
    context=context@entry=0xb69d2860) at ../../../libgcc/unwind.inc:62
#11 0xb6bbcff4 in _Unwind_RaiseException (exc=0x9b76d90)
    at ../../../libgcc/unwind.inc:131
#12 0xb6c3861a in __cxa_throw () from /usr/lib/libstdc++.so.6
#13 0x08057db1 in MultipleOutputs::Play(MusicChunk*) ()
#14 0x080602fb in Player::PlayNextChunk() ()
#15 0x08060bb9 in Player::Run() ()
#16 0x08060e5a in PlayerControl::RunThread() ()
#17 0x080b1200 in Thread::ThreadProc(void*) ()
#18 0xb7fc3ee4 in start (p=0xb69d2d50) at src/thread/pthread_create.c:150
