### ISSUE TITLE
MPD satellite mode with NFSv4 does not work

### ISSUE THREAD

**Issue by EdwinKM** [MusicPlayerDaemon/MPD#2038]
### Describe the bug
I have MPD running in satellite mode, where the music is stored on a NAS (Truenas Scale), and my laptop hosts the MPD instance as the sound source.

In the configuration, I've set the music directory to:
  ```music_directory "nfs://san/mnt/tank/var/music_temp"```

Everything operates smoothly when I use an NFSv3 share. However, when I switch to NFSv4, MPD fails to play the music.

I've verified that the share works fine and can be mounted:
 ```mount -v -o vers=4 -t nfs san:/mnt/tank/var/music_temp /mnt/music_temp```

According to the libnfs page, NFSv3 seems to be the default, and you need to specify "?version=4" in the URL. I've tried different variations for "music_directory", but they all fail. Additionally, I couldn't find a property in the default MPD configuration to force v4 mode.

Is this possible?

## Expected Behavior
Play music with NFSv3 or NFSv4 share

## Actual Behavior
NFSv3 works, NFSv4 does not work

## Version
Music Player Daemon 0.23.15 (0.23.15)

## Configuration

```test@linux-5q3o:~/gitea/truenas_apps_dockerfiles/mpd-satellite> cat /home/test/.config/mpd/mpd.conf |grep -v ^# |grep -v ^$
music_directory		"nfs://san/mnt/tank/var/music_temp"
log_file			"~/mpd.log"
log_level			"warning"
auto_update	"no"
zeroconf_enabled		"no"
database {
  plugin "proxy"
  host "san"
  port "9999"
}
input {
        plugin "curl"
}
audio_output {
	type		"pulse"
	name		"Pulse Output"
}
filesystem_charset		"UTF-8"
```

## Log
N/A

**Comment by MaxKellermann** [comment]
Incomplete bug report. You omitted the log even though you were asked to provide it.
