### ISSUE TITLE
FR: Support for Airsonic/Serviio Upnp server

### ISSUE THREAD

**Issue by gerroon** [MusicPlayerDaemon/MPD#204]
Hi

I have couple Upnp servers running. I enabled upnp database in Mpd. I am able to list the server medias from the avail Upnp servers but I can only really play songs from Emby. Mpd cant stream from  Airsonic(Subsonic fork) and Serviio. 

I get messages like these when I try to play from from Airsonic/Serviio in ncmpcpp

`MPD: Failed to decode jwt=eyJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL2FpcnNvbmljL2V4dC9zdHJlYW0_aWQ9MjAzNDcxJnBsYXllcj03NSIsImV4cCI6MTUxNzMzMTU2NH0.W35KZvJFlMphgW3Dp9kZ8N_mc9oALb9ISxTwdgfIcMc; Unrecognized URI`

On the otherhand Mpd has no problem streaming from Emby on my network. All the Upnp servers are running on the same Debian pc and accesing the same local music folders. I 

Vlc, BubbleUpnp, Hifi Cast, NeutronPlayer etc have no problem streaming from any of these servers. 

Mpd version
https://paste.debian.net/hidden/49734dc9/

thanks

**Comment by MaxKellermann** [comment]
Upload a packet capture. I have no such device, so I can't reproduce your problem.

**Comment by gerroon** [comment]
Hi

I never did packet capture before. What kind of capture are you looking to debug this? 

thanks

**Comment by MaxKellermann** [comment]
One made with Wireshark.

**Comment by MaxKellermann** [comment]
Closing due to lack of feedback.
