### ISSUE TITLE
openwrt安装mpd和upmpdcli,重启后不能运行

### ISSUE THREAD

**Issue by 725216** [MusicPlayerDaemon/MPD#2051]
刚开始安装完时，直接运行mpd,正常运行，qq音乐也可以正常推送，设置了自启动/etc/init.d/mpd enable后，重启路由，就不能正常运行了，症状是：qq音乐链接后播放按钮点不动，手机MPDroid播放按钮也点不动，提示绑定端口失败
root@ImmortalWrt:~# mpd -v
config_file: loading file /etc/mpd.conf
May 21 13:33 : exception: Failed to bind to '0.0.0.0:6600'; Failed to bind socket: Address in use

系统日志：Tue May 21 13:32:25 2024 daemon.err mpd[11241]: Could not open /dev/crypto: Permission denied

mpd的log:May 21 13:57 : config: option 'mixer_control' on line 15 was not recognized
May 21 14:00 : ffmpeg/mp3: Estimating duration from bitrate, this may be inaccurate
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:00 : player: problems opening audio device while playing "费玉清 一剪梅.mp3"
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:00 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:01 : player: played "费玉清 一剪梅.mp3"
May 21 14:01 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:01 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:01 : player: problems opening audio device while playing "http://isure6.stream.qqmusic.qq.com/M5000030QIVp0DaIAg.mp3?guid=0000000070a2f81b00000183c73bf5a7&vkey=B029BDE02AF68F9853A588DE3CB42D6A727BE3A1B676693C23A50C077EBD561A3DAD102F0B9092AF17BA7EA1D20398E0D688717C67DCDFDF&uin=1152921504987820027&fromtag=111042"
May 21 14:01 : ffmpeg/mp3float: Could not update timestamps for skipped samples.
May 21 14:01 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied
May 21 14:01 : exception: Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "hw:0,0": Permission denied

mpd.conf配置：

music_directory         "/mnt/mmcblk0p1/mp3" #歌曲目录
playlist_directory      "/mnt/mmcblk0p1/mp3/.mpd/" #播放列表存放目录
db_file                 "/mnt/mmcblk0p1/mp3/.mpd/mpd.db" #歌曲列表
log_file                "/tmp/mpd.log"
pid_file                "/tmp/mpd.pid"
user                    "root" 
group                   "users"
bind_to_address         "0.0.0.0"
port                    "6600"
audio_output {
     type         "alsa"        
     name         "My ALSA Device"        
     device         "hw:0,0" 
     format         "44100:16:2"
     mixer_control        "PCM"
}
filesystem_charset        "UTF-8"

#id3v1_encoding          "gb2312"

#OSS Mixer
mixer_type "software"
#mixer_device "/dev/mixer"
#mixer_control "speaker"

auto_update "yes"
#gapless_mp3_playback "yes"

**Comment by MaxKellermann** [comment]
Huh, what?
