### ISSUE TITLE
Support CD De-emphasis

### ISSUE THREAD

**Issue by realbaylen** [MusicPlayerDaemon/MPD#2053]
## Feature request
https://wiki.hydrogenaud.io/index.php?title=Pre-emphasis

**Comment by MaxKellermann** [comment]
I believe this can already be done with the FFmpeg filter plugin.
https://mpd.readthedocs.io/en/latest/plugins.html#id40
https://ffmpeg.org/ffmpeg-filters.html#aemphasis

**Comment by mshkrebtan** [comment]
I can't believe, literally yesterday I was listening to a CD-rip of [Pet Shop Boys — Please](https://www.discogs.com/release/1043038-Pet-Shop-Boys-%E3%83%9A%E3%83%83%E3%83%88%E3%82%B7%E3%83%A7%E3%83%83%E3%83%97%E3%83%9C%E3%83%BC%E3%82%A4%E3%82%BA-Please-%E3%82%A6%E3%82%A8%E3%82%B9%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89%E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA), which has pre-emphasis applied, and thought that there has to be a way to apply de-emphasis other than `sox deemph`.

Thank you @MaxKellermann! MPD rules! 🤘❤️

Here's a configuration snippet for others wondering:
```
filter {
  name "deemph"
  plugin "ffmpeg"
  graph "aemphasis=mode=reproduction:type=cd"
}
```

Then add it to the `audio_output` of your choice:
```
audio_output {
  filters "deemph"
  ...
}
```

I have 2 outputs for the same device now and enable the one with the filter when needed.
