### ISSUE TITLE
Better Opus ReplayGain support

### ISSUE THREAD

**Issue by nullobsi** [MusicPlayerDaemon/MPD#2055]
## Feature request

Hi,

Currently the support for ReplayGain for OPUS files is limited to the ReplayGain tags and OGG headers from the OPUS spec. For various reasons, I decide not to use those tags and instead use the generic `REPLAYGAIN_` tags.

I would like to be able to use these tags for my library, which can probably be done by prioritizing one tag over the other and falling back when needed. I've attached a shitty little hacky patch I made that seems to make it work just with REPLAYGAIN_ tags.

Thank you
[replaygain.patch](https://github.com/user-attachments/files/15509582/replaygain.patch)

**Comment by MaxKellermann** [comment]
I'm not convinced that this is a good idea or even useful.

**Comment by nullobsi** [comment]
https://github.com/complexlogic/rsgain?tab=readme-ov-file#opus-files

The RSgain utility has some reasoning behind why you might prefer `REPLAYGAIN_` tags over the `R128_` tags for Opus (by default it writes `REPLAYGAIN_` tags). I think a sane decision would be to prefer the R128_ and OutputGain over the traditional `REPLAYGAIN_` tags to preserve the previous behavior, but also make it better for those (like me) who have Opus libraries with `REPLAYGAIN_` tags.

I can draft a PR with better code quality than the hacky patch I made sometime soon.

**Comment by MaxKellermann** [comment]
Just use RFC mode if you insist on using that tool.
