### ISSUE TITLE
 player: Decoder is too slow; playing silence to avoid xrun

### ISSUE THREAD

**Issue by gerroon** [MusicPlayerDaemon/MPD#206]
Hi

I have been listening this particular radio for couple years, I generally do not have any issues playing it in other players that support streams. Recently I moved my radio stuff to Mpd and I am happy with it except that it refuses to play this particular station steadily. it seems like it stops playing  and starts throwing the error in the title. I have like 60 stations in my playlist and I do not seem to have any issue with any other one in there, at least I have not experienced with the rest.

I tried disabling ffmpeg, mpg123 etc but I cant seem to make a difference.   Ffplay or Mpv plays it fine. 

I enabled verbose logging and this is what I have, not sure if it helps. I think it does what it says, it is not really stopping it, I see it looks like it is playing in Malp or ncmpcpp but no sound is coming. 

I have pulse, http and pipe enabled as outputs. Everything else is pretty standard in my config.

Station
- http://38.107.243.188:8591

ffprobe http://38.107.243.188:8591/
- https://paste.debian.net/hidden/42eaf412/

Log
- https://paste.debian.net/hidden/d3125fc5/

Mpd -V
- https://paste.debian.net/hidden/b4b37f7c/

thanks

**Comment by skidoo23** [comment]
$ mpc add http://38.107.243.188:8591/

works as advertised - at least on MPD master from git on Debian testing x64. Ffmpeg 3.4.1

**Comment by gerroon** [comment]
@skidoo23 

Yes it plays, but it drops the connection after a while (after between 5-30secs) and starts flooding the log with "player: Decoder is too slow; playing silence to avoid xrun "

**Comment by gerroon** [comment]
@skidoo23 

Also the issue is I do not understand what the message is all about. What does decoder too slow mean in the context of debugging this?

**Comment by skidoo23** [comment]
*** ffmpeg ****
Jan 29 18:02 : playlist: play 0:"http://38.107.243.188:8591/"
(...)
Jan 29 18:02 : curl: icy-metaint=32768
Jan 29 18:02 : decoder_thread: probing plugin ffmpeg
Jan 29 18:02 : ffmpeg: detected input format 'mp3' (MP2/3 (MPEG audio layer 2/3))
Jan 29 18:02 : ffmpeg/mp3: Skipping 288 bytes of junk at 0.
Jan 29 18:02 : ffmpeg/mp3: Before avformat_find_stream_info() pos: 288 bytes read:1300 seeks:0 nb_streams:1
(,,,)
Jan 29 18:02 : ffmpeg/mp3: All info found
Jan 29 18:02 : ffmpeg/mp3: stream 0: start_time: 0.000 duration: -653583619391.637
Jan 29 18:02 : ffmpeg/mp3: format: start_time: 0.000 duration: -9223372036854.775 bitrate=128 kb/s
Jan 29 18:02 : ffmpeg/mp3: After avformat_find_stream_info() pos: 21792 bytes read:23020 seeks:0 frames:50
Jan 29 18:02 : ffmpeg: codec 'mp3'
Jan 29 18:02 : decoder: audio_format=44100:16:2, seekable=false
Jan 29 18:02 : icy_metadata: unknown icy-tag: 'StreamUrl'
Jan 29 18:02 : alsa_output: opened hw:USB_Audio type=HW
Jan 29 18:02 : alsa_output: buffer: size=90..262144 time=2040..5944309
Jan 29 18:02 : alsa_output: period: size=45..131072 time=1020..2972155
Jan 29 18:02 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Jan 29 18:02 : alsa_output: format=S16_LE (Signed 16 bit Little Endian)
Jan 29 18:02 : alsa_output: buffer_size=22050 period_size=5513
Jan 29 18:02 : output: opened "USB Audio" (alsa) audio_format=44100:16:2

*** mpg123 ***
Jan 29 18:07 : curl: icy-metaint=32768
Jan 29 18:07 : exception: Failed to decode http://38.107.243.188:8591/
Jan 29 18:07 : player: played "http://38.107.243.188:8591/"
Jan 29 18:07 : playlist: stop

*** mad ***
Jan 29 18:08 : playlist: play 0:"http://38.107.243.188:8591/"
(...)
Jan 29 18:08 : curl: icy-metaint=32768
Jan 29 18:08 : decoder_thread: probing plugin mad
Jan 29 18:08 : decoder: audio_format=44100:24:2, seekable=false
(...)
Jan 29 18:08 : alsa_output: opened hw:USB_Audio type=HW
Jan 29 18:08 : alsa_output: buffer: size=90..174762 time=2040..3962858
Jan 29 18:08 : alsa_output: period: size=45..87381 time=1020..1981429
Jan 29 18:08 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Jan 29 18:08 : alsa_output: format=S24_3LE (Signed 24 bit Little Endian in 3bytes)
Jan 29 18:08 : alsa_output: buffer_size=22050 period_size=5513
Jan 29 18:08 : output: opened "USB Audio" (alsa) audio_format=44100:24:2
Jan 29 18:08 : icy_metadata: unknown icy-tag: 'StreamUrl'

Listened to stream about ten minutes with ffmpeg and mad decoder without problem.

**Comment by gerroon** [comment]
@skidoo23 

Thanks for testing this out! This confirms that I am having an isolated decoding issue probably.

**Comment by WarnerV** [comment]
@Gerroon did you ever manage to resolve this?

I've had the same problem for months and I have to clue where to look for a solution..

**Comment by smeikx** [comment]
I’m still having this problem today.

**Comment by WarnerV** [comment]
In my case (as described in another thread) the issue was caused - believe it or not - by a faulty network cable. This caused an unstable connection and MPD complaining with the xrun message. Hope this observation sets you on the right trail ;)

**Comment by smeikx** [comment]
I figured it out too: in my case it was a faulty SATA adapter causing horribly slow read speed. Sorry for the noise.

**Comment by bobrathbone** [comment]
Unfortunately, Raspbian is released with a very out-of-date version of the Music Player daemon. The version released with Buster is **0.21.5** is some twenty versions behind the latest version  **0.21.25**. You should install MPD version **0.21.5** first. When it is all working if you are having problems playing certain it is well worth installing the latest version of MPD. Although the thought of compiling MPD may be a frightening one for some of you it is probably worth doing. I have described the process in a PDF document which can be found at [https://www.bobrathbone.com/raspberrypi/compiling_mpd.html](https://www.bobrathbone.com/raspberrypi/compiling_mpd.html). I cannot guarantee that the latest version of MPD will cure this particular problem but I have tested version 0.21.5 and it has cleared a number of problems relating to playback issues.

**Comment by macerg** [comment]
I have the latest version of mpd installed and I too am seeing this error regularly.
alsa_output: Decoder is too slow; playing silence to avoid xrun.
Music Player Daemon 0.22.11 (0.22.11)

**Comment by ToinneGuust** [comment]
> I have the latest version of mpd installed and I too am seeing this error regularly. alsa_output: Decoder is too slow; playing silence to avoid xrun. Music Player Daemon 0.22.11 (0.22.11)

Check your network (cables). I had the same issue as @WarnerV, a faulty network cable...

**Comment by mhuesch** [comment]
I see this same message with `mpd-0.23.4`, with reliable-seeming cabling directly from my laptop's audio output into a speaker. have never had issues with the cable or speaker before.

**Comment by ToinneGuust** [comment]
I'm running Music Player Daemon 0.20.18 (volumio). My issue was completely resolved once I replaced the faulty cable.
Have you got the same issue when playing local files on the machine?
Check for any other unstable links in your internet connection.

**Comment by mhuesch** [comment]
thanks @ToinneGuust.  I just tried two my other media players with my system, and it seems to have similar skipping issues with them (tho the durations of the skips seem shorter). will keep digging, but that might indicate that `mpd` is not a cause here...
