### ISSUE TITLE
Regression regarding TPOS? 0.20.15

### ISSUE THREAD

**Issue by quite** [MusicPlayerDaemon/MPD#209]
I have for a long time have tracks properly tagged with the `TPOS` frame (typically used for indicating which disc the track comes from, example value: "2/2"). Mpd has correctly indexed these before, and both mpc and ncmpcpp (my curses client of choice) show the value "2/2". In mpc, format `%disc%` maps to `TPOS`.

I'm now on 0.20.15 in Arch Linux, and I have noticed that if mpd reindexes the file that has the `TPOS` tag value of "2/2", what I get from `%disc%` is now "02". What's up with this?

**Comment by MaxKellermann** [comment]
See https://www.musicpd.org/doc/user/tags.html "disc: the decimal disc number in a multi-disc album"

"2/2" is not a decimal disc number. The disc number is just "2".

The definition of `TPOS` is slightly different from MPD's definition ("The value MAY be extended with a "/" character and a numeric string containing the total number of parts in the set"), and so MPD extracts only what is valid according to MPD's definition.

**Comment by tsufeki** [comment]
@MaxKellermann Would it be possible to add new tags (`totaltracks`&`totaldiscs`)?

**Comment by MaxKellermann** [comment]
I can't imagine a strong use case for that. If you want to know how many tracks, search for all tracks of that album and pick the highest number. Same for disc.

**Comment by tsufeki** [comment]
It helps with incomplete albums in the db, but I agree it's a corner case/out of scope for music player.
