### ISSUE TITLE
mpd does not respond if stream is not available for curl

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#210]
> $ mpd --no-daemon --stderr -v -v 
config_file: loading file /home/user/.mpd/mpd.conf
 path: SetFSCharset: fs charset is:
soxr: soxr converter 'high'
vorbis: Xiph.Org libVorbis 1.3.5
opus: libopus 1.2.1
sndfile: libsndfile-1.0.28
simple_db: reading DB
curl: version 7.58.0
curl: with GnuTLS/3.5.17
state_file: Loading state file /home/user/.mpd/state
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
playlist: queue song 2:"Sonda_2._Muzyka_z_programu_telewizyjnego/03_Andrzej_Korzyński_-_Struny.ogg"
decoder_thread: probing plugin vorbis
decoder: audio_format=44100:f:2, seekable=true
client: [0] opened from 127.0.0.1:45078
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "playid "58""
playlist: play 57:"http://212.14.1.70:8000/pl/radiotok.ogg"
exception: Failed to decode http://212.14.1.70:8000/pl/radiotok.ogg
exception: nested: CURL failed: Connection timed out after 10000 milliseconds
player: played "http://212.14.1.70:8000/pl/radiotok.ogg"

and that all. mpd is not responsive all all.

**Comment by mistepien** [comment]
[gdb_stream.txt](https://github.com/MusicPlayerDaemon/MPD/files/1679823/gdb_stream.txt)

**Comment by mistepien** [comment]
[trace_stream.txt](https://github.com/MusicPlayerDaemon/MPD/files/1679831/trace_stream.txt)

**Comment by skidoo23** [comment]
Same behaviour to other decoder errors. Disable all mpeg decoders and try to play a mp3 audio file. Bam.

**Comment by mistepien** [comment]
I don't understand. Stream is ogg vorbis. There is no mp3/mpeg at all.

**Comment by skidoo23** [comment]
Looks like problem is not only related to broken ogg/vorbis streams. Disable all mpeg decoders (ffmpeg, mad, mpg123) and play local mp3 file. Your result?
