### ISSUE TITLE
I have audio garbage/spiking on just ONE file... have checked, re-installed etc.

### ISSUE THREAD

**Issue by alan12345678** [MusicPlayerDaemon/MPD#2132]
really just to find out at this stage, rather than file a bug report... I have no real clue what's going on or why, so to explain:

been using mpd with Cantata player for years now with zero issues. All of a sudden, I'm playing a newly added album and on just this one track, I have this loud "pop" series of sounds that occur always in the same places.

I've played this track in e.g. MPV, Audacity, Kid3 and no issues at all. I've run mp3Val on the album. I reinstalled mpd to ensure that I wasn't missing any important deps.

Yet still, there's just this one track - from a large library of roughly 70,000 songs - that creates this noise. I can't find any other track, including on the same album, that does this.

At this stage I'd be keen to know if there's any output I should post, or anything I can run/double check at this end?

So curious that I can't fix this issue because I don't actually know where to start looking.

**Comment by ufleisch** [comment]
Have you analyzed the file with MP3 Diags?

**Comment by alan12345678** [comment]
I just did. Nothing I can see that looks untoward, it only varies from the other files in the same album in terms of MPEG Audio details i.e. frame count and last frame address. Otherwise nothing it is flagging as in need of attention.

I ran several of the transformations, still no change. What I am going to do at this stage is source a different copy of the file i.e. from a different vendor/store page. It seems too odd to have just one track behave like this.

**Comment by alan12345678** [comment]
just to add: purchased a new copy of the entire album from Amazon. Still have the same issue, on just the one track.

**Comment by bartkl** [comment]
Are you using the same audio backend/driver when playing with MPD compared to those other players? Also: does running MPD with more verbose logging give you any information when playing this file?

**Comment by alan12345678** [comment]
I admit to currently being completely stumped by this. I have spent the afternoon reading docs, deleting and recreating configs as necessary. I cannot make the issue go away.

Happy to post anything if requested, but since I went back to my journal (advice is against local logging if mpd is started via systemd, which mine is). From the below extract of log file, the problematic track is "..../Higher/07 Loving You On My Mind.mp3"

The noise occurs always at the same places in the track. This is a complete new copy of the album purchased from Amazon. Even looking at the problem track in Audacity shows nothing odd looking.

`Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "clear"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command list
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/01 What Am I Gonna Do.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/02 South Dakota.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/03 Trust.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/04 It Takes A Woman.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/05 The Fire.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/06 Think I’m In Love With You.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/07 Loving You On My Mind.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/08 White Horse.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/09 Higher.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/10 The Bottom.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/11 The Day I Die.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/12 Crosswind.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/13 Weight Of Your World.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: process command "add "Chris Stapleton/Higher/14 Mountains Of My Mind.mp3""
Oct 09 17:01:56 Snazz mpd[1684]: client: command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command list returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "play 0"
Oct 09 17:01:56 Snazz mpd[1684]: playlist: play 0:"Chris Stapleton/Higher/01 What Am I Gonna Do.mp3"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: playlist: queue song 1:"Chris Stapleton/Higher/02 South Dakota.mp3"
Oct 09 17:01:56 Snazz mpd[1684]: decoder_thread: probing plugin mad
Oct 09 17:01:56 Snazz mpd[1684]: cache: Prefetch 'Chris Stapleton/Higher/02 South Dakota.mp3'
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "playlistinfo"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [1] process command "idle"
Oct 09 17:01:56 Snazz mpd[1684]: client: [1] command returned 1
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "plchangesposid "17""
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [1] process command "idle"
Oct 09 17:01:56 Snazz mpd[1684]: client: [1] command returned 1
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "currentsong"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] process command "currentsong"
Oct 09 17:01:56 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:57 Snazz mpd[1684]: mad: detected LAME version 3.100 ("LAME3.100")
Oct 09 17:01:57 Snazz mpd[1684]: mad: LAME peak found: 0
Oct 09 17:01:57 Snazz mpd[1684]: mad: encoder delay is 576, encoder padding is 648
Oct 09 17:01:57 Snazz mpd[1684]: decoder: audio_format=44100:24:2, seekable=true
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: opened hw:0,0 type=HW
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: buffer: size=32..524288 time=725..11888617
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: period: size=16..262144 time=362..5944309
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Oct 09 17:01:57 Snazz mpd[1684]: alsa_output: buffer_size=22050 period_size=4410
Oct 09 17:01:57 Snazz mpd[1684]: output: opened "PCH" (alsa) audio_format=44100:32:2
Oct 09 17:01:57 Snazz mpd[1684]: output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:32:2
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] process command "replay_gain_status"
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:57 Snazz mpd[1684]: client: [1] process command "idle"
Oct 09 17:01:57 Snazz mpd[1684]: client: [1] command returned 1
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] process command "replay_gain_status"
Oct 09 17:01:57 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:01:57 Snazz mpd[1684]: client: [1] process command "idle"
Oct 09 17:01:57 Snazz mpd[1684]: client: [1] command returned 1
Oct 09 17:02:02 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:02 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] process command "playid "21""
Oct 09 17:02:03 Snazz mpd[1684]: playlist: play 6:"Chris Stapleton/Higher/07 Loving You On My Mind.mp3"
Oct 09 17:02:03 Snazz mpd[1684]: decoder_thread: probing plugin mad
Oct 09 17:02:03 Snazz mpd[1684]: mad: detected LAME version 3.100 ("LAME3.100")
Oct 09 17:02:03 Snazz mpd[1684]: mad: LAME peak found: 0
Oct 09 17:02:03 Snazz mpd[1684]: mad: encoder delay is 576, encoder padding is 1368
Oct 09 17:02:03 Snazz mpd[1684]: decoder: audio_format=44100:24:2, seekable=true
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:03 Snazz mpd[1684]: playlist: queue song 7:"Chris Stapleton/Higher/08 White Horse.mp3"
Oct 09 17:02:03 Snazz mpd[1684]: cache: Prefetch 'Chris Stapleton/Higher/08 White Horse.mp3'
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] process command "replay_gain_status"
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:03 Snazz mpd[1684]: client: [1] process command "idle"
Oct 09 17:02:03 Snazz mpd[1684]: client: [1] command returned 1
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] process command "currentsong"
Oct 09 17:02:03 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:09 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:09 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:14 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:14 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:14 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:14 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:19 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:19 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:24 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:24 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:29 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:29 Snazz mpd[1684]: client: [0] command returned 0
Oct 09 17:02:29 Snazz mpd[1684]: client: [0] process command "status"
Oct 09 17:02:29 Snazz mpd[1684]: client: [0] command returned 0
`

**Comment by bartkl** [comment]
Interrogating the MP3 file seems like a red herring given that other players play it fine.

Just to rule stuff out you could try to convert the MP3 to some other format, and play that with MPD. Who knows the discrepancy is due to the MP3 decoder library?
