### ISSUE TITLE
mpd git master no longer runs

### ISSUE THREAD

**Issue by whatamesss** [MusicPlayerDaemon/MPD#2138]
### Describe the bug
latest mpd git master builds but doesnt run

## Expected Behavior
launching mpd should run the server

## Actual Behavior
launching mpd generates a crash

## Version

mpd--version, as well as just 'mpd' only give me this output:

mpd --version
mpd: ../mpd-9999/src/command/AllCommands.cxx:296: void command_init(): Assertion `strcmp(commands[i].cmd, commands[i + 1].cmd) < 0' failed.
Oct 26 09:07 : exception: MPD died from signal 6: Success

## Configuration

metadata_to_use "+comment"
music_directory         "/home/audio/"
playlist_directory		"~/playlists"
db_file			"~/.mpd/database"
log_file "/var/log/mpd/mpd.log"
pid_file "/run/mpd/mpd.pid"
state_file			"~/.mpd/state"
user "mpd"
group "audio"
bind_to_address		"any"
bind_to_address		"~/.mpd/socket"
port				"6600"
log_level			"warning"
metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"

auto_update	"yes"

input {
        plugin "curl"
	enabled "yes"
}
resampler {
  	plugin "soxr"
  	quality "very high"
  	threads "0"
}
replaygain			"off"
audio_output {
    type            "pulse"
    server          "127.0.0.1"
    name            "MPD Pulse Output"
}
audio_output {
        enabled         "yes"
        type            "httpd"
        name            "((my-mpd))"
        port            "8000"
        format          "*:32:2"
        compression     "0"
        always_on       "yes"
        tags            "yes"
        oggflac         "yes"
        oggchaining    "yes"
        mixer_type      "none"
}

## Log

unfortunately, i tried several methods to get mpd built with debug symbols..

gdb always tells me:
Reading symbols from /usr/bin/mpd...
(No debugging symbols found in /usr/bin/mpd)

here is the output anyway:

(gdb) run
Starting program: /usr/bin/mpd --stderr --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
config_file: loading file "/etc/mpd.conf"
soxr: soxr converter "very high"
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.5.2
sndfile: libsndfile-1.2.2
simple_db: reading DB
mpd: ../mpd-9999/src/command/AllCommands.cxx:296: void command_init(): Assertion `strcmp(commands[i].cmd, commands[i + 1].cmd) < 0' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff40d21ec in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff40d21ec in ??? () at /lib64/libc.so.6
#1  0x00007ffff407cf76 in raise () at /lib64/libc.so.6
#2  0x00007ffff406537a in abort () at /lib64/libc.so.6
#3  0x00007ffff406529e in ??? () at /lib64/libc.so.6
#4  0x00007ffff4075576 in __assert_fail () at /lib64/libc.so.6
#5  0x0000555555594f8e in ??? ()
#6  0x0000555555593207 in ??? ()
#7  0x0000555555593957 in ??? ()
#8  0x00005555555926ce in ??? ()
#9  0x00007ffff4066e6e in ??? () at /lib64/libc.so.6
#10 0x00007ffff4066f29 in __libc_start_main () at /lib64/libc.so.6
#11 0x0000555555592c15 in ??? ()

**Comment by jcorporation** [comment]
Fix: #2137
