### ISSUE TITLE
Since todays commit mpd 0.24.0 (master) dumps core

### ISSUE THREAD

**Issue by GK-774** [MusicPlayerDaemon/MPD#2139]
Since todays commit mpd 0.24.0 (master) dumps core:

Oct 26 16:19:31 sdl9.hal9000.at systemd[1]: Starting Music Player Daemon...
Oct 26 16:19:31 sdl9.hal9000.at mpd[7051]: mpd: ../src/command/AllCommands.cxx:296: void command_init(): Assertion `strcmp(commands[i].cmd, commands[i + 1].cmd) < 0' failed.
Oct 26 16:19:32 sdl9.hal9000.at systemd-coredump[7053]: [🡕] Process 7051 (mpd) of user 985 dumped core.
Oct 26 16:19:32 sdl9.hal9000.at systemd[1]: mpd.service: Main process exited, code=dumped, status=6/ABRT
Oct 26 16:19:32 sdl9.hal9000.at systemd[1]: mpd.service: Failed with result 'core-dump'.
Oct 26 16:19:32 sdl9.hal9000.at systemd[1]: Failed to start Music Player Daemon.

(a checkout from Oct 11th runs ok)

**Comment by jcorporation** [comment]
Pull request #2137 fixes this issue.
