### ISSUE TITLE
realtime scheduling and musl

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#218]
I use buildroot with musl. No systemd. This is embedded system.

This is what mpd logs during start:

> daemon_err mpd: exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Function not implemented

This is musl code:
https://git.musl-libc.org/cgit/musl/tree/src/sched/sched_setscheduler.c

Explanation is given here:
http://www.openwall.com/lists/musl/2016/03/01/5

It seems that mpd is unintentionally glibcish. Musl is coming more and more popular among embedded systems like eg. openwrt/lede and so on. It would be great to be able to use all features of mpd on such embedded systems.

**Comment by MaxKellermann** [comment]
Please explain what is wrong with the MPD code. I don't understand.

**Comment by mistepien** [comment]
Consider this not as a bug but as a feature ticket. Musl and glibc differs in case of sched_setscheduler. However musl is more popular on embedded systems. Now mpd does not use musl as it could thus mpd is not fully usable on embedded systems.

**Comment by MaxKellermann** [comment]
Yes, they differ because: Musl doesn't implement `sched_setscheduler` properly, whereas glibc does implement the function properly. (That guy's complaint about glibc documentation being wrong is actually wrong.)

So this is really a feature missing in Musl. They have this stub but decided not to implement it. Blame Musl, not MPD.

**Comment by mistepien** [comment]
Ok, that's quite logical.
And this is why in code there are so many "ifdef ANDROID", "ifdef _WIN32", "ifdef __APPLE__", "ifdef __linux__", "ifdef __GLIBC__", "ifdef __GNUC__", "ifdef __clang__".

**Comment by MaxKellermann** [comment]
No.

**Comment by mistepien** [comment]
http://git.musl-libc.org/cgit/musl/commit/src/sched/sched_setscheduler.c?id=1e21e78bf7a5c24c217446d8760be7b7188711c2

**Comment by MaxKellermann** [comment]
This is a pretty stupid commit. Because it's wrong on many levels.

> the PS (process scheduling) functionality which the sched_* functions are supposed to have
This is wrong because **all** `sched_*` functions operate on a thread, and never on a process.

> the only conforming way to do this on linux. 
And this is a funny thing to say, because the `sched_*` functions are Linux-specific. What else, if not "Linux", shall this conform to?

> since some broken software assumes they exist
These are basic thread management system calls, and it is reasonable to assume they exist if you're compiling for Linux.

**Comment by richfelker** [comment]
POSIX specifies the sched_* functions, and the Linux syscalls do not do what the sched_* functions are specified to do. Rather, they implement the functionality specified for the pthread_setschedparam, etc. functions. glibc acknowledges this (see [bug 14829](https://sourceware.org/bugzilla/show_bug.cgi?id=14829#c1)) but is stuck with the legacy mistake for now for compatibility reasons. The correct way to set the scheduling priority of a thread on either musl or glibc is pthread_setschedparam. There is no way to set the scheduling priority of a process on Linux.

**Comment by MaxKellermann** [comment]
Ok, the answer to "What else, if not "Linux", shall this conform to?" is "POSIX has functions with the same name". I admit I didn't know that this definition exists, so this part of my complaint was wrong, sorry for that.
But this part of Linux is explicitly not POSIX-compliant and is documened that way (I misunderstood that part), and there is also (AFAIK) no other Linux system call which would allow a POSIX-compliant implementation. Of course, being explicitly not POSIX-compliant is unfortunate, and choosing a POSIX name was a bad decision.
In any case, software which assumes `posix_*` exists is not broken. It either expects POSIX standard semantics, or it expects Linux standard semantics with an #ifdef.

**Comment by mistepien** [comment]
That works great! I merged this with git.

I have one question. At the start on thread there is one thread "{output:V102,0 [} mpd" with realtime scheduling. If resampling is necessary second thread "{output:V102,0 [} mpd" is created but the new one has no real-time scheduling. Is that supposed to be so?

**Comment by MaxKellermann** [comment]
This thread is created and managed by libsoxr, and out of MPD's control.

**Comment by mistepien** [comment]
If libsoxr is compiled with -DWITH_OPENMP=OFF there is no additional thread but it will not utilize SMP machines. This is my last question: whether this thread do anything related to audio buffer xruns?
