### ISSUE TITLE
Sending incorrect password after the correct password does not revoke permissions

### ISSUE THREAD

**Issue by geneticdrift** [MusicPlayerDaemon/MPD#225]
Tested in version 0.21.0,

This is probably a minor issue, but still seems inconsistent.
Sending a correct password (out of several possible) sets the configured permissions on the connection, but then sending an incorrect password leaves the connection with the permission grunted by the previously correct password.

**Comment by MaxKellermann** [comment]
Why is this an issue at all? The incorrect password command fails, so it has no effect.

**Comment by geneticdrift** [comment]
OK, if it is considered a failed command then the connection state doesn't change.
I wrongly expected the wrong password to revert to the default permissions as configured.
