### ISSUE TITLE
Add support for satellite mode in MPD for Android

### ISSUE THREAD

**Issue by sandebert** [MusicPlayerDaemon/MPD#226]
I'm wondering if this is on the roadmap, and if so if there's a (rough) estimate for when it would show up? As I understood it, one would need to add support for NFS. I have no idea how complex that is though.

(It's so very attractive to make the phone play all the music served by the MPD server on the LAN.)

**Comment by gerroon** [comment]
Have you tried Mpd under Termux?  That is how I use it on my phone.

**Comment by sandebert** [comment]
> Have you tried Mpd under Termux?

Whoa, the thought never crossed my mind - great idea. Aaaaand I was just about to give it a shot, but it seems @MaxKellermann is just about to add NFS to the Android app. I might try the Termux way, but I'll wait a while to see if a new Android version is just about to be published.

**Comment by gerroon** [comment]
You can use Pulseaudio and the sound card (beside other outputs) as well, at leasts those work on my phone.
