### ISSUE TITLE
Icecast playlist.log reporting duplicate entries

### ISSUE THREAD

**Issue by madprops** [MusicPlayerDaemon/MPD#230]
Originally I posted this on Icecast's github. But they told me it was more relevant here.

Icecast has a feature to log the played history in a file called playlist.log
This is what it reported.

Notice the duplicates. They told me it's most likely an MPD issue, by reporting the song twice.

Unless they really played twice like that, but that would be a very big coincidence, sine the library is pretty big.

> 20/Feb/2018:12:07:37 -0500|/wok3n|1|MtH - 7MLGD
20/Feb/2018:12:11:04 -0500|/wok3n|1|emune - lifted
**20/Feb/2018:12:13:05 -0500|/wok3n|1|Gorillaz - On Melancholy Hill
20/Feb/2018:12:16:58 -0500|/wok3n|1|Gorillaz - On Melancholy Hill**
20/Feb/2018:12:16:59 -0500|/wok3n|1|nix - you  prod. alembic
20/Feb/2018:12:21:15 -0500|/wok3n|1|Orlando Díaz - Ser Sub
**20/Feb/2018:12:24:21 -0500|/wok3n|1|Veruca Salt - Victrola
20/Feb/2018:12:26:39 -0500|/wok3n|0|Veruca Salt - Victrola**
20/Feb/2018:12:26:40 -0500|/wok3n|0|Apollo Brown - Tao Te Ching
20/Feb/2018:12:28:42 -0500|/wok3n|1|Augustus Pablo - 555 Dub Street
20/Feb/2018:12:31:15 -0500|/wok3n|0|Rites of Spring - For Want Of
20/Feb/2018:12:34:17 -0500|/wok3n|0|kidkanevil - Shunkanido
20/Feb/2018:12:38:45 -0500|/wok3n|0|Animal Collective - Bluish
20/Feb/2018:12:43:58 -0500|/wok3n|0|THiNGYBOBinc - Jet Set Auradio
20/Feb/2018:12:45:57 -0500|/wok3n|0|Quickly, Quickly - Fog
**20/Feb/2018:12:49:21 -0500|/wok3n|0|J Dilla - Stepson of the Clapper
20/Feb/2018:12:50:12 -0500|/wok3n|0|J Dilla - Stepson of the Clapper**
20/Feb/2018:12:50:13 -0500|/wok3n|0|Gang Starr - Soliloquy Of Chaos
**20/Feb/2018:12:53:17 -0500|/wok3n|0|Nujabes - Music Is Mine
20/Feb/2018:12:57:27 -0500|/wok3n|0|Nujabes - Music Is Mine**
20/Feb/2018:12:57:27 -0500|/wok3n|0|My Bloody Valentine - Blown a Wish

**Comment by MaxKellermann** [comment]
MPD doesn't report "songs" to Icecast. So what is this really about?
