### ISSUE TITLE
UnicodeDecodeError when list artist (on Windows 10)

### ISSUE THREAD

**Issue by handsomegui** [MusicPlayerDaemon/MPD#231]
Hi, i found an UnicodeDecodeError with the latest version of MPD on Windows platform.  

```
OS: Windows 10 Pro  (Simplified Chinese)
MPD:  0.20.16 ~
python: 2.7.14 64bit
python-mpd2: 1.0.0
```

When i **list artist** from client library `python-mpd2`, will trigger the **UnicodeDecodeError** for my music directory.

After i move out a big audio folder from the music_directory( to a place outside the music_directory, then rescan the music_directory), the above error gone. 

From the MPD protocol document:
```
All data between the client and the server is encoded in UTF-8.
```

So i guess there might have UTF-8 encoding/decoding related bug for some special characters.

It may helpful to also read this related report(with detailed error info): https://github.com/Mic92/python-mpd2/issues/93

**Comment by handsomegui** [comment]
I have lots of audio files under my `music_directory`. 

Currently i still can not figure out how to pick out the "error" file which contains the error encoding artist meta info.

I try to add one debug line to print out the error decoding string in the `python-mpd2` lib file.
It shows me the below info. (I am not sure if this helps. Sorry.)

```
DEBUG INFO: OK

DEBUG INFO: Artist: 

DEBUG INFO: Artist: ????

DEBUG INFO: Artist: ????????????_??????????¼??

DEBUG INFO: Artist: ????????л??˳??

DEBUG INFO: Artist: ??????ȫ???ݳ?

DEBUG INFO: Artist: ?????��????ƽ?

UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 13: invalid start byte
```

Any help is appreciated.

**Comment by handsomegui** [comment]
After i set `pdb` to trace the specific failure point for the `python-mpd2` lib file:
```python
    def decode_str(s):
        try:
            return s.decode("utf-8")
        except Exception as e:
            print(s)
            print([c for c in s])
            import pdb; pdb.set_trace()

```
Below is what i got:

```
Artist: ?????��????ƽ?

['A', 'r', 't', 'i', 's', 't', ':', ' ', '?', '?', '?', '?', '?', '\xc0', '\xa1', '?', '?', '?', '?', '\xc6', '\xbd', '?', '\n']
--Return--
> c:\python27\lib\site-packages\mpd\base.py(54)decode_str()->None
-> import pdb; pdb.set_trace()
(Pdb) 
```
Sorry for my poor knowledge, currently i have no clue to find out the specific file:( 

I hope this can help.

**Comment by handsomegui** [comment]
@MaxKellermann  Max, can you re-open this issue? Thanks.

**Comment by MaxKellermann** [comment]
No, I won't reopen this until I have the packet capture.

**Comment by guizhenwei** [comment]
@MaxKellermann 

Sorry for the delay. I finally picked out the file which caused the UTF-8 decoding error:

https://www.dropbox.com/s/f72ti62v7op6biu/KPSU.mp3?dl=0

Please help to debug.

And it would be nice if this issue can be re-opened.
