### ISSUE TITLE
No sound when playing DSD files

### ISSUE THREAD

**Issue by ericxxxx** [MusicPlayerDaemon/MPD#233]
No sound when playing DSD(.dff & .dsf) files, mpd is running, dsd file is playing and the DAC(Chord Mojo) detects it is a DSD file but no sound. PCM files are playing great. Switched back to stable version of 0.20.17, both DSD & PCM files are OK again.
********************
git clone https://github.com/MusicPlayerDaemon/MPD.git
complied in a linux machine

mpd -V
Music Player Daemon 0.21 (v0.20.17-911-g9f6af4f2c)

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mpd.conf
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
db_file "/var/lib/mpd/tag_cache"
sticker_file "/var/lib/mpd/sticker.sql"
log_file "/var/log/mpd/mpd.log"
pid_file "/var/run/mpd/pid"
music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
state_file "/var/lib/mpd/state"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
zeroconf_enabled "yes"
zeroconf_name "xxxxx MPD"
volume_normalization "no"
audio_buffer_size "4096"
buffer_before_play "10%"
filesystem_charset "UTF-8"
id3v1_encoding "UTF-8"
gapless_mp3_playback "no"
auto_update "no"
mixer_type "disabled"
max_output_buffer_size "81920"
restore_paused "yes"
replaygain "off"
max_connections "20"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

audio_output {
type "alsa"
name "ALSA default" 
device "hw:1,0" 
dop "yes"
}

mpd.log

Feb 24 01:38 : client: [26] opened from 127.0.0.1:53338
Feb 24 01:38 : client: [26] process command "close"
Feb 24 01:38 : client: [26] command returned 3
Feb 24 01:38 : client: [26] closed
Feb 24 01:38 : decoder: audio_format=dsd128:2, seekable=true
Feb 24 01:38 : alsa_output: opened hw:1,0 type=HW
Feb 24 01:38 : alsa_output: buffer: size=90..131072 time=255..371520
Feb 24 01:38 : alsa_output: period: size=45..65536 time=127..185760
Feb 24 01:38 : alsa_output: default period_time = buffer_time/4 = 371519/4 = 92879
Feb 24 01:38 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Feb 24 01:38 : alsa_output: buffer_size=131072 period_size=32768
Feb 24 01:38 : alsa_output: DoP (DSD over PCM) enabled
Feb 24 01:38 : output: opened "ALSA default" (alsa) audio_format=dsd128:2
Feb 24 01:38 : client: [27] opened from 127.0.0.1:53342
Feb 24 01:38 : client: [27] process command "status"
Feb 24 01:38 : client: [27] command returned 0
Feb 24 01:38 : client: [27] process command "currentsong"
Feb 24 01:38 : client: [27] command returned 0

cat /proc/asound/card*/pcm*p/sub*/hw_params
closed
closed
closed
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 352800 (352800/1)
period_size: 32768
buffer_size: 131072

**Comment by MaxKellermann** [comment]
Please bisect.

**Comment by ericxxxx** [comment]
Log files captured from stable version of 0.20.17.
*************************************************

mpd -V

Music Player Daemon 0.20.17

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mpd.log

Feb 24 13:49 : client: [83] process command "close"
Feb 24 13:49 : client: [83] command returned 3
Feb 24 13:49 : client: [83] closed
Feb 24 13:49 : decoder_thread: probing plugin dsf
Feb 24 13:49 : decoder: audio_format=dsd128:2, seekable=true
Feb 24 13:49 : alsa_output: opened hw:1,0 type=HW
Feb 24 13:49 : alsa_output: buffer: size=90..131072 time=255..371520
Feb 24 13:49 : alsa_output: period: size=45..65536 time=127..185760
Feb 24 13:49 : alsa_output: default period_time = buffer_time/4 = 371519/4 = 92879
Feb 24 13:49 : alsa_output: format=S32_LE (Signed 32 bit Little Endian)
Feb 24 13:49 : alsa_output: buffer_size=131072 period_size=32768
Feb 24 13:49 : alsa_output: DoP (DSD over PCM) enabled
Feb 24 13:49 : output: opened plugin=alsa name="ALSA default" audio_format=dsd128:2
Feb 24 13:50 : client: [84] opened from 127.0.0.1:49147
Feb 24 13:50 : client: [84] process command "status"
Feb 24 13:50 : client: [84] command returned 0


cat /proc/asound/card*/pcm*p/sub*/hw_paramsclosed
closed
closed
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 352800 (352800/1)
period_size: 32768
buffer_size: 131072

**Comment by MaxKellermann** [comment]
https://git-scm.com/docs/git-bisect

**Comment by ericxxxx** [comment]
Hope that I've done it right.
***********************
git bisect log

git bisect start
# bad: [1628d801f9534ab33a711d337cdd691dca2c5710] playlist/Queue: add one-shot to single mode
git bisect bad 1628d801f9534ab33a711d337cdd691dca2c5710
# good: [cf86dfd3178bcdffbb2968cda4ad9c271ffdc4f3] release v0.20.9
git bisect good cf86dfd3178bcdffbb2968cda4ad9c271ffdc4f3
# good: [c582a9faae16247d4646f5128312dfbda950c376] event/MultiSocketMonitor: add "noexcept"
git bisect good c582a9faae16247d4646f5128312dfbda950c376
# bad: [be068f360d780ece0da2bdf76de1d1ae608a5803] Merge remote-tracking branches 'mmuman/configure-sockaddr-sin-len' and 'mmuman/haiku-build-fix'
git bisect bad be068f360d780ece0da2bdf76de1d1ae608a5803
# good: [6439727afc515bc0244d8be020e6946dbf6bca10] player/Thread: use std::lock_guard in RunThread()
git bisect good 6439727afc515bc0244d8be020e6946dbf6bca10
# bad: [0a4b866d8a191949a2b85a121418457d713342cf] db/upnp: use SplitString() instead of stringToTokens()
git bisect bad 0a4b866d8a191949a2b85a121418457d713342cf
# good: [8838bdc1e30bc76a446cefda47559c482cd1e2e6] player/Thread: move CommandFinished() call out of SeekDecoder(SongTime)
git bisect good 8838bdc1e30bc76a446cefda47559c482cd1e2e6
# bad: [10537c5095258b88cdc13beac06577b335bbf6ee] test/run_filter: use "auto"
git bisect bad 10537c5095258b88cdc13beac06577b335bbf6ee
# good: [7171e237007db547088c38295a7351573c0d79bf] player/Thread: make seeking into a new song non-blocking
git bisect good 7171e237007db547088c38295a7351573c0d79bf
# bad: [78c73fb9e7cb388ba58d26098098b31d53e52489] MusicChunk: reorder attributes to reduce padding
git bisect bad 78c73fb9e7cb388ba58d26098098b31d53e52489
# good: [de0c3e717e82508499ae572cfdf7423a3e36259b] MusicChunk: split struct MusicChunkInfo from struct MusicChunk
git bisect good de0c3e717e82508499ae572cfdf7423a3e36259b

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[a06bf388d968279808009d4538def57e78b4bee7] MusicChunk: make the struct size exactly 4096
**************

git bisect visualize

commit 78c73fb9e7cb388ba58d26098098b31d53e52489
Author: Max Kellermann <max@musicpd.org>
Date:   Sat Dec 30 17:52:07 2017 +0100

    MusicChunk: reorder attributes to reduce padding

commit a06bf388d968279808009d4538def57e78b4bee7
Author: Max Kellermann <max@musicpd.org>
Date:   Sat Dec 30 17:42:43 2017 +0100

    MusicChunk: make the struct size exactly 4096

**Comment by ericxxxx** [comment]
a06bf388d968279808009d4538def57e78b4bee7 is the first bad commit
commit a06bf388d968279808009d4538def57e78b4bee7
Author: Max Kellermann <max@musicpd.org>
Date:   Sat Dec 30 17:42:43 2017 +0100

    MusicChunk: make the struct size exactly 4096

:040000 040000 cd2e798e523da89e9a19e21f6582b6b2ec62974c 0a9027ec474cfbd05c894ff766758c5339dcf8cf M	src

git bisect log
*******
git bisect start
# bad: [1628d801f9534ab33a711d337cdd691dca2c5710] playlist/Queue: add one-shot to single mode
git bisect bad 1628d801f9534ab33a711d337cdd691dca2c5710
# good: [cf86dfd3178bcdffbb2968cda4ad9c271ffdc4f3] release v0.20.9
git bisect good cf86dfd3178bcdffbb2968cda4ad9c271ffdc4f3
# good: [c582a9faae16247d4646f5128312dfbda950c376] event/MultiSocketMonitor: add "noexcept"
git bisect good c582a9faae16247d4646f5128312dfbda950c376
# bad: [be068f360d780ece0da2bdf76de1d1ae608a5803] Merge remote-tracking branches 'mmuman/configure-sockaddr-sin-len' and 'mmuman/haiku-build-fix'
git bisect bad be068f360d780ece0da2bdf76de1d1ae608a5803
# good: [6439727afc515bc0244d8be020e6946dbf6bca10] player/Thread: use std::lock_guard in RunThread()
git bisect good 6439727afc515bc0244d8be020e6946dbf6bca10
# bad: [0a4b866d8a191949a2b85a121418457d713342cf] db/upnp: use SplitString() instead of stringToTokens()
git bisect bad 0a4b866d8a191949a2b85a121418457d713342cf
# good: [8838bdc1e30bc76a446cefda47559c482cd1e2e6] player/Thread: move CommandFinished() call out of SeekDecoder(SongTime)
git bisect good 8838bdc1e30bc76a446cefda47559c482cd1e2e6
# bad: [10537c5095258b88cdc13beac06577b335bbf6ee] test/run_filter: use "auto"
git bisect bad 10537c5095258b88cdc13beac06577b335bbf6ee
# good: [7171e237007db547088c38295a7351573c0d79bf] player/Thread: make seeking into a new song non-blocking
git bisect good 7171e237007db547088c38295a7351573c0d79bf
# bad: [78c73fb9e7cb388ba58d26098098b31d53e52489] MusicChunk: reorder attributes to reduce padding
git bisect bad 78c73fb9e7cb388ba58d26098098b31d53e52489
# good: [de0c3e717e82508499ae572cfdf7423a3e36259b] MusicChunk: split struct MusicChunkInfo from struct MusicChunk
git bisect good de0c3e717e82508499ae572cfdf7423a3e36259b
# bad: [a06bf388d968279808009d4538def57e78b4bee7] MusicChunk: make the struct size exactly 4096
git bisect bad a06bf388d968279808009d4538def57e78b4bee7
# first bad commit: [a06bf388d968279808009d4538def57e78b4bee7] MusicChunk: make the struct size exactly 4096
