### ISSUE TITLE
failed to decide mp3

### ISSUE THREAD

**Issue by nature2608** [MusicPlayerDaemon/MPD#236]
when i using windows 10 professional media player play mp3 with upmpdcli ,it can’t play but flac is normal. mpd.conf is  default。May i need to change somewhere ?
compiled with 4.9.82 kernel in openwrt x86

**Comment by MaxKellermann** [comment]
This project is not about Media Player, Windows, upmpdcli nor Kernel or OpenWRT. And I have really no clue what you are talking about.
