### ISSUE TITLE
 Unrecognized Vorbis BOS packet

### ISSUE THREAD

**Issue by Xanderio** [MusicPlayerDaemon/MPD#239]
decoder_thread: probing plugin vorbis
exception: Failed to decode file.ogg
exception: nested: Unrecognized Vorbis BOS packet

ffmpeg reports:
   Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp

**Comment by MaxKellermann** [comment]
Everything is missing in this bug report.

**Comment by Xanderio** [comment]
I'm sorry for providing not infomation, but the issue is now resolved. Opus support was not enable by default in the freebsd binary package
