### ISSUE TITLE
Tidal lossless fails to play

### ISSUE THREAD

**Issue by msmucr** [MusicPlayerDaemon/MPD#244]
Hi,

thank you for added Tidal input plugin for MPD. There is great potential for future consolidated playback of those services at dedicated player without Sonos, Roon or so.
I've grabbed and compiled current MASTER (03.03.2018) for Linux x86_64. It generally works, seeks, plays  (even with Replaygain, which is HUGE) with their AAC streams, but I haven't managed to get working lossless quality FLAC playback.

There can be some user error at my side, although input plugin doesn't have so much settings.
I tested to mess (increase, decrease) with total buffer size and initial portion before playback.. but no avail.

`tidal: Sending login request
tidal: Login successful, session=7bb0d484-a9e3-4899-99c9-61ef16618014
tidal: Tidal track '70789663' resolves to http://audio-enc.tidal.com/v2/0/e2eed31ee1b853d2ed65e4d32b33f6
2e_26.flac?__token__=exp=1520112876~hmac=ac3edb6424095f851be1d91b672509ad8004acd895d719c1c1560fb9c36f48a
0
decoder_thread: probing plugin flac
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
...
decoder_thread: probing plugin ffmpeg
exception: Failed to decode tidal://track/70789663
player: played "tidal://track/70789663"
playlist: stop
`

... apparently after a while it tries a FFMPEG decoder, which also supports FLAC, and then finally give up.
Any ideas? Is it working for you?

All the best,

Michal

**Comment by iamsi** [comment]
Hi Michal, I can re-produce this by using an api key that delivers encrypted versions of the flac files. if you play another track and wget that "resolves to" line you'll see it's not a flac file. Using a different API key will resolve the issue.
```
pi@Office:~/mpd/MPD $ file good.flac
good.flac: FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 9537890 samples
pi@Office:~/mpd/MPD $ file bad.flac
bad.flac: data
```

**Comment by msmucr** [comment]
Hi Iamsi, 
that's likely the culprit. I've used just the sniffed API key from their normal desktop client. I'll try to look for another one and possibly report any change.
Thank you for the hint!

Michal

**Comment by msmucr** [comment]
That was the issue! Thank you very much.
I had no idea, different API tokens may cause such weird behavior just with specific stream types. Because typically, when you don't have a right API key to some service, it will either let you know with some meaningful response or it will fails to work right after auth phase (for immediately after processing of track request)
Just tor the reference and when someone else would be reading this, another symptom of invalid token is this all catching response from Tidal API server, when you try to initiate playback:
`exception: Error from Tidal: Ooops, an unexpected error occurred. We'll try to fix this asap!`.
With the right token, it plays unencrypted streams and doesn't produce such errors.

All the best,
Michal

**Comment by MaxKellermann** [comment]
Uh, so if you have the wrong Tidal API token, you get garbage instead of an error message?

**Comment by msmucr** [comment]
Exactly, that surprised me as well.. ;) Because with invalid token, it would be much more logical to rather doesn't stream at all and signal that to the client right at API level.

**Comment by iamsi** [comment]
you can detect it, in the track JSON response you'll see there is a "SecurityToken" if this is null it's unencrypted, if it has data the file is encrypted.

**Comment by msmucr** [comment]
That makes sense, Iamsi. Thanks!
To be frank, I haven't really sniffed and analyzed much of communication of different Tidal clients and neither I am their registered developer, so it just initially surprised me, l've got different content or based on different API keys..
Anyway.. as I'm looking to that in browser, there's also "securityType" field in their respose, which shows "TIDAL_BASIC", when encrypted or it's null, when unencrypted.
So without knowing their API documentation, that looks like better field to work with in some response handler, if it will be feasible to distinguish between encrypted and unencrypted streams.
