### ISSUE TITLE
multiple unnecessary idle subsystem notifications?

### ISSUE THREAD

**Issue by torumyax** [MusicPlayerDaemon/MPD#246]
Hi!
I've just created a yet another client for MPD.
https://github.com/torumyax/MPD-Ctrl

And I realized that sending this,

**command_list_begin
clear
load MyPlaylist
play
command_list_end**

returns multiple idle notifications such as,

**changed: playlist
changed: player
OK**

**changed: player
OK**

**changed: player
OK**

causing clients to issue "status" command multiple times unnecessarily. I think the latter 2 notifications are not really necessary...

Cheers!

**Comment by torumyax** [comment]
I forgot to mention that I'm using MPD from apt repo on Ubuntu 17.10. The protocol version is 0.20.0. And sorry for my English. English isn't my language. Thanks!

**Comment by MaxKellermann** [comment]
Since you did not specify a MPD version, I had to look it up for you. It's 0.20.9, and that version is unsupported.

**Comment by torumyax** [comment]
Thank you very very much for your reply. I love MPD. And I appreciate your work. BTW, I just submitted my client app to Store a few minutes ago, so hopefully, it will be available soon.
