### ISSUE TITLE
Play nonexistent mmsh stream freezes MPD 

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#252]
MPD from git, Debian x64 testing, libmms 0.6.4 from distribution.

Add nonexistent stream mmsh://foo.bar eg. mpc add mmsh://foo.bar and select stream for playing. MPD becomes unresponsive and needs to be terminated with kill -9.

client: [0] process command "load "mmsh://mediau.yle.fi/a_radiosavo?MSWMExt=.asf#YLE""
[New Thread 0x7fffd27fc700 (LWP 1200)]
bt

MPD killed with -9

[Thread 0x7ffff7f9e540 (LWP 1189) exited]
[Thread 0x7fffd27fc700 (LWP 1200) exited]
[Thread 0x7fffd2ffd700 (LWP 1198) exited]
[Thread 0x7fffd37fe700 (LWP 1197) exited]
[Thread 0x7fffd970b700 (LWP 1194) exited]
[Thread 0x7fffd8f0a700 (LWP 1195) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.

**Comment by MaxKellermann** [comment]
Your description and your log show completely different actions.
Post backtrace of frozen MPD.

**Comment by skidoo23** [comment]
playlist: play 12:"mmsh://foo.bar"
[New Thread 0x7fffd27fc700 (LWP 1853)]
[Thread 0x7fffd27fc700 (LWP 1853) exited]

<<< kill -9 mpd.pid >>>

[Thread 0x7fffd37fe700 (LWP 1836) exited]
[Thread 0x7fffd3fff700 (LWP 1835) exited]
[Thread 0x7fffd8eea700 (LWP 1834) exited]
[Thread 0x7fffd96eb700 (LWP 1833) exited]
[Thread 0x7ffff7f9e540 (LWP 1828) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.

**Comment by MaxKellermann** [comment]
There's no backtrace and your second paste shows a different action again.

**Comment by skidoo23** [comment]
MPD master from git, made clean compiled with --enable-mms --enable-debug (Debian testing x64) other (virtual) machine.

# gdb --args /opt/mpd/bin/mpd --stdout --no-daemon --verbose
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/mpd/bin/mpd...done.
(gdb) run
Starting program: /opt/mpd/bin/mpd --stdout --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
config_file: loading file /opt/mpd/etc/mpd.conf
soxr: soxr converter 'very high'
simple_db: reading DB
[New Thread 0x7fffefa0f700 (LWP 5580)]
[New Thread 0x7fffef20e700 (LWP 5581)]
[New Thread 0x7fffeea0d700 (LWP 5582)]
state_file: Loading state file /opt/mpd/var/lib/state
[New Thread 0x7fffee20c700 (LWP 5583)]
inotify: initializing inotify
inotify: watching music directory

<<< mpc add mmsh://foo.bar >>>
client: [1] opened from 127.0.0.1:53096
client: [1] process command list
client: process command "add "mmsh://foo.bar""
client: command returned 0
client: [1] process command list returned 0
client: [1] closed
state_file: Saving state file /opt/mpd/var/lib/state

<<< $ mpc play 1 >>>
client: [2] opened from 127.0.0.1:53098
client: [2] process command "play "0""
playlist: play 0:"mmsh://foo.bar"
[New Thread 0x7fffed5cb700 (LWP 5589)]
client: [2] command returned 0
playlist: queue song 1:"mmsh://foo.bar"
client: [2] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [2] process command list returned 0
client: [2] closed
[Thread 0x7fffed5cb700 (LWP 5589) exited]

<<< $ mpc play 1 >>>
playlist: queue song 1:"mmsh://foo.bar"
client: [2] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [2] process command list returned 0
client: [2] closed
[Thread 0x7fffed5cb700 (LWP 5589) exited]
client: [3] opened from 127.0.0.1:53100
client: [3] process command "play "0""
playlist: play 0:"mmsh://foo.bar"

<<< mpd error: Timeout >>>
bt
<<< kill -9 (mpd.pid) >>>
[Thread 0x7fffee20c700 (LWP 5583) exited]
[Thread 0x7fffeea0d700 (LWP 5582) exited]
[Thread 0x7fffefa0f700 (LWP 5580) exited]
[Thread 0x7fffef20e700 (LWP 5581) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)
(gdb)
(gdb)
(gdb) bt
No stack.

Please give further advice.

**Comment by MaxKellermann** [comment]
You can't obtain a backtrace after slaying the MPD process forcefully. This must be made while MPD is still alive.

**Comment by skidoo23** [comment]
Sorry, no output from "bt" command.

**Comment by MaxKellermann** [comment]
Then you have a broken gdb.

**Comment by skidoo23** [comment]
Applied fix to git. Now MPD terminates without delay when trying to play (even existing) mms streams. Ouch.

**Comment by MaxKellermann** [comment]
Then write a proper bug report. It is very hard to help you this way, without information.
