### ISSUE TITLE
Play mms stream makes MPD v0.20 (git) quit

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#253]
MPD 0.20 from git, Debian x64 testing, libmms 0.6.4 from distribution. Compiled with --enable-mms and --enable-debug

# /opt/mpd/bin/mpd --no-daemon --verbose
config_file: loading file /opt/mpd/etc/mpd.conf
Mar 14 18:23 : soxr: soxr converter 'very high'
Mar 14 18:23 : simple_db: reading DB

$ mpc add mms://mediau.yle.fi/liveradiosuomi
$ mpc play 1
mms://mediau.yle.fi/liveradiosuomi

If neccessary repeat "mpc play 1" multiple times.
Abgebrochen (Cancelled)

mpd.log
Mar 14 18:24 : client: process command "add "mms://mediau.yle.fi/liveradiosuomi""
Mar 14 18:24 : client: command returned 0
Mar 14 18:24 : client: [0] process command list returned 0
Mar 14 18:24 : client: [0] closed
Mar 14 18:24 : state_file: Saving state file /opt/mpd/var/lib/state
Mar 14 18:24 : client: [1] opened from 127.0.0.1:38906
Mar 14 18:24 : client: [1] process command "play "0""
Mar 14 18:24 : playlist: play 0:"mms://mediau.yle.fi/liveradiosuomi"
Mar 14 18:24 : client: [1] command returned 0
Mar 14 18:24 : client: [1] process command list
Mar 14 18:24 : client: process command "status"
Mar 14 18:24 : client: command returned 0
Mar 14 18:24 : client: process command "currentsong"
Mar 14 18:24 : client: command returned 0
Mar 14 18:24 : client: [1] process command list returned 0
Mar 14 18:24 : client: [1] closed
pure virtual method called
terminate called without an active exception

**Comment by MaxKellermann** [comment]
Can't reproduce. Post a backtrace. (This time for real.)

**Comment by skidoo23** [comment]
Here we go

client: process command "add "mms://mediau.yle.fi/liveradiosuomi""
client: command returned 0
client: [0] process command list returned 0
client: [0] closed
client: [1] opened from 127.0.0.1:33620
client: [1] process command "play "0""
playlist: play 0:"mms://mediau.yle.fi/liveradiosuomi"
client: [1] command returned 0
client: [1] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [1] process command list returned 0
client: [1] closed
[New Thread 0x7fffed5b9700 (LWP 911)]
pure virtual method called
terminate called without an active exception

Thread 6 "input:mms" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffed5b9700 (LWP 911)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb)
(gdb)
(gdb)
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff111f231 in __GI_abort () at abort.c:79
#2  0x00007ffff19655a9 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff196b7fa in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff196b855 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff196c5f3 in __cxa_pure_virtual ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555b41f9 in ThreadInputStream::ThreadFunc (this=0x7fffe0000b20)
    at src/input/ThreadInputStream.cxx:89
#7  0x00005555555cc9f3 in BoundMethod<void ()>::operator()() const (
    this=0x7fffe0000b98) at ./src/util/BindMethod.hxx:77
#8  Thread::Run (this=0x7fffe0000b98) at src/thread/Thread.cxx:64
#9  Thread::ThreadProc (ctx=0x7fffe0000b98) at src/thread/Thread.cxx:93
#10 0x00007ffff14aa5aa in start_thread (arg=0x7fffed5b9700)
    at pthread_create.c:463
#11 0x00007ffff11dfcbf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
