### ISSUE TITLE
AlbumArtist find is not falling back to Artist

### ISSUE THREAD

**Issue by mxjeff** [MusicPlayerDaemon/MPD#254]
Here is a follow-up of [the thread "find command with albumartist type"](http://mailman.blarg.de/pipermail/mpd-devel/2018-March/000730.html).

I have an album of 5 tracks, only one of them is tagged with AlbumArtist.

Running a find command on AlbumArtist I should get only this track, here is what I got:

```bash
printf 'find albumartist "La Jungle" \nclose \n' | \
    nc localhost 6600 | \
    awk -F: 'tolower($1) ~ /^(albumartist|album|file)/'
```

```txt
file: La Jungle/2016-II/01-La Jungle - Hahehiho.flac
Album: II
Artist: La Jungle
AlbumArtist: La Jungle
file: La Jungle/2016-II/02-La Jungle - Technically You're Dead.flac
Album: II
Artist: La Jungle
file: La Jungle/2016-II/03-La Jungle - Helizona.flac
Album: II
Artist: La Jungle
file: La Jungle/2016-II/04-La Jungle - Blood Watermelon.flac
Album: II
Artist: La Jungle
file: La Jungle/2016-II/05-La Jungle - Cold.flac
Album: II
Artist: La Jungle
```

  * output of “mpd --version”

  Tested with 0.20.11, 0.20.18 and  0.19.21 (>0.20 tested with docker builds, 1.19.21 is Debian/Stretch build).

  * be clear about what you expect MPD to do, and what is actually happening

The find command should fall back to Artist find only when AlbumArtist returns no results.

  Expecting a single track found, ie. "file: La Jungle/2016-II/01-La Jungle - Hahehiho.flac":

```bash
printf 'find albumartist "La Jungle" \nclose \n' | \
    nc localhost 6600 | \
    awk -F: 'tolower($1) ~ /^(albumartist|album|file)/'
```

```txt
file: La Jungle/2016-II/01-La Jungle - Hahehiho.flac
Album: II
Artist: La Jungle
AlbumArtist: La Jungle
file: La Jungle/2016-II/02-La Jungle - Technically You're Dead.flac
```

  There are no relevant log messages associated.

**Comment by MaxKellermann** [comment]
This fallback is per song, not per result. What you see is correct behavior.
