### ISSUE TITLE
Clicks with DSD files in native DSD mode

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#262]
This is hardware:

> Amanero Technologies Combo384 Amanero at usb-0000:00:1d.7-6, high speed : USB Audio
Playback:
  Status: Running
    Interface = 2
    Altset = 2
    Packet Size = 136
    Momentary freq = 88195 Hz (0xb.0640)
    Feedback Format = 16.16
  Interface 2
    Altset 1
    Format: S32_LE
    Channels: 2
    Endpoint: 5 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
    Data packet interval: 125 us
  Interface 2
    Altset 2
    Format: S32_LE DSD_U32_BE
    Channels: 2
    Endpoint: 5 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
    Data packet interval: 125 us`

With 0.20 DSD files play just fine. In mpd-git it do not. There are audible clicks.

Maybe this should be extended upon native DSD?
https://github.com/MusicPlayerDaemon/MPD/commit/a2340c313f49d45abf3ade4645264e45c54918c7

BTW, mpd-git before half of december 2017 is ok.

**Comment by MaxKellermann** [comment]
Please bisect.

**Comment by sa1010** [comment]
I get the click/pop noises when switching to DSD. 

MPD Version: 0.20.18
DAC: DIYINHK USB Audio 2.0  (AK4497) and XMOS XU216.
OS: Ap-Linux 4.0

**Comment by MaxKellermann** [comment]
@sa1010 different problem, write a new bug report and explain why you believe this is MPD's fault.

**Comment by MaxKellermann** [comment]
I'll reopen this as soon as I have feedback.

**Comment by manolomalele** [comment]
Hi, I have to report the same issue. Playing dsd natively, and only DSD I can hear clicks and pops randomly during playback.
Any fix to this problem?
