### ISSUE TITLE
exception: Input plugin 'ffmpeg' is unavailable: No protocol

### ISSUE THREAD

**Issue by mapomme1108** [MusicPlayerDaemon/MPD#267]
Hello,

I want to use Music Player Daemon on Windows 10 x64.
Whatever the version of mpd.exe I use, there is this error message when I execute 
"mpd.exe mpd.conf"

"exception: Input plugin 'ffmpeg' is unavailable: No protocol"

I have downloaded ffmpeg's binaries and added them to the system environment but the message is still here and I cannot use MPD.

What could be the problem?

**Comment by MaxKellermann** [comment]
MPD comes with FFmpeg linked statically. Your DLLs will not be used.

Does this log message bother you? I can suppress it, would this solve your problem?

**Comment by mapomme1108** [comment]
Hello,
You don't have to suppress it because it works anyway. I thought the message was blocking MPD.
Thanks!
