### ISSUE TITLE
24 bit fails with flac and pipe

### ISSUE THREAD

**Issue by audiofool** [MusicPlayerDaemon/MPD#268]
The issue I am having involves playing 192khz 24 bit flac using audio_output type pipe.  The audio_format assigned is 192000:24:2, I believe this should be 192000:32:2.  

If I override the format with "*:32:*" it works but I require *:*:* for my pipe.  I captured the raw stream as a file and it would not play using play -r 192000 -c 2 -b 32(or 24) -e signed  ./fifo.raw.  Playing a raw file created using flac -d infile.flac outfile.raw  plays fine with play -r 192000 -b 32

Below is the relevant logs and versions - using Arch Linux so should be current

I took a quick look at the code, may be something to do with S24_P32?

=Log=
Apr 19 20:38 : client: [2] process command "playid "5""
Apr 19 20:38 : playlist: play 4:"Mark Knopfler/Tracker/02 Basil.flac"
Apr 19 20:38 : decoder_thread: probing plugin flac
Apr 19 20:38 : decoder: audio_format=192000:24:2, seekable=true
Apr 19 20:38 : output: opened plugin=pipe name="sox streamer" audio_format=192000:24:2

=FLAC Version=
flac - Command-line FLAC encoder/decoder version 1.3.2
Copyright (C) 2000-2009  Josh Coalson
Copyright (C) 2011-2016  Xiph.Org Foundation

=MPD Version=
Music Player Daemon 0.20.18

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un

**Comment by MaxKellermann** [comment]
Your log shows everything works as expected. Where's the problem? Show some evidence for the presence of a problem. Your only problem description is "would not play", but I have no idea what that means. Your log shows it does play.

**Comment by audiofool** [comment]
Thanks for responding Max,
The issue is that the file(stream in this case) plays noise unless I override the format to *:32:*.  I believe the raw stream should be 24 bit packed in 32 bits which is what the command line flac utility does when creating a raw file

**Comment by MaxKellermann** [comment]
MPD pads 24 bit samples to 32 bit. The "pipe" and "fifo" outputs require you to know MPD's internals - they are unsupported experimental plugins for people who know what they're doing. Don't use for anything serious.
So this isn't a bug after all, but just a mismatch between your expectation and what MPD actually does.

**Comment by audiofool** [comment]
24 bit WAV files pad to 32 bits, flac through the pipe shows 24 bit.  If it is padded to 32 bit I think its padded differently than WAV.  In any case I didn't realize that they were experimental plugins and unsupported.  Thanks again for mpd.
