### ISSUE TITLE
httpd plugin doesn't work with mono output and vorbis.

### ISSUE THREAD

**Issue by alkino** [MusicPlayerDaemon/MPD#269]
Hello,
I run through a bug when configuring httpd output plugin with `format "44100:16:1"`.
Port is correctly open but clients (mplayer / vlc) cannot run it failing with a "Read failed".

mpd version is "0.20.18"

Here is mpd log:
```
decoder: audio_format=44100:24:2, seekable=true
exception: Failed to open "alkinocast" [httpd]
exception: nested: error initializing vorbis encoder
exception: Failed to open "alkinocast" [httpd]
exception: nested: error initializing vorbis encoder
```

Once format is set to `44100:16:2` it works well.
Regards

**Comment by alkino** [comment]
The problem was my bitrate. It was too high for mono but not for stereo as it is divide by two.
It should report a better error message. But it is not possible as libvorbis doesn't send us useful error.

So close it?

**Comment by alkino** [comment]
I talk of this problem on #xiph@freenode.

> A: also, you shouldn't be asking for specific bitrates anyway; forcing CBR/ABR damages the encode quality.
> A: ask for a quality level if at all possible.
> B: ok, so maybe the solution is a patch in mpd documentation "bitrate or quality but prefer specifying quality, bitrate is for expert only."
> C: no, not even for experts, it's just plain wrong especially with CBR

What do you think about it? Today both options are shown in mpd as equivalent.

**Comment by mxork** [comment]
fwiw, I also got bit by this.
