### ISSUE TITLE
MPD random crash on Haiku

### ISSUE THREAD

**Issue by extrowerk** [MusicPlayerDaemon/MPD#270]
MPD randomly crash if i press play.
OS: Haiku hrev51891 x86_64
Current MPD recipe : https://github.com/haikuports/haikuports/tree/master/media-sound/mpd

Backtrace: https://gist.github.com/extrowerk/45da880d47a2afd0f0c1a79f56134629#file-mpd_haiku_backtrace

**Comment by MaxKellermann** [comment]
Your backtrace shows that this crash is inside a thread which was not created by MPD, but by `libmedia.so`, and no code from MPD is involved. This doesn't look at all like a MPD-specific problem. If you disagree, explain why.
