### ISSUE TITLE
MPC ruins fun

### ISSUE THREAD

**Issue by tsaber** [MusicPlayerDaemon/MPD#274]
It has so many things it doesnt accept as arguments and where it has this special tagging system that I just want to throw something into my computer to kick mpcs ass.

It is impossible to use it without studying it. And as that it failed as the easy CLI tool it is supposed to be.
I just makes me fucking angry.

Maybe that's just me though. So nice mpd really but mpc can go to fukcing hel

**Comment by MaxKellermann** [comment]
I'm sorry that MPD or MPC or whatever you're ranting about ruined your fun and made you angry. And I'm sorry that this issue is unfixable. There is only one solution: stop using it, and go on with your life. Have a nice day.
