### ISSUE TITLE
seekcur on remote file crashes mpd process

### ISSUE THREAD

**Issue by project-owner** [MusicPlayerDaemon/MPD#276]
I'm using mpd 0.20.18 Windows version. Sending commands over socket connection to the
default port 6600. The following commands sent in sequence will crash mpd process:

command_list_begin
clear
add http://www.archive.org/download/winnetou1_librivox/winnetou1_03_may_64kb.mp3
play 0
seekcur 100
command_list_end

It looks like seekcur command is trying to set current position on remote file when duration info is not available yet. As a workaround I moved seekcur from this batch and run it separately after
periodically running status command and checking that 'duration' is not 0. I'm just wondering 
if it would be possible to handle this in some other way.

Thanks!

**Comment by MaxKellermann** [comment]
Need a backtrace of the crash.

**Comment by project-owner** [comment]
Here are the last lines of the log file:

May 05 09:21 : client: [8] opened from 127.0.0.1:60057
May 05 09:21 : client: [8] process command list
May 05 09:21 : client: process command "clear"
May 05 09:21 : playlist: stop
May 05 09:21 : player: played "http://www.archive.org/download/winnetou1_librivox/winnetou1_01_may_64kb.mp3"
May 05 09:21 : output: closed plugin=winmm name="Speakers"
May 05 09:21 : client: command returned 0
May 05 09:21 : client: process command "add http://www.archive.org/download/winnetou1_librivox/winnetou1_04_may_64kb.mp3"
May 05 09:21 : client: command returned 0
May 05 09:21 : client: process command "play 0"
May 05 09:21 : playlist: play 0:"http://www.archive.org/download/winnetou1_librivox/winnetou1_04_may_64kb.mp3"
May 05 09:21 : client: command returned 0
May 05 09:21 : client: process command "seekcur 100"

**Comment by MaxKellermann** [comment]
Without a backtrace, I can't help with your issue.

**Comment by project-owner** [comment]
How can I get that backtrace on Windows?
