### ISSUE TITLE
MPD fails to read tags on DSD file

### ISSUE THREAD

**Issue by kimgavlestam** [MusicPlayerDaemon/MPD#277]
MPD fails to read tags from this DSD file and they show up as "Unknown". Using a tag editor like kid3 the tags read correctly. The file can be found here: https://drive.google.com/drive/folders/0B3QDG-sqWgm6b2lkVWFqd2w0Ymc?usp=sharing

**Comment by MaxKellermann** [comment]
Can't download.

**Comment by kimgavlestam** [comment]
Link updated. Hope it works.
