### ISSUE TITLE
Apparently random curl failures on long Qobuz tracks

### ISSUE THREAD

**Issue by nicolabotta** [MusicPlayerDaemon/MPD#281]
mpd --version: 
[mpd.version.txt](https://github.com/MusicPlayerDaemon/MPD/files/2021554/mpd.version.txt)

mpd.conf: 
[mpd.conf.txt](https://github.com/MusicPlayerDaemon/MPD/files/2021566/mpd.conf.txt)

tail -f /var/log/mpd/mpd.log:
May 21 07:37 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=47572575"
May 21 07:55 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=47572576"
May 21 08:05 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=47572577"
May 21 08:18 : exception: CURL failed: transfer closed with 11643349 bytes remaining to read
May 21 08:18 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=47572578"
May 21 08:35 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=42623121"
May 21 08:45 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=42623122"
May 21 08:56 : exception: CURL failed: transfer closed with 42190040 bytes remaining to read
May 21 08:56 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=42623123"
May 21 09:05 : player: played "http://192.168.178.101:49149/qobuz/track?version=1&trackId=42623124"

I have made extensive tests on different days and at different times. My observations are:

* The failures happen consistently on certain tracks. In the example above, these are form Mahler's 5th and 4th by Adam Fischer and the Düsseldorfer Symphoniker.

* The tracks on which failures typically occur tend to be long. I can replay whole albums with many short tracks (e.g., opera works) without failures. Sporadically, I have observed failures also on short tracks.

* The failures are not time consistent: replaying the same album (or the same track) does not necessarily yield the same failures.

* The failures do not depend on the file format: for the tracks reported above, they occur both when streaming mp3 (320 kbit/s) and FLAC files.

* The failures do not depend on the OS or on the MPD version. I can reproduce the same kind of (apparently random) failures on a Raspbian system and with MPD 0.19.21.

Any suggestions on how to fix this problem?

**Comment by MaxKellermann** [comment]
Hm, this error means that the Qobuz server has closed the HTTP connection before the end of the file. This is out of MPD's control. It is Qobuz's arbitrary decision. I think you should ask Qobuz support for help with this problem.

**Comment by nicolabotta** [comment]
@MaxKellermann As a matter of fact, the failures only occur during connections that have been initiated by MPD. Connections initiated by BubbleUPnP or by the Qobuz app on devices in the same LAN work flawlessly. Also, it seems that the frequency of the events does correlate with certain MPD settings. Thus, for instance, a higher value of  audio_buffer_size tends to produce more failures than a lower value. Thus, it does not appear that the events are fully out of MPD's control. I cannot really ask for Qobuz support because, as mentioned, streaming via the Qobuz app works flawlessly.
