### ISSUE TITLE
proxy plugin into password protected mpd

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#283]
Configuration:
MPD "Host" (+ Music Directory) is running on Raspberry Pi running NFS Server V3, it is password protected
MPD "Client" is running on Other machines (verified on Android and Linux Desktop)

MPD remote client (MPDroid, MALP and mpc) succesfully connects to MPD "Client" but is not permitted to any command e.g. idle, lsinfo etc.

Removing the password configuration from the MPD "Host" was the only thing that worked

**Comment by djselbeck** [comment]
password@hostname is perfectly working for the proxy plugin here

**Comment by roizcorp** [comment]
can you elaborate?
in the mpd "client" .conf? in the remote client?
password@MPD-HOST(read,add,control,admin) ?
