### ISSUE TITLE
Proxy plugin group by ArtistSortTag not working although advertised to client

### ISSUE THREAD

**Issue by djselbeck** [MusicPlayerDaemon/MPD#284]
With the database setup as an proxy database MPD returns the following tagtypes:

> 
> tagtype: Artist
> tagtype: ArtistSort
> tagtype: Album
> tagtype: AlbumSort
> tagtype: AlbumArtist
> tagtype: AlbumArtistSort
> tagtype: Title
> tagtype: Track
> tagtype: Name
> tagtype: Genre
> tagtype: Date
> tagtype: Composer
> tagtype: Performer
> tagtype: Disc
> tagtype: MUSICBRAINZ_ARTISTID
> tagtype: MUSICBRAINZ_ALBUMID
> tagtype: MUSICBRAINZ_ALBUMARTISTID
> tagtype: MUSICBRAINZ_TRACKID
> tagtype: MUSICBRAINZ_RELEASETRACKID
> 

but issuing the command 
`list album group AlbumArtistSort`

results in

> ACK [5@0] {} Unsupported tag

This is tested with MPD version 0.20.20 

Edit:

Running 0.20.20 on both MPD hosts

**Comment by mxjeff** [comment]
Hi,
I was not able to test on a recent MPD setup, but on v0.19.21 it looks like MUSICBRAINZ_RELEASETRACKID is not exposed through a proxied database.
