### ISSUE TITLE
Error relocating

### ISSUE THREAD

**Issue by DrUlysses** [MusicPlayerDaemon/MPD#291]
Hello, I'm trying  to run mpd on openwrt (Onion Omega 2 plus), but I become these errors
![image](https://user-images.githubusercontent.com/8532343/41191729-fe6e2fba-6bf3-11e8-9f68-1967c8afbb9e.png)
Mb I have forgot to install something?

**Comment by MaxKellermann** [comment]
Maybe, but I don't know and this problem is out of MPD's scope.
