### ISSUE TITLE
"end of stream" after song when input format changes

### ISSUE THREAD

**Issue by vasyugan** [MusicPlayerDaemon/MPD#294]
This is about mpd 0.20.20 on Debian Sid. 
I have an http stream configured as follows:

```
audio_output {
        type            "httpd"
        name            "My HTTP Stream"
        encoder         "lame"          # optional, vorbis or lame
        port            "8989"
        bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
        quality         "4.0"                   # do not define if bitrate is defined
}
```

Each time when the input format switches from ogg to mp3 or vice versa, the clients get disconnected, vlc reports "end of stream". From VLC I get 

`[00007f20d00029b0] prefetch stream error: unimplemented query (264) in control`

and I have to hit "play" again to restart the stream. Same with other clients. 

Have been using mpd with the same config on arch linux before, without any such effects.

**Comment by MaxKellermann** [comment]
Not a bug, but a configuration mistake - see https://www.musicpd.org/doc/user/output_plugins.html#httpd_output
