### ISSUE TITLE
MPD becomes shortly unresponsive after stopping a HLS stream

### ISSUE THREAD

**Issue by eduardosm** [MusicPlayerDaemon/MPD#298]
When MPD is playing an HLS stream and a stop command is sent, will be irresponsive for about a second.

Steps to reproduce:
- Play a HLS stream. Some HLS stream links can be found here: http://www.radiofeeds.co.uk/other.asp
- Send the stop command

Expected behaviour:
- MPD should stop playing the stream and reply "OK" immediately.

Behaviour on 0.20.x:
- Stream stops playing immediately
- MPD is unresponsive for ~1 second
- After that, an OK is received and MPD becomes responsive again

Behaviour on git master:
- Stream continues to play for 0.25 ~ 0.5 seconds
- MPD is unresponsive for ~1 second
- After that, an OK is received and MPD becomes responsive again

**Comment by MaxKellermann** [comment]
MPD can't play HLS. So what are you doing here?
Check: https://www.musicpd.org/help/

**Comment by eduardosm** [comment]
It seems it can play the streams provided on the link above. At least it can play a list of chunks from a m3u8 playlist and fetch the playlist periodically to get new chunks. It works well except for the issue described on this bug report.

**Comment by MaxKellermann** [comment]
I tried over and over with 0.20.20 and git master, and could not reproduce your problem. MPD stops immediately, and is never unresponsive. And I'm annoyed that you ignored the instructions in my link.

**Comment by eduardosm** [comment]
Sorry, I should have posted my configuration file. It seems that the line `audio_buffer_size "8192"` is causing the issue.

```
music_directory "/home/eduardosm/Música/"
playlist_directory "/home/eduardosm/.local/share/cantata/mpd/playlists"
sticker_file "/home/eduardosm/.local/share/cantata/mpd/sticker.sql"
bind_to_address "/home/eduardosm/.local/share/cantata/mpd/socket"
db_file "/home/eduardosm/.cache/cantata/mpd/tag_cache"
pid_file "/home/eduardosm/.cache/cantata/mpd/pid"
state_file "/home/eduardosm/.cache/cantata/mpd/state"
log_file "/dev/null"
metadata_to_use	"artist,album,title,track,name,genre,date,originaldate,disc,albumartist,composer,musicbrainz_albumid"
audio_output { 
  type "pulse"
  name "Output"
}
mixer_type "software"
audio_buffer_size "8192"
filesystem_charset "UTF-8"
id3v1_encoding "UTF-8"
```

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/user/config_other.html "Do not change these unless you know what you are doing."
Obviously you were **not** knowing what you were doing. And modified settings are unsupported.
You could have saved me the time for researching your issue by following the instructions when I asked you to. Every time I take time after somebody ignored my request, I regret it.
