### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [MusicPlayerDaemon/MPD#299]
Hi,

Since this app is FLOSS, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and we already have a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/445).

You can find some documentation [here](https://f-droid.org/docs/).

**Comment by ildar** [comment]
That generally doesn't require any action from devs, we just want to be sure you don't object.

**Comment by MaxKellermann** [comment]
I don't object. Is there anything that this project can do? For example, include build scripts in the git repository? Looks like it's more than just dropping an APK file?

**Comment by Poussinou** [comment]
@MaxKellermann F-Droid compiles everything from source, so yep, it's more than just dropping an apk file.

No binaries are allowed (no bin, no jar, no aar...), and everything (libraries, source code, other resources...) must be open source and "buildable" from sources.

Looks like it isn't a trivial build here, we usually use a gradle file to build apks, but you're using a python file (right?).

**Comment by MaxKellermann** [comment]
There's a Python script which is just a helper to download and build several libraries with the Android NDK (the same Python script can port those libraries to Windows). It is not mandatory - you can use any way you like to obtain Android ports of those libraries. MPD itself is built with autotools, which just needs the right parameters (`--host` etc.) to do the Android build.

**Comment by MaxKellermann** [comment]
I think this can be closed.
