### ISSUE TITLE
httpd: DLNA streaming broken

### ISSUE THREAD

**Issue by madroach** [MusicPlayerDaemon/MPD#304]
Hi,

in ``HttpdClient.cxx`` the following header is served when the client requests DLNA streaming:
``` cpp
"HTTP/1.1 206 OK\r\n"
"Content-Type: %s\r\n"
"Content-Length: 10000\r\n"
"Content-RangeX: 0-1000000/1000000\r\n"
"transferMode.dlna.org: Streaming\r\n"
"Accept-Ranges: bytes\r\n"
"Connection: close\r\n"
"realTimeInfo.dlna.org: DLNA.ORG_TLAG=*\r\n"
"contentFeatures.dlna.org: DLNA.ORG_OP=01;DLNA.ORG_CI=0\r\n"
"\r\n",
```

This is completely broken. Note the inconsistency betweed ``Content-Length`` and ``Content-RangeX``.
Also MPD won't stop streaming after the advertised ``Content-Length`` of 10000 bytes.
My http relay choked on this, because it expected another HTTP header after the 10000 bytes, but received just binary data.

Please disable this part until it is properly implemented. Fake it till you make it doesn't work here 😄

**Comment by MaxKellermann** [comment]
Uh-oh, this code doesn't appear to make sense. It was added in commit https://github.com/MusicPlayerDaemon/MPD/commit/21851c06733080b4c131d553d5d1f8784c12410f
