### ISSUE TITLE
high cpu using with icecast2

### ISSUE THREAD

**Issue by kiriharu** [MusicPlayerDaemon/MPD#309]
I using mpd 0.19.1 and i have problem with audio streaming to icecast2 server. CPU usage is going up to 50%. Can anyone help me?
![image](https://user-images.githubusercontent.com/38693046/42717136-bc918892-8707-11e8-9da2-3ff8b559cf5e.png)
mpd config: https://pastebin.com/tRFWQqqb

**Comment by MaxKellermann** [comment]
Sorry, MPD 0.19.1 is ancient and unsupported. Even for the unsupported 0.19 branch, this is twenty bug-fix releases behind!

**Comment by kiriharu** [comment]
I install Music Player Daemon 0.20.19 and have same problem.

**Comment by kiriharu** [comment]
![image](https://user-images.githubusercontent.com/38693046/42724043-029cb8a4-8774-11e8-8b28-42979a2cc584.png)
srsly, nothing new

**Comment by MaxKellermann** [comment]
Now explain why you believe 50% CPU usage is an issue.
And post a perf report demonstrating where this CPU time is spent (needs debug symbols in MPD and all libraries).
When you have enough data which shows that this is a problem in MPD code, I'll reopen this and take care of it.
Unfortunately, your report is devoid of information; other than the version number and a screenshot showing a CPU usage number, there is nothing.

**Comment by Euphorbium** [comment]
I am having the same issue. Icecast is consuming 99.9% of the CPU. I am willing to provide any information necessary to get this resolved.
