### ISSUE TITLE
Mixramp tags not working - Overlap songs by dB level

### ISSUE THREAD

**Issue by ArvyRogerio** [MusicPlayerDaemon/MPD#328]
MPD version: 0.20
OS: Fedora 28

After ran Mixramp to insert the tags, MPD is not overlapping the songs based on dB levels. The songs just play in sequence, with no overlap.

Mixramp tags correctly inserted on files, checked with VLC (midia info option).

Mixramp compiled with adjusts to the actual eyeD3 version, as mentioned on Mixramp's Sourceforge page (user reviews). But this not affect MPD directly, since Mixramp runs ok after the changes in compile files.

mpd.conf and more info on: [https://forum.musicpd.org/viewtopic.php?f=8&t=7250](url)

**Comment by MaxKellermann** [comment]
Seriously, https://www.musicpd.org/help/

> When you do request help, post the following data (use paste.debian.net on IRC):

- [ ] output of “mpd --version”
- [X]  your configuration file (mpd.conf)
- [ ] relevant portions of the log file (--verbose)
- [X] be clear about what you expect MPD to do, and what is actually happening

I'm pretty annoyed that you wrote "I already read the help page" when you really did not. Or you explicitly ignored parts of it. Is this page really too long/complex for you? I'm annoyed enough to close this for now, and maybe reopen it as soon as there is enough information.

**Comment by ArvyRogerio** [comment]
Wow, you're very nice person... congratulations. Don't want to help even I sent you all information before, including what you said I didn't send, like MPD Version (you said the version was old, and I updated to latest)... Just **read** the original message on your forum. And I said that the verbose log didn't have nothing specific about error about this.

If you don't know how to fix, or don't want to fix... you're in wrong place. If your software is open source, you need to think in be part of the open source community. And help others. I gave you all the info, and you don't want or don't know how to fix. Shame.

When you don't want to help, for ALL users, you just said the user is wrong and reply with https://www.musicpd.org/help/ and so, like was the user mistake.

Now I say "Seriously?".

**Comment by MaxKellermann** [comment]
Enough. Good luck with your problem - if you want volunteers to spend time on your problems, you better listen to what they need in order to help you. But what I certainly don't need is messages like your last one. That's just wasting my time, no thanks.
