### ISSUE TITLE
Support for PCM --> DSD upsampling 

### ISSUE THREAD

**Issue by norrest** [MusicPlayerDaemon/MPD#33]
It would be very nice if mpd-dsd could support the new branch of sox with PCM --> DSD upsampling (patching Sox Resampler.cxx)
https://github.com/lintweaker/mpd-dsd-019/issues/6

**Comment by MaxKellermann** [comment]
What you're talking about is not "SoX" but an unofficial fork of SoX. Reopen this feature request as soon as an official SoX release has this feature. Until then, I'm not interested in writing code for MPD that is needed only for very few MPD users who decided to buy a crippled DAC that is unable to process PCM, requiring MPD to do a lossy conversion to DSD, reducing audio quality.

**Comment by susman** [comment]
we can't compare PCM to DSD the way we do with plain PCM vs lossless codecs, that surely does not mean the conversion is lossy and reducing audio quality.
