### ISSUE TITLE
Player fails streams after upgrade to Ubuntu 16.04.5

### ISSUE THREAD

**Issue by WarnerV** [MusicPlayerDaemon/MPD#336]
My apologies in advance if my reporting is not fully compliant with the standards - I'm a bit of a beginner in Linux.

I've been using MPD (standard 0.19.xx) in Ubuntu for a while without any troubles, but after a recent upgrade streams (Shoutcast streams, like http://icecast.omroep.nl/3fm-bb-mp3) have started "stuttering". Local files play without issues, and using a different player (Rythmbox) the streams play just fine.

 - The mpd.log was not showing any feedback, even after setting mpd.conf to log Verbose.
 - After upgrading mpd to 20.12, mpd.log started reporting:

On start:
`Aug 09 11:03 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted`
When playing streams:
`Aug 09 11:07 : player: Decoder is too slow; playing silence to avoid xrun`

One hint that might point at the cause (but I'm really not sure) was the following after running "apt install --reinstall mpd"
>Error in '/usr/share/doc-base/mpd', line 7: all 'Format' sections are invalid.
Note: 'install-docs --verbose --check file_name' may give more details about the above error.
Registering documents with scrollkeeper...
Processing triggers for man-db (2.7.5-1) ...
Setting up mpd (0.20.12-1~ppa1~xenial1) ...
insserv: warning: current start runlevel(s) (empty) of script 'mpd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script 'mpd' overrides LSB defaults (0 1 6).

Any further info I can provide?

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by MaxKellermann** [comment]
Btw. MPD version 20.12 does not exist. The latest stable release is 0.20.20. If you don't have that version (or the latest git master), I can't help you.

**Comment by WarnerV** [comment]
Yeah, I've trying to find a way to get the latest version - but all I find is the source code. So I need to learn how to compile first.. I was trying to avoid that steep learning curve :(. 

I'll be back.

**Comment by WarnerV** [comment]
Alright.. I went through all the motions, and I'm sorry to say the result is exactly the same as before (but now with mdp 0.20.20).

The results of mpd --version is here:
http://paste.debian.net/1037250/
 
The mpd.conf file is here:
http://paste.debian.net/1037253/

The mpd.log file (verbose) is here:
http://paste.debian.net/1037256/

.. but from that, I figure the most relevant entries are this:

>Aug 09 13:59 : playlist: play 1:"http://icecast.omroep.nl/3fm-alternative-mp3#NPO 3FM Alternative (Alternative Rock)#NPO 3FM Alternative (Alternative Rock)"
Aug 09 13:59 : curl: icy-metaint=16000
Aug 09 13:59 : decoder_thread: probing plugin mad
Aug 09 13:59 : decoder: audio_format=48000:24:2, seekable=false
Aug 09 13:59 : client: [0] command returned 0
Aug 09 13:59 : playlist: queue song 2:"http://icecast.omroep.nl/3fm-bb-mp3#NPO 3FM Serious Radio 96.8 (Top 40/Pop)#NPO 3FM Serious Radio 96.8 (Top 40/Pop)"
Aug 09 13:59 : player: Decoder is too slow; playing silence to avoid xrun
Aug 09 13:59 : player: Decoder is too slow; playing silence to avoid xrun
Aug 09 14:00 : player: Decoder is too slow; playing silence to avoid xrun
Aug 09 14:00 : player: Decoder is too slow; playing silence to avoid xrun
Aug 09 14:00 : player: Decoder is too slow; playing silence to avoid xrun

Any help would be greatly appreciated!

**Comment by MaxKellermann** [comment]
In the log, the setup of the audio output is missing. It doesn't show the start of the playback.

Try switching to an ALSA output instead of Pulse. The `device` should be `hw:0` or similar to disable ALSA's internal processing.

**Comment by WarnerV** [comment]
Alright, here's a log including the start of the application (restarting after mpd --kill):
http://paste.debian.net/1037258/

And here's the log when using ALSA (no difference in the result, apart from losing volume control for which I guess I would have to add a mixer):
http://paste.debian.net/1037262/

**Comment by WarnerV** [comment]
Sorry, after reading again your message I tried with hw:1 instead of hw:1,0 in ALSA. Again same result, but here are the logs of that setup:
http://paste.debian.net/1037264/

**Comment by skidoo23** [comment]
Stream plays on MPD (git) without problems. Some ideas:

- comment out max_output_buffer_size setting in mpd.conf
- disable libmad and configure different mp3 decoder (mpg123, ffmpeg) in mpd.conf
- ARM cpu?

**Comment by MaxKellermann** [comment]
No, `max_output_buffer_size` affects only client communication; it has no effect on streaming playback. Some badly designed clients need it larger, and I disapprove suggestions to enlarge the setting, but it's unrelated to this issue.

@WarnerV thanks for your quick feedback so far; I'm not yet sure where the problem is. I cannot imagine your CPU is really too slow, but what's your hardware?

I think this is rather that your sound chip wants audio data faster than the radio transmits it. That is, the two clocks are badly in sync. I've never seen such a problem, but MPD doesn't handle such a problem gracefully; but MPD should. This may really be the problem I've been avoiding to solve for years (because there has been no pressure from users, no bug reports).

How often does this stuttering happen?

**Comment by MaxKellermann** [comment]
What would be interesting is to know what part of your upgrade caused the problem. I hoped this would be a Pulse upgrade problem, but apparently not. Maybe the kernel update? Can you boot into the older kernel again and check?

**Comment by WarnerV** [comment]
Good morning!

I've only had a few minutes this morning, but indeed it seems that booting to a 4.4 kernel resolves the issue - booting into 4.15 'causes'  the stuttering.

The CPU is an i7 4xxx, so that should really not be an issue. I'm running on the built-in soundcard (not sure about the exact type right now) via optical out to a stereo amplifier. Sounds pretty standard I think.

The stuttering happens a bit infrequently, but usually within a minute after starting playback. Once it starts, it stutters a few times and than usually it seems to give up. Average frequency I suppose is 4 times per minute or so (more or less in line with the mpd.log file). 

I'll be out for a few days - I'll be back on Sunday to make more tests.. It would be great if we can get to the root cause of this! (but as you can tell, I'm not really an expert, so you'll have to guide me a bit through the steps to take ;)).

Have a great day!

**Comment by WarnerV** [comment]
> Kernel 4.15 and snd_hda_intel has some issues with power saving.

Wouldn't you expect the problem to occur with all sound (i.e. not just streaming audio) if that is the cause?

**Comment by WarnerV** [comment]
Further info after some experimenting:
 - ffmpeg has the same issue, but it seems to be less frequent. 
 - mpg123 refuses to play the mp3 stream altogether
 - When I keep the system busy by playing a video in the background, the stuttering completely stops. As soon as the system is clocking down (e.g. after the video ends) the stuttering starts again. This is the case with both _mad_ and _ffmeg_

I changed decoders by adding the following at the bottom of mpg.conf: 
> decoder {
       plugin			"mad"
       enabled     		"no"
}
decoder {
       plugin			"mpg123"
       enabled     		"yes"
}
decoder {
       plugin			"ffmpeg"
       enabled     		"yes"
}

By the way, what's the meaning of `Aug 13 15:38 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted`? Should I just ignore that?

**Comment by skidoo23** [comment]
**options** snd_hda_intel power_save=0 intentionally omitted?

**Comment by WarnerV** [comment]
@skidoo23 ..I missed to copy the word "options" to the post, but in the modprobe.conf file it is there. Still not working though.

**Comment by MaxKellermann** [comment]
Can you disable CPU reclocking and always run at the highest CPU clock?

When you do see stuttering, do you also see high CPU usage in "top"? What is the CPU clock? (`cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq`)

The "could not get realtime scheduling" message means that MPD attempted to switch to the realtime scheduler, but your operating systems did not allow it to do so. Usually not a big deal, but it could be worthtile to allow realtime, because it might fix stuttering when your system is too busy ... though your current problem is stuttering when your system is "too idle"... (see https://www.musicpd.org/doc/html/user.html#real-time-scheduling)

**Comment by WarnerV** [comment]
> Can you disable CPU reclocking and always run at the highest CPU clock?

As long as the system runs at the highest clock, no stuttering occurs (cpufreq-selector -g performance)

> When you do see stuttering, do you also see high CPU usage in "top"? 

No, pulseaudio takes about 1% (regardless of playing audio or not) and mpd takes about 0.7% even if it is silent (as said, usually it 'stutters' twice and than gives up). These percentages are measured during power save (when the CPUs are running around 800MHz).

> What is the CPU clock? 

Output of `cat /proc/cpuinfo | grep "MHz"` or `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq` varies between 800 and 3500MHz. As said, the stuttering does not happen when at high frequencies, but it does when running 800-1500MHz

>(see https://www.musicpd.org/doc/html/user.html#real-time-scheduling)

Trying to follow the instructions: 
1. `ulimit -HS -r 50; mpd` gives me `exception: No configuration file found` 
2. `zgrep ^CONFIG_RT_GROUP_SCHED /proc/config.gz` gives me `gzip: /proc/config.gz: No such file or directory` 

I guess I would have to build my own kernels to set these options..? I think for reliability I should stick to the standard ones from Ubuntu (also because I'm running a webserver that needs the frequent security updates).

What still makes me wonder, is why the stuttering only occurs with streams, while all local music plays just fine (FLAC/MP3/24bit...)

**Comment by MaxKellermann** [comment]
When you launch MPD with `ulimit`, pass the same options to `mpd` as you usually would. The important part is to change the `ulimit` before launching MPD. How do you usually start MPD?

If `/proc/config.gz` doesn't exist, it means that your kernel was compiled without exposing its configuration at this path. How did you obtain your kernel? Is it an Ubuntu standard kernel? Which version? Try "grep ^CONFIG_RT_GROUP_SCHED /boot/config-`uname -r`" instead, this usually works with Debian/Ubuntu.

**Comment by WarnerV** [comment]
> How do you usually start MPD?

I run `mpd /home/warner/.mpd/mpd.conf` as user (not as root)

> How did you obtain your kernel? Is it an Ubuntu standard kernel? Which version? 

It's the out-of-the-box Ubuntu Kernel (currently 4.15.0-30-generic). Before upgrading to Ubuntu 16.04.5 I was running 4.4.0-xxx, which did not have any issue with mpd.

> Try "grep ^CONFIG_RT_GROUP_SCHED /boot/config-'uname -r'" instead, this usually works with Debian/Ubuntu.

This gives me no results, but I did find a line in the file `/boot/config-4.15.0-30-generic` that reads:

`# CONFIG_RT_GROUP_SCHED is not set`

Sorry.. I'm really not at home in the area of compiling kernels. So far I managed to get by without touching it ;)

**Comment by MaxKellermann** [comment]
Your kernel is fine. But you need to set the proper ulimits to allow MPD to use real-time scheduling.
On Debian-based distros, you can usually set ulimits in `/etc/security/limits.conf`, and they will take effect after logging in again.
I'm not sure if changing the ulimit would solve your problem; I suppose not.
Your problem is really surprising, because at 800 MHz, your CPU is still overpowered for MPD by an order of magnitude. I have no idea why increasing the clock even more would solve the problem, because it's already fast enough.

**Comment by WarnerV** [comment]
> Your kernel is fine. But you need to set the proper ulimits to allow MPD to use real-time scheduling.
On Debian-based distros, you can usually set ulimits in /etc/security/limits.conf, and they will take effect after logging in again.

Ok, thanks. Now I managed to start mpd with real-time scheduling. Unfortunately I can confirm that this was not the issue as the stuttering is still happening.

> I have no idea why increasing the clock even more would solve the problem, because it's already fast enough.

..Hold on.. it took a little longer this time, but it seems that also with the CPU set to 'performance' (and continuing high clocks) mpd is still stuttering. So we have to look somewhere else.

So:
1. CPU clocks don't affect the problem ('Performance'  mode does not change anything)
2. Playing a (silent) video on firefox does 'solve' the problem, as long as we prevent the screen from turning off.
3. Playing a (silent) _local_ video does not affect the problem
4. ALSA has the same issue as Pulse
5. Running mpd with `ulimit -HS -r 50; mpd /home/warner/.mpd/mpd.conf` does not affect the problem
6. Changing from mad to mpg123, ffmpeg does not affect the problem
7. Creating `modprobe.conf`, containing text `options snd_hda_intel power_save=0, running depmod -a, & reboot does not affect the problem (but I'm not sure if I implemented this correctly).

One idea: can it be that the stream is interrupted, not the sound but the _data_ stream? Maybe the new 4.15 kernel shuts down the datalink if firefox is not using it?

**Comment by WarnerV** [comment]
Just to report: I upgraded to Ubuntu 18.04.01, now running 4.15.0-33-generic. I also installed mpd 0.20.21. 

The issue is not affected. The only way to keep a stream playing seems to be to keep an active connection open (using a browser).

**Comment by WarnerV** [comment]
So.. Is there anything I can look at to investigate this issue further? I'm still stuck without a working mpd :(

**Comment by MaxKellermann** [comment]
Sorry, I've had to deal with other issues first, and there was no time yet for this one.
What you can do meanwhile is test the latest 0.21 release. I have improved and overhauled buffering and latency in that new release. There is a small chance that this fixes your problem.

**Comment by WarnerV** [comment]
Hi Max,

just wanted to let you know that I got around to updating MPD to 0.21.4 (had to find the time to learn about the new compiler ;)).

Unfortunately, the issue is unchanged by the update, and I still have no idea where to look for a solution.

**Comment by WarnerV** [comment]
Quick update: now I tried a list of alternative hardware (USB Audio, internal audio, optical, HDMI). All with the same result: after seconds or minutes the music stops playing and the ""Decoder is too slow; playing silence to avoid xrun" message is added to the log.

The issue only occurs with streaming audio. Anything internal (no matter the format) works without fail.

At this point I think that a complete reinstall might be the only solution..

**Comment by WarnerV** [comment]
Good news!

Finally I found that cause of the issue.. and in a place I would never have dared to suspect: the network connection of the MPD server was going via a high-voltage protection. Making a direct connection to the router resolved the issue.

Still so many questions though! (but not for this this thread.. that can be closed now):
- how is it possible that 3x kernels were doing fine, but 4x kernels were not?
- what on earth did the voltage protection do to the signal? Normal internet, regular network traffic, everything was fine and working without delays or reduced speed. I never noticed any meaningful packet drops.
- It was in fact only MDP and CURL (which in fact put me on the path to the cable/network: CURL transfers were taking _forever_) that were having issues. Are they both using a particular protocol that has a different style of signal protection?
- How come the MPD error log is showing 'Decoder is too slow' in this case? That seems not to reflect the actual problem. 

Anyhow.. After a year (minus 8 days), my music is playing again without
