### ISSUE TITLE
Inconsistent behavior with fchmod()

### ISSUE THREAD

**Issue by 1848** [MusicPlayerDaemon/MPD#337]
The recently switch to fchmod() for socket permissions seems to be not working well on some machines.
While everything worked perfectly fine when I tested, now it does not seem to work (I am now on a different machine but same arch, same dist, minor kernel version ahead).
Can anyone please confirm that a unix sockets does not get the right permission 0666 on creation?

While reading the docs and the internet I can also see inconsistent behavior.
Some ppl are confirming its works, some say its a "noop". For me its not a noop, but the permissions are not correct (e.g. getting 0755 instead of 0666).
unix7 manpage does not mention fchmod for setting permissions although its says fchmod is not working for abstract socket. Not sure why its mentioned there when its also not working for non-abstract sockets.
Anyway, will do more research but for now I think there is a need to revert this change.
@MaxKellermann can you do this? I will provide a PR to revert the changes asap just in case you prefer to not rollback that commit.
chmod() is not an optimal solution but it seems like its still the best solution for now.

Relevant commit:
84054203afeb9f3c0ece9b85922bb357f9419d14

Thanks.

Edit:
Related PR:  #339

**Comment by MaxKellermann** [comment]
Just from a rough look at the kernel sources:
`fchmod()` can be used to reduce the permission bits on a local socket, but the umask is applied when `bind()` is called:
https://github.com/torvalds/linux/blob/master/net/unix/af_unix.c#L1008..L1010
So `fchmod()` can be used as a security measure to fix race conditions, but to be sure, it must be called again after `bind()` to undo the effects of applying the umask.

**Comment by 1848** [comment]
Do you have any success with calling fchmod() AFTER bind()?
On my machine fchmod() after bind() is a noop.

For me it seems like
- fchmod(0) // prevent race conds
- bind()
- chmod(0666)

is the (best?) way solving this without messing with umask().

**Comment by MaxKellermann** [comment]
I think with local sockets, the socket and the file system inode are distinct objects, therefore `fchmod()` changes the socket's permissions, but not the file system inode. The inode inherits the socket's permissions upon creation (i.e. `bind()`), but the umask is applied.
So yes, if fixing the race condition is important, your approach seems good. But right now, without stricter permissions, there is no race condition; MPD wants to broaden the socket permissions, but never narrows it.

**Comment by 1848** [comment]
Of course you are completely right that there is no real need to secure this right now but there is also no disadvantage.
So I would create a PR tomorrow to implement this approach if you are good with this?

**Comment by MaxKellermann** [comment]
Yes.

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/MPD/commit/4797357fa9fe4cd9adfbbbf59288f38232ada262
