### ISSUE TITLE
mpd hangs when manually moving forward/backward on same track, or to next/prior track

### ISSUE THREAD

**Issue by je-vv** [MusicPlayerDaemon/MPD#34]
Note: Actions performed on both ncmpcpp and ncmpc leads to same results...  Using Arch GNU/Linux.

Whenever I move forward/backward on the same playing track (f/b), mpd just hangs, usually so hard, that mpd needs to be restarted to do anything. A workaround is to pause the track, and then move forward/backward, and then play again, most of the time that works...

When playing a track, and then moving to next/prior track (>/<), then mpd hangs. To get it back alive, it's enough to stop mpd (s), and start any track (enter). The pause work around for moving forward/backward on the same track doesn't work, mpd keeps hanging, but stopping mpd (s), and starting any track (enter) works. Stopping mpd (s), to move to the next track as a work around doesn't work, given there's no current track playing, therefore mpd can find the next...

So it's sort of weird that moving around where to play mpd, kinds of makes it hang...

BTW, I have 2 mpd outputs, the pulse output but also a visual fifo, however by keeping only the pulse audio doesn't help, so It's not related to the visual fifo...

It affects all my machines. Most are mintbox 2 with 2 core i5 as processors, intel hda audio and SATA SSD. One laptop is an HP EliteBook 840 G3 with 2 core i7 processors, intel hda audio (or plantronics USB audio headset) and PCIe SSD. One laptop is aToshiba nb505 with Atom 64 processor, intel hda and SATA SSD.  I've also tried SATA HD on the mintbox 2 machines...

Regarding what I'm playing, any ogg vorbis file I have experience the same. I don't have mp3 files. It doesn't matter if the files are in local SSD/HD, or network mounted drive. In any case is the same.

* package version(s)

mpd 0.20.6-1
libmpdclient 2.11-1
libmpd 11.8.17-2
ncmpcpp 0.7.7-4
ncmpc 0.27-1
pulseaudio 10.0-2
linux 4.10.5-1

Note: I recompiled the ncmpcpp package getting the exact same behavior on the EliteBook.

* config and/or log files etc.

% 'grep' '^[ \s]*[^#]' .config/mpd/mpd.conf
pid_file "~/.local/share/mpd/pid"
db_file "~/.local/share/mpd/db"
state_file "~/.local/share/mpd/state"
playlist_directory "~/.local/share/mpd/playlists"
music_directory "~/music"
sticker_file "~/.local/share/mpd/sticker.sql"
log_file "~/.local/share/mpd/log"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
bind_to_address "localhost"
input {
plugin "curl"
}
audio_output {
type "pulse"
name "pulse-audio"
}
audio_output {
type "fifo"
name "VISUAL_FIFO"
path "/tmp/mpd-vasqueja.fifo"
format "44100:16:2"
}
replaygain "album"
volume_normalization "yes"
audio_buffer_size "4096"
buffer_before_play "100%"

Note: I've played with combinations of buffer_before_play, and audio_buffer_size, with no effect...

% 'grep' '^[ \s]*[^#]' .ncmpcpp/config
visualizer_fifo_path = /tmp/mpd-vasqueja.fifo
visualizer_output_name = "VISUAL_FIFO"
visualizer_in_stereo = yes
visualizer_sync_interval = 30
visualizer_type = spectrum
visualizer_look = "+|"

**Comment by MaxKellermann** [comment]
Paste a verbose log.

**Comment by je-vv** [comment]
~/.local/share/mpd/log
May 09 16:46 : avahi: Initializing interface
May 09 16:46 : avahi: Client changed to state 101
May 09 16:46 : avahi: Client is CONNECTING
May 09 16:46 : state_file: Loading state file /home/vasqueja/.local/share/mpd/state
May 09 16:46 : client: [0] opened from [::1]:41554
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "plchanges "0"" 
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "outputs"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "decoders"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "outputs"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "outputs"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "playid "1"" 
May 09 16:46 : playlist: play 0:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/01. Day Break.ogg"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : playlist: queue song 1:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/02. Dime Dime.ogg"
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : decoder_thread: probing plugin vorbis
May 09 16:46 : decoder: audio_format=44100:f:2, seekable=true
May 09 16:46 : output: opened plugin=pulse name="pulse-audio" audio_format=44100:16:2
May 09 16:46 : output: converting in=44100:f:2 -> f=44100:16:2 -> out=44100:16:2
May 09 16:46 : output: opened plugin=fifo name="VISUAL_FIFO" audio_format=44100:16:2
May 09 16:46 : output: converting in=44100:f:2 -> f=44100:16:2 -> out=44100:16:2
May 09 16:46 : replay_gain: replay gain mode has changed off->album
May 09 16:46 : replay_gain: replay gain mode has changed off->album
May 09 16:46 : replay_gain: scale=1.000000
May 09 16:46 : replay_gain: scale=1.000000
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : state_file: Saving state file /home/vasqueja/.local/share/mpd/state
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "seek "0" "11""
May 09 16:46 : playlist: queue song 1:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/02. Dime Dime.ogg"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "status"
May 09 16:46 : client: [0] command returned 0
May 09 16:46 : client: [0] process command "idle"
May 09 16:46 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "seek "0" "63""
May 09 16:47 : playlist: queue song 1:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/02. Dime Dime.ogg"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : state_file: Saving state file /home/vasqueja/.local/share/mpd/state
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "seek "0" "55""
May 09 16:47 : playlist: queue song 1:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/02. Dime Dime.ogg"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "stop"
May 09 16:47 : playlist: stop
May 09 16:47 : client: [0] process command "stop"
May 09 16:47 : playlist: stop
May 09 16:47 : player: played "andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/01. Day Break.ogg"
May 09 16:47 : output: closed plugin=pulse name="pulse-audio"
May 09 16:47 : output: closed plugin=fifo name="VISUAL_FIFO"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] closed
May 09 16:47 : state_file: Saving state file /home/vasqueja/.local/share/mpd/state

**Comment by je-vv** [comment]
Actually, after doing search forward (f), and mpd just hanged, then I tried a search backwards (b), but that didn't even get registered in the log, :-(

May 09 16:47 : client: [0] process command "seek "0" "55""
May 09 16:47 : playlist: queue song 1:"andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/02. Dime Dime.ogg"
May 09 16:47 : client: [0] command returned 0
May 09 16:47 : client: [0] process command "idle"
May 09 16:47 : client: [0] command returned 1
May 09 16:47 : client: [0] process command "status"
...
May 09 16:47 : playlist: stop 
May 09 16:47 : player: played "andes/Andes Pan Pipes Plays - Amawa's - Fusion Andina-[TFM]-2011/01. Day Break.ogg"
May 09 16:47 : output: closed plugin=pulse name="pulse-audio"
May 09 16:47 : output: closed plugin=fifo name="VISUAL_FIFO"
...

**Comment by MaxKellermann** [comment]
The problem lies behind your `buffer_before_play` setting. DO NOT MESS WITH THESE SETTINGS.

Ok, admit, it's a MPD bug that it hangs when you configure implausible values. But your setting is wrong and you clearly don't know what you're messing with. Remove the buffer settings, and it'll work. Meanwhile, I'll fix the bug and make MPD complain about such implausible values.
