### ISSUE TITLE
Improve doc/protocol description

### ISSUE THREAD

**Issue by Grundligt** [MusicPlayerDaemon/MPD#340]
Working on a server using the MPD protocol but can't find anything actually mentioning nor showing a single example of a successful command -> response transaction, specifically how and when the server should format and send its response.

How do I format a simple response to a command requesting the status? Before the OK?

`
client: status\n
server: 
volume 24\n
repeat 0\n
OK\n
`

The mpc failed to parse the response. After? The same thing.

Do I format the response like this maybe?

`
status volume 24\n
status repeat 0\n
OK\n
`

When and how do I respond to a command_ok_list? Before or directly after a list_OK? After the last list_OK? 

It's nice with an ACK example on the page named response_syntax, but at least the basic examples or for that matter, any mention of how the server should respond to a command requiring information wouldn't hurt.

And I really like

>  The return value is whatever the return for a list of commands is.

https://www.musicpd.org/doc/protocol/command_lists.html

**Comment by MaxKellermann** [comment]
Multi-line responses should be multi-line in the documentation as well - i.e. no `\n` escape codes.
I don't understand your comand list question.
You're right that this documentation page is pretty badly phrased - it's still the original text from >10 years ago before I entered MPD development - blame my predecessos for writing such a text, and blame me for not rewriting it in 10 years ;)

**Comment by Grundligt** [comment]
Alright,

Lets say MPC for example sends,
```
command_list_ok_begin\n
status\n
currentsong\n
command_ok_list_end
```

Should the server response look like this?
```
volume 25 repeat 0 random 1 single 0...\n
list_OK\n
currentsong info...\n
list_OK\n
OK\n
```

I'd be happy to help rewrite it when I understand the basics :)
