### ISSUE TITLE
"exception: Failed to accept connection: unknown error" on master on Win32

### ISSUE THREAD

**Issue by jwise** [MusicPlayerDaemon/MPD#343]
On Windows, when I launch an mpd that is built from approximately master (specifically, from commit 18e6c69, which is jwise/mpd#urlencode), I get the following error:

```
C:\Users\jwise\mpd>mpd mpd.conf -v --stderr
config_file: loading file mpd.conf
exception: Failed to accept connection: Unknown error
```

The same mpd.conf works fine with an mpd built from a v0.20.20 with the urlencode changes backported to it.

**Comment by MaxKellermann** [comment]
I can't reproduce. It works with Wine, but I don't have a real Windows to test with.

**Comment by chrober** [comment]
I can confirm the problem originally reported by jwise.
I get the following result when attempting to launch the pre-compiled v0.21.1 in a Win10 command prompt:
```
C:\mpd>mpd --verbose c:\mpd\data\mpd.conf
config_file: loading file c:/mpd/data/mpd.conf
Nov 05 21:17 : exception: Failed to accept connection: Unknown error
```
There were no such problems with v0.20.23 (using the very same mpd.conf).

Unfortunately there is no additional information in the log file. Nevertheless, an empty log file is created if I delete the log file before calling mpd.exe.

**Comment by HyShai** [comment]
I'm experiencing this on windows as well...
