### ISSUE TITLE
opustags issues (stream finish at song change, duplicated metadata)

### ISSUE THREAD

**Issue by JustArchi** [MusicPlayerDaemon/MPD#344]
Hi again.

This issue is very strongly connected with https://github.com/MusicPlayerDaemon/MPD/issues/70 and PR #205.

I've compiled MPD from source and the feature works excellent. Metadata are nicely updated on song change and initial play, I've confirmed their availability using VLC client.

There are just two issues I've found that do not exist when `opustags` is turned off (`false`).

When listening to opus icecast2 stream through Chrome web browser, the stream ends when the song changes, either naturally or with something like `mpc next`. So far I've reproduced it only with Chrome, as there is no such issue when using Firefox or VLC. Chrome stream also works properly when not using `opustags` feature. As you can guess, you can immediately re-start the stream after song change and it'll work properly - until the next song change.

I'm not entirely sure if this is some specific Chrome behaviour that perhaps is worth reporting upstream, or MPD is updating metadata in some non-standard way that causes the stream to finish. I'd appreciate if you could take a look into this and forward the issue if needed.

Second issue that I've also noticed includes certain metadata being duplicated, in particular title, artist, album and genre. Perhaps MPD is somehow sending metadata update to icecast twice? I recall @MaxKellermann mentioning that MPD tries to update metadata also through icecast call, but it wasn't working in the past, perhaps it's doubled now together with chained metadata? I reproduced this one with VLC and foobar2000, web browsers do not really want to display what is being transmitted so I'm not sure.

![vlc](https://user-images.githubusercontent.com/1069029/44439003-12a76980-a5c2-11e8-9de4-f448d4f30706.png)

Sadly I'm not skilled enough to look into either of those myself, so I'm leaving this issue open if perhaps somebody would be interested in digging deeper. Thank you in advance for looking into this, despite of that I'm loving metadata updates on my opus stream.

CC @cathugger

```
Music Player Daemon 0.21 (9151b84)
```

**Comment by MaxKellermann** [comment]
I have a version number, but I have nothing else. I don't know at all what you're doing.
See https://www.musicpd.org/help/

**Comment by JustArchi** [comment]
Uh, sorry, I thought it'll be obvious considering my referenced issues.

I'm streaming using `shout` output to icecast2 server, using following config:

```
audio_output {
    type "shout"
    encoder "opus"
    name "Test"
    host "localhost"
    mount "/test.opus"
    password "hackme"
    always_on "yes"
    quality "10.0"
    format "48000:16:2"
    opustags "true"
}
```

**Comment by cathugger** [comment]
I have implemented stuff according to RFC 7845.
Unfortunately not all client software is able to process it properly, as highlighted in https://github.com/MusicPlayerDaemon/MPD/issues/70#issuecomment-342348470.
From my experience, it's more likely to be chrome's and VLC's fault than something wrong in MPD.
Can you reproduce using foobar2000, firefox or gst-play? These were working fine for me when I tried them last time.
Related: https://trac.videolan.org/vlc/ticket/18401 https://trac.ffmpeg.org/ticket/7011

**Comment by cathugger** [comment]
Oh, apparently you have no trouble with VLC. That's nicer than what I've experienced. Maybe they improved their stuff.
As for chrome, I guess they haven't tested for this case in their code. Or they use ffmpeg's code which isn't ready for this...
Actually I remember looking into MPD's decoder and it isn't designed to handle this either. Maybe I should bring myself to fix that sometime.

**Comment by cathugger** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=175281

**Comment by cathugger** [comment]
I guess you could (and probably should) run something like nginx ontop of icecast, have 2 streams, one using opustags on, other using opustags off, then have rules which direct (using user agent string) non-working clients to use stream with opustags off.

**Comment by cathugger** [comment]
and nag developers of clients and client libraries to get this working well, I've already spent more effort on this than I wanted

**Comment by JustArchi** [comment]
Funny thing that you mention it because this is exactly what I'm doing right now, except instead of redirecting I just decided to run two streams and test what works and what doesn't.

Thanks for all your time and insight @cathugger - I really appreciate it 👍.

**Comment by cathugger** [comment]
@JustArchi I ran local mpd with opustags enabled and http output.
For client I've used `curl -s http://192.168.0.10:30166 | opusdec --float - - | aplay -f FLOAT_LE -r 48000 -c 2`
I don't see any irregular stuff in its output:
```
[/] 00:00:18Decoding to 48000 Hz (2 channels)
Encoded with libopus 1.2.1
TITLE=better off dead
ARTIST=waiting to die
DATE=2016
ALBUM=semantic compositions on benadryl and i really need to pee.
TRACK=1
ALBUMARTIST=waiting to die
[|] 00:09:49Decoding to 48000 Hz (2 channels)
Encoded with libopus 1.2.1
TITLE=get antihistamine benadryl allergy medicine
ARTIST=waiting to die
DATE=2016
ALBUM=semantic compositions on benadryl and i really need to pee.
TRACK=2
ALBUMARTIST=waiting to die
[|] 00:13:01Decoding to 48000 Hz (2 channels)
Encoded with libopus 1.2.1
TITLE=i don't want to be alive
ARTIST=waiting to die
DATE=2016
ALBUM=semantic compositions on benadryl and i really need to pee.
TRACK=3
ALBUMARTIST=waiting to die
[|] 00:13:53
```
So it's probably the way VLC and foobar update their fields which is to blame there.

**Comment by cathugger** [comment]
Could you try command I used for your own setup to confirm that it's unrelated to icecast2 server?

**Comment by JustArchi** [comment]
@cathugger Interesting, I'm actually getting duplicated metadata there too.

```
root@archi:~# curl -s http://127.0.0.1:1333 | opusdec --float - - >/dev/null
Decoding to 48000 Hz (2 channels)
Encoded with libopus 1.3-beta-36-g004ef8b
ARTIST=Demetori
TITLE=リジッドパラダイス ～ Dawn of the Dead
ALBUM=BEGIERDE DES ZAUBERER
DATE=2011-12-30
GENRE=Game
ARTIST=Demetori
ALBUM=BEGIERDE DES ZAUBERER
TITLE=リジッドパラダイス ～ Dawn of the Dead
TRACK=3
GENRE=Game
DATE=2011-12-30
PERFORMER=Demetori
COMMENT=Rigid Paradise | Yoshika Miyako
[-] 00:00:11
```

Thing is, my files are properly tagged with metadata encoded in opus tags. I'm attaching a file sample used in above output: [リジッドパラダイス ～ Dawn of the Dead.zip](https://github.com/MusicPlayerDaemon/MPD/files/2321641/Dawn.of.the.Dead.zip)

Could you take a look and see if you can reproduce the issue with my file above? You can launch this file also locally in VLC and verify that tags are not duplicated, it has to be some MPD opus tags decoding issue.

**Comment by JustArchi** [comment]
No, it was one of the files of my current playlist, the output I got above was with initial metadata push on connect, I didn't wait for song change as metadata duplication already happened with it (see above).

**Comment by cathugger** [comment]
now that's weird. I checked with exfalso and metadata looks okay. But mpd (as seen in gmpc) somehow sees it as having 2 metadatas. Weird.

**Comment by cathugger** [comment]
I can reproduce your output but I don't think it's opus encoder what's doing it this way.

**Comment by cathugger** [comment]
```
$ nc 127.0.0.1 6600
OK MPD 0.21.0
currentsong
file: リジッドパラダイス ～ Dawn of the Dead.ogg
Last-Modified: 2016-10-21T06:33:32Z
Artist: Demetori
Title: リジッドパラダイス ～ Dawn of the Dead
Album: BEGIERDE DES ZAUBERER
Date: 2011-12-30
Genre: Game
Artist: Demetori
Album: BEGIERDE DES ZAUBERER
Title: リジッドパラダイス ～ Dawn of the Dead
Track: 3
Genre: Game
Date: 2011-12-30
Performer: Demetori
Time: 355
duration: 355.007
Pos: 14
Id: 15
OK
```

**Comment by JustArchi** [comment]
I'm happy that you managed to reproduce my issue.

Yes, metadata is definitely correct as I've used official `opusenc` for putting it and **[my python3-mutagen script](https://github.com/JustArchi/ArchiTag)** for appending comment field. I'm pretty sure that you should be able to reproduce it with any file that uses `OpusTags` field, for example `opusenc --title Test anyfile.flac reproduced.ogg`, as my script just appends extra field to existing `OpusTags` , I'm not using OGG container tags in any way (as this is what `OpusTags` are for in opus files).

I'm not sure what the root issue is as mpd seems to read the file correctly and doesn't show duplicated metadata, but pushing them further with `httpd` or `shout` protocol causes some of the fields to be duplicated. Note that not all fields are duplicated, for example `PERFORMER`, `TRACK` or `COMMENT` are not. Thing is, it doesn't make sense as opus tags are written correctly in the file so there is no reason for them to be duplicated - you can launch the file locally with any opus player like VLC or foobar and they'll read it correctly, no metadata duplication whatsoever.

**Comment by cathugger** [comment]
>as mpd seems to read the file correctly and doesn't show duplicated metadata
this sentence is probably no longer correct, please try reproducing with netcat command above

**Comment by JustArchi** [comment]
You're right, I've tried with some other file that follows the same `OpusTags` way and got the same issue.

```
root@archi:~# nc 127.0.0.1 6600
OK MPD 0.21.0
currentsong
file: 東京アクティブNEETs/2016.12.29 色は匂へど散りぬるを [C91]/コノ葉隠レ(Vocal version).ogg
Last-Modified: 2017-01-07T16:41:31Z
Artist: 東京アクティブNEETs
Title: コノ葉隠レ(Vocal version)
Album: 色は匂へど散りぬるを
Date: 2016-12-29
Artist: 東京アクティブNEETs
Album: 色は匂へど散りぬるを
Title: コノ葉隠レ(Vocal version)
Track: 3
Date: 2016-12-29
Comment: Wind God Girl | Aya Shameimaru
Time: 221
duration: 221.167
Pos: 21
Id: 22
OK
```

So it is MPD that in some way has metadata duplicated right at the file read step, interesting.

**Comment by JustArchi** [comment]
I think I'll open new issue for this one with all info in one place as at least half of this issue is no longer relevant for MPD, thanks for all your help @cathugger ❤️

**Comment by cathugger** [comment]
@JustArchi please check with other file types, this seems like issue with opus decoder, as I haven't observed it with FLAC files. Pretty much all my files are FLAC and I'm lazy to try myself.

**Comment by JustArchi** [comment]
Yes, I can't reproduce it with anything else either, my current culprit is `OpusTags` header that is somehow wrongly parsed or interpreted - I'm opening new issue about this one.
