### ISSUE TITLE
MPD metadata duplication with OpusTags opus files

### ISSUE THREAD

**Issue by JustArchi** [MusicPlayerDaemon/MPD#347]
This is a follow-up to issue #344 with huge thanks to @cathugger for helping me to debug the root cause.

MPD seems to read valid opus files with metadata included in `OpusTags` header, but some of the fields are duplicated. I'm attaching a **[file sample](https://github.com/MusicPlayerDaemon/MPD/files/2321641/Dawn.of.the.Dead.zip)** that reproduces this issue, but it should also be possible to reproduce with `opusenc --title Test anysong.flac reproduced.ogg` as `opusenc` uses `OpusTags` for writing title field.

Initially I thought that the issue is caused by `shout` protocol and related to Icecast2 but we've managed to reproduce it also with `httpd` protocol before finally verifying that MPD itself sees metadata as duplicated, so the bug is caused right at the file read and not some particular `output`:

```
$ nc 127.0.0.1 6600
OK MPD 0.21.0
currentsong
file: リジッドパラダイス ～ Dawn of the Dead.ogg
Last-Modified: 2016-10-21T06:33:32Z
Artist: Demetori
Title: リジッドパラダイス ～ Dawn of the Dead
Album: BEGIERDE DES ZAUBERER
Date: 2011-12-30
Genre: Game
Artist: Demetori
Album: BEGIERDE DES ZAUBERER
Title: リジッドパラダイス ～ Dawn of the Dead
Track: 3
Genre: Game
Date: 2011-12-30
Performer: Demetori
Time: 355
duration: 355.007
Pos: 14
Id: 15
OK
```

This issue seems to be specific to opus files with `OpusTags` header, I couldn't reproduce it with other file types or opus files that are using ogg container way of embedding metadata.

It's important to note that the file played locally with any opus-capable audio player does not suffer from metadata duplication, and the metadata is not duplicated in the file either. I've verified that with VLC and foobar. The file is not malformed, this is standard and recommended way of tagging opus files (as alternative to ogg container metadata).

The issue seems generic enough to not depend on some specific settings, but I'm attaching the log output anyway for easier debugging:

```
audio_output {
    type "httpd"
    encoder "opus"
    name "Test"
    port "1333"
    bind_to_address "127.0.0.1"
    always_on "yes"
    quality "10.0"
    format "48000:16:2"
    opustags "true"
}
```

With above output you can also reproduce the issue directly in `httpd`:

```
# curl -s http://127.0.0.1:1333 | opusdec --float - - >/dev/null
Decoding to 48000 Hz (2 channels)
Encoded with libopus 1.3-beta-36-g004ef8b
ARTIST=Demetori
TITLE=リジッドパラダイス ～ Dawn of the Dead
ALBUM=BEGIERDE DES ZAUBERER
DATE=2011-12-30
GENRE=Game
ARTIST=Demetori
ALBUM=BEGIERDE DES ZAUBERER
TITLE=リジッドパラダイス ～ Dawn of the Dead
TRACK=3
GENRE=Game
DATE=2011-12-30
PERFORMER=Demetori
COMMENT=Rigid Paradise | Yoshika Miyako
[-] 00:00:11
```

```
Music Player Daemon 0.21 (9151b84)

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local

Decoders plugins:
 [vorbis] ogg oga
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [pcm]

Filters:


Tag plugins:


Output plugins:
 shout null fifo oss httpd recorder

Encoder plugins:
 null vorbis opus wave

Input plugins:
 file curl

Playlist plugins:
 extm3u m3u pls cue embcue

Protocols:
 file:// http:// https://

Other features:
 epoll icu inotify ipv6 tcp un
```

Thank you in advance for looking into this issue.

**Comment by MaxKellermann** [comment]
3fae2150f5f120c5652ce6b62362ab040cf0945b

**Comment by JustArchi** [comment]
Thank you a lot for fixing this issue, I really appreciate it ❤️
