### ISSUE TITLE
Why don't you want to add support for internal mp3's lyrics kr .lrc files to add support for lyrics on protocol level?

### ISSUE THREAD

**Issue by initrider** [MusicPlayerDaemon/MPD#349]

**Comment by MaxKellermann** [comment]
I have no idea what that is, so I have no opinion.

**Comment by initrider** [comment]
@MaxKellermann http://id3.org/Lyrics3v2 ; https://en.m.wikipedia.org/wiki/LRC_(file_format)

**Comment by initrider** [comment]
@MaxKellermann http://id3.org/id3v2.3.0#Unsychronised_lyrics.2Ftext_transcription
