### ISSUE TITLE
Allow setting full audio output name

### ISSUE THREAD

**Issue by squigglezworth** [MusicPlayerDaemon/MPD#351]
For me, having the audio output name be readable at a glance is important -- thus, having "Music Player Daemon: " in front of it at all times can be a little troubling.

It would be helpful to be able to set the full string, allowing users to include that prefix if wanted (and by default) but also allowing those who want to to set the entire string

**Comment by MaxKellermann** [comment]
Huh? I don't understand any of this. You can give outputs arbitrary names. Up to you. What else do you want?

**Comment by squigglezworth** [comment]
I..... think that's pretty clear. Even when setting the output name to an empty string, the audio output name is "Music Player Daemon: "

I don't want it do display Music Player Daemon unless I put that in the setting

**Comment by MaxKellermann** [comment]
Who is "it"?

**Comment by squigglezworth** [comment]
Every Pulseaudio control interface I've tried. pavucontrol, pulsemixer, even pactl.

**Comment by squigglezworth** [comment]
It occurs to me this might simply be what all the interfaces do. Use the application name, as well as the application-supplied name.

If this is the case, apologies for wasting both of our time. :)

**Comment by MaxKellermann** [comment]
So you're talking about PulseAudio, not MPD. What you're seeing is the application name connected to PulseAudio. This prefix is not added by MPD; MPD merely states its own name, but it does not add this prefix to output names.
Not my department!
