### ISSUE TITLE
Feature Request: Define background picture

### ISSUE THREAD

**Issue by suermel** [MusicPlayerDaemon/MPD#352]
I would like to ask for a background picture in gmpc. No album art, just an ordinaly picture, needs not to be scalable. The reason for the request is I have gmpc 11.8.16.10 running in kiosk mode on a Raspberry Pi with touchscreen display, which is built into a jukebox. A solid background image would look really nice on this device.

**Comment by MaxKellermann** [comment]
This is MPD, not gmpc. You can't request gmpc features here.

**Comment by suermel** [comment]
yes sorry the GMPC bugtracker referres to this page.
There doesn seem to exist a bugtracker for GMPC then?
https://gmpclient.org/

--- Ursprüngliche Nachricht ---
Von: Max Kellermann <notifications@github.com>
Datum: 09.09.2018 16:51:40
An: MusicPlayerDaemon/MPD <MPD@noreply.github.com>
Betreff: Re: [MusicPlayerDaemon/MPD] Feature Request: Define background  picture (#352)

> This is MPD, not gmpc. You can't request gmpc features here.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MusicPlayerDaemon/MPD/issues/352#issuecomment-419721157
> 


---

________________________________________________________
Ihre E-Mail-Postfächer sicher & zentral an einem Ort. Jetzt wechseln und alte E-Mail-Adresse mitnehmen! https://www.eclipso.ch

**Comment by MaxKellermann** [comment]
This page refers to http://musicpd.org/mantis/ which hasn't existed for 5+ years or so. That page has a permanent redirect to http://bugs.musicpd.org/ which has ceased to exist nearly 2 years ago, after the bug tracker got hacked, and MPD moved to GitHub. I don't know what the gmpc project is up to now. Doesn't look good for the project's health if the bugtracker link hasn't been updated for so many years.
