### ISSUE TITLE
Cannot play flac stream

### ISSUE THREAD

**Issue by parkmino** [MusicPlayerDaemon/MPD#354]
I tried to play an flac stream - http://rondo.iradio.fi:8000/klasu.flac
It does not play and no progress while there's no problem to play with mpv, vlc and gst123.
Could you please check this on your side?

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by parkmino** [comment]
I run
$ mpc add http://rondo.iradio.fi:8000/klasu.flac
$ mpc play
and mpd does not respond.
Please let me know what I should do to send you log file or something like that.
Do you play the http://rondo.iradio.fi:8000/klasu.flac by mpd ?
And then I should close this issue.

$ mpd --version
Music Player Daemon 0.20.21

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local

Decoders plugins:
 [oggflac] ogg oga
 [flac] flac
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:


Tag plugins:
 id3tag

Output plugins:
 null alsa

Input plugins:
 file alsa curl ffmpeg mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// alsa://

Other features:
 epoll tcp

**Comment by MaxKellermann** [comment]
I'll reopen this as soon as you have added the missing information I requested from you.

**Comment by parkmino** [comment]
I understand your comments however I do not know what I could do it more to clear this issue.
Have you ever tried the stream http://rondo.iradio.fi:8000/klasu.flac ?
I do not receive any feedback from you except the fundamental comment.

$ cat /etc/mpd.conf

user "root"
bind_to_address "127.0.0.1"
metadata_to_use	"none"
zeroconf_enabled "no"
input {
plugin "file"
enabled "no"
}
input {
plugin "alsa"
enabled "no"
}
input {
plugin "ffmpeg"
enabled "no"
}
input {
plugin "mms"
enabled "no"
}
mixer_type "disabled"
audio_output {
type "alsa"
name "ALSA"
device "pcm.0"
auto_resample "no"
auto_channels "no"
auto_format "no"
mixer_device "/dev/null"
mixer_type "none"
replay_gain_handler "none"
}
decoder {
plugin "oggflac"
enabled "no"
}
decoder {
plugin "dsdiff"
enabled "no"
}
decoder {
plugin "dsf"
enabled "no"
}
decoder {
plugin "pcm"
enabled "no"
}
playlist_plugin {
name "asx"
enabled "no"
}
playlist_plugin {
name "rss"
enabled "no"
}
playlist_plugin {
name "embcue"
enabled "no"
}
playlist_plugin {
name "flac"
enabled "no"
}
audio_buffer_size "3683"
buffer_before_play "10.55969372980212839891001004021011%"

**Comment by MaxKellermann** [comment]
Setups with buffer settings are unsupported, so this alone would qualify for closing this issue for good. Just don't mess with those settings!
But the cause for your problem is trivial to find somewhere else, it's a true PEBCAK: you're trying to play an OggFlac stream, but you explicitly disabled the OggFlac plugin. For reasons only you know. Duh!

**Comment by parkmino** [comment]
No. oggflac decoder only affects to ogg not flac.
Enabling oggflac does not resolve this issue.
Have you ever tried the flac url and no problem on your side?
Then I will accept that it is my fault.

**Comment by parkmino** [comment]
OMG, it takes too long to play this url.
It plays the url after several minutes without changing my configuration.
It works anyway but it takes too long!

**Comment by MaxKellermann** [comment]
Yes, I can play the URL just fine, but that doesn't prove it's your fault. That alone wouldn't justify closing your bug report.

Our real problem right now is that we can't agree on a common logical base. I'm very certain that the stream is OggFlac, which can be proved by looking at the `Content-Type` header. But you reject this fact. I can't help you that way, without being able to revert to logic.

**Comment by MaxKellermann** [comment]
As I already wrote, don't mess with buffer settings.

**Comment by MaxKellermann** [comment]
Sigh. Two things are wrong with your last reply.
1. no, enabling `oggflac` is not necessary because it is enabled by default. You disabled it explicitly, and you disabled lots of other plugins, for whatever reasons. I don't know, and I cannot image why you would want to do that. See, your case demonstrates exactly why I refuse to even look at a problem without **all** the information. People think I am rude, but it's really people who post incomplete issue reports are rude towards me, because they waste my time.
2. yes, buffer settings are changed, as visible in your `mpd.conf` paste. You said you "commented out disabling oggflac" but you did not mention that you removed the buffer settings. Maybe you just forgot to mention that, but it's terribly hard to help you if you omit vital parts of your story. See above.

**Comment by parkmino** [comment]
It might be absurd to you that disabling not used codecs and changing buffers affects to sound quality.
At least disabling features save the system resource slightly though.

**Comment by MaxKellermann** [comment]
Again all of your points are wrong.
1. the codec you disabled was not "not used"; it was vitally necessary for the stream you wanted to play
2. I did not say that changing buffers affects sound quality, but yes, it can
3. changing buffers can affect lots of things and can cause lots of problems (for example complete failure to start playback, or slow playback, stuttering and more); of course you can do that if you want, but I'll refuse to help you if you run into trouble (your freedom and my freedom)
4. disabling those features at runtime doesn't save system resources; disabling them at compile time would

**Comment by MaxKellermann** [comment]
I think I misunderstood your sentence about "changing buffers affects to sound quality". Your sentence was a bit obscure. You said something might be "absurd to me", but other than pointing out a possible absurdness, it did not say anything, it had no point.

**Comment by parkmino** [comment]
That's what I said it might be absurd to you.
I do not want argue about the sound quality and anyway it is good to have options to change.
My buffer settings are not far from the default and the default 4096KB 10%, it might not cause serious problem.

**Comment by MaxKellermann** [comment]
I'm going to lock this thread now, because your self-inflicted issue is solved, and I feel that my ongoing explanations are not helping you.
In any case, please refrain from reporting problems or seeking any other sort of help from this project as long as you insist on those buffer settings.
