### ISSUE TITLE
Two audio outputs enabled result in short "hickup" at beginning of playback

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#356]
MPD from git, Snapcast from git, Linux x64, Debian testing.

Excerpt from mpd.conf

audio_output {
        type            "alsa"
        name            "Lexicon Omega"
        device          "hw:Omega"
        auto_resample   "no"
        auto_format     "no"
        mixer_type      "software"
        # no hardware mixer for device
}
audio_output {
    type            "fifo"
    name            "SnapCast"
    path            "/tmp/snapfifo" 
    format          "48000:16:2"
}

Start playback, a short "hickup" (< 1 second) on ALSA device occurs. Stop playback and start again to reproduce. Disable Snapcast output in MPD client and audio playback works flawless. Bug or feature?

**Comment by MaxKellermann** [comment]
The `fifo` output is experimental and unsupported. It should not be used. It is unfortunate that SnapCast decided to build the software on top of this messy plugin. I wish SnapCast had instead submitted a new output plugin to this project.

**Comment by skidoo23** [comment]
Bad news. I wanted to write some kind of mixer plugin to control volume, mute and maybe some grouping functions from SnapCast via its JSON-RPC API. Implementing complete SnapCast client and server functionality is somewhat beyond my time and errr... capabilities.

**Comment by MaxKellermann** [comment]
This is obsolete because MPD has a native Snapcast output plugin now.
