### ISSUE TITLE
MPD "freezes"/is unresponsive when (forced) disconnected from icecast server

### ISSUE THREAD

**Issue by Neui** [MusicPlayerDaemon/MPD#357]
# How to reproduce

1. Setup an icecast instance (in my case version 2.4.3)
2. Configure mpd to output to that icecast
3. Active the icecast output and start to play something (make sure it's actually streaming to it)
4. Disconnect (kill network on the mpd server in my case)
5. Try to toggle pause
6. Client complains about loosing the connection and can't connect

After a somewhat long time (0.5h - 1h?) it comes back alive, but I haven't really tested this. I usually killed mpd (I needed to use KILL, not TERM) and restarted it by hand.

# More information

Client: gmpc (11.8.16) and mpc (0.29? from the man page)  
Server: mpd 0.20.21 (custom compiled with `-g -Og`) and mpd 0.20.18 (from Ubuntu 18.04)

While it was unconnectable, I used `gdb` and did `thread apply all bt`: https://hastebin.com/raw/desugokuju (on the compiled 0.20.21 version so I can provide symbols)

**Comment by MaxKellermann** [comment]
This "hastebin" link gives me "Application Error".

**Comment by Neui** [comment]
It's a pastebin clone. It seems it is now online again, but for all cases here is a github gist mirror: https://gist.githubusercontent.com/Neui/1b210588f89f018a61ce52a0108b6419/raw/d10cff55036581eac95edbb676ef44ac07064a1f/gistfile1.txt

**Comment by MaxKellermann** [comment]
Your backtrace shows that MPD is stuck inside libshout. If anything, then this is a libshout problem. Since libshout has no asynchronous API, there is nothing MPD can do about it. Sorry.
