### ISSUE TITLE
MPD couldn't boot

### ISSUE THREAD

**Issue by grossestein** [MusicPlayerDaemon/MPD#358]
Archlinux user. 
After I added some songs to the music folder, I try to update database via 'u' in the ncmpcpp, then the mpd crashed. Because I occasionally installed Pulseaudio that time( I am a ALSA user ), I uninstalled Pulseaudio and totally reinstalled mpd, Eventuallly, I found I cann't boot mpd.  

This is the error [info](https://pastebin.com/P3m82yfQ).
[mpd.conf](https://pastebin.com/Ag14gVbr)

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by MaxKellermann** [comment]
Will reopen as soon as reporter provided enough information.

**Comment by grossestein** [comment]
> Will reopen as soon as reporter provided enough information.

I think I solved this after I added the "mpd" to group "users".
