### ISSUE TITLE
Does the new filter syntax in 0.21.0 protocol works?

### ISSUE THREAD

**Issue by Szunti** [MusicPlayerDaemon/MPD#365]
```
OK MPD 0.21.0
search (title)
ACK [2@0] {search} '==' or '!=' expected
search (title==)
ACK [5@0] {} Invalid unquoted character
search (title=='code')
ACK [5@0] {} Invalid unquoted character
search (title=="code")
ACK [5@0] {} Invalid unquoted character
```
I think the two last ones should be valid or at least one of them.
compiled from current master (6c40a278090e1621aaa6bc4c7a2cb6746d09e5e1)

**Comment by MaxKellermann** [comment]
Your basic protocol syntax is wrong. You must quote command parameters if they contain certain characters, and this is exactly what MPD's error message told you. Try:
`search "(title=='code')"`
