### ISSUE TITLE
win32 output shout crashes

### ISSUE THREAD

**Issue by KruegerDead** [MusicPlayerDaemon/MPD#368]
I try latest win32 builds of mpd (0.20.21 and previous), when you are using audio_output with type shout, mpd crashes on launch without any logs. log_level "verbose" doesn't show anything. Also I try to find working version, from this https://www.musicpd.org/download/win32/ all builds have the same problem. 
I found old version (0.17.4) and it's work fine. Any chance to fix this bug in new builds for win32?

my mpd.conf
```
music_directory     "e:/radio/mpd/music"
playlist_directory  "e:/radio/mpd/playlists"
db_file             "e:/radio/mpd/database/mpd.db"
log_file            "e:/radio/mpd/log/mpd.log"
state_file          "e:/radio/mpd/log/state"

bind_to_address	    "localhost"
port                "6600"

log_level "verbose"

audio_output {
type "shout"
encoding "vorbis"
name "my cool stream"
host "127.0.0.1"
port "8000"
mount "/mpd.ogg"
password "HACKME"
quality "5.0"
#bitrate "128"
format "44100:16:2"
protocol "icecast2"
user "source"
description "here is my long description"
genre "jazz"
public "no"
}
```

If you need more info for debug this issue, i will try to get it.

**Comment by MaxKellermann** [comment]
The Windows build has no Shout plugin, because libshout fails to compile on Windows. I see this error message on the console:
`No such audio output plugin: shout`
This happens before MPD opens the log file, so maybe you attempt to run MPD without a console window so you don't see it.
But you can use the `httpd` output plugin instead.

**Comment by MaxKellermann** [comment]
The Windows build of MPD has no Shout support, because libshout fails to compile on Windows.
This error message is shown on the console: `No such audio output plugin: shout`
Try to use the `httpd` plugin instead.
