### ISSUE TITLE
gcc 7.3 compiler warnings, clang 6.0 ok

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#370]
Lubuntu 18.04. x_64, MPD from git master, gcc 7.3.0 or clang 6.0

In file included from src/unix/Daemon.cxx:28:0:
src/unix/PidFile.hxx: In member function ‘void PidFile::Write(pid_t)’:
src/unix/PidFile.hxx:77:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   write(fd, buffer, strlen(buffer));
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/unix/Daemon.cxx: In function ‘void daemonize_commit()’:
src/unix/Daemon.cxx:210:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   write(detach_fd, &result, sizeof(result));
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(...)

src/util/Alloc.cxx: In function ‘void oom()’:
src/util/Alloc.cxx:32:2: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  (void)write(STDERR_FILENO, "Out of memory\n", 14);

**Comment by MaxKellermann** [comment]
The last warning in Alloc.cxx suggests that this is a compiler bug. The return value is not ignored; it is explictly casted to `void`.
I don't see any of those warnings with GCC 6.3, GCC 8.1, clang 7.0.0

**Comment by skidoo23** [comment]
No warning with gcc 8.2 too. Case closed.
