### ISSUE TITLE
Meson 0.45.1 Unknown type feature.

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#371]
I really hate to write this. Lubuntu 18.04, x64, recent updates applied. MPD from git/master - meson 0.48 (from Debian testing) runs without problems.

$ meson . output
The Meson build system
Version: 0.45.1
Source dir: /home/skidoo/src/mygit/MPD
Build dir: /home/skidoo/src/mygit/MPD/output
Build type: native build

meson_options.txt:5:0: ERROR: Unknown type feature.

A full log can be found at /home/skidoo/src/mygit/MPD/output/meson-logs/meson-log.txt
$ cat /home/skidoo/src/mygit/MPD/output/meson-logs/meson-log.txt
Build started at 2018-10-16T00:34:58.185826
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/skidoo/src/mygit/MPD
Build dir: /home/skidoo/src/mygit/MPD/output
Build type: native build

meson_options.txt:5:0: ERROR: Unknown type feature.

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/MPD/blob/master/meson.build#L5

**Comment by MaxKellermann** [comment]
It is already documented: https://www.musicpd.org/doc/html/user.html#compiling-from-source says Meson 0.47 is required.
Only 0.21. See: `git checkout v0.20.x && ls -l meson.build`

**Comment by skidoo23** [comment]
Reloading webpage helped.
