### ISSUE TITLE
SIGABRT in IsFileNotFound

### ISSUE THREAD

**Issue by riggs-** [MusicPlayerDaemon/MPD#373]
We have another instance of issue #41 on FreeBSD (reproducible e.g. with clang6 on i386):
`IsFileNotFound()` in `src/input/Error.hxx` is declared `gcc_pure` but it executes `std::rethrow_exception(ep);`

Thus it dies with SIGABRT on the first startup when no database exists yet. Can we remove the `gcc_pure`?

**Comment by riggs-** [comment]
This is the FreeBSD commit that fixes things for us in the current version of mpd:
https://svnweb.freebsd.org/ports/head/audio/musicpd/files/patch-src_input_Error.hxx?view=markup&pathrev=482238

**Comment by riggs-** [comment]
I'll check under which circumstances I can reproduce this problem.

**Comment by MaxKellermann** [comment]
I can reproduce this with clang 7 on Android. This very much looks like a clang bug! Can you please report it to the clang/llvm project? I'll add a workaround to MPD inside an `#ifdef __clang__` so it doesn't hurt GCC builds.

**Comment by MaxKellermann** [comment]
Oh no, I found more instances of this clang bug. I get lots of Android crash reports caused by this clang bug in other places.

**Comment by MaxKellermann** [comment]
Reported to the Android NDK bug tracker, let's see if they figure something out: https://github.com/android-ndk/ndk/issues/831

**Comment by riggs-** [comment]
Great, thank you for following up!
In the Android ndk bug you filed there is a response mentioning a fix in llvm 7.0: https://bugs.llvm.org/show_bug.cgi?id=32611
