### ISSUE TITLE
un-pausing song on smb:// skips to next track

### ISSUE THREAD

**Issue by azrdev** [MusicPlayerDaemon/MPD#376]
I have a satellite setup here, with a standard client config:
~~~
music_directory         "smb://192.168.x.y/music/"
database {
       plugin "proxy"
       host "192.168.x.y"
       port "6600"
}
...
~~~

This is on a laptop where I frequently pause/unpause the music, and go to suspend/resume (usually while music is paused).

When unpausing mpd after I have been in standby since it last played, it will continue with the current track for some seconds, but then skip to the next track. `mpd.log` contains
~~~
Oct 20 13:41 : exception: smbc_read() failed: Software caused connection abort
Oct 20 13:41 : player: played "previous_song.mp3"
~~~

# versions
(on the client)
Music Player Daemon 0.20.21
smbclient 4.8.5-1

from archlinux packages

**Comment by MaxKellermann** [comment]
This should be fixed by the new input cache in MPD 0.21. Please report if you still see the problem.

**Comment by azrdev** [comment]
@MaxKellermann just experienced this again. Do I have to enable/configure the input cache somehow? changelog only says `  - curl: download to buffer instead of throttling transfer`, nothing about smb/input in general.
~~~sh
$ mpc version 
mpd version: 0.21.6

**Comment by MaxKellermann** [comment]
True, the caching adapter was only enabled in the source code inside the CURL plugin - this should be enabled in all networking plugins.

**Comment by azrdev** [comment]
@MaxKellermann thank you! IIRC I had the same issue when using nfs instead of smb (but I don't remember if both were affected: built-in libnfs and OS-mounted nfs, with a "local" directory in mpd.conf). While you're at it, is it possible & useful to enable this for libnfs, too?
