### ISSUE TITLE
[database] add "date added" attribute for songs

### ISSUE THREAD

**Issue by Scrumplex** [MusicPlayerDaemon/MPD#378]
MPD should track for changes and add a "date added" attribute, so one can look for new songs in the database.

**Comment by jcorporation** [comment]
This feature would be great! I am unsure if it is better to get the timestamp when the song was added to the database or the creation time of the file.

I will look at the MPD code, if I could implement this. @MaxKellermann: What do you think and can you give me some hints, how it should be implemented that it can be merged?
