### ISSUE TITLE
DST format

### ISSUE THREAD

**Issue by bekovsky** [MusicPlayerDaemon/MPD#379]
Unfortunately, there is information on the Internet about the DST format, which has a liquefaction similar to lossless (flac for wav), although I may be mistaken.
I would like to hear from you about the support for this format for MPD. And are the capacities of most ARM-based boards enough to decode it? Thank you very much.

**Comment by skidoo23** [comment]
Are you talking about Direct Stream Transfer? See IEC 14496-3. MPD support via ffmpeg.

**Comment by MaxKellermann** [comment]
I've never before heard of this DST, and this issue's description is rather confusing. But since @skidoo23 noted that FFmpeg supports it, I thin I can safely close this one.

**Comment by bekovsky** [comment]
http://www.sonicstudio.com/pdf/dsd/DSDIFF_1.5_Spec.pdf
DST Direct Stream Transfer
Format for lossless encoded DSD audio
DST File DSDIFF file containing DST encoded audio

**Comment by bekovsky** [comment]
http://bitperfectsound.blogspot.com/2014/12/dst-compression.html
