### ISSUE TITLE
Launchctl plist does not work on macOS Sierra

### ISSUE THREAD

**Issue by ibrokemypie** [MusicPlayerDaemon/MPD#38]
using launchctl -w load $PLIST shows no visible error, however mpd is not run and checking console reveals that it has been silently failing instantly after load.
I have installed through homebrew with the --HEAD flag

**Comment by MaxKellermann** [comment]
Anything related to `launchctl` is out of this project's scope. This project does not support Apple's init implementation. Maybe you meant to report this to the Homebrew project?
If, however, this bug report was about MPD's failure to report a problem, rephrase your report and add more information about the problem.
So far, I don't even know what MPD version you're using (and I've never used Homebrew).
