### ISSUE TITLE
MPD UPnP Database Plugin failed with Upmpdcli

### ISSUE THREAD

**Issue by marcbth** [MusicPlayerDaemon/MPD#383]
Hello,

I used the mpd from Upmpdcli and Upmpdcli and the asset upnp server.

when I try in mpd.conf 

database
upnp

I can see all files from the asset upnp server but
from the Upmpdcli Qobuz I can't 
in ncmpc i have : 

Discover catalog
Discover Genres
Favourites

then 

no such object.

can I help me, please.

Thanks

Marc

**Comment by marcbth** [comment]
Sorry,

its on Debian stretch

**Comment by MaxKellermann** [comment]
I don't understand what this is about. Let's start with this one: https://www.musicpd.org/help/

**Comment by marcbth** [comment]
Thanks for your answer.

I Try this

mpd --stdout --no-daemon --verbose
config_file: loading file /etc/mpd.conf
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.5
opus: libopus 1.2~alpha2
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg
adplug: adplug 2.2.1
config: Ignoring the storage configuration because the database does not need it
curl: version 7.52.1
curl: with OpenSSL/1.0.2l
avahi: Initializing interface
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/debian
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
config: option 'use_mmap' on line 70 was not recognized
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
client: [0] opened from [::1]:38252
client: [0] process command "status"
exception: Failed to read mixer for 'DAC': no such mixer control: PCM
client: [0] command returned 0
avahi: Service group changed to state 2
avahi: Service 'debian' successfully established.client: [1] process command "lsinfo "Streamingdienste9""
client: [1] command returned 0
client: [1] process command "idle"client: [1] process command "lsinfo "Streamingdienste9/Discover Catalog""
exception: No such object
client: [1] command returned 2

**Comment by marcbth** [comment]
mpd --version
Music Player Daemon 0.20.12

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un

**Comment by ranperry** [comment]
This is not an MPD issue. Try here
https://www.lesbonscomptes.com/upmpdcli/upmpdcli-or-mpdupnp.html

**Comment by MaxKellermann** [comment]
You failed at "make sure you have the latest MPD version (0.20.22)" (https://www.musicpd.org/help/)
