### ISSUE TITLE
Android: Tasker integration

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#390]
I would like to be able to start/stop mpd depending on other states (which Tasker handles perfectly)

Also to be able to configure mpd (database proxy ip) is a great use case

**Comment by MaxKellermann** [comment]
Sorry, Tasker is a commercial closed-source app. MPD will not have explicit support for that.

**Comment by roizcorp** [comment]
how about dedicated intents for start/stop mpd?
