### ISSUE TITLE
mpd 0.21 not buildable on fedora with ffmpeg 4.0.2 

### ISSUE THREAD

**Issue by dominik96** [MusicPlayerDaemon/MPD#392]
ninja: Entering directory `x86_64-redhat-linux-gnu'
[186/486] Compiling C++ object 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o'.
FAILED: src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o 
ccache c++ -Isrc/input/plugins/src@input@plugins@@input_plugins@sta -Isrc/input/plugins -I../src/input/plugins -Isrc -I../src -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -Wall -Wextra -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -D_GNU_SOURCE -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack -fPIC  -MD -MQ 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o' -MF 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o.d' -o 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o' -c ../src/input/plugins/FfmpegInputPlugin.cxx
../src/input/plugins/FfmpegInputPlugin.cxx:34:10: fatal error: libavformat/avio.h: No such file or directory
 #include <libavformat/avio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[191/486] Compiling C++ object 'src/input/src@input@@input_glue@sta/Init.cxx.o'.
ninja: build stopped: subcommand failed.
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.4htBUV (%build)

Fehler beim Bauen des RPM:
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.4htBUV (%build)
----------------------------------------------------------------------------

/usr/include/ffmpeg/libavformat
/usr/include/ffmpeg/libavformat/avformat.h
/usr/include/ffmpeg/libavformat/avio.h
/usr/include/ffmpeg/libavformat/version.h

------------------------------------------------------------------------------------

%prep
%setup -q

%build
export CFLAGS="%{optflags} -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie $CFLAGS"
%meson --strip --auto-features=disabled \
-Ddocumentation=true \
-Dsyslog=disabled \
-Ddaemon=false \
-Dsystemd=disabled \
-Dffmpeg=enabled \
-Dhttpd=true \
-Did3tag=enabled \
-Dlame=enabled \
-Dpulse=enabled \
-Dfaad=enabled \
-Dflac=enabled \
-Dvorbis=enabled \
-Dvorbisenc=enabled \
-Dalsa=enabled 
ninja -C x86_64-redhat-linux-gnu

%install
cd x86_64-redhat-linux-gnu
DESTDIR=%{buildroot} ninja install
mkdir -p %{buildroot}%{_sharedstatedir}/%{name}/playlists %{buildroot}%{_sharedstatedir}/%{name}/music %{buildroot}%{_unitdir}
rm -rf %{buildroot}%{_docdir}/%{name}/ %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/mpd.svg
install -m 0644 %{SOURCE1} %{buildroot}%{_unitdir}
strip -s %{buildroot}%{_bindir}/%{name}

**Comment by MaxKellermann** [comment]
What's the output of `pkg-config libavcodec --cflags`?

**Comment by dominik96** [comment]
[root@srv:~]$ pkg-config libavcodec --cflags
-I/usr/include/ffmpeg

**Comment by dominik96** [comment]
ffmpeg build:

./configure \
    --arch=%{_target_cpu} \
    --bindir=%{_bindir} \
    --datadir=%{_datadir}/%{name} \
    --incdir=%{_includedir}/%{name} \
    --libdir=%{_libdir} \
    --mandir=%{_mandir} \
    --optflags="%{optflags}" \
    --prefix=%{_prefix} \
    --shlibdir=%{_libdir} \
    --extra-cflags="-I%{_prefix}/local/x264 %{optflags} -Ofast -ffast-math -funsafe-math-optimizations -funroll-loops -funswitch-loops -Wno-pointer-sign -minline-all-stringops" \
    --extra-ldflags="-I%{_prefix}/local/x264 -L%{_prefix}/local/x264 -ldl -Wl,-z,now -Wl,-z,relro,-z,noexecstack %{optflags} -Ofast -ffast-math -funsafe-math-optimizations -funroll-loops -funswitch-loops -Wno-pointer-sign -minline-all-stringops" \
    --disable-debug \
    --disable-logging \
    --disable-htmlpages \
    --disable-podpages \
    --disable-txtpages \
    --enable-small \
    --enable-gpl \
    --enable-nonfree \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libfdk_aac \
    --enable-libmp3lame \
    --enable-libvorbis \
    --enable-shared

**Comment by dominik96** [comment]
export CFLAGS="%{optflags} -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack -I/usr/include/ffmpeg"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie $CFLAGS"

add "-I/usr/include/ffmpeg" to CFLAGS fix the build problem

**Comment by MaxKellermann** [comment]
I think I know what's causing this. Adding a dependency on a static library inherits its sub-libraries, but not its CFLAGS.

**Comment by dominik96** [comment]
Nov 01 18:42 : exception: Failed to decode Deep Purple/Purpendicular/03 Soon Forgotten.mp3
Nov 01 18:42 : player: played "Deep Purple/Purpendicular/03 Soon Forgotten.mp3"

**Comment by dominik96** [comment]
do you have a solution for me?

**Comment by MaxKellermann** [comment]
Please don't mix different issues in this bug report. This gets confusing and in the end none will be solved.

**Comment by dominik96** [comment]
it makes me sick when good thinks changed with no good reason! 
../src/input/plugins/FfmpegInputPlugin.cxx:34:10: fatal error: libavformat/avio.h: No such file or directory
#include <libavformat/avio.h>

meson kills my old spec-file with %configure ...... and mpd is with meson not buildable on my system, the same problem was for a year with libmpdclient 

Fedora Users need a solution BTW i doesn't mix differnt issuses in this bug report

**Comment by dominik96** [comment]
[dsoft@srv:~/rpmbuild]$ rpmbuild -bb SPECS/mpd-meson.spec 
Ausführung(%prep): /bin/sh -e /var/tmp/rpm-tmp.FDLzCz
+ umask 022
+ cd /home/dsoft/rpmbuild/BUILD
+ cd /home/dsoft/rpmbuild/BUILD
+ rm -rf mpd-0.21
+ /usr/bin/xz -dc /home/dsoft/rpmbuild/SOURCES/mpd-0.21.tar.xz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd mpd-0.21
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Ausführung(%build): /bin/sh -e /var/tmp/rpm-tmp.uvU4Zl
+ umask 022
+ cd /home/dsoft/rpmbuild/BUILD
+ cd mpd-0.21
+ export 'CFLAGS=-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ CFLAGS='-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export 'CXXFLAGS=-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ CXXFLAGS='-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export 'CC=gcc -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ CC='gcc -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export 'LDFLAGS=-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ LDFLAGS='-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ CFLAGS='-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export CFLAGS
+ CXXFLAGS='-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export CXXFLAGS
+ FFLAGS='-m64 -march=core2 -mtune=core2 -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-m64 -march=core2 -mtune=core2 -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
+ export LDFLAGS
+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-redhat-linux-gnu --strip --auto-features=disabled --default-library=static -Ddocumentation=true -Dsyslog=disabled -Ddaemon=false -Dsystemd=disabled -Dffmpeg=enabled -Dhttpd=true -Did3tag=enabled -Dlame=enabled -Dpulse=enabled -Dfaad=enabled -Dflac=enabled -Dvorbis=enabled -Dvorbisenc=enabled -Dalsa=enabled
The Meson build system
Version: 0.47.2
Source dir: /data/dokuments/rpmbuild/BUILD/mpd-0.21
Build dir: /data/dokuments/rpmbuild/BUILD/mpd-0.21/x86_64-redhat-linux-gnu
Build type: native build
Project name: mpd
Project version: 0.21
Appending CFLAGS from environment: '-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
Appending LDFLAGS from environment: '-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
Native C compiler: gcc -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack (gcc 8.2.1 "gcc (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)")
Appending CXXFLAGS from environment: '-m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
Appending LDFLAGS from environment: '-Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack'
Native C++ compiler: ccache c++ (gcc 8.2.1 "c++ (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C++ supports arguments -Wall: YES
Compiler for C++ supports arguments -Wextra: YES
Compiler for C++ supports arguments -fvisibility=hidden: YES
Compiler for C++ supports arguments -ffast-math: YES
Compiler for C++ supports arguments -ftree-vectorize: YES
Compiler for C++ supports arguments -fno-threadsafe-statics: YES
Compiler for C++ supports arguments -fmerge-all-constants: YES
Compiler for C++ supports arguments -Wmissing-declarations: YES
Compiler for C++ supports arguments -Wshadow: YES
Compiler for C++ supports arguments -Wpointer-arith: YES
Compiler for C++ supports arguments -Wcast-qual: YES
Compiler for C++ supports arguments -Wwrite-strings: YES
Compiler for C++ supports arguments -Wsign-compare: YES
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES
Compiler for C++ supports arguments -Wno-noexcept-type -Wnoexcept-type: YES
Compiler for C supports arguments -Wall: YES
Compiler for C supports arguments -Wextra: YES
Compiler for C supports arguments -fvisibility=hidden: YES
Compiler for C supports arguments -ffast-math: YES
Compiler for C supports arguments -ftree-vectorize: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wshadow: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wcast-qual: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -pedantic: YES
Compiler for C supports arguments -ffunction-sections: YES
Compiler for C supports arguments -fdata-sections: YES
Compiler for C++ supports link arguments -Wl,--gc-sections: YES
Has header "locale.h": YES
Checking for function "getpwnam_r" : YES
Checking for function "getpwuid_r" : YES
Checking for function "initgroups" : YES
Checking for function "fnmatch" : YES
Checking for function "strndup" : YES
Checking for function "strcasestr" : YES
Dependency Boost () found: YES 1.66
Dependency threads found: YES
Dependency dbus-1 skipped: feature dbus disabled
Dependency icu-i18n skipped: feature icu disabled
Dependency smbclient skipped: feature smbclient disabled
Dependency zlib skipped: feature zlib disabled
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency alsa found: YES 1.1.6
Dependency libcurl skipped: feature curl disabled
Dependency expat skipped: feature expat disabled
Native dependency libavformat found: YES 58.12.100
Native dependency libavcodec found: YES 58.18.100
Native dependency libavutil found: YES 56.14.100
Library gcrypt skipped: feature qobuz disabled
Dependency (anonymous) skipped: feature libwrap disabled
Dependency libnfs skipped: feature nfs disabled
Native dependency libpulse found: YES 12.2-rebootstrapped
Library sndio skipped: feature sndio disabled
Dependency sqlite3 skipped: feature sqlite disabled
Dependency libsystemd skipped: feature systemd disabled
Dependency libupnp skipped: feature upnp disabled
Dependency yajl skipped: feature yajl disabled
Header <sys/socket.h> has symbol "struct ucred": YES
Header <sys/socket.h> has symbol "SO_PEERCRED": YES
Checking for function "getpeereid" : NO
Native dependency id3tag found: YES 0.15.1b
Dependency libchromaprint skipped: feature chromaprint disabled
Dependency samplerate skipped: feature libsamplerate disabled
Dependency soxr skipped: feature soxr disabled
Dependency libcdio_paranoia skipped: feature cdio_paranoia disabled
Dependency libmms skipped: feature mms disabled
Dependency libiso9660 skipped: feature iso9660 disabled
Library bz2 skipped: feature bzip2 disabled
Dependency zziplib skipped: feature zzip disabled
Dependency ao skipped: feature ao disabled
Dependency jack skipped: feature jack disabled
Dependency shout skipped: feature shout disabled
Native dependency flac found: YES 1.3.2
Dependency opus skipped: feature opus disabled
Native dependency vorbis found: YES 1.3.6
Native dependency vorbisenc found: YES 1.3.6
Native dependency ogg found: YES 1.3.2
Dependency adplug skipped: feature adplug disabled
Dependency fluidsynth skipped: feature fluidsynth disabled
Dependency audiofile skipped: feature audiofile disabled
Library faad found: YES
Library gme skipped: feature gme disabled
Library mad skipped: feature mad disabled
Dependency libmikmod skipped: feature mikmod disabled
Dependency libmodplug skipped: feature modplug disabled
Library mpcdec skipped: feature mpcdec disabled
Dependency libmpg123 skipped: feature mpg123 disabled
Dependency sndfile skipped: feature sndfile disabled
Dependency wavpack skipped: feature wavpack disabled
Library WildMidi skipped: feature wildmidi disabled
Library mp3lame found: YES
Dependency twolame skipped: feature twolame disabled
Dependency shine skipped: feature shine disabled
Dependency libmpdclient skipped: feature libmpdclient disabled
Configuring config.h using configuration
Program sphinx-build found: YES (/usr/libexec/python2-sphinx/sphinx-build)
Build targets in project: 50
Found ninja-1.8.2 at /usr/bin/ninja
+ ninja -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu'
[200/486] Compiling C++ object 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o'.
FAILED: src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o 
ccache c++ -Isrc/input/plugins/src@input@plugins@@input_plugins@sta -Isrc/input/plugins -I../src/input/plugins -Isrc -I../src -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -Wall -Wextra -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -D_GNU_SOURCE -m64 -march=core2 -mtune=core2 -fPIE -fuse-ld=gold -fuse-linker-plugin -Wa,--noexecstack -fPIC  -MD -MQ 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o' -MF 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o.d' -o 'src/input/plugins/src@input@plugins@@input_plugins@sta/FfmpegInputPlugin.cxx.o' -c ../src/input/plugins/FfmpegInputPlugin.cxx
../src/input/plugins/FfmpegInputPlugin.cxx:34:10: fatal error: libavformat/avio.h: No such file or directory
 #include <libavformat/avio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[205/486] Compiling C++ object 'src/input/src@input@@input_glue@sta/BufferedInputStream.cxx.o'.
ninja: build stopped: subcommand failed.
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.uvU4Zl (%build)
