### ISSUE TITLE
mpd 0.21 not buildable on FreeBSD

### ISSUE THREAD

**Issue by riggs-** [MusicPlayerDaemon/MPD#393]
It seems some assumptions regarding network-related data types do not apply:

c++ -Isrc/event/src@event@@event@sta -Isrc/event -I../src/event -Isrc -I../src -I. -I../ -I/usr/local/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Wall -Wextra -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -funwind-tables -D_GNU_SOURCE -O2 -fstack-protector -fno-strict-aliasing -fPIC  -MD -MQ 'src/event/src@event@@event@sta/ServerSocket.cxx.o' -MF 'src/event/src@event@@event@sta/ServerSocket.cxx.o.d' -o 'src/event/src@event@@event@sta/ServerSocket.cxx.o' -c ../src/event/ServerSocket.cxx
In file included from ../src/event/ServerSocket.cxx:22:
../src/net/IPv4Address.hxx:111:4: error: non-constant-expression cannot be narrowed from type 'uint16_t' (aka 'unsigned short') to 'sa_family_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
                        ToBE16(port),
                        ^~~~~~~~~~~~
../src/net/IPv4Address.hxx:111:4: note: insert an explicit cast to silence this issue
                        ToBE16(port),
                        ^~~~~~~~~~~~
                        static_cast<sa_family_t>( )
../src/net/IPv4Address.hxx:112:4: error: no viable conversion from 'struct in_addr' to 'in_port_t' (aka 'unsigned short')
                        address,
                        ^~~~~~~
../src/net/IPv4Address.hxx:114:3: warning: missing field 'sin_zero' initializer [-Wmissing-field-initializers]
                };
                ^
../src/net/IPv4Address.hxx:104:38: error: no return statement in constexpr function
        static constexpr struct sockaddr_in Construct(struct in_addr address,
                                            ^
../src/net/IPv4Address.hxx:123:20: error: no viable conversion from 'struct in_addr' to 'uint32_t' (aka 'unsigned int')
                return Construct(ConstructInAddr(address), port);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../src/net/IPv4Address.hxx:121:57: note: passing argument to parameter 'address' here
        static constexpr struct sockaddr_in Construct(uint32_t address,
                                                               ^
../src/net/IPv4Address.hxx:121:38: error: no return statement in constexpr function
        static constexpr struct sockaddr_in Construct(uint32_t address,
                                            ^
../src/net/IPv4Address.hxx:135:12: error: constexpr constructor must initialize all members
        constexpr IPv4Address(struct in_addr _address, uint16_t port) noexcept
                  ^
../src/net/IPv4Address.hxx:49:21: note: member not initialized by constructor
        struct sockaddr_in address;
                           ^
../src/net/IPv4Address.hxx:143:4: error: no matching constructor for initialization of 'IPv4Address'
                :IPv4Address(ConstructInAddr(a, b, c, d), port) {}
                 ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/net/IPv4Address.hxx:129:12: note: candidate constructor not viable: requires single argument '_address', but 2 arguments were provided
        constexpr IPv4Address(const struct sockaddr_in &_address) noexcept
                  ^
../src/net/IPv4Address.hxx:148:21: note: candidate constructor not viable: requires single argument 'port', but 2 arguments were provided
        constexpr explicit IPv4Address(uint16_t port) noexcept
                           ^
../src/net/IPv4Address.hxx:155:11: note: candidate constructor not viable: requires single argument 'src', but 2 arguments were provided
        explicit IPv4Address(SocketAddress src) noexcept;
                 ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class IPv4Address {
      ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../src/net/IPv4Address.hxx:127:2: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
        IPv4Address() = default;
        ^
../src/net/IPv4Address.hxx:141:12: note: candidate constructor not viable: requires 5 arguments, but 2 were provided
        constexpr IPv4Address(uint8_t a, uint8_t b, uint8_t c,
                  ^
../src/net/IPv4Address.hxx:141:12: error: constexpr constructor must initialize all members
        constexpr IPv4Address(uint8_t a, uint8_t b, uint8_t c,
                  ^
../src/net/IPv4Address.hxx:49:21: note: member not initialized by constructor
        struct sockaddr_in address;
                           ^
../src/net/IPv4Address.hxx:149:4: error: no matching constructor for initialization of 'IPv4Address'
                :IPv4Address(ConstructInAddr(INADDR_ANY), port) {}
                 ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/net/IPv4Address.hxx:129:12: note: candidate constructor not viable: requires single argument '_address', but 2 arguments were provided
        constexpr IPv4Address(const struct sockaddr_in &_address) noexcept
                  ^
../src/net/IPv4Address.hxx:148:21: note: candidate constructor not viable: requires single argument 'port', but 2 arguments were provided
        constexpr explicit IPv4Address(uint16_t port) noexcept
                           ^
../src/net/IPv4Address.hxx:155:11: note: candidate constructor not viable: requires single argument 'src', but 2 arguments were provided
        explicit IPv4Address(SocketAddress src) noexcept;
                 ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class IPv4Address {
      ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../src/net/IPv4Address.hxx:127:2: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
        IPv4Address() = default;
        ^
../src/net/IPv4Address.hxx:148:21: error: constexpr constructor must initialize all members
        constexpr explicit IPv4Address(uint16_t port) noexcept
                           ^
../src/net/IPv4Address.hxx:49:21: note: member not initialized by constructor
        struct sockaddr_in address;
                           ^
../src/net/IPv4Address.hxx:164:31: error: no return statement in constexpr function
        static constexpr IPv4Address MaskFromPrefix(unsigned prefix_length) noexcept {
                                     ^
../src/net/IPv4Address.hxx:231:10: error: no matching constructor for initialization of 'IPv4Address'
                return IPv4Address(ConstructInAddrBE(GetNumericAddressBE() & other.GetNumericAddressBE()),
                       ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/net/IPv4Address.hxx:129:12: note: candidate constructor not viable: requires single argument '_address', but 2 arguments were provided
        constexpr IPv4Address(const struct sockaddr_in &_address) noexcept
                  ^
../src/net/IPv4Address.hxx:155:11: note: candidate constructor not viable: requires single argument 'src', but 2 arguments were provided
        explicit IPv4Address(SocketAddress src) noexcept;
                 ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class IPv4Address {
      ^
../src/net/IPv4Address.hxx:48:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../src/net/IPv4Address.hxx:127:2: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
        IPv4Address() = default;
        ^
../src/net/IPv4Address.hxx:230:24: error: no return statement in constexpr function
        constexpr IPv4Address operator&(const IPv4Address &other) const noexcept {
                              ^
In file included from ../src/event/ServerSocket.cxx:23:
../src/net/IPv6Address.hxx:76:4: error: non-constant-expression cannot be narrowed from type 'uint16_t' (aka 'unsigned short') to 'sa_family_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
                        ToBE16(port),
                        ^~~~~~~~~~~~
../src/net/IPv6Address.hxx:76:4: note: insert an explicit cast to silence this issue
                        ToBE16(port),
                        ^~~~~~~~~~~~
                        static_cast<sa_family_t>( )
../src/net/IPv6Address.hxx:78:4: error: no viable conversion from 'struct in6_addr' to 'uint32_t' (aka 'unsigned int')
                        address,
                        ^~~~~~~
../src/net/IPv6Address.hxx:79:4: error: non-constant-expression cannot be narrowed from type 'uint32_t' (aka 'unsigned int') to 'uint8_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
                        scope_id,
                        ^~~~~~~~
../src/net/IPv6Address.hxx:79:4: note: insert an explicit cast to silence this issue
                        scope_id,
                        ^~~~~~~~
                        static_cast<uint8_t>( )
../src/net/IPv6Address.hxx:79:4: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                        scope_id,
                        ^~~~~~~~
                        {       }
../src/net/IPv6Address.hxx:79:4: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                        scope_id,
                        ^~~~~~~~
                        {       }
../src/net/IPv6Address.hxx:80:3: warning: missing field 'sin6_scope_id' initializer [-Wmissing-field-initializers]
                };
                ^
../src/net/IPv6Address.hxx:68:39: error: no return statement in constexpr function
        static constexpr struct sockaddr_in6 Construct(struct in6_addr address,
                                             ^
../src/net/IPv6Address.hxx:88:46: error: too few arguments to function call, expected 8, have 3
                :address(Construct(_address, port, scope_id)) {}
                         ~~~~~~~~~                         ^
../src/net/IPv6Address.hxx:52:2: note: 'Construct' declared here
        static constexpr struct in6_addr Construct(uint16_t a, uint16_t b,
        ^
../src/net/IPv6Address.hxx:86:12: error: constexpr constructor must initialize all members
        constexpr IPv6Address(struct in6_addr _address, uint16_t port,
                  ^
../src/net/IPv6Address.hxx:50:22: note: member not initialized by constructor
        struct sockaddr_in6 address;
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.

**Comment by MaxKellermann** [comment]
Is `HAVE_STRUCT_SOCKADDR_IN_SIN_LEN` defined in your `config.h`? If not, please check the Meson logs what happened to the test.

**Comment by riggs-** [comment]
This is from `config.h`:
```
#define HAVE_STRUCT_SOCKADDR_IN_SIN_LEN
#undef HAVE_STRUCT_UCRED
#define HAVE_TCP
```
During configure meson complains about not having SO_PEERCRED:
```Header <sys/socket.h> has symbol "AF_INET6": YES
Checking whether type "struct sockaddr_in" has member "sin_len" : YES
Header <sys/socket.h> has symbol "struct ucred": YES
Header <sys/socket.h> has symbol "SO_PEERCRED": NO
```

**Comment by MaxKellermann** [comment]
But does FreeBSD have `SO_PEERCRED`?

**Comment by riggs-** [comment]
No, it does not. I was just wondering whether it is required because it was the only red "NO" during configure.

**Comment by riggs-** [comment]
Ok, problem is this: `IPv6Address.hxx` contains this section, starting at line 72:
```
#if defined(__APPLE__)
                        sizeof(struct sockaddr_in6),
#endif
```
This is not Apple-specific, but applies to (at least) FreeBSD as well.
