### ISSUE TITLE
Failed to open ALSA device (alsa-lib 1.1.7, 96kHz and 192kHz file)

### ISSUE THREAD

**Issue by miblodelcarpio** [MusicPlayerDaemon/MPD#395]
Since I upgraded from alsa-lib 1.1.6 to 1.1.7, mpd (0.21) has stopped being able to play files with a sample rate of 96kHz or 192kHz, while it continues to be able to play 44.1kHz and 48kHz files.

Other programs (sox and mpv, although mpv apparently resamples to 48kHz) continue to handle the same 96kHz and 192kHz files that mpd is newly unable to handle, which sort of suggests to me that there may be something mpd could do differently to also handle the same files.

Here attached are my mpd.conf and verbose logs showing fresh runs of mpd started under alsa 1.1.6 and 1.1.7, trying to play a 96kHz file.

[mpd.conf.txt](https://github.com/MusicPlayerDaemon/MPD/files/2539797/mpd.conf.txt)
[log_alsa-1.1.6.txt](https://github.com/MusicPlayerDaemon/MPD/files/2539798/log_alsa-1.1.6.txt)
[log_alsa-1.1.7.txt](https://github.com/MusicPlayerDaemon/MPD/files/2539801/log_alsa-1.1.7.txt)

**Comment by MaxKellermann** [comment]
I currently cannot imagine how this is not an ALSA bug. The fact that other programs don't have the problem doesn't mean much, as they might use different calls to set up ALSA.
Please try configuring a "hw:" device in mpd.conf to get direct access to the hardware, e.g. `device "hw:0"`
Can you play other 24 bit files with ALSA 1.1.7? Try forcing MPD to play 16 bit (at 192/96 kHz) just to be sure if it's really the sample rate or the audio format. Within the `audio_output` section, add: `format "*:16:*"`

**Comment by MaxKellermann** [comment]
MPD uses `snd_pcm_hw_params_set_rate_near()` to set the sample rate. This chooses a matching sample rate from the list of sample rates supported by your device. So if this function succeeds, then `snd_pcm_hw_params()` must succeed as well. This is why I believe this is an ALSA bug.

**Comment by miblodelcarpio** [comment]
Cool, thanks @MaxKellermann. So are we straight on to reporting the bug to ALSA or would we be expected to gather more diagnostic stuff from MPD's side (e.g. a printout of `snd_pcm_hw_params_set_rate_near()`'s choice / the list of sample rates available to it)? If we're reporting, are you set up to do this via their devel mailing list?

**Comment by MaxKellermann** [comment]
Confirmed to be an alsa-lib bug: http://git.alsa-project.org/?p=alsa-lib.git;a=commit;h=b420056604f06117c967b65d43d01536c5ffcbc9
