### ISSUE TITLE
Filter: AND expressions...

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#399]
So I'm probably doing it wrong...but I could not find where I'm exactly wrong so please help me
`
mpc search --wait '(AudioFormat=="192000:24:2" AND Comment!="24/192 Mono")'`
`mpd error: ')' expected`

**Comment by MaxKellermann** [comment]
Every level needs parantheses because the parser is very dumb, e.g.:
`mpc search '((AudioFormat=="192000:24:2") AND (Comment!="24/192 Mono"))'`
btw. `--wait` doesn't make sense with `search`.

Anyway thanks for reporting this misunderstanding - I need to improve the documentation.

**Comment by roizcorp** [comment]
Thanks, I generally use `findadd` which `--wait` helps for but because I'm migrating my scrits to the new format I'm testing the queries first with `search`
