### ISSUE TITLE
mpd 0.21: meson: missing config option for tremor (libvorbisidec)

### ISSUE THREAD

**Issue by joerg-krause** [MusicPlayerDaemon/MPD#405]
Commit 94592c14062d5afc9482d11baa401648082022c0 dropped autotools in favour of meson build system. Unfortunately, support for the tremor (libvorbisidec) got lost by this change.

**Comment by MaxKellermann** [comment]
That was intentional, even though I did not document it. It looked like Tremor was mostly unmaintained (last release 1.0.2 was 16 years ago), and I had never heard of anybody using it. When it was developed, there were many low-end CPUs without FPU, but 6 years ago, even the very first Raspberry Pi had an FPU.
Do you believe Tremor support in MPD is still important?

**Comment by riggs-** [comment]
I wouldn't mind dropping it. Even the very low-end CPUs are fine decoding with the floating point libvorbis.

**Comment by joerg-krause** [comment]
tremor is still maintained, it received the last commit some month ago: http://git.xiph.org/?p=tremor.git.

There are still a lot of soft-floating CPUs around, so I would say, yes, it is still important for those CPUs. I am using an i.MX28-based board myself. This CPUs has a longevity until late 2020.

I don't agree, that it is decoding fine with libvorbis. It requires a lot more CPU usage, making it impossible to do other stuff, while decoding vorbis streams.

Furthermore, it doesn't cause any trouble to still keep it, right?

**Comment by MaxKellermann** [comment]
If there is a maintainer, the code will stay. Currently, there is none.
I'm already overloaded with work and too few people are helping with MPD/libmpdclient/mpc/ncmpc development, I didn't want to spend any time on bringing Tremor support to the new Meson build system. So anybody interested in Tremor support should become maintainer, do the Meson rules, and probably write a Travis-CI rule to do a Tremor-enabled build.

**Comment by joerg-krause** [comment]
I see, thanks! I will have a look and maybe give it a try...
