### ISSUE TITLE
Multiple use of "group" in list command broken

### ISSUE THREAD

**Issue by djselbeck** [MusicPlayerDaemon/MPD#408]
Since MPD 0.20.22 the repeatedly use of "group" within the list command is broken.

The command

`list album group musicbrainz_albumid` works as expected whereas

`list album group musicbrainz_albumid group albumartist` results in

> ACK [2@0] {list} not able to parse args

The protocol documentation states:

> Additional arguments may specify a filter. The group keyword may be used (repeatedly) to group the results by one or more tags.

So I think it is a valid use of the group feature

**Comment by fuchsmich** [comment]
Are you sure this bug didn't exist in version prior to 0.20.22?

**Comment by djselbeck** [comment]
Yes, 0.20.21 works correctly. 

Are there any news on this issue?

**Comment by amverweij** [comment]
I also came across this bug. From my testing it breaks several clients: 
- MPDroid is not able to list albums when browsing through the artists view
- M.A.L.P. is not able to list albums when browsing through the artists view
- Good old gmpc is not able to list albums when selecting an artist in the Artists Browser

So it seems that all Android clients are affected by this bug. On the other hand, Cantata and MPod still seem to work.

I can confirm that I have the bug with versions 0.21.4 and 0.21.9. Downgrading to 0.20.21 provides a solution.

**Comment by MaxKellermann** [comment]
@amverweij I can't reproduce those problems with gmpc and mpdroid. I didn't test malp.

**Comment by djselbeck** [comment]
It is also wrong, that MALP doesn't work. It will just not allow selection of albums based on MBID or AlbumArtist. 

However, I will try the commit with MALP and check if it fixes my problem ;) thanks

**Comment by djselbeck** [comment]
It looks like the command in principle works again, but the output order has changed.

With 0.20.21 it was e.g.:

> Album: Ägget
AlbumArtist: T.S.R.
MUSICBRAINZ_ALBUMID: 42a132ee-4577-4c01-8eb9-4e6c1213bf35
Album: Écailles de lune
AlbumArtist: Alcest
MUSICBRAINZ_ALBUMID: 33749b62-1fa9-4ab0-b1e2-8696e3386bae
Album: Équinoxe
AlbumArtist: Jean Michel Jarre
MUSICBRAINZ_ALBUMID: dc408bf4-2e60-4e37-bb92-acee40c22b56
Album: Ἀποκάλυψις
AlbumArtist: Chelsea Wolfe
MUSICBRAINZ_ALBUMID: 2400d15e-374c-4aa5-a34e-52674a84ec29
Album: ✝
AlbumArtist: Justice
MUSICBRAINZ_ALBUMID: e123a2d2-6f59-3937-a090-248109380220


and now with mpd 0.21.x it is:

> MUSICBRAINZ_ALBUMID: e123a2d2-6f59-3937-a090-248109380220
> AlbumArtist: Justice
> Album: ✝
MUSICBRAINZ_ALBUMID: e131d96a-68f2-483b-ba2b-6d77da25b8bc
AlbumArtist: Deep Purple
Album: The Battle Rages On...

**Comment by MaxKellermann** [comment]
The old implementation was completely wrong and did not make any sense. It is surprising that there never was a bug report. When I saw my mistake during 0.20.22 development, I was really horrified and was unable to explain my own code.
I have no idea what the 0.20.21 response means. Do you? What does MALP do with this crazy response?
With 0.21.11, it's easy: you want to see unique "album" values, grouped by "albumartist" and again by "musicbrainz_albumid". So what you get is on the top-most level a list of unique "musicbrainz_albumid" values, each containing unique "albumartist" values, and at the inner-most level, you see the unique "album" values within that group.

**Comment by djselbeck** [comment]
It was the only method I can think of (at the time being of 0.20) to request a list of albums with both albumartist and musicbrainz_albumid. Of course there should only be one item per ID for example. But still I as a developer of a client want to show the AlbumArtist and want to use the ID for internal selection.

It would all be superfluous if there was an easy way to get a list of albums with MBID and albumartist as tags.

**Comment by djselbeck** [comment]
Shouldn't the integration of the new behavior at least justify an increase of the protocol version in the 0.21.x branch?

**Comment by MaxKellermann** [comment]
True, f44011519c8c93af9e07e90130cf01f7f6b9fa2b increases the protocol version.
