### ISSUE TITLE
Throwing exceptions in methods declared __attribute__((pure)) leads to abort on (at least) FreeBSD

### ISSUE THREAD

**Issue by jonsiddle** [MusicPlayerDaemon/MPD#41]
MPD was recently changed to use C++ exceptions and I see aborts on FreeBSD. The simplest way to reproduce is to point at a music library directory with a single directory "foo" under which there's a single file "foo.mp3". Once MPD is running, move "foo" to "bar" and trigger an update. It will crash with an abort.

I tracked this down to the combination of `__attribute__((pure))` and the clang compiler which FreeBSD uses. I guess it's optimising away the exception handling. gcc seems to not make the same optimisation.

There may be other cases. I've just worked around by redefining `gcc_pure` (which MPD defines to apply the attribute) to no-op.

**Comment by riggs-** [comment]
Wow, this is interesting! Does this happen to solve the library update problem mentioned in https://forum.musicpd.org/viewtopic.php?f=7&t=4318#p6880 and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219048 ? Do you happen to have a patch we could test?

**Comment by riggs-** [comment]
Seems indeed to work!
Thanks for tracking down this one!

**Comment by jonsiddle** [comment]
Yes, that's exactly what I did. I didn't bother with a patch since it was such a simple change and I figured someone who knew the code might want to do it properly and keep the optimisation where exceptions weren't used or make it based on compiler. I'd be happy to have a go at a better fix if that would be helpful.

**Comment by MaxKellermann** [comment]
Huh, interesting find. The GCC documentation of `pure` leaves this part undefined - it does not mention whether "pure" functions are allowed to throw exceptions (which I interpreted as just another kind of "return value"), while clang appears to assume that a `pure` function is also `noexcept`.

**Comment by MaxKellermann** [comment]
I quickly wrote a clang plugin which shows me code locations that need to be fixed: https://gist.github.com/MaxKellermann/758ed94d66cc744fe163bee0f854352d

**Comment by jonsiddle** [comment]
Nice way to find them. I've applied the commit and can confirm it fixes the issue I was seeing.
