### ISSUE TITLE
MPD UPnP Database Plugin failed with Upmpdcli

### ISSUE THREAD

**Issue by marcbth** [MusicPlayerDaemon/MPD#421]
Hallo Max,

i install the newest mpd and Upmpdcli

the error is the same.

i see any UPnP server and i can play files from there but

no files on Upmpdcli server streaming plugin.
i see the directory from tidal (playlist, album, artist etc), when i try into a directory i have

no such file error in ncmpc or other clients.

in another software linn kazoo, mplayer its works great.

can you explain me, how can create a log file with the communication of mpd and Upmpdcli

many thanks

Marc

**Comment by MaxKellermann** [comment]
See https://forum.musicpd.org/viewtopic.php?f=7&p=10627 and https://github.com/MusicPlayerDaemon/MPD/issues/383
