### ISSUE TITLE
Support specifying icecast charset in extended m3u playlist

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#422]
Many CJK internet radio stations use non-unicode character set for icy title. Non-unicode characters break MPD clients.

I find it desirable to extend m3u further as follows.

```
#EXTM3U
#EXTINF:-1 icy-title-charset=shift-jis,FM Apple Wave
http://sdfsdfsdf.com/sdfsdf
#EXTINF:-1 icy-titlecharset=big5,FM Cat
http://fmcat.com/
#EXTINF:-1 icy-title-charset=cp949,FM SDFG
http://sdfg.com/radio
...
```

EPG programs use similar syntax for extra information.

**Comment by MaxKellermann** [comment]
What is this "similar syntax"? Please point me to a specification document.
The syntax you cited above, did you make this up, or is this something some other program is already using? This doesn't look like a good solution, because this limits its use to URLs contained in M3U.

**Comment by crocket** [comment]
I don't think there is a specification, but I found

* https://siptv.eu/howto/playlist.html
* https://forum.kodi.tv/showthread.php?tid=317399

Each station can use a different character encoding for icy title. That's why I thought it was appropriate to assign charset to each station.

Can you think of a better solution?

**Comment by crocket** [comment]
Do you prefer specifying icy title charset for playlist streams in database?

**Comment by MaxKellermann** [comment]
I don't know what that means, but we could (ab)use the fragment identifier to specify client-side parameters such as charsets (MPD being the client, telling MPD how to interpret the response).
Is there no existing standard for this? How do other players solve this problem?

**Comment by crocket** [comment]
It means saving something like this in database.

```
[Radio.m3u/stream.1.url]
icy-title-charset=shift-jis

[Radio.m3u/stream.2.url]
icy-title-charset=shift-jis
```

I couldn't find any standard for this. `pyradio` solved this problem by having its own playlist format that specifies charset.

I think it's just better to start with a minimalistic dog shed and upgrade to a proper standard later.
If you chose a minimal solution now, you could ditch it easily later.

**Comment by crocket** [comment]
Closing this because `#charset=xxx` solves this issue.
