### ISSUE TITLE
R128_TRACK_GAIN tag in .opus files is ignored

### ISSUE THREAD

**Issue by username-password** [MusicPlayerDaemon/MPD#427]
OGG/OPUS Files tagged with r128gain to provide loudness information are treated by MPD as if loudness information was missing. When I check the files with gst-discoverer-1.0 I can see that they have a "R128_TRACK_GAIN" tag in the "extended comment" section, but MPD only applies the default loudness based on the "replaygain_missing_preamp" setting instead of the using the tag as loudness information.

**Comment by MaxKellermann** [comment]
This bug report is so devoid of information that I have no choice but to close it without any investigations.
If you want this to be reopened, follow https://www.musicpd.org/help/
