### ISSUE TITLE
Wrong timestamp for 1 track per album

### ISSUE THREAD

**Issue by quimup** [MusicPlayerDaemon/MPD#429]
I have noticed that when I sort albums by the timestamp (retrieved from MPD) some albums get a wrong timestamp. These are always single-track albums (i.e. 1 audio file in the directory). Since I get the timestamp for the album from the first song that matches both the album and the artist I assume that one song per album is always given a wrong timestamp. Without exception the wrong timestamp also shows up (correctly) for another album in the list.

regards,

JS

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by quimup** [comment]
Sorry: Currently using 0.20.23 from Debian (testing).

JS

**Comment by MaxKellermann** [comment]
Will reopen as soon as you've posted all the information.

**Comment by quimup** [comment]
On Wednesday, November 28, 2018 2:16:52 PM CET Max Kellermann wrote:
> Will reopen as soon as you've posted all the information.

You can't be bothered to say what "all the information" is?

-- 
Johan Spee
    "Eve Ryth in Gisgon na Beal Right"

**Comment by MaxKellermann** [comment]
You can't be bothered to read the link I posted?

**Comment by quimup** [comment]
I finally managed to work around this. It may or may not be an MPD bug. Have a look at the code below and make your ow decision:

I have a 'single-track' album named ""Peace Time" and ran the following code:

    struct mpd_song *song;
    mpd_send_list_all_meta(conn, "/");
    while ((song = mpd_recv_song (conn)))
    {
        if (mpd_song_get_tag (song, MPD_TAG_ALBUM, 0) != nullptr )
            newalbum = QString::fromUtf8(mpd_song_get_tag (song, MPD_TAG_ALBUM, 0));
        else
            newalbum = "";

        if (newalbum.contains("Peace Time"))
        {
            QDateTime dtime;
            dtime.setTime_t(static_cast<uint>(mpd_song_get_last_modified(song)));
            printf ("album: %s\n", newalbum.toUtf8().constData() );
            printf ("Timestamp: %s\n", (dtime.toString("yy/MM/dd  hh:mm")).toUtf8().constData());
        }
        mpd_song_free (song);
    }
    mpd_response_finish (conn);

    mpd_search_db_songs(conn, false);
    mpd_search_add_tag_constraint (conn, MPD_OPERATOR_DEFAULT, MPD_TAG_ALBUM, "");
    mpd_search_commit(conn);
    while ((song = mpd_recv_song (conn)))
    {
        if (mpd_song_get_tag (song, MPD_TAG_ALBUM, 0) != nullptr )
            newalbum = QString::fromUtf8(mpd_song_get_tag (song, MPD_TAG_ALBUM, 0));
        else
            newalbum = "";

        if (newalbum.contains("Peace Time"))
        {
            QDateTime dtime;
            dtime.setTime_t(static_cast<uint>(mpd_song_get_last_modified(song)));
            printf ("album: %s\n", newalbum.toUtf8().constData() );
            printf ("Timestamp: %s\n", (dtime.toString("yy/MM/dd  hh:mm")).toUtf8().constData());
        }
        mpd_song_free (song);
    }
    mpd_response_finish (conn);


The above results in this output:

    album: Peace Time
    Timestamp: 12/11/11  22:55
    album: Peace Time
    Timestamp: 10/05/01  10:22

The first method (mpd_send_list_all_meta) gets it wrong!

But the second method (mpd_search_commit) gets it right, so my problem is solved (although I do not understand what was wrong).

cheers,
JS

**Comment by MaxKellermann** [comment]
Downloading the whole database into the client is not a supported operation, and your kludge to emulate this using the "search" command isn't supported either. Just don't do that. Please refactor your client to do database requests properly, on demand, with small result sets.

**Comment by quimup** [comment]
On Wednesday, November 28, 2018 8:17:58 PM CET Max Kellermann wrote:
> Please refactor your client to do database
> requests properly, on demand, with small result sets.

I am a copy&paste programmer with no formal training and limited intelligence. 
I would appreciate a hint on how to get a list of all the albums in the 
database 'properly'.

Thanks,

JS


-- 
Johan Spee
    "Eve Ryth in Gisgon na Beal Right"

**Comment by MaxKellermann** [comment]
`list album`
https://www.musicpd.org/doc/html/protocol.html#the-music-database
