### ISSUE TITLE
rtio thread consumes 100 percent of a cpu core streaming to Bluetooth through bluez-alsa

### ISSUE THREAD

**Issue by TheOldPresbyope** [MusicPlayerDaemon/MPD#432]
**System under test**: RPi3B+ with internal Bluetooth controller enabled and external USB DAC connected. This RPi has 4 CPU cores.

**Software**: 

- 2018-11-13-raspbian-stretch-lite
-bluez 5.49
-bluez-alsa 1.2.0
-mpd 0.21.4 (v0.21.3-12-g9c5790ab1)

**Tests**:

1. Stream Internet radio station through mpd to USB DAC. Works and CPU utilization is low as expected.

```
$ top -H -u mpd

top - 10:10:14 up 21:48,  2 users,  load average: 0.88, 1.28, 1.15
Threads: 142 total,   1 running,  96 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.7 us,  0.0 sy,  0.0 ni, 99.0 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  4.6 us,  1.6 sy,  0.0 ni, 93.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  6.1 us,  0.6 sy,  0.0 ni, 93.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.7 us,  1.0 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   949448 total,   601180 free,    70652 used,   277616 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   746604 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND      
30302 mpd       10 -10  145900  25192  17664 S  4.3  2.7   0:01.60 decoder:faad 
30304 mpd      -51 -10  145900  25192  17664 S  3.6  2.7   0:00.88 output:ALSA+ 
30201 mpd       10 -10  145900  25192  17664 S  0.0  2.7   0:00.23 mpd          
30227 mpd       10 -10  145900  25192  17664 S  0.0  2.7   0:00.04 io           
30228 mpd      -51 -10  145900  25192  17664 S  0.0  2.7   0:00.01 rtio         
30301 mpd       10 -10  145900  25192  17664 S  0.0  2.7   0:00.00 player       
```

2. Stream same Internet radio station through mpd to Bluetooth speaker via bluez-alsa/bluez. Works but rtio thread saturates one CPU core.

```
$ top -H -u mpd

top - 10:07:44 up 21:46,  2 users,  load average: 1.30, 1.34, 1.12
Threads: 144 total,   2 running, 100 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.0 us,  1.0 sy,  0.0 ni, 97.6 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 80.5 us, 19.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.3 us,  0.7 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  5.4 us,  0.3 sy,  0.0 ni, 94.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   949448 total,   601392 free,    70432 used,   277624 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   746788 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND      
23699 mpd      -51 -10  155428  25864  17748 R 99.7  2.7  25:19.10 rtio         
23980 mpd       10 -10  155428  25864  17748 S  4.3  2.7   0:45.65 decoder:faad 
23982 mpd      -51 -10  155428  25864  17748 S  0.3  2.7   0:02.78 output:ALSA+ 
23661 mpd       10 -10  155428  25864  17748 S  0.0  2.7   0:00.27 mpd          
23698 mpd       10 -10  155428  25864  17748 S  0.0  2.7   0:02.18 io           
23979 mpd       10 -10  155428  25864  17748 S  0.0  2.7   0:00.29 player       
26886 mpd       20   0  155428  25864  17748 S  0.0  2.7   0:00.68 pcm-io       
```

**Comments**: 

- When I previously used mpd 0.20.20 with the same hardware and Bluetooth subsystem I saw low CPU utilizations similar to the result in test 1 above; there was, of course, no rtio thread present.

- Clearly this issue relates to the now closed #425. 
---

```
 $ cat mpd.conf
music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"
log_file "/var/log/mpd/log"
pid_file "/var/run/mpd/pid"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
restore_paused "yes"
auto_update "no"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
zeroconf_enabled "no"
zeroconf_name "Moode44g1 MPD"
gapless_mp3_playback "yes"
replaygain "off"
volume_normalization "no"
audio_buffer_size "4096"
buffer_before_play "10%"
max_output_buffer_size "81920"
id3v1_encoding "UTF-8"
filesystem_charset "UTF-8"
max_connections "128"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

resampler {
plugin "soxr"
quality "very high"
threads "1"
}

audio_output {
type "alsa"
name "ALSA default"
device "hw:0,0"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA crossfeed"
device "crossfeed"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA parametric eq"
device "eqfa4p"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA graphic eq"
device "alsaequal"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA bluetooth"
device "btstream"
mixer_type "software"
}
```

**Comment by MaxKellermann** [comment]
Post a `perf report` and a brief `strace` of that thread.

**Comment by MaxKellermann** [comment]
Maybe essential, maybe not. At this point, I have no idea what could be causing high CPU usage, and only `perf report` will tell me where the CPU is wasted. The strace won't, because strace doesn't show CPU usage at all - though it may help guessing.
What makes you so sure that your linux-perf version doesn't work? Did you try?

**Comment by MaxKellermann** [comment]
Please test with commit 9c5790ab1d9bd597bebae4eed7581a97788fc4a8 - I think this could be a bluez-alsa bug, or maybe an alsa-lib documentation bug.

**Comment by MaxKellermann** [comment]
Sorry that should have been commit 5cb603983e2e20f1d2f9f638be55e945c90bd6b4

**Comment by TheOldPresbyope** [comment]
Yes, test with 5cb6039 throws exception

From mpd log

`Dec 05 08:13 : exception: Failed to play on "ALSA bluetooth" (alsa): snd_pcm_poll_descriptors_revents() failed: Invalid argument
Dec 05 08:13 : exception: Failed to open audio output
`

**Comment by MaxKellermann** [comment]
bluez-alsa bug then. Please report to bluez-alsa.

If bluez-alsa developers believe they error handling is correct, then this should be forwarded to alsa-lib to amend their API documentation. After the alsa-lib API documentation has been clarified, we can open this one and adjust MPD's implementation.

**Comment by TheOldPresbyope** [comment]
Thank you.

**Comment by Arkq** [comment]
Hi @MaxKellermann 

I've made assumption about the `snd_pcm_poll_descriptors_revents()` function based on the pulseaudio plugin, which is in the official ALSA git repository: http://git.alsa-project.org/?p=alsa-plugins.git;a=blob;f=pulse/pcm_pulse.c;h=283174357e8b2aa55076fd784c97aebb8b1b2bde;hb=HEAD#l627 Base on this code, poll_revents() function clearly can fail without setting `*revents` (which might be a bug).

Or maybe there is something else wrong with this function (bluez-alsa implementation of it)?

Also, I've got one question. Why in the `AlsaNonBlockPcm::DispatchSockets` function, the `snd_pcm_poll_descriptors_revents()` is called, but the returned value in the revents is discarded? https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga7e561f305702c6f52dab49b6c84f7df7 states, that the null event also exists. If the actual event value is of no interest to you, why even calling `snd_pcm_poll_descriptors_revents()`?

**Comment by MaxKellermann** [comment]
@Arkq:

`snd_pcm_poll_descriptors_revents()` is called not because MPD is interested in the return value, but because calling it is required by alsa-lib, see https://github.com/MusicPlayerDaemon/MPD/issues/391#issuecomment-436948394

bluez-alsa's implementation makes assumptions on the number and order of poll descriptors - it assumes it will get the exact same buffer which was previously passed to `snd_pcm_poll_descriptors()`. But the alsa-lib API documentation does not document that applications must do that, therefore I must assume that bluez-alsa's assumption is wrong and this is a bug in bluez-alsa.
But I'm not 100% sure - maybe alsa-lib developers just forgot to document this requirement, or maybe I missed something in the documentation. If somebody explains that I'm wrong, I'd be happy to correct MPD. Or if alsa-lib documentation gets amended, I will change MPD to obey this new requirement.

**Comment by TheOldPresbyope** [comment]
Below is link to case made by @Arkq for his particular approach in bluez-alsa which is based on the approach used by PCM plug-in’s in the alsa-plugins repository and the official AAF PCM plug-in.

https://github.com/Arkq/bluez-alsa/issues/174#issuecomment-455110132

**Comment by MaxKellermann** [comment]
His argument is "it makes more sense to pass the same buffer", but this is not about what makes sense, but what is documented in ALSA's API contract. MPD obeys the contract, but bluez-alsa does not. From this I can only deduce that this is a bluez-alsa bug.

Of course, it is unfortunate that ALSA's own example code makes those undocumented assumptions. This is also a bug! But this could also be a hint that this might be a bug in the ALSA API documentation instead, that the ALSA developers thought this should be true, but forgot to document it. We don't know.

We can only talk about the documented API, and we should not speculate about its hidden intent. MPD will follow the documented API, and bluez-alsa should do as well.
I repeat: "if alsa-lib documentation gets amended, I will change MPD to obey this new requirement". Until then, no action is required on MPD's side.

**Comment by arkq** [comment]
I'm not sure whether this issue is still the case for MPD but in the latest release of ALSA lib (1.2.11) the doc has been fixed/updated:
https://github.com/alsa-project/alsa-lib/blob/v1.2.11/src/pcm/pcm.c#L1855

So, now it's clearly stated that the order of poll file descriptors must not change.

Related commits (for better diff):
https://github.com/alsa-project/alsa-lib/commit/cd04da2bcfe147b08b8db2930b2294aead0a8968
https://github.com/alsa-project/alsa-lib/commit/d4992c36cc962bd2b3cef7158af173a95177ba2e
