### ISSUE TITLE
Installation of man page and example config

### ISSUE THREAD

**Issue by 0-wiz-0** [MusicPlayerDaemon/MPD#436]
After the switch to meson, the following files are not installed any longer:
`mpd.1`, `mpd.conf.5`, and `mpdconf.example`.
Please install them again. Thanks.

**Comment by MaxKellermann** [comment]
Paste the output of `meson configure|grep documentation` (from inside your output directory).

**Comment by 0-wiz-0** [comment]
That gives me
````
  documentation           false         [true, false]                    Build documentation
````
How can I change that?
Can the default be changed to `true`, or is this an indicator of a missing dependency?

Even set to `false`, this still installs
````
share/doc/mpd/AUTHORS
share/doc/mpd/COPYING
share/doc/mpd/NEWS
share/doc/mpd/README.md
````

**Comment by MaxKellermann** [comment]
By passing `-Ddocumentation=true` to Meson.

**Comment by 0-wiz-0** [comment]
Thank you, that installed the man pages and the sphinx-generated docs.
The example config is not installed that way, but I'll just do that manually.
