### ISSUE TITLE
Error message not formated as documented

### ISSUE THREAD

**Issue by The-Michael-R** [MusicPlayerDaemon/MPD#443]
In case the Audio-HW is busy the MPD (protocol version 0.21.0) responds with:
`error: Failed to open "Hifiberry" (alsa); Failed to open ALSA device "hw:0,0": Device or resource busy`
Expected something like:
`ACK [52@0] {play} Failed to open "Hifiberry" (alsa); Failed to open ALSA device "hw:0,0": Device or resource busy`

Either the [Documentation](https://www.musicpd.org/doc/html/protocol.html#failure-responses) should have this added  as valid response to the protocol or the message should be aligned to the format described format.

From my side that has very low priority. As my code ignores unexpected responses.

**Comment by MaxKellermann** [comment]
I believe this bug report is bogus, but since your bug report omits vital information (there's not even a MPD version number, wtf!), I can't explain why.
If you want an explanation (or prove my educated guess wrong), paste the conversation with MPD.

**Comment by The-Michael-R** [comment]
I included the protocol version as I expected that the problem is a protocol issue. It seems that I was wrong. I'm sorry about that. And it turned out that it can be reproduced 100% but it's a bit trickier than I initially thought.
```
$ mpd --version
Music Player Daemon 0.21.3 (0.21.3)
```

### System
Raspberry Pi 2B
HifiBerry DAC+
ArchLinux all updates installed
Audio system: ALSA

### MPD configuration
```$ cat /etc/mpd.conf
zeroconf_name		"MPD at Raspberry Pi"

music_directory		"/usr/local/music"
playlist_directory	"/var/lib/mpd/playlists"
pid_file                "/run/mpd/mpd.pid"
db_file                 "/var/lib/mpd/mpd.db"
state_file              "/var/lib/mpd/mpdstate"
#log_file		"/var/log/mpd.log"

bind_to_address		"127.0.0.1"
bind_to_address		"192.168.178.210"

auto_update_depth	"3"

user 			"mpd"

audio_output {
	name 		"Hifiberry"
        type            "alsa"
        device          "hw:0,0"
        mixer_type      "hardware"
        mixer_control   "DIGITAL"
        mixer_device    "hw:0"
        mixer_index     "0"
        auto_resample   "no"
        auto_format     "no"
        enabled         "yes"
}
```
### How to reproduce
Start mpd with a queue of titles but not play anything yet
Occupy the soundcard with other tool (e.g. ffplay)
Connect using nc and send the following command-list (important to have play and status issued in the list):
```
$ nc 192.168.178.210 6600
OK MPD 0.21.0
command_list_ok_begin
play 2
status
command_list_end
list_OK
volume: 19
repeat: 0
random: 0
single: 0
consume: 0
playlist: 73
playlistlength: 62
mixrampdb: 0.000000
state: pause
song: 2
songid: 3
time: 0:0
elapsed: 0.000
bitrate: 0
audio: 44100:24:2
error: Failed to open "Hifiberry" (alsa); Failed to open ALSA device "hw:0,0": Device or resource busy
nextsong: 3
nextsongid: 4
list_OK
OK
```

**Comment by The-Michael-R** [comment]
I just noticed that the protocol actually notes a possible error: message. This issue can stay closed as this is a user error:
```
error: if there is an error, returns message here
```

I'm sorry for the hassle.
