### ISSUE TITLE
Android: required permission Read_External_Storage

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#445]
Hi,

Due to large volume, my music on the phone is split between external sdcard and the internal card. MPD is able only to see the files in the internal.

I assume the reason is that Android requires user to allow access to external storage manually but I'm not too sure though

**Comment by MaxKellermann** [comment]
Already used: https://github.com/MusicPlayerDaemon/MPD/blob/master/android/AndroidManifest.xml#L10
