### ISSUE TITLE
`idle` takes a long time to get ACK

### ISSUE THREAD

**Issue by cykerway** [MusicPlayerDaemon/MPD#446]
I was trying to figure out which subsystems changed between two successive mpd server queries. But I noticed there is a tens of milliseconds delay after `idle` is sent and the server ACK it (Yes I mean the TCP ACK packet), when I write it this way:

    sock.send(b'idle\n')
    sock.send(b'noidle\n')

This is actually a lot of time for an interactive client. My current fix is to write it this way instead:

    sock.send(b'idle\nnoidle\n')

This is almost 1000x faster. Problem is:

-   I don't know if this always works as intended, or merely a coincidence.

-  This is not included in the API library so some ugly hack is needed.

Hopefully you can fix this timing issue, or at least explain what is happening with it.

**Comment by cykerway** [comment]
A simple test:

    #!/usr/bin/env python3
    
    import time, socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('localhost', 6600)); sock.recv(1024)
    t0 = time.time()
    for i in range(50):
        sock.send(b'idle\n')
        sock.send(b'noidle\n')
    #    sock.send(b'idle\nnoidle\n')
        sock.recv(1024)
    t1 = time.time()
    print(t1 - t0)

**Comment by MaxKellermann** [comment]
Convince me that this has anything to do with MPD.
MPD has no code to generate TCP ACKs. Your kernel has.

**Comment by cykerway** [comment]
True. The network stack is in kernel. But it's MPD commanding the kernel to send the reply. I haven't done an in-depth test yet but it looks like somewhere in the code MPD is waiting or has set a timeout which seems too large. It's probably helpful if you test the above code and reply how long it takes. If sending `idle` and `noidle` separately takes the same time as sending them together, I'll debug my kernel.

**Comment by MaxKellermann** [comment]
> But it's MPD commanding the kernel to send the reply.

Not true (in this context). MPD doesn't command the kernel to send a TCP ACK. The kernel decides on its own about TCP ACKs.

**Comment by MaxKellermann** [comment]
..... aaaand a TCP ACK isn't even necessary to send a second PSH packet, unless the window is exceeded. It is extremely unlikely that the window is exceeded by a 5 byte payload.

**Comment by cykerway** [comment]
> > But it's MPD commanding the kernel to send the reply.
> 
> Not true (in this context). MPD doesn't command the kernel to send a TCP ACK. The kernel decides on its own about TCP ACKs.

Ultimately it's MPD telling the kernel to send something.

Anyway, let's give it a run first? Simply toggle 3 lines of comments. If you wish you can write the test in another language. I'm interested in your results.

**Comment by MaxKellermann** [comment]
> Ultimately it's MPD telling the kernel to send something.

Once you tell me how MPD tells the kernel to send a TCP ACK, I'll reopen this issue.
Until then, I believe it is bogus and I'll not bother spending time on reproducing your results.

**Comment by cykerway** [comment]
After some debugging, I think now I can almost confirm this is the classic write-write-read problem where Nagle's algorithm and delayed ACK algorithm play badly together. So the problem is real. I think either the client needs TCP_NODELAY or the server needs TCP_QUICKACK. Unfortunately I have control of neither! All right I will leave this up to you to decide if providing a TCP_QUICKACK is worthwhile. Otherwise I probably need to beg the client library author, or maybe, keep hacking with `idle\nnoidle\n`.
