### ISSUE TITLE
radio stream problem

### ISSUE THREAD

**Issue by victor910** [MusicPlayerDaemon/MPD#448]
Hi  everyone,

I have a problem with playing internet stream under MPD.
For example, I have two address streams,

https://somafm.com/groovesalad256.pls
http://www.prosto.fm/files/Prosto128.m3u

Both address playing under any OS if I use any type of browsers.

When I try to play the first stream under MPD, I have no error, MPD is
playing without any problem.

But the second link does not play at all.
I have this error in MPD log file:

Jan 03 17:24 : client: process command "playid "18""
Jan 03 17:24 : playlist: play 17:"http://62.80.190.246:8000/PRK128"
Jan 03 17:24 : exception: Failed to decode http://62.80.190.246:8000/PRK128
Jan 03 17:24 : exception: nested: CURL failed: Operation timed out
after 10009 milliseconds with 0 out of 0 bytes received
Jan 03 17:24 : player: played "http://62.80.190.246:8000/PRK128"
Jan 03 17:24 : exception: Failed to decode http://62.80.190.246:8000/PRK128
Jan 03 17:24 : exception: nested: CURL failed: Operation timed out
after 10009 milliseconds with 0 out of 0 bytes received
Jan 03 17:24 : client: command returned 2

I have a problem with playing another internet stream under MPD as
well, this "problem" link only for example.

This problem present for me more than 1 year, before everything was fine.
I have used different version MPD, no one version help me.
Right now I have used Debian with last version MPD 0.21.3
curl 7.62.0, Linux 4.9.30 

I have to try "problem" links from this topic https://forum.musicpd.org/viewtopic.php?f=7&t=7315 and as well have the problem.
But you will say, try to update this will fixed problem, but look, he updated to 0.20.12, not to the last version. 
I have skip 0.20.x and jump in from 0.19.X to 0.21.X.
Anyway, right now I have the last version, 0.21.3.

**Comment by MaxKellermann** [comment]
This works very well for me. Can you do `curl -o /dev/null http://62.80.190.246:8000/PRK128`

**Comment by victor910** [comment]
this working very for me as well:
curl -o /dev/null http://62.80.190.246:8000/PRK128
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2634k    0 2634k    0     0  16333      0 --:--:--  0:02:45 --:--:-- 15841

But not working under MPD.

**Comment by miccoli** [comment]
just for reference: http://www.prosto.fm/files/Prosto128.m3u works for me

**Comment by victor910** [comment]
I have a proposal, this problem for me present for more than 1 year.
I am ready to compile source code MPD on my system with "super MEGA incredible" parameters for debugging.
after this I will provide all detailed logs to this thread, maybe after this, we will found the problem?
what parameters I must use for compiling for enable very detailed logs???

**Comment by MaxKellermann** [comment]
Configure MPD with `-Dtest=true` and build the program `run_input`. Then run this program:
> strace -tttTfo /tmp/trace run_input http://...

Upload the file `/tmp/trace` and let me inspect it.

**Comment by MaxKellermann** [comment]
Will reopen as soon as I have your data.

**Comment by mikepierce** [comment]
I'm having a similar issue. After trying to play [this stream](http://radio.stereoscenic.com/am-s.mp3) I get the error:

    Sep 29 23:55 : exception: Failed to decode http://radio.stereoscenic.com:80/am-s.mp3
    Sep 29 23:55 : exception: nested: CURL failed: Resolving timed out after 10009 milliseconds
    Sep 29 23:55 : player: played "http://radio.stereoscenic.com:80/am-s.mp3"  

Trying all the streams I have saved, it looks like **MPD will only play streams listed as IP-ADDRESS:PORT but not the ones that use a typical URL**. So like, it won't play anything like  [http://radio.stereoscenic.com:80/am-s.mp3](http://radio.stereoscenic.com:80/am-s.mp3) but it will play [http://198.27.120.235:8850](http://198.27.120.235:8850).

---

The version of MPD I have installed is 0.20.18. This is not an issue in version 0.19.12. Aside issue I tried to compile the latest MPD from source as [instructed here](https://www.musicpd.org/doc/html/user.html) to see if this is still an issue, but ran into issues just doing that.

     meson_options.txt:5:0: ERROR: Unknown type feature.  

If you want me to try this on the latest MPD, I'll need to be instructed how to get past that.

**Comment by miccoli** [comment]
@mikepierce : the OP reported
```
exception: nested: CURL failed: Operation timed out after 10009 milliseconds with 0 out of 0 bytes received
```
while you are experiencing 
```
exception: nested: CURL failed: Resolving timed out after 10009 milliseconds
```
which is a totally different problem, linked to DNS resolution. This thread is not the appropriate place to discuss your problem.

**Comment by mikepierce** [comment]
@miccoli AH! You're right. Sorry about that. I'll start a new bug report.
