### ISSUE TITLE
Fail to play some wav files from an http server using BufferedInputStream

### ISSUE THREAD

**Issue by netsuso** [MusicPlayerDaemon/MPD#453]
I've found that playing wav files from an http server fails if managed through BufferedInputStream.

I know it because it works for files >128 MB (which are not eligible for BufferedInputStream) but fails for smaller files (which are eligible). Also, I've tried recompiling mpd setting MAX_SIZE to 0 in BufferedInputStream.hxx (so no files are eligible) and then all wav files work perfectly.

On the 0.21.4 package in Arch Linux it crashes with this error:
`mpd: ../src/util/SparseBuffer.cxx:36: SparseMap::CheckResult SparseMap::Check(SparseMap::size_type)` const: Assertion `offset < GetEndOffset()' failed.`

On the version compiled by myself it doesn't crash and it keeps working, but it's not capable of playing any of those <128 MB wav files (they get stuck at the beginning).

I can keep testing if required, but please point me to where to look, as this seems some interaction between the wav file support and the buffered input stream, as other files (flac, mp3...) work independently of their size.

**Comment by FeroSu** [comment]
I had the same problem after upgrade to version 0.21.4
> On the 0.21.4 package in Arch Linux it crashes with this error:
mpd: ../src/util/SparseBuffer.cxx:36: SparseMap::CheckResult SparseMap::Check(SparseMap::size_type) const: Assertion offset < GetEndOffset()' 
> 

Now, after upgrading to version 0.21.5 I have exactly this behavior:
> It doesn't crash and it keeps working, but it's not capable of playing any of those <128 MB wav files (they get stuck at the beginning).
>
