### ISSUE TITLE
Mistake in Manual - which vers. Boost?

### ISSUE THREAD

**Issue by MPconta** [MusicPlayerDaemon/MPD#461]
The User's Manual tells me, that i have to use libboost vers. 1.58 to compile MPD.
This version is very old. Do you mean 1.68?

In the Ubuntu-packages i have vers. 1.67. This does not work well - is this correct?

**Comment by MaxKellermann** [comment]
The versions are minimum versions. You can always use newer versions.
Though Boost 1.67 is known to be buggy.
But please, never write "does not work well" - if you have a problem, report it with all details.

**Comment by MPconta** [comment]
Short question for clarification:

Is it possible to compile MPD with libboost 1.65, libboost 1.66 or even libboost 1.58?

**Comment by MaxKellermann** [comment]
Yes.
