### ISSUE TITLE
albumart request with 0 offset hangs server

### ISSUE THREAD

**Issue by chowbok** [MusicPlayerDaemon/MPD#462]
Running mpd v0.21.4-14-g37debed0b. This request works fine:

`albumart "Artists/B/Beatles/1965 - Rubber Soul/" 1`

This request completely hangs mpd and it has to be given a SIGKILL:

`albumart "Artists/B/Beatles/1965 - Rubber Soul/" 0`

**Comment by MaxKellermann** [comment]
Paste a backtrace of the main thread when MPD hangs.

**Comment by MaxKellermann** [comment]
@tokyovigilante a bug report for you

**Comment by chowbok** [comment]
Hopefully I did this right:
[backtrace.txt](https://github.com/MusicPlayerDaemon/MPD/files/2780435/backtrace.txt)

**Comment by MaxKellermann** [comment]
It hangs in libnfs. Which libnfs version are you using?

**Comment by MaxKellermann** [comment]
And please paste the backtrace of all threads (`thread apply all bt`). There might be more interesting information in the I/O thread.

**Comment by chowbok** [comment]
[thread-all-bt.txt](https://github.com/MusicPlayerDaemon/MPD/files/2780461/thread-all-bt.txt)

Here you go. This is with libnfs 3.0.0.

**Comment by MaxKellermann** [comment]
@tokyovigilante in your implementation, you forgot to lock the mutex prior to calling `InputStream` methods, causing a deadlock.

**Comment by tokyovigilante** [comment]
Thanks for the spot and fix.


On Tue, 22 Jan 2019, at 8:18 AM, Max Kellermann wrote:
> @tokyovigilante[1] in your implementation, you forgot to lock the
> mutex prior to calling InputStream methods, causing a deadlock.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/tokyovigilante
  2. https://github.com/MusicPlayerDaemon/MPD/issues/462#issuecomment-456201426
