### ISSUE TITLE
kernel messages when starting new songs

### ISSUE THREAD

**Issue by seniorgod** [MusicPlayerDaemon/MPD#468]
Dear all,

i compiled 0.21.4 on SBC allo Sparky on Debian stretch 
everything work fine 
Today i figure out, that i get strange kernel messages every time a new song starts playing:

Jan 27 10:31:32 DietPi kernel: Received Data is: : dump of 68 bytes of data at 0xe0a40000
Jan 27 10:31:32 DietPi kernel: [68B blob data]
Jan 27 10:31:32 DietPi kernel:  00000008 00000003 00000000 00000047 . . . . . . . . . . . . G . . .
Jan 27 10:31:32 DietPi kernel: [68B blob data]
Jan 27 10:31:32 DietPi kernel:  00000000 00000000 00000000 00000000 . . . . . . . . . . . . . . . .
Jan 27 10:31:32 DietPi kernel:  00000000 . . . .
Jan 27 10:35:07 DietPi kernel: Received Data is: : dump of 68 bytes of data at 0xc2360000
Jan 27 10:35:07 DietPi kernel: [68B blob data]
Jan 27 10:35:07 DietPi kernel:  00000008 00000003 00000000 00000084 . . . . . . . . . . . . . . . .
Jan 27 10:35:07 DietPi kernel: [68B blob data]
Jan 27 10:35:07 DietPi kernel:  00000000 00000000 00000000 00000000 . . . . . . . . . . . . . . . .
Jan 27 10:35:07 DietPi kernel:  00000000 . . . .
Jan 27 10:38:08 DietPi kernel: Received Data is: : dump of 68 bytes of data at 0xdf0b0000
Jan 27 10:38:08 DietPi kernel: [68B blob data]
Jan 27 10:38:08 DietPi kernel:  00000008 00000003 00000000 0000003d . . . . . . . . . . . . = . . .
Jan 27 10:38:08 DietPi kernel: [68B blob data]
Jan 27 10:38:08 DietPi kernel:  00000000 00000000 00000000 00000000 . . . . . . . . . . . . . . . .
Jan 27 10:38:08 DietPi kernel:  00000000 . . . .

Any idea what that means?
Before 0.21.4 i used an older version without having such messages

**Comment by MaxKellermann** [comment]
I have no idea what these messages are about and what this has to do with MPD. This is the wrong place to report your problem.

**Comment by seniorgod** [comment]
Oh, I'm sorry if I'm wrong. 
I put it here because these messages occur after upgrading from mpd 20.x to mpd 21.4 and the messages trigger when mpd starts playing a song.
