### ISSUE TITLE
Reproducible core dump

### ISSUE THREAD

**Issue by shibumi** [MusicPlayerDaemon/MPD#477]
Hi,
If you set the variable `pid_file` in the `mpd.conf` file to the value `/run/user/1000/mpd/pid/` it will crash the whole daemon. It should throw an error instead saying that you can't use a directory for the pid file.
**Version:** ```Music Player Daemon 0.21.4 (0.21.4)```

**Comment by MaxKellermann** [comment]
Your bug report is bad because it contains no information at all about the crash. So that's what I do with bad bug reports: I do random guesses.

**Comment by shibumi** [comment]
Well, what additional information do you need? I provided everything to reproduce the issue, so what else do you need?

**Comment by shibumi** [comment]
I have further looked into the stacktrace.. seems like an assertion will get triggered
