### ISSUE TITLE
MPD library limited to 16384 songs?

### ISSUE THREAD

**Issue by janui** [MusicPlayerDaemon/MPD#478]
Hi,
Is the MPD library limited to 16384 songs?
If so, is there a workaround which could increase this number?
Again if so, could this limit be increased to 32K in a future release?
Thanks in advance,
janui

**Comment by MaxKellermann** [comment]
On 2019/02/10 15:15, janui <notifications@github.com> wrote:
> Is the MPD library limited to 16384 songs?

No, there is no artificial limit.  My database has 35.942 songs, for
example, and I have heard of people in the 100.000s.

**Comment by janui** [comment]
Thanks Max,

Best Regards

**Comment by doublehp** [comment]
mpd --version                                                                                                                                   
Music Player Daemon 0.19.12  

on Orange Pi Zero
Title:                  Armbian 5.35 Orangepizero Ubuntu xenial next
Kernel:                 Linux 4.13.15
Build date:             22.11.2017

Processor:
model name      : ARMv7 Processor rev 5 (v7l)

I do encontour this 16384 limit. Also found an other trace here: https://www.runeaudio.com/forum/how-to-increase-playlist-limit-t3571.html

=> this limit is a thing !!! Maybe related to "not modern" architectures ? 16384 sounds close to 2^16 ...

https://www.diyaudio.com/community/threads/moode-audio-player-for-raspberry-pi.271811/page-15
mentions to add this to mpd.conf:

> max_playlist_length "131072"

and it worked for me. (the variable did not exist in the conf before editing, but adding it worked). I did not restart service, but did stop&start. (19024 tracks ATM for me in the list)
