### ISSUE TITLE
Add a volume scaling parameter to PulseAudio output

### ISSUE THREAD

**Issue by cpitclaudel** [MusicPlayerDaemon/MPD#479]
Hi!

Values for pulseaudio volume levels are not upper-bounded: users can set the volume to e.g. 200 to amplify the original signal.

What would be a good way to leverage this feature in MPD?  From https://github.com/MusicPlayerDaemon/MPD/issues/434 I understand that the pulseaudio output plug-in maps volume values in the 0-100 range to the 0-100 range of pulseaudio.

Would it be acceptable to add an extra setting for the pulseaudio plugin that would act as a multiplier? Say `pulseaudio_volume_scale`, which would default to `1`; setting it to `0.5` would map MPD's 0-100 range to pulseaudio values spanning `0-50`, and setting it to `2.0` would map MPD's `0-100` range to pulseaudio values spanning `0-200`.

Or is there a better way to do this?

Thanks!

**Comment by MaxKellermann** [comment]
I'm not sure what's the use of such a feature, but if somebody would submit a pull request with such a feature, I'd consider merging it.

**Comment by miccoli** [comment]
Just curious: if 100% is 0dBFS (zero dB Full Scale), why should I set the volume *above* this value? Almost all music I own is mastered very loud (overcompressed to win the infamous loudness war) and setting the volume a few notches above 0dBFS (whatever this means) would only cause clipping, severe sound distortion, and less dynamic range.

**Comment by cpitclaudel** [comment]
> Just curious: if 100% is 0dBFS (zero dB Full Scale), why should I set the volume _above_ this value?

It's a valid question.  My main reason is that most of my music collection is classical music from old CDs, and that these aren't mastered very loud (and the device I play them on, a Bose bluetooth speaker, doesn't have a separate volume control).
