### ISSUE TITLE
Issue with Satellite handling of regex filters

### ISSUE THREAD

**Issue by voxxpop** [MusicPlayerDaemon/MPD#480]
Hi

I have 2 MPD instances setup in a Master/Satellite configuration, both running from the same executable v0.21.4 (Debian Unstable) on the same machine, with libmpdclient2 v2.16 (Debian Unstable).

Connecting via telnet, and running on the Master then Satellite:
`count "(artist =~ 'The The')"`
Produces the output:
```
OK MPD 0.21.4
count "(artist =~ 'The The')"
songs: 126
playtime: 35416
OK
```

and
```
OK MPD 0.21.4
count "(artist =~ 'The The')"
songs: 126
playtime: 35417
OK
```
respectively - Ok apart from the 1s time difference.

However, running count `"(artist =~ '(?i)The The')"` produces the following output respectively:
```
OK MPD 0.21.4
count "(artist =~ '(?i)The The')"
songs: 126
playtime: 35416
OK
```
and
```
OK MPD 0.21.4
count "(artist =~ '(?i)The The')"
songs: 0
playtime: 0
OK
```
The same result is obtained using `count "(artist =~ '(?i)the the')"`.
Using `find "(artist =~ '(?i)the the')"` produces the expected output on the master, but only the following on the satellite:
```
OK MPD 0.21.4
find "(artist =~ '(?i)the the')"
OK
```
Trying `count "(artist =~ '(a.*)')"` gives on the Master:
```
OK MPD 0.21.4
count "(artist =~ '(a.*)')"
songs: 20107
playtime: 5412325
OK
```
and
```
OK MPD 0.21.4
count "(artist =~ '(a.*)')"
songs: 0
playtime: 0
OK
```
on the satellite.
Trying `find "(artist =~ 'a.*')"` also shows the expected output (lots of matches) but:
```
OK MPD 0.21.4
find "(artist =~ 'a.*')"
OK
```
when run against the satellite.
It looks like the `=~` is the problem.

Using the libmpdclient function `mpd_count_db_songs()` function also exhibits the same issue when run against the satellite.

v

**Comment by MaxKellermann** [comment]
According to https://buildd.debian.org/status/fetch.php?pkg=mpd&arch=amd64&ver=0.21.4-1%2Bb1&stamp=1547037223&raw=0 the Debian package was built with libmpdclient 2.11, which predates the regex features. Thus, a MPD binary built with such an old libmpdclient version cannot properly support these features.
