### ISSUE TITLE
cdio plugin does not compile on 0.21.5

### ISSUE THREAD

**Issue by riggs-** [MusicPlayerDaemon/MPD#490]
SEEK_SET is not necessarily defined when stdio is not included.
Patch proposal see pull request https://github.com/MusicPlayerDaemon/MPD/pull/489

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/MPD/commit/4c50a5e0b309adc524cda7a00c034ba2eb3689da
