### ISSUE TITLE
Error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by hrqmonteiro** [MusicPlayerDaemon/MPD#491]
Did a fresh arch install, in my previous it was all functioning with no problems, now mpd simply won't function because of this error.

mpd: error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or directory

Don't know what to do, alteady tried to recompile, this fluidsynth is already installed, tried everything and simply don't work

**Comment by terorie** [comment]
Are you sure `libfluidsynth.so` got installed to right path?

If so, try starting with `LD_PRELOAD=/path/to/my/libfluidsynth.so mpd` (replace with the actual path to libfluidsynth).

**Comment by hrqmonteiro** [comment]
> Are you sure `libfluidsynth.so` got installed to the right path?
> 
> If so, try starting with `LD_PRELOAD=/path/to/my/libfluidsynth.so mpd` (replace with the actual path to libfluidsynth).

The lib is in /usr/lib/libfluidsynth.so
This command you said gives me the same error.

![2019-02-23-155735_747x371_scrot](https://user-images.githubusercontent.com/17055027/53290513-bf39f200-3783-11e9-99e0-1bb8526cd157.png)

**Comment by hrqmonteiro** [comment]
I think the thing is that this libfluidsynth.so.1 simply doesnt exists, only this other ones:

When i enter pacman -Ql fluidsynth, the result is below:

![2019-02-23-160231_775x370_scrot](https://user-images.githubusercontent.com/17055027/53290551-6fa7f600-3784-11e9-8a84-185f0a1c73d6.png)

So this .so.1 simply doesnt comes with the installation of mpd (which itself installs the fluidsynth package)

**Comment by MaxKellermann** [comment]
This is not a MPD problem at all. This library isn't part of MPD, and its installation is out of MPD's scope. Ask your distribution for help.

**Comment by niallwdmartin** [comment]
I got round this by just copying libfluidsynth.so to libfluidsynth.so.1
```
find /usr/lib -name "libfluidsynth.so"
cp /usr/lib/libfluidsynth.so /usr/lib/libfluidsynth.so.1 
```
Works, not sure if politically correct :)
