### ISSUE TITLE
'pa_stream_new() has failed: Invalid argument' when playing a file with the wrong number of channels

### ISSUE THREAD

**Issue by cpitclaudel** [MusicPlayerDaemon/MPD#493]
Hello,

When I attempt to play a 5-channels OGG file through MPD, the command line client displays the following error:

```
ERROR: Failed to open "Pulse output" (pulse); pa_stream_new() has failed: Invalid argument
```

Playing the same file using `oggdec` then `paplay` works (though `paplay` complains: `Warning: Failed to determine channel map from file.`).  From reading the source code, the issue seems to be coming from this function:

```c++
inline void
PulseOutput::SetupStream(const pa_sample_spec &ss)
{
	assert(context != nullptr);

	/* WAVE-EX is been adopted as the speaker map for most media files */
	pa_channel_map chan_map;
	pa_channel_map_init_auto(&chan_map, ss.channels,
				 PA_CHANNEL_MAP_WAVEEX);
	stream = pa_stream_new(context, name, &ss, &chan_map);
	if (stream == nullptr)
		throw MakePulseError(context,
				     "pa_stream_new() has failed");
…
```

`pa_stream_new` calls `pa_stream_new_with_proplist`, which is here: https://github.com/pulseaudio/pulseaudio/blob/4e3a080d7699732be9c522be9a96d851f97fbf11/src/pulse/stream.c#L207

I rebuilt libpulse with debugging symbols to determine which part failed; it turns out that the issue is this test:

```c
PA_CHECK_VALIDITY_RETURN_NULL(c, !map || (pa_channel_map_valid(map) && map->channels == ss->channels), PA_ERR_INVALID);
```

`pa_channel_map_valid(map)` returns false, because of the map allocated by `pa_channel_map_init_auto`:

```
(gdb) print *map                                                                                                      
$28 = {channels = 5 '\005', map = {PA_CHANNEL_POSITION_INVALID <repeats 32 times>}}  
```

This makes sense, because `pa_channel_map_init_auto` doesn't know how to deal with five channels: in https://github.com/pulseaudio/pulseaudio/blob/4e3a080d7699732be9c522be9a96d851f97fbf11/src/pulse/channelmap.c#L297, the `PA_CHANNEL_MAP_WAVEEX`  case returns `null` when the channel count is 5.

I think the issue is that the value returned by the call to `pa_channel_map_init_auto` is not checked:

https://github.com/MusicPlayerDaemon/MPD/blob/44422b2b2f0a0bf29ffadfac0814b9bcd17db564/src/output/plugins/PulseOutputPlugin.cxx#L584

If it returns `null`, MPD could produce a more informative error message.  I'm not sure whether that's the right solution, though, or whether it would be better to call `pa_channel_map_init_extend` instead (which would map the fifth channel to AUX0), or something else.  Hence the long bug report :) Thanks!

**Comment by MaxKellermann** [comment]
Thanks for the excellent analysis. I decided to switch to `pa_channel_map_init_extend` which is a best-effort attempt to do the right thing.

**Comment by cpitclaudel** [comment]
Looks great.  Thanks for your continued dedication and hard work!
