### ISSUE TITLE
Support for case insensitive list command

### ISSUE THREAD

**Issue by ferdkuh** [MusicPlayerDaemon/MPD#494]
I think it would be nice to nice to have the ability to have to ability to do case-insensitive queries for tags using the `list `command. Currently this only seems possible when searching for songs using.

After playing around a bit I added a `listi` command that does that, analogous to  `find` / `search`. Is there interest in adding this feature? Should I create a "pull request" (it's really just ~15 lines)?
(Sorry, I am not really familiar with this process)

Best regards
Jonas

**Comment by MaxKellermann** [comment]
Yes, please create a PR.
I don't think a proper implementation is possible with just 15 lines because you'd need to extend the `Database` interface plus implementations for two database plugins, with compile-time and run-time checks in the `proxy` plugin. This isn't trivial, but I welcome your effort. Tell me if you need help.

**Comment by asktoby** [comment]
I'm controlling mpc with voice (via Google Home and IFTTT) and am having trouble with the
`mpc find`
command being case sensitive.

@ferdkuh in your first message you seem to imply that you know a way to do this, but you didn't finish the sentence?

> Currently this only seems possible when searching for songs using.   ...?

What was your method please?

**Comment by MaxKellermann** [comment]
@asktoby your question has nothing to do with this feature request. What you want is `mpc search`.

**Comment by asktoby** [comment]
Thanks, that's great. Sorry for the noise on-thread.

**Comment by buzuck** [comment]
Currently `mpc search` requires the right accentuation (eg `Mànran` is not found when searching for `manran`)

This may be harder to fix, so I will gladly open another issue for this if needed :-)
