### ISSUE TITLE
Crash, Assertion failed

### ISSUE THREAD

**Issue by Old-Geek** [MusicPlayerDaemon/MPD#496]
MPD: 0.21.15

MacOS: Mojave

Mar 01 09:57 : client: [91] opened from [::1]:62137
Mar 01 09:57 : player: played "https://listen.radioking.com/radio/110266/stream/149317"
Mar 01 10:02 : player: played "http://cdn.nrjaudio.fm/audio1/fr/30401/mp3_128.mp3?origine=tunein"
Assertion failed: (tail == (size_t)input->GetOffset()), function Read, file ../mpd-0.21.5/src/input/RewindInputStream.cxx, line 107.

**Comment by MaxKellermann** [comment]
Backtrace, please.
