### ISSUE TITLE
Opus loudness tags sometimes ignored

### ISSUE THREAD

**Issue by p10s** [MusicPlayerDaemon/MPD#497]
Loudness tags in Opus files (R128_TRACK_GAIN and R128_ALBUM_GAIN) are ignored when other common tags (e.g. TITLE, ARTIST, ALBUM) are missing. This seems to be caused by an incorrect condition in MPDOpusDecoder::HandleTags. The ReplayGainInfo rgi is only submitted when tag_builder is not empty, but loudness tags are not stored in tag_builder, so this condition will fail when the Opus file has loudness tags but no other (common) tags.

Version: 0.21.5

**Comment by MaxKellermann** [comment]
Thanks, your analysis was correct.
