### ISSUE TITLE
DSD_U32_BE altsetting Dont work

### ISSUE THREAD

**Issue by norrest** [MusicPlayerDaemon/MPD#50]
/* XMOS based USB DACs */
	switch (chip->usb_id) {
	case USB_ID(0x27f7, 0x1301): /* Wyred DSD Inrerface */
	
		if (fp->altsetting == 2)
			return SNDRV_PCM_FMTBIT_DSD_U32_BE;
		break;

In settings Dop = Off 

lsusb
Bus 001 Device 002: ID 27f7:1301 

cat /proc/asound/*
 0 [Interface      ]: USB-Audio - 32bit 384kHz DSD Interface
                      Wyred 4 Sound 32bit 384kHz DSD Interface at usb-1c14000.usb-1, high speed
  2: [ 0]   : control
  3: [ 0- 0]: digital audio playback
 33:        : timer
cat: /proc/asound/Interface: Is a directory
 0 snd_usb_audio
00-00: USB Audio : USB Audio : playback 1
G0: system timer : 1000.000us (10000000 ticks)
P0-0-0: PCM playback 0-0-0 : SLAVE
Advanced Linux Sound Architecture Driver Version k4.4.44.

cat: /proc/asound/card0/pcm0p: Is a directory
Wyred 4 Sound 32bit 384kHz DSD Interface at usb-1c14000.usb-1, high speed : USB Audio

Playback:
  Status: Running
    Interface = 2
    Altset = 1
    Packet Size = 448
    Momentary freq = 352795 Hz (0x2c.1970)
    Feedback Format = 16.16
  Interface 2
    Altset 1
    Format: S32_LE
    Channels: 2
    Endpoint: 5 OUT (ASYNC)
    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us

mpd.config 
decoder {
                plugin "ffmpeg"
                enabled "yes"
}

input {
                plugin "curl"
}

audio_output {

                 type           "alsa"
                 name           "Output"
                 device         "hw:0,0"
                 dop    "no"

**Comment by MaxKellermann** [comment]
I have no idea what this is about. Your bug report lacks a bug description. There's a bunch of pastes, but these are meaningless without a description.

**Comment by norrest** [comment]
DSD_U32 applications in the new version does not work!
It is a bug! (

**Comment by MaxKellermann** [comment]
"Does not work" is the worst possible problem description.

**Comment by norrest** [comment]
This site is not a full-featured bug trackers for internal correspondence of developers, so here you can speak in any form!
Does not work - mean "Do not support"

**Comment by MaxKellermann** [comment]
Your bug report "does not work".

**Comment by norrest** [comment]
for example:
https://patchwork.kernel.org/patch/9479117/
Add DSD support for  big endian (DSD_U32_BE)
--------------------------------------------------------
In my case
```
/* XMOS based USB DACs /
switch (chip->usb_id) {
case USB_ID(0x27f7, 0x1301): / Wyred DSD Inrerface */
	if (fp->altsetting == 2)
		return SNDRV_PCM_FMTBIT_DSD_U32_BE;
	break;

```
After this, id dop = off 
I must see 
DSD_U32_BE
But 
cat: /proc/asound/card0/*
Show 
Format: S32_LE

**Comment by ronnyzhao** [comment]
Hi norrest,
     YOU can play DSD file in native mode?
 can't play DSD file in native, MY DAC is support native DSD.  XMOS USB, Ustar Audio, USB ID: 20b1, 2012
I add kernel quirks, BUT not success still. hope get your help, thanks.
my E-mail: zybroseman2010@126.com
