### ISSUE TITLE
Fail to play some wav files from an http server

### ISSUE THREAD

**Issue by FeroSu** [MusicPlayerDaemon/MPD#501]
I had problem problem while playing some WAV files from http server after upgrade to version 0.21.4 in archlinux. mpd crashed with this error: 

>/src/util/SparseBuffer.cxx:36: SparseMap::CheckResult SparseMap::Check(SparseMap::size_type) const: Assertion offset < GetEndOffset()'
> 

Now, after upgrading to version 0.21.5 mpd doesn't crash, it keeps working, but it's not capable of playing wav files of smaller sizes (any of those <128 MB), they get stuck at the beginning. Large wav files are played back without problems.

There was similar issue #453, now closed, describing problem.

**Comment by MaxKellermann** [comment]
The version you're using is outdated, it predates the #453 fix!

**Comment by FeroSu** [comment]
I have the last AVAILABLE version installed and the problem still persists. 
===============
# mpd -V
Music Player Daemon 0.21.5 (0.21.5)
===============

**Comment by FeroSu** [comment]
I have the last AVAILABLE version installed and the problem still persists...

mpd -V
Music Player Daemon 0.21.5 (0.21.5)

**Comment by FeroSu** [comment]
I have just upgraded to version 0.21.6. and the problem still persists.
There is no possibility to playback smaller files wav files via http.
