### ISSUE TITLE
Any direction on how to use with qobuz

### ISSUE THREAD

**Issue by gearhead** [MusicPlayerDaemon/MPD#503]
I just enabled my qobuz account. They said to use bubbleupnp as the interface. Well, I can do that and play streamed music on the phone, but when I select the MPD renderer it fails. It will play local music (on the phone). I see reference to qobuz usernames and such in the config file. How do I configure MPD.conf to use this?

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/html/plugins.html#qobuz
