### ISSUE TITLE
Chinese characters in artist names

### ISSUE THREAD

**Issue by makmm** [MusicPlayerDaemon/MPD#504]
I'm randomly getting random chinese characters on artist names. Some with special characters (like í) and others not.
![2019-03-08_20-31](https://user-images.githubusercontent.com/7550995/54064946-9e58ae80-4211-11e9-840a-8368f5ca2029.png)

**Comment by owl770** [comment]
I have this same problem with some of my tracks. I realise that it is not an MPD issue as it is just displaying the characters as received. I *think* my problem started when I edited ID3 tags using ncmpcpp. I assume it is an encoding problem but I don't know how to fix it. Any tips/suggestions/ideas would be greatly appreciated. Thanks.

**Comment by makmm** [comment]
@owl770 I have checked with gnome-music, rhythmbox and even Retro Music (in Android) the tags, and they don't have chinese characters. What application are you using to check it?

**Comment by owl770** [comment]
@makmm  I can see the Chinese characters in MPDroid, mpc, o!mpd

![Screen Shot 2019-03-11 at 8 58 36 am](https://user-images.githubusercontent.com/16440359/54092078-f6dba780-43db-11e9-97fe-955da2820226.png)

**Comment by owl770** [comment]
And this is what "File Info" in O!MPD displays for one of the tracks...
![Screen Shot 2019-03-12 at 10 39 04 pm](https://user-images.githubusercontent.com/16440359/54197330-be40e880-4517-11e9-907d-fd60cf6a6420.png)

**Comment by MaxKellermann** [comment]
What makes you believe that this is a MPD bug and not a bug in the client you're using?

**Comment by owl770** [comment]
As I mentioned in my original post, I don't believe it to be an mpd bug but based on the OP comment, I just wanted some guidance on how to fix it (if anyone had come across it before)...

**Comment by MaxKellermann** [comment]
The question was meant for the submitter. He didn't provide any useful information, not even his MPD version number.

**Comment by MaxKellermann** [comment]
Will reopen when the required information is posted.

**Comment by makmm** [comment]
@MaxKellermann Ah sorry, I hate GitHub so I almost never log in into it. I tried with ncmpcpp and mpc and both failed, so I just assumed it was MPD's fault. any other client I can try with?

**Comment by MaxKellermann** [comment]
What did they fail?
You still did not post your version number.
Why do you believe that your file is correct? Upload an example file demonstrating the problem.
You said this occurs randomly. So sometimes one file gets chinese characters, and sometimes that very same file does not get chinese characters? This doesn't make sense. Be more specific and exact in your problem description.
I can't help unless you help me understand your problem.

**Comment by makmm** [comment]
```
~ % mpc list title
GDFR (feat. Sage The Gemini & Lookas) (K Theory Remix)
~ % mpc list artist
Flo Rida
䰀漀漀欀愀猀
匀愀最攀 吀栀攀 䜀攀洀椀渀椀
~ % mpd --version
Music Player Daemon 0.21.6 (0.21.6)
```

![Screenshot_20190401_184720](https://user-images.githubusercontent.com/7550995/55361901-04122080-54c8-11e9-82cc-5cc73ee241e2.png)
https://www77.zippyshare.com/v/vcoN7Z8O/file.html

The same file always gets chinese characters, it just doesn't seem to have a pattern between files.

is that enough?

**Comment by MaxKellermann** [comment]
Your file has three "Artist" tag values: "Flo Rida", "Sage The Gemini" and "Lookas". The three are part of one ID3v2 string list; at the beginning of the string list, there is a UTF-16 byte order mark. The first tag value "Flo Rida" is decoded properly by libid3tag; however libid3tag then forgets about the byte order mark, and parses the next two values of the string list without that knowledge, leading to garbage (which just happens to be Chinese characters).

This is a libid3tag bug, and MPD can do nothing to fix this, sorry. This must be fixed in libid3tag.

From the ID3v2 standard: http://id3.org/id3v2.4.0-structure
> UTF-16 [UTF-16] encoded Unicode [UNICODE] with BOM. **All strings in the same frame SHALL have the same byteorder.**

**Comment by makmm** [comment]
@MaxKellermann Well if I'm being honest I didn't understand nothing of that, could you please report this issue yourself? thanks.
