### ISSUE TITLE
Proxing issue: list artist TAG "VALUE"

### ISSUE THREAD

**Issue by mxjeff** [MusicPlayerDaemon/MPD#506]
With this proxy setup on `server1`:
```ini
database {
       plugin "proxy"
       host "server0"
       port "6600"
}
```
Running a list command on `server1` fails:
```bash
printf 'list artist Genre "Jazz"\nclose\n' | nc server1 6600

OK MPD 0.21.4
ACK [2@0] {} should be "Album" for 3 arguments
```
Looking at the verbose log on `server0` shows the following for the failed command:
```
client: [1] process command "list Artist "(Genre == \"Jazz\")""
client: [1] command returned 2
```

While running it on `server0` succeeds:
 
```bash
printf 'list artist Genre "Jazz"\nclose\n' | nc server0 6600

OK MPD 0.21.4
Artist: ...
...
OK
```
The log is now:

```
process command "list artist Genre "Jazz""
command returned 0
```

**Comment by MaxKellermann** [comment]
Which libmpdclient was used to compile both MPDs? (Note: I did not ask which libmpdclient version is being used at runtime)

**Comment by mxjeff** [comment]
On `server1` I'm pretty sure it's built with 2.16 even though I did not build it myself [0].
On `server0` I rebuilt it myself against 2.16.

[0] http://buildd.raspbian.org/status/fetch.php?pkg=mpd&arch=armhf&ver=0.21.5-3&stamp=1552029039

**Comment by mxjeff** [comment]
Actually this is probably the `list` command which is not working with filters.

Running on the same standalone server (no proxy set up).
 ```
find "( genre == 'Jazz' )"
```
**runs fine**

While
```
list "artist" "( genre == 'Jazz' )"
[2@0] {list} should be "Album" for 3 arguments
```
**fails**

This is probably triggered by the proxy setup because the old query format `<type> [<type> <query>]` seems to be converted with filters as show in the log.
`list artist Genre "Jazz"` on `server1` appears in `server1` log as `list Artist "(Genre == \"Jazz\")`.

Does it make any sense or did I overlook something?

**Comment by mxjeff** [comment]
Thanks Max :)
