### ISSUE TITLE
MPD 0.20 Does Not support DSD_U32_BE format

### ISSUE THREAD

**Issue by norrest** [MusicPlayerDaemon/MPD#51]
Why mpd ( for **dop=off**)   dont use DSD_U32_BE kernel settings (sound/usb/quirks.c):
`/* XMOS based USB DACs /
switch (chip->usb_id) {
case USB_ID(0x27f7, 0x1301): / Wyred DSD Inrerface */
   if (fp->altsetting == 2)
      return SNDRV_PCM_FMTBIT_DSD_U32_BE;
   break;`

And during dsd playback 

`cat: /proc/asound/card*
Wyred 4 Sound 32bit 384kHz DSD Interface at usb-1c14000.usb-1, high speed : USB Audio

Playback:
Status: Running
Interface = 2
Altset = 1
Packet Size = 448
Momentary freq = 352795 Hz (0x2c.1970)
Feedback Format = 16.16
Interface 2
Altset 1
Format: S32_LE
Channels: 2
Endpoint: 5 OUT (ASYNC)
Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
Data packet interval: 125 us`

32_LE but must be **DSD_U32_BE**

**Comment by ronnyzhao** [comment]
Now, what it is MPD support format (all format) ?
I add kernel quirks DSD_U32_BE or DSD_U32_LE
BUT can't play DSD in native mode successfully.
give me help please, email: zybroseman2010@126.com , thanks.
