### ISSUE TITLE
Fail to play some wav files from an http server

### ISSUE THREAD

**Issue by FeroSu** [MusicPlayerDaemon/MPD#512]
The problem from issue #453 and #501 remains unsolved.
I have tested versions 0.21.5 and 0.21.6

Playback of smaller wav files is stuck in the beginning of track.

**Comment by MaxKellermann** [comment]
Both tickets you refer to are about different problems (crash bug, not "stuck in the beginning").
Your bug report is devoid of information. In spite of your bad bug report, I took some of my free time to attempt to reproduce it, but couldn't. Everything works just fine.
