### ISSUE TITLE
how to use hdcd (example in Documentation)

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#513]
It tried to used hdcd filter.

I got something like that:

>  playlist: play 1710:"Mike_Oldfield/Mike_Oldfield_-_Five_Miles_Out_HDCD/01_Taurus_II.flac"
playlist: queue song 1711:"Mike_Oldfield/Mike_Oldfield_-_Five_Miles_Out_HDCD/02_Family_Man.flac"
decoder_thread: probing plugin ffmpeg
ffmpeg/flac: Format flac probed with size=2048 and score=100
ffmpeg: detected input format 'flac' ((null))
ffmpeg/flac: Before avformat_find_stream_info() pos: 4177 bytes read:8192 seeks:0 nb_streams:1
ffmpeg/flac: All info found
ffmpeg/flac: stream 0: start_time: 0.000 duration: 1485.360
ffmpeg/flac: format: start_time: 0.000 duration: 1485.360 bitrate=871 kb/s
ffmpeg/flac: After avformat_find_stream_info() pos: 6225 bytes read:8192 seeks:0 frames:1
ffmpeg: codec 'flac'
decoder: audio_format=44100:16:2, seekable=true
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
ffmpeg/NULL: reserved blocksize code: 0
alsa_output: opened hw:V102,0 type=HW
alsa_output: buffer: size=90..174762 time=2040..3962858
alsa_output: period: size=45..87381 time=1020..1981429
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S24_3LE (Signed 24 bit Little Endian in 3bytes)
alsa_output: buffer_size=22050 period_size=5513
output: opened "V102,0 [USB-SPDIF V1.02 USB Audio]" (alsa) audio_format=44100:24:2

I tried with such sections in /etc/mpd.conf

`filter {
plugin		"ffmpeg"
graph		"hdcd"
}`

and with
`filter {
plugin		"hdcd"
enabled		"yes"
}`

None of them works.

It would be great to have working example in Documentation.

**Comment by MaxKellermann** [comment]
Your configurations are both wrong. The setting `enabled` does not exist in `filter` sections, and you did not specify the `name`. Without a name, how did you refer to the filter in the `audio_output` section?

This isn't just yet about documentation missing - [there is documentation](https://www.musicpd.org/doc/html/user.html#configuring-filters), but it looks like you didn't read it at all.

**Comment by mistepien** [comment]
Ok, I managed. Now I have a question. This is example of log during playing non-hdcd file. Am I right that hdcd filter does not interfere with bitperfect playback?

>   playlist: play 1709:"Kylie_Minogue/Kylie_Minogue_-_Kylie/10_Love_at_First_Sight.flac"
playlist: queue song 1710:"Mike_Oldfield/Mike_Oldfield_-_Five_Miles_Out_HDCD/01_Taurus_II.flac"
decoder_thread: probing plugin flac
decoder: audio_format=44100:16:2, seekable=true
ffmpeg/abuffer: Setting 'sample_rate' to value '44100'
ffmpeg/abuffer: Setting 'sample_fmt' to value 's16'
ffmpeg/abuffer: Setting 'channels' to value '2'
ffmpeg/abuffer: Setting 'time_base' to value '1/44100'
ffmpeg/abuffer: tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:(null)
ffmpeg/Parsed_hdcd_0: Disabling automatic format conversion.
ffmpeg/AVFilterGraph: query_formats: 3 queried, 6 merged, 0 already done, 0 delayed
ffmpeg/Parsed_hdcd_0: Auto-convert: disabled
ffmpeg/Parsed_hdcd_0: Looking for 16-bit HDCD in sample format s16
ffmpeg/Parsed_hdcd_0: CDT period: 2000ms (88200 samples @44100Hz)
ffmpeg/Parsed_hdcd_0: Process mode: process stereo channels together
ffmpeg/Parsed_hdcd_0: Force PE: off
ffmpeg/Parsed_hdcd_0: Analyze mode: [0] disabled
alsa_output: opened hw:V102,0 type=HW
alsa_output: buffer: size=90..174762 time=2040..3962858
alsa_output: period: size=45..87381 time=1020..1981429
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S24_3LE (Signed 24 bit Little Endian in 3bytes)
alsa_output: buffer_size=22050 period_size=5513
output: opened "V102,0 [USB-SPDIF V1.02 USB Audio]" (alsa) audio_format=44100:24:2
output: converting in=44100:16:2 -> f=44100:32:2 -> out=44100:24:2
state_file: Saving state file /tmp/mpd/state
playlist: stop
player: played "Kylie_Minogue/Kylie_Minogue_-_Kylie/10_Love_at_First_Sight.flac"
output: closed "V102,0 [USB-SPDIF V1.02 USB Audio]" (alsa)
ffmpeg/Parsed_hdcd_0: Channel 0: counter A: 0, B: 0, C: 0
ffmpeg/Parsed_hdcd_0: Channel 0: pe: 0, tf: 0, almost_A: 0, checkfail_B: 0, unmatched_C: 0, cdt_expired: -1
ffmpeg/Parsed_hdcd_0: Channel 0: tg 0.0: 0
ffmpeg/Parsed_hdcd_0: Channel 1: counter A: 0, B: 0, C: 0
ffmpeg/Parsed_hdcd_0: Channel 1: pe: 0, tf: 0, almost_A: 0, checkfail_B: 0, unmatched_C: 0, cdt_expired: -1
ffmpeg/Parsed_hdcd_0: Channel 1: tg 0.0: 0
ffmpeg/Parsed_hdcd_0: Packets: type: ?, total: 0
ffmpeg/Parsed_hdcd_0: HDCD detected: no

**Comment by MaxKellermann** [comment]
No.

**Comment by mistepien** [comment]
Thus the statement "hdcd filter does not interfere with bitperfect playback of non-hdcd files" is true.

**Comment by MaxKellermann** [comment]
No.
Be careful with negated questions!

**Comment by MaxKellermann** [comment]
If you still believe there should be an example, submit a PR.

**Comment by mistepien** [comment]
Ok, but if file is non-hdcd then filter should to change the data.

**Comment by MaxKellermann** [comment]
Should not, but it does. That's how FFmpeg implements the filter, which is out of MPD's scope.
