### ISSUE TITLE
How does listing with filters work?

### ISSUE THREAD

**Issue by ondras** [MusicPlayerDaemon/MPD#515]
Hi,

I am confused by the way listing works when filters are used. My goal is to list all albums for a particular artist.

I am able to execute the **find** command with a filter:

```bash
$ echo 'find "(Artist == \"Caro Emerald\")"' | nc 0 6600 -N | grep Album | wc -l
12
```

But listing the distinct **Album** tags with the very same filter fails:

```bash
$ echo 'list album "(Artist == \"Caro Emerald\")"' | nc 0 6600 -N
OK MPD 0.21.4
OK
```

What am I doing wrong?

**Comment by MaxKellermann** [comment]
I have no idea, but I refuse to talk about outdated MPD versions.

**Comment by ondras** [comment]
Hi @MaxKellermann ,

thaks for your extra-prompt reply!

MPD 0.21.4 is the latest available in a pre-made package for Ubuntu. I even had to backport it from an unreleased (Disco) distribution, because according to [the official package search](https://packages.ubuntu.com/search?keywords=mpd&searchon=names&exact=1&suite=all&section=all), the latest stable would be 0.20.21.

I am willing to try to compile a more recent (git master) version, but I was unable to find any compilation instructions. I cloned the source code, but there is no `./configure` script, no `Makefile`, no `CMakeLists.txt` etc. I am not familiar with this. I am sorry for not properly understanding the build system. Does this limit my ability to ask questions? Would you please give me instructions to compile the source code so I can re-try with a version that is not considered outdated?

Finally, given the fact that you immediately closed my question, is it okay to post my comment here? Or shall I start a different issue? I have no idea what is your policy regarding GitHub issues.

**Comment by MaxKellermann** [comment]
Please go and complain to Ubuntu. More people should do that. Blame them for shipping outdated MPD versions. It's distributions like Ubuntu and Debian who have caused much frustration among many MPD users because they ship known-buggy MPD versions.

Compilation instructions can easily be found in MPD's documentation. I can't imagine how you could possibly miss those. Did you even see that MPD has documentation? Sure the documentation is not perfect, much of it outdated or badly written and incomplete, but the piece you're looking for is there and up to date.

**Comment by ondras** [comment]
> Compilation instructions can easily be found in MPD's documentation. I can't imagine how you could possibly miss those.

My bad, sorry. I was reading the [developer docs](https://www.musicpd.org/doc/html/developer.html), incorrectly assuming I would find the compilation info there.



> Did you even see that MPD has documentation?

[That](https://www.musicpd.org/doc/html/protocol.html#filters) is exactly where I read about those commands this issue is about.

I will try to compile MPD myself now and re-try again, posting my findings later.

**Comment by ondras** [comment]
Apparently the issue I found is precisely this: https://github.com/MusicPlayerDaemon/MPD/commit/59fdfd25cbfc82cd5bad92d26b9d904b8f81014b

Thanks for pointing me to a newer MPD version, although I am pretty pesimistic about MPD >= 0.21.6 being generally available anytime soon :-(
