### ISSUE TITLE
The 'findadd' command does not accept sort

### ISSUE THREAD

**Issue by ondras** [MusicPlayerDaemon/MPD#516]
Is there any reason why `findadd` does not accept explicit sort order? The sibling `find` command does that...

Alternatively, what is the recommended way to enqueue a large set of songs (based on filters) with a particular order?

**Comment by ondras** [comment]
Thanks a lot, @MaxKellermann !

**Comment by ondras** [comment]
This feature was apparently commited into a 0.22 release, but 0.22 has not been released over the course of almost one year. Is it necessary to wait for 0.22 to get the (fixed, implemented, ...) feature mentioned in this issue?

**Comment by MaxKellermann** [comment]
No, you don't need to wait, you can use git master any time. It's open source!

**Comment by ondras** [comment]
> No, you don't need to wait, you can use git master any time. It's open source!

Great.

Is there any particular reason for this feature not officially released yet, apart from giving people chance to use git master? In other words, is there an ETA for 0.22?

Waiting for a long time might be a reason to try setting up the whole daunting toolchain; things I never did before and am a bit afraid to fight with.

**Comment by MaxKellermann** [comment]
ETA is when it's done, and I wanted it to be done very long ago but got distracted too often. Yes, I should really learn to draw a line earlier...
