### ISSUE TITLE
garbled characters from webradio titles

### ISSUE THREAD

**Issue by gbrault** [MusicPlayerDaemon/MPD#517]
I have added this stream with mpc: 
```
mpc add http://stream.srg-ssr.ch/m/rsc_fr/aacp_96
mpc play
```
When I do mpc I get ? for some characters. 
Example:
```
Radio Suisse Classique: Johann Joachim Quantz - Allegretto du concerto pour fl?te et orchestre en r? majeur "Pour Potsdam"
[playing] #1/3   0:44/0:00 (0%)
volume: 64%   repeat: off   random: off   single: off   consume: off
```
The French characters are represented with ?.
What am I doing wrong?

**Comment by MaxKellermann** [comment]
The radio station is doing something wrong. They send those characters as ISO-8859-1, but MPD assumes they're UTF-8.
