### ISSUE TITLE
one cpu goes 100% 

### ISSUE THREAD

**Issue by 1985a** [MusicPlayerDaemon/MPD#518]
Hello, I have been suffering this problem since November the last year. I don't sure why it is, but I believe it is something related to snd_pcm_drain.

At the first time, I believe it was related to "GME" because the main use is for "streaming ost of the old games".

Then I test with some mp3 sound and the problem came out.

I don't know how to debug this program, but I think you might see something in those screenshots.

https://imgur.com/a/g7hK0We

mpd.conf
https://pastebin.com/yGDpgRuf

btw, I'm using the latest stable version, before that, I was using the git version. Both have that problem.

pd: my English has a problem, due to is not my mother language.

**Comment by MaxKellermann** [comment]
Which kernel version and which ALSA driver is being used? Copy the contents of `/proc/asound/cards`

**Comment by MaxKellermann** [comment]
And please paste a brief strace only of the thread which goes to 100% - using `strace -tttTp $THE_PID -o /tmp/trace`

**Comment by 1985a** [comment]
Thanks for you reply.
This is the strace-mpd-rtio <-- thread according to htop
https://pastebin.com/bHChgYTd

This one is the mpd strace
https://pastebin.com/Xmr2undZ


This is the sound card /proc/asound/cards

 0 [Intel          ]: HDA-Intel - HDA Intel
                      HDA Intel at 0xf6ffc000 irq 26


Finally, my kernel version

Linux nautilus.tcp4.me 4.20.3-zen2-1-zen #1 ZEN SMP PREEMPT Sun Jan 20 22:17:49 UTC 2019 x86_64 GNU/Linux

**Comment by MaxKellermann** [comment]
This very much looks like another instance of an old known alsa-lib bug. There is a workaround for one such bug in MPD, see: https://github.com/MusicPlayerDaemon/MPD/commit/f85d4d28d1e
alsa-lib bug fix 1: https://github.com/alsa-project/alsa-lib/commit/fdc898d41135
alsa-lib bug fix 2: https://github.com/alsa-project/alsa-lib/commit/e4377b16454f
Please report this to the alsa-lib project. I'm sorry I can't help you - this doesn't look like a MPD problem.
