### ISSUE TITLE
Stickers on root directory

### ISSUE THREAD

**Issue by caschoff** [MusicPlayerDaemon/MPD#524]
The documentation says: “Stickers” [2] are pieces of information attached to existing MPD objects (e.g. song files, **directories**, albums). Clients can create arbitrary name/value pairs. MPD itself does not assume any special meaning in them.

I tryed to stick a sticker on the "root" directory, but this seems not to work (or I did not found out the right syntax). Stickers on the "root" directory would be useful because its the only existing thing where you can stick stickers if the db is empty.

- Christian

**Comment by MaxKellermann** [comment]
Stickers are currently only implemented for songs. I thought this was documented, but I can't find it.
