### ISSUE TITLE
"Assertion `chunk->CheckFormat(format)' failed." crashes mpd randomly after running for some time

### ISSUE THREAD

**Issue by tmladek** [MusicPlayerDaemon/MPD#525]
Hello,
if I let mpd run for a day or two, I come back to this error and a crashed mpd:

    mpd: ../src/player/Thread.cxx:785: void PlayerControl::PlayChunk(DetachedSong&, MusicChunkPtr, const AudioFormat&): Assertion `chunk->CheckFormat(format)' failed.

I'm running mpd 0.21.5 on an up-to-date Debian stable.

It doesn't output anything to any physical audio device, but instead sends a MP3 and an OGG stream to an Icecast2 server. I *think* the crashes stopped happening (or happened less often) when I was only streaming a 128kbps MP3 stream, whereas now I'm streaming a 192kbps stream and a q=7 OGG, but given the timescales needed for the crash to happen, I can't say this for sure.

**Comment by tmladek** [comment]
I have updated my mpd and will try to produce a backtrace, but it might take a day or two unfortunately.

**Comment by MaxKellermann** [comment]
Let's reopen this when you have the required information.

**Comment by thiagolamosa** [comment]
I'm also facing this problem... any clues?

Raspberry Pi 2
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

mpd  0.21.5 (0.21.5)

**Comment by MaxKellermann** [comment]
@thiagolamosa no clues because you didn't give any, just like the original submitter. Note that meanwhile, 0.21.5 is heavily outdated; the current MPD version is 0.21.16, so you're 11 bug-fix releases behind.

**Comment by thiagolamosa** [comment]
@MaxKellermann , how can I help?


The last **syslog** entry is 
rngd[220]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
![IMG_20191101_234726](https://user-images.githubusercontent.com/6069579/68065073-95699f80-fd02-11e9-991b-7f85dc78dc06.jpg)


In the **mpd.log**, the last entry is
mpd: ../src/player/Thread.cxx:785: void PlayerControl::PlayChunk(DetachedSong&, MusicChunkPtr, const AudioFormat&): Assertion `chunk->CheckFormat(format)' failed.
The previous line is the last played song.

**Comment by thiagolamosa** [comment]
I think the problem is the audio file...
The "Pai nosso.mp3" codec is different from the others: 
![image](https://user-images.githubusercontent.com/6069579/68071898-3c2f5980-fd5e-11e9-9553-580246abe648.png)

On Windows, it doesn't show the bit-rate
![image](https://user-images.githubusercontent.com/6069579/68071925-7bf64100-fd5e-11e9-897b-ac5ea1ce5483.png)

 I'm restarting the playlist after removing the file. Let's see how it ends...

**Comment by thiagolamosa** [comment]
> I think the problem is the audio file...
> The "Pai nosso.mp3" codec is different from the others:
> ![image](https://user-images.githubusercontent.com/6069579/68071898-3c2f5980-fd5e-11e9-9553-580246abe648.png)
> 
> On Windows, it doesn't show the bit-rate
> ![image](https://user-images.githubusercontent.com/6069579/68071925-7bf64100-fd5e-11e9-897b-ac5ea1ce5483.png)
> 
> I'm restarting the playlist after removing the file. Let's see how it ends...

Guys, the mp3 file was actually causing the problem.
MPD stopped crashing after I re-encoded the mp3 file. Thanks for your help.
![image](https://user-images.githubusercontent.com/6069579/68213490-71d07e80-ffba-11e9-9053-e611b9e69cb2.png)

**Comment by MaxKellermann** [comment]
@thiagolamosa your posts are not helpful, unfortunately. None of them contain a backtrace. If you want this problem solved, post a backtrace.

**Comment by tmladek** [comment]
I would just like to add, since I originally reported the bug; it seems to have disappeared after I upgraded to the latest version and I would recommend the same. (Though I had to compile it myself, but the process is well documented)

**Comment by MaxKellermann** [comment]
> it seems to have disappeared after I upgraded to the latest version

That's why I usually refuse to even look at bug reports or help requests for outdated versions. This happens all the time. And yet people hate me for that attitude. Sigh.

**Comment by OpenGrid** [comment]
I just got this error at version 0.21.20

`mpd: ../src/player/Thread.cxx:799: void PlayerControl::PlayChunk(DetachedSong&, MusicChunkPtr, const AudioFormat&): Assertion `chunk->CheckFormat(format)' failed.`

**Comment by MaxKellermann** [comment]
> version 0.21.20

How annoying of you to complain about bugs in old versions, 3 years after I have already clarified that only the latest version is supported!
