### ISSUE TITLE
"list" command does not group when listing files

### ISSUE THREAD

**Issue by tarcisioe** [MusicPlayerDaemon/MPD#526]
Example: the command `list file group date` has the same output of `list file`. No dates are present, no grouping happens.

I was hoping to use `list file "(artist = '...')" group date group album` to easily create a list of every song by an artist in chronological order to add to the playlist. If there is a better way to do that, I would also like to know.

Unfortunately this along with #408 and the fact that `list file <filter> group date` outputs 

```
[ARG/2@0] {list} Unknown filter type
```

makes this usecase seemingly impossible.

I could try to help in fixing this, but I believe I would need a better understanding of what the `list` command is actually supposed to do and if it really should behave differently for `file`.

**Comment by MaxKellermann** [comment]
There's the `findadd` command which can sort in MPD 0.22 (git).
A note about "chronological order": `list` does not sort. It returns an arbitrary order.
But what you pointed out indeed is a bug; the `file` parameter is a special case in the MPD code which does not implement `group`.

**Comment by tarcisioe** [comment]
I see, grouping does not do sorting. I thought it would because it is a fairly straightforward way to group things. But can `findadd` sort by more than one criteria? And if it currently can't, would it be reasonable to add that feature? I could help with that.

**Comment by MaxKellermann** [comment]
It sorts by only one tag, but I'd welcome attempts to support multiple sort tags.
