### ISSUE TITLE
nfs build issue

### ISSUE THREAD

**Issue by riggs-** [MusicPlayerDaemon/MPD#527]
This is imho not an mpd bug, but maybe it's helpful in case other users have the same problem.
nfsc/libnfs.h fails to include sys/time.h where `struct timeval` is defined.
Subsequently, on systems, where this inclusion does not happen incidentally (e.g. FreeBSD), a workaround is to include sys/time.h before nfsc/libnfs.h in src/lib/nfs/Error.cxx

**Comment by MaxKellermann** [comment]
Better upgrade to a libnfs version without this bug. I don't like cluttering the MPD source code with tons of workarounds for buggy libraries. Just don't use known-buggy libraries.

**Comment by riggs-** [comment]
Totally agree. Just wanted to have this information documented in case someone else encounters the same problem.
