### ISSUE TITLE
SoundCloud

### ISSUE THREAD

**Issue by ki00** [MusicPlayerDaemon/MPD#53]
Is hard to play music with soundcloud, this appears (Cantata)

MPD ha informado del siguiente fallo: Failed to decode https://api.soundcloud.com/tracks/31289652/stream?client_id=0cb23dce4735…

If this had been reported, please close the thread. Thank you.

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by ki00** [comment]
[mpd.conf.zip](https://github.com/MusicPlayerDaemon/MPD/files/1033091/mpd.conf.zip)

**Comment by MaxKellermann** [comment]
Since you obviously didn't read the linked page, I'm closing this issue now.
