### ISSUE TITLE
MPD 'creating' a lot of TIME_WAIT connection?

### ISSUE THREAD

**Issue by gbrault** [MusicPlayerDaemon/MPD#531]
I have a lot of TIME_WAIT connections mentionning MPD. (MPD 0.19.0)

Same as https://www.linuxquestions.org/questions/linux-software-2/mpd-creating-lots-of-local-connections-4175628164/

Do you have any idea where it comes from?

Is it because one of my client doesn't close connection properly?

Thx!

PS: the software bundle (MPD + Mine) is working properly so...

**Comment by MaxKellermann** [comment]
This comes from your kernel's TCP stack and is its normal behavior and has nothing to do with MPD. If you have many of those, it means that many clients have connected (and disconnected) in the last few minutes. This is something you might want to check.
Note that MPD 0.19 is unsupported. All bug reports / questions about it will be closed without further investigation. If you want help with anything MPD related, you must use the latest version.
