### ISSUE TITLE
bluetooth crash in mpd 21.7 + BlueAlsa 1.3.1

### ISSUE THREAD

**Issue by gbrault** [MusicPlayerDaemon/MPD#534]
I have a configuration working well with mpd 0.19.21 and bleualsa 1.3.1. 

But, as recommended, I upgraded to latest mpd (21.7), mpc (0.31) and lib (2.16) compiling on latest (April) Raspbian and mpd crashes (just a crash message in syslog) when adding a BT device via mpc.
I work on a PI 3B plus.

I use an external BT dongle to avoid RPI built-in issues.
I had to compile Bluez  5.5, fdk-aac 2.0.2 and bluez-alsa 1.3.1 (1.4.0 has a socket issue at boot).

**Comment by MaxKellermann** [comment]
Your bug report contains no information at all about the crash. I need at least a full backtrace of the crash!

**Comment by gbrault** [comment]
I will do so, but for that I need to compile with debug as I have no other info in syslog except systemd telling mpd has crashed. Please let me some time to do that...

**Comment by MaxKellermann** [comment]
Since this bug report is completely useless without this information, let's close it and reopen it later.
