### ISSUE TITLE
Understanding interactions between single and repeat

### ISSUE THREAD

**Issue by DamienCassou** [MusicPlayerDaemon/MPD#539]
I'm the author of [mpdel](https://gitlab.petton.fr/mpdel/mpdel) an Emacs-based MPD client. I would like to add support for playback state, but I fail to understand exactly the interactions between the single and repeat modes. When `single=oneshot`:

1. if `repeat=0`, the playback stops after current song and sets `single` to `0`
2. if `repeat=1`, the current song is repeated forever and `single` is *never* set to `0`. 

Case 1 is similar to `single=1 & repeat=0` (except for the fact that `single` is set back to `0` in the former). I don't really see the point of it because in any way, the user will have to interact with the player to start another song and if he/she does, he/she can also set `single` to `0` manually.

Case 2 is exactly similar to `single=1 & repeat=1` so I also don't see the point of it. I would have expected `single=oneshot & repeat=1` to repeat the current song once and set `single` to `0` which would then play the next song in the playlist.

What are the use cases for `single=oneshot`?

**Comment by MaxKellermann** [comment]
`single=oneshot` was implemented by somebody who probably didn't know or care about interaction with `repeat=1`. What you see is a side effect which doesn't make sense, but it's undefined behavior, so why bother.
I don't know the use case for this option, but then again, I don't know the use case for any `single` mode. I've never used it, but I've also never used `repeat` or `random`. Unfortunately, the commit message (https://github.com/MusicPlayerDaemon/MPD/commit/1628d801f9534ab33a711d337cdd691dca2c5710) doesn't explain anything, neither does the contributor's documentation change. People want MPD to have the strangest options, and usually I tell them to implement it in the client - this option was one which barely passed my sanity check, so I merged the patch.

**Comment by arttuperala** [comment]
As someone who has implemented `single=oneshot` in a (dirty) client-side implementation, I can at least tell my use case for it. I personally don't really like pausing songs unless I really need to. So I try ending my playback right between songs, so I can enjoy them from beginning until the end. And if I'm working and I know I want to go get a drink/go to the bathroom/whatever, I set my player to stop playback after the current song and when playback ends, I take off my headphones and off I go. And when I come back, I just hit the play button on my keyboard and off I go again. I get everything in my queue without having to disable single state manually.

The only difference in my client-side implementation is that I stop the playback completely. I think it was mpdscribble or something else that liked to think I was still listening when the playback was just paused, but I can't really remember for sure now.

**Comment by Stephanowicz** [comment]
Hi,
my usecase: 
having a playlist...
single=1 & repeat=0 --> want to stop listening, but finish this song.
single=1 & repeat =1 --> want to listen to that song in loop, cause I love it sooo :D

even though I don't use it this much I'm glad it's possible.

Cheers, Stephan
