### ISSUE TITLE
"list file" is deprecated

### ISSUE THREAD

**Issue by geneticdrift** [MusicPlayerDaemon/MPD#541]
I suggest `list file` should not be deprecated.
It is useful when interested only in the file paths instead of the complete track info returned by `find`. For example to add all tracks from an artist to a playlist.

**Comment by MaxKellermann** [comment]
You can tell MPD to omit all tag values by specifying `tagtypes clear`, see https://www.musicpd.org/doc/html/protocol.html#connection-settings
