### ISSUE TITLE
Ability to swtich to dop and back without a retsart?

### ISSUE THREAD

**Issue by kiwi-ed** [MusicPlayerDaemon/MPD#544]
Hi,
Currently each time I want dop mode off or no I have to set it in my config and restart MPD. Can dop mode be switched some other way without a restart?

Also is a restart mandatory if the the wifi connection is lost and reestablished ( ip address not changed )?   

Thanks.

**Comment by MaxKellermann** [comment]
Already implemented using output attributes: https://www.musicpd.org/doc/html/plugins.html#alsa-plugin
