### ISSUE TITLE
Cannot install mpd with meson/ninja

### ISSUE THREAD

**Issue by LucioSantinelli** [MusicPlayerDaemon/MPD#546]
Hi, 
im working on a raspberry-pi model b+. 
I wanted to install mpd 0.21.8 but i always get some error during the installation with ninja. 
I have Meson installed in home/.local/bin version 0.50.1
and Ninja version 1.7.2
Im following the instruction in the User's manual of mpd and i fail last step 

ninja -C output/release install

This command  get me in a Authentication failure

If i try this command as sudo i get 

Import error: no module named 'mesonbuild'

**Comment by MaxKellermann** [comment]
This has nothing to do with MPD. You installed Meson in a user's home directory, and another user (i.e. root) can't use that Meson installation. Either root also needs to install Meson in his home directory, or you install it in the system folders for all users.

**Comment by LucioSantinelli** [comment]
Thanks anyway and sorry for my post.
