### ISSUE TITLE
snd_pcm_poll_descriptors_revents() failed: Invalid argument

### ISSUE THREAD

**Issue by ernibert** [MusicPlayerDaemon/MPD#548]
Hi,

I get "Failed to play on "ALSA Bluetooth Bridge" (alsa): snd_pcm_poll_descriptors_revents() failed: Invalid argument". The result is no sound via mpd. aplay itself can play perfectly on bluealsa so i assume thats something with mpd...

In my mpd.log. I've bluealsa+mpd running on a Raspberry, OS is ArchLinux. mpd is 0.21.8 and bluealsa is 1.4.0.

My alsa-config (/etc/asound.conf) is
=====
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "0C:A6:94:E9:14:A1"
defaults.bluealsa.profile "a2dp"
defaults.bluealsa.delay 10000

pcm.bluealsa {
  @args.HCI {
    type string
    default "hci0"
  }
  @args.DEV {
    type string
    default "0C:A6:94:E9:14:A1"
  }
  @args.PROFILE {
    type string
    default "a2dp"
  }
  type plug
  slave {
    pcm {
      type bluealsa
      device $DEV
      profile "a2dp"
    }
  }
  hint {
    show on
    description "bluealsa"
  }
}

ctl.bluealsa {
  type bluealsa
}
=====

and the mpd.conf looks like

=====
user                    "mpd"
pid_file                "/run/mpd/mpd.pid"
state_file              "/var/lib/mpd/mpdstate"

db_file                 "/mnt/hdd/mpd/mpd.db"
playlist_directory      "/mnt/hdd/mpd/playlists"

log_file                "/var/log/mpd.log"
log_level               "default"
#log_level              "verbose"

music_directory         "/mnt/hdd/data"
auto_update             "yes"

#volume_normalization   "yes"

audio_output {
        type            "alsa"
        name            "ALSA Bluetooth Bridge"
#       device          "bluealsa"
        device          "bluealsa:HCI=hci0,DEV=0C:A6:94:E9:14:A1,PROFILE=a2dp"
        mixer_type      "software"
#       auto_resample   "no"
#       auto_channels   "no"
#       auto_format     "no"
#       buffer_time     "500000"
#       period_time     "256000000"
#       format          "44100:16:2"
}
=====

All the variations which are commented out in mpd.conf has been tried but without success.

I must admit that i'm very low on knowledge about all that stuff so i hope someone could give me a hint...

**Comment by MaxKellermann** [comment]
This is a known bluez-alsa bug, see https://github.com/MusicPlayerDaemon/MPD/issues/432
