### ISSUE TITLE
jack audio output doesn't have software volume.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#549]
I want to control the volume level of MPD, but jack audio output doesn't have software volume control.

In mopidy, jack audio output doesn't disable software volume control.

Since jack audio connection kit occupies my sound devices, I should either use mopidy or bridge ALSA with jack.

I haven't yet been able to remove pop sounds from the bridge between ALSA and jack.

**Comment by MaxKellermann** [comment]
Let's clarify what you mean - you talk about software volume. MPD supports software volume on all audio outputs, see https://www.musicpd.org/doc/html/user.html#configuring-audio-outputs
Is that what you want? If not, what do you really want?

**Comment by crocket** [comment]
Oh, right. I misunderstood. I thought `mixer_type` was supported only by alsa output.
