### ISSUE TITLE
Wiki offline

### ISSUE THREAD

**Issue by Pimmetje** [MusicPlayerDaemon/MPD#55]
The wiki seems offline
http://mpd.wikia.com/wiki/Clients

As linked here: 
https://www.musicpd.org/clients/

Google cache still seems to hold a working version: http://webcache.googleusercontent.com/search?q=cache:_VLN-P8AZ4IJ:mpd.wikia.com/wiki/Clients+&cd=1&hl=en&ct=clnk&gl=nl&client=firefox-b-ab

**Comment by MaxKellermann** [comment]
That wiki is not associated with this project, therefore its status does not affect this project at all. It was full of confusing and misleading information - good riddance it's gone completely!

**Comment by Pimmetje** [comment]
@MaxKellermann Is https://www.musicpd.org/clients/ not related to the project?

**Comment by mer2329** [comment]
for the project to: link to an "unnoficial wiki, not maintain their list of clients, and then say good riddence its gone." says a lot about how the developers care.
the client page was a go to place to get a list of clients.

for now i have the clients page from the wiki added to my random pages.
https://sites.google.com/site/randompages33465/mpd-clients

**Comment by Pimmetje** [comment]
I still hope it will get fixed. In the meantime TWB machine is a good place
