### ISSUE TITLE
[CUE files]: 'PERFORMER' seems not being properly inherited 

### ISSUE THREAD

**Issue by nousernouser** [MusicPlayerDaemon/MPD#553]
**The problem**

When external CUE files playlists have 'PERFORMER' ('albumartist') in the disc (header) section, then the tracks without a specific 'PERFORMER' indication result having unknown 'artist' tags. 

Example -- I have the following CUE file playlist (note how 'PERFORMER' is only at the disc level and not is present for individual tracks):

~~~.text
REM DISCID "850aa60a"
REM GENRE "Folk"
REM DATE "1995"
PERFORMER "Dulce Pontes"
TITLE "A Brisa do Coração"
FILE "audiocd.flac" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
    TITLE "Os Índios Da Meia Praia"
  TRACK 02 AUDIO
    INDEX 01 05:35:00
    TITLE "Se Voaras Mais Perto"
  TRACK 03 AUDIO
    ...
...
~~~

and it results in (note how both 'artist' and 'performer' are empty):

~~~.text
$ mpc -f "%album%, %track%, %albumartist%, %artist%, %performer%"  current
A Brisa do Coração, 01, Dulce Pontes, , 
~~~

And this leads to bad weird situations in clients:

![ncmpcpp](https://user-images.githubusercontent.com/35839588/57733066-e3c8aa80-769e-11e9-9a78-3fb3c2a66c0c.png)

![cantata](https://user-images.githubusercontent.com/35839588/57733071-e925f500-769e-11e9-9fe4-680b2e61e63e.png)

**The probable cause**

I suppose the cause is that the tracks for which 'PERFORMER' is not present, do not inherit  'artist' from the 'PERFORMER' ('albumartist') in the disc section of the cuesheet (while 'performer' is correctly empty being not indicated at the track level in the cuesheet).

**The possible solution**

I suggest as a possible simple solution: 

- if a ***track HAS its own specific 'PERFORMER'*** in the cue, then the track should have this same specific 'PERFORMER' assigned to both 'performer' and 'artist' (ie: 'artist' inherits from 'performer' if this is not empty);

- if ***a track does NOT have a specific 'PERFORMER'*** in the cue, then the track should have an empty 'performer' and have set 'artist' = 'albumartist' (ie: 'artist' inherits from 'albumartist').

Thank you

**Comment by MaxKellermann** [comment]
cue's top-level "PERFORMER" maps to "AlbumArtist" in MPD. This works as designed.
You did not explain why this is a problem, therefore I cannot understand your suggested "solution".
What should probably be done is show this AlbumArtist tag in MPD clients.

**Comment by nousernouser** [comment]
> cue's top-level "PERFORMER" maps to "AlbumArtist" in MPD. This works as designed.
> You did not explain why this is a problem, 

Yes. Right. Indeed the above in not a problem.

But, the [CUESHEET specification](https://web.archive.org/web/20160201021136/http://digitalx.org/cue-sheet/syntax/#performer) also prescribes:

_"If the PERFORMER command appears before any TRACK commands, then the string will be encoded as the performer of the entire disc. If the command appears after a TRACK command, then the string will be encoded as the performer of the current track."_

and this kind of inheritancs do not seems to happen with mpd, leading some bad weird situations in clients when 'PERFORMER' is not present at cue's **track-level**.

> therefore I cannot understand your suggested "solution"

What I suggested is simply (during cue parsing): if a **track** does NOT have a specific 'PERFORMER' at the cue's track-level cue, then in teh mpd database the track should have an empty 'performer' and have 'artist' = 'albumartist' (ie: 'artist' inherits from 'albumartist').

> What should probably be done is show this AlbumArtist tag in MPD clients.

Maybe... But some clients show 'Artist' in the now playng view, and users can not change this behaviour...

Regards

**Comment by MaxKellermann** [comment]
> will be encoded as the performer of the entire disc

Which is what AlbumArtist means, doesn't it?

MPD's behavior is correct according to the CUE specification. And it's better than your "solution", because it solves an ambiguity in the specification in an elegant way: what if there's a PERFORMER both at disc level and at track level? MPD sets one as AlbumArtist and the other as Artist.

> some clients show 'Artist' in the now playng view, and users can not change this behaviour

Then you should ask those clients to improve this behavior. As for mpc and ncmpc, this is configurable by users, but after reading this issue report, I added AlbumArtist to the default format in both projects, which should be the default in all clients:
https://github.com/MusicPlayerDaemon/mpc/commit/fb4ba4834c762b847c4f10163cad1f1ea52e39cb
https://github.com/MusicPlayerDaemon/ncmpc/commit/3bb2b92bfa24285a20cce2ce2cc94408c861778f

**Comment by nousernouser** [comment]
> > will be encoded as the performer of the entire disc
> 
> Which is what AlbumArtist means, doesn't it?

Indeed.  But... what about the rest of the paragraph: _"If the command appears after a TRACK command, then the string will be encoded as the performer of the current track."_ ?

> MPD's behavior is correct according to the CUE specification. And it's better than your "solution", 

It's not "my" solution. It's the CUESHEET specification.

> because it solves an ambiguity in the specification in an elegant way: what if there's a PERFORMER both at disc level and at track level? MPD sets one as AlbumArtist and the other as Artist.

I totally agree with this (and in this situation maybe also better if PERFORMER at track level would be set as the track 'performer' in MPD).

 Anyway, this NOT resolve the loss of semantic consistency when there's a PERFORMER at disc level but NOT at track level: which results the track having 'albumartist' set, being _both_ 'artist' and 'performer' empty... That's why in this case the track's 'artist' should be inherited from 'albumartist' (and 'performer' let empty), as suggested by the second part of the statement in the specification.

> > some clients show 'Artist' in the now playng view, and users can not change this behaviour
> Then you should ask those clients to improve this behavior. 

Should not they read track's 'albumartist', 'artist' and 'performer' from the MPD database?

**Comment by MaxKellermann** [comment]
> Indeed. But... what about the rest of the paragraph: _"If the command appears after a TRACK command, then the string will be encoded as the performer of the current track."_ ?

I don't understand the question, because MPD does exactly that, and I have already explained it.

> > MPD's behavior is correct according to the CUE specification. And it's better than your "solution",
> 
> It's not "my" solution. It's the CUESHEET specification.

Yes, it is. See your "What I suggested is simply (during cue parsing): [...]" sentence. I explained why this is inferior, and you agreed.

> better if PERFORMER at track level would be set as the track 'performer' in MPD

This part is off-topic, but let me refer to https://github.com/MusicPlayerDaemon/MPD/commit/acaa725478ae5e6e4fff9e07cf8637d17d314c41 and https://web.archive.org/web/20151019171801/http://bugs.musicpd.org/view.php?id=3549
Further discussion about this in a different issue, please (if you disagree with that commit).

> And if 'albumartist' is set being _both_ 'artist' and 'performer' empty, the track will not be listed/found when grouping/searching for 'artist'...

MPD has tag fallbacks for AlbumArtist/Artist for exactly this reason. And it's even documented! See https://www.musicpd.org/doc/html/protocol.html#filters

> That's why in this case the track's 'artist' should be inherited from 'albumartist' (and 'performer' let empty), as suggested by the second part of the statement in the specification.

.. which is exactly what MPD does with its tag fallbacks!

> Yes. But why should not they use track's 'artist' and 'performer' from the MPD database in views such a artist or performer area in the now playing view?

I'm unable to parse this question.

**Comment by nousernouser** [comment]
First of all, thank you for your attention and explanations. And I'm sorry that I can't explain better what I mean.

So let me get back to the beginning. We have the CUE file of the example, where PERFORMER is indicated only at the top level, and not at the tracks level:
~~~ .text
...
PERFORMER "Dulce Pontes"
TITLE "A Brisa do Coração"
FILE "audiocd.flac" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
    TITLE "Os Índios Da Meia Praia"
  TRACK 02 AUDIO
   ...
~~~
when playing it:
~~~ .text
$ mpc -f "%album%, %track%, %albumartist%, %artist%, %performer%" current
A Brisa do Coração, 01, Dulce Pontes,,
~~~
where %albumartist% is present and has correctly taken the PERFORMER value from the top-level.

But what I would expect (even more so based on what you explained about the MPD implementation) would be that %artist% would also be set to the same value as %albumartist% (except, in the general case, if %albumartist% is' Various', but this is not the case of the example). I don't know why it happens, but this doesn't seem to be the expected behavior.

Still with reference to the example, %performer% is also empty but this is just as one would expect being PERFORMER not indicated at the track level.

I hope I have made it clearer what my concerns are.

Regards
