### ISSUE TITLE
mpd doesn't preserve extended m3u when it modifies playlist.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#554]
When I delete an entry in a playlist, extended m3u becomes plain m3u.
I want mpd to preserve extended m3u regardless of what I do to playlists.

Perhaps, https://github.com/MusicPlayerDaemon/MPD/issues/422 can be solved with this issue.

**Comment by MaxKellermann** [comment]
Those playlists are supposed to be managed only by MPD; its format is not defined, the current implementation just happens to use the plain m3u file format. If you edit files in this directory (or copy new files into it), that may or may not work. But MPD is not a full-featured playlist editor; it can ready fancy playlists in various formats, but its playlist directory is different. It's a simple listing of files, to be manipulated by MPD clients.
Is this a request to change this basic design?

**Comment by crocket** [comment]
Is the basic design to let MPD clients directly manipulate m3u files in playlist directory?

**Comment by MaxKellermann** [comment]
No, MPD clients (should) have no access to this directory; they may be remote, or may not have write permissions. These are edited by MPD, upon receiving commands from clients.
You can put any supported type of playlist into your music directory. There, MPD will never attempt to write them, but it can load them.

**Comment by crocket** [comment]
I just wanted to manage my expectations.
Can MPD read and edit .pls, .asx, and various other supported playlist file formats in playlist directory?
If so, then you could think about implementing data models required to manipulate icy-title charset in extended m3u from MPD clients.

But, I don't mind manually editing playlists.

**Comment by MaxKellermann** [comment]
See https://www.musicpd.org/doc/html/plugins.html#playlist-plugins

**Comment by crocket** [comment]
Oh, I finally understood. MPD supports

* Reading and writing plain m3u in playlist directory
* Reading extended m3u in playlist directory

Then, I shall keep manually editing m3u files in playlist directory since I don't want to lose stream titles.
