### ISSUE TITLE
Add support for http(s) as music storage when proxying database in a satellite setup

### ISSUE THREAD

**Issue by JerwuQu** [MusicPlayerDaemon/MPD#555]
If the mpd instance with the music library and the one accessing it are not on the same network, setting up NFS or SMB for hosting the raw files is, in my opinion, harder to get right than setting up a web server with basic auth such as `https://user:pass@example.com/music/...`.

This has some advantages over streaming using the `httpd` audio output, such as:
- Listening to the raw files instead of a re-encoded version
- Being able to share the music database and library with multiple people
- Possibly lower "action-to-change" latency because of not waiting for stream buffer

If http by itself is not enough (since it doesn't have proper directory tree listing), webdav could work.

**Comment by MaxKellermann** [comment]
This was implemented 2 years ago in commit 58fb36bdb9efc058061fa5b35bb910a759be4381

**Comment by JerwuQu** [comment]
Oh, my bad!

It wasn't listed in `mpd -V` for me, so I assumed it didn't exist, but of course it was simply that the distribution I was on didn't have support for it compiled in.

Apologies.
