### ISSUE TITLE
Single mode works unreliably in Nix and Guix packages

### ISSUE THREAD

**Issue by ajgrf** [MusicPlayerDaemon/MPD#556]
With single mode on (and repeat off), MPD doesn't reliably stop playback after a song finishes. Sometimes it stops, but other times it continues to the next song as if single mode were turned off.

I've run into this issue whenever I use the MPD package in [Nix](https://github.com/NixOS/nixpkgs/tree/master/pkgs/servers/mpd) or [Guix](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/mpd.scm). I'm reporting it here only after I realized that the same bug appears in both packages. That leads me to think it's some subtle upstream bug that, for some reason, only manifests itself when it's built with such an unusual filesystem hierarchy.

I run MPD as a user service with a very [barebones configuration](https://github.com/ajgrf/dotfiles/blob/master/.config/mpd/mpd.conf).

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by ajgrf** [comment]
mpd --version

    Music Player Daemon 0.21.8 (0.21.8)
    Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
    Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    Database plugins:
     simple proxy
    
    Storage plugins:
     local
    
    
    Decoders plugins:
     [vorbis] ogg oga
     [oggflac] ogg oga
     [flac] flac
     [opus] opus ogg oga
     [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
     [dsdiff] dff
     [dsf] dsf
     [hybrid_dsd] m4a
     [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
     [pcm]
    
    Filters:
     libsamplerate
    
    Tag plugins:
    
    
    Output plugins:
     null fifo pipe alsa ao pulse httpd recorder
    
    Encoder plugins:
     null vorbis opus lame wave flac
    
    Archive plugins:
     [bz2] bz2
    
    Input plugins:
     file archive alsa curl ffmpeg
    
    Playlist plugins:
     extm3u m3u pls flac cue embcue
    
    Protocols:
     file:// alsa:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://
    
    Other features:
     epoll icu inotify ipv6 tcp un

~/.config/mpd/mpd.conf

    music_directory    "~/music"
    playlist_directory "~/.local/share/mpd/playlists"
    db_file            "~/.local/share/mpd/database"
    log_file           "~/.local/share/mpd/log"
    pid_file           "~/.local/share/mpd/pid"
    state_file         "~/.local/share/mpd/state"
    sticker_file       "~/.local/share/mpd/sticker.sql"
    auto_update        "yes"
    #user               "nobody"
    #group              "nogroup"
    #bind_to_address    "any"
    #port               "6600"
    restore_paused     "yes"
    replaygain         "auto"
    #replaygain_preamp  "0"
    #replaygain_missing_preamp "0"
    #save_absolute_paths_in_playlists "no"
    
    audio_output {
        type "pulse"
        name "PulseAudio"
    }

Verbose log messages are attached from one instance where single mode was first honored, then ignored after the next song, then honored again, all without changing single mode.

[log.txt](https://github.com/MusicPlayerDaemon/MPD/files/3184034/log.txt)

May I suggest setting up [issue templates](https://help.github.com/en/articles/using-templates-to-encourage-high-quality-issues-and-pull-requests-in-your-repository) if you require a standard set of details in every bug report?

**Comment by MaxKellermann** [comment]
I've added an issue template, thanks for the hint. Previously I thought posting the version number would be common sense...

**Comment by ajgrf** [comment]
I'm still running into this bug after upgrading to 0.21.9. Let me know if there's any more information I can provide that would be useful.

Like I said before, I haven't encountered this bug using packages from any "normal" Linux distro, but it occurs frequently using the Nix or Guix packages. You can install the [Nix](https://nixos.org/nix/) or [Guix](https://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html#Binary-Installation) package manager on top of your existing distribution to try it out. Both packages are a little out of date, but I was able to upgrade on Guix by running this: 

    guix install --with-source=mpd@0.21.9=https://musicpd.org/download/mpd/0.21/mpd-0.21.9.tar.xz mpd
