### ISSUE TITLE
If bind_to_address is any, mpd tries to bind to the same address twice.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#557]
mpd-0.21.8

MPD configuration

```
music_directory "/data/music"
playlist_directory "/srv/mpd-pi/playlists"
db_file "/srv/mpd-pi/database"
log_file "/var/log/pi/mpd-pi.log"
log_level "default"
bind_to_address "any"
bind_to_address "@mpd"
auto_update "no"
audio_output {
  type "jack"
  name "jack"
  mixer_type "software"
  client_name "mpd"
  server_name "default"
  source_ports "out_1,out_2"
  destination_ports "system:playback_1,system:playback_2"
  autostart "no"
  always_on "yes"
}
filesystem_charset "UTF-8"
restore_paused "yes"
metadata_to_use "+comment"

default_permissions "read"
local_permissions "read,add,control,admin"
password "****@read,add,control,admin"
```

Error

```
May 16 20:09 : exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
```

If I replace `any` with `::`, `::` acts like `any`.
After binding to `[::]:6600`, binding to `0.0.0.0:6600` fails.

**Comment by MaxKellermann** [comment]
> If bind_to_address is any, mpd tries to bind to the same address twice.

That's not the same address. `0.0.0.0` is the IPv4 wildcard, and `::` is the IPv6 wildcard. These are different addresses, even different address families.

> If I replace `any` with `::`, `::` acts like `any`.

Not exactly correct. `::` acts only like `any` if your kernel decides to bind the IPv6 wildcard to IPv4 as well. For example, the Linux kernel does this if you set `/proc/sys/net/ipv6/bindv6only` to 0. If this option is enabled or if your Linux kernel was compiled without IPv6 support, the behavior is very different. On other (non-Linux) kernels, it may be a completely different story as well. What Linux does here is non-standard.

**Comment by crocket** [comment]
Right, `/proc/sys/net/ipv6/bindv6only` is already 0.

**Comment by crocket** [comment]
Perhaps, you want to enable `IPV6_V6ONLY` in socket. It seems that the default value for `/proc/sys/net/ipv6/bindv6only` is 0 according to `man ipv6`.

**Comment by MaxKellermann** [comment]
> Perhaps, you want to enable `IPV6_V6ONLY` in socket. It seems that the default value for `/proc/sys/net/ipv6/bindv6only` is 0 according to `man ipv6`.

But this would override the user's configured choice, which the user may be relying on.

Things aren't so simple. Ideas that sound good sometimes have bad consequences, and as a maintainer, I must be very cautious not to break somebody's existing setup. If there is global configuration, it should be obeyed by MPD, unless there are good reasons not to. (See https://xkcd.com/1172/)
