### ISSUE TITLE
database is created with mode 0666.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#558]
mpd-0.21.8

MPD configuration

```
music_directory "/srv/mpd-pi/music"
playlist_directory "/srv/mpd-pi/playlists"
db_file "/srv/mpd-pi/database"
log_file "/var/log/pi/mpd-pi.log"
log_level "verbose"
bind_to_address "::"
bind_to_address "@mpd"
auto_update "no"
audio_output {
  type "jack"
  name "jack"
  mixer_type "software"
  client_name "mpd"
  server_name "default"
  source_ports "out_1,out_2"
  destination_ports "system:playback_1,system:playback_2"
  autostart "no"
  always_on "yes"
}
filesystem_charset "UTF-8"
restore_paused "yes"
metadata_to_use "+comment"

default_permissions "read"
local_permissions "read,add,control,admin"
password "***@read,add,control,admin"
```

MPD is executed by an unprivileged user in a system service.

```
$ ls -lh /srv/mpd-pi
total 5.0K
-rw-rw-rw- 1 pi pi 229 May 16 22:06 database
drwxr-xr-x 2 pi pi   2 May 16 17:11 playlists/
```

How can I make it create database with mode 0644? It seems that umask is ignored.

**Comment by MaxKellermann** [comment]
I can reproduce this problem. With `O_TMPFILE`, the Linux kernel appears to ignore the umask. According to the documentation, `open()` **must** apply the umask:
> The effective mode is modified by the process's umask in the usual way

I can't see MPD doing anything wrong here, and I consider this a kernel bug.

**Comment by crocket** [comment]
How should I report the kernel bug, then?

**Comment by crocket** [comment]
I reported an issue on https://bugzilla.kernel.org/show_bug.cgi?id=203625

https://github.com/MusicPlayerDaemon/MPD/blob/2cf6b776276b4e09784449bd97fe71af61bb5a1e/src/fs/io/FileOutputStream.cxx#L176-L215

In this code fragment, I can see that `OpenCreate` first tries opening a file without `O_CREAT`. Perhaps, is the problem that mpd tries opening a file without `O_CREAT`? `O_CREAT` is tried when mpd falls back to plain POSIX. I suspect that without `O_CREAT`, `open` doesn't honor umask.

I found

> The effective mode is modified by the process's umask in the usual way

in the section for `O_CREAT`. The section for `O_TMPFILE` doesn't explicitly state that it honors umask.

By the way, `O_TMPFILE` seems to honor default ACLs.

**Comment by MaxKellermann** [comment]
> In this code fragment, I can see that `OpenCreate` first tries opening a file with `O_TMPFILE` and then with `O_CREAT`.

This is a fallback, because not all filesystems (and Linux kernel versions) support `O_TMPFILE`.

> I found
> 
> > The effective mode is modified by the process's umask in the usual way
> 
> in the section for `O_CREAT`. The section for `O_TMPFILE` doesn't explicitly state that it honors umask.

True, but this paragraph is about both flags.

> `O_TMPFILE` honors default posix ACLs. I set default posix ACLs as below.

Just like `O_CREAT`.

> Perhaps, `O_TMPFILE` is supposed to ignore umask?

Maybe. If that's the outcome, the `open()` manpage should be updated to mention this in an unambiguous way. And then I'll fix this MPD bug (which is then really a bug).

**Comment by MaxKellermann** [comment]
> Perhaps, `O_TMPFILE` is supposed to ignore umask?

Btw. that would pose a serious problem for MPD; MPD would then have to apply the umask manually, but there is no reliable (race-free) way to query the umask.

**Comment by crocket** [comment]
https://bugs.gentoo.org/686142 requests a minimal C example, and I don't know how to write C.

Can you provide me with a minimal C example of O_TMPFILE?

**Comment by MaxKellermann** [comment]
Meanwhile, somebody else has written a test program: https://bugs.gentoo.org/show_bug.cgi?id=686142#c3
(I don't have an account there, and not being a Gentoo user, I don't like to create one now.)
It fails on my computer; this is on a tmpfs:
```
current umask = 022
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
```
And this is on ext4:
```
current umask = 022
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
```
XFS:
```
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100777
stat():  in_mode=0777, resulting_mode=0100777
```

On another computer with a distribution standard kernel (which, unlike the kernels above, has ACL support); btrfs:
```
current umask = 022
fstat(): in_mode=0777, resulting_mode=0100755
stat():  in_mode=0777, resulting_mode=0100755
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100700
stat():  in_mode=0777, resulting_mode=0100700
```
And tmpfs:
```
current umask = 022
fstat(): in_mode=0777, resulting_mode=0100755
stat():  in_mode=0777, resulting_mode=0100755
current umask = 077
fstat(): in_mode=0777, resulting_mode=0100700
stat():  in_mode=0777, resulting_mode=0100700
```
My theory is that this has to do with kernel ACL support. What kernel are you using?

**Comment by MaxKellermann** [comment]
Fixes submitted:
https://lore.kernel.org/patchwork/patch/1096965/
https://lore.kernel.org/patchwork/patch/1096962/
https://lore.kernel.org/patchwork/patch/1096963/
https://lore.kernel.org/patchwork/patch/1096961/

**Comment by crocket** [comment]
$ uname -r
4.19.52-gentoo


[config.txt](https://github.com/MusicPlayerDaemon/MPD/files/3355453/config.txt)

**Comment by MaxKellermann** [comment]
Uh, you're using an out-of-tree filesystem, but you reported the bug to the upstream kernel bug tracker... you should have mentioned that!
Unfortunately, applying the umask needs to be done in every filesystem. Several in-tree filesystems had this bug, and maybe ZFS has a similar bug, but I don't know (I've never used ZFS, and probably never will).
In any case, I'm still very confident this isn't a MPD bug. And while my patches fix several similar kernel/filesystem bugs, it is likely that those don't solve your problem, and the ZFS projects need to do another fix.

**Comment by crocket** [comment]
On the issue tracker, I reported that I use mpd on zfs.
