### ISSUE TITLE
Some radio streams freeze mpd.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#561]
For example

* mms://112.221.163.203:8000
* mms://211.220.195.199/viewradio
* ....

When they are played, mpd stops responding to commands.
It stops responding to SIGTERM. I have to kill mpd with SIGKILL.

**Comment by MaxKellermann** [comment]
Those IPs do not respond, which means libmms emits a TCP connect which blocks for a long time, until the SYN timeout expires. MPD however has no chance to cancel this connect operation because libmms does not allow cancellation. Sorry, this is how libmms works, unfortunately.

**Comment by crocket** [comment]
Is it possible to configure libmms timeout from mpd?

**Comment by MaxKellermann** [comment]
No, libmms has no way to specify a timeout. And it already runs in a separate thread, but that doesn't help; at some point, MPD has to ensure that it isn't running anymore, so it has to wait for that libmms thread to finish. And no, threads cannot be killed like processes; threads share the memory space with the rest of MPD, and if you kill it, you leave the whole process in an undefined state.
The problem is that libmms is a badly designed library, and as long as we use libmms, we can't work around this.

**Comment by crocket** [comment]
ffmpeg supports mms, and mpd already uses ffmpeg. Perhaps, ffmpeg's mms support is better?

**Comment by MaxKellermann** [comment]
Unfortunately not. FFmpeg's libavio library supports only synchronous operation as well; just like with libmms, there is no way to cancel a blocking operation.

**Comment by crocket** [comment]
At least, https://ffmpeg.org/ffmpeg-protocols.html#Protocols states

```
All protocols accept the following options:

rw_timeout
Maximum time to wait for (network) read/write operations to complete, in microseconds.
```

**Comment by MaxKellermann** [comment]
True, FFmpeg has a configurable timeout. That's slightly less bad, but still not good: timeout too high means MPD freezes, timeout too low means slow servers fail. Doesn't solve the problem, just makes some of it less visible.

**Comment by crocket** [comment]
Since libmms doesn't have a definite timeout, it can time out after 2 hours.
A hard-coded timeout of 20 seconds is a good start.
You can also make the timeout a configurable variable in mpd.conf

**Comment by crocket** [comment]
I measured the timeout. Timeout occurred in a few minutes.
According to mopidy developers, it's common for MPC clients to allow users to configure connection timeout. Other web pages also say that connection timeout should be set in application.

Allowing users to configure timeout might be the way.
