### ISSUE TITLE
Inactive plugins 'tidal' and 'Qobuz' generate exceptions

### ISSUE THREAD

**Issue by th0rn** [MusicPlayerDaemon/MPD#565]
## Bug report

mpd gives errors on startup about optional, unconfigured plugins.

### Describe the bug

Starting mpd in regular non-verbose mode always generates errors about optional plugins, even if those plugins are completely unconfigured. Only way to start mpd without errors is presumably by configuring plugins that are supposed to be optional.

## Expected Behavior

mpd would start without errors.

## Actual Behavior

Starting mpd gives the following errors:

exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured

## Version

Music Player Daemon 0.21.9 (0.21.9)

## Log

N/A

**Comment by MaxKellermann** [comment]
Both plugins are optional. The log message is there to inform you that the plugins were enabled at compile time, but are not available at runtime. MPD startup continues as usual, and you can use it.
So, .... what really bothers you? Do you wish MPD to never log informational messages when a plugin is unavailable at runtime? I don't understand.

**Comment by th0rn** [comment]
Thanks for the fast reply.

> Do you wish MPD to never log informational messages when a plugin is unavailable at runtime? I don't understand.

Yes, this is correct. mpd has both, a "--verbose" and a "--stderr" flag. It is only reasonable to expect that starting the program in non-verbose mode without asking to print messages to stderr would not produce error messages unless it indicated some problem. Currently there's no obvious way to setup mpd to only print actual errors requiring intervention into stderr without also printing informational messages about available plugins.

> Do you wish MPD to never log informational messages when a plugin is unavailable at runtime?

Well, currently it's the other way around - there is no way to disable informational messages. One would expect these errors to be produced for instance when the plugins were configured but failed to start, etc. And there is a "--verbose" flag but there is no "--quiet" flag, so while the program runs at a fairly verbose info level to start off with, the only option is to make it even more verbose.

Prefixing informational messages about available plugins with "exception:" is confusing in its own right, and printing such messages into stderr is highly unusual/counterintuitive - I cannot see any compelling reason to need to confuse users like this. The cherry on top, so to speak, is that these informational messages about additional features are not only enabled by default, but cannot be disabled at all.

**Comment by MaxKellermann** [comment]
There's no `--quiet`, but there's the `log_level` setting. `--verbose` is just a shortcut which overrides the `log_level` setting.

But I agree that MPD should be less verbose in the default setting. Though there needs to be a difference between "plugin unavailable due to library initialization error" (which is bad) and "plugin unavailable because it was not configured" (not quite noteworthy).

**Comment by th0rn** [comment]
Right, absolutely, I think we're on the same page. Thanks for the tip and the fast reply!

**Comment by craigbarnes** [comment]
I think the problem isn't the logging itself but the fact the message begins with `exception:`. It's not surprising that people think it indicates a bug, given what "exception" means in other contexts.
