### ISSUE TITLE
Non-exist folder corrupts database update functionality

### ISSUE THREAD

**Issue by ykelvis** [MusicPlayerDaemon/MPD#57]
If a folder in Music Library no longer exist, "update database" will throw an exception,  `exception: Failed to access ${Folder}: No such file or directory`,  and the update procedure stops, cannot update database as usual.

Expected behavior: delete those entries in mpd.database(they don't exists any more), or simply pass/ignore.

Sys info: OSX 10.12.4
Mpd ver: Music Player Daemon 0.20.8

**Comment by MaxKellermann** [comment]
Duplicate of #41 and #58 (which have a better technical explanation).
