### ISSUE TITLE
TIDAL 

### ISSUE THREAD

**Issue by marcbth** [MusicPlayerDaemon/MPD#571]
### Describe the bug
Cant Play TIDAL song

## Version

Mpd 0.21.9

## Log

un 01 21:22 : exception: avformat_open_input() failed: Invalid data found when$
Jun 01 21:22 : exception: Error from Tidal: Asset is not ready for playback
Jun 01 21:22 : player: played "tidal://track/51771417"
Jun 01 21:22 : client: [907] opened from 127.0.0.1:46094

**Comment by marcbth** [comment]
another

Jun 03 20:32 : exception: Failed to scan tags of 'tidal://track/391651': Error $
Jun 03 20:33 : client: [46] opened from 127.0.0.1:56558
Jun 03 20:33 : client: [46] closed
Jun 03 20:33 : client: [47] opened from 127.0.0.1:56560
Jun 03 20:33 : client: [48] opened from 127.0.0.1:56562
Jun 03 20:33 : client: [47] closed
Jun 03 20:33 : client: [49] opened from 127.0.0.1:56564
Jun 03 20:33 : client: [48] closed
Jun 03 20:33 : client: [49] closed
Jun 03 20:33 : exception: avformat_open_input() failed: Invalid data found when$
Jun 03 20:33 : exception: Error from Tidal: Asset is not ready for playback
Jun 03 20:33 : player: played "tidal://track/391651"
Jun 03 20:33 : client: [50] opened from 127.0.0.1:56568
Jun 03 20:33 : client: [51] opened from 127.0.0.1:56570

**Comment by marcbth** [comment]
tidal: Login successful, session=5574ceb2-5223-4475-9e08-b966fb114be1
exception: Failed to decode tidal://track/10565654
player: played "tidal://track/10565654"
playlist: stop
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1

**Comment by marcbth** [comment]
/var/log# mpd --stdout --no-daemon --verbose
config_file: loading file /etc/mpd.conf
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg
adplug: adplug 2.2.1
simple_db: reading DB
exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured
curl: version 7.64.0
curl: with GnuTLS/3.6.7
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player @ soul10
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
avahi: Service group changed to state 2
avahi: Service 'Music Player @ soul10' successfully established.

**Comment by marcbth** [comment]
tidal: Login successful, session=3dcd84b6-4772-4e78-9720-6f506eb80461
decoder_thread: probing plugin ffmpeg
exception: avformat_open_input() failed: Invalid data found when processing input

**Comment by MaxKellermann** [comment]
I can play this song just fine.
Your log messages are truncated. Please post the full Tidal/FFmpeg error messages.
What's your FFmpeg version?

**Comment by MaxKellermann** [comment]
The unmaintained Tidal plugin has been removed, rendering this bug report obsolete.
