### ISSUE TITLE
output/httpd: blacklist some well-known request paths

### ISSUE THREAD

**Issue by cathugger** [MusicPlayerDaemon/MPD#572]
## Feature request
Currently mpd's httpd output plugin will serve music stream regardless of path requested.
This is usually okay and is pretty handy.
However, it behaves poorly when combined with some software which expects either fixed-sized content or "not found" response requesting some well known paths.
Namely, on firefox 67, when I open url like `http://mympdaddress/play.opus`, it additionally requests for `/favicon.ico`. mpd just returns endless audio stream, and firefox seems to be too silly to figure out that it's not icon of any kind and just continues accepting it.
So now instead of just single audio stream, firefox keeps accepting 2 streams, doubling bandwidth used.
I believe that serving anything at all for paths like these is undesirable for mpd, because various kinds of software (browsers, web spiders, crawlers) can hit mpd httpd with requests for stuff like `robots.txt`, `favicon.ico`, `sitemap.xml`, and not be fully prepared to handle endless stream mpd throws at them.
Therefore, I propose returning `404 not found` for `/favicon.ico`, `/robots.txt`, `/sitemap.xml` (de facto) and `/.well-known/*` (specified in [RFC 8615](https://tools.ietf.org/html/rfc8615)) paths.

I can make PR if this proposal makes sense.

**Comment by MaxKellermann** [comment]
Yes, why not. This could be in the stable branch (v0.21.x)

**Comment by cathugger** [comment]
https://github.com/MusicPlayerDaemon/MPD/pull/573
wasn't exactly sure against which branch to base on, but I think it shouldn't be issue to cherry-pick it for stable branch
