### ISSUE TITLE
dsf files do not play with mpd 021.x

### ISSUE THREAD

**Issue by rikmnet** [MusicPlayerDaemon/MPD#574]
<!-- Before you ask a question on GitHub, please read MPD's
documentation.

## Question

have been thru the docs and have been using mpd for a while and it has been mostly stable and reliable,  the problem now is what has been mentioned in another report about mpd 21 and ARM -- and DSD files will not play any more on Fedora x64 f29 or f30 either

the latest rev of mpd [ 21.9 ] is actually available in the fedora repo and while I can't get it to compile the fedora maintainers upstream obviously have, and it still will not play .dsf files

the log shows what it usually does when a DSD file plays, and /proc/asound looks right but on several different stereos and DSD capable DACs, it is just hiss static white noise

so I agree with the other user who said DSD was broken with 21.x on ARM, and that it is a change from 20.x, which was working as expected on Fedora 29 x64, until sometime before the upgrade to f30... and it has not been resolved with the move to f30 and mpd 021.9

I am thinking that there is a Debian vs. Fedora thing going on with the new build system, but I compiled earlier versions of 21x with the SACD iso patch and the old automake system, just to check...they all compiled when sndio was excluded, but they will not play dsf either

thanks for reading, and please let me know if anyone can think of anything, or if I can supply logs or other info that would help

**Comment by MaxKellermann** [comment]
Yes they do.
