### ISSUE TITLE
Expose Grouping from other metadata schemes besides ID3, re issue #563

### ISSUE THREAD

**Issue by TheOldPresbyope** [MusicPlayerDaemon/MPD#576]
Issue #563 was closed with commit 319c969 but this extracts the new metadata tag value only from ID3-tagged source. Could we please extend this to include other major tagging schemes? I'm most concerned about the Vorbis Comments in my FLAC files but I'm sure other MPD users have their favorites.

The metadata editors I'm aware of equate the ID3 TIT1 (grouping) with the following

scheme | name
-----------|-----------
APEv2 | GROUPING
ASF/WMA | WM/ContentGroupDescription
iTunes/MP4 | (at)grp
Ogg/Vorbis Comment (FLAC)  | GROUPING

(A useful cross-reference table can be found at, e.g., https://picard.musicbrainz.org/docs/mappings/)

I'm uncertain about the exact encoding in iTunes/MP4. As well, I used (at) to represent the "at" symbol (which github wants to interpret).

**Comment by MaxKellermann** [comment]
> but this extracts the new metadata tag value only from ID3-tagged source

Demonstrate that this assertion is true.

**Comment by MaxKellermann** [comment]
Closing due to lack of feedback.
