### ISSUE TITLE
Expose metadata "work" from MPD, re issues #576, #563

### ISSUE THREAD

**Issue by TheOldPresbyope** [MusicPlayerDaemon/MPD#577]
The metadata concept "work" is a specialization of "grouping". The concept of a work is so important to classical music that most metadata schemes include it specifically. ID3 is the odd man out, with only TIT1 specifically defined.

It would be beneficial to those of us MPD users with extensive classical music collections if a new MPD metadata tag "work" were defined.

Drawing again from the convenient table at https://picard.musicbrainz.org/docs/mappings/

scheme | name
----------|---------
APEv2 | WORK
ID3v2 | TXXX:WORK
Ogg/Vorbis | WORK
iTunes MP4 | (at)wrk

where again I'm uncertain of the specific encoding in WP4 and I used (at) to represent the at-sign.

I'm aware that some folks have used ID3/TIT1 to represent "work". I don't know how to resolve the ambiguity other than to suggest they mass-edit their files to use TXXX:WORK (but only if this new tag is added to MPD).

**Comment by MaxKellermann** [comment]
You request something, but omit its definition.
You should also explain why none of the existing tags are useful for this, e.g. "album" or "grouping".

**Comment by TheOldPresbyope** [comment]
ref: [https://musicbrainz.org/doc/Work](url) 

> a work is a distinct intellectual or artistic creation, which can be expressed in the form of one or more audio recordings.

And, of course, Music Brainz has an id for it: musicbrainz_workid	(Work Name MusicBrainz Identifier)

"Composition" and "work" are often used interchangeably. They may consist of one or more parts such as movements, acts and scenes (in an opera), etc. These parts are typically recorded as separate tracks.

### Examples of works:
#### Classical:
* Symphony No. 5 (composer: L.v. Beethoven)
#### Jazz:
* Perceptions (composer: J.J. Johnson)
#### Rock:
* Tommy (composer: P. Townsend and the Who)

In creating their metadata, classical music fans have sometimes used "album" to mean "work" because of the ID3 straitjacket but this is a perversion. In the world of classical music recordings, albums may contain only one work but frequently contain more than one. At the moment, I'm listening to a Philips album containing three of J. S. Bach's Brandenburg Concertos performed by Sir Neville Marriner leading the Acadamy of St. Martin of the Fields orchestra.

Sure, "grouping" can be used to represent "work", just as it could be used to represent "album", That might even sound sensical to a database designer but it's nonsensical musically.
