### ISSUE TITLE
Library updating, clang and __attribute__((pure))

### ISSUE THREAD

**Issue by riggs-** [MusicPlayerDaemon/MPD#58]
While testing 0.20.8 for the FreeBSD ports tree, I noticed that the fix in issue #41 did not fix the library updating problem, i.e. the following still does not work:

1. rm /path/to/file/in/library/song.ogg
2. issue mpd update command

mpd will log the file not found exception in its log and stop scanning the library. The removed song continues to be listed as part of the library.
As a workaround, I continue to use https://svnweb.freebsd.org/ports/head/audio/musicpd/files/patch-src_Compiler.h?revision=440334&view=co for now.

**Comment by MaxKellermann** [comment]
So my clang plugins missed lots and lots of function declarations, and many invalid `pure` attributes remained. The problem here is `StorageDirectoryReader::GetInfo()` and `Storage::GetInfo()`.
