### ISSUE TITLE
Random crash with mpd

### ISSUE THREAD

**Issue by Newbie13XD** [MusicPlayerDaemon/MPD#580]
### Describe the bug
mpd crashed, seemingly at random, while I was playing music. Unfortunately I'm not entirely sure about what it was doing when it happened, and neither am I sure about how to reproduce it. I'll be sure to update this if I find out more.

Side note: I'm on Fedora 30 Workstation, using Cantata as my frontend for mpd. 

## Expected Behavior
I expected it to play music. 

## Actual Behavior
Crashed.

## Version

[mpdversion.txt](https://github.com/MusicPlayerDaemon/MPD/files/3272515/mpdversion.txt)

## Log

[mpdlog-systemd.txt](https://github.com/MusicPlayerDaemon/MPD/files/3272529/mpdlog-systemd.txt)
[mpd.log-excerpt.txt](https://github.com/MusicPlayerDaemon/MPD/files/3272537/mpd.log-excerpt.txt)

mpdlog-system.txt contains the error that `systemctl --user status mpd` gave me, while mpd-log-excerpt.txt contains the parts of the log near when it happened (16:42). You may note that the mpd.log-excerpt.txt contains things that occurred after that time, and it's because I accidentally ran `mpd` before getting the log (I think).

**Comment by MaxKellermann** [comment]
Your MPD version is outdated.
