### ISSUE TITLE
MPD crashes when changing songs.

### ISSUE THREAD

**Issue by r3valkyrie** [MusicPlayerDaemon/MPD#584]
### Describe the bug
MPD does start successfully, but it crashes while changing songs. It does not matter which client I've used to change the songs, the MPD server consistently crashes. I am listening to multiple mp3 streams over http.

I just noticed this happening today. 

## Expected Behavior
MPD should switch songs without crashing.

## Actual Behavior
MPD immediately crashes upon switching songs.

## Version
[0.21.10-348](http://paste.debian.net/1088124/)

## Log
Here is [the relevant backtrace](http://paste.debian.net/1088233/). There's also this [core dump](http://paste.debian.net/1088008/) in the systemd journals. Stderr just gave me a bus error.

**Comment by MaxKellermann** [comment]
There is no backtrace at all! Did you forget to do the `bt` command in the gdb command prompt?

**Comment by r3valkyrie** [comment]
Sorry about that, I think I did leave that out. I will fix it when I'm home.

**Comment by r3valkyrie** [comment]
Updated with the actual backtrace.

**Comment by MaxKellermann** [comment]
Now your backtrace shows a different kind of crash. Previously, this was an assertion failure, but there's no `assert()` call at src/event/Loop.cxx:69:
https://github.com/MusicPlayerDaemon/MPD/blob/aebb1baad/src/event/Loop.cxx#L69
In the backtrace, some important values are `<optimized out>`, but even without those values, I guess I need more information.
How can I reproduce your problem?

**Comment by r3valkyrie** [comment]
It looks like that backtrace was from the most recent git version of MPD. I was a bit sloppy while troubleshooting this, and I must have pasted a backtrace from the latest git version of MPD, rather than 0.21.10. I'm going to go ahead and correct this. Very sorry about that.

As for reproducing the issue, I'm on Archlabs, kernel 5.1.9-arch1-1-ARCH, MPD version 0.21.10. Step the reproduce are:

1. Launch MPD through systemd --user mode, or directly from the command line.
2. Run `mpc play`, music should begin playing.
3. Run `mpc next`, the MPD server will crash and output `mpd error: Not playing`.

**Comment by MaxKellermann** [comment]
When I run `mpc play` or `mpc next`, I get an error, because my queue is empty. Please describe how to set up the queue in order to reproduce this.

**Comment by MaxKellermann** [comment]
> #0  0x0000555555624b26 in ?? ()

Your updated backtrace is useless because your MPD binary is stripped.

**Comment by r3valkyrie** [comment]
Would you like me to use the backtrace for the git version instead? It's basically the same issue, but with a different crash.

Here's the instructions for the queue:

1. `mpc add "http://live-mp3-128.kexp.org:8000/kexp128.mp3"
2. `mpc add "http://c2409ic1.fast-serv.com/stream"

**Comment by MaxKellermann** [comment]
Can't reproduce with these URLs. It plays as expected.
Please try this branch (based on v0.21.x): https://github.com/MusicPlayerDaemon/MPD/tree/dump_curl_socket
After the crash, upload the log (it prints various debugging statements to stderr) and the backtrace.

**Comment by r3valkyrie** [comment]
[Log](http://paste.debian.net/1088243/)
[Backtrace](http://paste.debian.net/1088244/)

**Comment by MaxKellermann** [comment]
Thanks, that was very helpful.
Unfortunately, I cannot help you because this turns out to be a bug in CURL. From your log:
```
CurlSocket::SocketFunction s=14 action=2 userp=0x55555572c4a0 socketp=(nil)
  Assign 0x7fffd4007b50
CurlSocket::SocketFunction s=14 action=1 userp=0x55555572c4a0 socketp=0x7fffd4007b50
[...]
CurlSocket::SocketFunction s=14 action=4 userp=0x55555572c4a0 socketp=0x7fffd4007b50
[...]
CurlSocket::SocketFunction s=14 action=3 userp=0x55555572c4a0 socketp=0x7fffd4007b50
```
The first line registers the socket `14` in MPD's I/O event loop, and MPD assigns it. `action=1` changes monitoring from `OUT` to `IN` (receiving instead of sending). Then `action=4` unregisters the socket ("[The specified socket/file descriptor is no longer used by libcurl](https://curl.haxx.se/libcurl/c/CURLMOPT_SOCKETFUNCTION.html)").
Now **after** that, CURL uses the socket again (`action=3`), passing MPD the `socketp` pointer which however was already freed by MPD. Using the freed memory now causes the crash, because that pointer contains garbage now.
Report this bug to the [CURL project](https://github.com/curl/curl/issues/)

**Comment by r3valkyrie** [comment]
Thank you for your help! I will do that.
