### ISSUE TITLE
MPD on Qnap QTS 4.3+

### ISSUE THREAD

**Issue by Mindsage** [MusicPlayerDaemon/MPD#586]
I have a QNAP TS-453Be - mpd runs but audio comes out of the built in speaker, I would like it to come out of HDMI so that I can send it to my receiver. 

via telnet and command line, issuing this command: 
`aplay -D hdmi:CARD=Intel,DEV=0 /opt/test.wav `

i get sound via HDMI output (which is what I want). 
Also with: 
`aplay -D hw:0,3 /opt/test.wav    `
works. but none of these work with mpd.conf in the audio_output for device. I get: Failed to open Alsa device 'default' no such file or directory. 

```
audio_output{
type "alsa"
name "default"
device "hw:0,3" 
}
```

In /opt/MPD/etc/mpd.conf device hw:0,0 does not work either, same error: Failed to open Alsa device 'default' no such file or directory. 

Commenting out the whole section directs output to the integrated speaker.

I do not have QNAPs HybridDeskStation installed (shouldn't need to). There is no pulse audio on this. I have tried setting defaults via asound.conf, and alsa.conf and . asoundrc mpd totally ignores them all. alsa - D obeys them all. 

Where is MPD getting its "default" output device config from?

Any help or insight would be appreciated to get this running out the desired output!

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/
