### ISSUE TITLE
Wildmidi can use freepats.cfg by default but mpd with freepaths installed can't 

### ISSUE THREAD

**Issue by i30817** [MusicPlayerDaemon/MPD#589]
### Describe the bug

It's as i wrote in the title. At first i thought it was because of a bogus timidity.cfg, but timidity wasn't installed at all (i dislike unnecessary daemons), just the soundfonts and wildmidi played midi files. Then i changed the conf file that wildmidi was using in mpd.conf to freepaths and it started playing.

## Expected Behavior

There is some unnecessary confusion here. As a user, I'd *prefer* some kind of transparent hierarchy of soundfont files used if there was none, ie: fluidr3_gs.cfg > fluidr3_gm.cfg > freepats.cfg > timidity.cfg and reporting each step as visible info on startup, not 'log info'.

Also i tried to replace the file by a timidity.cfg i had laying around for exult (it bundles timidity), and although it works on exult, it doesn't in mpd and it reports no missing timidity, so in addition to the above logging apparently there is the danger of parsing going wrong in wildmidi but mpd thinking everything is just fine. My next step is to try out the fluidsyth cfgs.

## Version
Music Player Daemon 0.21.4 (0.21.4)

## Log
(the 'actual section' was actually near impossible to find since the log file was growing so huge i moved it to tmp and i'm looking for a way to disable it altogether - i don't appreciate daemons writing 500mb files to disk, so i'll demur from pasting it).

**Comment by MaxKellermann** [comment]
I don't understand your text. The section "expected behavior" doesn't describe any expected behavior. Please rephrase.
And don't complain about the large log file here. This is off-topic and causes further confusion. If you believe MPD writes too much log, write a separate issue.

**Comment by MaxKellermann** [comment]
Also note that your MPD version is 6 bugfix releases behind. Even if this is a bug, and even if I fix it, you won't get the fix for the same reasons you're now not using the latest version.

**Comment by i30817** [comment]
> I don't understand your text. The section "expected behavior" doesn't describe any expected behavior. Please rephrase.
MPD does warn it doesn't find the required cfg file, but it apparently doesn't check if wildmidi can actually consume it (can it? With the return value of a subprocess that is?). Even 'worse' if we pass - what is apparently a invalid timidity.cfg file for this combination of wildmidi and timidity - it thinks midi is working and reports no error at all.

Since i *don't* actually have a timidity.cfg on the expected /etc/timidity/timidity.cfg location, wildmidi is (probably) using the freepats.cfg on the same directory installed by the freepats soundfount (installed when exult was installed by the ppa package i maintain).

>  And don't complain about the large log file here. This is off-topic and causes further confusion. If you believe MPD writes too much log, write a separate issue.
Sure.

**Comment by MaxKellermann** [comment]
> MPD does warn it doesn't find the required cfg file, but it apparently doesn't check if wildmidi can actually consume it

MPD checks the return value of `WildMidi_Init()`. What else do you expect MPD to do?

> Even 'worse' if we pass - what is apparently a invalid timidity.cfg file for this combination of wildmidi and timidity - it thinks midi is working and reports no error at all.

How do you expect MPD to learn about an error condition, if not from the `WildMidi_Init()` return value?

**Comment by i30817** [comment]
Don't shoot the messenger (-: , 

Try it out yourself. (if you can afford the time), apt-purge timidity ; install freepats and wildmidi and watch it run and mpd fail.

**Comment by MaxKellermann** [comment]
That's because wildmidi's example player uses a different default path. Which you can configure in MPD as well. But that's not what your bug report is about, is it?

**Comment by i30817** [comment]
If you don't want to report upstream that your usage of their api revealed a bug where they report success when it's actually failing, just say so and i'll open it myself shessh. I didn't even *know* how you used wildmidi before you told me you were using the library (i've seen exult using a subprocess to play audio before, with predictable results once ubuntu removed it with OSS).

**Comment by MaxKellermann** [comment]
This is not about what I want. I don't understand what this bug report is about. And you're not helping me at all understand it.

**Comment by i30817** [comment]
Ok, lets try again:

If i pass any existing file to the config_file here, no matter how nonsensical:
```
decoder {
    plugin "wildmidi"
    config_file "/home/i30817/.config/mpd/freepats.cfg"
}
```

mpd output reports:

```
$ mpd --no-daemon
Jun 24 19:35 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Jun 24 19:35 : exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
Jun 24 19:35 : exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured
```

ie: it's pretending everything is fine, even if it obviously failed hard.

**Comment by MaxKellermann** [comment]
WildMidi doesn't just magically work out of the box. The example application only works if you install the `libwildmidi-config` package (Debian's choice of package name). Without the package, it doesn't work:
```
System Error (_WM_BufferFileImpl:218) /etc/wildmidi/wildmidi.cfg (Unable to stat) : No such file or directory
```
... unless you explicitly specify a configuration file (for example Timidity's). It's the same as with MPD, just with a different default.

**Comment by i30817** [comment]
Uh, yeah, in ubuntu i just installed wildmidi, the package. Which is actually a good argument against defaults, if they can't be picked up at compile time: they can and probably willl, in the future be in different places.
