### ISSUE TITLE
Video game tracker files inside zips are invisible

### ISSUE THREAD

**Issue by i30817** [MusicPlayerDaemon/MPD#591]
### Describe the bug

Note, this is using ncmpcpp as the GUI. It's behavior with compressed files is strange. Basically after a update, you'll be able to switch between the browser and database view to view the 'new' zip files or dirs, but when it figures out that there are 'no valid files' it'll prune them sooner or later. I'm wholly and completely unsure if these are all mpd bugs, but i figure the root of them is likely to be here, since the compression support, libgme and filesystem browsing is here.

zipped MOD files (amiga): can be recognized by database updates and can play inside of zips and show in both interfaces. No problems here afaict.

zipped MIDI files: can't be recognized by db updates (though the zip files momentarily appear there but report they're 'empty' if you open them). They can play unzipped.

zipped SPC files: like midi, invisible in zip files, visible and playable outside.

Files which are containers themselves:

'VGZ' files: can't be recognized by db updates (though the zip files momentarily appear there but report they're 'empty' if you open them). I'm unsure if this is just a zip rename of if there is more to the format. If you unzip a zip full of them and try to play it, the progress bar starts and the screen actually shows metadata like the expected time to play, but fails before sound. 

'RNS' files: can't be recognized by db updates (the rns files never appear after a scan as is to be expected). I'm unsure if this is just a rar rename of if there is more to the format, but since they never show, nothing to tell.

'7z' files: didn't even try, but they don't appear anyway.

If it wasn't for MOD files working i'd say this was consistently broken.

## Expected Behavior

at least DB updates of 'primary' files that work unzipped like midi and spc work to work inside of zips. Even better would be if vgz worked, since libgme says it supports it (unless they're just renamed zips without metadata). 'RNS' files, if like i suspect are just renamed rars, can go to hell.

## Actual Behavior

Consistently broken except for the mysterious MOD support (from mikmod or modplug, not sure)

## Version

Music Player Daemon 0.21.4 (0.21.4)

Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log

It doesn't seem useful because the errors are 'invisible'. It tries to play vgz files (unzipped) but shows no error (the quick switching is a clue i guess):

```
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/21 Game Over.vgz"
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/21 Game Over.vgz"
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/05 Dim. Dream.vgz"
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/03 Eastern Mystical Love Consultation.vgz"
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/13 Disunified Field Theory of Magic.vgz"
Jun 24 18:25 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/12 Strawberry Crisis!!.vgz"
Jun 24 18:26 : player: played "Tracker Game Music/Touhou_Yumejikuu_~_Phantasmagoria_of_Dim._Dream._(NEC_PC-9801,_OPNA)/06 Tabula rasa ~ The Empty Girl.vgz"
```

And it tries to add files inside of zips  but only shows them in case of mods.

**Comment by MaxKellermann** [comment]
This is a limitation of the GME library: it can only open real files, not virtual files inside an archive file.

**Comment by i30817** [comment]
In the case of midi, which isn't handled by gme, it's the same limitation in another library?

**Comment by MaxKellermann** [comment]
Both WildMidi and FluidSynth can only access real files.

**Comment by i30817** [comment]
Another thing, if that's the case how the hell is libgme supposed to support vg**z** files, which linux `file` says are just:
```
$ file 01\ Game\ Start.vgz 
01 Game Start.vgz: gzip compressed data, last modified: Wed Mar  5 20:35:26 2014, original size 851

```

**Comment by MaxKellermann** [comment]
This is the wrong place to ask questions about libgme.
