### ISSUE TITLE
Better priority logic

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#594]
## Feature request
Moving away from gui mpd clients into using mpc, I started to get the potential of the priority feature. normally I would use MPD playing the entire music dir in the queue (randomized), while listening to music I pick up songs along the way to listen later on thus the priority feature :).

Problem is that you need to specify the "degree" of priority for each song you prioritize. In most cases the first song I prioritize - I would like to hear right after the current song, the second song would play after that and so on...but the absolute number I have to provide with each `prio` command limits me as I need to set the first song with the highest priority number w/o knowing how many I'm going to prioritize.

Currently I made a workaround which I believe, makes better use (and would like to suggest it), currently with every song I want to prioritize i'm doing the following:

1. list the queue for prioritzed songs, if none then provide `prio 1 <song_pos>`
2. in case there is prioritized song, I "push" it forward by increasing the current priority by 1 i.e. `prio <old_prio +1> <song_pos>`, then provide the new song I want to prioritize with `prio 1` (because it is the lowest)
3. on the n song I would like to add, I will pull the list of prioritized songs `mpc -f "[%prio%]_[%position%]" playlist | grep -E '^[1-9]_'`
4. sort the list numerically, reversed
5. increase all songs' priority by 1, (loop, one song at a time)
6. finally, provide the n song, priority 1 `prio 1 <new_song_pos>`

**Comment by MaxKellermann** [comment]
And what is your feature request?

**Comment by roizcorp** [comment]
To change the logic of priority feature to become a FIFO array basically,

**Comment by MaxKellermann** [comment]
MPD already has a FIFO array for songs to be played: it's called the "queue".
Can we close this feature request, or is it rather something else you want?

**Comment by roizcorp** [comment]
IMHO I think it is not semi-FIFO as the user requires to manually punch in the priority number rather than just send the command to add a given song to the queue and then MPD will set its priority automatically by the FIFO concept (if there are already queued songs they will go first)

This a suggestion...you should do whatever you feel right

**Comment by MaxKellermann** [comment]
MPD's queue is certainly very much FIFO.
Unless you explicitly disable the "FIFO mode" by enabling "random" mode.

**Comment by roizcorp** [comment]
oh... I always run in random..this why I thought it does not work that way...anyways..if you do not plan to do it I suppose I will workaround it via bash scripting

Thanks anyway and keep up the great work!

**Comment by MaxKellermann** [comment]
It sounds like a strange idea to disable MPD's FIFO mode and then ask me to implement a FIFO mode. The one you explicitly disabled.
So your solution is not workarounds with bash script, but `mpc random off`

**Comment by roizcorp** [comment]
I suppose this is a matter of preference....MPD playback my entire music dir...and some times I like to listen to couple of specific songs then get back to random...but either way I will manage...thx
