### ISSUE TITLE
Internet radio: Unsupported URI scheme

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#599]
## Bug report
MPD does not add webstreams to queue. 

### Describe the bug
$ mpc -h localhost add http://bytefm.cast.addradio.de/bytefm/main/mid/stream - same with GMPC.

## Expected Behavior
Add stream to playlist.

## Actual Behavior
error adding http://bytefm.cast.addradio.de/bytefm/main/mid/stream: Unsupported URI scheme

## Version
Music Player Daemon 0.22~git (v0.21.11-433-g326c6ae61)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local udisks

Neighbor plugins:
 udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo pipe alsa httpd

Encoder plugins:
 null opus lame flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa curl ffmpeg mms

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify systemd tcp un

## Log
client: [1] opened from 127.0.0.1:46682
client: [1] process command list
client: process command "add "http://bytefm.cast.addradio.de/bytefm/main/mid/stream""
exception: Unsupported URI scheme
client: command returned 3
client: [1] process command list returned 3
client: [1] closed

**Comment by skidoo23** [comment]
Missing break or do I miss the point?

diff --git a/src/LocateUri.cxx b/src/LocateUri.cxx
index dcb52bfde..04eb999b4 100644
--- a/src/LocateUri.cxx
+++ b/src/LocateUri.cxx
@@ -63,6 +63,8 @@ LocateAbsoluteUri(UriPluginKind kind, const char *uri
 {
        switch (kind) {
        case UriPluginKind::INPUT:
+               break;
+
        case UriPluginKind::STORAGE: // TODO: separate check for storage plugins
                if (!uri_supported_scheme(uri))
                        throw std::runtime_error("Unsupported URI scheme");

**Comment by MaxKellermann** [comment]
You miss the point. This is intentional, and adding `break` here would disable an important check.
