### ISSUE TITLE
[Feature request] Abillity to attach sticker data to song metadata instead of URI

### ISSUE THREAD

**Issue by JerwuQu** [MusicPlayerDaemon/MPD#608]
Currently, song stickers are attached to song paths. For someone that (infrequently) reorganizes their collection, this is fragile. It would be good to have an option in MPD to translate any incoming sticker URIs to either
- A hashsum of the complete audio file
- A hashsum of the file's metadata section
- A composite of `artist`, `title`, and `album`

This is somewhat related to #114 and #484.

**Comment by chaseadam** [comment]
My particular use case uses plugins to play items in the playlist (i.e. http locations) which are not represented in the database. It would be useful to have this concept of (sticker) metadata which can be associated to non-database items.

**Comment by sp1ff** [comment]
Just noting that attaching the sticker to a hash of the file's metadata (or just artist, title & album) would break if the tags were updated.

**Comment by jcorporation** [comment]
As #1659 is merged, can this issue be closed?

**Comment by JerwuQu** [comment]
I haven't been using MPD for the last couple of years but it looks like the PR fulfills the original request, so closing.

Thanks! :)
