### ISSUE TITLE
Youtube audio/video sound is wrong

### ISSUE THREAD

**Issue by sanntran** [MusicPlayerDaemon/MPD#61]
Hi,
I'm using youtube-dl (verion 2017.05.23) to take audio url from Youtube to play in MPD (version 0.19.12) that installed in Raspberry Pi (OS is Ubuntu minimal).
Everything worked well until some days ago. MPD now can play Youtube audio url but the sound is crazy (likes reading from crashed disk)
I think about error when decoding from HTTPS but I tried with Vimeo url (https) and it played without any problem
There is no problem when MPD plays audio from others servers and local files
The problem occurs only when play Youtube url

Please help me to fix this problem. Thank you so much...

**Comment by MaxKellermann** [comment]
Unsupported ancient MPD version.
