### ISSUE TITLE
MPD 0.21.11 soxr resampling hangs on seek

### ISSUE THREAD

**Issue by ClaudioSantacesaria** [MusicPlayerDaemon/MPD#610]
When resampling with soxr, any attempt to perform seek hangs mpd (music stops and requires mpd restart). This is still true with 0.21.11 (and for all previous versions with soxr).
Tested at least when resampling CD rate in flac format (44100) to 88200 or 96000 to alsa output.
If resampling is not active, no issue.

# mpc version
mpd version: 0.21.11

# mpc seek +00:01:00
Vasco Rossi - Stammi Vicino
[playing] #11/14   1:25/5:21 (26%)
volume: n/a   repeat: off   random: off   single: off   consume: off
# mpc
error: Connection refused
#

============================================
**From mpd.conf:**

audio_output {
type "alsa"
name "My ALSA Device"
device "hw:0,0"
mixer_type "none"
auto_resample "no"
dop "no"
allowed_formats "96000:24:2"
}
resampler {
plugin "soxr"
quality "very high"
threads "0"
}

**Comment by MaxKellermann** [comment]
Can't reproduce, and since you explicitly denied to paste your log (you removed the section from the bug reporting template), I can't help further.
