### ISSUE TITLE
Mpd 0.21.11 CdioParanoia input plugin build failure with libcdio-paranoia 0.90

### ISSUE THREAD

**Issue by GvMariani** [MusicPlayerDaemon/MPD#613]
### Describe the bug
Trying to build mpd 0.21.11 on the distro Rosa 2016.1 x86_64, a LTS distribution derived from Mandriva. It provides libcdio 2.0.0 with a rather old version of libcdio-paranoia (0.90) and the latter does not provide the cdio_cddap_messages function; this in turn causes the build process to fail when trying to compile CdioParanoiaInputPlugin.cxx, because of the absence of named function in cdda.h.

The culprit can be found at the line 304 of CdioParanoiaInputPlugin.cxx:
#if LIBCDIO_VERSION_NUM >= 90
cdio_cddap_messages(s_err);
#else
free(s_err);
#endif

The above snippet has two issues, AFAICT:
1) The initial test for the libcdio version is plainly wrong, because cdio_cddap_messages was added to libcdio-paranoia in Sep 24 2014, ie right before the release of version 0.93 (see: https://github.com/rocky/libcdio-paranoia/commits/master?after=363d13fbff8d6e8ccb98b6176147245d50348fe6+69). So the initial test at least should be something as:
#if LIBCDIO_VERSION_NUM >= 93.

2) But, even with the above change, while building against Rosa's libcdio-paranoia 0.90 the test still wrongly selects the absent "cdio_cddap_messages" function, instead of the existing "free" one: I guess this happens because the test uses the version of libcdio and not the libcdio-paranoia one... perhaps it was supposed that libcdio and libcdio-paranoia would always be installed in the same version.

## Expected Behavior
Successful build.

## Actual Behavior
Build failure while processing src/input/plugins/CdioParanoiaInputPlugin.cxx.

## Version
0.21.11 (but commit history shows that every release >= 0.21.5 will have the same issue).

## Log
-Isrc/input/plugins/c6f62ff@@input_plugins@sta -Isrc/input/plugins -I../src/input/plugins -Isrc -I../src -I. -I../ -I/usr/include/cdio -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/samba-4.0 -I/usr/include/yajl -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -D_GNU_SOURCE -O2 -Wa,--compress-debug-sections -gdwarf-4   -Wstrict-aliasing=2 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -fPIC -MD -MQ src/input/plugins/c6f62ff@@input_plugins@sta/CdioParanoiaInputPlugin.cxx.o -MF src/input/plugins/c6f62ff@@input_plugins@sta/CdioParanoiaInputPlugin.cxx.o.d -o src/input/plugins/c6f62ff@@input_plugins@sta/CdioParanoiaInputPlugin.cxx.o -c ../src/input/plugins/CdioParanoiaInputPlugin.cxx
clang-7: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
../src/input/plugins/CdioParanoiaInputPlugin.cxx:302:6: error: use of undeclared identifier 'cdio_cddap_free_messages'; did you mean 'cdio_cddap_messages'?
                                        cdio_cddap_free_messages(s_err);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~
                                        cdio_cddap_messages
/usr/include/cdio/paranoia/cdda.h:204:16: note: 'cdio_cddap_messages' declared here
extern char   *cdio_cddap_messages(cdrom_drive_t *d);
               ^
../src/input/plugins/CdioParanoiaInputPlugin.cxx:302:31: error: cannot initialize a parameter of type 'cdrom_drive_t *' (aka 'cdrom_drive_s *') with an lvalue of type 'char *'
                                        cdio_cddap_free_messages(s_err);
                                                                 ^~~~~
/usr/include/cdio/paranoia/cdda.h:204:51: note: passing argument to parameter 'd' here
extern char   *cdio_cddap_messages(cdrom_drive_t *d);
                                                  ^
2 errors generated.

**Comment by MaxKellermann** [comment]
What a mess! There's no way to check the libcdio-paranoia version at compile time; the macro `LIBCDIO_PARANOIA_VERSION` is a string, not a number. Of course, I could add configure-time checks, but on the other hand, it may be time to remove support for such old versions...
