### ISSUE TITLE
Link dead for release win32

### ISSUE THREAD

**Issue by MartyLake** [MusicPlayerDaemon/MPD#615]
## Question
Hello,

the download link for win32 https://www.musicpd.org/download/win32/0.21.12/mpd.exe from https://www.musicpd.org/download.html is dead. Do you know when a release for windows will be issued ?

**Comment by MartyLake** [comment]
Just checked now and the link is up again. thanks you very much !!!

**Comment by MaxKellermann** [comment]
Thanks for reporting, I was in a hurry when I released 0.21.12.

**Comment by MartyLake** [comment]
I updated from an old version and now seeking in flac files works!!! :D

Le dim. 4 août 2019 à 20:20, Max Kellermann <notifications@github.com> a
écrit :
