### ISSUE TITLE
MPD do no to open certain cue file

### ISSUE THREAD

**Issue by ahlborner** [MusicPlayerDaemon/MPD#62]
Good morning.
I use a moode audio.
The player don't open a certain cue file.
 If in a cue file (in "FILE" string) is present a non conventional character (ex. ê, ü, ç) the file is not open. 
I apologize for my English, sorry.
Thanks
 Best regards

**Comment by MaxKellermann** [comment]
Your description lacks the most vital information. https://www.musicpd.org/help/
Also upload your CUE file.
My random guess is that you're seeing a character set problem; either your CUE file contains malformed UTF-8 characters or your file names, or both don't agree on the same encoding.

**Comment by ahlborner** [comment]
Ok, today I upload some cue file,

thanks

**Comment by MaxKellermann** [comment]
Closing due to lack of information & feedback.
