### ISSUE TITLE
Crackle on RasPi with Hifiberry

### ISSUE THREAD

**Issue by The-Michael-R** [MusicPlayerDaemon/MPD#620]
### Describe the bug
Since mpd-0.21.12 playing music creates some crackling noise especially at loud passages. It sounds like digital clipping but that noise is also present if volume is not set to 100%. Downgrading to mpd-0.21.11 solves the issue.

## Expected Behavior
Playing MP3s (streams or local) nice and clean.

## Actual Behavior
Crackling noise in loud passages, easily hearable especially at basedrums (due to low frequency). Actual ALSA volume doesn't matter.

## Version

Music Player Daemon 0.21.12 (0.21.12)
[...]
(not present at mpd-0.21.11)

## Log

RasPi
ArchLinux (up to date)
Kernel 4.19.63-1-ARCH
HifiBerry

mpd.conf:
```
[...]
audio_output {
#	type		"alsa"
	name 		"Hifiberry"

        type            "alsa"
        device          "hw:0,0"
        mixer_type      "hardware"
        mixer_control   "DIGITAL"
        mixer_device    "hw:0"
        mixer_index     "0"
        auto_resample   "no"
        auto_format     "no"
        enabled         "yes"
}
```

**Comment by MaxKellermann** [comment]
See https://github.com/MusicPlayerDaemon/MPD/issues/617
