### ISSUE TITLE
id3 issue with lame - Raspberry Pi / Jessie

### ISSUE THREAD

**Issue by braselectron** [MusicPlayerDaemon/MPD#625]
### Describe the bug

First you configure outputs:

(server is a RPi)
Output 1 (My ALSA Device) is default (can be disabled)
Output 2 (Vorbis HTTP Stream) is enabled port 8000
Output 3 (MP3 HTTP Stream) is configured port 8003

(client is a network host - Ubuntu desktop/laptop)

## **Now connects to output 2:**

\~$ mpv http://rasp109:8109

Playing: http://rasp109:8109
 (+) Audio --aid=1 (mp3 2ch 44100Hz)

**File tags:**
 icy-title: String Serenades - 01 - Pyotr Il'itsch Tchaikovsky

AO: [pulse] 44100Hz stereo 2ch s16
A: 00:00:09 / 00:00:00 Cache:  0s+0KB

## **Now connects to output 3:**

\~$ mpv http://rasp109:8000
Playing: http://rasp109:8000
 
(+) Audio --aid=1 'Pyotr Il'itsch Tchaikovsky' (vorbis 1ch 44100Hz)

**File tags:**
 Artist: 01
 Album: String Serenades
 Genre: Unknown
 Title: Pyotr Il'itsch Tchaikovsky
 Track: 01

AO: [pulse] 44100Hz mono 1ch float
A: 00:00:06 / 00:00:00 Cache:  0s+0KB

Using mpv, vlc, ffplay, others same conclusion.

Now disable output 2 (mpc disable 2) and stream from output 3 has no tags after a certain amount of time/music foward steps. 

Note: I did not yet get to a conclusion how or when it stops sending the id3tags, but it just happens after a while playing.

## Expected Behavior

Output 2 and 3 should send same id3 tags to client and be independent of one another for CPU and energy budget I could keep only output 3 enabled.

## Where is the problem ?

I believe that the id3 tag insertion is only stable for the vorbis codec stream, and the lame codec is loosing sync with the cache/database after a certain amount of time (or rounds).

## Version

System:	RPi 3 B - Raspbian GNU/Linux 8.0 (jessie)
mpd --version:  Music Player Daemon 0.19.1

## Log
tail of mpd.log

Aug 09 18:41 : player: played "Classics_003/06-Substance_Over_Style/03-Substance Over Style.mp3"
Aug 09 18:51 : player: played "Classics_003/06-Substance_Over_Style/04-Substance Over Style.mp3"
Aug 09 19:01 : client: [111] opened from local
Aug 09 19:01 : client: [111] closed
Aug 09 19:02 : player: played "Classics_003/06-Substance_Over_Style/05-Substance Over Style.mp3"
Aug 09 19:02 : client: [112] opened from local
Aug 09 19:02 : client: [112] closed
Aug 09 19:03 : client: [113] opened from local
Aug 09 19:03 : server_socket: bind to '0.0.0.0:8000' failed: Address already in use (continuing anyway, because binding to '[::]:8000' succeeded)
Aug 09 19:03 : client: [113] closed
Aug 09 19:03 : client: [114] opened from local
Aug 09 19:03 : client: [114] closed
Aug 09 19:12 : player: played "Classics_003/06-Substance_Over_Style/06-Substance Over Style.mp3"

## Additional thoughts
I wish you could also send the cover image usually available in the source music files and/or a cover.jpg/png image in the music folder, and obey a priority 1 for image from file.   priority 2: image from folder.

Thank you for all the fun!

**Comment by MaxKellermann** [comment]
Your MPD version is very old and unsupported.

**Comment by braselectron** [comment]
Dear Max,

Thank you for the quick reply.

I understand that I am on a prior release but I don't usually use bleeding edge releases.

Can you please tell me if these "bugs", I mean, coding options, where "ajusted" to a similar aproach in regard to id3 tags ?  I mean, does vorbis and lame use the same tag structures ?

And can you confirm if the new commit/version can use the cover image available in the source audio files ?

Thank you.

**Comment by MaxKellermann** [comment]
It's your choice to use a 5 years old MPD version, and it's my choice not to even look at any detail of your bug report. At this point, there's nothing else to say about this.

**Comment by braselectron** [comment]
Dear Max,

Considering your replies to me and others, by reading comments here, please consider this: 
  I'm very sorry for your pain, 
in our insignificant blue pale dot, that is drifting along in our vast and endless universe.

MPD is a great software/package that is very useful, even though it doesn't have a user friendly support, at the moment.

"There are three methods to gaining wisdom. The first is reflection, which is the highest. The second is limitation, which is the easiest. The third is experience, which is the bitterest."  - Confucius

I forgive your bitterness. LLAP
