### ISSUE TITLE
[doc] explain how 'find' combines multiple different tag types

### ISSUE THREAD

**Issue by xipmix** [MusicPlayerDaemon/MPD#632]
## Feature request
https://www.musicpd.org/doc/html/protocol.html#filters explains

> ```(TAG == 'VALUE')```: match a tag value; If there are multiple values of the given type, at least one must match.

This is clear enough: ```find album foo album bar``` will return something if either ```foo``` or ```bar``` matches. But it prompted me to wonder 'what if you specify two tags of different types, e.g. ```find album foo artist baz``` ?' Are they implicitly ANDed together, or ORed? Or is this now illegal syntax in 0.21+ and one must explicitly AND or OR expressions together?

I don't think this is clear from this section of the docs as it stands now.
If someone can clarify this I'd be happy to work it into a PR.

**Comment by MaxKellermann** [comment]
The old syntax still works and is not illegal, but documentation for it was removed. Since your question is only about the (now-undocumented) old syntax, I don't think anything should be clarified here. Just don't use the old syntax in new code.
