### ISSUE TITLE
unable to build 0.22 on ubuntu xenial

### ISSUE THREAD

**Issue by stef97** [MusicPlayerDaemon/MPD#634]
### Describe the bug
ninja fails 
**[3/642] Compiling C++ object 'src/util/ed6d25d@@util@sta/Alloc.cxx.o'.
../../src/util/Alloc.cxx: In function ‘void oom()’:
../../src/util/Alloc.cxx:32:2: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  (void)write(STDERR_FILENO, "Out of memory\n", 14);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[293/642] Compiling C++ object 'src/archive/plugins/50b12ee@@archive_plugins@sta/Iso9660ArchivePlugin.cxx.o'.
FAILED: src/archive/plugins/50b12ee@@archive_plugins@sta/Iso9660ArchivePlugin.cxx.o
c++ -Isrc/archive/plugins/50b12ee@@archive_plugins@sta -Isrc/archive/plugins -I../../src/archive/plugins -Isrc -I../../src -I. -I../../ -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O2 -g -Wall -Wextra -Wvla -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -D_GNU_SOURCE -fPIC -Wdate-time -MD -MQ 'src/archive/plugins/50b12ee@@archive_plugins@sta/Iso9660ArchivePlugin.cxx.o' -MF 'src/archive/plugins/50b12ee@@archive_plugins@sta/Iso9660ArchivePlugin.cxx.o.d' -o 'src/archive/plugins/50b12ee@@archive_plugins@sta/Iso9660ArchivePlugin.cxx.o' -c ../../src/archive/plugins/Iso9660ArchivePlugin.cxx
In file included from ../../src/archive/plugins/Iso9660ArchivePlugin.cxx:32:0:
/usr/include/cdio/iso9660.h:277:45: error: flexible array member ‘iso9660_dir_s::filename’ not at end of ‘struct iso9660_pvd_s’
   char             filename[EMPTY_ARRAY_SIZE];
                                             ^
**
It seems there are few dependency that failed during mesos build but I was not able to find the updated version of those packages for xenial

Dependency libnfs found: NO found '1.9.8' but need: '>= 1.11'

Header <sndio.h> has symbol "ROAR_VERSION" : NO

Checking for function "getpeereid" : NO

Dependency libcdio_paranoia found: NO found '0.83' but need: '>= 10.2+0.93+1'
Run-time dependency libcdio_paranoia found: NO (tried pkgconfig and cmake)

**Comment by MaxKellermann** [comment]
This is a bug in libiso9660. You can disable the plugin with `-Diso9660=disabled`
It cannot be fixed in MPD.
