### ISSUE TITLE
some question about resampling / DSD / allowed_formats /

### ISSUE THREAD

**Issue by cdtsuipo** [MusicPlayerDaemon/MPD#637]
## Question
hi ,Max 
    i'm useing Moode on my rpi , i got those code in mpd.conf. resampling was closed in the Moode UI . fun part is , my usb dac can play dsf file in DSD mode , and paly 16/44.1 file in PCM 32/384 mode . but ,when i set resampling in the Moode UI , same configuration ,my usb dac only play DSD file in PCM 32/384 mode. So wired .the question is ,which component has completed the resampling work ,the sox ,or the libasound (according to https://www.musicpd.org/doc/html/plugins.html#alsa-plugin）
########################################################
resampler {
plugin "soxr"
quality "very high"
threads "1"
}

audio_output {
type "alsa"
name "ALSA default"
device "hw:1,0"
mixer_type "hardware"
dop "no"
auto_resample "no"
allowed_formats "384000:*:2 dsd64:* dsd128:* dsd256:*"
}
###########################################################
pcm 32/384
pi@moode:~ $ cat /proc/asound/card*/pcm*p/sub*/hw_params
closed
closed
closed
closed
closed
closed
closed
closed
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 384000 (384000/1)
period_size: 32768
buffer_size: 131072
#############################################################
DSD

pi@moode:~ $ cat /proc/asound/card*/pcm*p/sub*/hw_params
closed
closed
closed
closed
closed
closed
closed
closed
access: RW_INTERLEAVED
format: DSD_U32_BE
subformat: STD
channels: 2
rate: 88200 (88200/1)
period_size: 11025
buffer_size: 44100

**Comment by MaxKellermann** [comment]
I don't know. Paste a verbose log of the start of playback.

**Comment by cdtsuipo** [comment]
hi ,Max 
   Thanks for the reminder, i got verbose log ,and it says sox do the job ,whether auto_resampling is set to "no" or "yes" .
