### ISSUE TITLE
MusePack distortion

### ISSUE THREAD

**Issue by greenvorbisfan** [MusicPlayerDaemon/MPD#638]
### Describe the bug
Some (not all!) MusePack files play severely distorted sound. It works when ReplayGain is enabled (any mode). 
## Version
Music Player Daemon 0.21.5 (v0.21.4-1-g1862a98a4), Ubuntu 18.04.3 LTS
Attached file for example:
[John Larkin - Lady Bird.zip](https://github.com/MusicPlayerDaemon/MPD/files/3586275/John.Larkin.-.Lady.Bird.zip)

**Comment by MaxKellermann** [comment]
Your MPD version is outdated and has known bugs, and is for that reason unsupported. Get the latest version with all bug fixes. If this still occurs, we can reopen this bug report, but only if you complete it.
