### ISSUE TITLE
MusePack distortion #2

### ISSUE THREAD

**Issue by greenvorbisfan** [MusicPlayerDaemon/MPD#640]
### Describe the bug
Some (not all!) MusePack files play severely distorted sound. It works when ReplayGain is enabled (any mode).

## Expected Behavior
Correctly playing MusePack files with ReplayGain information.

## Actual Behavior
There is a noticeable sound distortion.

## Version
mpd --version
Music Player Daemon 0.22~git (v0.21.14-607-gee36a48db)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log
mpd .mpdconf --no-daemon --verbose
config_file: loading file .mpdconf
Sep 09 14:59 : soxr: soxr converter 'very high'
Sep 09 14:59 : vorbis: Xiph.Org libVorbis 1.3.5
Sep 09 14:59 : opus: libopus 1.1.2
Sep 09 14:59 : sndfile: libsndfile-1.0.28
Sep 09 14:59 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
Sep 09 14:59 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Sep 09 14:59 : adplug: adplug 2.2.1
Sep 09 14:59 : simple_db: reading DB
Sep 09 14:59 : exception: Input plugin 'tidal' is not configured: No Tidal application token configured
Sep 09 14:59 : exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
Sep 09 14:59 : curl: version 7.58.0
Sep 09 14:59 : curl: with GnuTLS/3.5.18
__________________________________________________________________________
[John Larkin - Lady Bird.zip](https://github.com/MusicPlayerDaemon/MPD/files/3590347/John.Larkin.-.Lady.Bird.zip)

**Comment by MaxKellermann** [comment]
What does "It works when ReplayGain is enabled" mean?
Your log doesn't show any playback.

**Comment by greenvorbisfan** [comment]
If ReplayGain is enabled in the configuration file, some MusePack format files are played with distortion.
Please, tell me, which keys you need to use in order to display playback in the log. Thanks.
