### ISSUE TITLE
freeze on one track

### ISSUE THREAD

**Issue by installgentoo** [MusicPlayerDaemon/MPD#642]
### Describe the bug
When you have a single song on a looped playlist mpd will sometimes freeze when it finishes. Seems to be happening for a while now, my options are [zxc], nothing's in logs- mpd just locks up with 0 cpu usage and can only be killed with -9, so it's a deadlock i presume. I couldn't catch this on debug build. Switching to next song manually while having one song does not cause the bug.

## Version

Music Player Daemon 0.21.14 (0.21.14)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local

Decoders plugins:
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 soxr

Tag plugins:

Output plugins:
 null alsa httpd

Encoder plugins:
 null lame wave

Input plugins:
 file alsa ffmpeg

Playlist plugins:
 extm3u m3u pls

Protocols:
 file:// alsa:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://

Other features:
 epoll icu inotify tcp un

**Comment by MaxKellermann** [comment]
Need verbose log and backtrace.

**Comment by installgentoo** [comment]
i've just caught this with logs on verbose.

there's nothing in log. mpd just freezes.

**Comment by MaxKellermann** [comment]
If there's nothing in the log file, then either you're looking at the wrong file or MPD isn't playing anything. MPD logs at start and end of playback.
And don't forget the backtrace. I'm unable to analyze your problem without full information.

**Comment by MaxKellermann** [comment]
Can't help without information.

**Comment by installgentoo** [comment]
A year later this is still happening. I just kill and restart mpd through a monitoring script, but the fact that software has freezes isn't good.
Other guy on the internet having this exact same problem: https://www.reddit.com/r/archlinux/comments/9xlqm3/mpd_and_ncmpcpp_freeze_after_last_update/

note that he posted around the same time i encountered the issue.

my config:

`
 music_directory		"/home/user/music"
playlist_directory	"/var/lib/mpd/playlists"
db_file			"/var/lib/mpd/database"
state_file		"/var/lib/mpd/state"
pid_file		"/var/lib/mpd/pid"
user			"mpd"
auto_update		"yes"
#log_file		"/tmp/mpd_log"
#log_level		"verbose"

audio_output {
 type		"alsa"
 name		"My ALSA Device"
 auto_resample	"yes"
}

audio_output_format		"48000:24:2"

samplerate_converter		"soxr high"

volume_normalization		"yes"

filesystem_charset "UTF-8"
`

**Comment by MaxKellermann** [comment]
Can't help without information! I'm serious. If you want to have your problem fixed, you need to post more information.

**Comment by installgentoo** [comment]
Debugging hangs is hard.

**Comment by MaxKellermann** [comment]
> Debugging hangs is hard.

And you make it impossible by withholding information.

**Comment by installgentoo** [comment]
well, i mean, verbose log just said the exact same things that it prints on song normal switch and cut off, and i couldn't get even catch this in debug build, so i just plugged in a script and forgot about it.

**Comment by MaxKellermann** [comment]
Let's stop wasting our time by discussing that you're unwilling to post any information. This doesn't lead anywhere.
