### ISSUE TITLE
Make it possible to configure real-time priority.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#643]
According to https://www.musicpd.org/doc/html/user.html#real-time-scheduling
output thread and rtio thread try to acquire the real-time priority of 50.

I want to lower it because

* With PREEMPT_RT_FULL=y, ethernet interrupts have real-time priority of 50.
* jack_netsource needs to have a lower real-time priority than ethernet interrupts. Otherwise, a lot of underruns occur from jackd netone backend and its clients.
* It doesn't seem to make sense for rtio thread and output thread to have higher real-time priority than jack_netsource.

**Comment by MaxKellermann** [comment]
I'd like MPD to work properly out of the box, and giving the user too many knobs will most of the time only give him a chance to shoot himself in the foot (look at the deprecated audio buffer settings...).
What do you think about changing the hard-coded real-time priority to a better value, one higher than jack_netsource? If that covers all use cases, we should do that instead of adding a new setting.
With just the new setting, most users won't benefit from it because they don't read the documentation and don't know about the priority conflict.

**Comment by crocket** [comment]
According to JACK audio connection kit, only real-time threads processing JACK audio connection kit data are supposed to have high priorities.

I suspect a saner default would be to not touch process priority.

**Comment by MaxKellermann** [comment]
> According to https://github.com/jackaudio/jackaudio.github.com/wiki/FAQ_and_Myths

MPD does exactly what this JACK document recommends, but this has little to do with your feature request.

> to not touch process priority or thread priority

Why would that be saner?

> to get lower real-time priorities than that given to JACK clients

I don't understand. MPD *is* a JACK client. (Anyway, who gives priorities to JACK clients?)

> to get a high nice priority instead of a real-time priority

The `nice` value is a per-process attribute, i.e. it affects all threads. That's not "saner", that's rather "insane".

> to just get a low real-time priority such as -5

There are no negative scheduler priorities (unlike `nice` values). Did you mean +5 instead?

**Comment by crocket** [comment]
> I don't understand. MPD is a JACK client. (Anyway, who gives priorities to JACK clients?)

I use ALSA output of MPD because mpd tries to connect its own JACK ports to other ports.
I bridged ALSA to JACK via zita-ajbridge.
rtio thread and output thread are not JACK clients.

> There are no negative scheduler priorities (unlike nice values). Did you mean +5 instead?

htop

![2019-10-09_Wed_02:18:01](https://user-images.githubusercontent.com/748856/66446730-bb46b000-ea86-11e9-9fdf-d6811dc79376.png)

top

![2019-10-09_Wed_02:19:38](https://user-images.githubusercontent.com/748856/66446736-c0a3fa80-ea86-11e9-9acb-748f30001f09.png)

**Comment by MaxKellermann** [comment]
"htop" and "top" don't show the `sched_priority` value.
And note that your "jackd" doesn't use a real-time scheduler (`RR` or `FIFO`). It uses the standard `OTHER` scheduler. (With a real-time scheduler, top's `PR` column shows just the text `rt` and never show the `sched_priority`, ever.)

What do you mean by "without real-time linux kernel"? Do you mean without the linux-rt patches? The vanilla Linux kernel has `RR` and `FIFO` without patches, but linux-rt improves the kernel's latency.

Just to be sure we're on the same line: are you aware that MPD uses the `FIFO` real-time scheduler, which is available in the vanilla kernel without linux-rt? And are you aware that unlike MPD, your jackd does **not** use a real-time scheduler? Your zita processes aren't real-time either.

> If rtio thread had a real-time priority of -5, htop and top would display its real-time priority as -6

I think that's wrong. From the `top` manpage:
> "PR  --  Priority; The scheduling priority of the task.  If you see `rt' in this field, it means the task is running under real time scheduling priority."

I repeat: "htop" and "top" don't show the `sched_priority` value. "ps" can show that value when you select the `rtprio` column (maybe "htop"/"top" have a similar column, but it's not shown by default, and your screenshots don't show it either).

I'm confused by your explanations. They don't map to my view of those things, and don't appear to make sense to me. I think we should get nomenclature like "real-time priority" right - the `sched_priority` value (as configured by `sched_setscheduler`) cannot be negative; the documented allowed range is `1..99`, and it is only applicable to `RR` and `FIFO`.

**Comment by crocket** [comment]
I guess `ps` is more appropriate here.

```
~> ps -Lo rtprio,pri,comm --sort pri (pgrep 'zita|jackd|mpd')
RTPRIO PRI COMMAND
     -  19 jackd
     -  19 jackd
    90 130 jackd
     -  19 jackd
     -  19 zita-a2j
     -  19 zita-a2j
     -  19 zita-a2j
    85 125 zita-a2j
    95 135 zita-a2j
     -  19 zita-j2a
     -  19 zita-j2a
     -  19 zita-j2a
    85 125 zita-j2a
    95 135 zita-j2a
     -  19 mpd
     -  19 io
    50  90 rtio
```

Without rt-linux patch applied, ethernet interrupts are not given real-time priority of 50.
So, I just execute `jackd -P 90`.
jackd, zita-a2j, and zita-a2j all have real-time threats.
The rtio thread comes from mpd.

**Comment by MaxKellermann** [comment]
As you see, there's no negative real-time priority!
And your jackd and zita threads have a higher priority than ethernet interrupts. I'm confused.

**Comment by crocket** [comment]
That's an output from my workstation computer which doesn't run jack_netsource.
Raspberry Pi runs jack_netsource.
My Raspberry Pi linux kernel used to run with rt-linux patch.
Right now, Raspberry Pi linux kernel doesn't run with rt-linux patch.

**Comment by MaxKellermann** [comment]
I implemented your suggestion (which was actually my own first suggestion), but I'm still confused why you posted 3 program outputs (htop, top, ps) and none of them were relevant to your issue. Most of your text was irrelevant, and you didn't admit that you were wrong about negative real-time priorities after you mixed up those things. We could have found an agreement earlier if you hadn't posted so much irrelevant and wrong text here.
And you apparently use an ALSA plugin and an ALSA loopback device to route audio to JACK instead of using MPD's native JACK output plugin, which sounds like a horrible idea. Every aspect of that is horrible. But hey, it's your freedom to do horrible things with free software... and fortunately you found configuration hacks to make it work seamlessly in spite of all the technical cruft you're using, who would've thought!

**Comment by crocket** [comment]
> Most of your text was irrelevant, and you didn't admit that you were wrong about negative real-time priorities after you mixed up those things. We could have found an agreement earlier if you hadn't posted so much irrelevant and wrong text here.

My setup has become so complex that it's hard to describe it without being confused.
I don't yet know how to explain it without being confused.
I was so confused that admitting that negative real-time priorities don't exist never occurred to my mind.

> And you apparently use an ALSA plugin and an ALSA loopback device to route audio to JACK instead of using MPD's native JACK output plugin, which sounds like a horrible idea. Every aspect of that is horrible. But hey, it's your freedom to do horrible things with free software... and fortunately you found configuration hacks to make it work seamlessly in spite of all the technical cruft you're using, who would've thought!

Actually, I moved away from ALSA loopback to SPDIF output and SPDIF input because ALSA loopback doesn't work.

Because it is still a terribly bad idea even with SPDIF, I decided to minimize my life style by eliminating JACK and using ALSA only.

I just kept the issue here for others who might want to use jack_netsource with rt-linux patch applied.
