### ISSUE TITLE
Why 'Connection Refused' on netcat when connecting to mpd?

### ISSUE THREAD

**Issue by RomeuG** [MusicPlayerDaemon/MPD#645]
## Question
I am running the MPD version `Music Player Daemon 0.22~git (0.22~git)` on MacOS.
Why is the connection refused when I try to connect to mpd through netcat?

The netcat command I am running is `netcat -u 127.0.0.1 6600`, being this the command line result:
```
➜  ~ netcat -u 127.0.0.1 6600
pause
read(net): Connection refused
```

Here is my mpd configuration file:

```
music_directory         "~/Music"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log"
pid_file                "~/.mpd/mpd.pid"
state_file              "~/.mpd/mpdstate"

audio_output {
    type                  "osx"
    name                  "CoreAudio"
    mixer_type            "software"
}

decoder {
    plugin                "mp4ff"
    enabled               "no"
}

bind_to_address         "127.0.0.1"
port                    "6600"
    
user                    "romeu"
```

It should be noted that I can run ncmpcpp without any problem.

Thank you.

**Comment by MaxKellermann** [comment]
## Question

Why are you using netcat's UDP mode?

**Comment by RomeuG** [comment]
You are right. I was using that command-line argument without even checking it out. Thanks.
