### ISSUE TITLE
android: logging configuration is ignored

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#647]
### Describe the bug
Configuration:
Android MPD Satelite clitent, mpd.conf is in /sdcard - works normally, until every now and then the connection to the Satelite Server (nfs) breaks. In order to debug that I added logging configuration `log_file = '/sdcard/mpd.log'` 
## Expected Behavior
mpd.log file is created in /sdcard (i even tried to set the log file to be created in /data/data/org.musicpd/

## Actual Behavior
no log file is created

## Version
0.21.11

## Log
no log because this is the bug

**Comment by MaxKellermann** [comment]
On Android, MPD uses Android's built-in logging facilities and ignores the configuration. This isn't documented, though, so this might just be a documentation bug.

**Comment by roizcorp** [comment]
perhaps a feature to export mpd logs from android into a file like "save as" manner?

**Comment by MaxKellermann** [comment]
MPD has no access to Android's log; it can only append to it, but not read it.
