### ISSUE TITLE
input_cache setting creates an exception

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#648]
### Describe the bug
I use MPD in my car, I want to spare my HDD from spinning all the time so I found `input_cache`
so I used the example in the documentation and pasted it to the mpd.conf
https://www.musicpd.org/doc/html/user.html#configuring-the-input-cache 
```
input_cache {
    size "1 GB"
}
```
## Expected Behavior
mpd works

## Actual Behavior
exception: nested: unrecognized parameter: input_cache

**Comment by MaxKellermann** [comment]
Incomplete bug report.

**Comment by roizcorp** [comment]
(bug report updated)

**Comment by MaxKellermann** [comment]
The version you're using doesn't have this feature.

**Comment by roizcorp** [comment]
documentation bug? e.g. "starting mpd 22.0"
