### ISSUE TITLE
MPD v0.20.9 imports wrong song title name with ## number in front

### ISSUE THREAD

**Issue by CaptainMetal** [MusicPlayerDaemon/MPD#65]
Dear MPD Team,

using mpd v0.20.9 and importing new songs via mpc update (v0.28) imports the songs into the database with their number ## in front of the title (it is part of the full file name). 
So using a mpd client-app the title shows off with the number in front. 
This was not the case in older versions like v0.19.19 (well i didn't tested every version, i am sorry for this). 

Is there an additional feature/flag in the mpd.conf file to toggle this behaviour ? or is it just a bug ?

regards,
captainmetal

**Comment by MaxKellermann** [comment]
I have no idea what this is about. Please rephrase your bug report and show some data, like the output of MPD's `listinfo` command and data about your files.

**Comment by CaptainMetal** [comment]
oh, sorry for missing infos, here it is: after "mpc update NAS/Music/Chuck\ Berry"
i get the following results, where you can see, that the Files are there, but the Title is missing with v0.20.9.

Please have a look on the screenshots taken from the iPad MPD app. There you can see that even the "Year" is not visible with v0.20.9

MPD 0.19.19:

mpc listall|grep -i chuck

NAS/Music/Chuck Berry/Chuck/01 Wonderful Woman.aif
NAS/Music/Chuck Berry/Chuck/02 Big Boys.aif
NAS/Music/Chuck Berry/Chuck/03 You Go To My Head.aif
NAS/Music/Chuck Berry/Chuck/04 3_4 Time (Enchiladas).aif
NAS/Music/Chuck Berry/Chuck/05 Darlin'.aif
NAS/Music/Chuck Berry/Chuck/06 Lady B. Goode.aif
NAS/Music/Chuck Berry/Chuck/07 She Still Loves You.aif
NAS/Music/Chuck Berry/Chuck/08 Jamaica Moon.aif
NAS/Music/Chuck Berry/Chuck/09 Dutchman.aif
NAS/Music/Chuck Berry/Chuck/10 Eyes Of Man.aif

mpc list title|grep -i wonderful
's Wonderful
S'Wonderful
Wonderful Woman


MPD 0.20.9:

mpc listall|grep -i chuck

NAS/Music/Chuck Berry/Chuck/01 Wonderful Woman.aif
NAS/Music/Chuck Berry/Chuck/02 Big Boys.aif
NAS/Music/Chuck Berry/Chuck/03 You Go To My Head.aif
NAS/Music/Chuck Berry/Chuck/04 3_4 Time (Enchiladas).aif
NAS/Music/Chuck Berry/Chuck/05 Darlin'.aif
NAS/Music/Chuck Berry/Chuck/06 Lady B. Goode.aif
NAS/Music/Chuck Berry/Chuck/07 She Still Loves You.aif
NAS/Music/Chuck Berry/Chuck/08 Jamaica Moon.aif
NAS/Music/Chuck Berry/Chuck/09 Dutchman.aif
NAS/Music/Chuck Berry/Chuck/10 Eyes Of Man.aif

mpc list title|grep -i wonderful
's Wonderful
S'Wonderful

Kind Regards,
CaptainMetal
![mpd0 19 19](https://user-images.githubusercontent.com/20752794/27286840-dc658f08-5501-11e7-96df-f9ca7495cf21.jpg)
![mpd0 20 9](https://user-images.githubusercontent.com/20752794/27286841-dc6a8256-5501-11e7-9ee2-9495840801cd.jpg)

**Comment by CaptainMetal** [comment]
oh, i forgot: there are no errors in the mpd.log listed !

both look like that:
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/01 Wonderful Woman.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/02 Big Boys.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/03 You Go To My Head.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/04 3_4 Time (Enchiladas).aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/05 Darlin'.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/06 Lady B. Goode.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/07 She Still Loves You.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/08 Jamaica Moon.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/09 Dutchman.aif
Jun 19 15:21 : update: added NAS/Music/Chuck Berry/Chuck/10 Eyes Of Man.aif

**Comment by MaxKellermann** [comment]
I asked you to post two things, and you posted **none**. I'm not interested in screenshots of an app I don't know, and I'm not interested in `listall`. These things are useless to me.

But my random guess is that you compiled MPD 0.20 without ID3 support. Prove otherwise by uploading your config.log.

**Comment by CaptainMetal** [comment]
[config.zip](https://github.com/MusicPlayerDaemon/MPD/files/1085095/config.zip)

Music Player Daemon 0.20.9

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [sidplay] sid mus str prg P00
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa roar openal pulse httpd

Encoder plugins:
 null vorbis opus flac

Input plugins:
 file alsa curl ffmpeg smbclient nfs cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify systemd tcp un

 avahi epoll icu inotify systemd tcp un

**Comment by MaxKellermann** [comment]
Brief result: my guess was wrong, and you still havn't posted what I initially asked for, so I can't help further.
