### ISSUE TITLE
a bit more agressive handling of audio output opening problems

### ISSUE THREAD

**Issue by sss123next** [MusicPlayerDaemon/MPD#651]
## Feature request

```
diff --git a/src/output/MultipleOutputs.cxx b/src/output/MultipleOutputs.cxx
index 7cdb0ef7f..9660e459c 100644
--- a/src/output/MultipleOutputs.cxx
+++ b/src/output/MultipleOutputs.cxx
@@ -195,7 +195,27 @@ MultipleOutputs::Play(MusicChunkPtr chunk)
 	assert(chunk != nullptr);
 	assert(chunk->CheckFormat(input_audio_format));
 
-	if (!Update(false))
+        //ugly hack to prevent auto pause on alsa buffer underrun
+        bool success = false;
+
+        for (short i = 0; i < 10; i++)
+        {
+            if (Update(false))
+            {
+                success = true;
+                break;
+            }
+            else
+            {
+                struct timespec s;
+                memset(&s, 0, sizeof(struct timespec));
+                s.tv_nsec = 5000000;
+                nanosleep(&s, 0);
+                Open(input_audio_format);
+            }
+        }
+
+	if (!success)
 		/* TODO: obtain real error */
 		throw std::runtime_error("Failed to open audio output");

```

this patch DOES help to prevent auto-paudsng on low-latency alsa dmix config in case of buffer underrun.

**Comment by sss123next** [comment]
also.

retry_count and retry_interval can be configurable options.

for my config 1.25ms is large enough retry interval

**Comment by MaxKellermann** [comment]
I have no idea what this is about. Please explain.

**Comment by sss123next** [comment]
Currently if audio output error occurs during playback, mpd will automatically set to "pause" state.
this hack will try to reopen audio output on errors and prevent autopausing if audio output successfully reopened.

i need this hack on low latency alsa config, it introduce one time clipping on alsa buffer underrun, but does not set player into pause state.

ideally we need 3 new options:
1. try_reopen_audio_output_on_errors (name may be better, this is global option)
2.. audio_output_retry_count
3. audio_output_retry_interval

in code above retry count set to 10 and retry interval set to 5000000 nanoseconds

**Comment by MaxKellermann** [comment]
But a buffer underrun is not an error that will stop the device. It is handled by MPD without stopping the device.
This is the code:
https://github.com/MusicPlayerDaemon/MPD/blob/d63e2c26416de3c65e4d6b71c2ef859b60372bfa/src/output/plugins/AlsaOutputPlugin.cxx#L771-L774

**Comment by MaxKellermann** [comment]
Please explain further. Your code doesn't appear to make sense, and is based on a misunderstanding - or maybe I misunderstand you, that's why I'm asking.

**Comment by sss123next** [comment]
i see, but looks like current handling of SND_PCM_STATE_XRUN does not work properly, it's not hard to reproduce, just set minimal acceptable period and buffer in dmix device


for example:

```
pcm.onboard_dmix_out {
    type dmix
    ipc_key 3216
    slave {
        channels 6
        rate 44100
        format S16_LE
        period_size 1024
            buffer_size 2048
        pcm {
            type hw
            card "Generic"
            device 0
        }
    }
}
```
