### ISSUE TITLE
MPD Group Setting Ignored

### ISSUE THREAD

**Issue by AdamDanischewski** [MusicPlayerDaemon/MPD#652]
mpd.conf:
```
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
user    "adanisch"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
group    "adanisch"
```
Yet mpd is starting up with an unknown number for the group: 
![Screenshot from 2019-09-19 13-34-31](https://user-images.githubusercontent.com/10157303/65267089-554bb600-dae2-11e9-8ab7-7f908e1ebd8a.png)

I suspect this is to be  the source of some Pulse interaction problems.

**Comment by MaxKellermann** [comment]
You deleted all parts of the bug reporting template, effectively refusing to provide the required information.
