### ISSUE TITLE
MPD won't play streams given as URL (vs IP address)

### ISSUE THREAD

**Issue by mikepierce** [MusicPlayerDaemon/MPD#656]
## Expected/Actual Behavior

After trying to play [this stream](http://radio.stereoscenic.com/am-s.mp3) via `ncmpcpp` I get an error and the stream does not play. Trying all the streams I have saved, it looks like **MPD will only play streams listed as IP-ADDRESS:PORT but not the ones that use a typical URL**. So it won't play anything like  [http://radio.stereoscenic.com:80/am-s.mp3](http://radio.stereoscenic.com:80/am-s.mp3) but it will play [http://198.27.120.235:8850](http://198.27.120.235:8850).

## Version

The version of MPD I have installed is 0.20.18. This is not an issue in version 0.19.12. Here's the MPD version information.

```
Music Player Daemon 0.20.18

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un
```

Aside issue I tried to compile the latest MPD from source as [instructed here](https://www.musicpd.org/doc/html/user.html) to see if this is still an issue, but ran into issues just doing that.

     meson_options.txt:5:0: ERROR: Unknown type feature.  

If you want me to try this on the latest MPD, I'll need to be instructed how to get past that. 

## Log

```
Sep 30 08:29 : client: [0] process command "status"
Sep 30 08:29 : client: [0] command returned 0
Sep 30 08:29 : client: [0] process command "idle"
Sep 30 08:29 : client: [0] command returned 1
Sep 30 08:29 : exception: Failed to decode http://radio.stereoscenic.com:80/asp-s.mp3
Sep 30 08:29 : exception: nested: CURL failed: Resolving timed out after 10009 milliseconds
Sep 30 08:29 : player: played "http://radio.stereoscenic.com:80/asp-s.mp3"
Sep 30 08:29 : playlist: stop
Sep 30 08:29 : client: [0] process command "status"
Sep 30 08:29 : client: [0] command returned 0
Sep 30 08:29 : client: [0] process command "idle"
Sep 30 08:29 : client: [0] command returned 1
```

**Comment by MaxKellermann** [comment]
Your MPD version is too old and unsupported.

**Comment by mikepierce** [comment]
@MaxKellermann Yep. *But* has this issue come up before? (So it's likely fixed in the latest version?) Also, I tried to compile the latest version myself and see, and ran into an issue fairly immediately:

     meson_options.txt:5:0: ERROR: Unknown type feature.

**Comment by MaxKellermann** [comment]
I have no idea, and I choose not to read any further when it's about an old version. This is just a waste of time, just like speculation whether this has been fixed at some point. Maybe it is, maybe not, but that's up to you to find out.
Your build failure is off-topic in this bug report, and is not an excuse for reporting problems with an old version. And I bet it's because you have a Meson version older than the one documented to be required by MPD.
