### ISSUE TITLE
[protocol specification] currentsong response format

### ISSUE THREAD

**Issue by nmeum** [MusicPlayerDaemon/MPD#658]
If been working on a server implementation of the MPD protocol and ran into serval issues with the protocol specification. In general, it often seems ambiguous and incomplete to me. One of the things I find especially annoying is that output formats are often not specified. Consider the specification of the currentsong command:

```
:command:`currentsong`
    Displays the song info of the current song (same song that is identified in status).
```

The specification doesn't define how "the song info of the current song" is encoded and what information must be present which renders this command definition somewhat useless. Not sure if you are interested in issues regarding the protocol specification, thus I didn't report any other issues I encountered so far.

**Comment by MaxKellermann** [comment]
Certainly the protocol documentation is less specific and less complete than we would wish it to be. What you found is one such thing, but you can easily find out the output format by reading MPD's response; after that, please submit a PR to improve the documentation.
I see little value in tracking each missing piece of the documentation here, when submitting PRs is so much more productive. (Unless the missing piece is not immediately obvious from MPD's implemented behavior and you can't figure out what to write in your PR.)
