### ISSUE TITLE
Support For HTTPS Remote File

### ISSUE THREAD

**Issue by wes1993** [MusicPlayerDaemon/MPD#659]
## Feature request
Hello!! Can you add the support for HTTPS in the LibCurl library?
I have tried to run the audio but I got this error...

playlist: play 0:"hxxps://example.com/file.mp3" client: [0] command returned 0 exception: Failed to decode hxxps://example.com/file.mp3 exception: nested: CURL failed: Protocol "https" not supported or disabled in libcurl

Stefano

**Comment by MaxKellermann** [comment]
This is a property of your CURL build, not of MPD.

**Comment by wes1993** [comment]
Ok thanks a lot Max
