### ISSUE TITLE
parallel output in order to compare DAC's

### ISSUE THREAD

**Issue by seniorgod** [MusicPlayerDaemon/MPD#661]
I think about buying a new rpi with allo usbridge and allo digione. In that case i have a clean usb output and clean SPDIF single ended output. I plant that in order to tests the quality of different DACS and/or different inputs at one DAC's. 
Simple Questions: 
1. Can MPD send the sound to more than one of the configured outputs in parallel?
2. Do i have to Setup two running mpd's for that? 

thanks in advance.

**Comment by MaxKellermann** [comment]
Yes, no.
