### ISSUE TITLE
#charset=cp949 at the end of URL doesn't work.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#675]
mpd 0.21.16

According to https://www.musicpd.org/doc/html/user.html#icy-metadata

```
mpc add 'http://vviii.saycast.com#charset=cp949'
mpc add 'http://youliyouli.inlive.co.kr#charset=cp949'
mpc add 'http://www.mukulcast.com#charset=cp949'
mpc play
```

should make mpd use cp949 character set, but mpd doesn't actually use cp949.

I see broken characters.

```
> mpc -f %name%
?? ?? ?ֽŰ??? ????Ʈ Top100 ???ۡ??ܡ? ??
> mpc -f %title%
Here I Am - ?¿?
```

**Comment by MaxKellermann** [comment]
This is a new 0.22 feature, but you're using 0.21.
