### ISSUE TITLE
#charset=xxx doesn't make mpd decode stream metadata with xxx charset.

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#676]
mpd https://github.com/MusicPlayerDaemon/MPD/commit/3f4437266bd4dc64a19a59d83cdca9be493b243a

```
> mpc add http://youliyouli.inlive.co.kr#charset=cp949
> mpc play
http://youliyouli.inlive.co.kr#charset=cp949
> mpc -f %title%
강용욱 - 잎새에스치는바람
> mpc -f %name%
?????ѹ߶???
```

If mpd receives any metadata other than %title% and %name%, it should be decoded from xxx charset.

**Comment by MaxKellermann** [comment]
Your bug report is incomplete. You were asked to
> Paste the output of "mpd --version" here

but you refused to do so.

**Comment by crocket** [comment]
```
> mpd --version
Music Player Daemon 0.22~git (0.22~git)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local udisks


Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo alsa httpd

Encoder plugins:
 null vorbis opus flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg mms

Playlist plugins:
 extm3u m3u pls flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// srtp:// tidal://

Other features:
 dbus udisks epoll icu inotify ipv6 tcp un
```

**Comment by MaxKellermann** [comment]
> If mpd receives any metadata other than %title% and %name%, it should be decoded from xxx charset.

So you don't want "title" and "name" to be decoded with the specified charset. This is what your sentence says, logically.
Correct?

But if you want to exclude those two tags, why are those the only ones you paste?

This whole bug report is bad. You removed all sections from the bug reporting template, and wrote some confusing contradictory text.

**Comment by crocket** [comment]
> So you don't want "title" and "name" to be decoded with the specified charset. This is what your sentence says, logically.
Correct?

I want the opposite. I want every metadata received from streams to be decoded with `#charset=xxx`.

**Comment by MaxKellermann** [comment]
So *everything* was wrong with your bug report. You want the opposite of what your text says.
Let's start from scratch. Write a proper bug report. Because I still don't understand what's wrong.

**Comment by crocket** [comment]
My sentences could have been less ambiguous.
