### ISSUE TITLE
M3U extended informations are overwritten when updating a playlist.

### ISSUE THREAD

**Issue by jeanbruder** [MusicPlayerDaemon/MPD#677]
### Describe the bug
When a playlist is loaded in GMPC and if containing EXTM3U informations (Ex: the name of the Internet Radio related to the following URL), when a new URL is added, all the EXTM3U informations are lost.

## Expected Behavior
New URL added and no EXTM3U informations lost. An improvement could be to add the URL AND add the name of the Stream (Ex:  Internet Radio).

## Actual Behavior
URL added to the playlist and all the EXTM3U informations are lost.

## Version

GMPC 11.8.16

## Log

No log available.

**Comment by crocket** [comment]
This issue is not unique to GMPC. For now, you can work around the issue by updating playlist manually in a text editor.

**Comment by MaxKellermann** [comment]
I have no idea how this is related to MPD, but since you only named the gmpc version and refused to provide a verbose MPD log, I must assume this doesn't belong here. (If you disagree, write a better bug report.)
