### ISSUE TITLE
Unable to override main conf with include

### ISSUE THREAD

**Issue by poofyteddy** [MusicPlayerDaemon/MPD#684]
### Describe the bug
if you set the setting of the main config file (/etc/mpd.conf) and in an included config file, with the goal of having the later override the former. MPD refuse to start.

I'll consider this a bug, since it is usually recommended to never edit the package config file if it support an include of some sort. Feel free to change it into a feature request

Thank's !
## Expected Behavior
MPD service support overriding config, and boot

## Actual Behavior
MPD service throw an exception and exit with a code 1

## Version
`Music Player Daemon 0.21.16 (debian/0.21.13-1-7-gc23b89d+)`

## Log
```
nov. 23 22:32:16 localhost systemd[1]: Starting Music Player Daemon...
nov. 23 22:32:22 localhost mpd[2557]: exception: Error in /etc/mpd.conf line 423
nov. 23 22:32:22 localhostmpd[2557]: exception: nested: Error in /etc/mpd.d/salt.conf line 10
nov. 23 22:32:22 localhost mpd[2557]: exception: config parameter "zeroconf_name" is first defined on line 163 and redefined on line 10
nov. 23 22:32:22 localhost systemd[1]: mpd.service: Main process exited, code=exited, status=1/FAILURE
nov. 23 22:32:22 localhost systemd[1]: mpd.service: Failed with result 'exit-code'.
nov. 23 22:32:22 localhost systemd[1]: Failed to start Music Player Daemon.
```
same error without going through systemd

**Comment by MaxKellermann** [comment]
4f11fa0d419af1c911e2dd5caa9d8e6ebe7e4027

**Comment by poofyteddy** [comment]
Thank-you very much for this.
