### ISSUE TITLE
'modified-since': Failed to parse time stamp

### ISSUE THREAD

**Issue by vestingz** [MusicPlayerDaemon/MPD#685]
Hi everyone,

`mpc search '(modified-since 20191112T221010+0100)'` results in error message `MPD error: Failed to parse time stamp`, while `mpc search '(modified-since 20191112)'` works as expected.
It seems like mpc does not fully support ISO 8601 timestamps. Is this the expected behaviour?

Best

PS: Thank you very much for this software! :)

**Comment by MaxKellermann** [comment]
This is a server-side problem, and has nothing to do with mpc.
What's your MPD version?

**Comment by vestingz** [comment]
`mpd --version` returns `Music Player Daemon 0.21.16 (0.21.16)`.

**Comment by vestingz** [comment]
Thank you :)
