### ISSUE TITLE
MPD don't run on Android x86

### ISSUE THREAD

**Issue by ProfOrribilus** [MusicPlayerDaemon/MPD#69]
Hello.

I tried to run [MPD for Android](https://play.google.com/store/apps/details?id=org.musicpd) on [Android x86 4.4-r5](http://www.android-x86.org/releases/releasenote-4-4-r5) installed on an [ASUS R51RL notebook](https://www.asus.com/Laptops/X51RL/specifications/), but it gives the following error message:
![screenshot_2017-06-23-12-54-36](https://user-images.githubusercontent.com/4707084/27483500-f96086fe-5825-11e7-972c-10b17bab226d.png)

What's the problem? Does it need an fix dedicated to Android-x86?

Thanks for your work.

**Comment by MaxKellermann** [comment]
No, it just needs to be built for that architecture. Right now, I only build for ARM, and adding more architectures requires adjusting the build scripts, which then need to run multiple times, once for each architecture. Not too hard to do, just lots of fiddling.

**Comment by ProfOrribilus** [comment]
Ok, thanks.

**Comment by MaxKellermann** [comment]
The 0.20.21 APK contains builds for ARMv7, Aarch64 and x86.
