### ISSUE TITLE
mpd.log return codes undocumented

### ISSUE THREAD

**Issue by adamf663** [MusicPlayerDaemon/MPD#693]
I've searched through too many mpd related sites for documentation on the return codes in the mpd.log file and found nothing.

When mpd.log has something like 
... process command "albumart "file.mp3" 0"
... command returned 3

What does the 3 mean?  How does that differ from when the command returns 0?

**Comment by MaxKellermann** [comment]
These are debug messages and not meant for users to understand (and therefore not documented in the manual). But if you really want to know, look it up in the source code:
https://github.com/MusicPlayerDaemon/MPD/blob/master/src/command/CommandResult.hxx

**Comment by adamf663** [comment]
Why do you even have log files if you don't think users are meant to use them?
How pray tell, is a user supposed to troubleshoot and diagnose problems like not getting artwork served if the contents of the log files are only for developers?
Would adding ten lines to your documentation really break the bank?

**Comment by MaxKellermann** [comment]
> Why do you even have log files if you don't think users are meant to use them?

This isn't a regular log message. This is a debug line, meant for developers. MPD logs those only in "verbose" mode, which is for troubleshooting.

>  How pray tell, is a user supposed to troubleshoot and diagnose problems like not getting artwork served if the contents of the log files are only for developers?

The number doesn't help with that. But your assumption which your question is based on is already wrong. Contents of log files are not "only for developers". But debug logs are "only for developers".

>  Would adding ten lines to your documentation really break the bank?

Yes, but the reason is not the number of lines. These numbers are not "stable". They can change in every minor MPD release, and they actually did. They are an internal implementation detail.

**Comment by adamf663** [comment]
If mpd.log can't be used for troubleshooting transactional success/failures, what is available for the task?

is the user expected to use the shotgun approach and just change things willynilly in the hope that some problem goes away?


----- Original Message -----
> From: "Max Kellermann" <notifications@github.com>
> To: "MusicPlayerDaemon/MPD" <MPD@noreply.github.com>
> Cc: "adamf663" <adam.github@thefelsons.us>, "Author" <author@noreply.github.com>
> Sent: Monday, December 16, 2019 2:58:10 PM
> Subject: Re: [MusicPlayerDaemon/MPD] mpd.log return codes undocumented (#693)

>> Why do you even have log files if you don't think users are meant to use them?
> 
> This isn't a regular log message. This is a debug line, meant for developers.
> MPD logs those only in "verbose" mode, which is for troubleshooting.
but apparently not for users to troubleshoot issues.

**Comment by MaxKellermann** [comment]
> If mpd.log can't be used for troubleshooting transactional success/failures, what is available for the task?

The command response!

The line containing that number contains less than that. So there's really no reason to argue about this line or this number. And this is all this issue report is about - remember, you chose to make it not about your albumart problem.
