### ISSUE TITLE
MPD Alsa (null device) stops playback and crashes

### ISSUE THREAD

**Issue by kaifisher** [MusicPlayerDaemon/MPD#695]
## Description of Bug
I had previously set up MPD to use jack and an alsa null pcm device with a hardware mixer set to my playback card. This had allowed me to have mpd clients change the alsa hardware volume even though I was using jack - quite useful.

Recently this stopped working on recent versions of MPD. When the alsa (null pcm) output is turned on the playback stops and is silent. The playback seems to loop over and over a (roughly) 2s stretch of audio but silently. When the alsa (null pcm) output is then turned off MPD stops responding.

MPD has to be killed, restarted and the alsa (null pcm) output disabled before playback is started to avoid further crashes.

## Expected Behavior
Playback would continue as normal on all MPD outputs. Volume control would work via the alsa mixer.

## Actual Behavior
Described above.

## Version
Music Player Daemon 0.21.16 (0.21.16)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao openal jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa curl ffmpeg smbclient mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus epoll icu inotify ipv6 systemd tcp un

## Log
Dec 18 23:20 : avahi: Initializing interface
Dec 18 23:20 : avahi: Client changed to state 101
Dec 18 23:20 : avahi: Client is CONNECTING
Dec 18 23:20 : state_file: Loading state file /var/lib/mpd/state
Dec 18 23:20 : client: [0] opened from [::1]:34534
Dec 18 23:20 : client: [1] opened from [::1]:34536
Dec 18 23:20 : client: [1] process command "channels"
Dec 18 23:20 : client: [1] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "replay_gain_mode auto"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "stats"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "lsinfo "mpd-client://cantata/2.3.3""
Dec 18 23:20 : exception: Unsupported URI scheme
Dec 18 23:20 : client: [0] command returned 2
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "playlistinfo"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "stats"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "urlhandlers"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "tagtypes"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "commands"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "playlistinfo"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "outputs"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "currentsong"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "listplaylists"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "listplaylistinfo "[Radio Streams]""
Dec 18 23:20 : exception: Failed to open '/var/lib/mpd/playlists/[Radio Streams].m3u': No such file or directory
Dec 18 23:20 : exception: No such playlist
Dec 18 23:20 : client: [0] command returned 2
Dec 18 23:20 : client: [0] process command "playlistinfo"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "outputs"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "playid "21""
Dec 18 23:20 : playlist: play 13:"Adele - 2011 - 21/09, One and Only.flac"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : decoder_thread: probing plugin flac
Dec 18 23:20 : decoder: audio_format=44100:16:2, seekable=true
Dec 18 23:20 : exception: bind to '0.0.0.0:8000' failed (continuing anyway, because binding to '[::]:8000' succeeded): Failed to bind socket: Address already in use
Dec 18 23:20 : jack_output: Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Dec 18 23:20 : jack_output: This system has no accessible HPET device (Device or resource busy)
Dec 18 23:20 : alsa_output: opened null type=NULL
Dec 18 23:20 : alsa_output: buffer: size=1..189408057 time=22..4294967279
Dec 18 23:20 : alsa_output: period: size=1..189408058 time=22..4294967295
Dec 18 23:20 : alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
Dec 18 23:20 : alsa_output: format=S16_LE (Signed 16 bit Little Endian)
Dec 18 23:20 : alsa_output: buffer_size=22050 period_size=5512
Dec 18 23:20 : output: opened "alsaVolControl" (alsa) audio_format=44100:16:2
Dec 18 23:20 : output: opened "Front" (jack) audio_format=48000:f:2
Dec 18 23:20 : libsamplerate: setting samplerate conversion ratio to 1.09
Dec 18 23:20 : output: converting in=44100:16:2 -> f=44100:16:2 -> out=48000:f:2
Dec 18 23:20 : output: opened "MPD HTTP Flac" (httpd) audio_format=44100:16:2
Dec 18 23:20 : replay_gain: replay gain mode has changed off->track
Dec 18 23:20 : replay_gain: scale=1.000000
Dec 18 23:20 : replay_gain: scale=0.353997
Dec 18 23:20 : replay_gain: replay gain mode has changed off->track
Dec 18 23:20 : replay_gain: replay gain mode has changed off->track
Dec 18 23:20 : replay_gain: scale=1.000000
Dec 18 23:20 : replay_gain: scale=1.000000
Dec 18 23:20 : replay_gain: scale=0.353997
Dec 18 23:20 : replay_gain: scale=0.353997
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "currentsong"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : state_file: Saving state file /var/lib/mpd/state
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "setvol "43""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "setvol "43""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "41""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "40""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "38""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "37""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "35""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "34""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "33""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "31""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "30""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "28""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "27""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "26""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "24""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "23""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "21""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "20""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "19""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "17""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "16""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "14""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "13""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "12""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "10""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "9""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "7""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "6""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "4""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "3""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "2""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "0""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "0""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "replay_gain_status"
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [1] process command "idle"
Dec 18 23:20 : client: [1] command returned 1
Dec 18 23:20 : client: [0] process command "setvol "43""
Dec 18 23:20 : client: [0] command returned 0
Dec 18 23:20 : client: [0] process command "stop"
Dec 18 23:20 : playlist: stop
Dec 18 23:20 : player: played "Adele - 2011 - 21/09, One and Only.flac"

**At this point I have to kill MPD - it stops responding.

## mpd.conf 

music_directory				"/mnt/music"
playlist_directory		"/var/lib/mpd/playlists"
db_file			"/var/lib/mpd/database"
log_file			"syslog"
pid_file			"/var/lib/mpd/pid"
state_file			"/var/lib/mpd/state"
user				"mythtv"
group				"audio"
bind_to_address		"any"
port				"6600"
log_level			"default"
auto_update	"no"
zeroconf_enabled		"yes"
zeroconf_name			"mpd"
audio_output {
	type			"alsa"
	name			"alsaVolControl"
	format			"44100:16:2"
	replay_gain_handler	"software"	#software, mixer, none
	device			"null"
	mixer_type		"hardware"	#hardware, software, none
	mixer_device		"PCH"
	mixer_control		"Master"
	auto_resample		"no"		#yes, no
	auto_channels		"no"		#yes, no
	auto_format		"no"		#yes, no
}

audio_output {
	type			"jack"
	name			"Front"
	#format
	replay_gain_handler	"software"
	client_name		"MPD"
	autostart		"no"
	source_ports		"left,right"
	destination_ports	"jackPipe:in1_FL,jackPipe:in2_FR"
	mixer_type		"none"
}

audio_output {
	type			"jack"
	name			"HP"
	client_name		"MPD HP"
	autostart		"no"
	source_ports		"left,right"
	destination_ports	"jackHPPipe:in1_HPL,jackHPPipe:in2_HPR"
}

audio_output {
	type			"jack"
	name			"Surround"
	client_name		"MPD Surround"
	autostart		"no"
	source_ports		"left,right"
	destination_ports	"jackPipe:in4_SL,jackPipe:in5_SR"
}

audio_output {
	type			"httpd"
	name			"MPD HTTP Flac"
	encoder			"flac"
	#encoder		"wave"
	#encoder		"vorbis"
	port			"8000"
	#quality		"5.0"	#do not define if bitrate is defined
	#bitrate		"256"	#do not define if quality is defined
	format			"44100:16:2"
	always_on		"yes"
	tags			"yes"
}

audio_output {
	type			"httpd"
	name			"MPD HTTP Vorbis"
	encoder			"vorbis"
	port			"8001"
	quality			"10.0"	#do not define if bitrate is used
	#bitrate		"256"	#do not define if quality is used
	format			"44100:16:2"
	always_on		"yes"
	tags			"yes"
}

samplerate_converter		"Best Sinc Interpolator"
replaygain			"auto"
replaygain_preamp		"0"
replaygain_missing_preamp	"0"
replaygain_limit		"no"

filesystem_charset "UTF-8"

## coredump

#0  0x00007fffeda22a5c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055555559f591 in PosixCond::wait (mutex=..., this=0x5555556ffcd0)
    at ../mpd-0.21.16/src/thread/PosixCond.hxx:74
#2  PlayerControl::ClientWait (this=0x5555556ffc30)
    at ../mpd-0.21.16/src/player/Control.hxx:397
#3  PlayerControl::WaitCommandLocked (this=<optimized out>)
    at ../mpd-0.21.16/src/player/Control.hxx:444
#4  PlayerControl::SynchronousCommand (cmd=PlayerCommand::CLOSE_AUDIO, this=0x5555556ffc30)
    at ../mpd-0.21.16/src/player/Control.hxx:459
#5  PlayerControl::LockSynchronousCommand (cmd=PlayerCommand::CLOSE_AUDIO, 
    this=0x5555556ffc30) at ../mpd-0.21.16/src/player/Control.hxx:471
#6  PlayerControl::LockStop (this=0x5555556ffc30)
    at ../mpd-0.21.16/src/player/Control.cxx:91
#7  0x00005555555a620e in playlist::Stop (this=0x5555556ffb98, pc=...)
    at ../mpd-0.21.16/src/queue/PlaylistControl.cxx:40
#8  0x000055555558efae in Partition::Stop (this=<optimized out>)
    at ../mpd-0.21.16/src/Partition.hxx:146
#9  handle_stop (client=..., args=..., r=...)
    at ../mpd-0.21.16/src/command/PlayerCommands.cxx:85
#10 0x000055555558e014 in command_process (client=..., num=num@entry=0, 
    line=line@entry=0x5555559672d0 "stop") at ../mpd-0.21.16/src/command/AllCommands.cxx:418
#11 0x0000555555596dbf in client_process_line (client=..., line=<optimized out>, 
    line@entry=0x5555559672d0 "stop") at ../mpd-0.21.16/src/client/ClientProcess.cxx:133
#12 0x0000555555597069 in Client::OnSocketInput (this=0x5555559672a0, data=0x5555559672d0, 
    length=<optimized out>) at ../mpd-0.21.16/src/client/ClientRead.cxx:46
#13 0x00005555555bf539 in BufferedSocket::ResumeInput (this=<optimized out>)
    at ../mpd-0.21.16/src/event/BufferedSocket.cxx:76
#14 BufferedSocket::ResumeInput (this=0x5555559672a0)
    at ../mpd-0.21.16/src/event/BufferedSocket.cxx:65
#15 0x00005555555bf6e8 in BufferedSocket::OnSocketReady (flags=<optimized out>, 
    this=0x5555559672a0) at ../mpd-0.21.16/src/event/BufferedSocket.cxx:113
#16 BufferedSocket::OnSocketReady (this=0x5555559672a0, flags=<optimized out>)
    at ../mpd-0.21.16/src/event/BufferedSocket.cxx:101
#17 0x00005555555c287f in EventLoop::Run (this=0x5555556ff548)
    at ../mpd-0.21.16/src/event/Loop.cxx:214
#18 0x000055555558cdac in mpd_main_after_fork (config=..., raw_config=...)
    at ../mpd-0.21.16/src/Main.cxx:600
#19 MainOrThrow (argc=<optimized out>, argv=<optimized out>)
    at ../mpd-0.21.16/src/Main.cxx:476
#20 0x000055555558d41a in mpd_main (argc=<optimized out>, argv=<optimized out>)
    at ../mpd-0.21.16/src/Main.cxx:487
#21 0x00007fffed6c7927 in __libc_start_main () from /lib64/libc.so.6
#22 0x000055555558c4ea in _start () at ../mpd-0.21.16/src/Main.cxx:382

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/html/user.html#mpd-crashes

> Nothing relevant shows in logs.

Your perception of relevance is not helpful. Leave that decision to the develper trying to figure out your bug report. There must be something relevant, but you might not be able to recognize it.

**Comment by kaifisher** [comment]
I included an example log above.

**Comment by MaxKellermann** [comment]
And you're aware that I'm still waiting for more necessary information?

**Comment by kaifisher** [comment]
What do you mean? What else can I provide? I'm not sure what you need.

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/html/user.html#mpd-crashes

**Comment by kaifisher** [comment]
I've included mpd.conf with all the commented text removed - above. Hope that's what you need. Thanks

**Comment by MaxKellermann** [comment]
That's also helpful, but that's not what I asked of you.

**Comment by kaifisher** [comment]
Ah. A back-trace will take a while. need to recompile a bunch of stuff and kernel. Not really my forte. But I'll try.

**Comment by kaifisher** [comment]
OK. I think I've got the coredump. Since MPD doesn't actually exit / crash per-se i had to kill it. Not sure if what I've attached is what is needed.
