### ISSUE TITLE
Compilation error (fall through)

### ISSUE THREAD

**Issue by Wang-Yue** [MusicPlayerDaemon/MPD#698]
```
[421/560] Compiling C object 'src/util/ed6d25d@@util@sta/format.c.o'.
FAILED: src/util/ed6d25d@@util@sta/format.c.o 
cc -Isrc/util/ed6d25d@@util@sta -Isrc/util -I../../src/util -Isrc -I../../src -I. -I../../ -I/usr/local/opt/expat/include -Xclang -fcolor-diagnostics -DNDEBUG -pipe -Wall -Winvalid-pch -std=c99 -O2 -g -Wall -Wextra -Wvla -fvisibility=hidden -ffast-math -ftree-vectorize -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wcast-qual -Wwrite-strings -pedantic -ffunction-sections -fdata-sections -D_GNU_SOURCE -MD -MQ 'src/util/ed6d25d@@util@sta/format.c.o' -MF 'src/util/ed6d25d@@util@sta/format.c.o.d' -o 'src/util/ed6d25d@@util@sta/format.c.o' -c ../../src/util/format.c
../../src/util/format.c:242:4: error: expected expression
                        gcc_fallthrough;
                        ^
../../src/util/Compiler.h:149:25: note: expanded from macro 'gcc_fallthrough'
#define gcc_fallthrough [[fallthrough]]
                        ^
1 error generated.
[426/560] Compiling C++ object 'mpd@exe/src_db_update_Archive.cxx.o'.
ninja: build stopped: subcommand failed.


$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


$ uname  -a
Darwin wangyue-macbookpro.roam.corp.google.com 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
```
latest xcode version.

**Comment by jacobvosmaer** [comment]
I have the same problem.

```
$ cc --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I suspect a1afe9afc6879960389491b6fb587f14ae1ae5df or 7770298a65e4c08eea1645abb121731867414488 have something to do with this.

**Comment by jacobvosmaer** [comment]
Reading this test, I wonder if we need a special compiler flag to make the double square brackets valid?

https://github.com/llvm-mirror/clang/blob/master/test/Sema/c2x-fallthrough.c

`-fdouble-square-bracket-attributes`

**Comment by jacobvosmaer** [comment]
No that's probably not it, we have old double square brackets in https://github.com/MusicPlayerDaemon/MPD/blob/master/src/config/Block.hxx

**Comment by jacobvosmaer** [comment]
I get the impression double square bracket attributes are a C++ feature. The file that is failing to compile is a C file. ?

**Comment by jacobvosmaer** [comment]
I found this [article about -Wimplicit-fallthrough](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/) which says that

> There is a proposal to add the [[...]] attribute syntax to C2X http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2052.pdf

This sounds an awful lot like `[[fallthrough]]` is C++-only. I wonder if we should just delete it from format.c.

**Comment by jacobvosmaer** [comment]
Fixed via https://github.com/MusicPlayerDaemon/MPD/commit/dca0519336586be95b920004178114a097681768
