### ISSUE TITLE
How to fix such messages - ffmpeg/flac or mp3: Could not find codec parameters

### ISSUE THREAD

**Issue by cmoulliard** [MusicPlayerDaemon/MPD#702]
## Question

I'm using mpd packaged which is packaged/installed with volumio2 and when it is started, I see these messages: 

```
Jan 02 10:08 : ffmpeg/flac: Could not find codec parameters (Audio: flac, 0 channels)
Jan 02 10:08 : ffmpeg/flac: Estimating duration from bitrate, this may be inaccurate
...
Jan 02 10:08 : mpg123: mpg123_getformat() failed: Message: I am done with this track.
Jan 02 10:08 : ffmpeg/mp3: Header missing
Jan 02 10:08 : ffmpeg/mp3: Could not find codec parameters (Audio: mp3, 0 channels, s16p)
Jan 02 10:08 : ffmpeg/mp3: Estimating duration from bitrate, this may be inaccurate
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 4092.
```

What should we do to fix them ?

Gist file containing the log and mpd version: https://gist.github.com/cmoulliard/cc3341cb9668dca4760978d94a9f68f6

**Comment by MaxKellermann** [comment]
You're not using MPD as published by this project, but a modified MPD fork. Sorry, it's impossible for me to support this fork. You should ask the maintainer of the fork for support.
However, in this case, it looks like the message is generated by the FFmpeg library, and not by MPD. Thus, the FFmpeg project is the best place to ask.
