### ISSUE TITLE
(Feature) Stop the playing at the end of the current track !

### ISSUE THREAD

**Issue by minitchoup** [MusicPlayerDaemon/MPD#705]
Hello,
- Can you add the possibility to stop the playing at the end of the current track ?
- Can you add the possibility of stopping the reading with a progressive reduction of the volume ?
Good job.
Thank you very much.
GMPC V11.8.13 (Debian 10)

**Comment by MaxKellermann** [comment]
>     * Can you add the possibility to stop the playing at the end of the current track ?

This feature was added already 10 years ago, it's called "single" mode. (`mpc single`)

>     * Can you add the possibility of stopping the reading with a progressive reduction of the volume ?

What does that mean?
