### ISSUE TITLE
Add FDK-AAC support

### ISSUE THREAD

**Issue by neheb** [MusicPlayerDaemon/MPD#706]
## Feature request

FDK-AAC has the advantage of being included in Fedora, meaning it has no patented functionality there. This is not the case with ffmpeg or faad.

**Comment by MaxKellermann** [comment]
What is it and which library supports it?

**Comment by neheb** [comment]
https://github.com/mstorsjo/fdk-aac

To clarify, Fedora and OpenWrt have a version of fdk-aac with all the patented functionality removed. This means that only AAC-LC can be decoded.

**Comment by MaxKellermann** [comment]
Sorry, FDK-AAC's license is incompatible with the GPL (which MPD uses), so it would be illegal (copyright violation).
See https://trac.ffmpeg.org/wiki/Encode/AAC and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=694257

**Comment by neheb** [comment]
Ah bugger.
