### ISSUE TITLE
build error: [...]../arm-linux-androideabi/bin/ld: error: cannot find -lc++

### ISSUE THREAD

**Issue by Yetangitu** [MusicPlayerDaemon/MPD#707]
I'm working my way through building mpd for Android to target older devices (now at 4.4 - kitkat) as the available APK's all seem to target 5.0 and higher. After gleaning the build incantation from FDroid (since this is not described in the documentation as far as I can see?) it goes mostly OK until it hits a wall in trying to link libmpd.so:

```
/home/frank/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ \
 -o libmpd.so  <lots_of_stuff/>  -Wl,-rpath-link,/var/src/MPD/MPD/output/android/src/java

/home/frank/Android/Sdk/ndk/20.1.5948944/toolchains/arm-linux-androideabi-4.9/ \
prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x \
/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++
```
Is this a known problem, possibly related to my attempt to build for a lower API level? The ndk does contain prebuilt versions of the needed library, albeit with versioned names:

```
ls  /home/frank/Android/Sdk/ndk/20.1.5948944/ \
   sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/
libandroid_support.a  libc++.a.20  libc++.a.25  libc++.so.16  libc++.so.21  libc++.so.26      libc++_static.a
libc++.a.16           libc++.a.21  libc++.a.26  libc++.so.17  libc++.so.22  libc++.so.27      libc++abi.a
libc++.a.17           libc++.a.22  libc++.a.27  libc++.so.18  libc++.so.23  libc++.so.28      libunwind.a
libc++.a.18           libc++.a.23  libc++.a.28  libc++.so.19  libc++.so.24  libc++.so.29
libc++.a.19           libc++.a.24  libc++.a.29  libc++.so.20  libc++.so.25  libc++_shared.so
```

...and it has the right search path set to find them... but it won't. There is no direct reference to `libc++` in the linker invocation so is infers this dependency from one of the linked files - which is unclear.

**Comment by Yetangitu** [comment]
https://github.com/android/ndk/issues/951

Probably related, some of the comments are _Stop passing --sysroot_ (https://github.com/android/ndk/issues/951#issuecomment-480343419) and _Don't pass -gcc-toolchain_ (https://github.com/android/ndk/issues/951#issuecomment-483838236) as well as some general comments on how this situation can arise in https://github.com/android/ndk/issues/951#issuecomment-501017894:

> I think there are two ways that you can get into this state:
> 
> - You've only partially migrated to the new toolchain format. That seems to be what the OP has done (please correct me if I'm wrong; I'm relying on command line forensics with that guess) by switching to the triple-prefixed Clangs, but still keeping all the old flags. Partial migrations are very likely to run into these sorts of problems, and it's best to just clean up all your flags at the same time.
> -  You haven't started migrating at all, but now your build is broken. Presumably the reason this happens because your build wasn't passing -nostdlib++ in prior releases. This flag is fairly new and the result of not passing it was fairly innocuous (even ndk-build and the CMake toolchain didn't do this until somewhat recently), so it was easy to forget. However it's something that you should be using if you're manually linking libc++. If you just add that flag that should let you continue using NDK r20 without more involved modifications to your build system (though you'll want to start looking into this soon, I'm guessing that r22 will be the release that does away with the legacy paths)._

**Comment by Yetangitu** [comment]
More FYI, the build succeeds when using NDK v18.1 so this problem is related to the issue mentioned above.

**Comment by MaxKellermann** [comment]
8c31370534a7c76aea243fb2ef4935f418f079cf
