### ISSUE TITLE
(modified-since 'VALUE') filter fails in 0.21.18

### ISSUE THREAD

**Issue by geneticdrift** [MusicPlayerDaemon/MPD#709]
## Bug report
Filtering with the new filter syntax fails for `modified-since`:
<pre>
OK MPD 0.21.11
find modified-since 1578941504
OK
find (modified-since '1578941504')
ACK [5@0] {} Invalid unquoted character
find (modified-since '2020-01-13')
ACK [5@0] {} Invalid unquoted character
find (modified-since "2020-01-13")
ACK [5@0] {} Space expected after closing '"'
</pre>

## Version

Music Player Daemon 0.21.18 (0.21.18)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log

<pre>
client: [8] opened from 127.0.0.1:34636
client: [8] process command "find modified-since 1578941504"
client: [8] command returned 0
client: [8] process command "find (modified-since '1578941504')"
exception: Invalid unquoted character
client: [8] command returned 2
client: [8] process command "find (modified-since '2020-01-13')"
exception: Invalid unquoted character
client: [8] command returned 2
client: [8] process command "find (modified-since "2020-01-13")"
exception: Space expected after closing '"'
client: [8] command returned 2
</pre>

**Comment by geneticdrift** [comment]
But with quotes around the filter expression  it does work:
<pre>
find "(modified-since '2020-01-13')" 
OK
</pre>

So may be just missed the documentation to quote the filter expression.

**Comment by MaxKellermann** [comment]
> So may be just missed the documentation to quote the filter expression.

No, it's not missing. It's right here https://www.musicpd.org/doc/html/protocol.html#requests

> If arguments contain spaces, they should be surrounded by double quotation marks.

And https://www.musicpd.org/doc/html/protocol.html#escaping-string-values mentions again that command parameters must be enclosed in double quotes.

This bug report is bogus.
