### ISSUE TITLE
IceCast streams still can not convert cp1251

### ISSUE THREAD

**Issue by AndriiZ** [MusicPlayerDaemon/MPD#716]
This is related to https://github.com/MusicPlayerDaemon/MPD/issues/616

I have built latest mpd from sources, but when I add http://radio.svoboda.fm:5555/128.mp3#charset=cp1251, I still receive ????? instead of proper characters. Am I missing something? How to enable icu support for building from source?

/media/usb/src/mpd-0.21.19/output $ /opt/bin/mpd -V
Music Player Daemon 0.21.19 (0.21.19)

/media/usb/src/mpd-0.21.19/output $ mpc -p 6601 add http://radio.svoboda.fm:5555/128.mp3#charset=cp1251
/media/usb/src/mpd-0.21.19/output $ mpc -p 6601 play
SVOBODA.FM: ??????????? - ?????i ???????
[playing] #1/2  22:34/0:00 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off

**Comment by MaxKellermann** [comment]
You truncated the output of `mpd -V`. Please don't.

**Comment by AndriiZ** [comment]
sorry 

Music Player Daemon 0.21.19 (0.21.19)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

**Comment by MaxKellermann** [comment]
> Other features:
> avahi dbus udisks epoll **icu** inotify ipv6 systemd tcp un

See, ICU support is already enabled. So this isn't the problem.

I cannot reproduce the problem because your URL gets me "404 File Not Found". Can you give me a new URL which works?

**Comment by AndriiZ** [comment]
http://eradio.cc.colocall.com:8000/eradio

**Comment by AndriiZ** [comment]
up@up /media/usb/src/mpd-0.21.19/output $ mpc -p 6601 play
http://eradio.cc.colocall.com:8000/eradio#charset=cp1251
[playing] #1/1   0:00/0:00 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off
up@up /media/usb/src/mpd-0.21.19/output $ mpc -p 6601
E!Radio: Patsyki z Franeka - ???????
[playing] #1/1   0:03/0:00 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off

**Comment by MaxKellermann** [comment]
OK, now I see the problem. This feature was added to MPD 0.22 (not yet released, source code is in the git master branch). MPD 0.21.x will not get any new features, only bug fixes.
With MPD 0.22, I see:
```
Title: Океан Ельзи - Перевал (OST Захар Беркут)
Name: E!Radio
```
