### ISSUE TITLE
Queue command rangeid is zeroing song duration

### ISSUE THREAD

**Issue by cataldor** [MusicPlayerDaemon/MPD#718]
### Describe the bug
By using the queue command `rangeid` within the bounds of the duration of song, the song playback duration is zeroed. 

I've used two clients to test the playback: mpc and ncmpc. For sending the command, i've used a modified version of libmpdclient + a modified version of the example of the same library.

I believe the problem is in the MPD itself and not in the command format. Still, i have slightly edited the code to print additional information related to this

my changes were:
in src/command/QueueCommands.cxx:
add a debug message to check the receiving command:
`FormatDebug(client_domain, "song %u %u %u\n", id, start.ToMS(), end.ToMS());`

in src/queue/Playlist.cxx:
edit the debug information from:
`FormatDebug(playlist_domain, "play %u:\"%s\"", order, song.GetURI());`
to
`FormatDebug(playlist_domain, "play %u:\"%s\" start %u end %u", order, song.GetURI(), song.GetStartTime().ToMS(), song.GetEndTime().ToMS());`

## Expected Behavior
The song duration to be limited to the range specified in the `rangeid` command.

## Actual Behavior
The song playback reports a song duration of "0" seconds.

## Attempt
I'm not very familiar with the MPD source code. Assuming i'm right that the problem is in MPD, i thought the problematic line was:
https://github.com/MusicPlayerDaemon/MPD/blob/1e07d1542856d63f026448eb37e1276576d8381b/src/player/Control.cxx#L71
as the song does not start anymore at zero.
But i was unable to change the behavior.

## Version

Music Player Daemon 0.22~git (v0.21.18-710-g235b6980b+)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log MPD
client [2] is the program that sends the rangeid command. It changes the range of the next song
client [3] and [4] is mpc for, respectively, mpc play and mpc next

Jan 23 15:43 : client: process command "add "30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/08 - The Mission.flac""
Jan 23 15:43 : client: process command "add "30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/09 - End of The Beginning.flac""
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: process command "status"
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: process command "playlistinfo "1""
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: [2] opened from [::1]:35806
Jan 23 15:43 : client: [2] process command "playlistinfo "1""
Jan 23 15:43 : client: [2] command returned 0
Jan 23 15:43 : client: [2] process command "rangeid "2" "1.500000:2.500000""
Jan 23 15:43 : client: song 2 1500 2500
Jan 23 15:43 : client: [2] command returned 0
Jan 23 15:43 : client: [2] closed
Jan 23 15:43 : client: [3] opened from [::1]:35808
Jan 23 15:43 : client: [3] process command "play"
Jan 23 15:43 : playlist: play 0:"30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/08 - The Mission.flac" start 0 end 0
Jan 23 15:43 : client: [3] command returned 0
Jan 23 15:43 : decoder_thread: probing plugin flac
Jan 23 15:43 : playlist: queue song 1:"30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/09 - End of The Beginning.flac"
Jan 23 15:43 : client: [3] process command list
Jan 23 15:43 : decoder: audio_format=44100:16:2, seekable=true
Jan 23 15:43 : client: process command "status"
Jan 23 15:43 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Jan 23 15:43 : output: opened "pulse audio" (pulse) audio_format=44100:16:2
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: process command "currentsong"
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: [3] process command list returned 0
Jan 23 15:43 : client: [3] closed
Jan 23 15:43 : client: [4] opened from [::1]:35810
Jan 23 15:43 : client: [4] process command "next"
Jan 23 15:43 : playlist: play 1:"30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/09 - End of The Beginning.flac" start 1500 end 2500
Jan 23 15:43 : decoder_thread: probing plugin flac
Jan 23 15:43 : decoder: audio_format=44100:16:2, seekable=true
Jan 23 15:43 : client: [4] command returned 0
Jan 23 15:43 : client: [4] process command list
Jan 23 15:43 : client: process command "status"
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: process command "currentsong"
Jan 23 15:43 : client: command returned 0
Jan 23 15:43 : client: [4] process command list returned 0
Jan 23 15:43 : client: [4] closed
Jan 23 15:43 : player: played "30 seconds to Mars - Discography (2002-2018) FLAC/[2002] 30 Seconds to Mars/09 - End of The Beginning.flac"
Jan 23 15:43 : playlist: stop

## Log MPC

`--> mpc play
30 Seconds to Mars - The Mission
[playing] #1/2   0:00/4:05 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off

`--> mpc next
30 Seconds to Mars - End of the Beginning
[playing] #2/2   0:02/0:01 (100%)
volume: 69%   repeat: off   random: off   single: off   consume: off

**Comment by MaxKellermann** [comment]
I don't get it. What is zeroed? I don't see a zero.

**Comment by cataldor** [comment]
Damn, i made a mistake; the range is in seconds (i thought it was in minutes)
i'm sorry
