### ISSUE TITLE
Some vorbis/opus files are unseekable

### ISSUE THREAD

**Issue by mwenzkowski** [MusicPlayerDaemon/MPD#719]
### Describe the bug
I noticed the following incorrect behavior while seeking some vorbis/opus files: For some vorbis/opus files which consist only of silence, MPD complains these are unseekable.

## Expected Behavior
MPD is able to seek in such files.

## Actual Behavior
I created two files: `silence.ogg` and`silence.opus` which can be found in [files.tar.gz](https://github.com/MusicPlayerDaemon/MPD/files/4113579/files.tar.gz). These files consist of 4 Minutes of silence. With these files in MPD's music directory ( in my case `~/Audio`) and an empty queue I did the following:

```
$ cd ~/Audio
$ mpc add silence.ogg silence.opus
$ mpc play 1
silence.ogg
[playing] #1/4   0:00/4:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off
$ mpc seek 2:00
MPD error: Not seekable
$ mpc play 2
silence.opus
[playing] #2/4   0:00/4:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off
$ mpc seek 2:00
MPD error: Not seekable
```
## Version
Music Player Daemon 0.21.19 (0.21.19)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log
Jan 24 16:21 : client: [2] opened from [::1]:36764
Jan 24 16:21 : client: [2] process command "play "0""
Jan 24 16:21 : playlist: play 0:"silence.ogg"
Jan 24 16:21 : decoder_thread: probing plugin vorbis
Jan 24 16:21 : client: [2] command returned 0
Jan 24 16:21 : playlist: queue song 1:"silence.opus"
Jan 24 16:21 : client: [2] process command list
Jan 24 16:21 : client: process command "status"
Jan 24 16:21 : client: command returned 0
Jan 24 16:21 : client: process command "currentsong"
Jan 24 16:21 : decoder: audio_format=44100:f:2, seekable=false
Jan 24 16:21 : client: command returned 0
Jan 24 16:21 : client: [2] process command list returned 0
Jan 24 16:21 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Jan 24 16:21 : output: opened "My Pulse Output" (pulse) audio_format=44100:f:2
Jan 24 16:21 : client: [2] closed
Jan 24 16:21 : replay_gain: replay gain mode has changed off->album
Jan 24 16:21 : replay_gain: scale=1.000000
Jan 24 16:21 : state_file: Saving state file /home/maximilian/.config/mpd/state
Jan 24 16:21 : client: [3] opened from [::1]:36766
Jan 24 16:21 : client: [3] process command "seekcur "120""
Jan 24 16:21 : playlist: queue song 1:"silence.opus"
Jan 24 16:21 : exception: Not seekable
Jan 24 16:21 : client: [3] command returned 2
Jan 24 16:21 : client: [3] closed
Jan 24 16:21 : client: [4] opened from [::1]:36768
Jan 24 16:21 : client: [4] process command "play "1""
Jan 24 16:21 : playlist: play 1:"silence.opus"
Jan 24 16:21 : decoder_thread: probing plugin opus
Jan 24 16:21 : decoder: audio_format=48000:16:2, seekable=false
Jan 24 16:21 : client: [4] command returned 0
Jan 24 16:21 : output: opened "My Pulse Output" (pulse) audio_format=48000:16:2
Jan 24 16:21 : playlist: queue song 2:"test.ogg"
Jan 24 16:21 : client: [4] process command list
Jan 24 16:21 : client: process command "status"
Jan 24 16:21 : client: command returned 0
Jan 24 16:21 : client: process command "currentsong"
Jan 24 16:21 : client: command returned 0
Jan 24 16:21 : client: [4] process command list returned 0
Jan 24 16:21 : client: [4] closed
Jan 24 16:21 : replay_gain: replay gain mode has changed off->album
Jan 24 16:21 : replay_gain: scale=1.000000
Jan 24 16:21 : replay_gain: scale=1.000000
Jan 24 16:21 : client: [5] opened from [::1]:36770
Jan 24 16:21 : client: [5] process command "seekcur "120""
Jan 24 16:21 : playlist: queue song 2:"test.ogg"
Jan 24 16:21 : exception: Not seekable
Jan 24 16:21 : client: [5] command returned 2
Jan 24 16:21 : client: [5] closed

**Comment by MaxKellermann** [comment]
Please write separate reports for separate bugs. Mixing two bugs in one report will only cause confusion.
In this report, I'll handle only the unseekable issue.
For the inaccurate seeking position, please open a new report.

**Comment by mwenzkowski** [comment]
I opened a new bug report (#720) for the inaccurate seeking position and edited this report to only contain the unseekable issue.
