### ISSUE TITLE
drop capabilities on Linux

### ISSUE THREAD

**Issue by DyslexicAtheist** [MusicPlayerDaemon/MPD#722]
## Feature request

hey, I'm a very happy mpd user since years and love this tool. 

I just fiddled with capabilities.h in another project of mine and then noticed that mpd was running with an insane amount of CAPS ... as measured by the pscap utility (from libcap-ng-utils):

```
sudo pscap |grep mpd
1     1162  root        mpd               chown, dac_override, dac_read_search, fowner, fsetid, kill, setgid, setuid, setpcap, linux_immutable, net_bind_service, net_broadcast, net_admin, net_raw, ipc_lock, ipc_owner, sys_rawio, sys_chroot, sys_ptrace, sys_pacct, sys_admin, sys_boot, sys_nice, sys_resource, sys_time, sys_tty_config, mknod, lease, audit_write, audit_control, setfcap, mac_override, mac_admin, syslog, wake_alarm, block_suspend, audit_read
```

It should be possible to drop not needed capabilities with a 3-liner using libcap-ng (cap-ng.h) as [described here](https://people.redhat.com/sgrubb/libcap-ng/). 

E.g.: 

```
#ifdef LINUX

#include <cap-ng.h>
    capng_clear(CAPNG_SELECT_BOTH);
    capng_updatev(CAPNG_ADD, 
         CAPNG_EFFECTIVE|CAPNG_PERMITTED, 
         CAP_CHOWN,
         CAP_SETUID, CAP_SETGID, 
        /* whatever else is needed */
        CAP_NET_ADMIN, -1); 
    capng_apply(CAPNG_SELECT_BOTH);

#endif 
```

**Comment by MaxKellermann** [comment]
You run MPD as root? Don't. Configure the `user` setting, and that will drop the capabilities.
Your idea will still allow MPD to overwrite system files, which means it can still do everything.

**Comment by MaxKellermann** [comment]
Closing because MPD is not meant to be run as root.
