### ISSUE TITLE
How to create multiple mount for icecast using mpd with client YMPD?

### ISSUE THREAD

**Issue by vinodclix** [MusicPlayerDaemon/MPD#725]
I am trying to create multiple mount inside mpd to stream different playlists in the icecast. 

MPD is running on default port: 6600
YMPD is running on port: 8080
Icecast is  running on port: 8000

icecast configuration in mpd.conf as below:

# An example of a shout output (for streaming to Icecast):
#
audio_output {
	type		"shout"
	encoding	"mp3"			# optional
	name		"My Shout Stream"
	host		"localhost"
	port		"8000"
#	bind_to_address "127.0.0.1"
	mount		"/mp3"
	password	"4getme!"
	quality		"5.0"
#	bitrate		"128"
	format		"44100:16:1"
	protocol	"icecast2"		# optional
	user		"source"		# optional
	description	"My Stream Description"	# optional
	url         "http://example.com"    # optional
	genre		"jazz"			# optional
}

=================================

**Icecast.xml code is:**

<icecast>
    
    <location>Earth</location>
    <admin>icemaster@localhost</admin>

    

    <limits>
        <clients>100</clients>
        <sources>50</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        
        <burst-on-connect>1</burst-on-connect>
        
        <burst-size>65535</burst-size>
    </limits>

    <authentication>
        
        <source-password>4getme!</source-password>
        
        <relay-password>4getme!</relay-password>

        
        <admin-user>admin</admin-user>
        <admin-password>4getme!</admin-password>
    </authentication>

    

    
  
    <directory>
        <yp-url-timeout>15</yp-url-timeout>
        <yp-url>/var/lib/mpd/music</yp-url>
    </directory>
    -->
    
    <hostname>localhost</hostname>

    
    <listen-socket>
        <port>8000</port>
        
        
    </listen-socket>
    
    <listen-socket>
        <port>8005</port>
	
       
        
    </listen-socket>

    <listen-socket>
        <port>8006</port>
    </listen-socket>

    <listen-socket>
        <port>8007</port>
        <shoutcast-mount>/live.mp3</shoutcast-mount>
    </listen-socket>
    
    

    <mount type="shout">
        <mount-name>/autoxmas</mount-name>
            <fallback-mount>/autoxmas_127_0_0_1_8009_kyoukaraganbaru</fallback-mount>
        </mount>
    <mount>
        <mount-name>/autoxmas_127_0_0_1_8009_kyoukaraganbaru</mount-name>
        <password>4getme!</password>
        <max-listeners>500</max-listeners>
        <charset>windows-31j</charset>
        <fallback-when-shutdown>0</fallback-when-shutdown>
        <stream-url>http://127.0.0.1:8009/kyoukaraganbaru.m3u</stream-url>
        <fallback-mount>/autoxmas_givemeliberty_ddo_jp_8000</fallback-mount>
    </mount>
    <relay>
        <server>127.0.0.1</server>
        <port>8009</port>
        <mount>/kyoukaraganbaru</mount>
        <local-mount>/autoxmas_127_0_0_1_8009_kyoukaraganbaru</local-mount>
        <on-demand>0</on-demand>
        <relay-shoutcast-metadata>1</relay-shoutcast-metadata>
    </relay>

    
    <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
    </http-headers>

    
    
    
    
    

    
    

    

    

    
    

    
    
    <mount type="normal">
        <mount-name>/stream.ogg</mount-name>

        <username>admin</username>
        <password>4getme!</password>

        <max-listeners>1</max-listeners>
        <dump-file>/tmp/dump-example1.ogg</dump-file>
        <burst-size>65536</burst-size>
        <fallback-mount>/example2.ogg</fallback-mount>
        <fallback-override>1</fallback-override>
        <fallback-when-full>1</fallback-when-full>
        <intro>/example_intro.ogg</intro>
        <hidden>1</hidden>
        <public>1</public>
        <authentication type="htpasswd">
                <option name="filename" value="myauth"/>
                <option name="allow_duplicate_users" value="0"/>
        </authentication>
        <http-headers>
                <header name="Access-Control-Allow-Origin" value="http://webplayer.example.org" />
                <header name="baz" value="quux" />
        </http-headers>
        <on-connect>/home/icecast/bin/stream-start</on-connect>
        <on-disconnect>/home/icecast/bin/stream-stop</on-disconnect>
    </mount>
    

    

    <fileserve>1</fileserve>

    <paths>
        
        <basedir>/usr/share/icecast2</basedir>

        
        <logdir>/var/log/icecast2</logdir>
        <webroot>/usr/share/icecast2/web</webroot>
        <adminroot>/usr/share/icecast2/admin</adminroot>
        <pidfile>/usr/share/icecast2/icecast.pid</pidfile>

        
        
        
        <alias source="/" destination="/status.xsl"/>
        
    </paths>

    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        
        <loglevel>3</loglevel> 
        <logsize>10000</logsize> 
        
        
    </logging>

    <security>
        <chroot>0</chroot>
        
    </security>
</icecast>

---------------------------------------------------

For multiple mount, I have used same code multiple times with different mount in mpd.conf but after that I am getting below error:
==========================

MPD Connecting to 127.0.0.1:6600
MPD connection: Connection refused
MPD connection failed.

===============================

So I want to know that how can I create multiple mount in mpd for streaming on icecast. Please share an example with different mount for icecast, if possible.

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by vinodclix** [comment]
@MaxKellermann I have checked this but I didn't find related to Icecast configuration. Can you please share an example of icecast configuration (shout output (for streaming to Icecast).

**Comment by MaxKellermann** [comment]
> When you do request help, post the following data:
> [...]
> Your collaboration is necessary to solve your problem. **We can’t help you if you don’t follow the instructions above**.

**Comment by vinodclix** [comment]
Hi @MaxKellermann, Please check once below information:

**1. Output of mpd --version:**

> Music Player Daemon 0.19.12
> 
> Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
> Copyright (C) 2008-2014 Max Kellermann <max@duempel.org>
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> 
> Database plugins:
>  simple proxy upnp
> 
> Storage plugins:
>  local smbclient nfs
> 
> Neighbor plugins:
>  smbclient upnp
> 
> Decoders plugins:
>  [mad] mp3 mp2
>  [mpg123] mp3
>  [vorbis] ogg oga
>  [oggflac] ogg oga
>  [flac] flac
>  [opus] opus ogg oga
>  [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
>  [audiofile] wav au aiff aif
>  [dsdiff] dff
>  [dsf] dsf
>  [faad] aac
>  [mpcdec] mpc
>  [wavpack] wv
>  [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
>  [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
>  [sidplay] sid mus str prg P00
>  [wildmidi] mid
>  [fluidsynth] mid
>  [adplug] amd d00 hsc laa rad raw sa2
>  [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
>  [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
>  [pcm]
> 
> Output plugins:
>  shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder
> 
> Encoder plugins:
>  null vorbis opus lame wave flac
> 
> Archive plugins:
>  [bz2] bz2
>  [zzip] zip
>  [iso] iso
> 
> Input plugins:
>  file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia
> 
> Playlist plugins:
>  extm3u m3u pls xspf asx rss soundcloud cue embcue
> 
> Protocols:
>  file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://
> 

**2. configuration file (mpd.conf):**

```
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/
# or /usr/share/doc/mpd/user-manual.html


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This 
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
music_directory		"/var/lib/mpd/music"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use 
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
playlist_directory		"/var/lib/mpd/playlists"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the 
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
db_file			"/var/lib/mpd/tag_cache"
# 
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog, otherwise logging is disabled.
#
log_file			"/var/log/mpd/mpd.log"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
pid_file			"/run/mpd/pid"
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server 
# state will be reset on server start up.
#
state_file			"/var/lib/mpd/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file                   "/var/lib/mpd/sticker.sql"
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
#user				"mpd"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group                          "nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other then the default, any.
# This setting can deny access to control of the daemon. Choose any if you want
# to have mpd listen on every address. Not effective if systemd socket
# activation is in use.
#
# For network
#bind_to_address		"127.0.0.1"
bind_to_address		"any"
#
# And for Unix Socket
#bind_to_address		"/run/mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
port				"6600"
#
# This setting controls the type of information which is logged. Available 
# setting arguments are "default", "secure" or "verbose". The "verbose" setting
# argument is recommended for troubleshooting, though can quickly stretch
# available resources on limited hardware storage.
#
#log_level			"default"
#
# If you have a problem with your MP3s ending abruptly it is recommended that 
# you set this argument to "no" to attempt to fix the problem. If this solves
# the problem, it is highly recommended to fix the MP3 files with vbrfix
# (available as vbrfix in the debian archive), at which
# point gapless MP3 playback can be enabled.
#
#gapless_mp3_playback			"yes"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists	"no"
#
# This setting defines a list of tag types that will be extracted during the 
# audio file discovery process. The complete list of possible values can be
# found in the mpd.conf man page.
#metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
#
# This setting enables automatic update of MPD's database when files in 
# music_directory are changed.
#
auto_update    "yes"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following 
# symbolic links outside of the configured music_directory.
#
#follow_outside_symlinks	"yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
#follow_inside_symlinks		"yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
#zeroconf_enabled		"yes"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network.
#
#zeroconf_name			"Music Player"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# can setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in. 
#
default_permissions             "read,add,control,admin"
#
###############################################################################


# Database #######################################################################
#

#database {
#       plugin "proxy"
#       host "other.mpd.host"
#       port "6600"
#}

# Input #######################################################################
#

input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple 
# audio outputs at the same time, through multiple audio_output settings 
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
audio_output {
	type		"alsa"
	name		"My ALSA Device"
#	device		"hw:0,0"	# optional
#	mixer_type      "hardware"      # optional
#	mixer_device	"default"	# optional
#	mixer_control	"PCM"		# optional
#	mixer_index	"0"		# optional
}
#
# An example of an OSS output:
#
#audio_output {
#	type		"oss"
#	name		"My OSS Device"
#	device		"/dev/dsp"	# optional
#	mixer_type      "hardware"      # optional
#	mixer_device	"/dev/mixer"	# optional
#	mixer_control	"PCM"		# optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
audio_output {
	type		"shout"
	encoding	"ogg"			# optional
	name		"My Shout Stream"
	host		"localhost"
	port		"8000"
#	bind_to_address "127.0.0.1"
	mount		"/mpd.ogg"
	password	"4getme!"
	quality		"5.0"
#	bitrate		"128"
	format		"44100:16:1"
	protocol	"icecast2"		# optional
	user		"source"		# optional
	description	"My Stream Description"	# optional
	url         "http://example.com"    # optional
	genre		"jazz"			# optional
#	public		"no"			# optional
#	timeout		"2"			# optional
#	mixer_type      "software"              # optional
}
#
# An example of a recorder output:
#
#audio_output {
#       type            "recorder"
#       name            "My recorder"
#       encoder         "vorbis"                # optional, vorbis or lame
#       path            "/var/lib/mpd/recorder/mpd.ogg"
##      quality         "5.0"                   # do not define if bitrate is defined
#       bitrate         "128"                   # do not define if quality is defined
#       format          "44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#	type		"httpd"
#	name		"My HTTP Stream"
#	encoder		"vorbis"		# optional, vorbis or lame
#	port		"8000"
#	bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
#	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#	max_clients     "0"                     # optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
# Please see README.Debian if you want mpd to play through the pulseaudio
# daemon started as part of your graphical desktop session!
#
audio_output {
	type		"pulse"
	name		"My Pulse Output"
#	server		"remote_server"		# optional
#	sink		"remote_server_sink"	# optional
}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#	type		"winmm"
#	name		"My WinMM output"
#	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#		or
#	device		"0"		# optional
#	mixer_type	"hardware"	# optional
#}
#
# An example of an openal output.
#
#audio_output {
#	type		"openal"
#	name		"My OpenAL output"
#	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
## Example "pipe" output:
#
#audio_output {
#	type		"pipe"
#	name		"my pipe"
#	command		"aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#	command		"AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#	command		"nc example.org 8765"
#	format		"44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#	type		"null"
#	name		"My Null Output"
#	mixer_type      "none"                  # optional
#}
#
# If MPD has been compiled with libsamplerate support, this setting specifies 
# the sample rate converter to use.  Possible values can be found in the 
# mpd.conf man page or the libsamplerate documentation. By default, this is
# setting is disabled.
#
#samplerate_converter		"Fastest Sinc Interpolator"
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <http://www.replaygain.org> for more details about ReplayGain.
# This setting is off by default.
#
#replaygain			"album"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp		"0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
#replaygain_missing_preamp	"0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
#replaygain_limit		"yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has 
# equal "loudness". This setting is disabled by default.
#
#volume_normalization		"no"
#
###############################################################################


# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you 
# may need to modify this setting.
#
filesystem_charset		"UTF-8"
#
# This setting controls the encoding that ID3v1 tags should be converted from.
#
id3v1_encoding			"UTF-8"
#
###############################################################################


# SIDPlay decoder #############################################################
#
# songlength_database:
#  Location of your songlengths file, as distributed with the HVSC.
#  The sidplay plugin checks this for matching MD5 fingerprints.
#  See http://www.c64.org/HVSC/DOCUMENTS/Songlengths.faq
#
# default_songlength:
#  This is the default playing time in seconds for songs not in the
#  songlength database, or in case you're not using a database.
#  A value of 0 means play indefinitely.
#
# filter:
#  Turns the SID filter emulation on or off.
#
#decoder {
#       plugin                  "sidplay"
#       songlength_database     "/media/C64Music/DOCUMENTS/Songlengths.txt"
#       default_songlength      "120"
#       filter "true"
#}
#
###############################################################################


```

**3. Relevant portions of log file(may be it is not related which I want):**

> Feb 04 17:25 : zeroconf: No global port, disabling zeroconf
> Feb 04 17:25 : pulse_output: Failed to enable "My Pulse Output" [pulse]: pa_context_connect() has failed: Connection refused
> Feb 04 17:25 : pulse_output: Failed to enable "My Pulse Output" [pulse]: pa_context_connect() has failed: Connection refused
> Feb 04 17:25 : pulse_output: Failed to enable "My Pulse Output" [pulse]: pa_context_connect() has failed: Connection refused
> Feb 04 17:25 : client: [0] opened from 127.0.0.1:48188
> Feb 04 17:30 : player: played "HighRatedGabruBanJaRani.mp3"

**4. What I want:**

> I want to play different playlist on the basis of different mount using mpd and icecast.
> I am using YMPD as a client of MPD. 
> for example:
> I have devotional, pop, sufi, mixed etc.... playlists which I want to play in a parallel on different mount

**Comment by MaxKellermann** [comment]
Apparently, you didn't read the link I posted.
> make sure you have the latest MPD version (0.21.19)

And now you have the nerve to post:
> Music Player Daemon 0.19.12

Seriously.
