### ISSUE TITLE
Parameter "window" does not seem to work when using "find/search"

### ISSUE THREAD

**Issue by rGunti** [MusicPlayerDaemon/MPD#73]
When I search for songs using the `search` command, the parameter `window` does not seem to work.
Everytime when I send the command it returns an error `[2@0] {search} incorrect arguments`.

My command was:
`search artist omfg window 0:10`

I am currently running v0.20.9 on ARM (Raspberry Pi 3) and the protocol version seems to be v0.19.0.

**Comment by MaxKellermann** [comment]
If you see protocol version 0.19.0, then you're not talking to MPD 0.20.x. And there's probably the reason for your problem.

**Comment by rGunti** [comment]
Sorry for the dump question but how do I get my MPD to protocol v0.20? I didn't quite get that from the documentation I found on the website.

**Comment by MaxKellermann** [comment]
By upgrading it to version 0.20.

**Comment by rGunti** [comment]
Sorry but this comment was not helpful. I've downloaded the latest sources and built it and it still tells me that it is Protocol v0.19. What am I missing here?!

**Comment by ranperry** [comment]
Here - http://www.musicpd.org/download/mpd/0.20/mpd-0.20.9.tar.xz
