### ISSUE TITLE
mpd service contains "RestrictNamespaces"

### ISSUE THREAD

**Issue by Clyybber** [MusicPlayerDaemon/MPD#74]
systemctl status mpd spits an error out that 'lvalue "RestrictNamespaces' is unknown.

**Comment by Clyybber** [comment]
This doesn't seem to hinder it from starting though.

**Comment by Clyybber** [comment]
not sure if i should close this then

**Comment by diogocp** [comment]
That option was added in systemd 233. You probably have an older version.

**Comment by MaxKellermann** [comment]
True. This is not a bug in MPD's service file. It is regular behavior to get such a warning if you have a systemd version that's older than the feature we're using.
