### ISSUE TITLE
MPD output to DSP script

### ISSUE THREAD

**Issue by arjunmenon** [MusicPlayerDaemon/MPD#75]
Hey
Is there a way to route the MPD first through a script running this [audio enhancement tool](https://github.com/zhangsu/seal), then to ALSA?

Visually, at present
phone -> mpd on pi -> alsa -> usb audio

required
phone -> mpd on pi -> script using `seal` gem -> alsa -> usb audio

I did [check this](https://www.musicpd.org/doc/user/config_audio_outputs.html), frankly, I cant get it how to configure to a script?

Using a Pi 3 with USB DAC.

**Comment by MaxKellermann** [comment]
No. That would need to be implemented as a filter plugin.
While it would be technically possible to "enhance" MPD to allow external filter scripts, there would be so many problems and disadvantages attached to that, you wouldn't be happy with it.

**Comment by arjunmenon** [comment]
Then may I ask two things - 
1. If there is an API and a sample file and configuration script to implement as a filter plugin, since the gem is over a C binding.
2. What about system-wide DSP? I found two software, [bmc0/dsp](https://github.com/bmc0/dsp/wiki/System-Wide-DSP-Guide) and [koute/dspr](https://github.com/koute/dspr).

If you can have a quick look, I would like to know, what configuration changes would this require in MPD, if there is?
Since most of what is suggested seems there isn't any essentially and what exists would be just about DSP itself.
