### ISSUE TITLE
0.20.8: assertion for 0-filled mp3 file

### ISSUE THREAD

**Issue by 0-wiz-0** [MusicPlayerDaemon/MPD#76]
Probably due to a broken download, I had a file lying around "foo.mp3" that just contained 0 bytes, about 4MB of them.
When I added that to the play queue, I got an assertion error in the log and mpd exited:
````
assertion "stream->md_len + md_len - si.main_data_begin <= MAD_BUFFER_MDLEN" failed: file "layer3.c", line 2633, function "mad_layer_III"
````

**Comment by MaxKellermann** [comment]
That's a libmad bug, not a MPD bug.
