### ISSUE TITLE
Plugin preference when multiple plugins support a file type?

### ISSUE THREAD

**Issue by jprjr** [MusicPlayerDaemon/MPD#761]
## Question

If multiple plugins support a file type, which plugin is picked? Is there a way to set preferences/priorities in the config file?

**Comment by MaxKellermann** [comment]
There's a hard-coded list of decoder plugins, and they are tested in this order:
https://github.com/MusicPlayerDaemon/MPD/blob/36a678276ba4f7b41a33878eeee65cf7a4948728/src/decoder/DecoderList.cxx#L55-L118
No, there's no way to change priorities. You can only disable plugins in your `mpd.conf` at runtime, or disable them at compile time with Meson flags.

**Comment by jprjr** [comment]
Thank you!
