### ISSUE TITLE
Plugin development: audio endianness

### ISSUE THREAD

**Issue by jprjr** [MusicPlayerDaemon/MPD#767]
## Question

When writing a plugin, should audio sent to the `SubmitData` call should be packed into a particular endianness, or use the machine-native format?

From looking at some of the output encoders, I think it's expected that (for signed 16-bit) the audio data is an array of `short`, as opposed to a stream of bytes with little-endian audio. But I haven't traced all the way through from `SubmitData` to output, so I wanted to check.

Thanks in advance!

**Comment by MaxKellermann** [comment]
MPD's internal format is always native-endian and interleaved.
(Don't say `short` because its size is not defined. Yes, it is 16 bit on all well-known implementations, but don't rely on it.)
