### ISSUE TITLE
mpd resume after restart not the last play song  

### ISSUE THREAD

**Issue by dominik96** [MusicPlayerDaemon/MPD#77]
I have build the mpd from sources but when i restart the service with systemd it resumed not the last play song, but before if has! 

[root@srv:]# mpd --version
Music Player Daemon 0.21

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local

Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [faad] aac
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:

Tag plugins:
 id3tag

Output plugins:
 null pulse httpd

Encoder plugins:
 null vorbis lame flac

Input plugins:
 file ffmpeg

Playlist plugins:
 extm3u m3u pls flac

Protocols:
 gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://

Other features:
 tcp

**Comment by MaxKellermann** [comment]
My brain cannot parse your bug description. Please rephrase and clarify.

**Comment by dominik96** [comment]
it works! my systemd file doesn't had write perimissions to the path /var/lib/mpdstate

[root@srv:]# systemctl status mpd
● mpd.service - Music Player Daemon
   Loaded: loaded (/usr/lib/systemd/system/mpd.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mpd.service.d
           └─mpdstate.conf
   Active: active (running) since Fre 2017-07-07 12:48:03 CEST; 36s ago
  Process: 22331 ExecStopPost=/usr/bin/rsync --quiet --recursive --times /run/mpd/mpdstate /var/lib/mpd/mpdstate (code=exited, status=0/SUCCESS)
  Process: 22338 ExecStartPre=/usr/bin/rsync --quiet --recursive --times /var/lib/mpd/mpdstate /run/mpd/mpdstate (code=exited, status=0/SUCCESS)
 Main PID: 22341 (mpd)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/mpd.service
           └─22341 /usr/bin/mpd --no-daemon /etc/mpd.conf

Jul 07 12:48:02 srv.home systemd[1]: Starting Music Player Daemon...
Jul 07 12:48:03 srv.home systemd[1]: Started Music Player Daemon.
