### ISSUE TITLE
Assertion failure when scanning database (possible ISO9660 archive plugin issue)

### ISSUE THREAD

**Issue by tobiasjakobi** [MusicPlayerDaemon/MPD#776]
## Bug report
I triggered a database scan today, which triggered an assertion after a while. I restarted the daemon and triggered the scan again, same result, hence reproducible.

Here's the assertion:
`mpd: ../mpd-0.21.20/src/db/plugins/simple/Directory.cxx:80: Directory* Directory::CreateChild(const char*): Assertion `*name_utf8 != 0' failed.`

I compiled the daemon with debug information and did the scan with gdb attached. See the backtrace below. I think I already have an idea what goes wrong. IIRC then libcdio was updated recently on my distro (Gentoo), and I suspect that libcdio's path handling slightly changed. The logic in UpdateArchiveTree() seems to be confused by the additional slash at the end of the path string.

## Expected Behavior
Well, scanning should not trigger that assertion.

## Actual Behavior
Assertion triggers.

## Version
mpd 0.21.20
libcdio 2.1.0

## Log
https://gist.github.com/tobiasjakobi/94336c4f7a6bfad40596fdd06d6a02d5

**Comment by MaxKellermann** [comment]
This looks like a ISO archive with an empty file name, or an invalid file name. Would be interesting to see a (raw) file listing..
In any case MPD should be able to just ignore invalid file names instead of crashing!

**Comment by tobiasjakobi** [comment]
Hmm, I'm not convinced that it's really a problem with the ISO. I should emphasize that this album was already contained in the database, I added it already in December last year. And when I ran mpc update back then I got no such assertion failure.

I'm going to check the ISO though.

**Comment by tobiasjakobi** [comment]
This is the output of libcdio's cd-info tool:
https://gist.github.com/tobiasjakobi/1e16bd9685862a8ae369b0496aa311e0

I don't see any abnormalities there.

**Comment by MaxKellermann** [comment]
I see lots of funny characters. Are all of those valid UTF-8?

**Comment by tobiasjakobi** [comment]
Everything is valid Japanese kana and kanji. The Gist looks correct here in Firefox and Chromium. Maybe you're just missing a font with the corresponding glyphs?

Reference:
https://www.math.uni-bielefeld.de/~tjakobi/archive/screenshot_2020-03-06-215122.png
