### ISSUE TITLE
XSPF parser issues

### ISSUE THREAD

**Issue by smithjd15** [MusicPlayerDaemon/MPD#781]
### Describe the bug
Some xspf playlists exhibit parsing problems preventing playback of certain tracks. Anything with ampersands in the location (&amp;) is improperly parsed. The location seems to be truncated at the ampersand, leaving off the front part of the uri. One playlist was fixed by increasing the buffer size in lib/expat/StreamExpatParser.cxx; the <track> entry was split between buffers.

The build has been patched with https://github.com/MusicPlayerDaemon/MPD/pull/772 for relative paths in playlists.

xml snippet (fixed by the buffer size increase):
`    <track>
      <location>../mpc/U2 - The Best Of 1990-2000/104 - U2 - Electrical Storm (William Orbit Mix).mpc</location>
      <title>Electrical Storm (William Orbit Mix)</title>
      <album>The Best Of 1990-2000</album>
      <duration>279000</duration>
      <trackNum>4</trackNum>
      <image>(embedded)</image>
    </track>`
...and the other track (ampersand):
`    <track>
      <location>../mpc/VA - Soundtrack - Top Gun/110 - Harold Faltermeyer &amp; Steve Stevens - Top Gun Anthem.mpc</location>
      <title>Top Gun Anthem</title>
      <creator>Harold Faltermeyer And Steve Stevens</creator>
      <album>Top Gun</album>
      <duration>250000</duration>
      <trackNum>10</trackNum>
      <image>(embedded)</image>
    </track>`

This is what the buffer-splitted location looks like:
`<location>../mpc/U2 - The Best Of 1990-2000/104 |f��- U2 - Electrical Storm (William Orbit Mix).mpc</location>` 
...and the ampersand location:
`<location>../mpc/VA - Soundtrack - Top Gun/110 - Harold Faltermeyer &amp; Steve Stevens - Top Gun Anthem.mpc</location>`

## Expected Behavior
All playlists should play correctly.

## Actual Behavior
The affected track cannot be played back.

## Version
Music Player Daemon 0.22~git (v0.21.19-731-gd5fe23108)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log
xxx xx xx:xx : client: [0] process command "playlistfind file "playlists/- U2 - Electrical Storm (William Orbit Mix).mpc""
xxx xx xx:xx : client: [0] command returned 0
xxx xx xx:xx : client: [0] process command "add "playlists/- U2 - Electrical Storm (William Orbit Mix).mpc""
xxx xx xx:xx : exception: No such directory
...
xxx xx xx:xx : client: [0] process command "playlistfind file "playlists/ Steve Stevens - Top Gun Anthem.mpc""
xxx xx xx:xx : client: [0] command returned 0
xxx xx xx:xx : client: [0] process command "add "playlists/ Steve Stevens - Top Gun Anthem.mpc""
xxx xx xx:xx : exception: No such directory

**Comment by MaxKellermann** [comment]
You forgot to describe how to reproduce the problem.

**Comment by smithjd15** [comment]
Special characters in any field cause this. If it's a `&amp;` in the location field the track will not play.

The other track works fine when its position in the list changes. Other fields also have similar truncation issues, presumably from the same cause, e.g. Artist became 'et', the location was intact and the track still played; this also resolved itself when the track's position in the list changed.
