### ISSUE TITLE
[enhancement] Identify library state so clients don't unnecessarily refetch

### ISSUE THREAD

**Issue by azrdev** [MusicPlayerDaemon/MPD#79]
Clients like Cantata or MPDroid keep a local cache of the library contents. In a large library, refreshing this cache can take quite a while (in which these applications are mostly unresponsive -- yes, their bugs). Thus, it's desirable to only refresh when the library has actually changed.

I therefore suggest adding some "library version id" which is changed (only) on library update and readable by clients. These can store the id and compare it to the future value to reliably recognize (missing) library changes.

Yes, the `idle` command already notifies about library updates, but this only works when the client is connected without interruption.

**Comment by raftopoulos** [comment]
I do not understand the problem. Why should clients download the complete library?

**Comment by MaxKellermann** [comment]
Clients like Cantata and MPDroid are shit if they do this. I refuse to even talk about this "use" of the protocol. I can talk to developers about alternatives, but not about downloading the whole library.
