### ISSUE TITLE
Replaygain: Clipping Prevention

### ISSUE THREAD

**Issue by handballriveting** [MusicPlayerDaemon/MPD#797]
## Feature request
Most modern players have this as an option and with quite a lot of music these days having a peak value above 1 it would be a nice option to have.

**Comment by MaxKellermann** [comment]
Need more explanation. The body of your feature request contains no information at all.

**Comment by MaxKellermann** [comment]
This feature already exists, and it is enabled by default: the config setting is called `replaygain_limit`:
https://github.com/MusicPlayerDaemon/MPD/blob/6979be008cb334ca08fc031ecb86a723bf656381/doc/mpdconf.example#L367-L374

Here's the source code:
https://github.com/MusicPlayerDaemon/MPD/blob/6979be008cb334ca08fc031ecb86a723bf656381/src/ReplayGainInfo.cxx#L36-L37

It means: if the calculated ReplayGain volume level (derived from the `gain` tag and an optional `preamp` configuration setting) would clip (`> 1.0`), then it will be lowered to the highest level which doesn't clip (`1.0 / peak`).

**Comment by MaxKellermann** [comment]
The option was added nearly 10 years ago: https://github.com/MusicPlayerDaemon/MPD/commit/e8310211e216a1de0b4e856496633966d106b831
Before, it could not be disabled; the feature was added 16 years ago here: https://github.com/MusicPlayerDaemon/MPD/commit/04fdc209d9e
