### ISSUE TITLE
[enhancement] Identify "source" library in satellite setup

### ISSUE THREAD

**Issue by azrdev** [MusicPlayerDaemon/MPD#80]
Some clients like Cantata or MPDroid maintain a local cache of the mpd library. When running multiple MPD servers in a [satellite setup](https://www.musicpd.org/doc/user/advanced_config.html#satellite), i.e. using the database of one "master" server through the `proxy` plugin, the clients have to keep this cache updated separately for each server, because they don't know it's actually the same database. Since database updates can take quite some time with large databases, it would be desirable to give clients the possibility to deduplicate their cache.

I therefore suggest to extend the protocol with some client-readable library-ID, which should be the same for proxied libraries, but unique otherwise.

I just stumbled over [mounts in the protocol spec](https://www.musicpd.org/doc/protocol/mount.html), which seem to make this request impossible or at least complicated, but I didn't dig further into the code and the mechanisms behind.

Maybe this request is related to #79.

**Comment by bb010g** [comment]
What about an `identifydatabase` command that returns a version 4 UUID updated every time a database event would be emitted? Testing for matching UUIDs should be all you need to see if a server is proxying another.

**Comment by MaxKellermann** [comment]
Maintaining a full copy of the database is very bad client design, and not supported by the MPD project. Therefore, such feature requests will be rejected.
