### ISSUE TITLE
mpd throws error if your are using the latest version gme

### ISSUE THREAD

**Issue by 1985a** [MusicPlayerDaemon/MPD#833]
### Describe the bug
After installer a new version of gme 0.6.3 using git commit version a465e8c, gme is using gme_set_fade(emu, track_info_->lenght, 8000 );

mpd actual commit 55b8f2c is showing me 
![mpd](https://user-images.githubusercontent.com/21690110/79670650-a6b04680-8192-11ea-872f-bf1de6abcf87.png)
after adding ,8000 into line [190](https://github.com/MusicPlayerDaemon/MPD/blob/master/src/decoder/plugins/GmeDecoderPlugin.cxx#L190) it went fine to compile.

## Version

55b8f2c

**Comment by MaxKellermann** [comment]
This is not a bug, but a request to support a new libgme version after the libgme project broke the API.

**Comment by MaxKellermann** [comment]
Another note: this is not "the latest version". The latest version is 0.6.3, but you're not using 0.6.3. You're using git master, which is unreleased.

**Comment by 1985a** [comment]
Thank you Max, the problem is that I never do this before and I didn't realize how to do it.
I'm glad you have realized it.
