### ISSUE TITLE
EXTM3U: adjust track duration to actual raw file

### ISSUE THREAD

**Issue by macmpi** [MusicPlayerDaemon/MPD#836]
## Feature request
In some cases, external playlist files (such as extended M3U) may have inconsistent track duration set in `#EXTINF` parameter, that do not match those of actual raw track file.

MPD figures-out proper track duration on raw-file in absence of offending `#EXTINF` info, but if `#EXTINF` info is supplied, then it seems the latter always takes precedence.

How-about changing that decision priority, and prefer actual raw-file duration (the real-stuff that get played in the end), over offending `#EXTINF` info?

There might be one side-case I can think of, where user may wish to voluntarily shorten playback by setting shorter `#EXTINF` track-time?...maybe...
But in anycase, **longer `#EXTINF` track-time than actual raw-file duration just does not make any sense**, and in such case at least, MPD would report actual raw-file duration.

Any thought?  (maybe it's more generic than just M3U playlist files BTW)
Thanks for consideration.

**Comment by MaxKellermann** [comment]
I don't like supporting known-broken data.
If your file contains bogus data, why is that so? I mean, specifying the duration in a m3u file is not mandatory - just omit it, but never use wrong data.

**Comment by macmpi** [comment]
That's the point, sometimes, you may not know in big collection files if some are "broken", until you spot it. As MPD see them and knows its maths, it can juts omit such wrong data.

**Comment by macmpi** [comment]
Would it be possible to support [.pls format](https://en.wikipedia.org/wiki/PLS_(file_format)), then?

**Comment by MaxKellermann** [comment]
You mean like this? https://www.musicpd.org/doc/html/plugins.html#pls

**Comment by macmpi** [comment]
I have the following `.pls` file, and MPD 0.21.19 does not seem to detect it (even after `mpc rescan` or `mpc update`), unlike `.m3u` sibling:

```
$ mpc load CD1
loading: CD1
MPD error: No such playlist
```

```
$ cat /var/lib/mpd/playlists/CD1.pls
[playlist]

Title1=CD - Track 1
File1=cdda:///1

Title2=CD - Track 2
File2=cdda:///2

Title3=CD - Track 3
File3=cdda:///3

Title4=CD - Track 4
File4=cdda:///4

Title5=CD - Track 5
File5=cdda:///5

Title6=CD - Track 6
File6=cdda:///6

Title7=CD - Track 7
File7=cdda:///7

Title8=CD - Track 8
File8=cdda:///8

Title9=CD - Track 9
File9=cdda:///9

Title10=CD - Track 10
File10=cdda:///10

Title11=CD - Track 11
File11=cdda:///11

NumberOfEntries=11
```

```
$ mpd --version
Music Player Daemon 0.21.19 (v20200122-173-gd420552f02)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local smbclient nfs

Neighbor plugins:
 smbclient

Decoders plugins:
 [mad] mp3 mp2
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [iso] iso

Input plugins:
 file archive alsa curl ffmpeg smbclient nfs cdio_paranoia

Playlist plugins:
 extm3u m3u pls flac cue embcue

Protocols:
 file:// alsa:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda://

Other features:
 avahi epoll icu inotify ipv6 tcp un
```

**Comment by MaxKellermann** [comment]
Move it to your `music_directory`.
The `playlist_directory` is only for playlists managed by the MPD protocol.

**Comment by macmpi** [comment]
Same problem if inside `music_directory` (after rescan).
BTW my `.m3u` are in the `playlist_directory` so far, with no issue.

**Comment by MaxKellermann** [comment]
Paste verbose log of your attempt to load it.

**Comment by macmpi** [comment]
very strange reference in log as this CD1 playlist has **never been** a m3u...
And it is now in music directory and rescan has been performed

```
client: process command "load "CD1""
exception: Failed to open '/var/lib/mpd/playlists/CD1.m3u': No such file or directory
exception: No such playlist
client: command returned 2
client: [1] process command list returned 2
client: [1] closed
```

**Comment by macmpi** [comment]
OK. Needs to be `mpc load CD1.pls` whereas for `m3u`, extension may be omitted.
Seems fine, thanks.
