### ISSUE TITLE
meson build borken

### ISSUE THREAD

**Issue by thelounge-zz** [MusicPlayerDaemon/MPD#84]
congratulations for not provide a configure-script and switch completly to meson while "INSTALL" still talks about configure/make and that you stuff is boken at all

WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
The Meson build system
Version: 0.41.1
Source dir: /home/builduser/rpmbuild/BUILD/libmpdclient-2.12
Build dir: /home/builduser/rpmbuild/BUILD/libmpdclient-2.12/x86_64-redhat-linux-gnu
Build type: native build
Project name: libmpdclient
Native c compiler: gcc -m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fPIC -fuse-ld=gold -fuse-linker-plugin (gcc 6.3.1)
Appending CFLAGS from environment: '-m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
Appending LDFLAGS from environment: '-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fuse-ld=gold -fuse-linker-plugin'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/home/builduser/rpmbuild/BUILD/libmpdclient-2.12/libmpdclient.ld: YES

Meson encountered an error in file meson.build, line 88, column 0:
Tried to form an absolute path to a source dir. You should not do that but use
relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.

error: Bad exit status from /var/tmp/rpm-tmp.TJ13qX (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.TJ13qX (%build)

**Comment by dominik96** [comment]
same on fedora 25 

[dominik@testsrv:/data/ablage/libmpdclient-build-test]$ meson . output
The Meson build system
Version: 0.41.1
Source dir: /data/ablage/libmpdclient-build-test
Build dir: /data/ablage/libmpdclient-build-test/output
Build type: native build
Project name: libmpdclient
Native c compiler: ccache cc (gcc 6.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/data/ablage/libmpdclient-build-test/libmpdclient.ld: YES

Meson encountered an error in file meson.build, line 88, column 0:
Tried to form an absolute path to a source dir. You should not do that but use
relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.

**Comment by MaxKellermann** [comment]
MPD has no Meson build.

**Comment by thelounge-zz** [comment]
WTF - libmpdclient-2.12 has ONLY a meson build

**Comment by joerg-krause** [comment]
@thelounge-zz This issue tracker is for MPD, **not** for libmpdclient. [This](https://github.com/MusicPlayerDaemon/libmpdclient) is the correct place for your bug report.

**Comment by joerg-krause** [comment]
@thelounge-zz If you had spent five minutes before posting your report you would have recognized that libmpdclient 2.13 removes the obsolete INSTALL file (https://github.com/MusicPlayerDaemon/libmpdclient/commit/270c5985b0f5905784e26ec9088f536e189b01fb) and includes a fix for the meson build (https://github.com/MusicPlayerDaemon/libmpdclient/commit/ad0db0a2e18dc85aa6b9cc81b269510386d71981).

**Comment by thelounge-zz** [comment]
@joerg-krause and if developers would had spent five minutes in tetsing before release broken tarballs they would have recognized it before

**Comment by thelounge-zz** [comment]
and that crap still don't build or has no useable informations how to replace autotools in a rpm spec and frankly it makes me sick when working things are replaced just for fun with no good reason
_________________________________________________
%build
export CFLAGS="%{optflags} -Os -fPIC -fuse-ld=gold -fuse-linker-plugin"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack %{optflags} -Os -fuse-ld=gold -fuse-linker-plugin"
%configure --disable-static
%{__make} %{?_smp_mflags}

%install
make install-strip DESTDIR=%{buildroot}
_________________________________________________
%build
export CFLAGS="%{optflags} -Os -fPIC -fuse-ld=gold -fuse-linker-plugin"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack %{optflags} -Os -fuse-ld=gold -fuse-linker-plugin"
%meson

%install
ninja -v -C %{buildroot}
_________________________________________________

The Meson build system
Version: 0.41.1
Source dir: /home/builduser/rpmbuild/BUILD/libmpdclient-2.13
Build dir: /home/builduser/rpmbuild/BUILD/libmpdclient-2.13/x86_64-redhat-linux-gnu
Build type: native build
Project name: libmpdclient
Native c compiler: gcc -m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fPIC -fuse-ld=gold -fuse-linker-plugin (gcc 6.3.1)
Appending CFLAGS from environment: '-m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
Appending LDFLAGS from environment: '-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -m64 -O2 -g0 -mfpmath=sse -mavx -msse2avx -march=sandybridge -mtune=sandybridge -fopenmp -pipe -fno-strict-aliasing -fomit-frame-pointer -fexceptions -fstack-protector-strong --param=ssp-buffer-size=6 -D_FORTIFY_SOURCE=2 -Wstack-protector -Wformat -Werror=format-security -Os -fuse-ld=gold -fuse-linker-plugin'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/home/builduser/rpmbuild/BUILD/libmpdclient-2.13/libmpdclient.ld: YES
Build targets in project: 2
+ exit 0
Ausführung(%install): /bin/sh -e /var/tmp/rpm-tmp.deTN4W
+ umask 022
+ cd /home/builduser/rpmbuild/BUILD
+ '[' /home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64 '!=' / ']'
+ rm -rf /home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64
++ dirname /home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64
+ mkdir -p /home/builduser/rpmbuild/BUILDROOT
+ mkdir /home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64
+ cd libmpdclient-2.13
+ ninja -v -C /home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64
ninja: Entering directory `/home/builduser/rpmbuild/BUILDROOT/libmpdclient-2.13-2.fc25.20170725.rh.x86_64'
ninja: error: loading 'build.ninja': No such file or directory
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.deTN4W (%install)


Fehler beim Bauen des RPM:
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.deTN4W (%install)

**Comment by MaxKellermann** [comment]
@thelounge-zz your bullshit is no longer welcome here. Please refrain from posting on any of the MPD projects again. Bye.
