### ISSUE TITLE
Non-ASCII characters stripped from Filenames

### ISSUE THREAD

**Issue by vroland** [MusicPlayerDaemon/MPD#842]
### Describe the bug

With the current master, MPD will replace non-ASCII characters in filenames with spaces when extracting metadata from filenames. This leads to scrambled Tags (Album, Artist, Title).
Seems to be introduced by cc72ceb368185381851bec2d7d4fe1c4d69b3f46.

## Expected Behavior

A file named '01 - Féhler.mp3'  (with no ID3 tags) is listed with title 'Féhler' in the database.

## Actual Behavior

A file named '01 - Féhler.mp3'  (with no ID3 tags) is listed with title 'F hler' in the database.
## Version
Occurs on current master.

**Comment by MaxKellermann** [comment]
Whoops. Indeed.

**Comment by vroland** [comment]
Thanks a lot, keep up the great work! :+1:
