### ISSUE TITLE
Several Audio Issues

### ISSUE THREAD

**Issue by Waynekosimoto** [MusicPlayerDaemon/MPD#85]
Using an iMac 2011 I've been having a lot of really annoying problems.

1.  Speakers pop whenever I boot up (twice sometimes)
2. Audio stops working. Sometimes I'm doing something else and the music completely stops working. No audio of any kind works until I reboot it.

**Comment by MaxKellermann** [comment]
Bug report is completely void of information.

**Comment by Waynekosimoto** [comment]
This isn't a bug report.

_Sent from my OPPO FIND7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MaxKellermann** [comment]
Then please don't use the bug reporting feature of GitHub. And please stop posting advertisement URLs. (Deleting your last post now.)
