### ISSUE TITLE
Protocol command "pause" - explanation of PAUSE flag

### ISSUE THREAD

**Issue by jprjr** [MusicPlayerDaemon/MPD#856]
## Question

Hi there -

I was going through the documentation for the protocol, and there's this snippet about the `pause` command:

```
pause {PAUSE}

    Toggles pause/resumes playing, PAUSE is 0 or 1.

    The use of pause command without the PAUSE argument is deprecated.
```

From the documentation, I'm not sure what that PAUSE argument controls.

From the code, I think setting it to zero means "resume", and setting it to 1 means "pause", and not having the argument just blindly toggles betwee pause/play. Is that correct?

**Comment by MaxKellermann** [comment]
That's correct. The deprecated behavior is just not documented - it was a bad idea. I don't think there's a big urge to document deprecated features, because people shouldn't be using that, and documenting it might lure people into using it...
