### ISSUE TITLE
Calculate Replay Gain

### ISSUE THREAD

**Issue by Badsheep** [MusicPlayerDaemon/MPD#857]
Hello,

I’m currently testing mpd with Mac OS X and I really like it, congrats for that nice soft !

My question is about Replay Gain : is Mpd capable of calculate and index the tags of the audio files ?

Or can mpd only read it and I have to do it with another software ?

Thanks !

**Comment by MaxKellermann** [comment]
I don't understand the question, please rephrase.

**Comment by Badsheep** [comment]
Hello,

Is mpd capable of calculating the replay gain of files ?
And then tag them with that value ?

I'm pretty sure the answer is no but I just wanted to be sure.

Thanks

**Comment by MaxKellermann** [comment]
MPD can use existing ReplayGain tags, but will not do its own calculations, and will never modify your music files.

**Comment by Badsheep** [comment]
OK !
Thanks for the explanation !

Have a good day
