### ISSUE TITLE
Can changes in the radio stream title be logged?

### ISSUE THREAD

**Issue by kowalcj0** [MusicPlayerDaemon/MPD#859]
## Question
Is it possible to configure MPD so it logs changes in the radio stream title?

I'm aware that I can record radio streams using [recorder plugin](https://www.musicpd.org/doc/html/plugins.html?highlight=log#recorder)
but that would simply gobble up the free space on my disk and also unnecessarily record (and transcode) locally played files.

Thanks

**Comment by MaxKellermann** [comment]
No, but you can write a small Python script which acts as a MPD client and logs all new tags. I suggest moving "special" features like this to a small and dedicated client.

**Comment by kowalcj0** [comment]
Thanks @MaxKellermann 

Here's an example python script that logs to system journal and to `/home/mpd/.mpd/play.log`.

```bash
pip install python-musicpd systemd-python
```

```python
#!/usr/bin/env python3
# coding: utf-8
from datetime import datetime

from systemd import journal
import musicpd
from musicpd import ConnectionError


def append_to_mpd_play_log(entry: str):
    with open("/home/mpd/.mpd/play.log", "a+") as log:
        log.write(entry)


def main():
    cli = musicpd.MPDClient()
    try:
        cli.connect()
        if cli.status()["state"] == "play":
            song = cli.currentsong()
            entry = f"{str(datetime.utcnow())}-MPD logger: {song['name']} -> {song['title']}\n"
            journal.send(entry)
            append_to_mpd_play_log(entry)
        cli.disconnect()
    except ConnectionError:
        pass


if __name__ == '__main__':
    main()
```

I run it every minute with simple cron job:
```bash
crontab -e
* * * * * /home/mpd/scripts/mpdlogger.py
```
