### ISSUE TITLE
Old versions of dependencies break mpd installs on updated systems

### ISSUE THREAD

**Issue by nojusr** [MusicPlayerDaemon/MPD#862]
### Describe the bug
Installing mpd from the arch linux repositiories on an updated system makes mpd throw a missing library error

## Expected Behavior
Installing mpd is exactly like installing any other package

## Actual Behavior
mpd throws a missing library error

## Version
`0.21.23-4`

## Log
$mpd --verbose
mpd: error while loading shared libraries: libicuuc.so.65: cannot open shared object file: No such file or directory

note: the package which provides the shared object in the error is `icu` which is at version `67.1-1`
I don't know if any of the developers here are responsible for maintaining the arch linux package, but a bump of the libraries in the program would be appreciated.

**Comment by nojusr** [comment]
Turns out there's a package named `icu65`, which is exactly what is needed for mpd to work in this case (assuming no further missing libraries). I suppose that now this is a request to fix the dependencies of the package.

**Comment by MaxKellermann** [comment]
This is a problem with your MPD build or with your Linux distribution. This has nothing to do with the MPD project.
