### ISSUE TITLE
auto_destination_ports in release

### ISSUE THREAD

**Issue by derekdreery** [MusicPlayerDaemon/MPD#863]
Hey, would you mind putting the auto_destination_ports feature in your next release?

https://github.com/MusicPlayerDaemon/MPD/blob/1efbbfcd6f1186002f76457ee1937b5fbe200ffb/src/output/plugins/JackOutputPlugin.cxx#L240

**Comment by MaxKellermann** [comment]
It will be in the next major release i.e. 0.22
The branch 0.21.x is feature-frozen and will only get bug fixes.
