### ISSUE TITLE
mpd version not reported correctly by "mpc version" or "telnet localhost 6600"

### ISSUE THREAD

**Issue by TheOldPresbyope** [MusicPlayerDaemon/MPD#865]
### Describe the bug

Already described in the issue title. Occurs with freshly built mpd 0.21.23 in Raspbian Stretch Lite on an RPi4B. Occurred as well with mpd 0.21.22.

## Expected Behavior

mpd --version, mpc version, and telnet localhost 6600 should all return the same version information.

## Actual Behavior

```
pi@rpi4b:~ $ mpd --version|head -1
Music Player Daemon 0.21.23 (0.21.23)
```

but

```
pi@rpi4b:~ $ mpc version
mpd version: 0.21.11
```

and

```
pi@rpi4b:~ $ telnet localhost 6600
Trying ::1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.21.11
```

**Comment by MaxKellermann** [comment]
MPD doesn't show its version number but its protocol version.

**Comment by TheOldPresbyope** [comment]
Ok, but then mpc is misleading
 
```
pi@rpi4b:~ $ mpc help|grep version
mpc version: 0.31
  mpc version                                           Report version of MPD
```

This was mpc version 0.31 but the same message is in the source code for version 0.33.
