### ISSUE TITLE
Specifying a configuration file location from the command line

### ISSUE THREAD

**Issue by duganchen** [MusicPlayerDaemon/MPD#869]
### Command-Line Option To Specify A Configuration File

How do I specify a configuration file location on the command line?

The mpd.conf manpage says "If not specified on the command line, MPD first searches for it at..."

Neither "mpd --help" nor "man mpd" lists any options for specifying the path to a configuration file. The MPD manpage does say "...or uses CONF_FILE", but I grepped MPD's source code for CONF_FILE and the only place that string shows up is in the manpage itself.

The reason I'm asking is because I'm working on my second MPD client, and I'm thinking of spinning up an MPD instance for the unit tests.

I suppose I can set XDG_CONFIG_HOME to the version-controlled test-resources directory, but is there a better way?

**Comment by owl770** [comment]
As per the man page, the config file is the last parameter on the command line...

> NAME
       MPD - A daemon for playing music
SYNOPSIS
       mpd [options] [CONF_FILE]
> 
I run a number of instances of mpd on the one host all with different config files.

**Comment by duganchen** [comment]
Thanks. Don't know how I managed to miss that.
