### ISSUE TITLE
Connecting to a Snapcast server or adding delay in HTTP plugin

### ISSUE THREAD

**Issue by buzuck** [MusicPlayerDaemon/MPD#873]
## Question
Hello,
First, I want to apologize if this has been already asked ^^'
 
I want to setup a multiroom setup, without perceptible delay when moving around the house.

I first tried the HTTP plugin provided by mdp, with a master mpd $1 steaming to another (the only in fact) mpd listener $2. This worked well, except that an annoying asynchronicity in audio is perceptible when moving from one room to the other.
I did not find a way to add a delay in the playback of the master (I may have missed something in the documentation though).

I then found out about Snapcast, with which I have been able to add that delay (around 2s in my case) when streaming from the master mpd server $1. However, this breaks the "workflow" I have when playing something different on either of my two MPD setups, as I have not been able to add that Snapcast flow into the palylist of the listener $2.

So, my question could be summed-up as:
Is there a way to either add a snapcast stream into a mpd playlist, or to add delay into the mpd's alsa output?

**Comment by MaxKellermann** [comment]
You can't add delay.
What does "add a snapcast stream" mean, technically? What *is* a snapcast stream?

**Comment by buzuck** [comment]
> What is a snapcast stream?
Technically, apart "a stream of stuff", I don't know. This protocol is not yet documented, except by its code =/

> *Roadmap*
> [ ] *Protocol specification* Snapcast binary streaming protocol, JSON-RPC protocol
Quoted from https://github.com/badaix/snapcast

Meh. Even this Snapcast is in active development, a better integration with mpd doesnt seem to be for tomorrow ^^'

Closing this question then :)
