### ISSUE TITLE
Stop after current song

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#874]
## Question

Not sure how much of is an actual issue or a question but here it goes:
I'm passing through ncat (but also tried telnet and nc) 2 commands: idle player and stop
the principal is to "dump" the commands on the server and forget about it, the server should wait until the songs end (`idle playlist`) and then stop (`stop`). For an example I could set these commands and leave the house and still be reassured that MPD will stop when the song will end.

so far I tried the following from the command line, but nothing happens, also I tried different variation of the idle command such as `idle mixer`, but still failed
`echo -e "idle playlist\nstop" | ncat MYMPDSERVER 6600`
`echo -e "idle\tplaylist\nstop" | ncat MYMPDSERVER 6600`
`echo -e "command_list_begin\nidle playlist\nstop\ncommand_list_end" | ncat MYMPDSERVER 6600`
`echo -e "command_list_begin\nidle\tplaylist\nstop\ncommand_list_end" | ncat MYMPDSERVER 6600`

MPD 0.21.11

**Comment by MaxKellermann** [comment]
Clients are not allowed to send commands other than `noidle` while in `idle` mode. Look at your MPD log, you'll see the error message.

**Comment by MaxKellermann** [comment]
See https://www.musicpd.org/doc/html/protocol.html#querying-mpd-s-status

> The idle command can be canceled by sending the command noidle (no other commands are allowed).

**Comment by roizcorp** [comment]
Thank you for your answer, what do you think of the use case? do you feel this "feature" (Stop after current) is something that will be compelling for users?
It's achievable via a client e.g. bash script that handles separated `idle` and `stop` commands, but I mean do you think this could/should be a server feature?

**Comment by owl770** [comment]
Have you tried the 'single' option at all? Would that meet your needs?
With a song playing, try "mpc single on" and MPD should stop playing after the current song, shouldn't it? Of course, you would then need to do "mpc single off" and "mpc play" to restart.

**Comment by roizcorp** [comment]
thanks. I think that "responsibility wise" it is the same solution, the client needs to change the single mode off back again. it is certainly gets me closer to my requirement but means that for every interaction command of the client with the server I would have to add `single off` command. it is not a problem nor ideal

**Comment by MaxKellermann** [comment]
Again, look at the protocol documentation https://www.musicpd.org/doc/html/protocol.html#playback-options
`single oneshot`

**Comment by roizcorp** [comment]
Thanks, foolishly I have tried to use the `oneshot` operator with `mpc` and not via the `ncat`, also by mistake I understood from the documentation that `1` is equal to the `oneshot`.
it works clearly, thank you again for taking the time.
