### ISSUE TITLE
Still having audio issues.

### ISSUE THREAD

**Issue by Waynekosimoto** [MusicPlayerDaemon/MPD#88]
If I knew what was at fault I would go to the dependency however, your music player is affected and is directly involved with these issues. You do not close them without providing any comment that would help me solve the issue. If you asked for something I would get it if not, add a tag to the issue needing additional information. Closing the issue means that it was solved, the issues still persist. You leave the issue open and add a tag to it if information was **NEVER** shown.

Now if I add a mpd config it wouldn't help much but because you require additional information without trying to clarify here you go.
```
music_directory         "~/Music/iTunes/iTunes Media/Music"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log"
pid_file                "~/.mpd/mpd.pid"
state_file              "~/.mpd/mpdstate"
auto_update             "yes"

audio_output {
    type       "ao"
    name       "My Mac Device"
    mixer_type "software"
    options    "buffer_time=400"
}

audio_output {
  type                    "fifo"
  name                    "my_fifo"
  path                    "/tmp/mpd.fifo"
  format "44100:16:2"
}

audio_output {
  type  "httpd"
  name  "My HTTP Stream"
  encoder  "lame"
  bitrate "320"
  port "8000"
  format "44100:16:1"
  bind_to_address "0.0.0.0"
}

port                    "6600"
bind_to_address "127.0.0.1"
bind_to_address "192.168.1.242"

```

Using an iMac 2011 I've been having a lot of really annoying problems.

1. Speakers pop whenever I boot up (twice sometimes)
2. Audio stops working. Sometimes I'm doing something else and the music completely stops working. No audio of any kind works until I reboot it.

**Comment by MaxKellermann** [comment]
Closing because the user was banned for posting commercial advertisement on another issue.
