### ISSUE TITLE
Add support for negative searches

### ISSUE THREAD

**Issue by chowbok** [MusicPlayerDaemon/MPD#89]
It would be nice if MPD could support negative searches; e.g., generate a playlist of songs that don't belong to a certain genre.

**Comment by roizcorp** [comment]
+1 pretty please

**Comment by bajidu** [comment]
+1

**Comment by bajidu** [comment]
+1

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/MPD/commit/7f1b134137cce99901b33114777a38d91d233443 has some backend code for this.

**Comment by roizcorp** [comment]
Wow you guys are so cool! many thanks!
