### ISSUE TITLE
readpicture does not find artwork on m4a files

### ISSUE THREAD

**Issue by agentsim** [MusicPlayerDaemon/MPD#892]
## Bug report

My library is composed mostly of ALAC encoded m4a files. I've noticed that `readpicture URI 0` returns an empty response for every m4a file I've tried. I've checked that the files have embedded artwork with `ffprobe`.

## Expected Behavior

A typical response indicating the artwork was found

## Actual Behavior

`OK` but an empty response.

## Version

Music Player Daemon 0.22~git (v0.21.23-1013-g9f5c6d29b)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local nfs curl

Neighbor plugins:
 upnp

Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 null fifo pipe ao openal osx httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg nfs

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// ftp:// ftps:// gopher:// http:// https:// mmsh:// mmst:// nfs:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// smb:// srtp://

Other features:
 ipv6 tcp un

**Comment by MaxKellermann** [comment]
No reply.

**Comment by agentsim** [comment]
Sorry, I missed your initial reply. Attached is a sample file.
[05 Applause.m4a.zip](https://github.com/MusicPlayerDaemon/MPD/files/4861794/05.Applause.m4a.zip)

**Comment by MaxKellermann** [comment]
MPD currently supports embedded pictures in FLAC files and in ID3v2 tags. Your file has neither.
MPD reads M4A files using the FFmpeg library, and that decoder plugin currently doesn't support embedded pictures. So this is a missing feature. Your file will be helpful with implementing and testing the feature for MPD's FFmpeg plugin.
