### ISSUE TITLE
Building from source issue on meson step

### ISSUE THREAD

**Issue by matmarczak** [MusicPlayerDaemon/MPD#896]
## Question
Hi! I was trying to build mpd from source (either from `master` or tar archive) on Ubuntu 18.04 with commands from docs. On the second step, when I execute `meson . output/release --buildtype=debugoptimized -Db_ndebug=true` I get following error:
`meson_options.txt:5:0: ERROR: Unknown type feature.`

**Comment by MaxKellermann** [comment]
Your Meson version is too old.
