### ISSUE TITLE
FAILED: src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o - please help me

### ISSUE THREAD

**Issue by ciuffoly** [MusicPlayerDaemon/MPD#900]
/usr/local/bin/ninja -C output/release

ninja: Entering directory `output/release'
[1/617] Compiling C++ object 'src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o'
FAILED: src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o 
c++ -Isrc/lib/pulse/170f599@@pulse@sta -Isrc/lib/pulse -I../../src/lib/pulse -Isrc -I../../src -I. -I../.. -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O2 -g -Wall -Wextra -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -D_GNU_SOURCE -fPIC -D_REENTRANT -MD -MQ 'src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o' -MF 'src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o.d' -o 'src/lib/pulse/170f599@@pulse@sta/LogError.cxx.o' -c ../../src/lib/pulse/LogError.cxx
/bin/sh: 1: c++: not found
[2/617] Generating GitVersion.cxx with a custom command
ninja: build stopped: subcommand failed.

gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~16.04) 

My previous steps:

sudo su - root

apt-get update

apt install meson g++ \
  libpcre3-dev \
  libmad0-dev libmpg123-dev libid3tag0-dev \
  libflac-dev libvorbis-dev libopus-dev libogg-dev \
  libadplug-dev libaudiofile-dev libsndfile1-dev libfaad-dev \
  libfluidsynth-dev libgme-dev libmikmod-dev libmodplug-dev \
  libmpcdec-dev libwavpack-dev libwildmidi-dev \
  libsidplay2-dev libsidutils-dev libresid-builder-dev \
  libavcodec-dev libavformat-dev \
  libmp3lame-dev libtwolame-dev libshine-dev \
  libsamplerate0-dev libsoxr-dev \
  libbz2-dev libcdio-paranoia-dev libiso9660-dev libmms-dev \
  libzzip-dev \
  libcurl4-gnutls-dev libyajl-dev libexpat-dev \
  libasound2-dev libao-dev libjack-jackd2-dev libopenal-dev \
  libpulse-dev libshout3-dev \
  libsndio-dev \
  libmpdclient-dev \
  libnfs-dev libsmbclient-dev \
  libupnp-dev \
  libavahi-client-dev \
  libsqlite3-dev \
  libsystemd-dev \
  libgtest-dev \
  libboost-dev \
  libicu-dev \
  libchromaprint-dev \
  libgcrypt20-dev

sudo apt-get install inotify-tool

root@ciuffoly-virtual-machine:/home/ciuffoly/Downloads/meson-0.54.2# wget https://bootstrap.pypa.io/get-pip.py
--2020-06-09 09:36:03--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.112.175, 2a04:4e42:1b::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.112.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1869136 (1,8M) [text/x-python]
Saving to: ‘get-pip.py’

get-pip.py                               100%[==================================================================================>]   1,78M  4,75MB/s    in 0,4s    

2020-06-09 09:36:04 (4,75 MB/s) - ‘get-pip.py’ saved [1869136/1869136]

root@ciuffoly-virtual-machine:/home/ciuffoly/Downloads/meson-0.54.2# python3 get-pip.py
Collecting pip
  Using cached pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
Collecting setuptools
  Downloading setuptools-47.1.1-py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 2.1 MB/s 
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-20.1.1 setuptools-47.1.1 wheel-0.34.2

root@ciuffoly-virtual-machine:/home/ciuffoly/Downloads/meson-0.54.2# python3 -m pip install meson
Collecting meson
  Downloading meson-0.54.2.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 1.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: meson
  Building wheel for meson (PEP 517) ... done
  Created wheel for meson: filename=meson-0.54.2-py3-none-any.whl size=642032 sha256=cee7a85f1262a7686d3ac3e06f892f093e421534dc199f4ff2e5032bf3d95a1a
  Stored in directory: /root/.cache/pip/wheels/87/46/77/766cd6a14c0608932e266038f1fa4a3ed90b1967d61713cc5e
Successfully built meson
Installing collected packages: meson
Successfully installed meson-0.54.2

root@ciuffoly-virtual-machine:/home/ciuffoly/Downloads/meson-0.54.2# python3 -m pip install ninja
Collecting ninja
  Downloading ninja-1.10.0-py3-none-manylinux1_x86_64.whl (102 kB)
     |████████████████████████████████| 102 kB 1.3 MB/s 
Installing collected packages: ninja
Successfully installed ninja-1.10.0

/usr/local/bin/meson . output/release --buildtype=debugoptimized -Db_ndebug=true
The Meson build system
Version: 0.54.2
Source dir: /home/ciuffoly/Downloads/mpd-0.21.1
Build dir: /home/ciuffoly/Downloads/mpd-0.21.1/output/release
Build type: native build

apt install gcc-6

**Comment by MaxKellermann** [comment]
Your C++ compiler installation is broken. This has nothing to do with MPD.
