### ISSUE TITLE
osx_output incorrectly choose the low quality format for Apple Airpods

### ISSUE THREAD

**Issue by Nemo157** [MusicPlayerDaemon/MPD#904]
### Describe the bug

`osx_output` incorrectly choose the low quality format for Apple Airpods. Since the first has a higher score it's switched to, despite being much lower quality than the input.

## Expected Behavior

It chooses the high quality one

## Actual Behavior

It chooses the low quality one

## Version
```
Music Player Daemon 0.21.23 (0.21.23)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

(But I also looked at the code on `master` and saw that it calculates the same scores).

## Log
```
decoder: audio_format=44100:f:2, seekable=true
osx_output: Format: 1 channel mixable interleaved 16-bit SInt LE (16000Hz) rated 348.750000
osx_output: Format: 2 channel mixable interleaved 32-bit Float LE (48000Hz) rated 95.250000
```

## Other stuff

I have a feeling the division here is backwards, and it should be `destination_rate / source_rate`, that does give much better scores in my testing, but I really can't follow the logic of this function to say whether that's actually the fix.

https://github.com/MusicPlayerDaemon/MPD/blob/d181ecce7b4e0dbce11538728f80c13c094b6c13/src/output/plugins/OSXOutputPlugin.cxx#L311

(for example the `else` here is afaict dead code since `(source_rate > destination_rate) == false` implies `int_portion < 1`)

https://github.com/MusicPlayerDaemon/MPD/blob/d181ecce7b4e0dbce11538728f80c13c094b6c13/src/output/plugins/OSXOutputPlugin.cxx#L318-L321

**Comment by MaxKellermann** [comment]
Hey, there was a bug reporting template. And you decided to delete all of it, and leave out the vital information requested there.

**Comment by Nemo157** [comment]
There, restored the template. The headings felt very irrelevant given that the logs already had all the details of the observable behaviour, and I had confirmed that the code in `master` had the same behaviour. It's also missing somewhere to put existing investigation, so I stuck it in an "Other stuff" section.
