### ISSUE TITLE
Command to initiate shutdown

### ISSUE THREAD

**Issue by kiddigital** [MusicPlayerDaemon/MPD#906]
## Feature request
For music playback devices (like a raspberry Pi for example) MPD could be the only really relevant process that runs and the only process that has any interaction with a client (any MPD client).

For some of these devices, turning it off requires interaction also so a second interaction channel (and accompanying process) has to be present.

If there would be a MPD command that indicates the desire to shutdown, that would remove the need for a second interaction process saving CPU cycles that keep polling for interaction.

Maybe a command like ‘SHUTDOWN’ could trigger the execution of something that has been specified in the configuration file. For example ‘sudo shutdown -h now’ by giving the MPD user explicit right for this in the sudoers file.

Open for all better suggestions :)

**Comment by MaxKellermann** [comment]
No need to extend MPD for this. It would be simple to write a client process running as root, listening for client-to-client messages (see https://www.musicpd.org/doc/html/protocol.html#client-to-client), which could then initiate shutdown if any client sends a special message.

**Comment by kiddigital** [comment]
> No need to extend MPD for this. It would be simple to write a client process running as root, listening for client-to-client messages (see https://www.musicpd.org/doc/html/protocol.html#client-to-client), which could then initiate shutdown if any client sends a special message.

Thx for the response. I did look into this but it didn’t met the ‘desire’ to _not_ have a second process that is listening by polling for incoming messages. Preferably these cpu cycles are kept reserved for MPD itself.

Unless there is another way that does not require polling.

**Comment by MaxKellermann** [comment]
Polling and CPU cycles, what do you mean?
That process can be tiny, and will not use any CPU cycles at all - until it is woken up when it receives a message.

**Comment by kiddigital** [comment]
Hm. Ok.. does not waste any cpu cycles. Great. That is what I am looking for. Any good/simple example I can look at ( not a real C++ wiz myself)? Thx.. I will investigate this direction further. Additional clues are welcome.

**Comment by MaxKellermann** [comment]
If you want to do it in C or C++, use libmpdclient. Connect, subscribe to a channel, wait for idle events, read messages, wait for idle events, ...

**Comment by MaxKellermann** [comment]
No change necessary because MPD provides all the tooling necessary to build this feature. Closing.
