### ISSUE TITLE
playlist support for running MPD on andriod

### ISSUE THREAD

**Issue by lschierer** [MusicPlayerDaemon/MPD#908]
I would like to be able to use playlists when running MPD on my android tablet.  I can do that if I use the version available via termux apt client, but that requires starting termux every time I want to start MPD.

**Comment by MaxKellermann** [comment]
You can do that with every MPD version.

**Comment by lschierer** [comment]
when installed from https://play.google.com/store/apps/details?id=org.musicpd&hl=en_US where would the playlists need to go to be picked up by MPD?

**Comment by MaxKellermann** [comment]
Wherever you configured them to be.

**Comment by lschierer** [comment]
the Google play installer configured everything.  I tried looking through the file system but there is no obvious config file for it.  I mean, I assume there is one, but it is clear that andriod is hiding a fair amount from the user by default and its file browser UI isn't showing me anything that looks MPD related.
