### ISSUE TITLE
mpd starts skipping if machine sits idle

### ISSUE THREAD

**Issue by yacoob** [MusicPlayerDaemon/MPD#91]
I've noticed this happening on an mpd instance that runs on my OSX workstation. If I leave machine unattended, mpd starts producing skipping audio. This happens before machine enables any kind of screen saving/blanking. Starting interactive work on the machine makes the skipping go away. 

As far as I can tell, the machine is not CPU bound. I've switched log level to `verbose`, but I haven't noticed any log entries when skipping happens. There are two clients connected when this behavior happens, ncmpcpp and kmbmpdc, but I've noticed skipping even without any clients. The music is located on local disk, so there shouldn't be any problems with reading the files. Just for kicks, I've set:

```
audio_buffer_size "8192"
buffer_before_play "15%"
```
but it didn't influence frequency nor time for skipping to occur. The skipping is persistent until you start doing something on the machine, and independent of the file being played.

If you need more information tell me, and I'll try to provide it.

macOS: 10.12.6-x86_64
mpd version:
```
Music Player Daemon 0.20.9

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 null fifo openal osx httpd recorder

Encoder plugins:
 null wave

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg

Playlist plugins:
 extm3u m3u pls cue embcue

Protocols:
 file:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://

Other features:
 icu ipv6 tcp un
```

**Comment by MaxKellermann** [comment]
Unfortunately, there is no MPD developer with OS X, thus the OS X plugin is unmaintained and unsupported.

**Comment by yacoob** [comment]
What kind of information would you like to see had this not been OSX-specific? :)
I'm trying to at least pin down where the problem might be residing - is it input, decoding or output.

**Comment by MaxKellermann** [comment]
If this were Linux, I would tell you to check the verbose log for ALSA xrun messages, but the OS X plugin does not emit any such logs. All the nice development and analysis tools I know from Linux don't exist on OS X, so I wouldn't even know where to start. I simply cannot help.
It is unfortunate that the OS X plugin is unmaintained, but this won't change until a new volunteer maintainer emerges. I keep a safe distance from OS X, so I'm not a candidate.

**Comment by yacoob** [comment]
FWIW, going via libao resolves those problems:

```
audio_output {
  name "default"
  type "ao"
}
```

**Comment by jgillman** [comment]
@MaxKellermann Out of curiosity, did you install mpd with `brew`? I've found that when I use `brew services` to start/stop mpd the playback skips really bad. I've stopped using it and now just manually start it with `mpd` when rebooting my machine and I don't get skipping any more.

**Comment by MaxKellermann** [comment]
No, I don't have a Mac. But maybe your `brew` installed an old MPD version?

**Comment by jgillman** [comment]
`brew` installed 0.20.9 ¯\\_(ツ)\_/¯ maybe it's just a Mac thing.

**Comment by thumphries** [comment]
Curious if this is related to #72 , it sounds similar and may have a similar resolution.

**Comment by yacoob** [comment]
Looks like it was indeed https://github.com/Homebrew/homebrew-core/pull/19410 - things work for me just fine right now with default homebrew build, no skipping. It's curious though, that changing output driver was fixing things here - I wouldn't expect much of a CPU difference, if any :)

**Comment by MaxKellermann** [comment]
Oh, WTF, so macOS's bad CPU scheduler was causing your problems?
I guess the `ao` output has internal differences which may make the problem less likely to occur.

**Comment by yacoob** [comment]
Not sure if it's necessarily a WTF, the process was declared as
"noninteractive" so it was more likely to get preempted. Works as
misconfigured, I'd say. 8) My bad for not verifying this idea after the
other bug was linked. ;)
