### ISSUE TITLE
SMB Authentication

### ISSUE THREAD

**Issue by metafarion** [MusicPlayerDaemon/MPD#910]
## Question
Is it possible to provide MPD credentials for a SMB share any way other than embedding them in the URI directly in mpd.conf?  I'm currently using the format smb://username:password@server/share for my music_directory definition, and they feel a little....exposed.

**Comment by MaxKellermann** [comment]
Not right now. It would be possible to write code to do it any other way, but how?

**Comment by metafarion** [comment]
Well, when passing options to mount.cifs, for example, you can define a credentials file that contains the lines username=x and password=y.  This is important because although you CAN put the username and password right on the command line, it is then visible in the process list and bash_history and such.  Similarly, when I include the credentials in the music_directory URI in mpd.conf, that string is potentially visible to clients.  Here's one of the config screens from myMPD, a web-based MPD client I've been testing.
![Screenshot](https://user-images.githubusercontent.com/2903603/85332328-5ceb2180-b49d-11ea-8fcc-b8c82208bd73.png)
You could of course argue that the client should not be displaying the smb URI to the user, but.... perhaps it would be better if sensitive information like that doesn't make it to the client at all.  The login and password would be safer in a credentials file accessed by MPD, or even directly in mpd.conf, just not in the URI.

**Comment by MaxKellermann** [comment]
Credentials are filtered out for `http://` but not for `smb://`. Would that solve your problem?

**Comment by MaxKellermann** [comment]
Here's the list of URI schemes which are enabled for stripping passwords:
https://github.com/MusicPlayerDaemon/MPD/blob/c6a7f6dabc3509bf0a11dc6eafa89aaa8125b86c/src/util/UriUtil.cxx#L73
One could easily add `smb://` here.

**Comment by metafarion** [comment]
Oh hey, yeah it would.  That's a pretty tidy solution.  I didn't realize the passwords were stripped for those protocols even.  It wouldn't hurt to put this in the documentation too; SMB authentication isn't mentioned at all as far as I can tell; I just kinda guessed that a standard smbclient string would work.

**Comment by MaxKellermann** [comment]
a43ee977462fdd29d6fcc6084978f7a0c5666ff2
