### ISSUE TITLE
MPD crashes on occasion while playing

### ISSUE THREAD

**Issue by StoppingBuck** [MusicPlayerDaemon/MPD#912]
### Describe the bug
On occasion, while I'm listening to music, MPD will seemingly crash out of nowhere and have to be restarted. This happens both when running MOD as a systemd service and when running it with `mpd --stdout --no-daemon --verbose`

## Version

Music Player Daemon 0.21.24 (0.21.24)

## Log

When running MPD with `mpd --stdout --no-daemon --verbose`, these are its last words:

```
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
client: [6] process command "status"
client: [6] command returned 0
client: [6] process command "idle"
client: [6] command returned 1
mpd: ../src/decoder/Bridge.cxx:412: virtual size_t DecoderBridge::Read(InputStream&, void*, size_t): Assertion `nbytes > 0 || is.IsEOF()' failed.
[1]    26619 abort (core dumped)  mpd --stdout --no-daemon --verbose
```

**Comment by MaxKellermann** [comment]
Got a backtrace?
I need the log from the start of playback, so I can see which decoder was used and which file format.
What are you playing, a local file or a stream?

**Comment by StoppingBuck** [comment]
@MaxKellermann This is the beginning:

```
➜  ~ mpd --stdout --no-daemon --verbose
config_file: loading file /home/mp/.config/mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
simple_db: reading DB
curl: version 7.71.0
curl: with OpenSSL/1.1.1g
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /home/mp/.config/mpd/state
inotify: initializing inotify
decoder_thread: probing plugin mad
mad: detected LAME version 3.98 ("LAME3.98r")
mad: LAME peak found: 0.000000
mad: encoder delay is 576, encoder padding is 1284
decoder: audio_format=44100:24:2, seekable=true
```
(then there's a billion 
```
client: [6] process command "idle"
client: [6] command returned 1
```
and related output until the crash happens. 

I'm using ncmpcpp as client

As for files, I can confirm it happening with MP3 files. There might be a change of it happening with M4A too, but I haven't caught it yet.

The files are from a NAS on the LAN which is mounted on boot via this entry in `/etc/fstab`:

``` 
# /mnt/music
//192.168.0.24/music /mnt/music cifs vers=2.0,uid=1000,gid=995,username=mp,password=<password>,rw,nounix,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0`

**Comment by MaxKellermann** [comment]
This crash happens if the kernel reports end of file (the `read` system call returns 0 bytes), but MPD expects more data because the kernel has told MPD previously that the file is larger. This could be a kernel bug related to `cifs`, but I don't know.
I'll push a check to branch https://github.com/MusicPlayerDaemon/MPD/tree/v0.21.x to detect this at runtime and print an error instead of crashing. Check if that error triggers - then we can see if there's really a kernel bug.

**Comment by StoppingBuck** [comment]
@MaxKellermann Thanks, I'll keep an eye out for "Unexpected end of file[...]" errors :+1:
