### ISSUE TITLE
0.22~git does not build for Windows

### ISSUE THREAD

**Issue by parkmino** [MusicPlayerDaemon/MPD#913]
### Describe the bug

0.22~git does not build for Windows.

[mpd.log](https://github.com/MusicPlayerDaemon/MPD/files/4859122/mpd.log)

**Comment by MaxKellermann** [comment]
Is this an incremental build or did you rebuild everything, including the external libraries?

**Comment by parkmino** [comment]
In user's manual, "Build on Linux for Windows using MPD’s library build script".

**Comment by MaxKellermann** [comment]
I reprhase my question: is this the first time you build this?

**Comment by parkmino** [comment]
Yes

**Comment by MaxKellermann** [comment]
This sounds very much like https://github.com/msys2/MINGW-packages/issues/5868 and is thus a problem with your toolchain or your environment, and not a MPD problem.
Do a clean rebuild, and upload the whole output, at least the part about compiling libFLAC. This would show which CFLAGS are used.
Type `echo $CFLAGS` and `echo $CPPFLAGS` to see if your envronment has overrides for compiler flags.

**Comment by parkmino** [comment]
Please find the attached file.

[flac.log](https://github.com/MusicPlayerDaemon/MPD/files/4864179/flac.log)

$CFLAGS and #CPPFLAGS are not set on my side.

**Comment by MaxKellermann** [comment]
This is why it fails:
```
checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... yes
```
This is libFLAC's default behavior, but with your toolchain, this option requires additional linker flags. This is not a problem with my version of the toolchain.

**Comment by parkmino** [comment]
Then close this issue.
