### ISSUE TITLE
On database update, error when filepath has a directory that ends in a whitespace

### ISSUE THREAD

**Issue by StoppingBuck** [MusicPlayerDaemon/MPD#914]
### Describe the bug
In situations where files are inside a directory that ends in whitespace, that seems to confuse MPD, which will ignore the file.

As an example, I had a file in the path `ED GAINS/ED GAINS - Team Building /ED GAINS - Team Building Exercise.flac` (notice the whitespace after 'Team Building' in the subdirectory name)

I can see this in the log during database update:

```
update: reading ED GAINS/ED GAINS - Team Building /ED GAINS - Team Building Exercise.flac
flac: Failed to read FLAC tags: FLAC__METADATA_CHAIN_STATUS_ERROR_OPENING_FILE
update: ignoring unrecognized file ED GAINS/ED GAINS - Team Building /ED GAINS - Team Building Exercise.flac
```

(As a side note: The whitespace was actually a mistake on my part and the problem was easily fixed by removing it, i.e. correcting the path so the file is on to `ED GAINS/ED GAINS - Team Building/ED GAINS - Team Building Exercise.flac`. But I felt I should report it as a bug anyway since the behavior seems unintended.)

## Version

Music Player Daemon 0.21.24 (0.21.24)

**Comment by MaxKellermann** [comment]
In this case, the file is opened by libFLAC, not by MPD. So if there really is a problem with opening files with spaces in a path, then it's libFLAC's problem. But I looked at libFLAC's source code - all it does is invoke `fopen()`, which is a basic C function. So the problem must be in `fopen()`...
But I don't think this has anything to do with the space. Did you ensure that MPD is allowed to read this file? If yes, how did you check it?

**Comment by StoppingBuck** [comment]
You're right, I think it was my files that were corrupted. Regardless, it likely wasn't an MPD issue. Sorry for the confusion!
