### ISSUE TITLE
Volume/gain adjustment for decoder plugins?

### ISSUE THREAD

**Issue by hjri** [MusicPlayerDaemon/MPD#929]
## Feature request

Currently playing tracker music/midis and possibly other non-pcm music gives very quiet sound compared to conventional music. I assume tracker/midi decoders just provide PCM with that volume, however there's no way to adjust that. Currently I have to manually decrease/increase volume in MPD or system when switching between tracks, which isn't ideal and it's easy to forget that you were playing midis which are quiet and need to lower the volume when switching to traditional music to avoid ear being blasted.

Playing Cave Story theme (modplug)
![image](https://user-images.githubusercontent.com/3514245/88984329-fb0cab80-d2d5-11ea-920f-aeeb0ed86f52.png)

Playing GRABBAG.MID (fluidsynth, same results with wildmidi)
![image](https://user-images.githubusercontent.com/3514245/88984376-17a8e380-d2d6-11ea-8eda-6a2085663481.png)

Playing Deus Ex theme (Title_musix.umx) (modplug)
![image](https://user-images.githubusercontent.com/3514245/88984512-7c643e00-d2d6-11ea-85f6-5667d75fc20b.png)

Playing Grabbag.ogg from duke 3d megaton
![image](https://user-images.githubusercontent.com/3514245/88984403-2abbb380-d2d6-11ea-8bcd-f2fd9db03c7f.png)

**Comment by MaxKellermann** [comment]
That's a problem with all music files, and MPD supports ReplayGain in many file formats. But I havn't heard of the possibility of ReplayGain tags in the file formats you named.
What general concrete solution do you suggest? Your description is very vague.

**Comment by hjri** [comment]
My idea would be being able to put something like this in `mpd.conf`
```
decoder {
    plugin "fluidsynth"
    gain "+2db"
}
```
or
```
decoder {
    plugin "fluidsynth"
    volume_scale "1.5"
}
```

**Comment by hjri** [comment]
fluidsynth by itself supports `--gain -g` parameter which defaults to 0.2 and sounds about as loud as MPD gives, but gain=1 is closer to what i want:

```
-g, --gain
    Set the master gain [0 < gain < 10, default = 0.2]
```


`fluidsynth -a alsa GRABBAG.MID`  
![image](https://user-images.githubusercontent.com/3514245/89015045-1bad2380-d31f-11ea-8340-c52fa5e99507.png)

`fluidsynth -a alsa -g 1 GRABBAG.MID`
![image](https://user-images.githubusercontent.com/3514245/89015102-34b5d480-d31f-11ea-896e-cfd53e1accfa.png)

**Comment by hjri** [comment]
could the same done for wildmidi and modplug?
