### ISSUE TITLE
Loaded playlist name ?

### ISSUE THREAD

**Issue by XpamAmAdEuS** [MusicPlayerDaemon/MPD#938]
Can we see name of the last loaded playlist?
I have some kind of plugin that load playlists by date/code/name every day.
I cannot know name of playlist currently loaded into mpd.

**Comment by MaxKellermann** [comment]
No.
How is that supposed to work? Let's say I send `load a`, `load b` and add a few songs to the queue and then remove a few - what will MPD tell you which playlist is loaded? Because it's a combination of "a", "b" and some manual changes.

**Comment by geneticdrift** [comment]
Just an idea: add a new property "queue_title" to the player queue. Set this to the playlist name when loaded and clear it when the queue is changed. The "queue_title" will be included in the status response. Optionally add commands to set and clear the queue title so clients can set it not only when loading a playlist.

**Comment by XpamAmAdEuS** [comment]
> Just an idea: add a new property "queue_title" to the player queue. Set this to the playlist name when loaded and clear it when the queue is changed. The "queue_title" will be included in the status response. Optionally add commands to set and clear the queue title so clients can set it not only when loading a playlist.

Great idea.
For my needs its ok if it returns last loaded playlist name becouse i must always start with clear queue.
But command for set name its great idea.
Even better if we can set additional infos like datetime added.
