### ISSUE TITLE
playcount and skips count

### ISSUE THREAD

**Issue by 7h3qu1rkyb1t** [MusicPlayerDaemon/MPD#939]
## Feature request
missing how many times a track is played or how many times it is skipped. for skip counts i can use sticker but for play count i couldn't make it. I searched it in documentation but no use. i found one beets plugin but while trying that i almost lost every song on my computer.
Thanks,

**Comment by MaxKellermann** [comment]
You can implement play counts in stickers as well, and no change in MPD is required. Since you did not explain your problems, there's nothing I can do to help you with it.

**Comment by 7h3qu1rkyb1t** [comment]
i can implement skips using stickers but cant implement play count
