### ISSUE TITLE
Add support for multiple genres

### ISSUE THREAD

**Issue by cassava** [MusicPlayerDaemon/MPD#940]
## Feature request

What would it take to get MPD to support multiple genres per filetype?

I'm aware that this is probably not part of any standard, so I assume it would be a
configurable opt-in kind of thing. 
There have been multiple suggestions on how this would be parsed out of the genre tag,
such as using `;` or `/` or `\0` as separators.
This would suggest simply providing a configuration option to split a genre tag,
which per default could be empty to indicate no splitting performed.

Is there a reason why MPD should not support this as a feature?
If I wanted to help out with this, where would I start?

**Comment by MaxKellermann** [comment]
MPD already supports any number of tags values for each tag.

**Comment by cassava** [comment]
Wow, and it works. Thanks for the information, it was a little hard to find!

In case anyone else is looking for information on how to tag the files:
- MusicBee lets you input multiple tags by splitting on `;`
- Cantata lets you input multiple tags by splitting on `,`
- Easytag lets you input multiple tags by splitting on ` - `, but must be enabled in the preferences first
