### ISSUE TITLE
Cannot compile under libcxx 10

### ISSUE THREAD

**Issue by neheb** [MusicPlayerDaemon/MPD#941]
### Describe the bug

libcxx 10 does not support std::auto_ptr by default. This is removed functionality in C++17.

There's a hack to enable it (-D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES) but this should probably be fixed as MPD claims to be a C++17 project.

## Expected Behavior
Compiles

## Actual Behavior
Does not compile

## Version
master branch

## Log

```
In file included from ../src/decoder/plugins/SidplayDecoderPlugin.cxx:46:
/usr/include/sidplayfp/SidTune.h:52:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr<libsidplayfp::SidTuneBase> tune;
    ~~~~~^
In file included from ../src/decoder/plugins/SidplayDecoderPlugin.cxx:50:
/usr/include/sidplayfp/SidDatabase.h:45:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr<libsidplayfp::iniParser> m_parser;
```

**Comment by MaxKellermann** [comment]
This is a sidplayfp problem, and has nothing to do with MPD.
