### ISSUE TITLE
Crash when loading some streaming audio links

### ISSUE THREAD

**Issue by cache-return** [MusicPlayerDaemon/MPD#952]
Strace attached. I can reliably reproduce by loading https://direct.radiofrance.fr/live/franceinter-midfi.mp3.

[strace.log](https://github.com/MusicPlayerDaemon/MPD/files/5189505/strace.log)

Edit: to clarify that ncmpc seems to be the only thing crashing.

**Comment by MaxKellermann** [comment]
Hey, this bug report doesn't even contain a version number!
https://www.musicpd.org/help/

**Comment by cache-return** [comment]
Sorry. I've never made a bug report before. I pulled from git after commit fb3425806d6439ea1ab51e44d594bc32dc27d889. ncmpc -V gives 0.38

**Comment by MaxKellermann** [comment]
Need more information. Read https://www.musicpd.org/help/

**Comment by cache-return** [comment]
mpd --version is 0.21.5

I have also attached mpd.log, mpd.conf, and the config from ~/.ncmpc/config. Let me know what else I can provide.


[ncmpc_config.txt](https://github.com/MusicPlayerDaemon/MPD/files/5190042/ncmpc_config.txt)
[mpd.log](https://github.com/MusicPlayerDaemon/MPD/files/5190021/mpd.log)
[mpd.conf.txt](https://github.com/MusicPlayerDaemon/MPD/files/5190029/mpd.conf.txt)

**Comment by MaxKellermann** [comment]
You said you pulled MPD from git, but that's not true.
https://www.musicpd.org/help/ says "make sure you have the latest MPD version (0.21.25)" but you ignored that part.
Don't ignore instructions I give you. That makes it impossible for me to help you.
In your case, you know what to do. (Let me repeat just in case you don't: "make sure you have the latest MPD version (0.21.25)").

**Comment by cache-return** [comment]
Sorry, I was unclear and had to edit the original post. I did not pull mpd from git, it is the raspbian package, so correct not the latest. I pulled ncmpc from git and that is what is crashing. Sorry for posting in the wrong place and being unclear. Is the latest version of mpd required in order to report a bug in ncmpc? Should I restart in the correct place, or will it be closed again if I don't update mpd?

**Comment by MaxKellermann** [comment]
You reported a MPD bug, and you never said that ncmpc crashes. ncmpc should never crash, no matter which MPD version you're using.
Report ncmpc bugs here: https://github.com/MusicPlayerDaemon/ncmpc
... and don't forget to post a backtrace of the crash. Without the backtrace, your bug report cannot be analyzed.

**Comment by cache-return** [comment]
Okay, I will report there. When you say backtrace, is what I posted at the top from strace sufficient? I'm not sure I can get it with gdb as described in the FAQ because of the hardware setup, but I can make an effort if it is required.

**Comment by MaxKellermann** [comment]
No, strace is not sufficient. The strace only shows system calls, but says nothing about the crash, because it's not the system call (=kernel) which crashed.
