### ISSUE TITLE
RTP protocol is broken

### ISSUE THREAD

**Issue by doronbehar** [MusicPlayerDaemon/MPD#959]
### Describe the bug

When adding a valid, working `rtp://` stream to mpd, it get stuck. To reproduce:

Run:

```
vlc <INPUT FILE> --sout '#transcode{vcodec=mp4v,acodec=mpga,vb=800,ab=128,deinterlace}: rtp{mux=ts,dst=localhost,sdp=sap,name="TestStream"}'
```

[Source](https://wiki.videolan.org/Documentation:Streaming_HowTo/Command_Line_Examples/).

And then test the stream with:

```
vlc rtp://localhost
```

And then try to make mpd play the stream:

```
mpc add rtp://localhost
```

## Expected Behavior

MPD plays the stream.

## Actual Behavior

If you are using an interactive client, it'll report it can't connect to the MPD server. If you run `mpd` from a terminal, you'll notice it hangs - you need to `kill -SIGKILL` as it won't stop even with a <kbd>Ctrl-c</kbd>. Using `--verbose` doesn't show an interesting message besides:

```
playlist: play 10:"rtp://localhost"
```

## Version

```
Music Player Daemon 0.21.25 (0.21.25)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu://

Other features:
 avahi dbus udisks epoll icu inotify systemd tcp un
```

## Log

```
playlist: play 10:"rtp://localhost"
```

**Comment by MaxKellermann** [comment]
Your log doesn't contain any information. You probably forgot to make it verbose.

**Comment by doronbehar** [comment]
I didn't forget the `--verbose`, for sure. I just didn't want to clutter the report with uninteresting messages such as:

```
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] closed
```

**Comment by MaxKellermann** [comment]
But your log doesn't show any playback command. I need to see everything between the command which starts playback and the hang.

**Comment by doronbehar** [comment]
Nothing happens, since I press <kbd>Enter</kbd> on `ncmpcpp`, and that log message.

**Comment by doronbehar** [comment]
By "Nothing happens" I mean - no other log messages.

**Comment by MaxKellermann** [comment]
This means your client doesn't actually attempt to start playback, it doesn't send any command to do it to MPD. But then why does MPD decide to start playback?
Your information is inconsistent, and I can't help until all data is consistent.

**Comment by doronbehar** [comment]
Here's how it goes:

[![asciicast](https://asciinema.org/a/360480.svg)](https://asciinema.org/a/360480)

Previously, from some reason, I didn't saw the log messages prefixed with `ffmpeg/`. Also, a bit surprisingly, MPD got stuck also in the 1st trial, when the rtp stream was in the queue but wasn't being played - I think I didn't told ncmpcpp to play it. Anyway, that's a detail. I hope this demonstrates the issue.

Regards.

**Comment by MaxKellermann** [comment]
I can reproduce your problem, even without running VLC.
The problem is that FFmpeg (the library which implements RTP) waits forever (inside `avio_read()`, but this is out of MPD's control. MPD cannot do anything to interrupt FFmpeg.
Sorry, but if you want this fixed, report the problem to the FFmpeg project.
