### ISSUE TITLE
Some audio files does not play under Windows WASAPI exclusive mode

### ISSUE THREAD

**Issue by parkmino** [MusicPlayerDaemon/MPD#967]
### Describe the bug
MPD does not play mp3 and flac 96KHz files under WASAPI exclusive mode while there is no problem with flac 44.1KHz.
Connection is lost or showing the following error message.

`ERROR: Failed to open "wasapi" (wasapi); Format is not supported: AUDCLNT_E_UNSUPPORTED_FORMAT`

## Version

MPD 0.22 for Windows

## Log

[mpd.log](https://github.com/MusicPlayerDaemon/MPD/files/5300110/mpd.log)

**Comment by MaxKellermann** [comment]
@ibmibmibm please have a look

**Comment by ibmibmibm** [comment]
Seems that 96kHz is not supported by your audio card.

**Comment by MaxKellermann** [comment]
That is a condition which should be handled by the output plugin, by forcing a supported sample rate!

**Comment by ibmibmibm** [comment]
Ok, I'll make this change and open a pull request

**Comment by parkmino** [comment]
FYI, my audio card supports up to 192KHz.
It is strange not to play mp3.

**Comment by ibmibmibm** [comment]
@parkmino Could you try to play that file using this command:
```
mpv [musicfile] --msg-level=ao/wasapi=v --audio-exclusive --no-audio-display
```
with [mpv](https://github.com/mpv-player/mpv) for windows, and collect the logs for me? Thanks.

**Comment by parkmino** [comment]
@ibmibmibm Please find the attached file.

[mpv.log](https://github.com/MusicPlayerDaemon/MPD/files/5576976/mpv.log)

**Comment by MaxKellermann** [comment]
da642b289049836f2d89b65726ef1aa5229b5f82
