### ISSUE TITLE
Add meson options to specify install directories

### ISSUE THREAD

**Issue by ManDay** [MusicPlayerDaemon/MPD#971]
It would be good if installation directories. From the looks of [meson's docs](https://mesonbuild.com/Installing.html), that's up to the program to do and meson provides no special facility. E.g. user wants to install documentation into `/usr/share/doc/mpd-0.21.25/` rather than `/usr/share/doc/mpd/`

**Comment by MaxKellermann** [comment]
MPD installs the HTML manual below Meson's `datadir`, which is configurable:
https://github.com/MusicPlayerDaemon/MPD/blob/4484d7a5c2faabd6632e9ca6bc88712781cd4fa6/doc/meson.build#L23
I'm not convinced that MPD's `meson.build` should allow fine-grained control over where each and every file gets installed. Doing so would add a lot of clutter to the build scripts and would confuse users with too many choices. If you want to add a version suffix, just rename the directory.

**Comment by ManDay** [comment]
I'm not very familar with meson, but isn't renaming a directory after build a sure way to shoot yourself in the foot? In the worst case, these paths may have been configured into the source code or other places. When the user renames the directories where mpd expects to find things, things will stop working, no?

**Comment by ManDay** [comment]
As for clutter, I don't see why replacing, for instance, `meson.project_name( )` in this case with a option variable would cause clutter. And then, there are how many of these directories that? `bin`, `lib`, and `doc`. That wouldn't cause much clutter?

**Comment by MaxKellermann** [comment]
> I'When the user renames the directories where mpd expects to find things, things will stop working, no?

No. MPD doesn't expect to find documentation anywhere. Only users (i.e. you) expect to find documentation, but MPD doesn't care about documentation. You can move the documentation wherever you like.
