### ISSUE TITLE
io_uring throws and exception

### ISSUE THREAD

**Issue by dschrempf** [MusicPlayerDaemon/MPD#972]
### Describe the bug
I get a memory allocation exception since yesterday after updating to MPD 0.22. Also, many files went missing in the library.

EDIT: A `rescan` fixed the data base problems, but it is weird that the data base got scrambled in the first place.

## Version
```
Music Player Daemon 0.22 (0.22)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Log
```
Oct 03 17:25:03 blaubaer systemd[765]: Starting Music Player Daemon...
Oct 03 17:25:03 blaubaer mpd[5107]: Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
Oct 03 17:25:03 blaubaer systemd[765]: Started Music Player Daemon.
```

**Comment by MaxKellermann** [comment]
On 2020/10/03 17:28, Dominik Schrempf <notifications@github.com> wrote:
> I get a memory allocation exception since yesterday after updating to MPD 0.22.

This happens when you start MPD with a memlock limit that is too
small.

The systemd unit that comes with MPD sets an appropriate memlock
limit, but if you don't use systemd, you might need to adjust the
limit manually.

It is not a critical problem - MPD works, but cannot use io_uring, and
will fall back to blocking file I/O.

**Comment by dschrempf** [comment]
Hm, I am using Systemd and the same limit (64MB) as is set in the service file coming with MPD (I am using the default service provided by Arch Linux).

**Comment by MaxKellermann** [comment]
So what's the effective limit of the running process? Try `cat /proc/$(pidof mpd)/limits`

**Comment by dschrempf** [comment]
```
 + cat /proc/773/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             29603                29603                processes
Max open files            1024                 524288               files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       29603                29603                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

**Comment by shikitohno** [comment]
I'm having the same issue, though in my case, scanning the db dies once it gets to the directory "Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]" which wasn't previously an issue.  If I remove this album from ~/Music, mpd will successfully complete a db scan and start, but it fails to read metadata for properly tagged files, either displaying them as <empty> or producing gibberish output.  東京事変 becomes ?F?ʨ?., for example.  These files display correct file paths, and can be played fine displaying the same tag info MPD had prior to the upgrade in other media players, but attempting to play them in ncmpcpp produces "No such file" errors.

As soon as I add that album back to ~/Music, mpd dies.

**Comment by MaxKellermann** [comment]
@dschrempf, your memlock limit is ok, but I wonder why the ring allocation fails. Can you strace MPD and see which system call fails right before logging the error?

**Comment by MaxKellermann** [comment]
@shikitohno if MPD dies, write a new bug report and post details about how MPD dies. This doesn't belong here.

**Comment by sbraz** [comment]
@MaxKellermann I'm seeing this too, here are the limits:
```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             128156               128156               processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       128156               128156               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

And the strace, the error appears just after closing the database file (fd 11):
```
stat("/var/lib/mpd/database", {st_mode=S_IFREG|0644, st_size=437754, ...}) = 0                    
close(11)                               = 0                                                              
io_uring_setup(1024, {flags=0, sq_thread_cpu=0, sq_thread_idle=0}) = -1 ENOMEM (Cannot allocate memory)
futex(0x7f961372d1e0, FUTEX_WAKE_PRIVATE, 2147483647) = 0                                    
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x12), ...}) = 0   
write(2, "Failed to initialize io_uring: i"..., 84Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
) = 84                                                                                                   
```

**Comment by MaxKellermann** [comment]
Oh, I was wrong - the memlock limit is **not** ok. I mixed up the units - `/proc/PID/limits` shows bytes, not kilobytes (unlike the `ulimit` bash built-in, which ).
Your effective memlock limit is 64 *kilo*bytes, not 64 megabytes. That is not enough for io_uring!
@dschrempf, @sbraz you need to find out why the limit in MPD's systemd units does not work.
This is not a MPD problem! MPD does not (and can not) set those limits, they must be configured by the entity launching MPD.

**Comment by sbraz** [comment]
Works fine after  `ulimit -l 65535` which sets the limit to 64 MiB (oh just saw your message). Yeah it's all good.

**Comment by dschrempf** [comment]
Thank you! Could you maybe give me a hint where to report the bug upstream? Is this a bug in SystemD?

**Comment by MaxKellermann** [comment]
No, I have no idea. I don't know if this is a systemd bug, and I doubt it.
If this is a systemd user unit, your user instance of systemd may not have permission to raise the limit (if your user session has a lower limit). But that is just speculation, because you did not give any relevant information about your setup.

**Comment by dschrempf** [comment]
Hm, I am unsure about which information to provide. I do not set any limits (didn't even know I could do that). I went through all files in `/etc/security/`, and all lines are commented. I don't know how to find the default limit.

Shouldn't the default work with MPD? Should I contact the Arch Linux developers to provide better defaults?

**Comment by MaxKellermann** [comment]
> I am unsure about which information to provide

How do you start MPD? You said systemd, but is it a user systemd or the system-wide systemd?

Check `systemctl show mpd|grep LimitMEMLOCK` (or `systemctl --user show mpd|grep LimitMEMLOCK` if it's your user systemd) to see if systemd "knows" this limit.

> Shouldn't the default work with MPD?

What default? The MPD systemd file comes with a working value, but this value is not effective on your computer. I don't know why that happens on your computer, but since that's outside of MPD's scope, I'm not the best guy to analyze your problem.

> Should I contact the Arch Linux developers to provide better defaults?

If this is about Arch's defaults, then yes. But we don't know that.

> Not sure why you labeled this with bogus, since it is a real issue for me :).

It's a real issue for you, but it's not a MPD issue.

**Comment by dschrempf** [comment]
Thank you for all your help! With respect to the tag name, I just felt a little bewildered, because `bogus` sounds like I came up with a fake issue, which is not the case. Maybe `external` or `upstream` would be a friendlier name :)!

I use a user service. The command you suggested returns:
```
 + systemctl --user show mpd | grep LimitMEMLOCK
LimitMEMLOCK=67108864
LimitMEMLOCKSoft=67108864
```

So I guess, SystemD is not aware of the limitation? I don't even know, were the defaults are set. I couldn't find any default value for these limits.

Thanks again, I am sorry that I bother you with this problem, I just don't know where to report it elsewhere... I guess the next instance would be the SystemD issue tracker.

**Comment by MaxKellermann** [comment]
> So I guess, SystemD is not aware of the limitation?

Yes it is. The output you pasted shows that systemd is aware, because these are the values from systemd's perspective. I believe that systemd attempts to set those limits, but isn't allowed to.

Remember what I wrote before:
> If this is a systemd user unit, your user instance of systemd may not have permission to raise the limit (if your user session has a lower limit).

What are the limits of your systemd user process?

**Comment by dschrempf** [comment]
I am not sure if I understand. The command was issued for the service manager of the user. The system wide command (without `--user`) shows the same values. Is there another way to determine the limits for the user process?

**Comment by MaxKellermann** [comment]
This doesn't determine the limits for the user process. The command `cat /proc/.../limits` does that.
`systemctl show ....` determines which limits systemd will *attempt* to use. But it doesn't say whether this will be successful.
Because, as I said twice here, a user systemd (like any other user process) is unable to raise limits higher than its own limits. It can only lower them. That's why I asked you to check systemd's own (effective) limits! Which you did not.

**Comment by dschrempf** [comment]
Wow, you are the unfriendliest developer I have ever had contact with :smile:, I guess you take it as a compliment! Peace!

Anyways, thank you! It works now. I raised the memlock limit of the systemd process in `/etc/security/limits.conf`. I tried using `/etc/systemd/user.conf`, but that didn't work. I also don't see where the default limits are set. All this is super shady to me...

**Comment by zupatisc** [comment]
FYI This same problem of a too low limit caused mpd to fail on scanning the DB making me think that I had a problem ala #974 but using [prlimit](https://serverfault.com/questions/201207/set-max-file-limit-on-a-running-process) solved both the warning of low memory and the dying on scanning the DB.

**Comment by michaelcadilhac** [comment]
Quite clearly, something has changed in the defaults on Arch Linux (also on Raspberry Pi OS).  It _may_ be good to give a more verbose message for this error, since quite a few users will face this.  Changing `limits.conf` does work for starting MPD by hand, but it seems that `systemd` isn't very keen on picking that up (`limits.conf` does not affect `systemd`).

**Comment by MaxKellermann** [comment]
@michaelcadilhac this problem is out of MPD's scope. MPD just reports the error condition that gets reported by liburing, and liburing just forwards the error condition reported by the kernel (ENOMEM with no further explanation).
As you already mentioned: there is no universal, simple fix for this problem. This is specific to how to launch MPD, whether systemd or not, whether your systemd is a user systemd or a system-wide systemd, whether PAM or not, etc. etc.

Do you know why systemd doesn't care about `/etc/security/limits.conf`? Because this isn't a generic or universal configuration file - it is a configuration file for `pam_limits` and *nothing else*! The whole `/etc/security/` directory is owned by PAM modules. PAM modules are used for login, but not for system services. Of course systemd doesn't care, because this is none of systemd's business!

The MPD documentation has a brief section about this problem: https://www.musicpd.org/doc/html/user.html#error-failed-to-initialize-io-uring - but doesn't go into much detail, because it's, as I said, out of MPD's scope.

You said you wish to have a more verbose message. What wording would be more helpful in your opinion? Right now, MPD just states the facts it sees (but MPD itself doesn't know why this error occurred).

**Comment by michaelcadilhac** [comment]
Thanks for the prompt answer Max.  I understand your frustration: it's as if we're blaming MPD, while MPD is simply a victim of an outside change, apologies if my suggestion came across that way.  The proper message would be RTFM, I believe :-)  Something like:

```
Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
See https://www.musicpd.org/doc/html/user.html#error-failed-to-initialize-io-uring for more information.
```

Cheers.

**Comment by snowman** [comment]
From https://www.musicpd.org/doc/html/user.html#error-failed-to-initialize-io-uring,

> Error "Failed to initialize io_uring"
> Linux specific: the io_uring subsystem could not be initialized. This is not a critical error - MPD will fall back to "classic" blocking disk I/O. You can safely ignore this error, but you won't benefit from io_uring's advantages.
> 
> "Cannot allocate memory" usually means that your memlock limit (ulimit -l in bash or LimitMEMLOCK in systemd) is too low. 64 MB is a reasonable value for this limit.
> 
> Your Linux kernel might be too old and does not support io_uring.>

**Comment by BachoSeven** [comment]
> I raised the memlock limit of the systemd process in `/etc/security/limits.conf`. I tried using `/etc/systemd/user.conf`, but that didn't work. I also don't see where the default limits are set. All this is super shady to me..

@dschrempf It looks like although the limit cannot be changed from`user.conf`, perhaps because systemd's user process cannot change its own limits, you _can_ however  set `DefaultLimitMEMLOCK=2083642880` in `/etc/systemd/system.conf`, and that will fix the error.

**Comment by dschrempf** [comment]
Hi,

thanks for this info. What I did is adding myself to the `realtime` group which
has elevated memory limits.

Dominik
