### ISSUE TITLE
Opus stream not seekable, if start time is non-zero

### ISSUE THREAD

**Issue by jarnos** [MusicPlayerDaemon/MPD#973]
### Describe the bug

I have recorded a large opus stream file that has non-zero startup time. mpd can not seek the file. VLC can seek the file. If I create a new file by `ffmpeg -i old.opus -c:a copy new.opus` mpd can seek it.

If I run `ffprobe -show_streams` for the old and new file, there is a difference in the output:

```
$ diff old new
19,22c19,22
< start_pts=27172852480
< start_time=566101.093333
< duration_ts=45847607680
< duration=955158.493333
---
> start_pts=0
> start_time=0.000000
> duration_ts=18674755200
> duration=389057.400000
40a41
> TAG:ENCODER=Lavf57.83.100
```

Note: not using curl storage.

## Expected Behavior

Expect to be able to seek using a client.

## Actual Behavior

Seeking does not work. For example 

```
$ mpc seek +00:00:01
Seek amount would seek past the end of the song
streaming/old.opus
[playing] #13/13 9435:02/0:00 (0%)
volume: 78%   repeat: on    random: off   single: off   consume: off
```

## Version

Music Player Daemon 0.21.22 (0.21.22)

**Comment by MaxKellermann** [comment]
What does "start time is non-zero" mean?
I need to have such a file; please upload it.
Note that your MPD version is outdated and unsupported. Before we can continue, update to the latest version. If that shows the same problem, upload your file and answer the question.

**Comment by jarnos** [comment]
It is sad that (any release of) Ubuntu does not have a supported version of MPD. Installing from source would be difficult in the machine where I use MPD. It has Ubuntu version 18.04 32 bit and I would have to build even some development tools from source that I am not used to; besides, there is no upgrade for the OS.

However, here is a crop of the file from the start: https://www.dropbox.com/s/fhlsobz8tvyalzu/crop.opus?dl=0
Non-zero start time means that `ffprobe -show_streams` tells `start_time` is non-zero.

**Comment by MaxKellermann** [comment]
That file is broken because it has no end_of_stream packet.

**Comment by jarnos** [comment]
> That file is broken because it has no end_of_stream packet.

Maybe because I created the crop by using `dd` command?

**Comment by nikp123** [comment]
This is still an issue with a completely correct file, try downloading an opus stream from YouTube (via youtube-dl) and this will happen.

**Comment by nikp123** [comment]
But however it happens even when the start time is not zero. Here's the info of the file that bugs out for me:
```
ffprobe version n4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, ogg, from 'Return to Moonland.opus':
  Duration: 00:06:24.93, start: 0.007500, bitrate: 147 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ALBUM           : Alchemy
      album_artist    : Au5
      ARTIST          : Au5
      ENCODER         : Lavf58.45.100
      GENRE           : Ambient
      LANGUAGE        : eng
      TITLE           : Return to Moonland
      track           : 7
    Stream #0:1: Video: png, rgb24(pc), 640x640, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
[STREAM]
index=0
codec_name=opus
codec_long_name=Opus (Opus Interactive Audio Codec)
profile=unknown
codec_type=audio
codec_time_base=1/48000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=360
start_time=0.007500
duration_ts=18476520
duration=384.927500
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:ALBUM=Alchemy
TAG:album_artist=Au5
TAG:ARTIST=Au5
TAG:ENCODER=Lavf58.45.100
TAG:GENRE=Ambient
TAG:LANGUAGE=eng
TAG:TITLE=Return to Moonland
TAG:track=7
[/STREAM]
[STREAM]
index=1
codec_name=png
codec_long_name=PNG (Portable Network Graphics) image
profile=unknown
codec_type=video
codec_time_base=0/1
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=640
height=640
coded_width=640
coded_height=640
closed_captions=0
has_b_frames=0
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=rgb24
level=-99
color_range=pc
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=unspecified
field_order=unknown
timecode=N/A
refs=1
id=N/A
r_frame_rate=90000/1
avg_frame_rate=0/0
time_base=1/90000
start_pts=675
start_time=0.007500
duration_ts=34643475
duration=384.927500
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=1
DISPOSITION:timed_thumbnails=0
TAG:comment=Other
[/STREAM]
```

**Comment by nikp123** [comment]
It also seems that it happens more often as the current playlist grows.

**Comment by nikp123** [comment]
Also reproducing this bug doesn't work a 100% of the time. MPD logs show nothing useful.

**Comment by nikp123** [comment]
Another discovery: This happens only to files the user did not actually hit play, but rather to files which were selected by mpd through the current playlist after finishing the last song.

**Comment by nikp123** [comment]
Here's a file that has a 100% reproducing rate:
```
ffprobe version n4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, ogg, from 'The Passing.opus':
  Duration: 00:08:11.77, start: 0.007500, bitrate: 143 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ALBUM           : 7 Minutes Dead EP
      album_artist    : 7 Minutes Dead
      ARTIST          : 7 Minutes Dead
      ENCODER         : Lavf58.45.100
      GENRE           : Electro
      LANGUAGE        : eng
      TITLE           : The Passing
      track           : 3
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 1200x1200 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
[STREAM]
index=0
codec_name=opus
codec_long_name=Opus (Opus Interactive Audio Codec)
profile=unknown
codec_type=audio
codec_time_base=1/48000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=360
start_time=0.007500
duration_ts=23604840
duration=491.767500
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:ALBUM=7 Minutes Dead EP
TAG:album_artist=7 Minutes Dead
TAG:ARTIST=7 Minutes Dead
TAG:ENCODER=Lavf58.45.100
TAG:GENRE=Electro
TAG:LANGUAGE=eng
TAG:TITLE=The Passing
TAG:track=3
[/STREAM]
[STREAM]
index=1
codec_name=mjpeg
codec_long_name=Motion JPEG
profile=Baseline
codec_type=video
codec_time_base=0/1
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1200
height=1200
coded_width=1200
coded_height=1200
closed_captions=0
has_b_frames=0
sample_aspect_ratio=1:1
display_aspect_ratio=1:1
pix_fmt=yuvj444p
level=-99
color_range=pc
color_space=bt470bg
color_transfer=unknown
color_primaries=unknown
chroma_location=center
field_order=unknown
timecode=N/A
refs=1
id=N/A
r_frame_rate=90000/1
avg_frame_rate=0/0
time_base=1/90000
start_pts=675
start_time=0.007500
duration_ts=44259075
duration=491.767500
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=1
DISPOSITION:timed_thumbnails=0
TAG:comment=Other
[/STREAM]
```

**Comment by nikp123** [comment]
Yup ignore the first one, this one bugs out every single time.

**Comment by nikp123** [comment]
Also out of all files, those which are tagged are the only ones that have this bug.

**Comment by nikp123** [comment]
Tested on MPD version 0.22.3 from Arch repos.

**Comment by jarnos** [comment]
> That file is broken because it has no end_of_stream packet.

I tried some other players with the file I provided, and they are able to seek (though ffplay uses the position relative to the start of the given stream file, not absolute timestamp).

vlc 3.0.9.2:
nvlc --start-time=$((566101+15)) crop.opus

ffplay 4.2.4:
ffplay -ss 15 crop.opus

mpv 0.32.0:
mpv --rebase-start-time=no --start=$((566101+15)) crop.opus 
mpv --rebase-start-time=no --start=157:15:16 crop.opus
mpv --rebase-start-time=yes --start=15

All the above commands seek to approximately same position and start playback.

So apparently lack of end_of_stream packet does not prevent seeking. For my purposes I need to be able to use the absolute timestamp.

**Comment by jarnos** [comment]
As shown above some other players can seek the file just fine, but `mpc` cannot. So I think this issue should not be labeled as "bogus".

I tested again by Music Player Daemon 0.22.11 (0.22.11) and then mpc (version 0.33) just tells "MPD error: Not seekable".

**Comment by MaxKellermann** [comment]
It is bogus because you had a broken file, and I don't want to argue about spending my free time supporting broken data. I wasted so much time on supporting users with broken files and broken operating systems, and eventually decided life is too short for that; it is enough for me that MPD is a good software which runs on well-configured computers playing correct files.
You can decide to spend *your* free time on broken file support in MPD, and then submit a PR.

**Comment by jarnos** [comment]
https://wiki.xiph.org/OggOpus#Packet_Organization tells 

> The last page SHOULD have the 'end of stream' flag set, but implementations should be prepared to deal with truncated streams which do not have a page marked 'end of stream'.

That said, I am not sure, if MPD supports even properly segmented files whatever properly means in that.

Suppose you want to record some radio stream by `ffmpeg` and use segmentation with continuous timestamps to be able to seek to wanted position of the overall podcast. According to my experience **seeking the segment files does not work by `mpc`** (but I have not tried the latest version; and I used ffmpeg version 4.4.2).

Can you tell, if `ffmpeg` is broken in creating segmented files? You could create three sample files (in current directory) like this

`ffmpeg -i "https://stream.alandsradio.ax/stream.ogg" -c copy -t 25 -f segment -segment_time 10 -reset_timestamps 0 -strftime 1 test-record'-%FT%H%M%S%z'.opus`

Alternatively, you could use `-stream_segment` instead of `-segment` :

> stream_segment is a variant of the muxer used to write to streaming output formats, i.e. which do not require global headers, and is recommended for outputting e.g. to MPEG transport stream segments. ssegment is a shorter alias for stream_segment.

reference: https://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment

I do not know, if selection between these two makes a difference to how MPD should work.

In the above command recording is stopped automatically after 25 seconds. It may be that recording is stopped prematurely due to stream being (possibly temporarily) broken or due to user sending INT or TERM signal, for instance. It would be nice to be able to seek the recorded stream anyway. Otherwise the whole file might have to be re-processed. Does missing 'end of stream' metadata make seeking significantly more difficult?

**Comment by jarnos** [comment]
> But however it happens even when the start time is not zero. Here's the info of the file that bugs out for me:
> 
> ```
> start_time=0.007500

I suppose you meant even when the start time is (approximately) zero. I noticed that, too: I recorded an opus stream by ffmpeg using segmentation like above but with `-reset_timestamps 1` . Resulting files are not seekable by MPD. I don't know, if the files have end_of_stream packet or what is causing that issue with MPD. Should I post another bug report about that?
