### ISSUE TITLE
After upgrading to MPD 0.22, MPD dies on scanning db

### ISSUE THREAD

**Issue by shikitohno** [MusicPlayerDaemon/MPD#974]
### Describe the bug
Since upgrading to MPD 0.22 a couple of days ago, the MPD user service dies on attempting to scan the db.  If I remove the album "Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/" from ~/Music, MPD completes the scan and updates the db, but fails to read metadata in properly tagged files either displaying them as <empty> or producing gibberish output.  東京事変 becomes ?F?ʨ?., for example.  These files display correct file paths, and can be played fine displaying the same tag info MPD had prior to the upgrade in other media players, but attempting to play them in ncmpcpp produces "No such file" errors.

If the album "Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/" is added back to the music directory, MPD dies immediately on attempting to scan it.  This album posed no issues in prior versions of MPD, and nothing has been changed in my config.
## Expected Behavior
MPD should launch, scan the music directory and successfully add and display all properly tagged files.

## Actual Behavior
MPD dies on scanning some particular files, and when these are removed, properly tagged files fail to display metadata tags accurately.

## Version
Music Player Daemon 0.22 (0.22)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log
Oct 04 12:27:57 Shiki-home systemd[777]: Starting Music Player Daemon...
░░ Subject: A start job for unit UNIT has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has begun execution.
░░ 
░░ The job identifier is 2043.
Oct 04 12:27:57 Shiki-home mpd[12953]: Oct 04 12:27 : exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
Oct 04 12:27:57 Shiki-home mpd[12953]: Oct 04 12:27 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Oct 04 12:27:57 Shiki-home mpd[12953]: Oct 04 12:27 : exception: Failed to open '/home/baard/.config/mpd/database': No such file or directory
Oct 04 12:27:57 Shiki-home mpd[12953]: Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory
Oct 04 12:27:58 Shiki-home systemd[777]: mpd.service: Main process exited, code=killed, status=11/SEGV
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit UNIT has exited.
░░ 
░░ The process' exit code is 'killed' and its exit status is 11.
Oct 04 12:27:58 Shiki-home systemd[777]: mpd.service: Failed with result 'signal'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has entered the 'failed' state with result 'signal'.
Oct 04 12:27:58 Shiki-home systemd[777]: Failed to start Music Player Daemon.
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished with a failure.
░░ 
░░ The job identifier is 2043 and the job result is failed.
Oct 04 12:27:58 Shiki-home systemd-coredump[12958]: Process 12953 (mpd) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 12956:
                                                    #0  0x000056509a407a81 n/a (mpd + 0xe0a81)
                                                    #1  0x000056509a408050 n/a (mpd + 0xe1050)
                                                    #2  0x000056509a40d90a n/a (mpd + 0xe690a)
                                                    #3  0x000056509a40e6f4 n/a (mpd + 0xe76f4)
                                                    #4  0x000056509a40c793 n/a (mpd + 0xe5793)
                                                    #5  0x000056509a40e6f4 n/a (mpd + 0xe76f4)
                                                    #6  0x000056509a4053f3 n/a (mpd + 0xde3f3)
                                                    #7  0x000056509a3a36a4 n/a (mpd + 0x7c6a4)
                                                    #8  0x00007f3fc93c93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                    #9  0x00007f3fc70f8293 __clone (libc.so.6 + 0x100293)
                                                    
                                                    Stack trace of thread 12953:
                                                    #0  0x00007f3fc70f8e7b inotify_add_watch (libc.so.6 + 0x100e7b)
                                                    #1  0x000056509a40f9f5 n/a (mpd + 0xe89f5)
                                                    #2  0x000056509a40fb2d n/a (mpd + 0xe8b2d)
                                                    #3  0x000056509a377d76 n/a (mpd + 0x50d76)
                                                    #4  0x000056509a37918d n/a (mpd + 0x5218d)
                                                    #5  0x000056509a36f41c n/a (mpd + 0x4841c)
                                                    #6  0x00007f3fc7020152 __libc_start_main (libc.so.6 + 0x28152)
                                                    #7  0x000056509a36f71e n/a (mpd + 0x4871e)
                                                    
                                                    Stack trace of thread 12954:
                                                    #0  0x00007f3fc70f85de epoll_wait (libc.so.6 + 0x1005de)
                                                    #1  0x000056509a3a9bf6 n/a (mpd + 0x82bf6)
                                                    #2  0x000056509a3a36a4 n/a (mpd + 0x7c6a4)
                                                    #3  0x00007f3fc93c93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                    #4  0x00007f3fc70f8293 __clone (libc.so.6 + 0x100293)
                                                    
                                                    Stack trace of thread 12955:
                                                    #0  0x00007f3fc70f85de epoll_wait (libc.so.6 + 0x1005de)
                                                    #1  0x000056509a3a9bf6 n/a (mpd + 0x82bf6)
                                                    #2  0x000056509a3a36a4 n/a (mpd + 0x7c6a4)
                                                    #3  0x00007f3fc93c93e9 start_thread (libpthread.so.0 + 0x93e9)
                                                    #4  0x00007f3fc70f8293 __clone (libc.so.6 + 0x100293)
░░ Subject: Process 12953 (mpd) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 12953 (mpd) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.

Relevant section of ~/.config/mpd/log

Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/03. Si el Hombre Es Lo Que Ama.flac
Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/04. Entre Pobres.flac
Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/01. Nada Tengo Que Cuidar y Todo para Vivir.flac
Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/05. Dios Va Contigo a Todas Partes.flac
Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/02. Yo Vengo de Todo el Mundo.flac
Oct 04 12:27 : update: added Facundo Cabral - Canciones en Vivo [2016] [WEB - FLAC - 16-44]/06. Vuele Bajo.flac
Oct 04 12:27 : update: added Thiaguinho MT - Tudo Ok (Eudora Remix) [2020][WEB - FLAC - 16-44]/Thiaguinho MT - Tudo Ok (Eudora Remix).flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/06 Chamber of Sacred Ootheca.flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/01 Manor of Infinite Forms.flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/03 Abysswalker.flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/05 Gored Embrace (Confronting Biodegradation).flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/04 Final Struggle of Selves.flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/02 Blood Mirror.flac
Oct 04 12:27 : update: added Tomb Mold - Manor of Infinite Forms (2018)/07 Two Worlds Become One.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/01. Witches Hammer - Thulsa Doom.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/11. Witches Hammer - Final Storm.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/02. Witches Hammer - Rabid Captor.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/04. Witches Hammer - Gorgon.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/08. Witches Hammer - Legions of the Undead.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/05. Witches Hammer - Mantle of Death.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/10. Witches Hammer - National Front.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/07. Witches Hammer - I.N.R.I. - Gorgon.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/09. Witches Hammer - Deadly Mantis.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/03. Witches Hammer - Frozen God - Witches Hammer.flac
Oct 04 12:27 : update: added Witches Hammer - Canadian Speed Metal (2003) [FLAC]/06. Witches Hammer - Death of No Reprieve.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/03 Cichli.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/07 Montreal.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/05 Pule.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/06 Bike.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/02 Goz Quarter.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/01 Laughing Quarter.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/04 Basscadet.flac
Oct 04 12:27 : update: added Pink Freud - Pink Freud plays Autechre (2016) [FLAC]/08 Eggshell.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/02 - Click Bait.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/03 - Throw Your Heart Away.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/01 - Open Wound.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/08 - Pearlescent.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/07 - The Currency of Beauty.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/04 - Listen to Someone.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/05 - Silent Restraint.flac
Oct 04 12:27 : update: added Svalbard - When I Die, Will I Get Better_ - (2020) {WEB - FLAC}/06 - What Was She Wearing_.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/04 Malas Intenciones.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/12 Con Nombre de Guerra.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/01 Entre Dos Tierras.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/08 Hechizo.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/07 Héroe de Leyenda.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/11 Decadencia.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/03 La Carta.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/05 Sal.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/06 Senda.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/10 Despertar.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/09 Oración.flac
Oct 04 12:27 : update: added Heroes del Silencio - Senderos de Traición (1990) FLAC [1992 EMI Mexico]/02 Maldito Duende.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/A1 Odens Ride Over Nordland-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/A5 Holocaust-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/B2 Dies Irae-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/B3 Blood Fire Death-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/B1 For All Those Who Died-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/A4 Pace 'Til Death-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/A2 A Fine Day To Die-16bit.flac
Oct 04 12:27 : update: added Bathory [1988] [LP] Blood Fire Death [FLAC]/A3 The Golden Walls Of Heaven-16bit.flac
Oct 04 12:27 : update: added DJ Ari SL - Megafunk Da Maconha 2020 [WEB - FLAC - 16-44]/DJ Ari SL - Megafunk Da Maconha.flac
Oct 04 12:27 : update: added Sonido Gallo Negro - Chaneque - 2018/01. Chaneque.flac
Oct 04 12:27 : update: added Niack - Oh Juliana (Remix Brega Funk) [2020] [WEB - FLAC - 24-44]/01. Oh Juliana.flac
Oct 04 12:27 : update: added Lan Lahn - 100 Xurumela [2020] [WEB - FLAC -16-44]/Lan Lanh - 100 Xurumela.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/10 - Hail To The Bopp.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/03 - Book Of Shadows.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/14 - Wavy Line.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/04 - Oblivion  Humans.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/13 - The Thumb.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/07 - Acid Again.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/09 - Where Are You  Enuff.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/11 - 3 Floors Above You.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/06 - The Tweek.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/12 - Funny Feeling.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/01 - Everything's Under Control.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/05 - Let's Have Fun.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/08 - Let Go.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/15 - Wildlife.flac
Oct 04 12:27 : update: added Meat Beat Manifesto - Actual Sounds + Voices (1998) [flac] {BIAS 345 CD}/02 - Prime Audio Soup.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/06 - Sonero Mayor.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/01 - Che Che Cole.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/07 - Sangrigorda.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/04 - Te Conozco.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/05 - Juana Peña.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/03 - Ausencia.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/02 - No Me LLores Mas.flac
Oct 04 12:27 : update: added Willie Colon - Cosa Nuestra (1971) (2007 Pressing) [FLAC]/08 - Tu No Puedes Conmigo.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/08 Byakuya.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/02 Kibun Wo Kaete.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/05 Tender Rain.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/07 Shounen No Hi No Merry-Go-Round.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/01 Anata Wa Shocking Shine.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/10 Watashi Wa Ai Wo Utawanai.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/04 Kimagure Yohou.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/03 Perfect Game.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/06 Cosmic Blue.flac
Oct 04 12:27 : update: added (1978) Amii Ozaki (尾崎亜美) - Prismy {1993 EMI Music Japan RE} [WEB FLAC]/09 Temptation.flac
Oct 04 12:27 : update: added Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/05 - Kumiko Hara (原久美子) - ちょっと背のびを.flac
Oct 04 12:27 : update: added Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/02 - Kumiko Hara (原久美子) - 水の流れに.flac
Oct 04 12:27 : update: added Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/08 - Kumiko Hara (原久美子) - ほっといて.flac
Oct 04 12:27 : update: added Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/04 - Kumiko Hara (原久美子) - 恋は汽車のよう.flac
Oct 04 12:27 : update: added Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]/10 - Kumiko Hara (原久美子) - 耳もとかすめ.flac

**Comment by MaxKellermann** [comment]
I need a backtrace of the crash (with an unstripped MPD binary).

**Comment by nyanmeister** [comment]
I don't have the expertise to provide the full debug info, but I can confirm having a bug that seems like this after upgrading today as well.
`$ mpd`
`Failed to initialize io_uring: io_uring_queue_init() failed: Cannot allocate memory`

**Comment by MaxKellermann** [comment]
@nyanmeister your paste shows https://github.com/MusicPlayerDaemon/MPD/issues/972 which is your misconfiguration, but has nothing to do with this crash.

**Comment by shikitohno** [comment]
Rebuilt MPD with the options given in the [manual](https://www.musicpd.org/doc/html/user.html), and reproduced the crash in gdb.  Ran bt against the core dump and got this:

Shiki-home% gdb /usr/local/bin/mpd mpd022crash 
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/mpd...
[New LWP 54287]
[New LWP 54277]
[New LWP 54281]
[New LWP 54282]
[New LWP 54283]
[New LWP 54284]
[New LWP 54285]
[New LWP 54286]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/local/bin/mpd --no-daemon --stderr ~/.config/mpd/mpd.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  DetachedSong::SetStartTime (_value=..., this=0x0) at ../../src/song/DetachedSong.hxx:220
220                     start_time = _value;
[Current thread is 1 (Thread 0x7fffc3fff640 (LWP 54287))]
(gdb) bt
#0  DetachedSong::SetStartTime(SongTime) (_value=..., this=0x0) at ../../src/song/DetachedSong.hxx:220
#1  CueParser::Feed2(char*) (this=0x7fffbc00daf0, p=<optimized out>) at ../../src/playlist/cue/CueParser.cxx:261
#2  0x00005555556334a0 in CueParser::Feed(char const*) (this=0x7fffbc00daf0, line=<optimized out>) at ../../src/playlist/cue/CueParser.cxx:274
#3  0x0000555555630135 in CuePlaylist::NextSong() (this=0x7fffbc00cad0) at ../../src/playlist/plugins/CuePlaylistPlugin.cxx:53
#4  0x0000555555637a0f in UpdateWalk::UpdatePlaylistFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&, PlaylistPlugin const&) (this=0x7fffc3ffe468, parent=..., name=..., info=..., plugin=...)
    at /usr/include/c++/10.2.0/bits/unique_ptr.h:421
#5  0x0000555555637d8f in UpdateWalk::UpdatePlaylistFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, char const*, StorageFileInfo const&)
    (this=0x5555559c41e0, directory=..., name="No Smoking.cue", suffix=<optimized out>, info=...) at ../../src/db/update/Playlist.cxx:99
#6  0x00005555556368ce in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) (this=0x5555559c41e0, directory=..., exclude_list=..., info=...) at ../../src/db/update/Walk.cxx:361
#7  0x0000555555636b29 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&)
    (this=0x5555559c41e0, directory=..., exclude_list=..., name=0x7fffbc0091d0 "Kumiko Hara (原久美子) - (1978) No Smoking {Universal PROT-1060 CD RE} [FLAC]", info=...) at ../../src/db/update/Walk.cxx:211
#8  0x00005555556368ce in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) (this=0x5555559c41e0, directory=..., exclude_list=..., info=...) at ../../src/db/update/Walk.cxx:361
#9  0x0000555555636f41 in UpdateWalk::Walk(Directory&, char const*, bool) (this=0x5555559c41e0, root=..., path=<optimized out>, discard=<optimized out>) at ../../src/db/update/Walk.cxx:486
#10 0x0000555555634666 in UpdateService::Task() (this=0x55555574d800) at ../../src/db/plugins/simple/SimpleDatabasePlugin.hxx:85
#11 BindMethodDetail::BindMethodWrapperGenerator2<UpdateService, true, void (UpdateService::*)() noexcept, &UpdateService::Task, void>::Invoke(void*) (_instance=0x55555574d800) at ../../src/util/BindMethod.hxx:189
#12 0x00005555555d764d in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../../src/util/BindMethod.hxx:90
#13 Thread::Run() (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#14 Thread::ThreadProc(void*) (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#15 0x00007ffff55cb3e9 in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007ffff3365293 in clone () at /usr/lib/libc.so.6


@MaxKellermann is that sufficient, or do I need to redo it in some other way?  Sorry if it's not what you needed, first time submitting a bug report/attempting to backtrace anything.

**Comment by MaxKellermann** [comment]
This is a bug in the CUE parser. Can you upload the file `No Smoking.cue`? That file might help to reproduce the problem.

**Comment by shikitohno** [comment]
Github complained about a .cue file, so it's zipped, but here it is.

Let me know if there's anything else needed.

[No Smoking.zip](https://github.com/MusicPlayerDaemon/MPD/files/5327974/No.Smoking.zip)

**Comment by MaxKellermann** [comment]
That file is indeed broken in an interesting way, which causes MPD to crash. That is a bug which needs to be fixed - MPD must never crash, no matter how broken a file is.

**Comment by MaxKellermann** [comment]
I wrote a fuzzer for the CUE parser, and it found this bug after a few milliseconds. Sigh. I should have fuzzed this piece of code earlier!
