### ISSUE TITLE
Opus replaygain not falling back to available tag if the tag for the enabled mode is missing

### ISSUE THREAD

**Issue by kartikynwa** [MusicPlayerDaemon/MPD#977]
### Describe the bug

Here are the files I tested it with: [electric_feel.zip](https://github.com/MusicPlayerDaemon/MPD/files/5371598/electric_feel.zip)

`electric_feel_album.opus` only has the `R128_ALBUM_GAIN` tag. `electric_feel_track.opus` only has `R128_TRACK_GAIN`.

Here is my conf: [mpd.conf](http://ix.io/2AAj)

When `replaygain` is set to `album`, playing `electric_feel_track.opus` results in `R128_TRACK_GAIN` not being applied, but `replaygain_preamp` from `mpd.conf` seems to be applied. So the audio gets very loud with noticeable clippings. Same thing happens when replaygain mode is set to `track` and `electric_feel_album.opus`is played. When set to `auto`, the same thing happens when `random` is off and `electric_feel_track.opus` is played, and with `random` on, `electric_feel_album.opus` produces the same effect.

## Expected Behavior

mpd should be falling back to the available replaygain tag if the one for the selected mode is missing. This happens for mp3 files but not opus.

## Version
`Music Player Daemon 0.22 (0.22)`

## Log
http://ix.io/2AAB

This is the log running the following commands:

``` bash
mpd --verbose
mpc add electric_feel/electric_feel_track.opus
mpc play
```
The replaygain mode was set to album.

Log file when playing `electric_feel_album.opus`: http://ix.io/2AAH

**Comment by MaxKellermann** [comment]
Bug was caused by https://github.com/MusicPlayerDaemon/MPD/commit/23d5a2b8620cea69958d087fc7e13fe1e5adb83d (by @awused) which always applied `output_gain`, but this broke the MPD fallback feature, because track & album gain now always had a defined value.

**Comment by kartikynwa** [comment]
That was very fast. Thanks a ton!
