### ISSUE TITLE
Opus (httpd) Output Gain distorts after playing one song, possibly ignores replay gain setting too

### ISSUE THREAD

**Issue by waffshappen** [MusicPlayerDaemon/MPD#980]
### Describe the bug
My entire music library is encoded in opus with ffmpeg/libopus 1.3

Whenever i start mpd and start playback 
(opus in -> opus out via http stream straight from mpd)
it works for __one__ track. As soon as it switches to the next it becomes far too loud and distorts, but normalized.

I know that a fix for something similar went in recently. However i am using
http://koji.rpmfusion.org/koji/buildinfo?buildID=16862
and i am not sure if that specific fix is in there yet, since its version matches the latest release.

I have also set replaygain to disabled and to limit, but it did not help.

## Expected Behavior
When playing opus tracks via opus stream it should not suddenly distort

## Actual Behavior
Massive distortion occurs, but only from the second track on.

Note: i have not tried any other source format.

## Config
<details>
<summary>Relevant Config bits</summary>
<p>

```
audio_output {
        type                "httpd"
        name                "Opus 192k"
        encoder             "opus"
        port                "XXXX"
        bitrate             "192000"
        signal              "music"
        opustags            "yes"
        format              "48000:16:2"
        always_on           "yes"
        tags                "yes"
        complexity          "10"
}

# Neither replaygain auto nor off make a difference
replaygain                  "off"
replaygain_preamp           "0"
replaygain_missing_preamp   "0"
replaygain_limit            "yes"
volume_normalization        "no"


```
</p>
</details>  

## Version

<details>
<summary>mpd -V</summary>
<p>

```
Music Player Daemon 0.22.1 (0.22.1)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```
</p>
</details>  

## Log

<details>
<summary>Verbose Log</summary>
<p>

```
$time : client: [0] process command "next"
$time : playlist: play 1:"$randomsonghere.opus"
$time : decoder_thread: probing plugin opus
$time : decoder: audio_format=48000:16:2, seekable=true
$time : client: [0] command returned 0
$time : playlist: queue song 2:"$randomsonghere.opus"
$time : replay_gain: scale=1.778279
$time : replay_gain: scale=1.778279
$time : replay_gain: scale=1.778279
$time : client: [0] process command "status"
$time : client: [0] command returned 0
$time : client: [0] process command "replay_gain_status"
$time : client: [0] command returned 0                                                                                                                          
$time : client: [1] process command "idle"
$time : client: [1] command returned 1                                                                                                                          
$time : client: [0] process command "currentsong"                                                                                                               
$time : client: [0] command returned 0
$time : client: [0] process command "seekid "245" "65""
$time : playlist: queue song 2:"$randomsonghere.opus"
$time : client: [0] command returned 0
$time : client: [0] process command "status"
$time : client: [0] command returned 0
$time : client: [0] process command "replay_gain_status"
$time : client: [0] command returned 0
$time : client: [1] process command "idle"
$time : client: [1] command returned 1
$time : client: [0] process command "status"
$time : client: [0] command returned 0
$time : client: [0] process command "seekid "245" "124""
$time : playlist: queue song 2:"$randomsonghere.opus"
$time : client: [0] command returned 0
$time : client: [0] process command "status"
$time : client: [0] command returned 0
$time : client: [0] process command "replay_gain_status"
$time : client: [0] command returned 0
$time : client: [1] process command "idle"
$time : client: [1] command returned 1
$time : output: closed "Opus 320k" (httpd)
$time : output: closed "Opus 192k" (httpd)
$time : output: closed "Opus 36k" (httpd)
```
</p>
</details>

**Comment by MaxKellermann** [comment]
Your log shows that you enabled ReplayGain. What does `mpc replaygain` say?

**Comment by waffshappen** [comment]
> mpc replaygain

mpc replaygain
replay_gain_mode: off

**Comment by MaxKellermann** [comment]
This is not consistent. Your log shows ReplayGain is enabled, but your latest paste shows it's not. Both cannot be true at the same time.
Can you reproduce the problem while mpc shows it's "off"? Is it still "off" while the problem is audible?

**Comment by waffshappen** [comment]
> This is not consistent. Your log shows ReplayGain is enabled, but your latest paste shows it's not. Both cannot be true at the same time.
> Can you reproduce the problem while mpc shows it's "off"? Is it still "off" while the problem is audible?

Yes, it is audibly distorting right now, across all 3 configured outputs (320k/192k/36k opus), the file played directly is perfectly fine, systemctl restart mpd and it works but switching a single track and it goes back to distorting.

My config is still 1:1 as above, "no replaygain".

**Comment by MaxKellermann** [comment]
You did not answer my questions. I rephrase: what does `mpc replaygain` print while you reproduce the problem? Be very specific.
So far, you described the problem, and you said what `mpc replaygain` prints at some random point in time, but we need to pinpoint it both at one time.

**Comment by waffshappen** [comment]
> You did not answer my questions. I rephrase: what does `mpc replaygain` print while you reproduce the problem? Be very specific.
> So far, you described the problem, and you said what `mpc replaygain` prints at some random point in time, but we need to pinpoint it both at one time.

I just noticed, Cantata auto-sets it to "auto" after a while. That is the moment distortion starts. Sneaky, but that is where the replaygain enable seems to come from.

**Comment by MaxKellermann** [comment]
WTF Cantata!

**Comment by MaxKellermann** [comment]
> However, i should be on a "fixed" version with the patch for distortion according to the rpmfusion version number?

I know of no such patch.

Your log shows that MPD calculates a scale of 1.7. That sounds like a lot (more than 1.0!), and could cause clipping. Maybe the ReplayGain values of your Opus files are wrong.

Until you demonstrate that your Opus files are correctly tagged, I'll assume that this is a combination of an annoying Cantata mis-feature and broken Opus files.

**Comment by waffshappen** [comment]
> > However, i should be on a "fixed" version with the patch for distortion according to the rpmfusion version number?
> 
> I know of no such patch.

mediainfo reports 0 tags related to replaygain on the file, so possibly hit by
#976 

> Your log shows that MPD calculates a scale of 1.7. That sounds like a lot (more than 1.0!), and could cause clipping. Maybe the ReplayGain values of your Opus files are wrong.

Exactly, but i thought the patch for replay-gain less opus files was already in.

> Until you demonstrate that your Opus files are correctly tagged, I'll assume that this is a combination of an annoying Cantata mis-feature and broken Opus files.

mediainfo --Full *.opus | grep -i gain (or replay) shows nothing.

Atleast cantata lets me disable for now.
Closing for now until i'm 100% certain 976 is in and re-checking then.
