### ISSUE TITLE
yajl errors contain trailing newlines

### ISSUE THREAD

**Issue by arcnmx** [MusicPlayerDaemon/MPD#981]
### Describe the bug

`mpc status` fails to decode the response from MPD when the current error contains a trailing newline. It's not clear to me whether this is a bug in mpd (emitted errors should not contain newlines in the protocol?) or libmpdclient (it should be able to parse/ignore newlines?). Note that this appears to be intentional on yajl's part: https://github.com/lloyd/yajl/issues/227

## Expected Behavior

`mpc` displays the error message

## Actual Behavior

`mpc` exits with an error `Failed to parse MPD response`

## Version

mpd 0.22
mpc 0.33
libmpdclient 2.19

**Comment by MaxKellermann** [comment]
True, newlines must be stripped out of any error messages received from libraries MPD calls.
