### ISSUE TITLE
Make it possible to disable CuePlaylistPlugin in configuration

### ISSUE THREAD

**Issue by pjanx** [MusicPlayerDaemon/MPD#988]
## Feature request
CuePlaylistPlugin gets extremely annoying when the referenced files do not exist and you're not in a position to delete the CUE file.

Either make it possible to disable it in the configuration, or make it check filenames.

Thanks.

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/doc/html/user.html#configuring-playlist-plugins

**Comment by guillermofbriceno** [comment]
Did adding the playlist_plugin block to disable the cue plugin work for you @pjanx ? I've updated and rescanned my database and the cue tracks are still there.

**Comment by pjanx** [comment]
I actually haven't checked until now but yes, no more virtual directories.

```
playlist_plugin {
	name "cue"
	enabled "false"
}
```

Originally I went immediately after a/ the example config, b/ the source code, and couldn't find anything relevant in either place within an hour or so.
