### ISSUE TITLE
clarify `mixer_type` deprecation

### ISSUE THREAD

**Issue by matthewleon** [MusicPlayerDaemon/MPD#99]
Comments in the source indicate that the `mixer_type` configuration setting is deprecated. For example: https://github.com/MusicPlayerDaemon/MPD/blob/a257504ba4bbc9ae1c45b0b87a8f771b1d5b2193/src/output/Init.cxx#L84

The `mpd.conf` documentation, however, does not mention this. Can the situation be clarified in the docs?

**Comment by MaxKellermann** [comment]
You're confusing two different things: the **global** `mixer_type` option (which is deprecated), and the per-output `mixer_type` option (which is not).

**Comment by matthewleon** [comment]
Thank you for the clarification.
