### ISSUE TITLE
Crash while parsing malformed cue file

### ISSUE THREAD

**Issue by Waffl3x** [MusicPlayerDaemon/MPD#990]
### Describe the bug
Crash when parsing malformed cue file 
related cue file can be found here https://termbin.com/gdln

The crash occurs even when it is the only file being read.

Note: The smallest portion I could get to still crash was lines 30 to 61, it might have been able to get smaller while still crashing though.
What is interesting is fixing line 53 (removing the line break) avoids the crash completely without any other changes, however if I have just lines 44 to 61 WITHOUT fixing line 53, it also will not crash. I'm just guessing but this seems to suggest it's a ripple effect of many small errors in the cue file that caused it.

## Expected Behavior
Gracefully fail

## Actual Behavior
Crashes (Segmentation fault)

## Version

waffl3x@flex-kubuntu20-10:~$ mpd --version
Music Player Daemon 0.22 (0.22)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy

Storage plugins:
 local

Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate

Tag plugins:

Output plugins:
 null fifo pipe oss pulse jack httpd recorder

Encoder plugins:
 null vorbis opus wave flac

Input plugins:
 file ffmpeg

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// ftp:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// sftp:// srtp://

Other features:
 epoll icu inotify ipv6 systemd tcp un

## Log

[New Thread 0x7fffeb82f640 (LWP 24489)]
update: starting
update: spawned thread for update job id 1
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
update: removing MEGA YABAICORE.cue/track0001
update: removing MEGA YABAICORE.cue/track0007
update: removing MEGA YABAICORE.cue/track0006
update: scanning playlist '/home/waffl3x/Music/test/MEGA YABAICORE.cue'
update: removing MEGA YABAICORE.cue/track0005
update: removing MEGA YABAICORE.cue/track0004
update: removing MEGA YABAICORE.cue/track0003
update: removing MEGA YABAICORE.cue/track0002

Thread 4 "update" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb82f640 (LWP 24489)]
0x00005555555ab658 in DetachedSong::SetStartTime (this=0x0, _value=...) at ../../src/song/DetachedSong.hxx:220
220                     start_time = _value;
(gdb) thread apply all bt

Thread 4 (Thread 0x7fffeb82f640 (LWP 24489)):
#0  0x00005555555ab658 in DetachedSong::SetStartTime(SongTime) (this=0x0, _value=...) at ../../src/song/DetachedSong.hxx:220
#1  0x00005555556645ec in CueParser::Feed2(char*) (this=0x7fffdc00a1b0, p=0x7fffdc00a836 "") at ../../src/playlist/cue/CueParser.cxx:261
#2  0x0000555555664700 in CueParser::Feed(char const*) (this=0x7fffdc00a1b0, line=0x7fffdc0097c9 "    INDEX 01 00:00:00") at ../../src/playlist/cue/CueParser.cxx:274
#3  0x00005555556600eb in CuePlaylist::NextSong() (this=0x7fffdc009190) at ../../src/playlist/plugins/CuePlaylistPlugin.cxx:53
#4  0x000055555566ef54 in UpdateWalk::UpdatePlaylistFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&, PlaylistPlugin const&) (this=0x555555802350, parent=..., name="MEGA YABAICORE.cue", info=..., plugin=...) at ../../src/db/update/Playlist.cxx:67
#5  0x000055555566f2ba in UpdateWalk::UpdatePlaylistFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, char const*, StorageFileInfo const&) (this=0x555555802350, directory=..., name="MEGA YABAICORE.cue", suffix=0x7fffdc008fbf "cue", info=...) at ../../src/db/update/Playlist.cxx:99
#6  0x000055555566c222 in UpdateWalk::UpdateRegularFile(Directory&, char const*, StorageFileInfo const&) (this=0x555555802350, directory=..., name=0x7fffdc008fb0 "MEGA YABAICORE.cue", info=...) at ../../src/db/update/Walk.cxx:186
#7  0x000055555566ab18 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) (this=0x555555802350, directory=..., exclude_list=..., name=0x7fffdc008fb0 "MEGA YABAICORE.cue", info=...) at ../../src/db/update/Walk.cxx:197
#8  0x000055555566b558 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) (this=0x555555802350, directory=..., exclude_list=..., info=...) at ../../src/db/update/Walk.cxx:361
#9  0x000055555566b89b in UpdateWalk::Walk(Directory&, char const*, bool) (this=0x555555802350, root=..., path=0x5555557e58e0 "", discard=false) at ../../src/db/update/Walk.cxx:486
#10 0x0000555555668a61 in UpdateService::Task() (this=0x5555557e5830) at ../../src/db/update/Service.cxx:123
#11 0x000055555566966d in BindMethodDetail::BindMethodWrapperGenerator2<UpdateService, true, void (UpdateService::*)() noexcept, &UpdateService::Task, void>::Invoke(void*) (_instance=0x5555557e5830) at ../../src/util/BindMethod.hxx:189
#12 0x00005555555f210e in BoundMethod<void () noexcept>::operator()() const (this=0x5555557e5880) at ../../src/util/BindMethod.hxx:91
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00005555555f78b0 in Thread::Run() (this=0x5555557e5880) at ../../src/thread/Thread.cxx:63
#14 0x00005555555f788d in Thread::ThreadProc(void*) (ctx=0x5555557e5880) at ../../src/thread/Thread.cxx:92
#15 0x00007ffff5420590 in start_thread (arg=0x7fffeb82f640) at pthread_create.c:463
#16 0x00007ffff5346223 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffec030640 (LWP 24486)):
#0  0x00007ffff534656e in epoll_wait (epfd=8, events=0x7fffffffd9d8, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00005555555f1710 in EpollFD::Wait(epoll_event*, int, int) (this=0x7fffffffd9d4, events=0x7fffffffd9d8, maxevents=16, timeout=-1) at ../../src/system/EpollFD.hxx:55
#2  0x00005555555f18df in PollGroupEpoll::ReadEvents(PollResultEpoll&, int) (this=0x7fffffffd9d4, result=..., timeout_ms=-1) at ../../src/event/PollGroupEpoll.hxx:75
#3  0x00005555555f10cf in EventLoop::Run() (this=0x7fffffffd940) at ../../src/event/Loop.cxx:232
#4  0x00005555555f0532 in EventThread::Run() (this=0x7fffffffd940) at ../../src/event/Thread.cxx:65
#5  0x000055555559ce38 in BindMethodDetail::BindMethodWrapperGenerator2<EventThread, true, void (EventThread::*)() noexcept, &EventThread::Run, void>::Invoke(void*) (_instance=0x7fffffffd940) at ../../src/util/BindMethod.hxx:189
#6  0x00005555555f210e in BoundMethod<void () noexcept>::operator()() const (this=0x7fffffffdaa8) at ../../src/util/BindMethod.hxx:91
#7  0x00005555555f78b0 in Thread::Run() (this=0x7fffffffdaa8) at ../../src/thread/Thread.cxx:63
#8  0x00005555555f788d in Thread::ThreadProc(void*) (ctx=0x7fffffffdaa8) at ../../src/thread/Thread.cxx:92
#9  0x00007ffff5420590 in start_thread (arg=0x7fffec030640) at pthread_create.c:463
#10 0x00007ffff5346223 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffec831640 (LWP 24485)):
#0  0x00007ffff534656e in epoll_wait (epfd=6, events=0x7fffffffd848, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00005555555f1710 in EpollFD::Wait(epoll_event*, int, int) (this=0x7fffffffd844, events=0x7fffffffd848, maxevents=16, timeout=-1) at ../../src/system/EpollFD.hxx:55
--Type <RET> for more, q to quit, c to continue without paging--
#2  0x00005555555f18df in PollGroupEpoll::ReadEvents(PollResultEpoll&, int) (this=0x7fffffffd844, result=..., timeout_ms=-1) at ../../src/event/PollGroupEpoll.hxx:75
#3  0x00005555555f10cf in EventLoop::Run() (this=0x7fffffffd7b0) at ../../src/event/Loop.cxx:232
#4  0x00005555555f0532 in EventThread::Run() (this=0x7fffffffd7b0) at ../../src/event/Thread.cxx:65
#5  0x000055555559ce38 in BindMethodDetail::BindMethodWrapperGenerator2<EventThread, true, void (EventThread::*)() noexcept, &EventThread::Run, void>::Invoke(void*) (_instance=0x7fffffffd7b0) at ../../src/util/BindMethod.hxx:189
#6  0x00005555555f210e in BoundMethod<void () noexcept>::operator()() const (this=0x7fffffffd918) at ../../src/util/BindMethod.hxx:91
#7  0x00005555555f78b0 in Thread::Run() (this=0x7fffffffd918) at ../../src/thread/Thread.cxx:63
#8  0x00005555555f788d in Thread::ThreadProc(void*) (ctx=0x7fffffffd918) at ../../src/thread/Thread.cxx:92
#9  0x00007ffff5420590 in start_thread (arg=0x7fffec831640) at pthread_create.c:463
#10 0x00007ffff5346223 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fffece4b340 (LWP 24481)):
#0  0x00007ffff534656e in epoll_wait (epfd=4, events=0x7fffffffd6e0, maxevents=16, timeout=60000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00005555555f1710 in EpollFD::Wait(epoll_event*, int, int) (this=0x7fffffffd6dc, events=0x7fffffffd6e0, maxevents=16, timeout=60000) at ../../src/system/EpollFD.hxx:55
#2  0x00005555555f18df in PollGroupEpoll::ReadEvents(PollResultEpoll&, int) (this=0x7fffffffd6dc, result=..., timeout_ms=60000) at ../../src/event/PollGroupEpoll.hxx:75
#3  0x00005555555f10cf in EventLoop::Run() (this=0x7fffffffd648) at ../../src/event/Loop.cxx:232
#4  0x0000555555574f4a in MainConfigured(options const&, ConfigData const&) (options=..., raw_config=...) at ../../src/Main.cxx:530
#5  0x0000555555575160 in MainOrThrow(int, char**) (argc=5, argv=0x7fffffffdf48) at ../../src/Main.cxx:606
#6  0x000055555557520d in mpd_main(int, char**) (argc=5, argv=0x7fffffffdf48) at ../../src/Main.cxx:614
#7  0x000055555557529c in main(int, char**) (argc=5, argv=0x7fffffffdf48) at ../../src/Main.cxx:628

**Comment by MaxKellermann** [comment]
Your MPD version is outdated.
