### ISSUE TITLE
cue-file not parsed correctly

### ISSUE THREAD

**Issue by MPconta** [MusicPlayerDaemon/MPD#992]
### Describe the bug
When i have a cue-file in my music library, the songs which are included in the cue-file show up doubled in the client. (MPDroid in my case)

## Expected Behavior
The songs in the cue-file should be shown only once, as it is meant.

## Actual Behavior
The songs are shown doubled

## Version

0.23 (git-version)

## Log

The log-file is not really useful in this case.
What i want to playback is a flac-file of a whole album without any tags. In addition to this there is a cuefile in the same directory, which looks like this:

REM GENRE aaa
REM DATE 1969
REM COMMENT spezielle Testversion 2019
PERFORMER "Josefus"
TITLE "Get Off My Case"
FILE "Josefus - Get Off My Case.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Crazy Man"
    PERFORMER "Josefus"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Country Boy"
    PERFORMER "Josefus"
    INDEX 01 03:43:32
  TRACK 03 AUDIO
    TITLE "Get Off My Case"
    PERFORMER "Josefus"
    INDEX 01 07:01:15
  TRACK 04 AUDIO
    TITLE "A Social Song"
    PERFORMER "Josefus"
    INDEX 01 11:01:00
  TRACK 05 AUDIO
    TITLE "Feelin' Good"
    PERFORMER "Josefus"
    INDEX 01 13:36:12
  TRACK 06 AUDIO
    TITLE "Situation"
    PERFORMER "Josefus"
    INDEX 01 19:41:15
  TRACK 07 AUDIO
    TITLE "Dead Man"
    PERFORMER "Josefus"
    INDEX 01 21:56:17

The entry in the tag_cache is the following:

directory: josefus
mtime: 1569608519
begin: _test/josefus
directory: Josefus - Get Off My Case.cue
type: playlist
mtime: 1604081060
begin: _test/josefus/Josefus - Get Off My Case.cue
song_begin: track0001
Target: ../Josefus - Get Off My Case.flac
Range: 0-223426
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 01
Title: Crazy Man
Artist: Josefus
song_end
song_begin: track0002
Target: ../Josefus - Get Off My Case.flac
Range: 223426-421200
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 02
Title: Country Boy
Artist: Josefus
song_end
song_begin: track0003
Target: ../Josefus - Get Off My Case.flac
Range: 421200-661000
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 03
Title: Get Off My Case
Artist: Josefus
song_end
song_begin: track0004
Target: ../Josefus - Get Off My Case.flac
Range: 661000-816160
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 04
Title: A Social Song
Artist: Josefus
song_end
song_begin: track0005
Target: ../Josefus - Get Off My Case.flac
Range: 816160-1181200
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 05
Title: Feelin' Good
Artist: Josefus
song_end
song_begin: track0006
Target: ../Josefus - Get Off My Case.flac
Range: 1181200-1316226
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 06
Title: Situation
Artist: Josefus
song_end
song_begin: track0007
Target: ../Josefus - Get Off My Case.flac
Range: 1316226-
Genre: aaa
Date: 1969
Comment: spezielle
AlbumArtist: Josefus
Album: Get Off My Case
Track: 07
Title: Dead Man
Artist: Josefus
song_end
end: _test/josefus/Josefus - Get Off My Case.cue
song_begin: Josefus - Get Off My Case.flac
Time: 2256.360000
mtime: 1535371964
song_end
playlist_begin: Josefus - Get Off My Case.cue
mtime: 1604081060
playlist_end
end: _test/josefus

It seems, the last 8 lines in the tag_cache are more or less redundant and couse the douplication of the presented songs?!

**Comment by MPconta** [comment]
Please tell me, if i could provide additional infos.

**Comment by MaxKellermann** [comment]
It's a feature, not a bug™
What you see is a MPD 0.22 feature showing contents of CUE files as a virtual directory, see https://github.com/MusicPlayerDaemon/MPD/issues/39 for the feature request. You can disable this feature by disabling the CUE playlist plugin completely, or by disabling its `as_directory` setting, see https://www.musicpd.org/doc/html/user.html#configuring-playlist-plugins
