### ISSUE TITLE
httpd "always-on" not working in partitions

### ISSUE THREAD

**Issue by Stapper** [MusicPlayerDaemon/MPD#994]
### Describe the bug
When moving a httpd output with the "always_on" option to a partition, the stream is not always on. It gets closed when playback is stopped.

## Expected Behavior
The stream should go silent, but should not close

## Actual Behavior
stream is stopped
## Version
Music Player Daemon 0.22.2 (0.22.2)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log
Log of my actions:
* connect move output from partition to default
* start playback
* stop playback => output is not stopped in this instance (as expected)
* go to Partition "test" and move the output to this partition
* start playback
* stop playback => output is also stopped (not as expected)
```
Nov 03 10:07 : client: [6] opened from 127.0.0.1:54474
Nov 03 10:07 : client: [6] process command "moveoutput 0" 
Nov 03 10:07 : client: [6] command returned 3
Nov 03 10:07 : client: [6] process command "moveoutput Sorad_Reserved_0"
Nov 03 10:07 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "stop"
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "play"
Nov 03 10:08 : playlist: play 0:"local/Gorillaz/Gorillaz (2001)/02 5_4.mp3"
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : decoder_thread: probing plugin mad
Nov 03 10:08 : playlist: queue song 1:"local/Gorillaz/Gorillaz (2001)/03 Tomorrow Comes Today.mp3"
Nov 03 10:08 : mad: detected LAME version 3.99 ("LAME3.99r")
Nov 03 10:08 : mad: LAME peak found: 0.000000
Nov 03 10:08 : mad: encoder delay is 576, encoder padding is 1552
Nov 03 10:08 : decoder: audio_format=44100:24:2, seekable=true
Nov 03 10:08 : output: opened "Sorad_Reserved_0" (httpd) audio_format=44100:16:2
Nov 03 10:08 : output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:16:2
Nov 03 10:08 : replay_gain: replay gain mode has changed off->track
Nov 03 10:08 : replay_gain: scale=1.000000
Nov 03 10:08 : client: [6] process command "stop"
Nov 03 10:08 : playlist: stop
Nov 03 10:08 : player: played "local/Gorillaz/Gorillaz (2001)/02 5_4.mp3"
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "partition test"
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "stop"
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "moveoutput Sorad_Reserved_0"
Nov 03 10:08 : output: closed "Sorad_Reserved_0" (httpd)
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : client: [6] process command "play"
Nov 03 10:08 : playlist: play 0:"local/IDLES - MR.MOTIVATOR.mp3"
Nov 03 10:08 : decoder_thread: probing plugin mad
Nov 03 10:08 : client: [6] command returned 0
Nov 03 10:08 : playlist: queue song 1:"local/03 Mr. Motivator.mp3"
Nov 03 10:08 : decoder: audio_format=48000:24:2, seekable=true
Nov 03 10:08 : output: opened "Sorad_Reserved_0" (httpd) audio_format=44100:16:2
Nov 03 10:08 : libsamplerate: setting samplerate conversion ratio to 0.92
Nov 03 10:08 : output: converting in=48000:24:2 -> f=48000:24:2 -> out=44100:16:2
Nov 03 10:09 : client: [6] process command "stop"
Nov 03 10:09 : playlist: stop
Nov 03 10:09 : player: played "local/IDLES - MR.MOTIVATOR.mp3"
Nov 03 10:09 : output: closed "Sorad_Reserved_0" (httpd)
Nov 03 10:09 : client: [6] command returned 0
```

**Comment by Stapper** [comment]
It looks like replay_gain_mode also needs to be set again.
Moving an output to a partition seems to reset some options to default

**Comment by Stapper** [comment]
Ok I think I pinpointed where the issue is.
If I read this correctly a new <AudioOutputControl> is created, which holds the "always_on" property set to false by default. Then the output, which does'nt have the "always_on" property is moved into the freshly created <AudioOutputControl>.

```
MultipleOutputs::Add(std::unique_ptr<FilteredAudioOutput> output,
		     bool enable) noexcept
{
	// TODO: this operation needs to be protected with a mutex
	outputs.emplace_back(std::make_unique<AudioOutputControl>(std::move(output),
								  client));
```

So any ideas on how to fix this?

**Comment by Stapper** [comment]
fixed by adding new AudioOutputControl constructor in `src/output/control`

```cpp
AudioOutputControl::AudioOutputControl(AudioOutputControl *_output,
				       AudioOutputClient &_client) noexcept
	:output(std::move(_output->Steal())),
	 tags(_output->tags),
	 always_on(_output->always_on),
	 name(output->GetName()),
	 client(_client),
	 thread(BIND_THIS_METHOD(Task))
{
}
```
And adding a AddCopy function to MultipleOutputs Class `src/output/MulitpleOutputs`
```cpp
void
MultipleOutputs::AddCopy(AudioOutputControl *outputControl,
		     bool enable) noexcept
{
	// TODO: this operation needs to be protected with a mutex
	outputs.emplace_back(std::make_unique<AudioOutputControl>(outputControl,
								  client));

	outputs.back()->LockSetEnabled(enable);

	client.ApplyEnabled();
}
```
So when calling `handle_moveoutput` AddCopy() is used in stead of Add() in `src/command/PartitionCommands`
```
dest_partition.outputs.AddCopy(output,was_enabled);
```

I'm not a c++ programmer, so this is probably a horrible solution, but it seems to work

**Comment by MaxKellermann** [comment]
Excellent analysis - and your idea to fix this looks good. Can you turn this into a PR for branch v0.22.x?

**Comment by Stapper** [comment]
Sure, I 'll try to send one by the end of this week.
