### ISSUE TITLE
mpd 0.22 has issues being cross compiled

### ISSUE THREAD

**Issue by neheb** [MusicPlayerDaemon/MPD#997]
### Describe the bug

For some reason, cross compilation is using the build compiler and not the target one

## Version
0.22.3. Actually all of the 0.22.x series. 0.21.x worked fine.

## Log
Small section
```
Using 'PKG_CONFIG_PATH' from environment with value: '/home/mangix/devstuff/openwrt/staging_dir/target-powerpc_464fp_musl/usr/lib/pkgconfig:/home/mangix/devstuff/openwrt/staging_dir/target-powerpc_464fp_musl/usr/share/pkgconfig'
Run-time dependency libmpdclient found: YES 2.19
Configuring config.h using configuration
Build targets in project: 62

Found ninja-1.10.1 at /home/mangix/devstuff/openwrt/staging_dir/hostpkg/bin/ninja

ERROR: C++ Compiler does not support -std=c++17
```

The host compiler is GCC 4.8.2 (CentOS7). The target one is GCC 10.2.0.

**Comment by MaxKellermann** [comment]
MPD compiles one executable with the host compiler, whose output will then be used in the rest of the build process. So yes, you need a C++17 host compiler!

**Comment by neheb** [comment]
That's inaccurate. Even when I fixed the configure issue, it still builds the binaries (or tries to) with the host compiler. I know because it errors with cannot find <string_view>

**Comment by neheb** [comment]
Hmm maybe it is...

```
~/d/o/b/t/m/m/i/m/u/bin (master)> ldd mpd
        not a dynamic executable
```

The fact that ldd fails indicates it's cross compiled.
